### ISSUE TITLE
Make comment section collapsible and different font/style than main content

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#1002]
- [x] This is a feature request.

## Environment informations
- **Minimal Mistakes version:** I don't know how to tell, [here](https://github.com/asarkar/asarkar.github.io) is my Github
- **`github-pages`**: 

---

## Expected behavior

Thanks for making this awesome theme available. Traffic to my blog is picking up, as well as comments. Currently, the comments are displayed in the same font and style as the main content, which IMHO, is a little distracting, and also ends up taking up some space at the bottom (case in point, http://blog.abhijitsarkar.org/technical/netflix-eureka/).
Thus, I'm making a couple of feature requests:

1. Collapse the comment section until someone expands it.
2. Use a different font, preferably smaller than the content, and style, for the comments.

**Comment by mmistakes** [comment]
The styling you can easily take care of by adding some custom CSS to the main stylesheet. The entire comment's section has the class `.page__comments` so you could very easily change the font (or other styling) for just that section.

The same could be said for making it [collapsible that expands](http://stackoverflow.com/questions/17460116/how-can-i-expand-and-collapse-a-div-using-javascript) by adding custom JS to `_includes/scripts.html`.

I'd rather not bake either into the theme as they're the sort of thing some people will want and others won't. I've tried to make the theme easily customizable to allow you to tailor it as you see fit.

**Comment by asarkar** [comment]
@mmistakes Sorry about the delayed response. I agree with what you said, but the problem is that not everyone has your skills. What if there's an `features` or `extras` folder,  where people, including you, can contribute features that can be optionally added? Then front end dummies like me can simply copy-paste the features they want, and those who don't, can ignore the folder.
