### ISSUE TITLE
How to add Google Tag Manager Script after body tag on all pages

### ISSUE THREAD

**Issue by Edmilerad** [mmistakes/minimal-mistakes#1005]
- [x] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Question about google tag manager

Hello Michael, thank you for your theme.
How would you add elegantly the google tag manager script.
It requires 2 scripts : 

- One in the head (and you have built a custom head for that)
- One immediately after the body tag
I am struggling to add the second to all the page of the site (which are using multiples layout).
Do you have a suggestion ?

Thank you very much
And thank you for your quick start guide. It is awesome to learn.
Edmilerad

**Comment by mmistakes** [comment]
Edit [`_layouts/default.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/default.html) and paste in the scripts where you want them. They'll be applied to every page.

**Comment by Edmilerad** [comment]
Thank you very much !
