### ISSUE TITLE
JSON Feed

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#1035]
Didn't know if you would be interested in a JSON feed added to this repo.  I don't believe the PR for [jekyll-feed](https://github.com/jekyll/jekyll-feed) is going to move forward, so it won't happen by a gem.  And the one advertised for [vallieres](https://github.com/vallieres/jekyll-json-feed) does not take into account some changes done by MM (such as images).

- [json.html](https://github.com/justinrummel/jr.com-mm/blob/jr-branch/_layouts/json.html) (Layout that also uses compress)
- [feed.json](https://github.com/justinrummel/jr.com-mm/blob/jr-branch/feed.json)

**Comment by mmistakes** [comment]
Perhaps. 

I've done mine own version of a [JSON Feed layout](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/_layouts/json_feed.html). Still want to switch to jekyll-seo-tag plugin and standardize on there use of `page.image` or `page.image.feed` instead of `page.image.feature` to better leverage the official Jekyll plugins that use those variables.

**Comment by justinrummel** [comment]
Gotcha... if there is going to be changes in the future then people can view my repo and use it if they want, but it may be better to wait till those elements calm down.

**Comment by justinrummel** [comment]
qq on use of liquid to parse data, why is it necessary to put the tags in a [for loop](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/_layouts/json_feed.html#L61-L65).  Since this is already an array of tags, can you simply state:

```
"tags" : {{ post.tags | jsonify }}
```

better yet, I would ```sort``` and ensure the array is ```unique```.

**Comment by mmistakes** [comment]
Good question. Just a miss when I [forked the layout](https://github.com/vallieres/jekyll-json-feed).There were a few other things I simplified and removed. Dropping the `for` loop should improve build times slightly too.

`sort` and `uniq` are good ideas as well.

**Comment by rriemann** [comment]
Any progress on this? @justinrummel, have you prepared a PR?

**Comment by mmistakes** [comment]
Closing as I don't really have any interest in managing a layout for this. My concerns are all echo'd here https://github.com/jekyll/jekyll-feed/issues/172

Your best bet is looking for a gem that does this or rolling your own layout.
