### ISSUE TITLE
Add Creative Commons XML to footer of posts.

### ISSUE THREAD

**Issue by twhite96** [mmistakes/minimal-mistakes#1046]
- [x ] This is a question about using the theme.
- [ ] This is a feature request.
- [x ] I have updated all gems with `bundle update`.
- [x ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 
4.4.1
- **`github-pages` or `jekyll` gem version:** 
3.3.1
- **Operating system:** 
macOS 10.12.4

---

## Steps to reproduce the behavior

Trying to add XML CC License to the bottom of each post. Not sure how to do that in Jekyll/Ruby/Liquid. Any help would be nice.

This is the code I am trying to add:

```xml
<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Just Another DevBlog</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://tiffanywhite.tech" property="cc:attributionName" rel="cc:attributionURL">Tiffany White</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.<br />Based on a work at <a xmlns:dct="http://purl.org/dc/terms/" href="https://tiffanywhite.tech" rel="dct:source">https://tiffanywhite.tech</a>.</div>
```

**Comment by mmistakes** [comment]
Looks like plain old HTML to me, not Liquid/Ruby/etc. Not sure I follow what the issue is. Should just be able to paste this into your posts. Or tact it on in a layout or include to keep things DRY.

**Comment by twhite96** [comment]
@mmistakes that's what I wasn't sure of. I'll tack it onto a layout. Thanks.

**Comment by twhite96** [comment]
I added it to the single.html layout and it is breaking the Disqus comments and the footer. Not sure what's going on.

**Comment by twhite96** [comment]
Just need to know how to style this. I added a license class to the div I used to hold the license but I have no clue how to style it with the SASS you've got. I know nada about SASS and the bare minimum of CSS.

**Comment by mmistakes** [comment]
The HTML above isn't valid so that's likely you're problem. For example you end it with `</div>` but there's no opening `<div>`.

Not sure if you wrote there HTML or if it came from somewhere but I'd double check it. 

As far as styling maybe give Stackoverflow or CSS tutorials a go. You don't have to write Sass, it will accept vanilla CSS if you're more comfortable with that.

**Comment by twhite96** [comment]
@mmistakes I didn't write the HTML. I knew there was something wrong with it but wasn't sure what. Thanks.

**Comment by mmistakes** [comment]
This is a good tool to identify invalid markup https://validator.w3.org/

**Comment by twhite96** [comment]
I was overthinking it. Added `text-align: center;` and all is good.
