### ISSUE TITLE
Inconsistency regarding modified date

### ISSUE THREAD

**Issue by poudelprakash** [mmistakes/minimal-mistakes#1060]
I was following your [sample code](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages-3.1.6/_posts/2010-01-07-post-modified.md) to update modified date and It was not working.

After going through source code of single page layout: <https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html>, I came to realise the key for modified date has changed from `modified` to `last_modified_at`.

**Comment by mmistakes** [comment]
This is a really easy "first commit" if someone wants to help out and submit a pull request to change `modified` to `last_modified_at` in sample posts and docs.

**Comment by poudelprakash** [comment]
I was confused, which one among doc and code was intended. Now it's clear, I can commit to update docs and send you pull request

**Comment by mmistakes** [comment]
Fixed in #929
