### ISSUE TITLE
"Sticky" masthead/top navigation bar

### ISSUE THREAD

**Issue by palatinux** [mmistakes/minimal-mistakes#1085]
- [x] This is a question about using the theme.
- [x] This is a feature request.

Dear MR,

When using the sidebar navigation in MM, it stays fixed when scrolling down a page. Is it possible to do the same with the headmast/top nav and the footer? (example http://idratherbewriting.com/documentation-theme-jekyll/ and https://aksakalli.github.io/jekyll-doc-theme/)

**Comment by couet** [comment]
I am interested in that also ... I managed to make the top bar fixed with some tricks but then the side menu bar hides and the TOC are hidden on top when scrolling and the section headers are also hidden when clicking on an item in the TOC.... that's *very* annoying ....

**Comment by fortierq** [comment]
Here is an example, to add a sticky class to masthead: https://github.com/fortierq/fortierq.github.io/commit/477b98f45c87474484327a55cae185873b6caac0

Result: https://fortierq.github.io/python-dev-1

**Comment by josecastillolema** [comment]
Thanks for your example @fortierq .
I your example I see that the anchors are being overlapped by the sticky masthead.
Does anyone has a solution to adjust this?
I have played around with **scroll-margin-top** in the CSS but I have been unable to solve the issue.
