### ISSUE TITLE
google-plus comments provider 

### ISSUE THREAD

**Issue by zmsp** [mmistakes/minimal-mistakes#1092]
google-plus comments provider seems to be stuck on loading. Didn't really see any javascript error on console. 

- [ ] This is a feature request.
- [ ] This is a question about using the theme.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations
Latest minimal-mistakes version
OS: Windows: Chrome/Linux: Firefox

## Steps to reproduce the behavior
To reproduce, try to add comments after enabling google-plus commenting. 
page: zmsp.github.io/hardware/cryptocurrency/gfx-too-high/
repo: github.com/zmsp/zmsp.github.io
![capture](https://user-images.githubusercontent.com/949058/27767409-1b9c1e68-5ec5-11e7-84ae-84ec7f75b2cb.PNG)

**Comment by mmistakes** [comment]
Not sure what's going on. I'm not seeing any script errors. Only thing I can think of Google changed the API or deprecated something.

To get this working originally I followed some instructions from a random blog post. I never could find official documentation from Google on how to embed G+ comments on a website.

**Comment by zmsp** [comment]
This change fixed it. I am not familiar with how it loads the comment box so its not the most elegant. But let me know if you want the change and I can submit a pull request.  https://github.com/zmsp/zmsp.github.io/commit/23914d3eb554c875cb36f144ffce83dc4efb416f

**Comment by mmistakes** [comment]
A PR with this fix would be great.
