### ISSUE TITLE
How to list collection items in the sidebar?

### ISSUE THREAD

**Issue by ellenkorbes** [mmistakes/minimal-mistakes#1096]
- [x] This is a question about using the theme.

---

Hi,

I've omitted most of the stuff in the template since this is a very simple question.

I'm trying to add a list of all pages in a collection to the sidebar of a page. I can do this in the content area of normal pages with the code below:

```html
<ul>
{% for item in site.support %}
    <li><a href="{{ item.url }}">{{ item.title }}</a></li>
{% endfor %}
</ul>
```

But I have no idea how to add it to the sidebar. I could go to `_includes/sidebar.html` and hack something there, but I'm wondering is there's a proper, less hacky way to do it.

Ideally I'd have two lists, for two different collections.

Thanks a bunch, and kudos on the awesome theme :)

**Comment by mmistakes** [comment]
There's no proper way to build a list in the way you want. You either have to define all the links using [this method](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-navigation-menu), or hack something to loop over your collections like you have above.

**Comment by ellenkorbes** [comment]
Alrighty, thank you (:
