### ISSUE TITLE
Serve local videos?

### ISSUE THREAD

**Issue by shivahnshankar** [mmistakes/minimal-mistakes#1098]
- [x ] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** Latest version
- **`github-pages` or `jekyll` gem version:** 3.4.3
- **Operating system:** macosx

---

Apart from the YouTube and Vimeo handlers, is there a way to embed a video file that is saved in the /assets/videos folder?

**Comment by mmistakes** [comment]
Sure. The theme doesn't care what your content is. Simply add HTML using the [`<video>` element ](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content)and you're good to go in your posts or pages.

```html
<video src="/assets/video/your-video.mp4" controls>
```

All modern browsers support that, so unless you need older browsers to work with it you won't need to add any JavaScript or 3rd party video players.

Closing this as it's not theme specific. If you need additional help [Stackoverflow](https://stackoverflow.com/questions/tagged/html) or other related web development sites would be the place to go.
