### ISSUE TITLE
Deprecation warning with sass gem 3.5

### ISSUE THREAD

**Issue by dpron** [mmistakes/minimal-mistakes#1114]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version: 4.4.2** 
- **`github-pages` or `jekyll` gem version:** (straight from forked source)
- **Operating system: Mac 10.12.5** 

---

## Expected behavior
Site builds without warnings

## Steps to reproduce the behavior

rm Gemfile.lock
bundle update

(updates saas gem to 3.5.1)

build site - causes screens full of the following warnings 

*DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("mixin-exists")) instead.*

and

*DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.*

if I force the saas gem back to 3.4.25 - warnings disappear.

Unfortunately warnings don't reference the exact file names.

**Comment by mmistakes** [comment]
If I had to guess it's due to one of the 3rd party mixins I'm using (Breakpoint, Susy, etc.). I'll see if I can track down which Sass partial is the issue and see if they have updated their libraries to get around the warnings.

**Comment by mmistakes** [comment]
Investigate 3rd party Sass

- https://github.com/mmistakes/minimal-mistakes/tree/master/_sass/minimal-mistakes/vendor

**Comment by mmistakes** [comment]
Found the culprit, [**Susy 2's** set of mixins](https://github.com/oddbird/susy/tree/susytwo).

These deprecation warnings are mostly harmless but figured I'd go ahead and upgrade to Susy 3 anyways. That project went through a fairly serious rewrite so I had to refactor a lot of the CSS I was using to build the theme's grid.

Everything looks good to me, but if anyone wants to test and verify I didn't break anything (specifically grid layouts in related posts, galleries, etc) give it a go.

To test you can replace the entire `_sass` folder with [this one](https://github.com/mmistakes/minimal-mistakes/tree/susy-3-upgrade/_sass) in the `susy-3-upgrade` branch. Or if you're using the theme gem replace `gem "minimal-mistakes-jekyll"` with this line:

```ruby
gem "minimal-mistakes-jekyll", :git => "https://github.com/mmistakes/minimal-mistakes.git", :branch => "susy-3-upgrade"
```

**Comment by wkc1986** [comment]
Merged updates from `susy-3-upgrade`, seems to work well.

**Comment by mmistakes** [comment]
Great, thanks for confirming @wkc1986. I'll get this merged into the next release.

**Comment by justinrummel** [comment]
using the specific susy-3-upgrade branch eliminated the warnings for me too.

**Comment by mmistakes** [comment]
Good to hear @justinrummel. Kind of bummed with all the helper functions Susy removed with v3. All of the gallery mixins are gone which makes doing custom stuff a lot more involved. Especially for those who want to customize the columns. #623 #875

**Comment by mmistakes** [comment]
Merged in https://github.com/mmistakes/minimal-mistakes/commit/4ba7cccdc449107f17ee654ec9ca6b6ae2dddf7f
