### ISSUE TITLE
How to get the site exactly like https://mmistakes.github.io/minimal-mistakes/ ?

### ISSUE THREAD

**Issue by hsluoyz** [mmistakes/minimal-mistakes#1122]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 4.4.2
- **`github-pages` or `jekyll` gem version:** jekyll 3.5.0
- **Operating system:** Win10 x64 with RubyInstaller 2.4.1-2

---

## Expected behavior

See the site like in: https://mmistakes.github.io/minimal-mistakes/

![image](https://user-images.githubusercontent.com/3787410/28247160-cd46f09a-6a5d-11e7-87e9-a4bc2c0a6ae8.png)

But actually I see:

![image](https://user-images.githubusercontent.com/3787410/28247162-dcd1c184-6a5d-11e7-8844-bfd84976b15b.png)

## Steps to reproduce the behavior

git clone https://github.com/mmistakes/minimal-mistakes
cd folder/to/repo

bundle install
bundle exec jekyll serve

So how to see the the exact site like https://mmistakes.github.io/minimal-mistakes/ ?

**Comment by mmistakes** [comment]
You need to modify the default index page to use the `splash` layout. You can see the entire source for the demo site in the [`/docs` folder](https://github.com/mmistakes/minimal-mistakes/tree/master/docs) if you need an example.

- [Home page splash example](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_pages/home.md)

If you search through the closed issues you'll find some more guidance as this has been asked a few times before.

**Comment by hsluoyz** [comment]
Thanks! The /docs folder is just what I need. I really mixed the demo site with the theme itself. I don't know if it's in the docs, but maybe you can mention /docs is the demo site in a more clear position:)
