### ISSUE TITLE
ER: What is the best way to add bigfoot.js to minimal-mistakes

### ISSUE THREAD

**Issue by emory** [mmistakes/minimal-mistakes#1127]
- [x] This is a question about using the theme.
- [x] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:**  minimal-mistakes-jekyll 4.4.1
- **`github-pages` or `jekyll` gem version:** jekyll 3.5.0
- **Operating system:** macOS 10.12.5 16F73

I have rvm installed, and I'm using bundle bundler in my rake tasks; `bundle exec jekyll $whatever`. The only rvm ruby I have installed is `2.4.0` and otherwise macOS system ruby.

---

## Expected behavior

I attempted to add [bigfoot.js](https://github.com/lemonmade/bigfoot) because I love it so much. I put `bigfoot.js` in `./assets/js/plugins`, added this:

```
  // Bigfoot footnotes like on mademistakes <3 @emory
  var bigfoot = $.bigfoot(
  // {
  //   actionOriginalFN: "ignore"
  //   }
  );
```

…to `./assets/js/_main.js`, added it to the `uglify` node task at the end of the list of plugins and additional javascripts.

#### This is where I've done something probably wrong:

I added `@import 'vendor/bigfoot/bigfoot-number';` to `./assets/css/main.scss` and I have `./_sass/vendor/bigfoot/` with `bigfoot-number.scss` inside there along with `bigfoot-default.scss` and `bigfoot-bottom.scss`.

#### Why I'm here

When I do all of that and run the `npm` tasks I get a warning amounting to `Side effects in initialization of unused variable` but the variable *is* defined as far as I can tell since I define it in `_main.js`. I get a lot of weird behavior from this point on, I fiddle with some different ways to attempt to load the `sass` and sometimes get footnote circles that take up 40% of the screen or the buttons are created but not labeled and have no contents, etc.

I also will get an error from Jekyll itself: 

```
      Regenerating: 1 file(s) changed at 2017-07-11 16:11:32     Liquid Warning: Liquid syntax error (line 9): Expected end_of_string but found colon in "{{SUP:data-footnote-backlink-ref}}" in assets/js/main.min.js
    Liquid Warning: Liquid syntax error (line 9): Expected end_of_string but found colon in "{{"+t+":"+o[1]+"}}" in assets/js/main.min.js
...done in 3.826932 seconds.
      Regenerating: 1 file(s) changed at 2017-07-11 16:11:36 ...done in 3.778978 seconds.
      Regenerating: 1 file(s) changed at 2017-07-11 16:13:14 ...done in 4.206295 seconds.
      Regenerating: 1 file(s) changed at 2017-07-11 16:13:25     Liquid Warning: Liquid syntax error (line 9): Expected end_of_string but found colon in "{{SUP:data-footnote-backlink-ref}}" in assets/js/main.min.js
    Liquid Warning: Liquid syntax error (line 9): Expected end_of_string but found colon in "{{"+t+":"+o[1]+"}}" in assets/js/main.min.js
...done in 3.505367 seconds.
      Regenerating: 1 file(s) changed at 2017-07-11 16:13:29 ...done in 3.776937 seconds.
```

This is where my troubleshooting completely fell apart because the file it generates with `npm` tasks has those refs but they look like the ostensibly functional ones you (mm) have in your combined ugly min javascript for your website.

## Steps to reproduce the behavior

I *just* successfully reverted my broken HEAD without thinking about this part. I can get it staged again into a broken state pretty easily ;) but I think my explanation may reveal my error. I tried to follow the notes in the docs/examples as best I could and I am hopefully there is a really simple thing I'm obviously screwing up and can add bigfoot to my site [incumbent.org](https://incumbent.org/)!

**Comment by mmistakes** [comment]
Take a look at #894. They eventually got Bigfoot.js working so you can likely peep their repo to see what you're doing differently.

Looks like your errors above are Liquid related since `main.min.js` has Front Matter `---` blocks. Guessing there might be a missing or extra `{` `}` or something else in your JavaScript that is causing Liquid to barf.

**Comment by mmistakes** [comment]
Also your best bet might be to add the BigFoot script by itself, instead of trying to squash it in with the rest of the theme. Because of the way theme gems works it might be a pain in the ass to sort out.

It won't be as performant as concatenating/minifying all the scripts together, but will likely get around the Liquid barfing.

**Comment by emory** [comment]
The repo she linked is now using another jekyll theme of yours! I will see if I can just add BigFoot and include it like you suggested.

**Comment by mmistakes** [comment]
The BigFoot.js script is up on [various CDNs](https://cdnjs.com/libraries/bigfoot), so you should be able to link it fairly easy to test if that works.

If it does then I'm sure it can be made to work by concatenating it with the main theme script. Just might take some tinkering and/or running it through a JS linter to make sure it's all valid.

**Comment by emory** [comment]
Is the proper place to put my stylesheet stuff `_sass/vendor`, or
`./assets/css/vendor` or something else ?


⤷
  You are standing in an open field west of a white house, with a boarded
front door.
  There is a small mailbox here.

**Comment by mmistakes** [comment]
@emory https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/

**Comment by emory** [comment]
I added the CDN-hosted bigfoot-number.js to `scripts.html` and `@import 'vendor/bigfoot/bigfoot-number';` is still in `./assets/css/main.scss` above `@import "minimal-mistakes";`

I write out the file and it generates pages and I see a lot of this:

```
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("mixin-exists")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("mixin-exists")) instead.
```

Should I just abandon the use of the `gem` for the sake of simplicity? I have that `./_sass` directory that may be superfluous or confusing things.

**Comment by mmistakes** [comment]
These are just warnings and not errors. They're from 3rd party mixins which likely haven't updated for newer versions of Sass.

If the Sass compiles into CSS I wouldn't worry about it.

**Comment by emory** [comment]
Thank you.

I am using `@import 'vendor/bigfoot/bigfoot-number';` and have added a CDN-hosted `bigfoot.js` but the part I was missing (and may be why having it minify and uglify my own output file wasn't working) was this which I added to `scripts.html`:

```
<script type="text/javascript">
    $.bigfoot();
</script>
```

I will still try to get it into my own output soon but for now a working example is not live in production on the web but the repository has it correct, https://github.com/emory/inc-mm-v4

**Comment by mmistakes** [comment]
Nice. Going to close this as you seem to have it under control.
