### ISSUE TITLE
Showing overlay color only on home page

### ISSUE THREAD

**Issue by straurob** [mmistakes/minimal-mistakes#1130]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version: 4.4.2** 
- **`github-pages` version: 143** 
- **`jekyll` gem version: 3.4.5** 
- **Operating system: Windows 7 64 Bit** 

---

## Usage Question
Source:
https://mmistakes.github.io/minimal-mistakes/docs/layouts/#header-overlay

As described on the above page it is possible to add an overlay color like this:
```
header:
  overlay_color: "#444"
```

This works fine when using on posts in the `_posts` directory. However I'd like to show the overlay color only on the "home page", i.e. the first page which is shown to the visitor.

How do I need to set this up?

**Comment by mmistakes** [comment]
Works the same way for any page. You just add the YAML Front Matter to it. In this case it would be your `index.html`, `index.md` or any other page you want.

For example the [MM demo site's homepage](https://mmistakes.github.io/minimal-mistakes/) has a feature image and overlay. You can see the [source here](https://raw.githubusercontent.com/mmistakes/minimal-mistakes/master/docs/_pages/home.md).

**Comment by straurob** [comment]
I added the `overlay_color` to `_layouts/home.html` which seems to be the wrong place. After having added it to `index.html` it works just fine. Thanks :+1:
