### ISSUE TITLE
 Conversion error: Jekyll::Converters::Sass encountered an error while converting 'Artists-Theme/assets/css/all.sass

### ISSUE THREAD

**Issue by srivallapa27** [mmistakes/minimal-mistakes#1137]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- jekyll 3.5.1 this is jekyll version
- hosted in Cloud 
- Artists-Theme is the theme

---

## Expected behavior

The server should start and should create the _site folder while deploying it the first time.

But below exception is been thrown 
[31m  Conversion error: Jekyll::Converters::Sass encountered an error while converting 'Artists-Theme/assets/css/all.sass':[0m
[31m                    Invalid variable: "$animation:". on line 5[0m
jekyll 3.5.1 | Error:  Invalid variable: "$animation:". on line 5

## Steps to reproduce the behavior

I couldn't able to upload the zip file because of the size issues

I am attaching the lines in teh all.sass file 

### Content Starts here ###
---
---

@import '1-tools/-tools-dir'

//------------------------------------------------
// Transition the image paths from the settings file to usable SASS variables
$animation: {{ site.data.layout.animation }}
$logo-path: '{{ site.data.layout.logo }}'
$hero-path: '{{ site.data.layout.hero }}'
$avatar-path: '{{ site.data.layout.avatar }}'

$projects: {% for project in site.data.settings.projects %} "{{ project.folder }}", {% endfor %}

//------------------------------------------------
// Set some colors as sass variables

$accent: {{ site.data.layout.accent }}
$accent-light: adjust-hue(saturate(lighten($accent, 11%), 12.6%), 14%)
$selectionColor: lighten($accent, 30%)

$textColor: {{ site.data.layout.textColor }}
$headlineColor: {{ site.data.layout.headlineColor }}
$bgcolor: {{ site.data.layout.bgcolor }}
$documentBackgroundColor: {{ site.data.layout.documentBackgroundColor }}

@import '2-base/-base-dir'
@import '3-sections/-sections-dir'

**Comment by mmistakes** [comment]
Closing as it appears you're filing an issue on the wrong theme. 

You'll want to reach out to the developer of that them here https://github.com/DevTips/Artists-Theme
