### ISSUE TITLE
Enhancement for developer documentation 

### ISSUE THREAD

**Issue by halirutan** [mmistakes/minimal-mistakes#1143]
- [x] This is a question about using the theme.
- [x] This is a **documentation** request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment information

- **Minimal Mistakes version:**  latest master commit 
- **`github-pages` or `jekyll` gem version:** jekyll 3.5.1
- **Operating system:** XUbuntu 16.04

---

## Documentation for *developers*

This theme is really (!!) nice and I plan to use it. I'm completely new to Jekyll, not a web-developer but used Pelican a bit and have a general understanding how everything works together. What I would like to do is the following:

- I have your repo cloned so that I can pull changes and probably make PR for small enhancements.
- I want the source of my site in a different folder and work with my local copy of minimal-mistakes as it would be the gem from the official repository

With this, I can make site-specific changes to the theme in the source of my site, while I'm still able to work on your original code. One way would be (like you do it) to make another branch and add my site there but then my site would sit inside the minimal-mistakes repo and I need to merge down changes to the branch when I pull updates.

Is there a way to work with the repo as it were on rubygems.org?

**Comment by halirutan** [comment]
Darn, I found the solution inside your `test` folder. I just need to set the `path` for the gem. If you like a PR for an updated *Development* section of your README, I'm happy to contribute a paragraph.

**Comment by mmistakes** [comment]
Sure feel free to submit a PR to beef up the documentation. Can probably add a note or a sub-section under the [Ruby Gem quick start](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#ruby-gem-method) in the docs.
