### ISSUE TITLE
feed not generated after changing gems: to plugins: in _config.yml

### ISSUE THREAD

**Issue by BoWuGit** [mmistakes/minimal-mistakes#1144]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

It works well locally, but github pages not, I just don't know why, thanks.

**Comment by mmistakes** [comment]
I don't think GH Pages has the latest Jekyll yet with this change. Roll it back to `gems` in your _config.yml until they updated it.

Closing as this is [gitHub/github-pages](https://github.com/github/pages-gem) related and not a theme issue.
