### ISSUE TITLE
Minor issue: Google analytics script should be in header

### ISSUE THREAD

**Issue by halirutan** [mmistakes/minimal-mistakes#1160]
The `analytics.html` code is included from `scripts.html` which in return is included at the end of `default.html`. When you verify your site through google-analytics, you get a warning:

> **Move the tag inside the head.**
We have detected that the Google Analytics tracking code is outside of the
section on this page. This decreases the likelihood that the tracking beacon will be sent before the user leaves the page.
One of the main advantages of the asynchronous snippet is that you can position it at the top of the HTML document. This increases the likelihood that the tracking beacon will be sent before the user leaves the page. We've determined that on most pages, the optimal location for the asynchronous snippet is at the bottom of the section, just before the closing tag.
Solution: Ensure that you add the Google Analytics tracking code onto this page before the closing tag.

Despite the fact that I really don't care, I wanted to report it for your information.

**Comment by mmistakes** [comment]
I'm aware. It's intentionally included near the closing `</body>` element to improve page loading performance.

I care more about potentially speeding up the page load for a visitor than Google Analytics being able to track a partial page load (the reason Google suggests placing in the `head`).

**Comment by halirutan** [comment]
Yes, I suspected this but wasn't sure. Please close this issue then.

**Comment by ohadschn** [comment]
@mmistakes but the `<script>` element is `async`...

**Comment by easybills-admin** [comment]
Google uses Google Analytics to **verify domains**, and it won't be able to do it because the script is in ~the wrong~ a different place:

> Verification failed for [URL] using the Google Analytics method (84 days ago). The Google Analytics tracking code on your site is in the wrong location. You can verify site ownership with the asynchronous snippet placed in the <head> section of your home page. Learn more.
