### ISSUE TITLE
Support Jekyll Docker container

### ISSUE THREAD

**Issue by dvkwong** [mmistakes/minimal-mistakes#1162]
- [] This is a question about using the theme.
- [X] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

Sorry but I don't understand enough about gems, css etc to provide more technical info.

## Environment information

NA- Docker container running in Linux with Alpine

- **Minimal Mistakes version: Latest
- **`github-pages` or `jekyll` gem version:Latest
- **Operating system:
---

## Expected behavior

When I execute the command on Windows powershell where $PWD is working directory I expect the pages to be rendered correctly

docker run --rm --volume="$PWD":/srv/jekyll -it -p 4001:4000 jekyll/jekyll:pages jekyll serve

Have tested this using github pages with built in templates and works great.

## Steps to reproduce the behavior

1. Install docker for your OS Windows/Mac/Linux
2. Clone minimal mistakes repo
3. Open terminal to the docs folder
4. Run command below (replace $PWD with the current path)
docker run --rm --volume="$PWD":/srv/jekyll -it -p 4001:4000 jekyll/jekyll:pages jekyll serve
5. Open browser and navigate to localhost:4000/minimal-mistakes
6. Rendering does no look correct.

**Comment by dvkwong** [comment]
Actually looking at rendered pages and the urls http://0.0.0.0:4000 eg http://0.0.0.0:4000/assets/css/main.css which are not acessible should be something like /assets/css/main.css

**Comment by mmistakes** [comment]
Sorry, I don't have any experience with Docker so not sure what to suggest. I'll leave this open in case someone else knows more.

Maybe ask for help on https://talk.jekyllrb.com ?

**Comment by dvkwong** [comment]
Yup definitely the 0.0.0.0. Will have to figure out how to override the url. Tried the below command setting the hosts which rendered the html urls correctly but could no longer browse the site.

docker run --rm --volume="$PWD":/srv/jekyll -it -p 4000:4000 jekyll/jekyll:pages jekyll serve --force_polling --host localhost

**Comment by dvkwong** [comment]
Ok solved it. 

1. Requires specifying the JEKYLL_ENV variable can be set to anything.
docker run --rm --volume="$PWD":/srv/jekyll -it -p 4000:4000 -e JEKYLL_ENV=dev jekyll/jekyll:pages jekyll s --force_polling --config _config.dev.yml

2. Set your config yml url and repository settings.

theme: minimal-mistakes-jekyll
url: http://localhost:4000
repository               : "myblog/blog"

I'll get around to making a pull request to add to docs, docker is sooo much easier to work with once you know how :)
