### ISSUE TITLE
Reading time doesn't display plural form of `minute`

### ISSUE THREAD

**Issue by yzgyyang** [mmistakes/minimal-mistakes#1165]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 4.5.0
- **`github-pages` or `jekyll` gem version:** 2.6.11
- **Operating system: ** Arch Linux x64

---

## Expected behavior

For displaying reading time estimates, `3 minute read` will be displayed instead of `3 minutes read` or at least `3 minute(s) read`.

## Steps to reproduce the behavior

Add `read_time: true` and create a long article.

**Comment by mmistakes** [comment]
This is intentional, see #356 for context.

If you prefer `minute(s) read` instead of `minute read` you can change that text to whatever you'd like in [`_data/ui-text.yml`](https://github.com/mmistakes/minimal-mistakes/blob/master/_data/ui-text.yml#L15).

```yaml
 minute_read: "minute read"
```
