### ISSUE TITLE
Follow Dropdown should go away, if clicked on screen outside from dropdown menu

### ISSUE THREAD

**Issue by deepaksood619** [mmistakes/minimal-mistakes#1168]
- [ ] This is a question about using the theme.
- [x] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations
- **Minimal Mistakes version:** v4.5.0
- **`github-pages` or `jekyll` gem version:** 3.5.1
- **Operating system:** Ubuntu, Chrome Browser mobile + desktop

---

## Current behavior

1. User will click out of screen and would expect the drop down to close.
2. Also after clicking outside the follow button shade changes, but the drop down share menu doesn't get removed.
3. Again clicking on follow button removes the dropdown menu, but follow button shades become selected (black)

![selection_001](https://user-images.githubusercontent.com/13206612/29110263-bc25064a-7d03-11e7-90af-7084ae12d196.png)

![selection_002](https://user-images.githubusercontent.com/13206612/29110420-35253254-7d04-11e7-8659-cec7b05372b3.png)

**Comment by Kulbhushan-Chand** [comment]
This issue seems similar to the one https://github.com/mmistakes/minimal-mistakes/issues/1987 where the problem was with hamburger icon on top right.( and issue is still there).
