### ISSUE TITLE
Table of contents out of screen when using Splash Layout

### ISSUE THREAD

**Issue by imbiansl** [mmistakes/minimal-mistakes#1169]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

Hi! First of all: this theme is awesome!

I've just updated to the newest unreleased version and I found the following problem:

When I use the `splash` layout with the table of contents and maximize the window, the table appears out of screen and I have to scroll right to find it. It looks like this:

![screenshot](http://i1.bvimg.com/1949/f96829806659a27c.png)

*(using the Quick-Start Guide as an example)*

Though I have little understanding of your project, I believe this is relevant to the last few commits.

Is it possible to fix this problem? Thanks!

**Comment by mmistakes** [comment]
Thanks for this. You're right, it was related to the last couple of commits.

Table of contents don't typically show up on the `splash` layout so it wasn't something I designed for or noticed. Pushing a fix shortly.

**Comment by vortexing** [comment]
So, in the end, did you decide to prevent toc's on splash pages?  I have the same need (the toc to show up either on the side of the text body OR inline).  Basically I don't use a sidebar for this particular website, and so it looks really silly unless I use the splash layout.

**Comment by mmistakes** [comment]
@vortexing Right side TOCs should work. I fixed this in the commits above back in November.

https://github.com/BoWuGit/bowugit.github.io/commit/d2ec18018f5bf991cd61458b20cac58cf8569414
