### ISSUE TITLE
Strange margin-bottom in the body

### ISSUE THREAD

**Issue by cristinadeoliveira** [mmistakes/minimal-mistakes#1173]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---
There is a strange margin between the initial page and the footer. I inspected and I found a in-line style:
```html
style="margin-bottom:101px"
``` 
![image](https://user-images.githubusercontent.com/30827643/29253242-8f63a67e-806f-11e7-8b1b-1f928bdd77fc.png)

I would like to remove it, however I can not find where is it being defined.

**Comment by mmistakes** [comment]
That margin is being added to `<body>` to compensate for the footer that is absolutely positioned to the bottom of the page. Without it there's a possibility it would overlap content making it impossible to see it.

That said if you'd like to remove it you'll need to:

1. Edit [`/assets/js/_main.js`](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/_main.js#L7-L13) by removing these lines
    ```js
    // Sticky footer
    var bumpIt = function() {
      $('body').css('margin-bottom', $('.page__footer').outerHeight(true));
    },
    didResize = false;

    bumpIt();
    ```
3. Rebuild the theme's JS file by running `npm run build:js`... [see the documentation](https://mmistakes.github.io/minimal-mistakes/docs/javascript/#customizing) for additional guidance.

**Comment by mmistakes** [comment]
Example with margin bottom added to `<body>` so the main content clears the footer.

![screen shot 2017-08-13 at 7 51 24 pm](https://user-images.githubusercontent.com/1376749/29254310-ff2984e2-8060-11e7-9d58-2aab4b2d5a40.png)

Example with it removed... you can see the footer overlaps the main content (banner ad at the bottom is now obscured by footer)

![screen shot 2017-08-13 at 7 51 42 pm](https://user-images.githubusercontent.com/1376749/29254311-02655d16-8061-11e7-95a2-7c01adc55e5b.png)
