### ISSUE TITLE
"Sticky" table of contents sidebar

### ISSUE THREAD

**Issue by nelsonmestevao** [mmistakes/minimal-mistakes#1174]
- [ ] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

As the profile side bar or menu side bar when we scroll down it doesn't. It would be super cool if the TOC didn't too. For UX purpose it would be super awesome!

**Comment by keohan** [comment]
As a user of MinimalMistakes, my users have also requested this Feature.

I feel that this feature it is core to this project as it enhances consistency across the UI by making menus sticky across the board.

**Comment by mmistakes** [comment]
@keohan This is already a feature of the theme. Check out the documentation for more info.

https://mmistakes.github.io/minimal-mistakes/layout-table-of-contents-sticky/
