### ISSUE TITLE
Mobile Follow Button z-index incorrect on posts

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#1185]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.
- [X] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- Minimal Mistakes version: **minimal-mistakes-jekyll 4.5.0 from git://github.com/mmistakes/minimal-mistakes.git (at layout-adjustments@1f58867**
- `github-pages` or `jekyll` gem version: **jekyll 3.5.2**
- Operating system: **10.12.6**

---

## Steps to reproduce the behavior

the main index page when looking from a mobile device, the "Follow" button displays as expected.

![](https://d3vv6lp55qjaqc.cloudfront.net/items/2H3z1M3n2C3a3t3s1A2s/Image%202017-08-16%20at%207.37.00%20PM.png?X-CloudApp-Visitor-Id=205743)

However, when viewing an actual post, it seems the z-index is off.

![](https://d3vv6lp55qjaqc.cloudfront.net/items/2r1f3g241H0N3y1c3l3y/Image%202017-08-16%20at%207.39.01%20PM.png?X-CloudApp-Visitor-Id=205743)

If I insert a ```z-index: -1;``` on the article class, it looks correct, however, I'm not sure if that is the correct solution... nor if it has a negative impact on other things.

![](https://d3vv6lp55qjaqc.cloudfront.net/items/0q3j043l272F2Q1J2p1g/Image%202017-08-16%20at%207.39.50%20PM.png?X-CloudApp-Visitor-Id=205743)

**Comment by mmistakes** [comment]
-1 was what it previously was but it appeared below the main content. There's probably something else at play I'll have to adjust.

**Comment by mmistakes** [comment]
I can't reproduce it on any of demo site's sample pages. Do you see the overlap there? 

https://mmistakes.github.io/minimal-mistakes/

Perhaps it has to do with customizations you've made.

**Comment by mmistakes** [comment]
![img_8989](https://user-images.githubusercontent.com/1376749/29441092-da81a56e-8396-11e7-9502-eaf14067730c.PNG)

**Comment by mmistakes** [comment]
You need to use the latest on `master`. There's some additionally CSS that was added in https://github.com/mmistakes/minimal-mistakes/commit/173f18404725c8930603a1aa356a51aadefaa905 to the `.sidebar` element to position it above the main content. The CSS you're using on your site is missing that.
