### ISSUE TITLE
Print adds a lot of extra pages

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#1196]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 4.5.0
- **`github-pages` or `jekyll` gem version:** Using Github Pages
- **Operating system:** Github Pages

---

## Expected behavior

I am expecting there to be only the pages needed when printing to save the forrests.

## Steps to reproduce the behavior

You can try to print this page: http://historie.vih.dk/dji-start/

That post is based on https://github.com/vih/historie/blob/gh-pages/_posts/1992-03-08-dji-historie-ole-work.md

**Comment by mmistakes** [comment]
This is Chrome issue that I thought I fixed awhile ago. Will have to take another look. My guess is an element is being stretched vertically, creating the extra blank pages.

cc/ #909 #919
