### ISSUE TITLE
duplicate `disqus_thread` in HTML id

### ISSUE THREAD

**Issue by fantasticfears-stage** [mmistakes/minimal-mistakes#1199]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 4.5.1
- **`github-pages`:** 155
- **Operating system:** OS X 10.12.6

---

## Expected behavior

No duplicate id for `disqus_thread` in HTML.

## Steps to reproduce the behavior

Build with `comments.disqus.shortname`, the output HTML has the duplicate id in HTML.

**Comment by mmistakes** [comment]
You have a public repo somewhere I can inspect? Hard to tell what's going on without seeing your actual `_config.yml` and post content.

**Comment by fantasticfears-stage** [comment]
https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments.html#L9
https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments-providers/disqus.html#L2
duplicate id here.

For example, this is the HTML https://erickguan.me/2017/copy-and-paste-bookmarklet
And config https://github.com/fantasticfears-stage/erickguan.me/blob/master/_config.yml

**Comment by mmistakes** [comment]
Got it. Looks like this was from #1179 

`<div id="disqus_thread"></div>` was added to `_includes/comments-providers/disqus.html` when it shouldn't have been.
