### ISSUE TITLE
Remove Google Authorship

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/minimal-mistakes#120]
Google's Authorship markup is no longer supported, remove from `_head.html`.

**Comment by jfairbank** [comment]
Are there any plans to incorporate microdata as a replacement?

https://support.google.com/webmasters/answer/176035

**Comment by mmistakes** [comment]
Yes. I marked up some of my other themes with it so it shouldn't be a big deal to add the extra markup to include microdata for post authors.
