### ISSUE TITLE
want to make a blog archive by category, posts listed in a grid

### ISSUE THREAD

**Issue by taunsquared** [mmistakes/minimal-mistakes#1200]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 4.4.1
- **`github-pages` or `jekyll` gem version:** github-pages in browser
- **Operating system:** windows

---

## Expected behavior

An archive page with headers for each category, with posts listed in grid view beneath each header. 

## Steps to reproduce the behavior

Here is the file and repository: https://github.com/everymind/SurprisingMinds/blob/gh-pages/_pages/blog-archive.html

It almost does it -- the category headers are just floating at the top of the page, instead of with their respective posts. The posts themselves seem to have filtered correctly, and are displaying in a grid more or less how I want them. But I can't figure out how to get the headers to go in the right place. 

![debug04](https://user-images.githubusercontent.com/27739141/29633078-fe4ecfd0-883c-11e7-8200-0bbbd98a4698.png)

I've tried moving around the location of the grid__wrapper div, but I suspect I need to change something else, perhaps something in a css file? Apologies if this is super obvious, any tips much appreciated!

**Comment by mmistakes** [comment]
This one might be tricky to get right. The grid items use `nth-child` selectors to `float` and `clear` floats at various breakpoints.

Depending on where you inject the category headings it might be viewed as a child element and that could explain the overlapping. You'll most likely need to add some `<div>` or other wrappers to combat the `nth-child` CSS so it only applies to the grid items and not the headings. Then make sure the headings clear any floats.

The relevant CSS is all in [`_archive.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_archive.scss#L114-L189) if you want to get a feel for what's going on.

**Comment by taunsquared** [comment]
Hi, thanks for the prompt reply! 

I'm looking at _archive.scss, in the section labeled "Grid view". When you say I might need to add <div> or other wrappers, do you mean here? I don't see anything using :nth-child here, nor in the gallery document in the _includes directory, which seems to get called here. 

My current best guess is that I need to add something that takes care of archive subtitles in the Grid View, then perhaps all of this: 
`  .archive__item-title {
    margin-top: 0.5em;
    font-size: $type-size-5;
  }

  .archive__item-excerpt {
    display: none;
  }

  @include breakpoint($small) {
    @include gallery(5 of 10);
    .archive__item-teaser {
      max-height: 200px;
    }
  }

  @include breakpoint($medium) {
    margin-left: 0; /* reset before mixin does its thing*/
    margin-right: 0; /* reset before mixin does its thing*/
    @include gallery(2.5 of 10);

    .archive__item-teaser {
      max-height: 120px;
    }

    .archive__item-excerpt {
      display: block;
      font-size: $type-size-6;
    }`

needs to be placed inside of a wrapper?

I'm pretty new to css in general -- any good documentation you could suggest that would be relevant to this puzzle?

**Comment by mmistakes** [comment]
I'm talking about these lines https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_archive.scss#L114-L189

You'll see all sorts of `&:nth-child` selectors in there.

In it's most simplest form you should have HTML like this:

```html
<h2>Heading</h2>
<div class="grid__wrapper">
  <div class="grid__item"></div>
  <div class="grid__item"></div>
  <div class="grid__item"></div>
  <div class="grid__item"></div>
</div>

<h2>Heading 2</h2>
<div class="grid__wrapper">
  <div class="grid__item"></div>
  <div class="grid__item"></div>
  <div class="grid__item"></div>
</div>
```

The CSS for `.grid_item` uses the `nth-child` selectors to position the 2nd, 3rd, 4th, etc. grid items in a repeatable pattern so everything lines up.

What you need to do is clear the floated `grid__item` elements.

Add `clear: both` to `.grid__wrapper` and to `.archive__subtitle` and it should fix your problem.

**Comment by taunsquared** [comment]
Ack, I was looking at an older version of this document! I understand now :)

It's almost working! Now the category titles are in the correct places, more or less, but the second category seems to be offset by the wrong number of grid cells: 
![debug05](https://user-images.githubusercontent.com/27739141/29680556-d6e47632-88fc-11e7-8ab8-32a1c89b2393.png)

does it matter the order in which `clear: both` appears under `.grid__wrapper` and `.archive_subtitle`?

**Comment by mmistakes** [comment]
No shouldn't matter. For what it's worth when I look at your site it's aligned correctly.

![heading](https://user-images.githubusercontent.com/1376749/29682024-9113d55a-88d7-11e7-880f-7ae0555f0493.jpg)

**Comment by taunsquared** [comment]
Oh! I guess things just hadn't updated properly yet. 

Many thanks!!
