### ISSUE TITLE
Add color "skins" to the theme

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/minimal-mistakes#1208]
- [x] This is a feature request.

Strip out hard-coded color values in SCSS and replace with variables to allow for more "skinning" opportunities ala [Basically Basic](https://github.com/mmistakes/jekyll-theme-basically-basic#skin).

**Comment by mmistakes** [comment]
SCSS has been refactored to better hand "skinning". If anyone wants to play around with it the changes can be found in the `color-skins` branch.

Probably the easiest way to enable it is by using the pre-release theme gem, add the following to your `Gemfile`:

```
gem 'minimal-mistakes-jekyll', :git => 'https://github.com/mmistakes/minimal-mistakes.git', :branch => 'color-skins'
```

And then add `minimal_mistakes_skin: "dark"` to your `_config.yml` file.

![mm-dark-skin-1](https://user-images.githubusercontent.com/1376749/29986035-b5d9a05a-8f2f-11e7-8225-e56083e49725.png)

![mm-dark-skin-2](https://user-images.githubusercontent.com/1376749/29986037-b9963a0a-8f2f-11e7-9c65-b748532e8714.png)

Couple of minor styling things need to happen (eg. fix author icon colors on dark backgrounds), but it's mostly usable.

**Comment by mmistakes** [comment]
### Dirt skin: `dirt`

![mm-dirt-post](https://user-images.githubusercontent.com/1376749/30114153-fcdad952-92e4-11e7-976e-338b98ebcc01.png)

![mm-dirt-archive](https://user-images.githubusercontent.com/1376749/30114155-fecac59c-92e4-11e7-8e81-9f071fbcb4f5.png)

**Comment by mmistakes** [comment]
### Air skin: `air`

![mm-air-post](https://user-images.githubusercontent.com/1376749/30114909-3579115a-92e7-11e7-87dc-3ad730fb1e4c.png)

![mm-air-archive](https://user-images.githubusercontent.com/1376749/30114911-36c30ba6-92e7-11e7-941a-8a0b1c6c785a.png)

**Comment by mmistakes** [comment]
### Mint skin: `mint`

![mm-mint-post](https://user-images.githubusercontent.com/1376749/30117047-1aba586e-92ed-11e7-86f1-a10342336639.png)

![mm-mint-archive](https://user-images.githubusercontent.com/1376749/30117050-1c20fdfc-92ed-11e7-8dff-090b7b9f657c.png)

**Comment by justinrummel** [comment]
These are great!  Thanks for the work.

**Comment by justinrummel** [comment]
I noticed that none of your examples include a comments section.  I would expect the color options to be reversed vs. dark text field with light border area.

![](http://cl.rummel.co/1L0u0k0V2h0K/Image%202017-09-06%20at%202.03.10%20PM.png)

**Comment by justinrummel** [comment]
Last note for documentation, if you have already made CSS changes be sure to update your [/assets/css/main.scss](https://github.com/mmistakes/minimal-mistakes/blob/689b0aacbef10cabccd3bbb5a730fff1eee68814/assets/css/main.scss) to include 

``` css
@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
```

**Comment by mmistakes** [comment]
@justinrummel I'm guessing you have an outdated `_sass/_forms.scss` file or one of the comments includes.

`form` should have `background-color: $form-background-color;` which will fill it in with a darker color like this:

![image](https://user-images.githubusercontent.com/1376749/30128858-19f0049a-9312-11e7-81a0-e754d1924efb.png)

**Comment by justinrummel** [comment]
Thanks, I must have an override somewhere on /assets/css/main.scss somewhere...
