### ISSUE TITLE
Cannot find my website via google search

### ISSUE THREAD

**Issue by taochenshh** [mmistakes/minimal-mistakes#1212]
I try to search my website on google. I searched the website's title, but my website is not on the search result list. Are there any changes I can make on this theme to get rid of this issue? Thanks.

**Comment by mmistakes** [comment]
This isn't a theme issue. Google and other search engines can take time to spider and index your site. You'll want to use Google's webmaster tools to submit your site, point it at your `sitemap.xml`, etc. to start that process.

Search around for SEO best practices as that's what you'll want to work on to get your content ranking.
