### ISSUE TITLE
Items in "You may also enjoy section overlap" $x-large     

### ISSUE THREAD

**Issue by UnderNotic** [mmistakes/minimal-mistakes#1213]
I think possible solution would be to increase $x-large breakpoint.
My proposal is to change it from 1280px to 1680px.

![capture](https://user-images.githubusercontent.com/6854701/29995719-5c82545e-8ff0-11e7-85b6-9f8064cd1fec.PNG)

**Comment by mmistakes** [comment]
I think this is pretty rare... having a string of your length without any spaces. That's what is breaking the layout.

The better option would be to apply some CSS that truncates it with `...` for any characters that don't fit in the space.

https://software.intel.com/en-us/html5/hub/blogs/ellipse-my-text/

**Comment by mmistakes** [comment]
Titles that overflow the parent are now truncated with an ellipsis to avoid breaking the layout.

![mm-truncate-overflown-text](https://user-images.githubusercontent.com/1376749/30129629-869ebf58-9314-11e7-9777-99d45150eb19.png)
