### ISSUE TITLE
Add SourceForge author info

### ISSUE THREAD

**Issue by ohadschn** [mmistakes/minimal-mistakes#1214]
It's no GitHub, but it still contains hundreds of thousands of projects and millions of users (personally I still have several projects hosted there I would like to show off :]). One could argue that it's more significant than GitLab (Alexa rank of 328 compared to 2,326 at the time of writing) and possibly BitBucket (Alexa rank 666), both of which have their own author info spot...

**Comment by mmistakes** [comment]
Closed for all of the reasons cited in #1142, #820, #779, #709, #360, #299, and many more.

**Comment by ohadschn** [comment]
Fair enough, though I still think it makes more sense to replace say GitLab with SourceForge (kind of annoying they don't have a Font Awesome icon though).
