### ISSUE TITLE
Pagination link to page number 1

### ISSUE THREAD

**Issue by mittalyashu** [mmistakes/minimal-mistakes#1227]
Tried to use this [code](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/paginator.html).

But faced the issue that when we click on the page number 1

It opens this page: 
![image](https://user-images.githubusercontent.com/29014463/30099721-3638e3fa-9304-11e7-96d9-490d6c682350.png)

**Comment by mmistakes** [comment]
Which version of the theme are you using? What is your `_config.yml` settings? Do you have a public repo?

**Comment by mittalyashu** [comment]
Here is the [repo](https://github.com/codecarrotnet/blog).

The problem we are facing using that [code](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/paginator.html), we have not pushed to GitHub yet. We were testing it locally.

**Comment by mmistakes** [comment]
Looks like you're not using the theme so I won't be of much help. If you're trying to piece parts of this theme into another project you'll have to really dig in and make sure you're getting everything.

You've likely missed a configuration somewhere. Best I can offer is to check [Jekyll's pagination docs](http://jekyllrb.com/docs/pagination/) to make sure you have everything configured.

**Comment by mmistakes** [comment]
For what it's worth I cloned your repo and built it locally, pagination works fine for me and all of the links resolve correctly.

![image](https://user-images.githubusercontent.com/1376749/30119753-be716a72-92f4-11e7-8099-6d3dcf938a7e.png)

Maybe something is up with your development environment. You are running Jekyll with `bundle exec jekyll serve` correct?

Closing as this isn't an issue with the Minimal Mistakes theme. The Jekyll help forum or Stackoverflow is a more appropriate place to ask these sorts of questions.

**Comment by mittalyashu** [comment]
Yes. I am using `bundle exec jekyll serve` only.

Can you tell, that when you tried locally? What was the link to your homepage *(after going back from page 2 to page 1)*?

`localhost:(port)/?`

**Comment by mmistakes** [comment]
1. Cloned your repo locally.
2. `bundle install`
3. `bundle exec jekyll serve`
4. Visit `http://localhost:4000`

All of the paginator links work as expected.

On index/page 1 the HTML is this:

```html
<div class="pagination">
    <div class="container">
        <!-- Previous Button -->
        <span style="display: none" class="page-numbers current">Previous</span>
        
        <!-- Previous Page Button -->
        <span style="display: none" class="page-numbers current"></span>
        
        <!-- Current Page Button -->
        <span class="page-numbers current">1</span>
        
        <!-- Next Page Button -->
        <a href="/page/2/" class="page-numbers">2</a>
        
        <!-- <span class="page-numbers dots">...</span>
        <a href="/page/8/" class="page-numbers">8</a> -->
        
        <!-- Next Button -->
        <a href="/page/2/" class="page-numbers">Next</a>
    </div>
</div>
```

And on page 2 it is this:

```html
<div class="pagination">
    <div class="container">
        <!-- Previous Button -->
        <a href="/" class="page-numbers">Previous</a>
        
        <!-- Previous Page Button -->
        <a href="/" class="page-numbers">1</a>
        
        <!-- Current Page Button -->
        <span class="page-numbers current">2</span>

        <!-- Next Page Button -->
        <a href="/page/3/" class="page-numbers">3</a>
        
        <!-- <span class="page-numbers dots">...</span>
        <a href="/page/8/" class="page-numbers">8</a> -->

        <!-- Next Button -->
        <a href="/page/3/" class="page-numbers">Next</a>
    </div>
</div>
```

If you're getting links like `/page/:num` then there is something wrong with your local environment and the `jekyll-paginate` gem is likely not current or installed properly. I can't help you with that. You'll have to reach out on Stackoverflow or some other help forum.
