### ISSUE TITLE
Header image dimensions

### ISSUE THREAD

**Issue by darrenhaken** [mmistakes/minimal-mistakes#1229]
What are the recommended image dimensions for the header/hero banner?

**Comment by mmistakes** [comment]
There are  no hard-fast sizes. Something between `1280-1600px` wide is a good balance for quality/file size as the same image will be used on mobile and desktop unless you implement some sort of responsive image solution.

Height is up to you and how much of the page you want it to occupy. Here's an example of an image orientated in [landscape](https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-image-horizontal/) and another as [portrait](https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-image-vertical/).
