### ISSUE TITLE
_pages and _layouts not included when publish to Github Pages

### ISSUE THREAD

**Issue by L3K0V** [mmistakes/minimal-mistakes#1233]
- [X] This is a question about using the theme.
- [ ] This is a feature request.
- [X] I believe this to be a bug with the theme.
  - [X] I have updated all gems with `bundle update`.
  - [X] I have tested locally with `bundle exec jekyll build`.
---

## Environment informations

- **Minimal Mistakes version:** 4.5.2
- **Jekyll version:** 3.5.2
- **GitHub Pages hosted:** yes
- **Operating system:** Mac OS X

Tested locally with both jekyll and github-pages gems

---

## Expected behavior

Jekyll site with Minimal Mistakes theme installed using the gem procedure to be published correctly to Github Pages.Testing Everything is working fine when testing locally.

## Steps to reproduce the behavior

Publishing to Github give me:

> Your site is having problems building: A file was included in _pages/about.md that is a symlink or does not exist in your _includes directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink/.

`_pages` is included in `include:` into `_config.yml`

After removing all pages the error remains but `_layouts/home.html` became a issue

So maybe something is misconfigured but I don't know what. Maybe is not documented well or not documented at all. What I'm missing here?

Source can be found here: https://github.com/L3K0V/c-programming

**Comment by L3K0V** [comment]
It looks like 3th party themes are not allowed when hosted on Github Pages as documented here: https://mmistakes.github.io/minimal-mistakes/jekyll/gemified-theme-beta/

**Comment by ohadschn** [comment]
I suggest GitLab pages, which support plugins out of the box (they can be made to work in GH pages too but it's more involved).

You can fork my repo for a fully working Minimal Mistakes: https://gitlab.com/ohadschn/ohadschn.gitlab.io/
