### ISSUE TITLE
Shorthand form for (lightbox) linked inline image

### ISSUE THREAD

**Issue by ohadschn** [mmistakes/minimal-mistakes#1235]
- [x ] This is a question about using the theme.

Is there a shorthand form for `[![foobar](/foo/bar.jpg)](/foo/bar.jpg)`?

That is, both insert an inline image and link to it (so the lightbox pops up). I could use a gallery but that's both less standard and introduces more overhead than it saves...

**Comment by mmistakes** [comment]
Don't think so. That's Markdown. Maybe inquire with the [Kramdown project](https://github.com/gettalong/kramdown) as that's what Jekyll uses by default to parse `.md` files. Or look at the other [Markdown parsers](https://jekyllrb.com/docs/configuration/#markdown-options) supported by Jekyll to see if they support shorter ways of linking images to other images.

The way the lightbox is currently configured is to [trigger on any `<a>` element that links to a image](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/_main.js#L37-L38). There are a ton of different ways of setting that up, all of which can be read about on the [Magnific Popup documentation](http://dimsemenov.com/plugins/magnific-popup/).

Closing as this isn't really theme related as per the original request.

**Comment by ohadschn** [comment]
I didn't see any direct Kramdown solution, but it does let you set [custom attributes on images](https://kramdown.gettalong.org/syntax.html#images) so something like this works: `![foobar]({{ '/foo/bar.png' | absolute_url }}){:.image-popup href="{{ 'foo/bar.png' | absolute_url }}"}` (yes, I am adding `href` to an `img` element, a hack to make the lightbox work).

Of course, that's even worse than the vanilla form above, but with a little jQuery to apply the attributes automatically it should be simple to achieve automatically:

```js
$('.page__content img')
    .addClass('image-popup')
    .attr('href', function() { return $(this).attr("src") });
```

WDYT?

**Comment by mmistakes** [comment]
If that does the job for you should be fine to add as a custom bit of script to your overrides. 

Don't think it makes sense to bake it into the theme as a default.

**Comment by ohadschn** [comment]
Yeah I agree, just wanted to run my solution by you.

**Comment by ohadschn** [comment]
However now that I think about it would be really cool if I could say `![foobar]({{ '/foo/bar.png' | absolute_url }}){:.image-popup"}` and in your [`_main.js`](https://github.com/mmistakes/minimal-mistakes/blob/b5e1eeb0075067528ed03bd2f41857a52fc79c09/assets/js/_main.js#L41) you would just add the `href` if missing...
