### ISSUE TITLE
Add crossorigin="anonymous" to all script elements

### ISSUE THREAD

**Issue by ohadschn** [mmistakes/minimal-mistakes#1237]
This will allow a better debugging experience: https://stackoverflow.com/a/18336863/67824

**Comment by mmistakes** [comment]
I don't really get what problem this proposes to fix.

**Comment by ohadschn** [comment]
Well if scripts were included from a different origin, it would provide a better debugging experience should something go wrong. Currently it seems like only one script is loaded and it's from the same origin (`main.min.js`) but I suppose that could change (I've already suggested such a change here: https://github.com/mmistakes/minimal-mistakes/issues/1238).

**Comment by mmistakes** [comment]
Maybe I'm being dense, but I still get what benefit this adds to the average user of the theme.

**Comment by ohadschn** [comment]
It just allows him to get more information should some error occur and either debug the issue himself or post a more meaningful issue here. Debuggability is important, and in this case it's pretty much free (just add an attribute).
