### ISSUE TITLE
Social sharing twitter

### ISSUE THREAD

**Issue by rudvfaden** [mmistakes/minimal-mistakes#124]
When sharing to twitter, only the `page.url` is shared

**Comment by mmistakes** [comment]
That's because you didn't set a `site.url` in your `_config.yml`. Either set `url: http://rudvfaden.github.io` or you can hardcode it into the links found in the `_social-share.html` so they're all absolute page URLs.

``` html
<a href="https://twitter.com/intent/tweet?text={{ page.url | prepend:'http://rudvfaden.github.io/' }}" class="twitter" title="Share on Twitter"><i class="fa fa-twitter"></i><span> Twitter</span></a>
```
