### ISSUE TITLE
File to import not found or unreadable: minimal-mistakes/skins/air

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#1244]
- [X] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [X] I have updated all gems with `bundle update`.
  - [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.5.2
- **Jekyll version:** 3.5.2
- **GitHub Pages hosted:** no
- **Operating system:** Travis

---

Updated to use the new version of MM locally and everything worked as expected, however, when committed to use the latest update 4.5.2, Travis CI complained:

``` bash
 Theme Config file: /home/travis/build/justinrummel/jr.com-mm/vendor/bundle/ruby/2.4.0/bundler/gems/minimal-mistakes-1a2a953dfb21/_config.yml
            Source: /home/travis/build/justinrummel/jr.com-mm
       Destination: /home/travis/build/justinrummel/jr.com-mm/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
              Lunr: Creating search index...
              Lunr: Index ready (lunr.js v0.4.5)
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: minimal-mistakes/skins/air. Load paths: /home/travis/build/justinrummel/jr.com-mm/vendor/bundle/ruby/2.4.0/bundler/gems/minimal-mistakes-1a2a953dfb21/_sass /home/travis/build/justinrummel/jr.com-mm/vendor/bundle/ruby/2.4.0/bundler/gems/minimal-mistakes-1a2a953dfb21/_sass on line 3
jekyll 3.5.2 | Error:  File to import not found or unreadable: minimal-mistakes/skins/air.
Load paths:
  /home/travis/build/justinrummel/jr.com-mm/vendor/bundle/ruby/2.4.0/bundler/gems/minimal-mistakes-1a2a953dfb21/_sass
  /home/travis/build/justinrummel/jr.com-mm/vendor/bundle/ruby/2.4.0/bundler/gems/minimal-mistakes-1a2a953dfb21/_sass on line 3
The command "./script/cibuild" exited with 1.
```

What is interesting is I set to use ruby 2.4.1, which is later confirmed to be available, yet the error path is referencing `/ruby/2.4.0/`.

``` bash
$ rvm use 2.4.1 --install --binary --fuzzy
$ export BUNDLE_GEMFILE=$PWD/Gemfile
$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
$ rvm --version
rvm 1.29.2 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]
$ bundle --version
Bundler version 1.15.4
```

Not sure if you can see Travis CI outputs, but [here is the link](https://travis-ci.org/justinrummel/jr.com-mm/builds/274617495)
Repo: https://github.com/justinrummel/jr.com-mm

**Comment by mmistakes** [comment]
I've seen that weird version of Ruby too when testing. What I think the issue is, is the missing Sass partials for the new skins. I haven't released it yet so maybe you have some sort of conflict using the `4.5.2` gem and what's currently only on `master` in the MM repo.

When I do a `4.6` release all the new skin stuff will be in the gem, but it's not there yet.

**Comment by mmistakes** [comment]
Think the issue is here in your `Gemfile`

```
gem "minimal-mistakes-jekyll", :github => "mmistakes/minimal-mistakes"
# gem "minimal-mistakes-jekyll", :github => "mmistakes/minimal-mistakes", :branch => 'color-skins'
```

You're using the latest on `master`, which doesn't have the color skin stuff. You need to uncomment that second line if you want that.

Or remove this line from your `/assets/css/main.scss` file.

```scss
@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
```

**Comment by justinrummel** [comment]
ah!  my fault... thought it was released.  Thanks for the help!

**Comment by mmistakes** [comment]
No worries. Should be released soon...
