### ISSUE TITLE
GreedyNav differences

### ISSUE THREAD

**Issue by ohadschn** [mmistakes/minimal-mistakes#1247]
You said something in a another thread about adjustments to GreedyNav.js that had to be made. Here's the diff as it looks today: https://github.com/ohadschn/GreedyNav/commit/7724590baf4ae1d54abfc20ca7caa728fb455a76.

Are these changes still necessary? Could they perhaps be integrated into the main GreedyNav file (e.g. via some sort of configuration / parametrization)? That way future GreedyNav updates would be easy to pull, especially when it gets [properly versioned and uploaded to a CDN](https://github.com/lukejacksonn/GreedyNav/issues/14).

**Comment by mmistakes** [comment]
Yes these changes are necessary. I made some [improvements/bug fixes](https://github.com/mmistakes/minimal-mistakes/commits/master/assets/js/plugins/jquery.greedy-navigation.js) specific for the MM theme.

At this point I would treat this script as a fork of the original.

**Comment by ohadschn** [comment]
Fair enough. If you ever reconsider, integrating these improvements (possibly configurable/parametrized) into `GreedyNav` would allow for a better upgrade story and CDN support.

**Comment by mmistakes** [comment]
Don't think that will be possible due to class names being different and the other changes I made to enhance it specifically for the theme.
