### ISSUE TITLE
404 page not working

### ISSUE THREAD

**Issue by rudvfaden** [mmistakes/minimal-mistakes#125]
The custom 404 page is not working.

**Comment by mmistakes** [comment]
Your [custom 404 page](http://rudvfaden.github.io/jdfjlsajkjksldjfkldjkldfsjfklds) is working just fine from what I can tell (except for the broken feature image at the top of the page).

If you're trying to test it locally, then yes it won't work. The WEBrick server Jekyll uses doesn't know anything about a custom 404 page to fire up.

**Comment by rudvfaden** [comment]
When I try to test the 404 site on github i just see this

![screen shot 2015-02-22 at 19 58 27](https://cloud.githubusercontent.com/assets/2445577/6319863/5f2ac63c-bacd-11e4-9ced-aa9e0cd9cf52.png)

If I look at the `404.md` it has a text. 

`Sorry, but the page you were trying to view does not exist --- perhaps you can try searching for it below.`

But it never shows up.

**Comment by rudvfaden** [comment]
Sorry. I worked when i removed the image.

**Comment by mmistakes** [comment]
Not sure I follow what you're asking.

The search box that appears on the page is a Google Search box. If your site hasn't been indexed yet from Google you're not going to get any results. I only included it as a sample of what you might want to put on your 404 page. It's up to you to customize it to fit your site's needs.

**Comment by rudvfaden** [comment]
Sorry. I all worked out when i removed the link to the image that didn't exist.
