### ISSUE TITLE
Tags for collections does not work properly

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#1256]
- [ ] This is a question about using the theme.
- [x] This is a feature request.
- [x] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.5.0
- **GitHub Pages hosted:** yes

---

## Expected behavior

I was expecting that tags on collections was also working properly and could be mixed with the _posts tags, but as seen here: https://travis-ci.org/vih/historie#L1139 the tags are not existent on the tags page.

## Steps to reproduce the behavior

Create a collection. Add tags and then see the failing links.

**Comment by mmistakes** [comment]
This is how Jekyll works with tags. They're only used for `posts`. I believe there is a discussion on `jekyll/jekyll` about extending them to collections, but not sure if its being considered by the core team.
