### ISSUE TITLE
Links in headers does not play well with TOC

### ISSUE THREAD

**Issue by alukach** [mmistakes/minimal-mistakes#126]
As the default CSS and Kramdown settings are configure, if you have a heading that contains a link, such as:
``` markdown
## Running Jekyll

### [This is a link](http://github.com)
```
The HTML will render as:
```html
<ul id="markdown-toc">
  <li><a href="#running-jekyll">Running Jekyll</a>
    <ul>
      <li><a href="#this-is-a-linkhttpgithubcom"><a href="http://github.com">This is a link</a></a></li>
    </ul>
  </li>
</ul>
```

The nested `<a>` tags aren't valid HTML, and render in Chrome's DOM as:
```html
<ul>
    <li>
        <a href="#this-is-a-linkhttpgithubcom"></a>
        <a href="http://github.com">This is a link</a>
    </li>
</ul>
```

This doesn't particularly play nicely with the TOC's styling, as the empty `<a>` tag is added as an entry:

![screen shot 2015-02-22 at 12 57 36 pm](https://cloud.githubusercontent.com/assets/897290/6320088/6c9de578-ba92-11e4-9fe5-9bfcc0b444d6.png)

The first empty space will link internally to the position of the link on the page.  The second "This is a link" entry will follow the external link.  The ideal scenario would be where Kramdown scrubbed any links from elements that are used to build the TOC.

I'm happy to do the work to resolve this but I wanted to see if anyone could provide some suggestions. I've messed around with Kramdown options (`remove_block_html_tags`, `remove_span_html_tags`, `parse_span_html`, `parse_block_html`), nothing seems to do the trip.

**Comment by mmistakes** [comment]
I've run into this myself and haven't come up with a great way around it, other than not putting links in headings or limiting the amount of levels.

There's probably some fancy CSS you could work up to `display: none;` the empty anchors but I've never been motivated enough to bother with it.

**Comment by mmistakes** [comment]
Also, the Kramdown options you included above likely wouldn't effect the automatic table of contents generator part of Kramdown, I think they're only for specify how it parses text for Markdown purposes.

There are a [set of options specific for the TOC generator](http://kramdown.gettalong.org/converter/html.html#toc) that might be helpful.

**Comment by alukach** [comment]
Ah, you're totally right, thanks for pointing that out.  I'll plug away at this over the next couple of weeks and see if I can find an acceptable solution.

**Comment by alukach** [comment]
Settled for a hacky-fix by adding the following code to bottom of the base template:

```html
<script>
// Remove odd bug with nested <a> tags in TOC
$('#markdown-toc li a + a').each(function() {
  $(this).prev().text(this.text);
  this.remove();
});
</script>
```

Not ideal but sufficient for my purposes.
