### ISSUE TITLE
Custom /404/index.html location

### ISSUE THREAD

**Issue by Huixiong91** [mmistakes/minimal-mistakes#1263]
- [x] This is a question about using the theme.

As I am using firebase for hosting, it requires me to place my custom 404 page on the root directory itself named `404.html`. Currently it is being generated on `/404/index.html` instead. May I know how should I go about customising the location?

**Comment by mmistakes** [comment]
Consult Jekyll's documentation about [setting a page's permalink](https://jekyllrb.com/docs/permalinks/).

Closing as this isn't a theme issue.
