### ISSUE TITLE
Missing out the box dependency

### ISSUE THREAD

**Issue by DrValani** [mmistakes/minimal-mistakes#127]
Hi, it maybe useful to add nodejs as a dependency to running your theme. 

I followed your instructions out the box but got the following error when running 
    bundle exec jekyll build

I got the following error:

/var/lib/gems/1.9.1/gems/execjs-2.2.2/lib/execjs/runtimes.rb:51:in `autodetect': Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
	from /var/lib/gems/1.9.1/gems/execjs-2.2.2/lib/execjs.rb:5:in `<module:ExecJS>'
	from /var/lib/gems/1.9.1/gems/execjs-2.2.2/lib/execjs.rb:4:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/coffee-script-2.3.0/lib/coffee_script.rb:1:in `require'
	from /var/lib/gems/1.9.1/gems/coffee-script-2.3.0/lib/coffee_script.rb:1:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/coffee-script-2.3.0/lib/coffee-script.rb:1:in `require'
	from /var/lib/gems/1.9.1/gems/coffee-script-2.3.0/lib/coffee-script.rb:1:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `require'
	from /var/lib/gems/1.9.1/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/jekyll-2.5.1/lib/jekyll/deprecator.rb:46:in `require'
	from /var/lib/gems/1.9.1/gems/jekyll-2.5.1/lib/jekyll/deprecator.rb:46:in `block in gracefully_require'
	from /var/lib/gems/1.9.1/gems/jekyll-2.5.1/lib/jekyll/deprecator.rb:44:in `each'
	from /var/lib/gems/1.9.1/gems/jekyll-2.5.1/lib/jekyll/deprecator.rb:44:in `gracefully_require'
	from /var/lib/gems/1.9.1/gems/jekyll-2.5.1/lib/jekyll.rb:166:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/jekyll-2.5.1/bin/jekyll:6:in `require'
	from /var/lib/gems/1.9.1/gems/jekyll-2.5.1/bin/jekyll:6:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

Hope this helps

**Comment by mmistakes** [comment]
This looks more like you have a gem conflict. To my knowledge Jekyll doesn't use Node at all, it's all Ruby based. Did you update your gemfile at all? How's it compare to the one I bundled with theme? I'm pretty certain one of the gems either didn't install properly or is causing a ruckus with another one.

I've found that some of the newer versions of certain gems don't always play nice with other Jekyll dependencies, especially anything related to Pygments or if you're trying to run Jekyll on a Windows machine.

I do include some Grunt tasks for concatenating JavaScript files for the theme and optimizing images. In that case you need to have Node installed. But these have nothing to do with Jekyll and running `build` or `serve`.

**Comment by DrValani** [comment]
Hi Michael,

I didn't update my gemfile. After running app-get install nodejs, it
started working.
Other posts have suggested adding gem therubyracer.

I am running Jekyll on an ubuntu machine, and I would certainly not rule
out a gem conflict. Anyway,
I shall probably try and run this off a vagrant box instead of my local box
and see how I get on.

Regards

Yogi

On 23 February 2015 at 20:00, Michael Rose <notifications@github.com> wrote:

> This looks more like you have a gem conflict. To my knowledge Jekyll
> doesn't use Node at all, it's all Ruby based. Did you update your gemfile
> at all? How's it compare to the one I bundled with theme? I'm pretty
> certain one of the gems either didn't install properly or is causing a
> ruckus with another one.
>
> I've found that some of the newer versions of certain gems don't always
> play nice with other Jekyll dependencies, especially anything related to
> Pygments or if you're trying to run Jekyll on a Windows machine.
>
> I do include some Grunt tasks for concatenating JavaScript files for the
> theme and optimizing images. In that case you need to have Node installed.
> But these have nothing to do with Jekyll and running build or serve.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mmistakes/minimal-mistakes/issues/127#issuecomment-75619642>
> .
>

-- 


This email, including attachments, is private and confidential. If you have 
received this email in error please notify the sender and delete it from 
your system. Emails are not secure and may contain viruses. No liability 
can be accepted for viruses that might be transferred by this email or any 
attachment. Any unauthorised copying of this message or unauthorised 
distribution and publication of the information contained herein are 
prohibited.

7digital Limited. Registered office: 69 Wilson Street, London EC2A 2BB.
Registered in England and Wales. Registered No. 04843573.

**Comment by mmistakes** [comment]
Digging into it more it's related to the CoffeeScript gem Jekyll uses. It's a [known issue](https://github.com/jekyll/jekyll/issues/2327) with Jekyll and isn't specific to my theme, so best to take the discussion there. 

As someone who doesn't use CoffeeScript it'll be nice when it's made optional in Jekyll 3 to avoid any unnecessary dependencies, especially since it sounds like `therubyracer`can take awhile to install.
