### ISSUE TITLE
Comments section disappeared after moving to GitLab pages

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#1272]
I'm trying to move my blog to HTTPS, and since GitLab Pages supports HTTPS for custom domains, but GitHub doesn't, I set up an initial repo in GitLab using the Gem version. After some fidgeting, the blog is up and running but the comments section disappeared. See below page for example:
https://asarkar.gitlab.io/technical/spring-cloud-config/

I've comments enabled in `_config.yml` using `staticman` and it works fine locally. If you've Docker installed, you can run the following command and the site will come up on port 4000.
```
curl -sSL https://raw.githubusercontent.com/asarkar/non-compos-mentis/master/docker-compose.yml | docker-compose -f - up -d
```

**Comment by asarkar** [comment]
It may be due to my mistake. Will reopen ticket after checking again. Thanks for the awesome theme.

**Comment by asarkar** [comment]
For the record, the following changes fixed the issue, although I've no clue why:
```
name                     : &name "Abhijit Sarkar"
 description              : "thoughts().random()"
 url                      : "https://asarkar.gitlab.io"
-# baseurl                  : ""
+baseurl                  : # the subpath of your site, e.g. "/blog"
+repository               : "asarkar/asarkar.gitlab.io"
```

**Comment by mmistakes** [comment]
Not sure I don't use GitLab. Maybe your paths weren't `https` and the browser wasn't loading something because it thought it was insecure. 

You can verify that by opening your browser's web development tools and checking the console for errors.

**Comment by ohadschn** [comment]
FYI, you can [get HTTPS on GitHub pages with a custom domain using CloudFlare](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/). 

Having said that, I still recommenced GitLab due to its gem-based theme support. You can see how I implemented it here: https://gitlab.com/ohadschn/ohadschn.gitlab.io/blob/master/.gitlab-ci.yml.

**Comment by asarkar** [comment]
Moved to [Netlify](https://www.netlify.com/), as they have everything I need, for *free*. I can keep my code on GitHub (not GH Pages), and Netlify will manage deploy, SSL cert and DNS. Really cool! I didn't really liked GitLab, they have close to 10k bugs open, which doesn't say much about their quality, and they deploy fails randomly.

**Comment by ohadschn** [comment]
@asarkar well to be fair Netlify is not open source so you don't know how many bugs they would have had open...

**Comment by asarkar** [comment]
@ohadschn True, but I opened 2 tickets and they responded within a few hours. For a free account, it's impressive customer service.

**Comment by ohadschn** [comment]
@asarkar agreed. And to be honest I can't say the same about GitLab, where it seems they largely ignore user issues, or at best respond after [more than a week](https://gitlab.com/gitlab-org/gitlab-pages/issues/81#note_41142983). Still, I'm happy with what they offer so far, so to each his own...
