### ISSUE TITLE
Make it explicit that Staticman doesn't work with anything other than GitHub

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#1273]
I recently moved from GitHub Pages to GitLab pages because GH doesn't support HTTPS for custom domains. Unfortunately, I lost all comments in the process because Staticman doesn't (yet) support GL (https://github.com/eduardoboucas/staticman/issues/22). If this had been made explicit in the docs, I'd not have chosen them to begin with. I'm now using Disqus as the comment provider. The same problem would occur for any kind of hosting solutions (which I was seriously considering before finding GL Pages).

**Comment by VincentTam** [comment]
Staticman now supports Gitlab Pages _in principle_.  See eduardoboucas/staticman#219.
