### ISSUE TITLE
Archive permalinks are inconsistent

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#1274]
category.archive.html -> `/categories/`
collection-archive.html -> `/collection-archive/`
page-archive.html -> `/page-archive/`
portfolio-archive.html -> `/portfolio/`
recipes-archive.html -> `/recipes/`
tag-archive.html -> `/tags/`
year-archive.html -> `/year-archive/`

Apart from the fact that some permalinks have the word `archive` in them, others don't, the file names are also inconsistent. `recipes` is plural, whereas the other files are named in a singular fashion.

**Comment by mmistakes** [comment]
These are just samples for testing purposes. You can name them whatever you want.

**Comment by asarkar** [comment]
@mmistakes That's true, but to keep in sync with your site, wouldn't it be better if these are named consistently? Otherwise, whenever I do an upgrade, I've to go through each file that's different and decide whether or not I want to keep it.

**Comment by mmistakes** [comment]
These sample pages will never be updated as a part of the core theme files. They aren't bundled in the gem and they only live under `/docs`which I use to build the demo site. 

They're in the repo only as an example and not meant to be used as is.

**Comment by mmistakes** [comment]
You shouldn't be syncing with any of the files under `/docs` or `/test`. They aren't theme files.

**Comment by asarkar** [comment]
I'm afraid that's not entirely true because the docs link to some of these files from `docs/_pages` for archive settings, and ask that those be copied over.

> Note: these are simply hash (fragment) links into the full taxonomy index pages. For them to resolve properly, the category and tag index pages need to exist at /categories/index.html (copy to _pages/category-archive.html) and /tags/index.html (copy to _pages/tag-archive.html).

**Comment by mmistakes** [comment]
For reference. They're linked and mentioned as examples, meant for you to copy, adjust, and learn from. 

 A theme is the layout and style, these are pages.... which is content.
