### ISSUE TITLE
Previous button does not point to page2

### ISSUE THREAD

**Issue by timedreamer** [mmistakes/minimal-mistakes#1287]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---
## Expected behavior

Hi, I still got the issue that the previous button on recent post does not pointing to `page2` after I add the `url: "https://timedreamer.github.io"`. When I open [my website](https://timedreamer.github.io/), it automatically on page 2. And the `Previous` button goes to the same page. Here is [my repo](https://github.com/timedreamer/timedreamer.github.io).

Did I do anything wrong?

Thanks!

**Comment by mmistakes** [comment]
Yes, you setup your `index.html` with a `permalink`. As per the Jekyll [documentation for pagination](http://jekyllrb.com/docs/pagination/#enable-pagination), you shouldn't do that.

![image](https://user-images.githubusercontent.com/1376749/31096073-ff64f4ce-a788-11e7-8c88-7016f99883d2.png)

Just remove `permalink: /` from `index.html` and everything should work. I just did that with a fork of your repo and the homepage displays as expected.

![image](https://user-images.githubusercontent.com/1376749/31096207-60e5c9ee-a789-11e7-8330-9b945392ee6e.png)

**Comment by timedreamer** [comment]
Awesome! Thank you so much!
