### ISSUE TITLE
System font renders incorrectly in Chrome on macOS/OS X

### ISSUE THREAD

**Issue by tony-ho** [mmistakes/minimal-mistakes#1289]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.6.0
- **Jekyll version:** 3.5.2
- **GitHub Pages hosted:** yes
- **Operating system:** macOS

---

## Expected behavior

San-serif fonts in Chrome on macOS and OS X (El Capitan) should render as San Francisco but are rendering as Helvetica Neue.

## Steps to reproduce the behavior

Browse to the following Minimal Mistakes 4.6.0 URL:
https://mmistakes.github.io/minimal-mistakes/docs/installation/

Inspect any body text using Chrome DevTools:
![existing](https://user-images.githubusercontent.com/24859148/31123524-0a9a6190-a88c-11e7-9e4b-4752e1534ac8.png)

The named fonts `.SFNSText-Regular` and `San Francisco` do not resolve and Chrome falls back to `Helvetica Neue`.

This renders correctly when using the Chrome supported `BlinkMacSystemFont` instead of the private font names.

![fixed](https://user-images.githubusercontent.com/24859148/31123527-10466de6-a88c-11e7-8963-d3237ac23e87.png)

> Chrome now supports a BlinkMacSystemFont generic font name that behaves like Safari’s -apple-system.

Ref: http://furbo.org/2015/07/09/i-left-my-system-fonts-in-san-francisco/

**Comment by mmistakes** [comment]
Happy to look at a PR if you want to take a stab at fixing this.

**Comment by mmistakes** [comment]
Nevermind... just saw your PR :smile:
