### ISSUE TITLE
fonts.googleapis.com

### ISSUE THREAD

**Issue by Sciss** [mmistakes/minimal-mistakes#129]
I'm reading this article ["Google Webfonts, The Spy Inside? "](http://fontfeed.com/archives/google-webfonts-the-spy-inside/), and I'm generally not comfortable linking to anything Google. So I took a look at the page source, and I wonder what the implications of the following line are:

```html
<link href='//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700%7CPT+Serif:400,700,400italic' rel='stylesheet' type='text/css'>
```

What does this line actually do, and what does it imply with respect to capabilities of Google to create meta-data from people using my website. Is it possible to replace this line by something on my site itself?

**Comment by mmistakes** [comment]
It's used to load custom webfonts hosted by Google which are then referenced in the site's stylesheet. If you don't want to use the ones Google provides you can easily remove that line and either replace with another type service, host your own web fonts, or just opt to use default system fonts (Arial, Verdana, Courier, Georgia, etc).
