### ISSUE TITLE
Remote SVG doesn't render when embedded with kramdown

### ISSUE THREAD

**Issue by sdruskat** [mmistakes/minimal-mistakes#1297]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [X] I believe this to be a bug with the theme.
  - [X] I have updated all gems with `bundle update`.
  - [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** minimal-mistakes-jekyll (4.6.0, 4.5.2)
- **Jekyll version:** 3.6.0
- **GitHub Pages hosted:** yes
- **Operating system:** Ubuntu 16.04

---

## Expected behavior

When I embed a remote SVG, it is rendered.

## Steps to reproduce the behavior

Include the following in kramdown:

    ![doesn't work](https://zenodo.org/badge/DOI/10.5281/zenodo.1003150.svg)

Instead of rendering the image ![](https://zenodo.org/badge/DOI/10.5281/zenodo.1003150.svg), the alt text shows.

**Comment by mmistakes** [comment]
The reason this doesn't work for you is related to the headers from the server hosting that SVG. See [this thread on Stackoverflow](https://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown) for context.

The reason that Markdown above works on GitHub is they're doing some "magic" to serve up the `zenodo.org` SVG from one of their servers. If you inspect the rendered `<img>` element above you'll see the source changed to one that GitHub controls and can properly serve the correct headers.

```html
<img src="https://camo.githubusercontent.com/c90e4afcfa9d468ee4dda636d82ede8883b90b16/68747470733a2f2f7a656e6f646f2e6f72672f62616467652f444f492f31302e353238312f7a656e6f646f2e313030333135302e737667" alt="" data-canonical-src="https://zenodo.org/badge/DOI/10.5281/zenodo.1003150.svg" style="max-width:100%;">
```

Closing as this has nothing to do with the theme.
