### ISSUE TITLE
Dropdown menu title

### ISSUE THREAD

**Issue by bmenicucci** [mmistakes/minimal-mistakes#1301]
- [x] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.6
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** Mac OS

---

## Expected behavior

Is it possible to have a dropdown item in the nav bar, like bootstrap?

**Comment by mmistakes** [comment]
The menu currently follows the "priority plus" pattern and isn't something I'm interested in supporting.

If you want a navigation bar similar to Bootstrap's you'll need to use a Bootstrap theme or customize the theme. Here's some Jekyll resources to get you started if you want to build your own.

- https://thinkshout.com/blog/2014/12/creating-dynamic-menus-in-jekyll/
- http://planetjekyll.github.io/snippets/nav-with-data.html
- https://github.com/forestryio/jekyll-menus
- https://gist.github.com/kasperisager/9416313

**Comment by bmenicucci** [comment]
Michael, thank you for your prompt reply.
However, I like your theme so I'm going to try to customize it.
Have a nice day
