### ISSUE TITLE
Enhance theme to fully support jekyll-paginate-v2 plugin

### ISSUE THREAD

**Issue by jaybe-jekyll** [mmistakes/minimal-mistakes#1307]
Feature request to add support for:

- [ ] **jekyll-paginate-v2** [Pagination Generator](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md)
- [ ] **jekyll-v2-paginate** [Auto-Pages](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md) for generating tag and category archives (similar to [Jekyll Archives implimentation](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings))

---

Notes:

1. The `minimal-mistakes-jekyll` gem has an `_includes/paginator.html` include which gets included to produce the paging navigation and [lovely] UI. See the theme's `_layouts/home.html` layout for the calling.

  - The `include` refers to `site.pagination_path` to build the [proper] reference links to navigate between pages.
  - Note `site.pagination_path` refers to `jekyll-paginate` (version 1), not v2.  Ergo, out of box, `minimal-mistakes-jekyll` gem is not designed to be compatible with `jekyll-pagination-v2`.
  - For example, if you try to use pagination outside of root path/URI `/` breakage will occur with pagination... unless adaptation to `_includes/paginator.html` has been accommodated.
    - e.g. `...{{ page.pagination.mypaginator_path | replace: ':cat', page.autopages.display_name | replace: 'page:num', '' | replace: '//', '/' | absolute_url %}}...`

2. The default `_config.yml` for `minimal-mistakes-jekyll` theme/gem does not contain configuration for `jekyll-paginate-v2`, which requires new/additional/different configuration to enable... both in _config.yml and then within the pages where you desire pagination, e.g.:

- **/index.html**
  ```
  ---
  ...
  layout: my_home_layout_pagination_ready
  pagination:
    enabled
    per_page: 2
    ...
  ---
  ```

I was eventually able to integrate and implement:
- minimal-mistakes-jekyll
- jekyll-paginate-v2
  - ...along with it's AutoPages feature to generate category, tag, collection pages, etc.

It required addressing the aforementioned aspects however, which meant having the following files and adjusted outside of the `minimal-mistakes-jekyll` gem theme:
- `./_layout/home.html`
- `./_layout/archive-taxonomy.html`
- `./_includes/paginator.html`
- `./index.html`
- `./_config.yml` (expected)

Would very much like to see `jekyll-paginate-v2` integration and capabilities without the need to maintain and manage core theme files within the site/source.  Wonderful theme and offering!  Thank you @mmistakes!

re: #1240 
re: [#issuecomment-337258095](https://github.com/mmistakes/minimal-mistakes/issues/1240#issuecomment-337258095)

**Comment by jaybe-jekyll** [comment]
related: https://github.com/jekyll/jekyll/issues/6391

**Comment by douglangille** [comment]
This is what I did to get it to work on https://douglangille.ca with the gem'd theme:

https://github.com/douglangille/douglangille/blob/master/_config.yml
https://github.com/douglangille/douglangille/blob/master/_includes/paginator.html
https://github.com/douglangille/douglangille/blob/master/_layouts/autopage.html

As mentioned elsewhere, moving from jekyll-paginate to jekyll-paginate-v2 will remove the need for jekyll-archives. There will need to be some cleanup in a few places to fix that up. Right now, I have to leave references to jekyll-archives in _config.yml because I'm lazy.

I like @mmistakes' hand-rolled trailpath in paginator.html and I had to hack at it to get it to work with jekyll-paginate-v2. Moving to the new gem's trailpath functionality is ultimately cleaner tho.

**Comment by fantasticfears** [comment]
If @mmistakes wants to support `github-pages` then `jekyll-paginate-v2` is not really an option since it's not included in the gem yet.

**Comment by mmistakes** [comment]
I'd be up for rolling in support for the superior jekyll-paginate-v2 plugin if/when it gets allowed on GitHub Pages. Same for its autopages feature.

I use both on my personal site, but not sure if there is a way to do them now and give the user a choice of falling back to the whitelisted gems. I sort of do that with Jekyll Archives support, but it's kind of messy and makes configuring confusing, especially for those not familiar with Jekyll.

**Comment by johnlane** [comment]
For anyone looking to implement `jekyll-paginate-v2` now, coming here to find the links from @douglangille are dead,  there is a compatible version of ` _includes/paginator.html` [here][1]. I found that it offers the same behaviour as the theme's support for the default paginator.


Alternatively please read the [blog post][2] by @mmistakes.

@mmistakes you mention that you use `jekyll-paginate-v2` on your own site - if your config is better (or more robust, or whatever) than [that what I linked to][1] then would you mind sharing a gist that we might use until the theme catches up? (great theme, by the way!!!)

[1]: https://github.com/dev4223/ondata/blob/c5c900f3e81672b69f635389f9294415f671f8f5/_includes/paginator.html
[2]: https://mademistakes.com/articles/using-jekyll-2017/

**Comment by mmistakes** [comment]
@johnlane I use jekyll-paginate-v2 on my own site but that's a completely different theme from Minimal Mistakes. So the config settings is likely not 1:1. I'm also using the plugins Autopage feature to generate tag archives.

**Comment by WizKidd42** [comment]
Enhancement

**Comment by iBug** [comment]
Can we get some insights on this? Paginate V2 is AWESOME and I'm trying to patch MM to adapt it for my site.

If needed, I can provide assistance or even fire up a PR for this.

**Comment by luispuerto** [comment]
@iBug I would love to have paginate-v2 support! since I would like to be able to paginate paginate my jekyll archives, but I think that theme-wise we shouldn't drop compatibility with jekyll-paginate. Not everyone wants to build outside gh-pages
