### ISSUE TITLE
Help with custom plugin and CSS

### ISSUE THREAD

**Issue by igoratencompass** [mmistakes/minimal-mistakes#1323]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes/no
- **Operating system:** 

---

## Steps to reproduce the behavior

Hi Michael,

I'm trying to set a go-to-top button on the site via a JQuery plugin I've been using elsewhere. I have put the plugin under `assets/js/simple-jekyll-search.min.js` and tried to include the CSS in the following CSS:

```
<!-- UItoTop (go to top) plugin -->
<script type="text/css">
#toTop {
        display:none;
        text-decoration:none;
        position:fixed;
        bottom:10px;
        right:10px;
        overflow:hidden;
        width:51px;
        height:51px;
        border:none;
        text-indent:-999px;
        background:url("{{ site.baseurl }}/assets/images/ui.totop.png") no-repeat left top;
}

#toTopHover {
        background:url("{{ site.baseurl }}/assets/images/ui.totop.png") no-repeat left -51px;
        width:51px;
        height:51px;
        display:block;
        overflow:hidden;
        float:left;
        opacity: 0;
        -moz-opacity: 0;
        filter:alpha(opacity=0);
}

#toTop:active, #toTop:focus {
        outline:none;
}
</script>
```

in the  `_includes/head/custom.html` but without success. What would be the best way to get this working?

Thanks,
Igor

**Comment by mmistakes** [comment]
The problem likely is you're trying to load inline CSS with the `<script>` tag instead of `<style>`.

Try this instead:

```html
<!-- UItoTop (go to top) plugin -->
<style>
<!-- your custom CSS -->
</style>
```

And not:

```html
<script type="text/css">
<!-- your custom CSS -->
</script>
```

**Comment by igoratencompass** [comment]
Well that was really embarrassing, I'm getting old :-(

Thanks
