### ISSUE TITLE
Featured post

### ISSUE THREAD

**Issue by anbasile** [mmistakes/minimal-mistakes#1329]
- [X ] This is a feature request.
---

## Environment informations

- **Minimal Mistakes version: 4.6** 
- **GitHub Pages hosted:** yes
 

---

## Expected behavior

I would like to have on my page page a feature post that list more content and displays the header image. Something like  the [Casper theme for ghost](https://blog.ghost.org/):

![screenshot from 2017-11-02 16-34-14](https://user-images.githubusercontent.com/13586519/32334904-f20db25e-bfeb-11e7-96f8-75a39a9a67a6.png)

Do you think is this possible with the present theme somehow?

**Comment by mmistakes** [comment]
You could probably hack up something using the [feature row helper](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#feature-row) for the larger "featured" post and then the grid view for below.

Other than that you might want to look for a theme that does this layout specifically. I know I've seen quite a few Ghost theme ports for Jekyll.

**Comment by anbasile** [comment]
I have figured out a solution for this.

I created an include, ```featured.html```:
```

{% if post.header.teaser %}
{% capture teaser %}{{ post.header.teaser }}{% endcapture %}
{% else %}
{% assign teaser = site.teaser %}
{% endif %}

{% if post.id %}
{% assign title = post.title | markdownify | remove: "<p>" | remove: "</p>" %}
{% else %}
{% assign title = post.title %}
{% endif %}

<div class="{{ include.type | default: "list" }}__item">
    <article class="archive__item" itemscope itemtype="http://schema.org/CreativeWork">
	<h2 class="archive__item-title" itemprop="headline">
	    {% if post.link %}
            <a href="{{ post.link }}">{{ title }}</a> <a href="{{ post.url | absolute_url }}" rel="permalink"><i class="fa fa-link" aria-hidden="true" title="permalink"></i><span class="sr-only">Permalink</span></a>
	    {% else %}
            <a href="{{ post.url | absolute_url }}" rel="permalink">{{ title }}</a>
	    {% endif %}
	</h2>
	<img src="{{ teaser }}" alt="img">
	{% if post.excerpt %}<p class="archive__item-excerpt" itemprop="description">{{ post.excerpt | markdownify | strip_html | truncate: 160 }}</p>{% endif %}
    </article>
</div>
```
And then I modifed the ```home``` layout:

```
---
layout: archive
---

<h3 class="archive__subtitle">{{ site.data.ui-text[site.locale].featured_post | default: "Featured Posts" }}</h3>

{% assign post = site.posts.first %}
{% include featured.html %}

<h3 class="archive__subtitle">{{ site.data.ui-text[site.locale].recent_posts | default: "Recent Posts" }}</h3>

{% for post in paginator.posts offset:1 limit:2 %}
  {% include archive-single.html %}
{% endfor %}

{% include paginator.html %}
```
And this is the result:

![screenshot from 2017-11-24 17-38-03](https://user-images.githubusercontent.com/13586519/33218661-5e05c9de-d13e-11e7-8b4c-bfc00510acb3.png)

I am still not fully sutisfied but I think this is the right way to do it. I am marking this as closed.
