### ISSUE TITLE
Long table of contents add vertical space to code blocks if they overlap

### ISSUE THREAD

**Issue by carlesfernandez** [mmistakes/minimal-mistakes#1338]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.7.0
- **Jekyll version:** 3.6.0
- **GitHub Pages hosted:** yes
- **Operating system:** macOS 10.13.1

---

## Expected behavior

I expect the Table of Contents to not affect the height of the overlapping code blocks.

## Steps to reproduce the behavior

When I switched from the toc helper to jekyll-toc (activated in the front matter), I noticed that long ToCs add extra vertical space to code blocks if they overlap. 

An online example is here: http://gnss-sdr.org/coding-style/
The website content is here: https://github.com/gnss-sdr/geniuss-place.git

I always can switch back to the toc helper, which did not exhibit this behavior, but I wonder if this possible bug can be fixed in jekyll-toc. I'm quite illiterate in Liquid, so I'm afraid I can't help on this.

Thanks for your time and for your wonderful work on this theme.

**Comment by mmistakes** [comment]
I think something else is at play. From the looks of it you don't have all of the latest layouts, includes, and CSS.

If you take a look at the demo site you should see something like this at the top of your HTML source:

```html
<!--
  Minimal Mistakes Jekyll Theme 4.7.0 by Michael Rose
  Copyright 2017 Michael Rose - mademistakes.com \| @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE.txt
-->
```

and this in your CSS:

```css
/*!
 * Minimal Mistakes Jekyll Theme 4.7.0 by Michael Rose
 * Copyright 2017 Michael Rose - mademistakes.com | @mmistakes
 * Licensed under MIT (https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE.txt)
*/
```

When I check yours there's no version in the HTML and your CSS has:

```css
/*!
 * Minimal Mistakes Jekyll Theme 4.5.2 by Michael Rose
 * Copyright 2017 Michael Rose - mademistakes.com | @mmistakes
 * Licensed under MIT (https://github.com/mmistakes/blob/master/LICENSE.txt)
*//
```

I made some layout adjustments to the right sidebar a few versions ago and doesn't look like your fork incorporates those. You can see in this [sample post](https://mmistakes.github.io/minimal-mistakes/layout-table-of-contents-post/) on the demo site the TOC sidebar doesn't overlap code blocks.

On yours it's also overlapping notice blocks, which tells me it's using the older layout and CSS. This was one of the issues I fixed.

If you haven't made any changes to the theme's core files I'd suggest remove them from your fork, and pulling in the latest `_layouts`, `_includes`, `_sass`, etc. Just to verify if it's your content or theme. I have seen jekyll-toc do some weird things, but that has more to do with extra headings showing up than any sort of overlap with main content.

**Comment by carlesfernandez** [comment]
I see, my mistake then. I will update that. Thanks for looking it out.
