### ISSUE TITLE
Use theme gem on GitHub Pages

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/minimal-mistakes#1339]
GitHub Pages has whitelisted the [Jekyll Remote Theme](https://github.com/benbalter/jekyll-remote-theme) plugin which means Minimal Mistakes can finally be used without needing to fork this repo.

This is apparently in beta, but in my testing everything works as expected. To get up in running follow the instructions for the [installing the Ruby gem version](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#ruby-gem-method) of the theme, then:

**Step 1.** Add the following to your `_config.yml` file

```yaml
plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/minimal-mistakes
```

**Step 2.** Add `gem 'jekyll-remote-theme'` to your Gemfile if building locally with the GitHub Pages gem.

An [example repo](https://github.com/mmistakes/mm-remote-theme-test) can be viewed here, which is [hosted on GitHub Pages](https://mmistakes.github.io/mm-remote-theme-test/).

**Comment by vg** [comment]
Any idea on how to use the different skins/color variations using remote_theme?

**Comment by mmistakes** [comment]
Haven't tested it but should with the same way you'd normally use them, set the skin you want in _config.yml.

```
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
```

**Comment by mmistakes** [comment]
Tested. Adding `minimal_mistakes_skin` and the [variation](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin) you want to your `_config.yml` works as it should.

**Comment by vg** [comment]
I did test it before commenting above. It did not work. Here is the config.yml and the built site. 

https://github.com/vg/mm-remote-theme-test/blob/master/_config.yml
https://vg.github.io/mm-remote-theme-test/

**Comment by LongQi** [comment]
But if I modify the "locale", it did not work.

**Comment by mmistakes** [comment]
@LongQi You still need to commit the [`_data/ui-text.yml`](https://github.com/mmistakes/minimal-mistakes/blob/master/_data/ui-text.yml) file. The test theme repo I built didn't include those so it just defaults back to English.

**Comment by ldt116** [comment]
Please add this good news to the doc, which is easier for newcomers to reach out.

Can you also post some migration guide for someone who forked repo to use the remote theme?

**Comment by mmistakes** [comment]
@ldt116 Docs were updated last week. See GitHub Pages compatible method in the Quick Start instructions.

https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

For migration follow the guidelines under "Setup Your Site." You can ignore since of the Gemfile specific stuff as that only applies to the Ruby gem version.

**Comment by ldt116** [comment]
Oh. Thanks for pointing out. I missed that.
