### ISSUE TITLE
Delete Sample Pages

### ISSUE THREAD

**Issue by twhite96** [mmistakes/minimal-mistakes#134]
Wondering how I delete the sample pages that came with the theme. Last time I tried to get rid of them I messed things. This is just a general question, really.

**Comment by mmistakes** [comment]
I think you just answered your own question, **you delete them** :wink: . 

Go into `_posts` and remove all of the Markdown files and replace with your own. If you don't want the About, Posts listing, or Theme Setup pages to appear delete those too...  [`/about`](https://github.com/mmistakes/minimal-mistakes/tree/master/about), [`/posts`](https://github.com/mmistakes/minimal-mistakes/tree/master/posts), and [`/theme-setup`](https://github.com/mmistakes/minimal-mistakes/tree/master/theme-setup).

And if you want a different homepage modify `index.html` in the root folder.

There's nothing to mess up unless you delete `_layouts`, `_includes` or anything related to the site design. The rest is just content.
