### ISSUE TITLE
Import from Wordpress to Staticman support

### ISSUE THREAD

**Issue by arthurlacoste** [mmistakes/minimal-mistakes#1346]
Hi,

Like you, I think using a static generator like Jekyll could be a good way to replace all kinds of blogs made with WordPress.

To help new comers have already a WordPress blog wanting to use Staticman, there was no real well-documented export/import tool.

I've taken some time to work on [this tool](https://github.com/arthurlacoste/wordpress-comments-jekyll-staticman) who keep your `_data/comments/blog-slug/comment-timestamp.md` structure.

I hope this can be helpful for someone. 

- [ ] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

**Comment by mmistakes** [comment]
Very nice. I'll add a link to your tool in my theme docs under the Staticman section.

**Comment by arthurlacoste** [comment]
Thank you 👍
