### ISSUE TITLE
Is there any way to specify that a portion of a post shouldn't add to the total word count?

### ISSUE THREAD

**Issue by oxfist** [mmistakes/minimal-mistakes#1347]
I'm adding a References section to a post and I'd like that section to be excluded from the total read time. Is there any way to do this?

Thanks in advance.

**Comment by mmistakes** [comment]
No there isn't that I know of. All in doing is using a Liquid filter that counts the amount of words in `{{ content }}` which is then divided to approximate words per minute.

You'd likely need some sort of Jekyll plugin to exclude content from that.

**Comment by oxfist** [comment]
Thanks a lot for your response! I see, would you be willing to a PR if I can implement a filter of some sorts for excluding a block from the count? If so we could figure out how to implement it. I'd be very happy to contribute, I love your theme!

**Comment by mmistakes** [comment]
If the filter is GitHub Pages compatible, flexible, and doesn't add overhead or complexity to the [`read-time.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/read-time.html) include then sure, feel free to submit a PR.

**Comment by oxfist** [comment]
That's great to hear! Could you help me with some guidance as for where should I start? I'd appreciate it so much.

**Comment by mmistakes** [comment]
Sorry, I really have no idea. I don't think this is an easy problem to solve. There's likely some sort of Jekyll plugin you'll need to write, but that won't work for GitHub Pages sites.

Only other thing I can think of is some crazy Liquid code to strip out content, but that seems extremely fragile and prone to breakage.

**Comment by oxfist** [comment]
Sounds tricky, but I'll make some time to check it out either way starting with what you told me. Thanks  again!
