### ISSUE TITLE
Alexa 'Claim your site' has been retired.

### ISSUE THREAD

**Issue by coliff** [mmistakes/minimal-mistakes#1350]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

Alexa.com no longer allow sites to be verified (http://www.alexa.com/siteowners/claim) and is now a paid-for service. I suggest the documentation/feature for this can be removed:
https://mmistakes.github.io/minimal-mistakes/docs/configuration/

**Comment by mmistakes** [comment]
Yeah, think this is safe to remove as a feature.
