### ISSUE TITLE
Why do the Author Profile docs suggest modifying _utilities.scss?

### ISSUE THREAD

**Issue by ohadschn** [mmistakes/minimal-mistakes#1351]
https://mmistakes.github.io/minimal-mistakes/docs/layouts/#author-profile

> Start by copying `_utilities.scss` `<site root>/_sass`. Open it up to the icon section (it’s near the bottom) and nest a new class beneath `.social-icons` that matches the one used to declare the Font Awesome icon. In our case `.fa-reddit`.

Isn't it more desirable (simpler and more gem upgrade safe) to edit `main.scss`? It seems to work...

**Comment by mmistakes** [comment]
That bit of documentation was likely written before there was a Ruby gem version.

Best practice when writing Sass is to break up your styles into components, utility classes, mixins, functions, variables, etc. That is the point of view I was taking when I built the themes and documented.

So it depends. If you're a forker editing `_utilities.scss` is the way to go. If you're Ruby gem installer then dropping in your styles wherever it makes sense to augment the styles is best. The docs could be probably updated to mention both approaches, but that might further complicate things and be too prescriptive.

**Comment by mmistakes** [comment]
Note to self: links to `_variables.scss` and `_utitlities.scss` are broken and need updating to new paths under `/_sass/minimal-mistakes`.
