### ISSUE TITLE
Can it support formula? like latex

### ISSUE THREAD

**Issue by LongQi** [mmistakes/minimal-mistakes#1355]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes/no
- **Operating system:** 

---

**Comment by mmistakes** [comment]
See #735 

You need to add the Latex script.
