### ISSUE TITLE
Disable analytics in development

### ISSUE THREAD

**Issue by maaz93** [mmistakes/minimal-mistakes#1359]
- [ ] This is a question about using the theme.
- [X] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.7.1
- **Jekyll version:** 3.5.2
- **GitHub Pages hosted:** yes
- **Operating system:** macOS 10.10.5

---

## Expected behavior
I realised that [my blog](https://github.com/maaz93/maaz93.github.io)'s page visits were being tracked even in development. This is adding wrong entries into the site analytics. I would expect that the theme has a way to disable analytics in development.

Just to solve the issue quickly, I added `if (window.location.hostname !== "localhost") { ... }` in `google-universal.html`.

But, after [searching a bit](http://david.elbe.me/jekyll/2015/06/08/jekyll-different-settings-production-github-and-development.html), I found that we can use
```
{% if jekyll.environment == 'production' %}
  I'm in production!
{% else %} 
  I'm in development!
{% endif %}
```
I would add this change in `analytics.html`.

If you think this is a valid feature request, I wouldn't mind submitting a PR for this.

**Comment by maaz93** [comment]
This could apply to the comments section as well.

**Comment by mmistakes** [comment]
@maaz93 This sounds like a good idea to me if you want to go ahead and submit a PR. Maybe do them as two separate PRs... one for disabling Google Analytics in nonprod and another for disabling comments.

You can probably piggyback on these lines

[**_includes/analytics.html**](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/analytics.html#L1)

```
{% if jekyll.environment == 'production' and site.analytics.provider and page.analytics != false %}
```

[**_layouts/single.html**](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L66)

```
{% if jekyll.environment == 'production' and site.comments.provider and page.comments %}
```

**Comment by maaz93** [comment]
@mmistakes Sounds good! Should I create a separate issue for disabling the comments or can I use this issue itself for both PRs?

**Comment by mmistakes** [comment]
You can reference this same issue.
