### ISSUE TITLE
GitHub pages build warning

### ISSUE THREAD

**Issue by sfdye** [mmistakes/minimal-mistakes#1366]
Hi, 

Thanks for the awesome jekyll template. I built my site using your theme and deployed to netlify. (not GitHub pages)

Might not be the best place to ask, but every time I commit I got this warning from GitHub. Is there a way disable to this annoying message?

>The page build completed successfully, but returned the following warning for the `master` branch:

> You are attempting to use a Jekyll theme, "minimal-mistakes-jekyll", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

> For information on troubleshooting Jekyll see:

 > https://help.github.com/articles/troubleshooting-jekyll-builds

> If you have any questions you can contact us by replying to this email.

I can't disable GitHub Page either.

![image](https://user-images.githubusercontent.com/1016390/33227298-095aed40-d1db-11e7-93e5-973221af8299.png)

**Comment by nickgarlis** [comment]
Just follow [these instructions](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#github-pages-compatible-methods) to get your site running on github pages. You have to modify your Gemfile and your _config.yml for your site to build on Github. Also, check out this [repository](https://github.com/mmistakes/mm-remote-theme-test).

**Comment by sfdye** [comment]
The thing is, I don’t want to use GitHub Page, because my site is already hosted somewhere else. I need GitHub only as my version control system whilst disabling the warning. Any idea?

________________________________

**Comment by nickgarlis** [comment]
You can make new branch, set it as default and delete master.

**Comment by ohadschn** [comment]
https://help.github.com/articles/unpublishing-a-user-pages-site/

> **Unpublishing a User Pages site**
> You may want to unpublish your GitHub User Pages site if the content is no longer relevant or you no longer want it to be publicly available.
> 
> To unpublish your User Pages site, delete the `master` branch or delete your `username.github.io` repository

**Comment by sfdye** [comment]
@nickgarlis different branch will actually work, I was thinking the same. 

It's shame GitHub doesn't provide a unsubscribe feature for these emails.

**Comment by sfdye** [comment]
@ohadschn Yeah, this works too but I have to set the rule on different clients.

**Comment by ohadschn** [comment]
@sfdye not sure what your e-mail provider is, but usually (GMail, Exchange, etc) you can set those once on the server side (so no need to set it up on multiple clients).
