### ISSUE TITLE
How to control the alignment of navigation list?

### ISSUE THREAD

**Issue by Queequeg92** [mmistakes/minimal-mistakes#1372]
- [x ] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes/no
- **Operating system:** 

---

**Comment by mmistakes** [comment]
What are you hoping the accomplish? Do you have an example of a list you want to change? The entire theme's styling is done through CSS. 

If I have a better idea of what you're wanting to change I can maybe point you to where in `_sass` you'd need to modify.

**Comment by Queequeg92** [comment]
Thanks for your reply! 
If I have a short navigation list, the list is aligned to the right. This looks very weird. I hope the list is aligned to the left just like the following pic.
![2017-12-05 13 08 23](https://user-images.githubusercontent.com/8766653/33591007-d5a775be-d9bd-11e7-8164-23772fc1dc21.png)

**Comment by mmistakes** [comment]
Got it. Those links are aligned used flexbox. You can align them to the "start" (or the left in this case) by removing the following two lines from `.visible-links` in [`_sass/minimal-mistakes/_navigation.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_navigation.scss#L212-L220).

```diff
    .visible-links {
-      -webkit-box-pack: end;
-       justify-content: flex-end;
        ...
```

Or you can override them with instead:

```diff
    .visible-links {
+      -webkit-box-pack: start;
+       justify-content: flex-start;
        ...
```

**Comment by Queequeg92** [comment]
Thank you.:sun_with_face:
