### ISSUE TITLE
[ui-text] zh-HK should be as same as zh-TW

### ISSUE THREAD

**Issue by Covernel** [mmistakes/minimal-mistakes#1374]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations
Nil

---

## Expected behavior
zh-HK should be as same as zh-TW

## Steps to reproduce the behavior
Nil

## Reason
Hong Kong is as same as Taiwan using Traditional Chinese instead of Simplified Chinese

**Comment by mmistakes** [comment]
I don't speak any of these languages so I'll just have to take your word for it. Care to submit a pull request with the fix?

**Comment by fantasticfears** [comment]
I can confirm this because Chinese Wikipedia uses similar approach.
