### ISSUE TITLE
Support tooltips for links in masthead

### ISSUE THREAD

**Issue by maaz93** [mmistakes/minimal-mistakes#1377]
- [ ] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

Sometimes the text displayed in the masthead links are not descriptive enough. If we could have tooltips for the links, we could give more details about what the link represents. For example, "Tags" can have a tooltip "Posts grouped by tags" as a tooltip.

I think this can be supported by adding an extra field in the _navigation.yml called `tooltip` and use it in the `masthead.html` like this

```
<li class="masthead__menu-item"><a href="{{ domain }}{{ link.url }}" title="{{ link.tooltip | default = link.title }}">{{ link.title }}</a></li>
```

If it seems like a valid request, I would love to submit a PR for this.

**Comment by mmistakes** [comment]
Sounds good to me. Maybe to keep things simple just add `title`. The `tooltip` override seems unnecessary as I'm thinking most will just use title for the tooltip text anyways.

**Comment by maaz93** [comment]
Alright. While I'm at it, do you think I could add tooltips to other links, like social media links for the author, the footer etc. ? I could change this issue as a general support for tooltips, if that makes sense.

**Comment by mmistakes** [comment]
Not sure how much value they'd add elsewhere. My feeling is most of the links are already descriptive of what they are. I want to avoid overcomplicating configuration and the templates.

**Comment by maaz93** [comment]
Alright. Sounds good to me. I'll just change the links in the masthead.
