### ISSUE TITLE
Can I bump jekyll version?

### ISSUE THREAD

**Issue by fantasticfears** [mmistakes/minimal-mistakes#1384]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

Since I'm using MRI 2.4+, the dependency fails because of old gems are incompatible with Ruby 2.4 in old `jekyll`. But I notice `github-pages` has bumped to `jekyll` 2.6 which should solve the problem. Mind a PR?

**Comment by mmistakes** [comment]
I think it's safe to bump to `3.6`, same as the GitHub Page gem.
