### ISSUE TITLE
disqus comments are not loading

### ISSUE THREAD

**Issue by prasadmuley** [mmistakes/minimal-mistakes#139]
Every post file contains **comments: true** to load disqus
So disqus should load in every post.

But disqus loads in [code highlighting post] (https://mmistakes.github.io/minimal-mistakes/code-highlighting-post/). It doesn't load in other posts.

**Comment by mmistakes** [comment]
They're working fine on the demo site just fine, something must be screwy on your fork. You have the Disqus shortname set in `_config.yml` as well right?

**Comment by prasadmuley** [comment]
@mmistakes Yes. I've set it to [rootpy](https://disqus.com/by/rootpy/) But not showing it.
I forked it 2 days ago and I don't think you've updated your repo in last 2 days.

disqus was loading only for  [code highlighting post](https://mmistakes.github.io/minimal-mistakes/code-highlighting-post/) when I checked on live and decided to report here.

You can check it by visiting my first post [Hello World](http://rootpy.com/Hello-World/)

It says **We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.**

**Comment by mmistakes** [comment]
Sounds like a Disqus issue. I've seen this happen before and usually is a
cookie problem. You can verify if that's the case by opening the page in
Chrome incognito mode or by clearing your browser/cookie cache.

**Comment by prasadmuley** [comment]
@mmistakes. 
I had deleted cookie cache and Disqus isn't loading in chrome incognito mode or priavate browing in firefox. 

Checked disqus documentation for jekyll and I've entered correct user_name there.
I am not able to figure out why is it not loading in [Hello World!](http://rootpy.com/Hello-World/)

**Comment by mmistakes** [comment]
Well the problem isn't Jekyll or the theme. Looks to me you haven't registered a shortname for your site on Disqus yet. If you had [rootpy.disqus.com](http://rootpy.disqus.com) would work and it doesn't. **rootpy** is your username and a *shortname*. 

[Check out this page on Disqus](https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-) on more info on how to setup one for your site. After you create a shortname for your site then replace `rootpy` in your `_config.yml` Disqus should work properly.

**Comment by prasadmuley** [comment]
@mmistakes Yes. I forgot to add my **website**'s  **shortname**
I thought **username** and **shortname** are same.
It is working in [Hello World!](http://rootpy.com/Hello-World/)
Thanks for pointing my mistake.

**Comment by Robifarlo** [comment]
I have been successful with the problem, by simply replacing a new account using the account facebook or tweeter. Previously, it was the same account to the account of my website

**Comment by navneet1991** [comment]
disqus comment not displaying not my website..

http://androidtoall.com/best-wordpress-free-responsive-theme/

**Comment by mmistakes** [comment]
@navneet1991 

1. Your site isn't using the Minimal Mistakes theme.
2. Your site is using Wordpress and not Jekyll.
3. Disqus is indeed working on your site.

![screen shot 2017-01-11 at 7 05 28 am](https://cloud.githubusercontent.com/assets/1376749/21847950/7f909af0-d7cc-11e6-8e33-bcade753f3a7.png)
