### ISSUE TITLE
How do you select a skin? Can you add it to the readme?

### ISSUE THREAD

**Issue by viktorsmari** [mmistakes/minimal-mistakes#1390]
- [x] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes/no
- **Operating system:** 

---

**Comment by mmistakes** [comment]
It's all in the documentation.

https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin

**Comment by viktorsmari** [comment]
Thank you. 

I relied on the search and 'skin' gave me 0 results.

**Comment by mmistakes** [comment]
The searc
