### ISSUE TITLE
Is it possible to invert the order for the next/previous buttons?

### ISSUE THREAD

**Issue by wAuner** [mmistakes/minimal-mistakes#1391]
- [x ] This is a question about using the theme.

---

I have a site where I list my projects in a grid, I include them in reversed order, such that the most recent (=the highest number in the filename) file e.g. 07.md gets shown first, then 06.md and so on. So the most recent file is on the top left in the grid and the oldest, 00.md, is in the bottom right corner. [This](http://localhost:4000/projects/) is my how my project page looks.
The problem now is that the next/previous buttons in the project articles are reversed to that order. The next button goes to the file next in the ascending order, but that is counterintuitive in my case, I want it to move descending.

Is there are an easy way I can achieve that? Not sure where to look. 
Thanks

**Comment by mmistakes** [comment]
Hack the [post pagination include](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/post_pagination.html) to be reversed.

Or change the next/previous text to be the opposite in `_data/ui-text.yml`.

```yaml
pagination_previous: "Next"
pagination_next: "Previous"
```

Just note that either of these changes will be applied globally. If you want to be more surgical with it you may need to make your own layout to apply selectively.

**Comment by wAuner** [comment]
thanks you're awesome!
I modified the `post_pagination.html` to the following:
```
  {% assign next = page.previous %}
  {% assign previous = page.next %}

  <nav class="pagination">
    {% if previous %}
      <a href="{{ previous.url | absolute_url }}" class="pagination--pager" title="{{ previous.title | markdownify | strip_html }}">{{ site.data.ui-text[site.locale].pagination_previous | default: "Previous" }}</a>
    {% else %}
      <a href="#" class="pagination--pager disabled">{{ site.data.ui-text[site.locale].pagination_previous | default: "Previous" }}</a>
    {% endif %}
    {% if next %}
      <a href="{{ next.url | absolute_url }}" class="pagination--pager" title="{{ next.title | markdownify | strip_html }}">{{ site.data.ui-text[site.locale].pagination_next | default: "Next" }}</a>
    {% else %}
      <a href="#" class="pagination--pager disabled">{{ site.data.ui-text[site.locale].pagination_next | default: "Next" }}</a>
    {% endif %}
  </nav>

```
This could probably be even decided on the specific type, if you check for page.collection !? But I really don't know anything about webdev ^^

Thanks for your great work!
