### ISSUE TITLE
new directory doesn't work on online url

### ISSUE THREAD

**Issue by jnuc093** [mmistakes/minimal-mistakes#140]
i just upgrade to jekyll 2.5.3, and installed minimal-mistakes successfully.
when i added a directory named "examples" it works fine on http://127.0.0.1:4000/examples/.
but when i push it to github code is here:

https://github.com/qinkun1234/qinkun1234.github.io/tree/master/examples 

it doesn't works(i use CNAME)

http://hmcy.net/examples/.

how can i resolve this.

but my another website works find http://jnuc093.github.io/py/, did i forget something.

**Comment by mmistakes** [comment]
You need an `index.html` in your examples folder. The server is hitting `/examples` and not finding anything to display.

**Comment by jnuc093** [comment]
thanks。i find the problem. i add a folder named "framework7-parse" ,this result in github can't parse the folder。just remove  "*-parse" like folder。
