### ISSUE TITLE
TOC doesn't work.

### ISSUE THREAD

**Issue by wonter** [mmistakes/minimal-mistakes#1403]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.8.0
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** 

---

## Current behavior

https://wonter.github.io/reproduce/reproduce/

## Steps to reproduce the behavior

When post just has first-level headers, TOC doesn't work.

Is this the cause of kramdown???

**Comment by mmistakes** [comment]
Level 1 headers are typically used for post titles. I'd suggest in your actual posts starting at level 2.

Semantically and SEO wise it's better too as you should only ever have one `h1` (level 1 heading) on a page.

**Comment by wonter** [comment]
That's my bad..

Thanks for you and your amazing theme.
