### ISSUE TITLE
I am wondering if "og:title" is SEO title

### ISSUE THREAD

**Issue by laureltreetop** [mmistakes/minimal-mistakes#1405]
I am wondering if "og:title" is SEO title

- [x] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

- **Minimal Mistakes version:** 4.8.0
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** 

I am wondering if "og:title" is SEO title
I will propose at _includes/seo.html
```html
<meta property="og:title" content="{{ page.title | default: site.title | markdownify | strip_html | strip_newlines | escape_once }}">
```
to
```html
<meta property="og:title" content="{{ seo_title }}">
```

please check your site this :
https://developers.facebook.com/tools/debug/sharing/

**Comment by mmistakes** [comment]
`seo_title` adds in extraneous stuff that isn't needed for sharing. Page title (or the site title in the case of the homepage) looks much nicer when sharing.

Homepage:

![screen shot 2017-12-17 at 9 52 38 am](https://user-images.githubusercontent.com/1376749/34080687-093fe522-e310-11e7-9af4-1212d6887e27.png)

Other pages:

![screen shot 2017-12-17 at 9 52 16 am](https://user-images.githubusercontent.com/1376749/34080684-fd5878be-e30f-11e7-8009-7101b4c8a261.png)

Using `seo_title` gives you the full title that appends the separator (eg. `-`) and then the site title. If used for `og:title` would give things like `Quick-Start Guide - Minimal Mistakes`, which is good for the `<title>` element and SEO purposes, but for social sharing is unnecessary.

**Comment by laureltreetop** [comment]
ok, thank you.
I like use "-" style, format, so I will set it for myself.
