### ISSUE TITLE
quick-start-guide: wrong to recommend removal of minimal-mistakes-jekyll.gemspec

### ISSUE THREAD

**Issue by Sciss** [mmistakes/minimal-mistakes#1407]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.8.0
- **Jekyll version:** 3.6.2
- **GitHub Pages hosted:** no
- **Operating system:** Debian Stretch

---

## Description

Following instructions from https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remove-the-unnecessary , I removed file `minimal-mistakes-jekyll.gemspec`. This causes bundle to reject execution:

```
$ bundle exec jekyll serve

[!] There was an error parsing `Gemfile`: There are no gemspecs at /data/temp/minimal-mistakes. Bundler cannot continue.

 #  from /data/temp/minimal-mistakes/Gemfile:2
 #  -------------------------------------------
 #  source "https://rubygems.org"
 >  gemspec
 #  -------------------------------------------
```

In order to make a fresh install work, do _not_ delete the gemspec file.

Therefore, please remove `minimal-mistakes-jekyll.gemspec` from https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_docs/01-quick-start-guide.md#remove-the-unnecessary

**Comment by mmistakes** [comment]
I don't thing this is a bug. Sounds to me you might have forked the theme and didn't finish following all of the directions in the docs.

The `Gemfile` in the root of this repo is used to build a Ruby gem, it is incomplete and missing gems for building a Jekyll site. This is where [these instructions](https://mmistakes.github.io/minimal-mistakes/docs/installation/#install-dependencies) come into play. Depending on if you're hosting on GitHub Pages or elsewhere they vary, but essentially you create (or update an existing `Gemfile`) with `gem "jekyll"` or `gem "github-pages"`.

You want it to look something [like this](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/Gemfile) and not [like this](https://github.com/mmistakes/minimal-mistakes/blob/master/Gemfile). Remove the `gemspec` line and then add the appropriate gems depending on your installation needs.
