### ISSUE TITLE
How to add a subscribe button and email input filed in the Index page?

### ISSUE THREAD

**Issue by srinivasakumar-a** [mmistakes/minimal-mistakes#1413]
- [x] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes/no
- **Operating system:** 

---

**Comment by coliff** [comment]
If you want the email addresses to come to you or an email address you have control over I'd recommend https://formspree.io/ - its fast and easy to setup and is free to use.

Simply add the following code to your page:
```
<form action="https://formspree.io/your@email.com"
      method="POST">
    <input type="text" placeholder="Name" name="name">
    <input type="email" placeholder="Email" name="_replyto" required>
    <input type="submit" value="Send">
</form>
```
