### ISSUE TITLE
Masthead links don't show

### ISSUE THREAD

**Issue by zorbathegreek** [mmistakes/minimal-mistakes#1414]
Hello everyone,
thanks for looking into my issue!

- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

## Environment informations
- **Minimal Mistakes version:** two days old (where do I find the version number?) 
- **Jekyll version:** 3.6.2
- **GitHub Pages hosted:** yes
- **Operating system:** Fedora 27, updated yesterday

## Expected behavior

I have put a few .md files in a _pages folder in the root directory
I have included the relevant file info  in _data/navigation.yml like so
title: "TITLE" 
url: /_pages/FILENAME.md 

Tried many different YAML headers but none brings up the page. (404, file not found)

Intended output or what I expected to see:

When I refresh the page, both locally with bundle exec jekyll serve, or F5 online, I thought I should see the page but I only get above mentioned error messages

## Steps to reproduce the behavior

Here is the repo:
https://github.com/zorbathegreek/gorillablog

I forked the minimalmistakes theme, pulled it, removed /docs and /test and the other files recommended for removal, customized _config.yml, added my own posts and pages, started up a local Jekyll server, pushed the repo because the posts didn't show locally neither and I thought they might do online. 

^C[user@localhost gorillablog]$ bundle exec jekyll serve --trace
Configuration file: /home/user/minimalmistakes/gorillablog/_config.yml
            Source: /home/user/minimalmistakes/gorillablog
       Destination: /home/user/minimalmistakes/gorillablog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
^C/home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/parser.rb:1288:in `scan': Interrupt
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/parser.rb:1288:in `tok'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/parser.rb:1192:in `tok!'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/static_parser.rb:197:in `class_selector'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/static_parser.rb:159:in `simple_selector_sequence'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/static_parser.rb:111:in `selector'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/static_parser.rb:86:in `selector_comma_sequence'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/parser.rb:1186:in `expr!'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/static_parser.rb:20:in `parse_selector'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/rule_node.rb:145:in `block in try_to_parse_non_interpolated_rules'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/logger/base.rb:30:in `capture'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/rule_node.rb:142:in `try_to_parse_non_interpolated_rules'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/rule_node.rb:73:in `initialize'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/parser.rb:672:in `new'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/parser.rb:672:in `ruleset'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/parser.rb:696:in `block_child'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/parser.rb:686:in `block_contents'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/parser.rb:137:in `stylesheet'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/scss/parser.rb:41:in `parse'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/engine.rb:414:in `_to_tree'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/engine.rb:321:in `to_tree'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:327:in `block in visit_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:88:in `block in with_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:88:in `with_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:326:in `visit_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `block in with_base'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `with_base'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `block (2 levels) in visit_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `map'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `block in visit_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:88:in `block in with_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:88:in `with_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:326:in `visit_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `block in with_base'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `with_base'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `block (2 levels) in visit_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `map'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `block in visit_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:88:in `block in with_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:88:in `with_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:326:in `visit_import'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `block in with_base'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `with_base'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:52:in `map'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:52:in `visit_children'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:171:in `block in visit_children'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:170:in `visit_children'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `block in visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:190:in `visit_root'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:161:in `visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:10:in `visit'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/root_node.rb:36:in `css_tree'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/tree/root_node.rb:20:in `render'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass/engine.rb:290:in `render'
	from /home/user/.gem/ruby/2.4.0/gems/sass-3.5.4/lib/sass.rb:57:in `compile'
	from /usr/local/share/gems/gems/jekyll-sass-converter-1.5.0/lib/jekyll/converters/scss.rb:119:in `convert'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:98:in `block in convert'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `each'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `reduce'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `convert'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:80:in `render_document'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:62:in `run'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:466:in `block in render_pages'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:464:in `each'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:464:in `render_pages'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:193:in `render'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:73:in `process'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (3 levels) in init_with_program'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `each'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (2 levels) in init_with_program'
	from /usr/local/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/share/gems/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/share/gems/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/user/.gem/ruby/2.4.0/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<top (required)>'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `load'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `kernel_load'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:28:in `run'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:424:in `exec'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:27:in `dispatch'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:18:in `start'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
	from /home/user/.gem/ruby/2.4.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
	from /home/user/bin/bundle:23:in `load'
	from /home/user/bin/bundle:23:in `<main>'

[user@localhost gorillablog]$ bundle exec jekyll serve --trace --verbose
  Logging at level: debug
Configuration file: /home/user/minimalmistakes/gorillablog/_config.yml
  Logging at level: debug
      GitHub Pages: github-pages v172
      GitHub Pages: jekyll v3.6.2
         Requiring: jekyll-seo-tag
         Requiring: jekyll-github-metadata
Dotenv not found. Skipping 
         Requiring: jekyll-paginate
         Requiring: jekyll-sitemap
         Requiring: jekyll-gist
         Requiring: jekyll-feed
         Requiring: jemoji
         Requiring: jekyll-remote-theme
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-github-metadata
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
         Requiring: kramdown
   GitHub Metadata: Initializing...
            Source: /home/user/minimalmistakes/gorillablog
       Destination: /home/user/minimalmistakes/gorillablog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       EntryFilter: excluded /package.json
       EntryFilter: excluded /Gemfile.lock
       EntryFilter: excluded /LICENSE.txt
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Rakefile
           Reading: _posts/2017-12-19-fifth-post.md
           Reading: _posts/2017-12-20-sixth-post.md
           Reading: _posts/2017-12-16-second-post.md
           Reading: _posts/2017-12-15-first-post.md
           Reading: _posts/2017-12-17-third-post.md
           Reading: _posts/2017-12-18-fourth-post.md
       EntryFilter: excluded /assets/js/vendor
       EntryFilter: excluded /assets/js/plugins
        Generating: JekyllOptionalFrontMatter::Generator finished in 4.6659e-05 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 8.4408e-05 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 0.002047776 seconds.
        Generating: Jekyll::JekyllSitemap finished in 0.000254329 seconds.
        Generating: JekyllFeed::Generator finished in 0.000551588 seconds.
        Generating: JekyllRelativeLinks::Generator finished in 5.4957e-05 seconds.
        Generating: JekyllDefaultLayout::Generator finished in 0.000762485 seconds.
        Generating: JekyllTitlesFromHeadings::Generator finished in 0.000116363 seconds.
         Rendering: _posts/2017-12-15-first-post.md
  Pre-Render Hooks: _posts/2017-12-15-first-post.md
  Rendering Liquid: _posts/2017-12-15-first-post.md
  Rendering Markup: _posts/2017-12-15-first-post.md
         Requiring: kramdown
  Rendering Layout: _posts/2017-12-15-first-post.md
         Rendering: _posts/2017-12-15-first-post.md
  Pre-Render Hooks: _posts/2017-12-15-first-post.md
  Rendering Liquid: _posts/2017-12-15-first-post.md
  Rendering Markup: _posts/2017-12-15-first-post.md
         Rendering: _posts/2017-12-16-second-post.md
  Pre-Render Hooks: _posts/2017-12-16-second-post.md
  Rendering Liquid: _posts/2017-12-16-second-post.md
  Rendering Markup: _posts/2017-12-16-second-post.md
  Rendering Layout: _posts/2017-12-16-second-post.md
         Rendering: _posts/2017-12-16-second-post.md
  Pre-Render Hooks: _posts/2017-12-16-second-post.md
  Rendering Liquid: _posts/2017-12-16-second-post.md
  Rendering Markup: _posts/2017-12-16-second-post.md
         Rendering: _posts/2017-12-17-third-post.md
  Pre-Render Hooks: _posts/2017-12-17-third-post.md
  Rendering Liquid: _posts/2017-12-17-third-post.md
  Rendering Markup: _posts/2017-12-17-third-post.md
  Rendering Layout: _posts/2017-12-17-third-post.md
         Rendering: _posts/2017-12-17-third-post.md
  Pre-Render Hooks: _posts/2017-12-17-third-post.md
  Rendering Liquid: _posts/2017-12-17-third-post.md
  Rendering Markup: _posts/2017-12-17-third-post.md
         Rendering: _posts/2017-12-18-fourth-post.md
  Pre-Render Hooks: _posts/2017-12-18-fourth-post.md
  Rendering Liquid: _posts/2017-12-18-fourth-post.md
  Rendering Markup: _posts/2017-12-18-fourth-post.md
  Rendering Layout: _posts/2017-12-18-fourth-post.md
         Rendering: _posts/2017-12-18-fourth-post.md
  Pre-Render Hooks: _posts/2017-12-18-fourth-post.md
  Rendering Liquid: _posts/2017-12-18-fourth-post.md
  Rendering Markup: _posts/2017-12-18-fourth-post.md
         Rendering: _posts/2017-12-19-fifth-post.md
  Pre-Render Hooks: _posts/2017-12-19-fifth-post.md
  Rendering Liquid: _posts/2017-12-19-fifth-post.md
  Rendering Markup: _posts/2017-12-19-fifth-post.md
  Rendering Layout: _posts/2017-12-19-fifth-post.md
         Rendering: _posts/2017-12-19-fifth-post.md
  Pre-Render Hooks: _posts/2017-12-19-fifth-post.md
  Rendering Liquid: _posts/2017-12-19-fifth-post.md
  Rendering Markup: _posts/2017-12-19-fifth-post.md
         Rendering: _posts/2017-12-20-sixth-post.md
  Pre-Render Hooks: _posts/2017-12-20-sixth-post.md
  Rendering Liquid: _posts/2017-12-20-sixth-post.md
  Rendering Markup: _posts/2017-12-20-sixth-post.md
  Rendering Layout: _posts/2017-12-20-sixth-post.md
         Rendering: _posts/2017-12-20-sixth-post.md
  Pre-Render Hooks: _posts/2017-12-20-sixth-post.md
  Rendering Liquid: _posts/2017-12-20-sixth-post.md
  Rendering Markup: _posts/2017-12-20-sixth-post.md
         Rendering: index.html
  Pre-Render Hooks: index.html
  Rendering Liquid: index.html
  Rendering Markup: index.html
  Rendering Layout: index.html
         Rendering: assets/js/lunr-en.js
  Pre-Render Hooks: assets/js/lunr-en.js
  Rendering Liquid: assets/js/lunr-en.js
  Rendering Markup: assets/js/lunr-en.js
  Rendering Layout: assets/js/lunr-en.js
         Rendering: assets/css/main.scss
  Pre-Render Hooks: assets/css/main.scss
  Rendering Liquid: assets/css/main.scss
  Rendering Markup: assets/css/main.scss
         Rendering: _pages/one.md
  Pre-Render Hooks: _pages/one.md
  Rendering Liquid: _pages/one.md
  Rendering Markup: _pages/one.md
  Rendering Layout: _pages/one.md
         Rendering: one.md
  Pre-Render Hooks: one.md
  Rendering Liquid: one.md
  Rendering Markup: one.md
  Rendering Layout: one.md
         Rendering: _pages/sample-page.md
  Pre-Render Hooks: _pages/sample-page.md
  Rendering Liquid: _pages/sample-page.md
  Rendering Markup: _pages/sample-page.md
  Rendering Layout: _pages/sample-page.md
         Rendering: _pages/two.md
  Pre-Render Hooks: _pages/two.md
  Rendering Liquid: _pages/two.md
  Rendering Markup: _pages/two.md
  Rendering Layout: _pages/two.md
         Rendering: assets/css/style.scss
  Pre-Render Hooks: assets/css/style.scss
  Rendering Liquid: assets/css/style.scss
  Rendering Markup: assets/css/style.scss
         Rendering: page2/index.html
  Pre-Render Hooks: page2/index.html
  Rendering Liquid: page2/index.html
  Rendering Markup: page2/index.html
  Rendering Layout: page2/index.html
         Rendering: sitemap.xml
  Pre-Render Hooks: sitemap.xml
  Rendering Liquid: sitemap.xml
  Rendering Markup: sitemap.xml
  Rendering Layout: sitemap.xml
         Rendering: robots.txt
  Pre-Render Hooks: robots.txt
  Rendering Liquid: robots.txt
  Rendering Markup: robots.txt
  Rendering Layout: robots.txt
         Rendering: feed.xml
  Pre-Render Hooks: feed.xml
  Rendering Liquid: feed.xml
  Rendering Markup: feed.xml
  Rendering Layout: feed.xml
                    done in 3.863 seconds.
         Requiring: jekyll-watch
           Watcher: Ignoring (?-mix:_config\.yml)
           Watcher: Ignoring (?-mix:_site)
           Watcher: Ignoring (?-mix:assets\/js\/plugins)
           Watcher: Ignoring (?-mix:assets\/js\/_main\.js)
           Watcher: Ignoring (?-mix:assets\/js\/vendor)
           Watcher: Ignoring (?-mix:Gemfile)
           Watcher: Ignoring (?-mix:package\.json)
           Watcher: Ignoring (?-mix:Rakefile)
 Auto-regeneration: enabled for '/home/user/minimalmistakes/gorillablog'
[2017-12-21 18:31:03] INFO  WEBrick 1.3.1
[2017-12-21 18:31:03] INFO  ruby 2.4.2 (2017-09-14) [x86_64-linux]
[2017-12-21 18:31:03] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on /.
[2017-12-21 18:31:03] DEBUG unmount .
[2017-12-21 18:31:03] DEBUG Jekyll::Commands::Serve::Servlet is mounted on /gorillablog.
    Server address: http://127.0.0.1:4000/gorillablog/
[2017-12-21 18:31:03] INFO  WEBrick::HTTPServer#start: pid=27108 port=4000
  Server running... press ctrl-c to stop.
^C[2017-12-21 18:31:05] DEBUG close TCPSocket(127.0.0.1, 4000)
[2017-12-21 18:31:05] INFO  going to shutdown ...
[2017-12-21 18:31:05] INFO  WEBrick::HTTPServer#start done.

Thanks again for looking into this!

Anthony
 
NB: The command I found out to be giving the desired result is  
bundle exec jekyll serve --trace
not (as accidentally proposed)
bundle exec jekyll --trace --verbose 
(I'll write a pull request)

**Comment by mmistakes** [comment]
The url isn't the source file paths. Put in what the rendered path is. 

Eg `/filename/` or `/filename/index.html`

**Comment by zorbathegreek** [comment]
Sorry, 
you mean this link?
https://zorbathegreek.github.io/gorillablog/

**Comment by mmistakes** [comment]
No I mean the page's url not the site.

In the case of [this page](https://github.com/zorbathegreek/gorillablog/blob/master/_pages/one.md) you'd set `url: /one/`, same as the permalink.

If you need more examples as to how it works check out the demo site's main navigation. https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_data/navigation.yml

**Comment by zorbathegreek** [comment]
Works! Great! Thanks!
