### ISSUE TITLE
Add support for additional search providers

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/minimal-mistakes#1416]
Augment search feature by allowing support for different search providers, similar to what was done with commenting.

- [x] GitHub Pages compatible search (Lunr.js default)
- [x] Algolia, powered by [jekyll-algolia](https://github.com/algolia/jekyll-algolia) plugin
- [ ] [Google Custom Search Engine](https://cse.google.com/cse/)
- [ ] Other

**Comment by nickgarlis** [comment]
Would you also be interested in multiple language support for searching ?

**Comment by mmistakes** [comment]
Not sure I follow what you mean by multiple language support @nickgarlis. Could you expand on it some?

**Comment by nickgarlis** [comment]
@mmistakes I am not sure about Algolia but Lunr does not support any other languages other than English by default. Non English users might be interested in searching in their native language. My solution to this was to use a [different](https://github.com/ioniodi/site-gem/blob/master/assets/js/lunr-gr.js) .js file for the extra language that I wanted to support where I registered a new stemmer.

**Comment by mmistakes** [comment]
Ah ok. Yeah I dunno. If it can be done in a way to not over complicate setup. In my experience it can be tricky handling multiple languages with a theme because Jekyll core isn’t really all that friendly to it.

Last thing I want to do is open a can of worms that can’t be supported well.

**Comment by mmistakes** [comment]
@nickgarlis Possible solution would be leverage `site.locale` set in _config.yml. This could be used to determine what language .js to load. Since `locale` can be language and locale (eg. `en-US`) doing something like this would normalize it to just the language.

```
{% assign lang = site.locale | slice: 0,2 | default: "en" %}
```

Then you could load the appropriate .js and if one doesn't exist for the given `locale` default to English.

```html
<script src="{{ '/assets/js/lunr-{{ lang }}.js' | absolute_url }}"></script>
```

**Comment by nickgarlis** [comment]
That's exactly how I was thinking of doing it !

**Comment by pixelastic** [comment]
For what it's worth, Algolia is language agnostic :)

Is there anything I could do to help you integrate jekyll-algolia?

**Comment by mmistakes** [comment]
@pixelastic It's on my todo list. I just need to lay the ground work for it in the theme.

**Comment by mmistakes** [comment]
Has a pull-request #1531

**Comment by user414** [comment]
First thanks for the great theme @mmistakes, very useful. Should we keep this request open since google CSE is still not supported or should we open a new one to keep track of it? We were also looking to support google CSE and came upon this issue.

**Comment by mmistakes** [comment]
@user414 Open a new issue so it can be tracked, if and when I get around to it.
