### ISSUE TITLE
Quickstart docs -- Github Pages no longer requires plugin

### ISSUE THREAD

**Issue by MV10** [mmistakes/minimal-mistakes#1432]
Minor doc update. To use this as a remote theme with Github Pages no longer requires the `plugin: jekyll-remote-theme` config entry. Just the line `remote_theme: mmistakes/minimal-mistakes` is adequate.

https://github.com/blog/2464-use-any-theme-with-github-pages

**Comment by mmistakes** [comment]
Happy to accept a PR if you wanted to make the this minor and easy change to the docs.
