### ISSUE TITLE
Support to analytics.js google analytics

### ISSUE THREAD

**Issue by lwasser** [mmistakes/minimal-mistakes#144]
Hello - question about the google analytics setup. It appears (i could be wrong) that you are pulling analytics using the old ga.js implementation. I wondered if you had any plans to move to the universal analytics upgrade?

i found the scripts.html page but am not sure if this was customized to optimize tracking.
Thank you
Leah

**Comment by mmistakes** [comment]
I haven't updated it to the universal one yet because as far as I know you need to opt into it. Wasn't sure if it would break things for those who haven't done so yet.

scripts.html is the include you want to update. Just replace this with your Universal snippet from Google. 

``` javascript
{% if site.owner.google.analytics %}
<!-- Asynchronous Google Analytics snippet -->
<script>
  var _gaq = _gaq || [];
  var pluginUrl = 
 '//www.google-analytics.com/plugins/ga/inpage_linkid.js';
  _gaq.push(['_require', 'inpage_linkid', pluginUrl]);
  _gaq.push(['_setAccount', '{{ site.owner.google.analytics }}']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
{% endif %}
```

**Comment by lwasser** [comment]
Thank you so much. that worked perfectly. I just updated the scripts.html file. Much appreciated :+1:
