### ISSUE TITLE
Jekyll excerpt_separator tag supported on index page?

### ISSUE THREAD

**Issue by MV10** [mmistakes/minimal-mistakes#1441]
Should the excerpt_separator config item work on the index page? I was using it in my earlier theme but minimal-mistakes seems to just ignore it. When I noticed it wasn't working from config, I tried adding it to page-level defaults and then to an individual page, but that didn't change anything.

**Comment by mmistakes** [comment]
It should work. To be honest I've never tried it on an index page. How much text you have on the index? I seem to recall an issue with only a single paragraph of content causing issues... though I could be making that up.

You have a public repo and example so I can see if anything sticks out to me?
MM is setup with this line in _config.yml to autogenerate an excerpt globally on new paragraphs.

```
excerpt_separator: "\n\n"
```

Which you can override at the post/page level if you want to use something like:

```
---
excerpt_separator: <!--more-->
---

Excerpt
<!--more-->
Out-of-excerpt
```

This shouldn't be theme dependent, and is more a Jekyll thing than something special MM is doing.

**Comment by mmistakes** [comment]
One more thing, if your index page is `.html` I'm not 100% sure the auto-generated excerpt feature of Jekyll works. Pretty sure it has to be a Markdown file.

**Comment by MV10** [comment]
The repo is public (mv10/mv10.github.io), it's just using your default home layout for now. Sorry, new to Jekyll, many ways to skin the cat, your layout is grabbing the text in a completely different way (not excerpt-driven). Not a big deal, I'll get around to writing my own index a bit later.
