### ISSUE TITLE
Code block: Long first line will be under the upper right code icon

### ISSUE THREAD

**Issue by halirutan** [mmistakes/minimal-mistakes#1443]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.8.1
- **Jekyll version:**
- **GitHub Pages hosted:** yes/no
- **Operating system:** 

---

I noticed this after updating from 3.6. The width of the central page content was reduced. I generally like this very much because narrow text blocks are faster and easier to read. However, it has some implications when you use code-blocks. I used the mm-doc pages to make my case and the following example is from https://mmistakes.github.io/minimal-mistakes/markup-syntax-highlighting/

![screen shot 2018-01-03 at 16 37 42](https://user-images.githubusercontent.com/511683/34527400-b9a69076-f0a5-11e7-9f2a-2e415bc9a9cc.png)

I highlighted a rectangular part that has its lower edge on the upper boundary of the displayed code. As you can see, if the first line is longer, the code will be hidden under the upper right icon. I solved this by removing the padding from this icon.

In general, with the default settings for page width and font-scalings, we only have about 60 visible characters in a code block before a scrollbar appears. This is a very ambitious limit. I had to decrease the code font scaling and made my page a bit larger.

Shouldn't a reasonable goal be to have the famous 80 character line for code-blocks without the need of scrollbars?

**Comment by mmistakes** [comment]
I'm likely going to remove the code icon in a future release so it won't be an issue anymore. In my opinion it's pointless decoration that just adds more visual clutter to the page.

Would be great if there was an easy way to limit to around 80 characters. I don't know of any way to do that without specify some length, which depending on the font size could be completely irrelevant.
