### ISSUE TITLE
Changing syntax highlighting theme

### ISSUE THREAD

**Issue by svoner** [mmistakes/minimal-mistakes#1458]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:** 3.6.2
- **GitHub Pages hosted:** no
- **Operating system:** ubuntu server 14.04 LTS

---

## Steps to reproduce the behavior

Hi, Michael
I want the style of code block like this:
![finaly](https://user-images.githubusercontent.com/16408845/34712586-41dae9ee-f55e-11e7-8c22-f7e578ea86ad.png)

Not like this:
![after](https://user-images.githubusercontent.com/16408845/34712615-5f1d5d52-f55e-11e7-994a-212b22873b15.png)

This's my markdown file:
![md_file](https://user-images.githubusercontent.com/16408845/34712699-b4309782-f55e-11e7-9ca0-22ac865df6c4.png)

Also, I tried to read all the posts in this site -"https://mmistakes.github.io/minimal-mistakes/ " ,but did not find a way, what should I do ?

**Comment by mmistakes** [comment]
You have 3 options:

1. [Downgrade the theme](https://mmistakes.github.io/minimal-mistakes/docs/upgrading/) to 4.8.1
2. [Override the 16 color variables](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#colors) used for syntax highlighting to one of the other included code block themes.
3. Come up with your [own set of base16 colors](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_variables.scss#L108-L124) and replace them. There are numerous base16 themes out there if you Google around.

**Comment by MV10** [comment]
Quick note for anybody wanting to go the "override" route, add your replacement base variables after the `@import` of the skin but before the `@import` of the main partials in `main.scss` and add `!important` to override the skin variables.

```scss
--- 
# front-matter
--- 

@charset "utf-8";

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin

// syntax highlighting from the "contrast" skin
// https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#colors
$base00: #000000 !important;
$base01: #242422 !important;
$base02: #484844 !important;
$base03: #6c6c66 !important;
$base04: #918f88 !important;
$base05: #b5b3aa !important;
$base06: #d9d7cc !important;
$base07: #fdfbee !important;
$base08: #ff6c60 !important;
$base09: #e9c062 !important;
$base0a: #ffffb6 !important;
$base0b: #a8ff60 !important;
$base0c: #c6c5fe !important;
$base0d: #96cbfe !important;
$base0e: #ff73fd !important;
$base0f: #b18a3d !important;

@import "minimal-mistakes"; // main partials
```
