### ISSUE TITLE
Have more than one cta button in header overlay

### ISSUE THREAD

**Issue by Sciss** [mmistakes/minimal-mistakes#1461]
- [X] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 4.9.0** 
- **Jekyll version: 3.6.2**
- **GitHub Pages hosted:** no
- **Operating system:** Linux Debian 

---

Hi! In my "old" web site I used multiple buttons in the index.md; it's straight forward in the body of the markdown. However, now I'm migrating, and I think I want to use the header overlay image; so my idea is to use the CTA option for buttons.

The question is: is there a way to have more than one `cta_label` / `cta_url`? If not, what would be the best approach to implement such layout? I attach a mock up of how I imagine the result.

![three_cta_mock](https://user-images.githubusercontent.com/131300/34745369-8ed8fba0-f590-11e7-9d6b-de6bb4c3dc15.jpg)

**Comment by mmistakes** [comment]
No not currently, the overlay was designed for a single call to action button. You'll need to hack something together right now.

I could potentially treat it similar to [one of my other themes](https://github.com/mmistakes/jekyll-theme-basically-basic), where you feed it an array of action buttons, but I'll have to give that some more thought.

Sample code would be something like:

```html
{% if page.actions %}
  <p>
  {% for action in page.actions %}
    <a href="{{ action.url }}" class="btn btn--light-outline btn--large">{{ action.label }}</a>
  {% endfor %}
{% endif %}
```

And then you'd have some YAML like in the post/page:

```yaml
actions:
  - label: "News"
    url: "/news/index.html"
  - label: "Contact"
    url: "/contact/index.html"
```

**Comment by Sciss** [comment]
Brilliant that works (https://github.com/Sciss/minimal-mistakes/commit/7b7970ed7db2ab81798d09540c35782af2e45a5d). Thanks so much!

**Comment by lthurner** [comment]
+1 for this extension
