### ISSUE TITLE
RSS feed ONLY works on Firefox; not on Chrome, GnomeWeb, IceCat, ...  

### ISSUE THREAD

**Issue by zorbathegreek** [mmistakes/minimal-mistakes#1462]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [x ] I have updated all gems with `bundle update`.
  - [x ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** last month's version (?) 
- **Jekyll version:**  3.6.2
- **GitHub Pages hosted:** yes
- **Operating system:** Fedora 27

---

## Expected behavior

I would like to click on the FEED button in the footer and be carried to the Atom subscribe page. This only works on Firefox.

Not sure if I should file this as an issue at all above mentioned browsers except Firefox, rather than here?! 
 
## Steps to reproduce the behavior

I clicked the Feed button, in the footer, from above mentioned browsers: 
https://gorillatravelservices.github.io/gorillablog/

and except in Firefox, I get this error message:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<feed xmlns="http://www.w3.org/2005/Atom">
<generator uri="https://jekyllrb.com/" version="3.6.2">Jekyll</generator>
<link href="http://localhost:4000/gorillablog/feed.xml" rel="self" type="application/atom+xml"/>
<link href="http://localhost:4000/gorillablog/" rel="alternate" type="text/html"/>
<updated>2018-01-10T15:34:30+02:00</updated>
<id>http://localhost:4000/gorillablog/</id>
<title type="html">Gorillablog</title>
<subtitle>
A site to guide you to the best travel experience in Eastern Congo DRC, including gorilla tracking.
</subtitle>
<author>
<name>Philippe Tembeya</name>
</author>
<entry>
<title type="html">Sixth Post</title>
<link href="http://localhost:4000/gorillablog/sixth-post/" rel="alternate" type="text/html" title="Sixth Post"/>
<published>2017-12-20T00:00:00+02:00</published>
<updated>2017-12-20T00:00:00+02:00</updated>
<id>http://localhost:4000/gorillablog/sixth-post</id>
<content type="html" xml:base="http://localhost:4000/gorillablog/sixth-post/"><p>sixth post</p></content>
<author>
<name>Philippe Tembeya</name>
</author>
<summary type="html">sixth post</summary>
</entry>
<entry>
<title type="html">Fifth Post</title>
<link href="http://localhost:4000/gorillablog/fifth-post/" rel="alternate" type="text/html" title="Fifth Post"/>
<published>2017-12-19T00:00:00+02:00</published>
<updated>2017-12-19T00:00:00+02:00</updated>
<id>http://localhost:4000/gorillablog/fifth-post</id>
<content type="html" xml:base="http://localhost:4000/gorillablog/fifth-post/"><p>fifth post</p></content>
<author>
<name>Philippe Tembeya</name>
</author>
<summary type="html">fifth post</summary>
</entry>
<entry>
<title type="html">Fourth Post</title>
<link href="http://localhost:4000/gorillablog/fourth-post/" rel="alternate" type="text/html" title="Fourth Post"/>
<published>2017-12-18T00:00:00+02:00</published>
<updated>2017-12-18T00:00:00+02:00</updated>
<id>http://localhost:4000/gorillablog/fourth-post</id>
<content type="html" xml:base="http://localhost:4000/gorillablog/fourth-post/"><p>fourth post</p></content>
<author>
<name>Philippe Tembeya</name>
</author>
<summary type="html">fourth post</summary>
</entry>
<entry>
<title type="html">Third Post</title>
<link href="http://localhost:4000/gorillablog/third-post/" rel="alternate" type="text/html" title="Third Post"/>
<published>2017-12-17T00:00:00+02:00</published>
<updated>2017-12-17T00:00:00+02:00</updated>
<id>http://localhost:4000/gorillablog/third-post</id>
<content type="html" xml:base="http://localhost:4000/gorillablog/third-post/"><p>third post</p></content>
<author>
<name>Philippe Tembeya</name>
</author>
<summary type="html">third post</summary>
</entry>
<entry>
<title type="html">Second Post</title>
<link href="http://localhost:4000/gorillablog/second-post/" rel="alternate" type="text/html" title="Second Post"/>
<published>2017-12-16T00:00:00+02:00</published>
<updated>2017-12-16T00:00:00+02:00</updated>
<id>http://localhost:4000/gorillablog/second-post</id>
<content type="html" xml:base="http://localhost:4000/gorillablog/second-post/"><p>second post</p></content>
<author>
<name>Philippe Tembeya</name>
</author>
<summary type="html">second post</summary>
</entry>
<entry>
<title type="html">First Post</title>
<link href="http://localhost:4000/gorillablog/first-post/" rel="alternate" type="text/html" title="First Post"/>
<published>2017-12-15T00:00:00+02:00</published>
<updated>2017-12-15T00:00:00+02:00</updated>
<id>http://localhost:4000/gorillablog/first-post</id>
<content type="html" xml:base="http://localhost:4000/gorillablog/first-post/"><p>first post</p></content>
<author>
<name>Philippe Tembeya</name>
</author>
<summary type="html">first post</summary>
</entry>
</feed>

The repo is here:
https://github.com/gorillatravelservices/gorillablog

This the output of 
bundle exec jekyll build --trace --verbose

[user@localhost gorillablog]$ bundle exec jekyll build --trace --verbose
  Logging at level: debug
Configuration file: /home/user/gorillablog_Jan2018/gorillablog/_config.yml
      GitHub Pages: github-pages v172
      GitHub Pages: jekyll v3.6.2
         Requiring: jekyll-seo-tag
         Requiring: jekyll-github-metadata
Dotenv not found. Skipping 
         Requiring: jekyll-paginate
         Requiring: jekyll-sitemap
         Requiring: jekyll-gist
         Requiring: jekyll-feed
         Requiring: jemoji
         Requiring: jekyll-remote-theme
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-github-metadata
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
         Requiring: kramdown
   GitHub Metadata: Initializing...
            Source: /home/user/gorillablog_Jan2018/gorillablog
       Destination: /home/user/gorillablog_Jan2018/gorillablog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       EntryFilter: excluded /package.json
       EntryFilter: excluded /Gemfile.lock
       EntryFilter: excluded /LICENSE.txt
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Rakefile
           Reading: _posts/2017-12-19-fifth-post.md
           Reading: _posts/2017-12-20-sixth-post.md
           Reading: _posts/2017-12-16-second-post.md
           Reading: _posts/2017-12-15-first-post.md
           Reading: _posts/2017-12-17-third-post.md
           Reading: _posts/2017-12-18-fourth-post.md
       EntryFilter: excluded /assets/js/vendor
       EntryFilter: excluded /assets/js/plugins
        Generating: JekyllOptionalFrontMatter::Generator finished in 6.9132e-05 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 0.000108509 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 0.00276414 seconds.
        Generating: Jekyll::JekyllSitemap finished in 0.000611988 seconds.
        Generating: JekyllFeed::Generator finished in 0.000940688 seconds.
        Generating: JekyllRelativeLinks::Generator finished in 0.003481637 seconds.
        Generating: JekyllDefaultLayout::Generator finished in 0.003492946 seconds.
        Generating: JekyllTitlesFromHeadings::Generator finished in 4.1011e-05 seconds.
         Rendering: _posts/2017-12-15-first-post.md
  Pre-Render Hooks: _posts/2017-12-15-first-post.md
  Rendering Liquid: _posts/2017-12-15-first-post.md
  Rendering Markup: _posts/2017-12-15-first-post.md
         Requiring: kramdown
  Rendering Layout: _posts/2017-12-15-first-post.md
         Rendering: _posts/2017-12-15-first-post.md
  Pre-Render Hooks: _posts/2017-12-15-first-post.md
  Rendering Liquid: _posts/2017-12-15-first-post.md
  Rendering Markup: _posts/2017-12-15-first-post.md
         Rendering: _posts/2017-12-16-second-post.md
  Pre-Render Hooks: _posts/2017-12-16-second-post.md
  Rendering Liquid: _posts/2017-12-16-second-post.md
  Rendering Markup: _posts/2017-12-16-second-post.md
  Rendering Layout: _posts/2017-12-16-second-post.md
         Rendering: _posts/2017-12-16-second-post.md
  Pre-Render Hooks: _posts/2017-12-16-second-post.md
  Rendering Liquid: _posts/2017-12-16-second-post.md
  Rendering Markup: _posts/2017-12-16-second-post.md
         Rendering: _posts/2017-12-17-third-post.md
  Pre-Render Hooks: _posts/2017-12-17-third-post.md
  Rendering Liquid: _posts/2017-12-17-third-post.md
  Rendering Markup: _posts/2017-12-17-third-post.md
  Rendering Layout: _posts/2017-12-17-third-post.md
         Rendering: _posts/2017-12-17-third-post.md
  Pre-Render Hooks: _posts/2017-12-17-third-post.md
  Rendering Liquid: _posts/2017-12-17-third-post.md
  Rendering Markup: _posts/2017-12-17-third-post.md
         Rendering: _posts/2017-12-18-fourth-post.md
  Pre-Render Hooks: _posts/2017-12-18-fourth-post.md
  Rendering Liquid: _posts/2017-12-18-fourth-post.md
  Rendering Markup: _posts/2017-12-18-fourth-post.md
  Rendering Layout: _posts/2017-12-18-fourth-post.md
         Rendering: _posts/2017-12-18-fourth-post.md
  Pre-Render Hooks: _posts/2017-12-18-fourth-post.md
  Rendering Liquid: _posts/2017-12-18-fourth-post.md
  Rendering Markup: _posts/2017-12-18-fourth-post.md
         Rendering: _posts/2017-12-19-fifth-post.md
  Pre-Render Hooks: _posts/2017-12-19-fifth-post.md
  Rendering Liquid: _posts/2017-12-19-fifth-post.md
  Rendering Markup: _posts/2017-12-19-fifth-post.md
  Rendering Layout: _posts/2017-12-19-fifth-post.md
         Rendering: _posts/2017-12-19-fifth-post.md
  Pre-Render Hooks: _posts/2017-12-19-fifth-post.md
  Rendering Liquid: _posts/2017-12-19-fifth-post.md
  Rendering Markup: _posts/2017-12-19-fifth-post.md
         Rendering: _posts/2017-12-20-sixth-post.md
  Pre-Render Hooks: _posts/2017-12-20-sixth-post.md
  Rendering Liquid: _posts/2017-12-20-sixth-post.md
  Rendering Markup: _posts/2017-12-20-sixth-post.md
  Rendering Layout: _posts/2017-12-20-sixth-post.md
         Rendering: _posts/2017-12-20-sixth-post.md
  Pre-Render Hooks: _posts/2017-12-20-sixth-post.md
  Rendering Liquid: _posts/2017-12-20-sixth-post.md
  Rendering Markup: _posts/2017-12-20-sixth-post.md
         Rendering: _pages/1.md
  Pre-Render Hooks: _pages/1.md
  Rendering Liquid: _pages/1.md
  Rendering Markup: _pages/1.md
  Rendering Layout: _pages/1.md
         Rendering: _pages/fifteen.md
  Pre-Render Hooks: _pages/fifteen.md
  Rendering Liquid: _pages/fifteen.md
  Rendering Markup: _pages/fifteen.md
  Rendering Layout: _pages/fifteen.md
         Rendering: _pages/five.md
  Pre-Render Hooks: _pages/five.md
  Rendering Liquid: _pages/five.md
  Rendering Markup: _pages/five.md
  Rendering Layout: _pages/five.md
         Rendering: _pages/four.md
  Pre-Render Hooks: _pages/four.md
  Rendering Liquid: _pages/four.md
  Rendering Markup: _pages/four.md
  Rendering Layout: _pages/four.md
         Rendering: index.html
  Pre-Render Hooks: index.html
  Rendering Liquid: index.html
  Rendering Markup: index.html
  Rendering Layout: index.html
         Rendering: assets/js/lunr-en.js
  Pre-Render Hooks: assets/js/lunr-en.js
  Rendering Liquid: assets/js/lunr-en.js
  Rendering Markup: assets/js/lunr-en.js
  Rendering Layout: assets/js/lunr-en.js
         Rendering: assets/css/main.scss
  Pre-Render Hooks: assets/css/main.scss
  Rendering Liquid: assets/css/main.scss
  Rendering Markup: assets/css/main.scss
         Rendering: _pages/one.md
  Pre-Render Hooks: _pages/one.md
  Rendering Liquid: _pages/one.md
  Rendering Markup: _pages/one.md
  Rendering Layout: _pages/one.md
         Rendering: _pages/seven.md
  Pre-Render Hooks: _pages/seven.md
  Rendering Liquid: _pages/seven.md
  Rendering Markup: _pages/seven.md
  Rendering Layout: _pages/seven.md
         Rendering: _pages/six.md
  Pre-Render Hooks: _pages/six.md
  Rendering Liquid: _pages/six.md
  Rendering Markup: _pages/six.md
  Rendering Layout: _pages/six.md
         Rendering: _pages/three.md
  Pre-Render Hooks: _pages/three.md
  Rendering Liquid: _pages/three.md
  Rendering Markup: _pages/three.md
  Rendering Layout: _pages/three.md
         Rendering: _pages/two.md
  Pre-Render Hooks: _pages/two.md
  Rendering Liquid: _pages/two.md
  Rendering Markup: _pages/two.md
  Rendering Layout: _pages/two.md
         Rendering: assets/css/style.scss
  Pre-Render Hooks: assets/css/style.scss
  Rendering Liquid: assets/css/style.scss
  Rendering Markup: assets/css/style.scss
         Rendering: page2/index.html
  Pre-Render Hooks: page2/index.html
  Rendering Liquid: page2/index.html
  Rendering Markup: page2/index.html
  Rendering Layout: page2/index.html
         Rendering: sitemap.xml
  Pre-Render Hooks: sitemap.xml
  Rendering Liquid: sitemap.xml
  Rendering Markup: sitemap.xml
  Rendering Layout: sitemap.xml
         Rendering: robots.txt
  Pre-Render Hooks: robots.txt
  Rendering Liquid: robots.txt
  Rendering Markup: robots.txt
  Rendering Layout: robots.txt
         Rendering: feed.xml
  Pre-Render Hooks: feed.xml
  Rendering Liquid: feed.xml
  Rendering Markup: feed.xml
  Rendering Layout: feed.xml
                    done in 4.158 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
[user@localhost gorillablog]$ 

My Gemfile contains this line:
gem 'jekyll-feed'

In _config.yml, this line is present:
plugins:
- jekyll-feed

I ran 
bundle-update

I added {% feed_meta %}
to the head section of default.html but it had no effect locally, 
so I removed it again

Thanks a lot for looking ínto this!!

**Comment by mmistakes** [comment]
MM doesn't build the feed, that's coming from the [`jekyll/jekyll-feed`](https://github.com/jekyll/jekyll-feed) plugin.

Regardless, I wouldn't worry too much about it. It's building the feed fine. Some browsers have better support for viewing the XML... which I'm guessing Firefox doesn't. But seeing how it's not a feed reader seems like a none issue to me.

**Comment by zorbathegreek** [comment]
I have been editing my Issue submission while you replied but only for cosmetics. Well, yeah it's strange, it builds, but only with Firefox, not with the other browsers. Didn't try IE... again, you think it's worthwhile filing issues with them?

**Comment by mmistakes** [comment]
Up to you. I don't really see the issue as I don't try to read XML/Atom feeds in browser, I use a dedicated reader for that. But yes, they're GitHub issue tracker would be the appropriate location to file your grievance.

Jekyll Feed does have support for [custom feed styles](https://github.com/jekyll/jekyll-feed#custom-styling) if default browser ones don't suit you.
