### ISSUE TITLE
Urgent help needed - links were rendered to localhost:4000 instead of site.url

### ISSUE THREAD

**Issue by Sciss** [mmistakes/minimal-mistakes#1463]
Hi Michael,

sorry for barging in - I just discovered a problem after overwriting the contents of my website; it's that despite

    url : "https://www.sciss.de" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

It seems that most links, including pages and css were still rendered to use `localhost:4000`. E.g. if you look at the page source of 

    http://www.sciss.de/index.html

There is

    <link rel="canonical" href="http://localhost:4000/">
    <meta property="og:url" content="http://localhost:4000/">

Consequently, the site is broken now. I don't understand why it didn't pick up the `url`. It seems every link starting with `/` is affected. Any clues what is causing this, and how I can re-render with the correct URL?

Thanks!

**Comment by Sciss** [comment]
Solved. Needed to set

    export JEKYLL_ENV=production

Before running `bundle exec jekyll serve`

**Comment by mmistakes** [comment]
FYI if you're building your site use `bundle exec jekyll build`. You won't need to set the `production` environment variable then.

Jekyll changed behavior awhille ago that when you spin up a development server with `jekyll serve` it overides `site.url` with `localhost`.
