### ISSUE TITLE
Add docs for switching from regular fork to remote_theme

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#1470]
- [x] This is a question about using the theme.
- [x] This is a feature request.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes/no
- **Operating system:** 

---

I've started using the theme prior to 4.5.0, and since then `remote_theme` feature has been introduced, but I cannot seem to quite understand how to upgrade to i. I've updated Gemfile, ran bundle update, I added remote_theme to _config.yml, removed _layouts and _includes and _sass and some of the stuff from /assets/, and then restarted jekyll, but it just complains about 

```
     Build Warning: Layout 'single' requested in _questions/2016-08-anekdote.md does not exist.
     Build Warning: Layout 'single' requested in _questions/2016-09-taenker-tilbage.md does not exist.
     Build Warning: Layout 'single' requested in _questions/2016-10-bedste-oplevelse.md does not exist.
     Build Warning: Layout 'single' requested in _questions/2016-11-paedagogik.md does not exist.
     Build Warning: Layout 'single' requested in _questions/2016-12-hvilket-sted.md does not exist.
     Build Warning: Layout 'single' requested in _questions/2017-01-betydning-for-dig.md does not exist.
     Build Warning: Layout 'single' requested in _pages/disclaimer.md does not exist.
  Liquid Exception: Included file '_includes/archive-single.html' not found in _pages/index.md
```

For sure it is me that is not quite understanding github-pages, jekyll and how it all works. Hoping for just a pointer in the right direction.

**Comment by mmistakes** [comment]
Can you share your repo? Remote theme probably isn't configured correctly or you're missing the GitHub Pages gem that installs it.

**Comment by lsolesen** [comment]
Hi @mmistakes,

Thanks for the quick response. The commit where I added remote_theme and updated Gemfile.lock is here: https://github.com/vih/derfor.vih.dk/commit/256e764ec93234b58c1a9d32bb0f33bc30893188

I reverted to having all of the directories available again. As soon as I e.g. remove the layouts, the error mentioned above will appear.

**Comment by mmistakes** [comment]
Run `bundle update`

You're running an older version of `github-pages` which isn't installing the remote theme gem. That's why it's not finding the layouts and includes.

**Comment by lsolesen** [comment]
Doh, I was sure I had did that, but this commit going to github-pages 172 does not make a difference to the Build warnings when removing the single-layout.

https://github.com/vih/derfor.vih.dk/commit/cc9b1edcd878dd480bd9a46d72969c0acbf518d1

**Comment by mmistakes** [comment]
Not sure what else to tell you, it's definitely your environment.

I just cloned your repo from that commit, removed `_layouts`, `_includes`, and `_sass`. Ran `bundle update`, then `bundle exec jekyll build` and it worked perfectly fine. No errors.

**Comment by mmistakes** [comment]
Try using the verbose tag when you build to see if gives any clues. 

```terminal
bundle exec jekyll build --verbose
```

My guess is [jekyll-remote-theme](https://github.com/benbalter/jekyll-remote-theme) gem isn't working for you. I've had troubles getting it to run on Windows environments, not sure what your setup is like.

But if that's the case you'll want to file an issue with them since its upstream and not theme related.

**Comment by lsolesen** [comment]
Thanks for looking into this. Your last advice paid off, and the environment got fixed - and I was able to remove the theme files. https://github.com/vih/derfor.vih.dk/pull/19. Thanks once again for sharing your brilliant theme for Jekyll.
