### ISSUE TITLE
Add optional ability to display date of post in the "archive-single.html"

### ISSUE THREAD

**Issue by BR0kEN-** [mmistakes/minimal-mistakes#1473]
### Synopsis

I think it would be good to have an optional ability to display the date of a post (from `post.date`) in the `archive-single.html` template.

### Technical approach

To not break the operability of the current implementation I propose to introduce the `date_show` argument to the `include` statement. That way those who interested in displaying the date would be able to optionally step in and turn the feature on. Also, alongside with the first argument, it's reasonable to allow configuring the date format, introducing the `date_format` argument that defaults to the `%B %-d, %Y`.

**Comment by mmistakes** [comment]
See #1474 for context as to why it was closed.
