### ISSUE TITLE
ability to decralatively set sidebar rendering (regardless of screen size)

### ISSUE THREAD

**Issue by ddd-workshop** [mmistakes/minimal-mistakes#1479]
- [x ] This is a question about using the theme.
- [ x] This is a feature request.
- [ ] I believe this to be a bug with the theme.

---

## Expected behavior

I'd love to be able to declare that on same pages (e.g. home) author sidebar is rendered according to screen size (as is the case currently), e.g. on large screens:
![full-bio](https://user-images.githubusercontent.com/16007327/34990778-9d9604e4-fac7-11e7-9912-b2e2a8203938.png)
and on small screens:
![minimal-bio](https://user-images.githubusercontent.com/16007327/34990789-a568aee2-fac7-11e7-9ab4-7f987337b035.png)
but on few other pages (e.g. articles) to always (regardless of screen size)) use the minimalistic sidebar version:
![minimal-bio](https://user-images.githubusercontent.com/16007327/34990830-c2545538-fac7-11e7-99ea-db4f55446aa5.png)

**Comment by mmistakes** [comment]
This is an intentional design decision.

On smaller screens there is less room for a full blown author sidebar like on `1024px` and up. This is why it is collapsed to focus more on what matters, the page's content not the author's profile.
