### ISSUE TITLE
QUestion: how to make content area wider

### ISSUE THREAD

**Issue by ddd-workshop** [mmistakes/minimal-mistakes#1480]
- [x ] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.

---

How can I make the article size wider (I'm using single layout) on larger screens so that the content is not limited to only to the narrow part of the whole page as on the attached screenshot: 
![width](https://user-images.githubusercontent.com/16007327/34991020-70b00064-fac8-11e7-8f96-2212e4fa4e8c.png)

**Comment by mmistakes** [comment]
Please search through the closed issues. I've replied to this with examples and actual code more times than I can count.

**Comment by mmistakes** [comment]
cc/ #1373, #1265
