### ISSUE TITLE
Author icons does not adapt to dark minimal_mistakes_skin.

### ISSUE THREAD

**Issue by kwlin** [mmistakes/minimal-mistakes#1482]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 4.9.0** 
- **Jekyll version: 3.7.0**
- **GitHub Pages hosted:** yes
- **Operating system: Windows 10 (using Bash on Linux)** 

---

## Expected behavior

I have applied the dark skin on my _config.yml and It seems that the icons of the author url's aren't adapted/changed by the dark skin as [documention](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin). My expectations was that the twitter, linkedin & github icons are grey icons instead of blue or black icons.

My Jekyll site (local screenshot):
![image](https://user-images.githubusercontent.com/1265483/35014650-afaaf9ba-fb11-11e7-9548-725e22ee6e11.png)

Expected example:
![image](https://mmistakes.github.io/minimal-mistakes/assets/images/dark-skin-archive-large.png)

I've verified that the include `@import "minimal-mistakes/skins/default"; // skin` is defined in the main.scss and on the right place.

Am I missing something in my configuration?

**Comment by Sciss** [comment]
It's a problem for dark colours such as GitHub. I did the following:

https://github.com/Sciss/minimal-mistakes/blob/4829082dd1e619bda4d99925a7ad7c06b9f4dc4e/_sass/minimal-mistakes/skins/_sciss.scss#L26

**Comment by mmistakes** [comment]
@kwlin Good catch. The fix until I get to it is adding this:

```scss
.social-icons .svg-inline--fa {
  color: inherit !important;
}
```

**Comment by kwlin** [comment]
@mmistakes Thanks for the fix. I'll see it in the new version of gem :)
