### ISSUE TITLE
Make feature_row work well with all layouts

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#1484]
- [ ] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes/no
- **Operating system:** 

---

## Expected behavior

The feature_row helper is really nice - and really close to look nice with other layouts than ´splash´. I would be really cool if small tweaks would be made to make feature_row usable on all layouts.

## Steps to reproduce the behavior

Here you see how close it is to look nice on e.g. the ´archive´ layout. 

![skaermbillede 2018-01-17 kl 17 36 46](https://user-images.githubusercontent.com/148026/35054670-6dbe4a38-fbad-11e7-8422-c8b377da4baf.png)

It seeks that these tweaks needs to be made for other layouts:

- fill container in width
- make sure that the headline is scaled down a bit and less top margin

That would make them usable in other layouts also, which will make the feature_row even more useful.

**Comment by mmistakes** [comment]
Do you have a repo with this example? I'd like to drop it in to a test page and see how hard it would be to add some CSS to make feature rows more portable.

**Comment by lsolesen** [comment]
On this branch - https://github.com/vih/historie/tree/yearbook

When build the screenshot is from /yearbooks/2017/ and there is an example on "left" and "center" on /yearbooks/

**Comment by lsolesen** [comment]
Just an extra question regarding feature_row. On :hover on the headlines they get underlined, and that makes me want to click them, but that is not possible, which seems a little counterintuitive.

**Comment by mmistakes** [comment]
Thanks.

And agree on the hover state of feature rows. That's something I recently removed but haven't pushed up yet.

**Comment by mmistakes** [comment]
Was a pretty fix so I pushed a couple of updates. Here's an example of an archive page with feature rows placed after (might have to flush your browser's cache to get the latest CSS).

- [Post archive with feature rows](https://mmistakes.github.io/minimal-mistakes/post-archive-feature-rows/) ([source file](https://github.com/mmistakes/minimal-mistakes/blob/master/test/_pages/post-archive-feature-rows.html))

In your example where you're using a grid wrapper to expand the main content's width, you need to place the feature row includes inside of that `<div>`. That will allow the feature rows to fill the entire area without the space on the right.

```html
{% assign site_posts = site.posts | where: "tags", page.title | sort: "date" %}

<div class="grid__wrapper">
  {% include feature_row id="intro" type="center" %}

  {% for post in site_posts %}
    {% include archive-single.html %}
  {% endfor %}

  <h2>Har du også læst?</h2>
  {% include feature_row type="left" %}
  {% include feature_row id="feature_row_2" type="right" %}
  {% include feature_row %}
</div>
```

**Comment by mmistakes** [comment]
Example with updated CSS:

![image](https://user-images.githubusercontent.com/1376749/35062318-eb89549c-fb91-11e7-8bbc-e744b5fbd3cb.png)

**Comment by lsolesen** [comment]
Awesome. Thanks for your work on this theme. The theme is reason I like Jekyll so much :)
