### ISSUE TITLE
Change copyright year in footer

### ISSUE THREAD

**Issue by Soumyabrata** [mmistakes/minimal-mistakes#1488]
Is it possible to change the copyright year in the footer of each page. I want to change the copyright year from 2017 to 2018. I presumed, that, the following line needs to be changed in the file `footer.html`.

`<div class="page__footer-copyright">&copy; {{ site.time | date: '%Y' }} {{ site.name | default: site.title }}. {{ site.data.ui-text[site.locale].powered_by | default: "Powered by" }} <a href="http://jekyllrb.com" rel="nofollow">Jekyll</a> &amp; <a href="https://mademistakes.com/work/minimal-mistakes-jekyll-theme/" rel="nofollow">Minimal Mistakes</a>.</div>`

Can you suggest what needs to be updated for the same? Cheers!

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes/no
- **Operating system:** 

---

**Comment by Sciss** [comment]
site.time | date: '%Y'

That precisely means, you only have to set `time` in `_config.yml` or, if absent, it will use the current date, thus 2018 already. Here it works, if have no `time` set, and it renders to 2018.

**Comment by mmistakes** [comment]
That's correct, you need to customize `_includes/footer.html`. Depending on how you installed the theme that process will vary.

If you're using it as a remote_theme or Ruby gem you'll copy [`_includes/footer.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/footer.html) from this repo and add it to your local repo. Any changes you make to it there will override the bundled theme.

If you forked the theme repo you can just edit the file directly.

**Comment by mmistakes** [comment]
`site.time` is set by Jekyll automatically to the current time. You don't have to add anything to `_config.yml` unless you want to override that.

Simply building your site will automatically update to the current year.

**Comment by Soumyabrata** [comment]
I'm using this theme, by rendering the website directly in the server (not in my local machine). I guess Jekyll should automatically set the time to the current time. Unfortunately, in my case [https://soumyabrata.github.io/](https://soumyabrata.github.io/), it still shows 2017.

**Comment by Sciss** [comment]
@Soumyabrata are you using current version of mm? Because I see the narrow uppercase navigation which I loved from the old version, and I would like to reenable that in current version. How did you do that?

**Comment by Soumyabrata** [comment]
@Sciss I'm not exactly sure what needs to changed in mm. I followed the steps mentioned in Tuset's site for creating an academic website, [http://jponttuset.cat/building-an-academic-website/](http://jponttuset.cat/building-an-academic-website/). This rendered the narrow upercase navigation in my site.

**Comment by mmistakes** [comment]
@Soumyabrata Looks like you're using an ancient version of MM :stuck_out_tongue_winking_eye:
