### ISSUE TITLE
Link in portfolio item title.

### ISSUE THREAD

**Issue by jellis18** [mmistakes/minimal-mistakes#1490]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 4.9.0** 
- **Jekyll version: 3.7.0**
- **GitHub Pages hosted:** no
- **Operating system: macOS 10.12.6** 

---

Is there a way to make a portfolio (in grid view) where the title is a link to a different site? For example, on the portfolio example, is there a way that when I click "Fizz Bang Identity" it takes me to a different site and not the page for that portfolio object?

**Comment by mmistakes** [comment]
If you set `link: http://whatever.com` in the page’s YAML Front Matter it should partially do what you want.

[List view handles](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/archive-single.html#L27-L31) it with linking to external link and the post’s page. That same logic is in the grid view, though I haven’t actually tested it to see how it looks.
