### ISSUE TITLE
When moving default index.html to a different permalink recent blog posts do not show up

### ISSUE THREAD

**Issue by brandonskerritt** [mmistakes/minimal-mistakes#1493]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:Latest (directly forked from GitHub today)
- **Jekyll version:Unknown, forked directly from GitHub today
- **GitHub Pages hosted:** yes
- **Operating system: Windows 10

---

## Steps to reproduce the behavior

https://github.com/brandonskerritt/brandonskerritt.github.io

I cloned the repo, changed _config.yml to include _posts. I then took index.html which had the original front matter
```
---
layout: home
author_profile: true
---
```

and change it so it has a permalink attribute
```
---
layout: home
author_profile: true
permalink: /blog
---
```
I also moved this file into _pages and added _pages to _config.yml

There is a 404 on my page at "brandonskerritt.github.io/" which is expected, but when i visit /blog it shows me the home layout but with *no* posts on it, despite there previously being posts when the index.html file was at /

Note: I want to have my own HTML file (to use as a personal portfolio) on / but I want to be able to access my blog posts from /blog

There is no compilation error.

Screenshot of /blog
https://screenshots.firefox.com/mk3PnBv27Vu5si3H/brandonskerritt.github.io
Note: when the permalink is removed and index.html is moved to the outer folder it shows blog posts, which leads me to believe I don't understand something about this theme.

My question is: How do I show my blog posts at /blog and have index.html be my own custom HTML file?

**Comment by mmistakes** [comment]
The permalink on `_pages/index.html` isn't valid. You need a slash on the end so it knows where to build the `index.html`.

Should be `permalink: /blog/` instead.

You also might want to seriously cleanup the repo. You have many of the theme only files in there `/docs`, `/test`, and your `Gemfile` is wrong. Could run into problems later keeping all that stuff around.

I'd also suggest renaming `/_pages/index.html` to `_pages/blog.index` since the way you have it now might get confusing if you add more pages later on.

**Comment by mmistakes** [comment]
Closing as this is a Jekyll issue and not theme specific. If you need help using Jekyll, their [community forum](https://talk.jekyllrb.com/) is the place to ask.
