### ISSUE TITLE
width of code block (<code></code> tags width size in article)

### ISSUE THREAD

**Issue by zooozoo** [mmistakes/minimal-mistakes#1496]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:**  4.9.0
- **Jekyll version:** 3.7.0 
- **GitHub Pages hosted:** yes
- **Operating system:** linux

---

In the single layout page, code block html tags structure is  
```
<div class="highlighter-rouge-">
  <div class="highlight">
    <pre class="highlight">
      <code></code>
    </pre>
  </div>
</div>
```
Directly I want to break line if the code block content is too long.

Currenttly if the content of the code block has a long line, we can use scroll bar of the bottom of the code block. And what I want to do is just break the long line automatically instead of using scroll bar.  

I thought it is reason that the I have 'toc nav'  and `<code>` tag width is wider than wrapper tags. And If I could resizing the width, i could make it.
But I f failed to resizing width of the `<code>`tag. I don't know how can do that.

Any recommands... are good for me! 

Thanks

**Comment by mmistakes** [comment]
This is simple CSS and can be done with the [`white-space` declaration](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space).

```css
pre {
  white-space: pre-wrap;
}
```

Will turn codeblocks like this:

![image](https://user-images.githubusercontent.com/1376749/35336380-32c437ba-00e6-11e8-81f2-fc10b58f28cf.png)

Into this (scroll bar goes away and lines are wrapped):

![image](https://user-images.githubusercontent.com/1376749/35336394-3dda4acc-00e6-11e8-9a75-9e9c326116ea.png)

**Comment by zooozoo** [comment]
Great~! Thanks!!
