### ISSUE TITLE
images in site missing subpath in gh pages

### ISSUE THREAD

**Issue by Andy-ABTec** [mmistakes/minimal-mistakes#1497]
- [x] This is a question about using the theme.
- [x] I am using the latest version of the theme.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

Just downloaded and installed the theme locally and everything works as expected. The version I've pushed up to github however is not showing my images in pages (broken links)

top of _config.yml looks like this:-

```
locale                   : "en-GB"
title                    : "TV Rename"
title_separator          : "-"
name                     : "TV Rename"
description              : "Television. Sorted."
url                      : "https://andy-abtec.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/minimal-mistakes" # the subpath of your site, e.g. "/blog"
repository               : "Andy-ABTec/minimal-mistakes" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : true # true, false (default)
words_per_minute         : 200
```

Page works ok eg:
(https://andy-abtec.github.io/minimal-mistakes/manual/quickstart/)
Images are in assets image viz:
(https://andy-abtec.github.io/minimal-mistakes/assets/images/tools/folder-monitor-01.png)
 and are browable
However inspecting the link to the image in the page I see:
`/assets/images/tools/folder-monitor-01.png`

Which is the correct path but has the subpath (/minimal-mistakes) missing from the front. If i use inspect to add it everything behaves...

I know I've broken something, but what have I done?

Thanks!

**Comment by mmistakes** [comment]
This is a Jekyll issue and not really something with the theme.

Short of it is since you're using a `baseurl`... in this case `/minimal-mistakes` your asset paths need to include that. So in your Markdown (or HTML) image paths should include that to be something like:

```markdown
![your image](/minimal-mistakes/assets/tools/your-image.jpg)
```

or if you want to be smarter about it:

```markdown
![your image]({{ site.baseurl }}/assets/tools/your-image.jpg)
```

Or you can use Jekyll's built in relative URL filter to do this for you.

```markdown
![your image]({{ '/assets/tools/your-image.jpg' | relative_url }})
```

If you didn't need a `baseurl` then the paths as you have them now would work as is.

**Comment by Andy-ABTec** [comment]
I knew it was me - many thanks

**Comment by nilsbecker** [comment]
thanks for the explanation. i think this is really a bug in jekyll? is it not natural to think that one can move around a generated web site by changing the base url? or is there a scenario where asset urls are absolute on the server?
