### ISSUE TITLE
removing underline from list of posts

### ISSUE THREAD

**Issue by benslack19** [mmistakes/minimal-mistakes#1499]
- [x ] This is a question about using the theme.
- [x ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.9
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** Mac OSX

---

## Expected behavior

(Sorry a bit of a noob here so wasn't sure if my request posted correctly. I'm re-posting here.)

Hello, thank you for making Minimal Mistakes! I think this is a great theme. Hopefully is a relatively simple question. Underlining the list of blog posts seems to be the default, so I'm just trying to figure out how to do that. You actually have what I'm looking for in the bottom right screenshot at [this link](https://github.com/mmistakes/minimal-mistakes/blob/master/screenshot-layouts.png).

While I don't have this yet, I'm looking to make a list of collections, so I'd like the "without underline list" to be the default style applied globally. Any tips?

**Comment by mmistakes** [comment]
This can be done with CSS using `text-decoration: none`.

Previously I did this to post titles in an archive, but that was short sighted of me. To make it more clear they are "link" and clickable I reverted back to the default styling of a `<a>` element... underlined.

You'll need to drop this into your CSS to override the theme's default.

```css
.archive__item-title a {
  text-decoration: none;
}
```

**Comment by benslack19** [comment]
OK thanks so much for the quick reply. Sorry I should've mentioned that I did see the CSS override from another post. I just wasn't sure where to put it. Do I just copy and paste it into the _layouts/archive.html page?

**Comment by mmistakes** [comment]
No, as per the [stylesheet documentation](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/):

> To make basic tweaks to theme’s style it can be overridden by adding to `<your_project>/assets/css/main.scss`.

**Comment by benslack19** [comment]
worked like a charm :-)     thanks so much!
