### ISSUE TITLE
Apply an id tag to a masthead entry

### ISSUE THREAD

**Issue by Andy-ABTec** [mmistakes/minimal-mistakes#1500]
Apologies for being back so soon, Google is not my friend today...

Is there any way of applying an id tag to a masthead menu entry?

I'd like to use some jQuery to modify a "Download"  link so it always points to the latest version of an exe file in our main repo. Or is there a better way of doing it?

Thanks...

**Comment by mmistakes** [comment]
If you want to edit the theme files sure. The masthead links Liquid logic is here...

https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/masthead.html#L7-L16

If you want to add IDs to those links you can probably use [Jekyll's `slugify` filter](https://jekyllrb.com/docs/templates/) applied to the link titles, which you could then target with jQuery.

```html
<a id="{{ link.title | slugify }}" href="{{ domain }}{{ link.url }}" {% if link.description %}title="{{ link.description }}"{% endif %}>{{ link.title }}</a>
```

If you had `link.title` of `My Site` you'd get something like this after Jekyll did its thing.

```html
<a id="my-site" href="/path-to-my-site/">My Site</a>
```

**Comment by Andy-ABTec** [comment]
You're the man - thanks!

**Comment by Andy-ABTec** [comment]
Works like a charm!!!
