### ISSUE TITLE
Can't get header items to display

### ISSUE THREAD

**Issue by mikheyev** [mmistakes/minimal-mistakes#1502]
- [X] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [X] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.9.0
- **Jekyll version:** 3.6.2
- **GitHub Pages hosted:** yes
- **Operating system:**  MacOS

---

## Expected behavior

A [header video](https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-video/) should be displayed

## Steps to reproduce the behavior

I currently have a stripped down site on [github](https://github.com/mikheyev/MikheyevLab) 
It was created by first establishing a blank repo, and then a single post. When I try to duplicate some header functions, like the having a [header video](https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-video/) (or other functions specified in the header), but nothing is loaded.

**Comment by mmistakes** [comment]
Your test post has the wrong layout, that’s why it’s not working. The theme doesn’t have a ``post` `layout`. Use `layout: single` instead.

https://mmistakes.github.io/minimal-mistakes/docs/layouts/#single-layout
