### ISSUE TITLE
creating page showing list of files for collection

### ISSUE THREAD

**Issue by benslack19** [mmistakes/minimal-mistakes#1505]
- [x ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.9
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** Mac OSX

---

## Expected behavior

Hi again Michael, I’m trying to create a page that has links to all of my markdown files in a certain folder. (The folder also contains Jupyter notebooks from which the markdown files were created.)

It sounds like I’m making a collection, so I’ve been following [this](https://mmistakes.github.io/minimal-mistakes/docs/collections/), your example with recipes [here](https://mmistakes.github.io/minimal-mistakes/recipes/), while also looking at the structure of your test unit [here](https://github.com/mmistakes/jekyll-theme-unit-test).

This is what I’ve done (note that my “mynotes” is akin to your “recipes”):
- Updated my _config.yml to show:
	`# Collections
	collections:
  	  mynotes:
    	    output: true
    	    permalink: /:collection/:path/`
- Also added this to the default section of _config.yml:
  	` # _mynotes
  	- scope:
	    path: ""
      	    type: mynotes
    	  values:
      	    layout: single
      	    author_profile: false
            share: true ` 
- Put all my markdown files in a directory named “_mynotes”
- Created a mynotes.html file with archive layout that is a clone of your recipes.html file [here](https://github.com/mmistakes/jekyll-theme-unit-test/blob/master/_pages/recipes-archive.html)

From these sources, I think I’ve done everything I needed to do, yet the page where I expect my list of linked markdown files is empty as shown below.

![screen shot 2018-01-28 at 11 20 44 am](https://user-images.githubusercontent.com/20425799/35486116-39ba4f4c-041e-11e8-8172-f256438b5a80.png)

My repository is [here](https://github.com/benslack19/benslack19.github.io) for reference.

Any tips or advice would be very much appreciated!

**Comment by mmistakes** [comment]
Doesn't look like a theme issue to me. You're better off asking for general Jekyll related help on their talk forum.

It looks to me like you don't have any valid collection documents in `_mynotes`. Jekyll will only process files with YAML Front matter. I didn't see any files in that folder that meet that requirement. Even though there are .md files won'ti believe Jekyll still needs the `---` front matter.

That's why your collection index page appears empty.

**Comment by benslack19** [comment]
an, ok! i overlooked a simple fix. adding yaml to my markdown files was all i needed. thanks!
