### ISSUE TITLE
Support rake install method for existng website?

### ISSUE THREAD

**Issue by putztzu** [mmistakes/minimal-mistakes#151]
I've seen the method you describe often which is to create a new website and copy over the content. The current Jekyll bootstrap documentation describes an easier, more direct method using rake
http://jekyllbootstrap.com/usage/jekyll-theming.html

Would be nice if you can support that method instead, Thx.

**Comment by mmistakes** [comment]
That only works for themes built for Jekyll bootstrap, which theme isn't. It's just vanilla Jekyll. 

From what I've read the JB method isn't all that great either. Best solution I've seen so far is building themes as Ruby gems and using Octopress and Octopress Ink to integrate with your Jekyll site. Waiting to see if that gains traction in the community.
