### ISSUE TITLE
Figure align-left / align-right?

### ISSUE THREAD

**Issue by iceboundflame** [mmistakes/minimal-mistakes#1515]
- [ ] This is a question about using the theme.
- [x] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.9.0
- **Jekyll version:** 3.7.2
- **GitHub Pages hosted:** no
- **Operating system:** Mac OS X

---

## Expected behavior

Is it possible to float half- or third-width `figure`s to the left or right of text, much like images can currently be `align-left` or `align-right`? I'd like to flow text around a figure with caption, while still preserving the breakpoints so that it becomes full-column below a certain browser size. Thanks!

**Comment by mmistakes** [comment]
Not sure that would work or look very well. Images would need to be much smaller to fit 2 or 3 across while floating alongside some text.

**Comment by iceboundflame** [comment]
Actually, looks like you've already done what I'm looking for on your demo page here.

https://mmistakes.github.io/minimal-mistakes/markup/markup-image-alignment/
https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_posts/2013-01-10-markup-image-alignment.md

Thanks for the comprehensive examples!

**Comment by drorcohengithub** [comment]
sorry I cannot seem to find how I include a caption for an image inserted like so:

![Figure 3]({{ site.url }}{{ site.baseurl }}/assets/images/Fig3.png){: .align-center} 

Is there anyway to add a caption to this?

**Comment by mmistakes** [comment]
@drorcohengithub Markdown you have above is for just an image and not caption. To add a caption use this helper instead:

https://mmistakes.github.io/minimal-mistakes/docs/helpers/#figure

**Comment by drorcohengithub** [comment]
Thanks mate. But then I lose the alignment options, right?
