### ISSUE TITLE
Linking bootstrap

### ISSUE THREAD

**Issue by shrivinayak** [mmistakes/minimal-mistakes#1518]
Whats the easiest way to link bootstrap and enable all bootstrap styles?
I find that linking bootstrap breaks the styles defined in this theme.

**Comment by mmistakes** [comment]
Probably use a different theme that's built for Bootstrap.

You're not going to be able to drop in the Bootstrap styles with MM because it wasn't built for it. There will be clashes in class names and such.

**Comment by shrivinayak** [comment]
okay! thanks.
