### ISSUE TITLE
Skin Changes are not reflecting after the 4.9.1 update!

### ISSUE THREAD

**Issue by srinivasakumar-a** [mmistakes/minimal-mistakes#1519]
- [x ] I believe this to be a bug with the theme.
- [ x] I am using the latest version (4.9.1) of the theme
---

## Environment informations
- **Minimal Mistakes version: ** 4.9.1
- **Jekyll version:** 
- **GitHub Pages hosted:** Yes
- **Operating system:**  Win 10

---

## Steps to reproduce the behavior

https://github.com/srinivasakumar-a/minimal-mistakes

  1) Cloned the theme, 
  2) Customized _config.yml,

**Comment by mmistakes** [comment]
Check your configuration, you don't have `remote_theme` set properly. You have it on the wrong theme...

https://github.com/srinivasakumar-a/minimal-mistakes/blob/master/_config.yml#L56

**Comment by mmistakes** [comment]
Closing as this looks like you've fixed it. When I visit your site it shows it is using version 4.9.1 and has the correct skin. If you're not seeing the same make sure you've flushed your browser's cache.

![image](https://user-images.githubusercontent.com/1376749/35872844-0091da2c-0b36-11e8-8703-878f4559e5c1.png)
