### ISSUE TITLE
One site not getting v 4.9.1

### ISSUE THREAD

**Issue by jengalas** [mmistakes/minimal-mistakes#1522]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.9.0/4.9.1
- **Jekyll version:** 3.7.2
- **GitHub Pages hosted:** no
- **Operating system:** Windows 10

---

I'm trying to figure out why one of my sites doesn't seem to be picking up the 4.9.1 version of the theme, while I have another one configured the same way that is getting the new version. Both are set up as the gem-based theme, not hosted on GitHub pages. I've run `bundle update` and it says `Using minimal-mistakes-jekyll 4.9.1`, but when I view the source of the generated page, I see `Minimal Mistakes Jekyll Theme 4.9.0 by Michael Rose`. This happens both locally and when Netlify builds the site. Any ideas what I can be missing or what else I should check?

**Comment by mmistakes** [comment]
If you `Gemfile.lock` says 4.9.1 then you have the latest version installed.

Other things to check are to make sure you've flushed your browser's cache. This usually affects the `.css` and `.js` more so than the `.html` files.

Also, do you have any `_layouts` you are overriding? I got bit by this once where I created a modified version of `_layouts/default.html` which replaced the bundled theme's version. This file is what [prints the theme's version number](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/default.html#L5-L10).

**Comment by jengalas** [comment]
That's it! I was overriding `_layouts/default.html` on that site. Duh. Thank you!

**Comment by mmistakes** [comment]
:smile: No worries.
