### ISSUE TITLE
Social media images don't appear

### ISSUE THREAD

**Issue by peterewills** [mmistakes/minimal-mistakes#1523]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.8.1
- **Jekyll version:** 3.6.2
- **GitHub Pages hosted:** yes
- **Operating system:** macOS 10.13.2

---

## Expected behavior

Social media icon links appear.

## Steps to reproduce the behavior

The social media link images fail to appear in the sidebar and footer. The code for my site is at https://github.com/peterewills/peterewills.github.io.

**Comment by justinrummel** [comment]
I had this too when first updating to the new Font Awesome. Something is getting cached, either server, cdn, or at the browser.

**Comment by mmistakes** [comment]
@peterewills Check your `_includes/scripts.html` file which is out of sync with the core theme. It's [missing the following line](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/scripts.html#L12) which loads Font Awesome.

```html
<script src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
```

**Comment by peterewills** [comment]
Thanks!!

**Comment by liloli** [comment]
sorry, this won't fix in my case. https://liloli.github.io/
