### ISSUE TITLE
Theme not applying

### ISSUE THREAD

**Issue by jacc** [mmistakes/minimal-mistakes#1525]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x ] I am using the latest version of the theme.
  - [ x] I have updated all gems with `bundle update`.
  - [ x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:**  latest
- **Jekyll version:** latest
- **GitHub Pages hosted:** yes
- **Operating system:** macOS

---

## Expected behavior

the theme would be applied

## Steps to reproduce the behavior

https://github.com/jacc/JBGuide

**Comment by mmistakes** [comment]
You have your site configured wrong.

If you inspect the source of any page you'll see the paths are wrong (it's duplicating some stuff and you have an extra `/`).

For example this:

```html
<link rel="stylesheet" href="https://jacc.github.io/JBGuide//JBGuide/assets/css/main.css">
```

I'd take a closer look at `url`, `baseurl`, `repository`, etc in your _config.yml and try to sort that out. This isn't a theme issue.
