### ISSUE TITLE
How to add custom icons for author links

### ISSUE THREAD

**Issue by arainot** [mmistakes/minimal-mistakes#1529]
- [x] This is a question about using the theme.
  - [ x] I am using the latest version of the theme.
  - [x ] I have updated all gems with `bundle update`.
  - [x ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** latest
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** MacOS

---

## Expected behavior

I'd like to add my custom icon to a custom link in the author-profile-custom-links
<img width="203" alt="screen shot 2018-02-13 at 10 47 25" src="https://user-images.githubusercontent.com/28651800/36143445-6923832c-10ab-11e8-9d0a-f7356c492b3a.png">

In my old website (written in html5), I was able to add that icon (ORCiD is the iD icon here below) but here it seems to be a bit more complicated and I don't really know where to add such an icon. I have the icon files and everything required to see it online (see attached screenshot). 
<img width="261" alt="screen shot 2018-02-13 at 10 49 02" src="https://user-images.githubusercontent.com/28651800/36143563-c1319fe0-10ab-11e8-9db1-2412dcbcb1ab.png">

Anyone willing to help please? And how do you keep the correct font?

**Comment by mmistakes** [comment]
> To add a new link you’ll need three things:
> 
> 1. Destination URL
> 2. [Font Awesome icon](https://fontawesome.com/icons?d=gallery) (`fa-` class)
> 3. Label for the link

https://mmistakes.github.io/minimal-mistakes/docs/layouts/#author-profile

**Comment by arainot** [comment]
@mmistakes Thanks I've read this from your website already but I would like to add my own icon, one that is not in font awesome. Is that possible?

**Comment by mmistakes** [comment]
Anything is possible if you know HTML and CSS.

**Comment by mmistakes** [comment]
Inspecting elements with your browser's web developer tools is the way to go. It'll tell you all the CSS you'll need to apply to match the styling.

You'll probably need to add some custom CSS too to fine tune things.

![screen shot 2018-02-13 at 7 04 14 am](https://user-images.githubusercontent.com/1376749/36149055-45f1d4e0-108c-11e8-885a-afd93848c8fb.png)

**Comment by arainot** [comment]
@mmistakes I tried to make it work before but I'm still a novice in HTML and CSS. I have the files that used to work on my old website but I don't know the structure of your template and I was not able to make it work. Any suggestions/guidance on where to load css, svg files and then call them within the author-profile-custom-links.html please?

**Comment by mmistakes** [comment]
Custom CSS - https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#customizing

**Comment by mmistakes** [comment]
Also, if you mimic the same HTML markup used for the other icons it'll pick up the correct styling and fix the font issue. I'm guessing you didn't drop it into a `<li>` element like the others.

And since FontAwesome injects their icons as SVGs, if you put yours in as an inline SVG and apply the same classes they do, it should "just work". I say should because I have no clue how your SVG's are built or marked-up, so they are a bit of a wild card.

```html
<li>
  <a href="https://whatever.com">
    <svg class="svg-inline--fa fa-w-14 fa-fw" aria-hidden="true" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
      ... <!-- svg paths and stuff -->
    </svg> Whatever
  </a>
</li>
```

**Comment by arainot** [comment]
@mmistakes Using the inline SVG method worked! Thanks a lot!

**Comment by Sciss** [comment]
If I want to use Fork Awesome (https://forkawesome.github.io/Fork-Awesome/get-started/), could you give me a hint which file I would have to edit to use different CDN from standard Font Awesome?

**Comment by mmistakes** [comment]
@Sciss https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/scripts.html#L12

**Comment by Sciss** [comment]
@mmistakes thank you Michael; I commented this script out and instead added the link-rel to head/custom.hml, but somehow the icons don't load. Now I also tried adding the `css` and `fonts` folders from fork-awesome directly to `assets`, same problem:

![screenshot from 2018-03-26 01-17-03](https://user-images.githubusercontent.com/131300/37881131-74eefd0a-3093-11e8-8a29-51b16e2bd451.png)

(to test: https://www.sciss.de/ )

the css looks correct: https://www.sciss.de/assets/css/fork-awesome.min.css
and the relative font URL also resolves: https://www.sciss.de/assets/fonts/forkawesome-webfont.eot

Any idea?

**Comment by Sciss** [comment]
So this is caused by using css classes `fab` and `fas` instead of `fa`. They have probably something to do with the colours? But also seem to constrain the icon size wrongly. I change now to `fa`. What's the reason for using `fab` and `fas`?

**Comment by mmistakes** [comment]
@Sciss Have a look at [Font Awesome's documentation](https://fontawesome.com/how-to-use/upgrading-from-4). They changed things in version 5 and added the new `fab` and `fas` classes. They have to do with different versions of the icons... solid... brand... etc.

What's the reasons behind switching tofont Fork Awesome?

**Comment by Sciss** [comment]
Thanks for the link. The reason is the upstream project decided not to add any more icons, which I think is a real crap. All the open source social media platforms such as Mastodon, Diaspora, Friendica are not represented and pull requests not accepted. The fork brings all these icons.

**Comment by antenore** [comment]
Sorry to comment on a closed issue, but I don't see a good reason to submit a new one.
@Sciss brought a really good argument regarding the possibility to use Fork Awesome instead of Font Awesome. I was trying to do it by hand, but it's like doing a full fork of minimal mistakes.

These are the files that need to be modified to adapt the class and icon name:

```
_includes/toc
_includes/tag-list.html
comments-providers/staticman_v2.html
comments-providers/staticman.html
_includes/category-list.html
_includes/archive-single.html
_includes/author-profile-custom-links.html
_includes/footer.html
_includes/social-share.html
_includes/comments.html
_includes/author-profile.html
_layouts/single.html
``` 

It may be incomplete or not completely correct (I've done just a grep on the files)

So far I've included the `scripts.html` in my  `_includes` and updated adding the Fork Awesome fonts

```html
  <script src="{{ '/assets/js/main.min.js' | relative_url }}"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.1.7/css/fork-awesome.min.css" integrity="sha256-gsmEoJAws/Kd3CjuOQzLie5Q3yshhvmo7YNtBG7aaEY=" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/4eee35f757.js"></script>
``` 

I think it would be possible to adapt this with a couple of `if` and add a configuration option in the _config.yml 

So that people can choose between one or the other.

Do you want I try to implement it? Will you accept a PR? 

Thanks and sorry again for commenting on this old issue.

**Comment by mmistakes** [comment]
@antenore  As you noted above, there's a lot of includes that I'd have to manage conditionals for to swap out font names between the two libraries. That's going to add complexity to the theme that I'm not comfortable introducing.

**Comment by mmistakes** [comment]
Also, all of the fonts @Sciss mentioned above are all included in Font Awesome now (with the exception of Friendica). So it does appear they are merging in new icons as they become available.

- [Mastodon](https://fontawesome.com/icons?d=gallery&q=mastodon)
- [Diaspora](https://fontawesome.com/icons?d=gallery&q=Diaspora)

**Comment by antenore** [comment]
I understand. I'll think about a solution, for me it's more a philosophical matter :-P

**Comment by mmistakes** [comment]
I get it. It's hard balancing for those who want to set it and forget it using the theme's sensible defaults, and then those that want to rip out every 3rd party service and replace with something else.

**Comment by antenore** [comment]
@mmistakes @Sciss it's much easier than I thought.

The Fork Awesome project added a compatibility layer with font awesome, so it's enough to remove the Font Awesome link in the scripts.html, and add the two Awesome Fork css in the the _includes/head/custom.html 

```diff
diff --git a/_includes/head/custom.html b/_includes/head/custom.html
index 4a14faf..334c018 100644
--- a/_includes/head/custom.html
+++ b/_includes/head/custom.html
@@ -1,5 +1,8 @@
 <!-- start custom head snippets -->

+<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.1.7/css/fork-awesome.min.css" integrity="sha256-gsmEoJAws/Kd3CjuOQzLie5Q3yshhvmo7YNtBG0
```

That's all.

**Comment by mmistakes** [comment]
@antenore you don't even have to go as far as overriding any of the theme's `_includes` which makes updating easier.

The theme has [a couple of hooks](https://mmistakes.github.io/minimal-mistakes/docs/javascript/#customizing) you can add an array of scripts to in your `_config.yml` and it will inject them instead of what's currently there.

For `<head>` scripts you add this to `_config.yml`

```yaml
head_scripts:
  - "https://cdn.jsdelivr.net/npm/fork-awesome@1.1.7/css/fork-awesome.min.css"
  - "https://cdn.jsdelivr.net/npm/fork-awesome@1.1.7/css/v5-compat.css"
```

Then for scripts added before the footer you'd add the following. This will deactivate all footer scripts including FontAwesome. So you just need to add back in `main.js` since that has all of the theme's scripts that handle smooth scroll, jQuery, and other things.

```yaml
footer_scripts:
  - /assets/js/main.min.js
```

**Comment by antenore** [comment]
Thanks @mmistakes I'm having some hard time with this but it's the best solution finally, I forgot about these hooks.

Thanks!
