### ISSUE TITLE
Staticman Empty Message

### ISSUE THREAD

**Issue by Xabacadabra** [mmistakes/minimal-mistakes#1532]
- [ ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.10
- **Jekyll version:** 
- **GitHub Pages hosted:** yes
- **Operating system:** Windows 10

---

## Expected behavior

Hello!

I'm using Staticman and all was going fine, but today a user told me that his comment was "invisible"...so i've tried to do a little test:

## Steps to reproduce the behavior

https://github.com/Xabacadabra/Xabacadabra.github.io/commit/d96a645e16beae54e3fc2f9d061de26c77f17fdc

As you can see, the field "message" is empty although i've normaly wrote "test" in the comment field as always before the sending

**Comment by mmistakes** [comment]
Strange. I just did a test comment on your site and it wasn't blank.

I don't think Staticman does any sort of form validation. In theory you could type a bunch of spaces in the message field and it would accept it.

https://github.com/Xabacadabra/Xabacadabra.github.io/commit/cc0306205c6800b3837c7e3e278e5b332f3e7349

**Comment by Xabacadabra** [comment]
Thanks for the answer!

It seems to work in most cases (I've tried to comment with my smartphone and everything went well). 

I thought that was a browser problem, but I've tested with Chrome and Firefox with the same results, very strange indeed.

**Comment by mmistakes** [comment]
This thread might be related. Noticed others mentioning empty values for `message` along with some fields that weren't there before like `layout` and `moderation`.

https://github.com/eduardoboucas/staticman/issues/176
