### ISSUE TITLE
Home page: show full text posts

### ISSUE THREAD

**Issue by rianvdm** [mmistakes/minimal-mistakes#1534]
- [x ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x ] I am using the latest version of the theme.
  - [x ] I have updated all gems with `bundle update`.
  - [x ] I have tested locally with `bundle exec jekyll build`.

---

The home page shows a list of recent posts with excerpts: https://rianvdm.com/

Is it possible to have the home page show a list of posts with the full text of each post, instead of just showing an excerpt?

**Comment by mmistakes** [comment]
It's possible if you're comfortable editing the theme files.

Instead of `post.excerpt` you'd replace it with `post.content`

https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/archive-single.html

**Comment by rianvdm** [comment]
@mmistakes Ok I'll give that a try. Thanks for the super quick response!
