### ISSUE TITLE
Posts not showing up under "Recent Posts"

### ISSUE THREAD

**Issue by sliuu** [mmistakes/minimal-mistakes#1535]
- [X] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
- [ ] I am using the latest version of the theme.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** Newest (>4)
- **Jekyll version:** 3.6.2
- **GitHub Pages hosted:** yes
- **Operating system:** MacOS

---

## Expected behavior

Posts appears under "recent posts" on the home page

## Steps to reproduce the behavior

https://github.com/sliuu/hciproject/
Downloaded the theme, unzipped, added to repository
Customized _config.yml, added some navbar and author links, added front page image
Created a post under _posts/ 
Built, and served with jekyll

**Comment by mmistakes** [comment]
Looks like you got this working as I see your latest post on the home page.

![screen shot 2018-02-18 at 2 43 13 pm](https://user-images.githubusercontent.com/1376749/36356026-40524be6-14ba-11e8-82e1-60e05cdb0520.png)

**Comment by sliuu** [comment]
It does seem to show up, but the formatting for the post itself isn't what I expected and it doesn't show up on my local... any idea why?

**Comment by mmistakes** [comment]
That's because you don't have the layout for the post at correctly. Should be `layout: single` not `default`.

**Comment by sliuu** [comment]
Is there any reason why the "recent posts" section would show up on the website but not on my local?

**Comment by mmistakes** [comment]
Yeah. You probably don't have the pagination gem installed properly. GitHub Pages does all that for you when they host the site. You need to do the same locally.

https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/

**Comment by sliuu** [comment]
Thanks so much for all your help! Also turns out the reason my posts weren't showing up locally is because I set the date in the future (stuff's due tomorrow). Didn't think about that.

**Comment by mmistakes** [comment]
You can use the `--future` flag when building your Jekyll site, to force publish and future dated posts.

**Comment by havesomeleeway** [comment]
I seem to have the same problem that @sliuu was facing. I have pushed my changes to the page over at www.havesomeleeway.com but nothing is showing up on my recent posts

What I have now: 
* `_posts` with a file named `2018-02-20-test.md` 
*  layout of post is set to `single`

**Comment by mmistakes** [comment]
This file is your problem.

https://github.com/havesomeleeway/havesomeleeway.github.io/blob/master/_pages/home.md

As noted in the docs, a home page that is paginated can't be a markdown file. For whatever reason jekyll-paginate requires it to be named `index.html` and in the root of your repo.

Rename it and move it out of `_pages`.

**Comment by havesomeleeway** [comment]
@mmistakes thanks a lot, it works now.

**Comment by exetico** [comment]
For people finding this on Google, and as me, had everything configured correctly:
Think about your timezone on the post...

I created a post one hour in the future (didn't think about summer<>wintertime) and therefore, the post didn't show up, as I was expecting. Half an hour waisted, and fixed by moving the post one hour. 

To... Hopefully I can save your time ;) ...

😆 ....
