### ISSUE TITLE
Staticman comment form does not appear

### ISSUE THREAD

**Issue by sfdye** [mmistakes/minimal-mistakes#1544]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.10.0
- **Jekyll version:** 3.7.2
- **GitHub Pages hosted:** no, netlify on `deploy` branch
- **Operating system:** MacOS

---

the repo: https://github.com/sfdye/sfdye.github.com

My question is does staticman work with netlify? Right now the comment form does not appear in any post? Even though I have the `comments: true` front matter.

I think I am using the gem, so I should not worry about `_includes` right?

**Comment by mmistakes** [comment]
As long as you have the site in a GitHub repo Staticman will work. It uses GitHub's API to push commits with the comments as data files. Your site can be hosted with Netlify (or anywhere else) for this to happen.

The form isn't showing up for you because you need to configure your `repository` in _config.yml

https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-repository

It's needed as part of the comment form to send a call to Staticman. Without it a form submit won't work. There is a conditional to only show the form when repo and the branch have been assigned.

**Comment by sfdye** [comment]
Thanks for the quick reply, I think I have the repository in the _config.yml and everything else according to the docs.

________________________________

**Comment by mmistakes** [comment]
And you've set your Jekyll environment variable to`production` right?

https://jekyllrb.com/docs/configuration/#specifying-a-jekyll-environment-at-build-time

Comments are only shown in production, and not `development` which Jekyll tends to default to.

**Comment by sfdye** [comment]
Yes, I’ve tried that as well. Did not work. Would you mind taking a look at my config to see anything suspicious?

________________________________

**Comment by dev4223** [comment]
Have a look at my site and config https://github.com/dev4223/ondata
It works on netlify.

**Comment by sfdye** [comment]
@mmistakes My bad, now it works on local. But production still no form.

**Comment by sfdye** [comment]
@dev4223 Thanks, let me check.

**Comment by sfdye** [comment]
I am switching back to disqus.

**Comment by stanleykylee** [comment]
@dev4223 i've been trying to get this working as well. I'm not even able to get the staticman fields to show up at the end of the blog posts. Are there additional settings to enable them to show up? When I go to my site, I see the [raw page](view-source:https://5aac521d0b79b760d6325a71--optimistic-neumann-326356.netlify.com/2018/03/12/new-jekyll-site/) and see the comments section there but nothing is loading. Am I missing something else, here is my repo [https://github.com/stanleykylee/stanleykylee.github.io](https://github.com/stanleykylee/stanleykylee.github.io)

**Comment by mmistakes** [comment]
@stanleykylee Comments work just fine. I just cloned your repo and built it locally. What you're likely having an issue with is the setting J[ekyll's environment variable](https://jekyllrb.com/docs/configuration/#specifying-a-jekyll-environment-at-build-time) to `production`... what I stated above for @sfdye applies here as well.

When I built locally with `JEKYLL_ENV=production jekyll build` comments show up. 

![screen shot 2018-03-16 at 8 18 29 pm](https://user-images.githubusercontent.com/1376749/37549537-643efed0-2957-11e8-80d9-14ddaeac16c1.png)

I see you're hosting with Netlify and according to your config file you aren't setting this environment variable.

I don't have much experience with Netlify but I'd assume you could modify your build script to this instead `command = "JEKYLL_ENV=production bundle exec jekyll build && bundle exec jekyll algolia"`

If that doesn't work the also let you set environment variables which you could just add `JEKYLL_ENV=production`. A lot of people forget this step as GitHub Pages automatically sets this for you.

**Comment by stanleykylee** [comment]
Awesome. Thanks for the quick reply. I think I know what you’re talking about. I’ll give it a shot when I get back home tonight!
