### ISSUE TITLE
Pagination Tabs Wrap on Mobile

### ISSUE THREAD

**Issue by ejmg** [mmistakes/minimal-mistakes#1545]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [x] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** minimal-mistakes-jekyll (4.10.0)
- **Jekyll version:** jekyll 3.7.2
- **GitHub Pages hosted:** no
- **Operating system:** debian

---

## Expected behavior

The pages should be indexed as a single line, as on desktop:

![normal behavior, imgur link](https://i.imgur.com/nJwfnLE.png)

## Actual Behavior

![](https://i.imgur.com/ntZHnEw.png)

## Steps to reproduce.

I'm not sure. I suspect this may just be because I have a lot of archived posts. I'm assuming this is a quick fix but am not really good with liquid templates nor do I have access to them anymore now that I'm using this jekyll theme as a Ruby Gem(?). Here is a link to my [repository](https://github.com/ejmg/ageof.info). I really appreciate any help on this.

**Comment by mmistakes** [comment]
This has nothing to do with Liquid. It’s pure CSS used to style those links. Not sure what can be done to make it fit on a single line as the more pages you have the longer it’ll be.

Maybe you could replace [Previous and Next](https://github.com/mmistakes/minimal-mistakes/blob/master/_data/ui-text.yml#L7-L8) with a chevron glyph to save space.

**Comment by ejmg** [comment]
Hmm, okay. That seems like a pretty reasonable fix. Given that this is restricted to a mobile use-case, is it possible to resort to the chevron glyph on mobile devices only?

I ask because that would seem like a decent feature to PR in. I guess my situation is sort of an edge case given how much I've written, but it could benefit someone else too?
