### ISSUE TITLE
Change Size of Masthead Links?

### ISSUE THREAD

**Issue by ygkip** [mmistakes/minimal-mistakes#1546]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.10
- **GitHub Pages hosted:** yes

repo: https://github.com/ygkip/gjkip
Site: https://ygkip.github.io/gjkip/
---

## Expected behavior

I would like to change the size of the links (or spacing) in the masthead so that all my links show up without using the hidden button thing. Is this possible? How can I do this?

**Comment by mmistakes** [comment]
Through CSS. All of the masthead styles are in this Sass partial.

https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_masthead.scss

**Comment by ygkip** [comment]
Thank you I figured it out!
