### ISSUE TITLE
Header and footer's background image

### ISSUE THREAD

**Issue by ekofi** [mmistakes/minimal-mistakes#1547]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations
- **Minimal Mistakes version:*4.10* 
- **GitHub Pages hosted:***yes*

---

## Expected behavior
I want to place the background image on footer and header, but i couldn't. How can I do this? Thanks

**Comment by mmistakes** [comment]
Theme only supports adding an image to the top of a post or page. If you want a background image in the header or footer you’ll need to hack it yourself.

https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-overlay-image/
