### ISSUE TITLE
Excluding TOC elements does not work with 'toc: true' in the YAML Front Matter

### ISSUE THREAD

**Issue by matteosecli** [mmistakes/minimal-mistakes#1556]
- [ ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [x] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.10.0
- **Jekyll version:** 3.6.2
- **GitHub Pages hosted:** yes
- **Operating system:** MacOS 10.13.3

---

## Expected behavior

I expect to be able to control what goes in my TOC by using [standard Kramdown](https://kramdown.gettalong.org/converter/html.html#toc), i.e. by assigning `{:.no_toc}` to a header.

## Steps to reproduce the behavior

Take a simple MD file:
```
---
title: "TOC Test"
---

# Header 1

## Header 2

### Header 3
{:.no_toc}
```

* The feature works correctly with the TOC include, i.e. by including `{% include toc %}` the generated TOC will be

    ```
    - Header 1
       - Header 2
    ``` 
    However the TOC include is going to be **deprecated**, so I'd prefer to avoid doing it this way.
* The feature **does not** work correctly when enabled via the YAML Font Matter , i.e. by using `toc: true` the generated TOC will be

    ```
    - Header 1
       - Header 2
       - Header 3
    ```

**Comment by mmistakes** [comment]
This doesn't work because `toc: true` uses JavaScript too build the table of contents instead of Kramdown.

To exclude headers you'll need to use the [`toc` include helper](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#table-of-contents) instead.

**Comment by matteosecli** [comment]
> To exclude headers you'll need to use the toc include helper instead.

Indeed, it's what I'm using right now. But I'm worried by the fact that the toc helper will be deprecated, so the "old" pages that use the toc helper won't work anymore with the new version of the theme.

**Comment by mmistakes** [comment]
Even if deprecated you can copy _includes/toc into your repo and still use it.

**Comment by matteosecli** [comment]
Ok, thank you!

Btw: thanks for your awesome theme! 😄
