### ISSUE TITLE
Translation not working anymore

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#1557]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.9.1
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** 

---

## Expected behavior

UI strings are translated to Danish - but they are not: see http://historie.vih.dk/

## Steps to reproduce the behavior

The UI strings are not translated anymore. I am not sure whether it has worked for me since switching to remote_theme: "mmistakes/minimal-mistakes@4.9.1". See repository: https://github.com/vih/historie

**Comment by mmistakes** [comment]
You're missing the [`ui-text.yml` data file](https://github.com/mmistakes/minimal-mistakes/blob/master/_data/ui-text.yml). Remote themes don't pull in `_data` files, so you have to manually copy it over to your repo.

**Comment by lsolesen** [comment]
Do. Sorry about that. I thought it went from the remote theme.

**Comment by mmistakes** [comment]
It pulls when you use it as a theme gem since that utilizes a 3rd party plugin to copy the theme's `_data` files. But sadly that plugin isn't supported on GitHub Pages yet so you have to go through the extra step of copying the file yourself.
