### ISSUE TITLE
When installing via Gem method, post-install message from html-pipeline requests more dependencies — which if any are needed?

### ISSUE THREAD

**Issue by briandigital** [mmistakes/minimal-mistakes#1558]
- [x] This is a question about using the theme. **installation** specifically.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`. **n/a**

---

## Environment information

- **Minimal Mistakes version:** 4.10.0
- **Jekyll version:** 3.7.3
- **GitHub Pages hosted:** no
- **Operating system:** macOS 10.13.3

---

When installing the theme via Gem method, a post-install message from html-pipeline requests more dependencies —which if any are needed for your theme to function?

Message:
```
Thank you for installing html-pipeline!
You must bundle Filter gem dependencies.
See html-pipeline README.md for more details.
https://github.com/jch/html-pipeline#dependencies
```

The information at the provided URL says "you must bundle the filter's gem dependencies. "

Which filters, if any, are required to be installed? I'm _presuming_ these would be specific filters the theme is using?

(forgive me if this is a stupid question, but I'm not a ruby dev, and 30 minutes of web searches gave me no clues. Thanks for making all your resources available to the world. Your work is appreciated!)

**Comment by mmistakes** [comment]
I'm not a Ruby dev either. The [theme gem](https://github.com/mmistakes/minimal-mistakes/blob/master/minimal-mistakes-jekyll.gemspec#L18-L27) doesn't use `html-pipeline` as a dependency.

My guess is one of the Jekyll plugins it does use has it as a dependency.

If you look at your `Gemfile.lock` depencies are indented and should give you a clue which gem(s) need it. Then you can follow-up with the plugin maintainer to see what filters are needed.

**Comment by briandigital** [comment]
Thanks for the response. FWIW, it looks like it's needed by `emoji (0.9.0)`? Which is maintained by GitHub apparently.

**Comment by mmistakes** [comment]
Sounds about right. 

You can inquire with that project but I'm guessing you can probably ignore the post install messaging.

**Comment by briandigital** [comment]
Thank you, I appreciate your input. This was the plan I also came to… wait it out, see what, if anything breaks.
