### ISSUE TITLE
Windows CRLF line endings in gem

### ISSUE THREAD

**Issue by matiasfrndz** [mmistakes/minimal-mistakes#1564]
I noticed that the template files in the minimal-mistakes-jekyll gem (version 4.10.0) have Windows style CRLF line endings instead of Linux style LF line endings. This seems odd as the source code has correct LF line endings. It get even stranger when building the site as the result is a mix of CRLF and LF line endings.
What is the reason for the templates files in the minimal-mistakes-jekyll gem having Windows style CRLF line endings?

**Comment by mmistakes** [comment]
Just a matter of preference that gets enforced by text editors that support [`.editorconfig`](https://github.com/mmistakes/minimal-mistakes/blob/master/.editorconfig).

```
[*]
insert_final_newline = true
```

ref: http://editorconfig.org/

**Comment by mmistakes** [comment]
To be clear, I don't add these new lines. It is 100% controlled by my text editor and what is in `.editorconfig` (default values for the most part).

If the mixture in styles is being caused by that I'd be interested in a fix.

**Comment by mmistakes** [comment]
Looks like it could be a side-effect of my text editor (Visual Studio Code) ignoring what's in `.editorconfig` and defaulting to CRLF line endings.

**Comment by matiasfrndz** [comment]
Hi Michael, thanks for your feedback. I understand that you work on Windows. The default there is to use CRLF. As far as I understand, Git converts line endings upon checkin and checkout, see [Formatting and Whitespace](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace) in the Git documentation. Furthermore, I guess that you may be building the Gems on your Windows platform and that this process leaves line endings as they are when checked out. This would explain why the line endings in the Git repository (on GitHub) have LF line endings and the files in the Gem have CRLF line endings.

What I don't understand is that the issue only appears when copying template files from the Gem file into my repository (without changing the line endings). When using `jekyll build` without copying the templates files, the issue doesn't appear. ¯\_(ツ)_/¯

**Comment by matiasfrndz** [comment]
I've checked some [jekyll themes on RubyGems](https://rubygems.org/search?utf8=%E2%9C%93&query=jekyll-theme) and it looks as if most use Linux style line endings (LF). I'd probably recommend using `end_of_line = lf` in `.editorconfig`, this may require changing `core.autocrlf` in your Git config.

**Comment by mmistakes** [comment]
Beats me. I build the theme on macOS and Windows and all of the defaults are set to `LF`. So I have no idea why anything is `CRLF`.

**Comment by matiasfrndz** [comment]
I checked again. The only gem version affected by this is 4.10.0. Both versions 4.8.1 and the current version 4.10.1 don't have this issue, i.e. the files have Linux stye `LF` line endings.

Based on that you can probably close this issue.

**Comment by mmistakes** [comment]
Might have to do with Bundler then. 4.10.1 was `gem build` on macOS, the others were likely Windows. No idea why it decides to change the line endings when all of the source files are authored with `LF`.
