### ISSUE TITLE
Excerpt as strapline

### ISSUE THREAD

**Issue by johnlane** [mmistakes/minimal-mistakes#1569]
- [x] This is a question about using the theme.
- [x] This is a feature request or enhancement.

I am using the `excerpt` frontmatter to set what I would call a *strapline* which appears on the page masthead `overlay_image` beneath the `title`.

When I do this, the same `excerpt` is used on the paginated output. I would sometimes prefer that to be different: if I don't define an excerpt then the paginated text quotes the first paragraph of the content. I would like to retain this behaviour whilst, at the same time, defining a strapline.

I just wanted to ask

* am I using it right?
* what would you think about a `strapline` frontmatter to be used on the masthead in preference to any defined `excerpt` so the latter could, if defined, be different?
* does that make sense at all?

**Comment by mmistakes** [comment]
See https://github.com/mmistakes/minimal-mistakes/issues/1429

**Comment by johnlane** [comment]
Ok, I read #1429 and saw you're not too keen on the complexity of the suggestion that aligns most with my question.

However, I took a quick look myself and it was trivial to implement what I wanted. All I did was change [_includes/page__hero.html]( https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/page__hero.html#L45) at line 45:
```
-      {% if page.header.show_overlay_excerpt != false and page.excerpt %}
+      {% if page.strapline %}
+        <p class="page__lead">{{ page.strapline | markdownify | remove: "<p>" | remove: "</p>" }}</p>
+      {% elsif page.header.show_overlay_excerpt != false and page.excerpt %}
```
This allows one to have an *excerpt* which displays on index pages that is different to a *strapline* that displays beneath the title on an overlay image. If there is no defined *strapline* then the *excerpt* behaviour is used instead (i.e it works as it does now).

(I'm not fussed about terminology, just functionality; if you would prefer a different name than *strapline* that's fine - it's just the concept I wanted). 

What do you think, should I submit a PR for you ?

**Comment by johnlane** [comment]
just pinging this issue due to the stale marker because I am still interested in providing this functionality.
