### ISSUE TITLE
Using jekyll-algolia on the documentation website

### ISSUE THREAD

**Issue by pixelastic** [mmistakes/minimal-mistakes#1570]
- [x] This is a feature request or enhancement.

Hello,

As we previously discussed (I lost track of which issue/PR it was), I'd like to feature your theme in the official jekyll-algolia documentation.  But it seems that your [documentation website](https://mmistakes.github.io/minimal-mistakes/) is not yet using the v4.10.0 that includes the jekyll-algolia implementation. 

![image](https://user-images.githubusercontent.com/283419/37165578-4ac761fa-22fd-11e8-9ed4-89c8988da6e9.png)

I'm opening this issue as a way of being alerted when the new version will be deployed live, so I can update the doc on my side. I hope you don't mind me hijacking your issues for that :)

**Comment by pixelastic** [comment]
> Not sure if the documentation site will ever use Algolia due to how Travis CI would need to be integrated and how I have it under the docs/ folder.

I, too, have been frustrated with how cumbersome TravisCI can be for updating records on GitHub pages. Something I recently thought about was to replace TravisCI with Netlify (not for hosting, just for pushing records).

The way it would work would be to have Netlify listen to every push to `master` and run `jekyll algolia` in response. It won't even have to host anything, just run `jekyll algolia` to update your records in parallel of GitHub Pages deploying the website.

Would that be easier for you? If you're ok adding Netlify to the mix, I can write the step by step documentation.

**Comment by mmistakes** [comment]
I'll have to give it some thought. A lot of users clone this repo and use the /docs site as a starter. 

I don't want to do further complicate that and "junk" up the repo more than it already is with additional config files. It just becomes a support bottleneck for me as I'm already constrained on time.

**Comment by mmistakes** [comment]
The [documentation site](https://mmistakes.github.io/minimal-mistakes/) now uses Algolia search.

I just had to add ` gemfile` line to my `.travis.yml` file and modify the build script slightly to have it find `/docs` on the master branch.

**Comment by pixelastic** [comment]
Thanks! Gonna update the documentation on my side in the coming days!

**Comment by pixelastic** [comment]
Updated the documentation on my side with a brand new page listing all themes: https://community.algolia.com/jekyll-algolia/themes.html
