### ISSUE TITLE
How to add custom fonts?

### ISSUE THREAD

**Issue by seldamat** [mmistakes/minimal-mistakes#1571]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
4.5.1
- **Jekyll version:**
3.5.2
- **GitHub Pages hosted:** yes/no
yes
- **Operating system:** 
mac os sierra
---

## Question

I would like to add my own custom font to the minimal-mistakes template. I've added a *.ttf file under ./assets/fonts/*.tff and created a .css file in the same directory that contains the code:

```
@font-face {
    font-family: BrownFox;
    src: url("/assets/fonts/BrownFox.ttf") format('truetype');
    font-weight: bold;
    font-style: normal;
}
```

How can I update just a single phrase in the banner of my home page to reflect this? My fall back option is to just create a high res image of the font and upload it without any of the text (suboptimal).

Thank you so much for your continued support.

**Comment by mmistakes** [comment]
If you can target the text you want to change the font with a CSS selector should be easy enough.

You'd use that selector and add `font-family: Brown fox;` to it.

**Comment by seldamat** [comment]
Hmm I'm afraid I do not know what a CSS selector is or much about HTML web coding in general besides pure basics and what can be gleaned from comments & pseudocode.

I've played a round a bit with CSS selector patterns as suggested by https://www.w3schools.com/cssref/css_selectors.asp but I haven't been able to make any progress.

Could you perhaps explain in a bit more detail? I would greatly appreciate the transmission of knowledge! Thanks :)
