### ISSUE TITLE
Foot in the middle of the page

### ISSUE THREAD

**Issue by travelalone** [mmistakes/minimal-mistakes#1578]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [x] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---
When I add a `html` page in my `markdown` post,  the **Foot** is not at the bottom, but in the middle of my page. 
It's like this 

![bokeh](https://user-images.githubusercontent.com/16696598/37280902-1f14f416-262a-11e8-9c74-7d04e54d2559.png)

## Environment informations

- **Minimal Mistakes version: 4.10.0** 
- **Jekyll version: 3.7.3**
- **GitHub Pages hosted:** yes
- **Operating system: Linux/Ubuntu** 

---

## Expected behavior

The Foot should be placed at the bottom

Here is my file
**zip_file** : [file.zip](https://github.com/mmistakes/minimal-mistakes/files/1802489/file.zip)

**Comment by mmistakes** [comment]
You're loading some arbitrary JavaScript and CSS that appears to be messing with the page.

![image](https://user-images.githubusercontent.com/1376749/37282494-fda71750-25ca-11e8-9141-04c43f54bbb2.png)

I don't think the theme is at fault here. What you might want to try is adding the JavaScript to the footer so it loads after the theme's main scripts. They determine the height of the page to force the footer to the bottom, your scripts are likely interfering with this which is causing the footer to be placed in the middle of the page.

**Comment by travelalone** [comment]
How can I add the JavaScript to the footer? I'm new to the JavaScript, and I'm not good at this. Could you show me how to do this? Thanks.

**Comment by mmistakes** [comment]
Please read the theme's documentation.

https://mmistakes.github.io/minimal-mistakes/docs/javascript/

**Comment by mmistakes** [comment]
Related #1494, #1504, #1427
