### ISSUE TITLE
Author_profile not showing for single layout

### ISSUE THREAD

**Issue by pateskinasy** [mmistakes/minimal-mistakes#1579]
- [X] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [X] I am using the latest version of the theme.
  - [X] I have updated all gems with `bundle update`.
  - [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.10.0
- **Jekyll version:** 3.6.2
- **GitHub Pages hosted:** yes
- **Operating system:** Windows 10 Pro

---

## Expected behavior

Can't manage to see Author_Profile in any post
Example: https://pateskinasy.github.io/blog-test/ 

Background:
Layout for post is single
Author_profile is set to true (both in config.yml defaults as well as in post YAML), but I can't figure out what sort of CSS interference is going on

I've even tried the suggested solution in this issue: https://github.com/mmistakes/minimal-mistakes/issues/735, but no luck

## Steps to reproduce the behavior

https://github.com/pateskinasy/pateskinasy.github.io

$ bundle exec jekyll build --trace
Configuration file: C:/Users/Patricia/documents/github/pateskinasy.github.io/_co                                                                                            nfig.yml
            Source: C:/Users/Patricia/documents/github/pateskinasy.github.io
       Destination: C:/Users/Patricia/documents/github/pateskinasy.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme mmistakes/minimal-mistakes
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
    Liquid Warning: Liquid syntax error (line 4): Unexpected character & in "paginator.page == 1 && featured_posts.size > 0" in /_layouts/home.html
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: minimal-mistakes/skins/contrast. Load path: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-theme-primer-0.5.2/_sass on line 3
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-sass-converter-1.5.0/lib/jekyll/converters/scss.rb:123:in `rescue in convert': File to import not found or unreadable: minimal-mistakes/skins/contrast. (Jekyll::Converters::Scss::SyntaxError)
Load path: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-theme-primer-0.5.2/_sass on line 3
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-sass-converter-1.5.0/lib/jekyll/converters/scss.rb:118:in `convert'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:98:in `block in convert'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `each'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `reduce'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `convert'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:80:in `render_document'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:62:in `run'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:466:in `block in render_pages'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:464:in `each'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:464:in `render_pages'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:193:in `render'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:73:in `process'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby25-x64/bin/jekyll:23:in `load'
        from C:/Ruby25-x64/bin/jekyll:23:in `<main>'

$ bundle exec jekyll build --trace ---verbose is ultra long, let me know if needed.

**Comment by mmistakes** [comment]
The author profile is there, it's just not populating it with any content which makes it look like it's blank.

![image](https://user-images.githubusercontent.com/1376749/37363054-60afa4e0-26cd-11e8-9596-e8256c9e05a3.png)

What I believe is happening is your posts have `author: "Pat Eskinasy"` in their YAML Front Matter. When you use this method you also have to include a key with that data in `_data/authors.yml` so it knows what `name`, image, social links, etc. to pull in.

Check the documentation on an [example of that](https://mmistakes.github.io/minimal-mistakes/docs/authors/).

If your site is a single author site just remove those `author` lines from the post. The theme will use what you've defined as the author in `_config.yml` instead.

**Comment by pateskinasy** [comment]
Thanks Michael. Confirmed. Removing the `author` line from the post file did the trick. 
Thanks again
