### ISSUE TITLE
Add posts, categories, tags, and collection layouts for easier archive page building

### ISSUE THREAD

**Issue by travelalone** [mmistakes/minimal-mistakes#1582]
- [ ] This is a question about using the theme.
- [x] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

When I browse the `Tag Archive` page, I should spend a lot time to find the tags I need.

Could you add some Tags' collection at the head of `Tag Archive` page, like your so simple theme
and also posts page and categories page? 

Like this:
![tag_archive](https://user-images.githubusercontent.com/16696598/37448226-6d23e6f2-2860-11e8-887e-67377ca60d8b.png)

**Comment by mmistakes** [comment]
You'll have to use the `sort` filter on the array... maybe using the `size` property.

Have you asked for help on [Jekyll Talk](https://talk.jekyllrb.com/)? You'll get answer quicker there than from me as this is vanilla Liquid/Jekyll. Nothing special related to the theme to do this.

**Comment by mmistakes** [comment]
Also if you look at my other theme So Simple you'll see how I'm sorting it by tag count.

https://github.com/mmistakes/so-simple-theme/blob/master/_layouts/tags.html

**Comment by sheldonhull** [comment]
Thanks, no, i haven't, i was posting more to help in case it saved her some work, or you, that said, thanks for the pointers as it was something I wanted to know for sure.

**Comment by mmistakes** [comment]
[New layouts](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#taxonomy-archives) have been added to the `master` branch and will be available in the next theme release.

- [`layout: categories`](https://mmistakes.github.io/minimal-mistakes/categories/)
- [`layout: tags`](https://mmistakes.github.io/minimal-mistakes/tags/)
- [`layout: collection`](https://mmistakes.github.io/minimal-mistakes/portfolio/) with grid view
- [`layout: posts`](https://mmistakes.github.io/minimal-mistakes/year-archive/)
