### ISSUE TITLE
How do I limit image width?

### ISSUE THREAD

**Issue by johnlane** [mmistakes/minimal-mistakes#1583]
- [x] This is a question about using the theme.
---

I have an image displayed with:
```
![](/images/image.jpg){: .align-right}
```
I would like to limit its width to, say, half of the content space. What's the right way to do that?

What I have done is to add a CSS class
```
.width-half {
    width: 50%
}
```

and then used it like this
```
![](/images/image.jpg){: .align-right .width-half}
```
It works, but I would have thought the theme would have a provision for this. I did look through the sass, particularly in `_sass/minimal-mistakes/_utilities.scss`, but never saw anything. So I'm just wondering if I am doing this wrong ?

**Comment by mmistakes** [comment]
The way you're doing it is fine, the theme doesn't have any such utility classes for this. It has alignment classes and that's it.

**Comment by johnlane** [comment]
thanks for clarifying :)

**Comment by ShaneKosieradzki** [comment]
@mmistakes  Is it possible to do something similar to this but using the [figure helper](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#figure)? That is, is it possible to scale down the width of the `figure` template?
