### ISSUE TITLE
Staticman_v2 comments not showing up js-comments returns nothing upon Inspect

### ISSUE THREAD

**Issue by pateskinasy** [mmistakes/minimal-mistakes#1584]
- [X] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [X] I am using the latest version of the theme.
  - [X] I have updated all gems with `bundle update`.
  - [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.10.0 
- **Jekyll version:** 3.6.2
- **GitHub Pages hosted:** yes
- **Operating system:** Windows 10 Pro

---

## Expected behavior
Comments not showing on blog post. 
js-comments is returning nothing upon Inspect
For blog post: https://pateskinasy.github.io/blog-test/

## Steps to reproduce the behavior
What I've done: 
* Set comment provider to "staticman_v2" and branch to "master"
* Comment set to true in config.yml
* Comment set to true in the post  https://pateskinasy.github.io/blog-test/
* Abused comment form a bit as I wanted to remove URL from form
* Abused single layout a bit as I wanted to show post publishing date and read time (and number of comments) in line 
* Added Staticman as a Collaborator and received OK!
* Webhook is connected as per Staticman documentation 
* given sintax for comments folder is posts/data/comments, changed a few files to incorporate that path
* Comments were still not showing after having tried 4+ comments, so tried enabling reCaptcha. reCaptcha seems ok.
* Moderation set to true everywhere, received requests to merge from staticman, but comments wouldn' show up
* Moderation set to false, I'd still get message "Thanks for your comment! It will show on the site once it has been approved.", but comment would still not show up

Repository is: https://github.com/pateskinasy/pateskinasy.github.io

Result of trace is:
```
Configuration file: C:/Users/Patricia/documents/github/pateskinasy.github.io/_config.yml
            Source: C:/Users/Patricia/documents/github/pateskinasy.github.io
       Destination: C:/Users/Patricia/documents/github/pateskinasy.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme mmistakes/minimal-mistakes
    Liquid Warning: Liquid syntax error (line 4): Unexpected character & in "paginator.page == 1 && featured_posts.size > 0" in /_layouts/home.html
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: minimal-mistakes/skins/contrast. Load path: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-theme-primer-0.5.2/_sass on line 3
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-sass-converter-1.5.0/lib/jekyll/converters/scss.rb:123:in `rescue in convert': File to import not found or unreadable: minimal-mistakes/skins/contrast. (Jekyll::Converters::Scss::SyntaxError)
Load path: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-theme-primer-0.5.2/_sass on line 3
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-sass-converter-1.5.0/lib/jekyll/converters/scss.rb:118:in `convert'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:98:in `block in convert'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `each'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `reduce'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `convert'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:80:in `render_document'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:62:in `run'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:466:in `block in render_pages'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:464:in `each'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:464:in `render_pages'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:193:in `render'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:73:in `process'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (3 levels) in init_with_program'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `each'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (2 levels) in init_with_program'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby25-x64/bin/jekyll:23:in `load'
        from C:/Ruby25-x64/bin/jekyll:23:in `<main>'

```
-->

<!--

**Comment by mmistakes** [comment]
I see the issue. Your comment data files aren't in the correct location. They need to live inside of the `_data` folder... that is where the theme expects them.

It matches the post URL to a sub-folder in `_data/comments` and if it sees any YAML files it spits out the comments. Looks like yours are in the [root of the project](https://github.com/pateskinasy/pateskinasy.github.io/tree/master/docs/_data/comments/blog-test).

Move the files to `_data` so you have something like `_data/comments/blog-text/*.yml`. Then you'll need to change your Staticman config file so it generates new comments with the proper path.

Instead [of this](https://github.com/pateskinasy/pateskinasy.github.io/tree/master/docs/_data/comments/blog-test) you'll want to use the default value instead of picking up what I'm using for the demo site:

```yaml
path: "/_data/comments/{options.slug}"
```

**Comment by pateskinasy** [comment]
Thanks Michael, super appreciated!

Moving all comment-related data and paths to `/_data/comments/` made the comments show up in the post.

However I've now regressed to a problem I was having earlier (and managed to solve then somehow): "Sorry, there was an error with your submission. Please make sure all required fields have been completed and try again."). All fields are filled..

The error I get from console is: Cannot GET /v2/entry/pateskinasy/pateskinasy.github.io/master/comments

![image](https://user-images.githubusercontent.com/18645509/37485625-eec9d4b4-2883-11e8-9006-83bfeefafba5.png)

Any hints on how to proceed?

**Comment by mmistakes** [comment]
Hard to say. Those errors are related to Staticman not liking what you're sending over the wire via the form submit.

Since you edited the form I'd start there. Could be something simple like you didn't update Staticman's config file to not require fields you removed... or vice versa.

You might be able to expand that object in the console to see if there are any clues, but I'm not sure. JavaScript isn't really my forte.

**Comment by pateskinasy** [comment]
Thanks once again for the hints @mmistakes 

As an update for others getting stuck in the future: I did not manage to get to the root of what was causing the issue (sth with JS was off). My way to fix it was to revert the codebase to a previous "working commit" and apply your fix of moving all comment-related data and paths to /_data/comments/

Closing this off now.
