### ISSUE TITLE
Remote Theme - Version in Header vs github tagged release

### ISSUE THREAD

**Issue by sheldonhull** [mmistakes/minimal-mistakes#1586]
I just successfully cloned the remote_theme repo, updated with all my content, and built. 
The header in the html shows :

```html
  Minimal Mistakes Jekyll Theme 4.9.0 by Michael Rose
  Copyright 2013-2018 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE.txt
```

I'm a little confused as the tagged release in github shows 4.10. I've seen I can use "bleeding edge" by referencing the github repo url. However, if I'm ok using the latest stable release and want the benefit of a remote_theme, shouldn't I see any tagged release in releases reflected when I do a build? I also see I can use a tag to specify a specific release. I'm assuming that the default behavior should be to get latest release.

My environment: 
Windows 10 
Docker - jekyll latest

My build console output confirmed: 
```cmd
Bundle complete! 5 Gemfile dependencies, 83 gems now installed.
```

**Comment by sheldonhull** [comment]
I just performed a build using `remote_theme: mmistakes/minimal-mistakes@4.10.1` and built successfully. However, the header still shows `4.9.0` so unless I'm doing something wrong, I'm guessing that the header information is not picking up the version correctly even though I'm assuming my remote test is running `4.10.1`

**Comment by sheldonhull** [comment]
I reviewed and verified package.json in your repo shows `4.10.1` . Hopefully this is enough information to shed some light on my ignorance :-)  Thanks again for this awesome theme and your fantastic contribution to the community.

**Comment by mmistakes** [comment]
Not sure. In my experience you don't need to tag it, just include the remote theme and everytime it's built it will pull down the latest version from GitHub.

The only thing I've seen cause confusion is people expect their sites to update with the latest version... without doing a build. In those cases you have to either push up some new content or do a blank commit to force it.

**Comment by mmistakes** [comment]
It could be something as simple as the browser caching the HTML. Make sure you fully flush it, or try opening the page in a private/incognito tab as that doesn't use the cache.

**Comment by sheldonhull** [comment]
I did a cache empty and reload in chrome in incognito, still shows 4.9. I will run docker command to force rebuild. I've not published, it's running locally only. I'll let you know the result

**Comment by mmistakes** [comment]
Can you use the gem version instead or are you hosting on GitHub Pages?

The Ruby gem version is more stable as Jekyll's remote theme plugin is fairly new and potentially had bugs.

**Comment by mmistakes** [comment]
Also make sure you don't have any local copies of `_layouts`, `_includes`, `_sass`, etc.

From the looks of [your repo](https://github.com/sheldonhull/sheldonhull.github.io) that's what you've done. They're are overriding the remote theme's versions which is why you are seeing 4.9.0 and not the latest.

**Comment by sheldonhull** [comment]
fyi, my repo is not what I'm testing with. I actually learned about remote theme's later on , and have a local forked copy of your remote theme demo repo that I'm doing all my testing with. 

![image](https://user-images.githubusercontent.com/3526320/37548346-2bff2246-2945-11e8-8303-10aa7d71d584.png)

I'll have to figure out how to use the gem based approach with only overrides included as all I want to do is eliminate manual updates, and if the gem based approach can do that, I'll do that way instead. I just am newer to gem's, so must have missed that it worked similar.

**Comment by sheldonhull** [comment]
Followed the directions for ruby gem method and worked great. Must be something with the remote_theme issue. I removed everything except my customized stuff and used the gem approach and it gave me the updated version. Thanks again for the beautiful theme. I got a great complement on the clean design today from someone, so that's a positive!
