### ISSUE TITLE
absolute_url vs relative_url

### ISSUE THREAD

**Issue by mplacona** [mmistakes/minimal-mistakes#1588]
- [ ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [X] I believe this to be a bug with the theme.
  - [X] I am using the latest version of the theme.
  - [X] I have updated all gems with `bundle update`.
  - [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment information

- **Minimal Mistakes version:*latest* 
- **Jekyll version:*3.7.3*

---

## Expected behaviour
Seems like this theme uses `absolute_url`, which will yield urls like 0.0.0.0:PORT when you use it with docker. I've noticed that your other theme "so-simple" works well with docker as it uses `relative_url`. I was wondering if there's a reason for that. I'd be happy to update it all and send you a PR, but wanted to check with you first if there's a reason. Should all work the same after the update.

**Comment by mmistakes** [comment]
Are you correctly assigning `JEKYLL_ENV=production` at build? Jekyll defaults `development`, which overrides `url` with `localhost`... or in your case `0.0.0.0:PORT`.

Give `production` a try first. `absolute_url` could likely be changed to `relative_url`, but I think your issue is the [environment flag](./.cache/sync-requires.js). You might want to search through the closed issues as I know I've seen others who had the same problem and solved it without messing with the theme.

**Comment by mmistakes** [comment]
Here's how to solve it. Closing as this is a duplicate.

https://github.com/mmistakes/minimal-mistakes/issues/1162#issuecomment-320642249

**Comment by mplacona** [comment]
Thanks @mmistakes. I'd already tried that, but it doesn't quite solve the problem. When you set the build for `production`, you're basically saying "use the url as it is in my _config.xml". In the example you gave me, the author changes the url to be what they want locally. However, deploying this to production would mean changing that again, which is prone to errors.

Ideally, if you use a relative path instead, the url stops getting on the way.

**Comment by mmistakes** [comment]
This is where multiple config files can come into place. You can daisy chain them in your build command.

> Specify config files instead of using `_config.yml `automatically. Settings in later files override settings in earlier files.
>
> ref: https://jekyllrb.com/docs/configuration/

```yaml
# _config.yml
# contains all your normal configs
```

```yaml
# _config.dev.yml (or whatever you want to name it)
# add any variables you want to override for development purposes

url: http://localhost:4000
```

Then your Jekyll build command would change to `jekyll serve --config _config.yml,_config.dev.yml`

**Comment by mplacona** [comment]
Right on! Doing that solved it.

Still think it would be easier to just use relative urls to avoid the "hackery" around how you start Jekyll, but this completely solved it.

Thank you for the responsiveness!
