### ISSUE TITLE
Optimising the generated HTML output

### ISSUE THREAD

**Issue by justinhartman** [mmistakes/minimal-mistakes#1589]
- [x] This is a feature request or enhancement.
- [x] I am using the latest version of the theme.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
---

## Environment information

- **Minimal Mistakes version:** 4.10.1
- **Jekyll version:** 3.7.3
- **GitHub Pages hosted:** yes
- **Operating system:** macOS 10.13.3

---
Michael, I really want to compliment you on a truly amazing job you've done with this theme. I've worked with a number of CMS' in the past, which includes WordPress, Joomla, Drupal, Jekyll and more recently Grav. Grav has become my preferred choice but after installing your theme and working with it I am gobsmacked by how powerful Jekyll is. 

Your theme has really brought out and showcased the power of Jekyll but more importantly, I have never worked with a theme that is so simple, yet so powerful in execution. I really am blown away by both Jekyll and by you and what you've done. You have inspired me and I've spent the last 48 hours or so, almost non-stop, working with your theme and setting up my site. It's fantastic.

I have noticed however that due to the modularity and flexibility of the theme the outputted HTML is a bit messy. This is understandable as it is fragmented and trying to output neat HTML is nigh impossible given how configurable the theme is.

I have a proposition which I want to run by you first before implementing and submitting a PR as I don't want to waste either of our time. As I've been going through the site I have been optimising the generated HTML and so far so good. 

To give you an example, here is the Archive source code of the MM demo site:
![original](https://user-images.githubusercontent.com/717118/37557846-587ddf00-2a13-11e8-8884-0891716e9782.png)

The following is my Archive source code on my site that I've been cleaning up.
![optimised](https://user-images.githubusercontent.com/717118/37557844-582d0ada-2a13-11e8-8fdd-d0a0f3f84d59.png)

As you can see, mine is nowhere near perfect but it is improving on the outputted HTML generated by Jekyll. In addition, I'm only a short way in with the head elements and there is a lot of work to (a) get this right and then (b) get the body and other areas (footer, nav, etc.) to a point where the output is neater than current.

My proposition is for me to make a best-effort attempt at cleaning up the output so that there are less white-space and line breaks and try to get the output as clean as humanly possible. I am going to do this irrespective but my question to you is would you like me to fork, fix and PR this type of change or should I just focus on this for myself? In other words, is there value in you receiving a PR with this type of change or not?

Let me know.
Cheers,
Justin

PS: Thank you for your work. It is inspiring.

**Comment by mmistakes** [comment]
Thanks.

I think where it makes sense then sure submit a PR with cleaned up whitespace and indention. For the most the source should be pretty clean.

Though likely what you're seeing is the product of Liquid. Things like `{% for %}`, conditionals, etc. don't collapse and that accounts for all the whitespace and screwed up indentation in the outputted HTML. Liquid 4 has a way to collapse the whitespace now so I'd be interested in PR's that help with that.

That said I'm not super concerned about the whitespace. Anyone who cares about page performance should be minifying their HTML anyways to strip out all whitespace and get the file size down. As long as the source is readable that's mainly what I'd like to see upheld.

**Comment by justinhartman** [comment]
Yes. Liquid makes the output dirty. The source is clean.
I had no idea Liquid 4 could do this. I'm happy to explore this route and see if I can add value on that front. I'll play around and see what I can do and if I feel I can add value with a PR I'll go ahead and do that; based on being able to control the whitespace output.

You don't have to leave this issue open. I was trying to get some insight into your thinking and roadmap so I now know what will add value.

**Comment by mmistakes** [comment]
Sounds good.
