### ISSUE TITLE
[Feature Request] Floating TOC

### ISSUE THREAD

**Issue by karthikraman** [mmistakes/minimal-mistakes#159]
Hello, thanks for the seriously amazing theme --- it rocks. I was wondering if it is possible to float the TOC along with the scroll, since some pages can be really long, like the theme setup page.

Cheers,
Karthik

**Comment by mmistakes** [comment]
Yes that's possible. I would have done it that way by default but if you have a really long TOC list it overflows off the screen with no way of viewing it all.

As long as your lists aren't that long it shouldn't be an issue unless you want to tinker with the TOC's CSS and add some scroll overflow to it.

But if you want to make it so it stays put as you scroll just change `position: absolute` to `position: fixed` on the `.toc` class in [`/_sass/page.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/page.scss#L459).

``` css
.toc {
	font-size: 95%;
	@media #{$large} {
		display: block;
		@include grid(12,2);
		@include prefix(12,0.5);
		@include suffix(12,0.5);
		position: fixed; /* changed from absolute */
		top: 5.5em;
		right: 0;
		background-color: $white;
	}
}

**Comment by karthikraman** [comment]
Super, works perfect! Thanks!
