### ISSUE TITLE
Staticman v2 stopped working

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#1590]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

The Staticman v2 used to work correctly up until two days ago where this was added, https://github.com/vih/historie/commit/2f654c14115d8aefde2df1448ec07f622453716c - and as far as I can tell, I have not made any breaking changes since. https://github.com/vih/historie/commits/gh-pages

I get this - which seems to be related to https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments.html#L80 - where [reCaptcha][siteKey] is also part of the form.

´´´
"{"success":false,"data":["hidden"],"rawError":{"_smErrorCode":"INVALID_FIELDS","data":["hidden"]},"errorCode":"INVALID_FIELDS"}"
´´´

---

## Environment informations

- **Minimal Mistakes version:** 4.10.1
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** 

---

## Expected behavior

I was expecting the comments with staticman v2 to work - but it seems I get a 500 from staticman, when I inspect the network through Chrome webmaster tools. 

## Steps to reproduce the behavior

Only difference from the original theme staticman.yml is the recaptcha stuff here:

https://github.com/vih/historie/blob/gh-pages/staticman.yml#L97

**Comment by mmistakes** [comment]
If it was working for you and you made no changes then it's likely something on Staticman's side. I don't control that so you might want to inquire with the [project on GitHub](https://github.com/eduardoboucas/staticman).

**Comment by lsolesen** [comment]
Did a little more digging - and it could be related to the minimal mistakes.

I get this - which seems to be related to https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments.html#L80 - where [reCaptcha][siteKey] is also part of the form.

´´´
"{"success":false,"data":["hidden"],"rawError":{"_smErrorCode":"INVALID_FIELDS","data":["hidden"]},"errorCode":"INVALID_FIELDS"}"
´´´

**Comment by lsolesen** [comment]
Also wonder if it has something to do with: https://github.com/eduardoboucas/staticman/commit/28caae6ebae7eacdc3b8d0eab7469712b0781954

**Comment by mmistakes** [comment]
Maybe. Could probably wrap those lines in a Liquid conditional, but Staticman shouldn't care if you send extra data.

The only time I see it fail is when you try to submit a form with missing required fields, as defined in the Staticman config. These recaptca lines aren't required.

**Comment by mmistakes** [comment]
I believe it's related to changes are occurring on the Staticman repo. I haven't touched the MM demo site or anything related to Staticman comments and it's failing there too.
