### ISSUE TITLE
Disable Previus and Next button

### ISSUE THREAD

**Issue by XaBerr** [mmistakes/minimal-mistakes#1592]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

How can I disable these two buttons from the theme?
If you can help this is my use of the [theme](https://xaberr.github.io/JATE/structure).
Thanks in advance.

![cattura](https://user-images.githubusercontent.com/16030020/37613802-3710450a-2ba9-11e8-8956-fc2d59f56164.PNG)

**Comment by mmistakes** [comment]
You can't disable them without customizing the theme.
The [relevant line](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L63) is here which brings in an include for the buttons `{% include post_pagination.html %}`

What you could do add a blank file `/_includes/post_pagination.html` to your local repo which would override the one bundled in the theme. It would have the same affect as removing the buttons from the page.

**Comment by XaBerr** [comment]
Great thanks

**Comment by DonghunP** [comment]
@mmistakes 
`add a blank file /_includes/post_pagination.html to your local repo`

Can you explain it more detail? I have little knowledge of html. 

Sorry for bothering you...
