### ISSUE TITLE
Render markdown codeblock glitch

### ISSUE THREAD

**Issue by XaBerr** [mmistakes/minimal-mistakes#1593]
- [ ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [x] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

I'm using your theme on github to render php+html+twig code and give a problem.
I'm not sure at what level the problem is whether of jekyll or Rouge or others. I wanted to ask you if, since you know the theme, if you could give me a temporary solution to view the code that is not seen.
Thanks in advance.

[code](https://github.com/XaBerr/JATE/blob/master/docs/_docs/view-page.md)

[rendering](https://xaberr.github.io/JATE/view-page)

----
```php
<?php
  private function pageView() {
    $heros = $this->queryFetch("SELECT * FROM hero");
    jBlock();
    ?>
      <div>
        <table class="table">
          <tr>
            <th>hero</th>
            <th>name</th>
            <th>surname</th>
          </tr>
          {% for hero in heros %}
            <tr>
              <td>{{hero["hero_name"]}}</td>
              <td>{{hero["name"]}}</td>
              <td>{{hero["surname"]}}</td>
            </tr>
          {% endfor %}
        </table>
      </div>
    <?php
    return jBlockEnd("twig", ["heros" => $heros]);
  }
?>
```

**Comment by mmistakes** [comment]
This isn’t a theme issue so I’m going to close it.

 It I can give you a hint how to fix it. You need to wrap Liquid tags like `{% for %}` or any variables `{{ yourVar }}` with raw tags so they are aren’t processed when Jekyll builds your site.

Ref: https://help.shopify.com/themes/liquid/tags/theme-tags#raw
