### ISSUE TITLE
No search toggle

### ISSUE THREAD

**Issue by pgyogesh** [mmistakes/minimal-mistakes#1597]
- [X] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [X] I am using the latest version of the theme.
  - [] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** MacOS

---

## Expected behavior

I'm not getting search toggle even after adding `search : true` in `_config.yml`

## Steps to reproduce the behavior

Site: pgyogesh.com/blog
Repo: github.com/pgyogesh/blog

**Comment by mmistakes** [comment]
It's not working because you wrote invalid YAML. Remove the commas after `true`

```yaml
search                   : true, #false (default)
search_full_content      : true, #false (default)
```

**Comment by pgyogesh** [comment]
Thanks @mmistakes ... It worked
