### ISSUE TITLE
Can not add staticman_v2 comments

### ISSUE THREAD

**Issue by Wqrld** [mmistakes/minimal-mistakes#1599]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [x] I believe this to be a bug with the theme.
- [x] I am using the latest version of the theme.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: forked yesterday
- **GitHub Pages hosted:** yes

---

## Expected behavior

I want to be able to use staticman comments.
## Steps to reproduce the behavior
1) add staticman and authorize it
2) configure staticman
3) changed the entry of jekyll.environment == production to jekyll.environment != production because it doesnt seem like you can change the environment from inside github pages
4) add comments: true to your post
5) provider: staticman in the config
6) still no comments

layout single: https://hastebin.com/axovasoyaq.scala (used in my posts)

a post: https://imluc.ga/blog/first-test/

_config.yml https://hastebin.com/oxahebofow.bash

edit: the comments js shows up in the f12 menu

**Comment by mmistakes** [comment]
GitHub Pages automatically sets the environment to `production` when they build your site.

So you changing the conditional to `!=` likely broke it.

Is this a public repo? I need to see the rest of your files so I can reproduce and run a build locally. I can almost guarantee it's not a bug but a setting that was omitted.

**Comment by Wqrld** [comment]
yes, that fixed it! I likely forgot to enable comments or something along those lines
