### ISSUE TITLE
Navigation menu on header image.

### ISSUE THREAD

**Issue by pgyogesh** [mmistakes/minimal-mistakes#1604]
- [ ] This is a question about using the theme.
- [X] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [X] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** MacOS

---

## Expected behavior

Is there any layout which will have navigation on header image?

For Example:
https://jarrekk.github.io/Jalpc/

**Comment by mmistakes** [comment]
No, there is not. This theme doesn't support any such feature, the navigation purposely doesn't overlap header images.

You'll need to use a different theme or hack it yourself.
