### ISSUE TITLE
How to use the pygments style highlighting for fenced code blocks?

### ISSUE THREAD

**Issue by jyuhuan** [mmistakes/minimal-mistakes#161]
The fenced code blocks are not highlighted at all, but the pygments code blocks are fine. Why the separation? How can I apply the pygments highlighting on fenced code blocks?

**Comment by mmistakes** [comment]
Jekyll has a [tag for syntax highlighting](http://jekyllrb.com/docs/posts/#highlighting-code-snippets), you need to use that. Fenced code blocks default to generic looking ones.

See this [sample post](https://raw.githubusercontent.com/mmistakes/minimal-mistakes/master/_posts/2013-08-16-code-highlighting-post.md) for examples.

**Comment by jyuhuan** [comment]
I know that I could use the Liquid syntax (which uses something like `{% highlight java %}`). But I have problem using that, because my blog contents are mainly from some markdown files on my GitHub (which uses the three-backtick syntax to specify code blocks). 

I have solved this problem by replacing the **kramdown** markdown engine with **redcarpet**. A side effect of this replacement is that the table of contents (for example, the one in the *Theme Setup* post) will be destroyed.

**Comment by mmistakes** [comment]
The auto table of contents is a Kramdown only feature.

Another option is to use [Coderay with Kramdown](http://blog.codebykat.com/2013/05/23/gorgeous-octopress-codeblocks-with-coderay/) instead of Pygments or Rouge. I believe it works with fenced codeblocks.
