### ISSUE TITLE
Creating a collection of images

### ISSUE THREAD

**Issue by prateekbhagdev** [mmistakes/minimal-mistakes#1611]
## Description

Is there a way to create a collection of images or can you help me on this? I want to have page for my gallery & just wish as I add the image to the images folder, it starts reflecting on the gallery page. I am new to coding stuff :(

**Comment by mmistakes** [comment]
Not with the theme. You'll need a Jekyll plugin or something custom. 

Ask for suggestions on Jekyll's help forum.

https://talk.jekyllrb.com/
