### ISSUE TITLE
Trying to add ResearchGate social network icon

### ISSUE THREAD

**Issue by jkbecker** [mmistakes/minimal-mistakes#1612]
## Description

I'm in the process of adding the social network [ResearchGate](https://www.researchgate.net/) to the author profile sidebar. I have not fully understood how the icons are shown yet, it seems to be through FontAwesome... which doesn't have the icon for ResearchGate yet. Is there another way to add custom icons? Or should I just use something generic?

**Comment by mmistakes** [comment]
There is not, unless you want to hack something up yourself.

Currently the only way to get an icon in there is by using a Font Awesome one, so the easiest solution would be to [use something generic](https://fontawesome.com/icons?d=gallery).

**Comment by jkbecker** [comment]
Thanks, I'll look into it. Should I keep this to myself or would adding ResearchGate be a valuable addition to the profile? It's a research-focused social network with some low-double-digit million users. Too niche? Let me know and I'll either pull request when I'm ready or I won't ;)

**Comment by mmistakes** [comment]
I’d say if it’s not something Font Awesome supports and requires custom hacks to get in. Then it’s best left to local customizations and not folded into the core theme.

Customizations like this are best suited for https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/author-profile-custom-links.html
