### ISSUE TITLE
First heading appearing twice 

### ISSUE THREAD

**Issue by ahhz** [mmistakes/minimal-mistakes#1618]
## Description
I am using Minimal Mistake with pages that start with a heading, as follows:

```
# Introduction
Blah, blah, blah
```
The way these pages appear is by showing the first heading twice, i.e. the word "Introduction" big and bold on two consecutive lines.

I know I can avoid this by using a YAML front matter block. 

```
---
title: Introduction
---
Blah, blah, blah
```
but, I really prefer not using front matter blocks, if only because it does not appear nicely on my Github page.

## Environment

Hosting on github: 

https://github.com/ahhz/raster/docs
http://ahhz.github.io/raster

The following page uses the YAML front matter and looks good on the website, but not on Github:

http://ahhz.github.io/raster/rationale/
https://github.com/ahhz/raster/blob/master/docs/rationale.md

The following page does not use YAML and looks good on Github but not on the website:

http://ahhz.github.io/raster/examples/example_1/
https://github.com/ahhz/raster/blob/master/docs/examples/example_1.md
 
## Expected behavior

Ideally I can use markdown headings without a YAML front matter block and use the _config.yml file to suppress the double heading. 

## Steps to reproduce the behavior

I don't think there is an error to reproduce. Just me not understanding the system, or the system not working as I would like it to.

**Comment by mmistakes** [comment]
I think you'll have to use the `title` attribute as that's a very common Jekyll convention.

Setting the `h1` element in your Markdown file isn't something I see often. It's almost always left out and added as a `title`. Jekyll even goes as far as to pull the title from your `.md` filename if omitted.

I get the reason why you'd want to include the `h1` directly in the body as it looks better when viewing source on GitHub. But it breaks some common patterns with Jekyll, not to mention SEO things... as you'll get 2 `h1` elements on the page. Which isn't desirable.

You might want to poke around jekyll/jekyll or ask for suggestions on Jekyll Talk. I have to feel others have hit this (especially those who use Jekyll for site docs). There may even be a way to have Kramdown ignore `# Headline` when Jekyll parses it, giving you the best of both worlds.

**Comment by ahhz** [comment]
Thank you, I will try these resources.

**Comment by mmistakes** [comment]
Solution is to use [jekyll-titles-from-headings](https://github.com/benbalter/jekyll-titles-from-headings) plugin to strip `page-title` and replace with body content heading.

Reference: http://talk.jekyllrb.com/t/title-derived-from-heading-appears-twice-on-top-of-page/1686/4?u=mmistakes

**Comment by chfast** [comment]
Do you know if that should also work for GitHub Pages using minimal-mistakes as remote theme? Somehow I cannot make it work for me.
