### ISSUE TITLE
features row links without buttons?

### ISSUE THREAD

**Issue by zahachtah** [mmistakes/minimal-mistakes#1626]
## Description

I like to keep the layout as clean as possible and without buttons if I can avoid it. On my splash page I have feature rows to describe the content. I would like the entire area of each feature (picture+text) to be clickable and follow the link that is normally used with the button. How would I best go about editing the source to achieve this. I could probably get it to work with some ugly hack but thought others might also be interested and you likely know how to make this as slick as possible.

## Environment

I am using github-pages with the ruby-gem method (does that limit my hackability?)

---

## Expected behavior

Just want a feature row without buttons but still with links to new pages by clicking the area of image+text

**Comment by mmistakes** [comment]
Edit `_includes/feature_row` to behave you want.

Here's the line that applies the link to a text anchor styled as a button. You could use the same Liquid variable and wrap the entire feature if that's what you want as the link.

https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/feature_row#L43

**Comment by zahachtah** [comment]
I got that to work by wrapping the link around the image. if I wrap it around the text also all text becomes styled as links. I assume I would have ot go into the css to define feature_row.a to behave like normal text?

**Comment by mmistakes** [comment]
That's correct. You'll likely need to add `text-decoration: none` to something to remove the underlines.

**Comment by zahachtah** [comment]
feel free to ignore this if its too detailed to bother you for, but this does not do the job (added to the _page.scss file) although I kinda thought it would... any ideas?

```
.feature__item {
  a {
      color: #fff;
      text-decoration: none;
  }
}
```

**Comment by mmistakes** [comment]
Best bit of advice I can give you when having CSS issues is open the page in your browser's web developer tools. And start poking around the elements to see which one you need to apply CSS to.

You likely have the wrong specificity or it's being overrided somewhere else in the cascade.

**Comment by zahachtah** [comment]
Will do. thanks again!
