### ISSUE TITLE
The file named _octopress.yml doesn't worked.

### ISSUE THREAD

**Issue by SaulLawliet** [mmistakes/minimal-mistakes#163]
When I used `octopress` to create a post, I found it seems like using the default config.
So I move all contents from `_octopress.yml` to `_config.yml`.
The `octopress` command worked good.

Sorry for my poor english.

**Comment by synthbiont** [comment]
Very useful. 

Apparently with octopress 3.0 the configuration is read from `_config.yml ` as shown here https://github.com/octopress/octopress
