### ISSUE TITLE
Disqus

### ISSUE THREAD

**Issue by vishaleckhart** [mmistakes/minimal-mistakes#164]
Is there any more configuration for discqus other than putting your disqus shortname in the _config.yml and _includes/disqus_comments files?
thank you

**Comment by mmistakes** [comment]
Set `comments: true` In the YAML Front Matter of each post you want comments on. If you want another behavior it's easy enough to change the Liquid if statement in the layout to do whatever you want (ie: comments enabled on all posts, not at all, etc)

**Comment by ohoroyoi** [comment]
is there any way to add disqus as a default using remote-theme? Not to add each.
