### ISSUE TITLE
Font Awesome 5 SVG with JS - Huge File Size

### ISSUE THREAD

**Issue by deepfriedbrain** [mmistakes/minimal-mistakes#1643]
I'm currently using v4.6.0 and was looking to upgrade to the latest version (4.11.1). I noticed that Font Awesome 5 SVG with JS file (which is used in this project) is about 700KB and even the gzipped version is about 290KB. 

Isn't the huge file size an issue for a handful of icons that can be downloaded individually and self-hosted? 

In the current version, Font Awesome woff2 file that gets downloaded is about 70KB, and even that is a concern to me. I counted that my site was using fewer than 20 icons and I was planning to hand-pick them and serve just those. I did that already in another project.

**Comment by mmistakes** [comment]
Not sure. This is a question you should ask the maintainers of Font Awesome. The SVG in JS version is what they recommend.

https://fontawesome.com/how-to-use/

**Comment by deepfriedbrain** [comment]
Good idea. I'll post my issue to the FA team and close this issue. Thanks.

**Comment by coliff** [comment]
Font Awesome's size continues to grow as it adds more icons. It's now at v5.7.1 and 1.1MB (and 453KB gZipped). I think it'd be good to look at alternative ways to display the icons. The webfonts/CSS method is a lot smaller.

**Comment by mmistakes** [comment]
@coliff Happy to look at a PR if you want to swap out the SVG/JS version with the CSS/webfont one. I know there have been issues (#1457) with JavaScript in the menu executing slowly. As far as I can tell those issues started after switching to the JS version of FontAwesome.

I'd be curious to see if going back to the CSS/webfont version speeds up the page load some and fixes it.
