### ISSUE TITLE
How to add latest font awesome icons?

### ISSUE THREAD

**Issue by juliohm** [mmistakes/minimal-mistakes#1646]
Today I tried to use the recently released ResearchGate icon, but the link provided at the bottom didn't work:

https://fontawesome.com/icons/researchgate?style=brands

I copied `<i class="fab fa-researchgate"></i>` in place of my currently existing icon in minimal mistakes. Any guidance is appreciated.

**Comment by mmistakes** [comment]
The version of FA linked in the theme is a few versions back. You'll have to wait until #1620 is merged in or apply the patch manually to your site.

**Comment by juliohm** [comment]
Thank you @mmistakes, I will close the issue, the patch should be easy to apply. I will wait for the PR to be merged.
