### ISSUE TITLE
How to get RSS feed by tag? 

### ISSUE THREAD

**Issue by ritiek** [mmistakes/minimal-mistakes#1648]
Hi, going to `/feed.xml` provides RSS feed for all posts. Is it possible to get RSS feed only for posts with a specific tag like the way it is possible with [blogger](https://fedoraproject.org/wiki/How_to_provide_a_category_specific_feed_using_Blogspot_or_Blogger?rd=How_to_provide_a_category_specific_feed_using_Blogger) or [wordpress](https://premium.wpmudev.org/blog/daily-tip-how-to-provide-category-or-tag-specific-rss-feeds-for-wordpress/)?

**Comment by mmistakes** [comment]
RSS feed is built with [jekyll-feed](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml). They only support a single feed for all posts. If you want tag based feeds you'd have to build those yourself, similar to what I suggested in #1460.

You'd create a feed `.xml` page for each tag and with a line similar to the following for grabbing all posts for a given tag/category.

```
{% assign posts = site.tag.your_tag | where_exp: "post", "post.draft != true" %}
```

There is currently an open issue on jekyll-feed to do what you want. I'd weigh in there to try and persuade the maintainers of that plugin to add such a feature.

https://github.com/jekyll/jekyll-feed/issues/70

**Comment by ritiek** [comment]
I guess `.xml` page for each tag would suffice for my case as well. Although, I think I'll give up a thumbs up for this feature on jekyll/jekyll-feed#70. Thanks for the help!
