### ISSUE TITLE
I  think PR 1653 broke build for projects using remote theme

### ISSUE THREAD

**Issue by LucySheridan** [mmistakes/minimal-mistakes#1658]
## Description
I am generating GitHub pages referencing the Minimal Mistakes theme remotely, since about a hour ago my builds have failed because of the following error: 
Your SCSS file `assets/css/main.scss` has an error on line 228: Undefined variable: "$gitlab-color". 

This appears to coincide with a update that was done in this repo about an hour ago...

**Comment by LucySheridan** [comment]
Yep - already worked that out... and fixed it. Is there a way to sign up
for notification of changes. I was in the middle of presentation on GitHub
pages (perfect timing) when this happened... :)

**Comment by mmistakes** [comment]
You're best bet would be to star and "watch" this repro. GitHub will send you emails when commits are pushed so you'll know what's being worked on if you need to react to them due to having a custom build.

**Comment by mmistakes** [comment]
Also, if you want to lock what version of the theme you use vs. being on the bleeding edge of `master` you can do something like this in your _config.yml file:

```yaml
remote_theme: mmistakes/minimal-mistakes@4.11.2
```
