### ISSUE TITLE
Lunr search results missing content

### ISSUE THREAD

**Issue by adamdmharvey** [mmistakes/minimal-mistakes#1663]
## Environment

- Minimal Mistakes version: 4.11.2 (pinned)
- Ruby gem or remote theme version: mmistakes/minimal-mistakes@4.11.2
- Jekyll version: 3.6.2
- Git repository URL: Company Internal GitHub Enterprise
- Operating system: WIndows Ubuntu & Debian
- GitHub Pages hosted (if yes provide URL to site): Company Internal GitHub Enterprise
- Search Depth: originally default, though tested with search_full_content: true and no difference (though we confirmed that works by searching for words existing beyond line 50 in certain files)

---

## Expected behavior

Searching for a certain key word returns results in a specific file.

## Steps to reproduce the behavior

* Searching for a specific key word returns 1 result, but not for a file that contains the word in the title, excerpt, and dozens of references in the top of the content
* What we've discovered is our entire `_pages` folder, or all files at the root of the site, containing roughly a dozen or so files, do not exist in the generated lunr content store under `_site/assets/js/lunr/lunr-store.js`. Only our sub-folder collections.
* The `minimal-mistakes` docs don't describe if there is a way to include/exclude content, such as referred to by the `lunr` doc examples, so we're wondering how does mmistakes identify which content to scan? Or where to look further to troubleshoot?

**Comment by rdmueller** [comment]
Is it possible to add `site.pages` to the lunr index?

**Comment by rdmueller** [comment]
thanx! I've found the `assets/js/lunr/lunr-store.js` and managed to add the other pages...

**Comment by mrmanc** [comment]
This caught me out a bit yesterday. Just wondering whether it would be best to submit a PR to update the docs with this information, or whether a PR to include `site.pages` would be preferred? The docs currently state:

> The default search uses Lunr to build a search index of all your documents.

Which is a little misleading as it’s only posts and documents in collections.
