### ISSUE TITLE
All Table of Contents entries on pages where one or more headers are defined in a table cell link to null anchors

### ISSUE THREAD

**Issue by tlindsay42** [mmistakes/minimal-mistakes#1666]
## Description

All of the Table of Contents entries on my [Must Read page](https://www.troylindsay.io/must_read/) link to null anchors (`/#`) ([source](https://github.com/troylindsay/troylindsay.github.io/blob/master/_pages/must-read.html)).  I created a simple test page with a h2 header, and I was able to duplicate the issue.  My guess is that this is a kramdown issue, but I asked [here](https://talk.jekyllrb.com/t/kramdown-table-of-contents-links-when-header-is-defined-in-table-cell/1777) and no response yet, so I wanted to check to see if maybe I was doing something wrong, or if this just isn't supported.

## Environment

- Minimal Mistakes version: 
- Ruby gem or remote theme version: 
- Jekyll version:

```powershell
Get-Content -Path .\Gemfile.lock | Select-String -Pattern '^\s{4}(?:jekyll\s|minimal-mistakes-jekyll|jekyll-remote-theme)'

    jekyll (3.7.3)
    jekyll-remote-theme (0.2.3)
    minimal-mistakes-jekyll (4.11.2)
```

- Git repository URL: https://github.com/troylindsay/troylindsay.github.io/blob/master/_pages/test.md
- Operating system: Windows 10
- GitHub Pages hosted (if yes provide URL to site): https://www.troylindsay.io

---

## Expected behavior

The table of content links to page anchors should populate correctly with named anchors.

## Steps to reproduce the behavior

* Create test.html page with the following content:
  ```html
  ---
  toc: true
  ---
  <table>
    <tr>
      <td>
        <h2>
          Test
        </h2>
      </td>
    </tr>
  </table>
  ```
* Serve
* The table of contents links will have null anchors

**Comment by mmistakes** [comment]
Couple of things I can clear up that might help.

1. `toc: true` method activates some Liquid logic using [jekyll-toc](https://github.com/allejo/jekyll-toc) that tries to parse out headings and build a TOC. It's by no means perfect and has a few gotchas. Looks like you're hitting one of them or maybe a bug.
2. Your test file above is a `.html` file... which Kramdown won't process. If you're looking for Kramdown to use its auto TOC feature it would need to be `.md` and the headings written in Markdown. You'd also need to manually include the Kramdown snippet to enable it... `{% include toc %}` in the body of your content.

I tried to look at your source but doesn't look like https://github.com/troylindsay/troylindsay.github.io/blob/master/_pages/test.md is valid anymore. If you can get a test repo up I can clone and test.

---

I would try a page with some headings and content, not in a table, and without `<a></a>` wrapped around them. **jekyll-toc** might be getting confused.

**Comment by mmistakes** [comment]
Did some testing of my own. Doesn't look like **jekyll-toc** doesn't work correctly HTML.

```html
<h2>Test</h2>
```

Produces blank anchors with `#`. While:

```markdown
## Test
```

Produces `#test` as expected. Using Kramdown with HTML doesn't seem to work either... heading is omitted from the TOC.

```html
{% include toc %}

<table>
  <tr>
    <td>
      <h2>
        Test
      </h2>
    </td>
  </tr>
</table>
```

**Comment by mmistakes** [comment]
OK I know what's going on. Headings need an `id` attribute so they can be linked to. When you write headings with Markdown Kramdown automatically generates these... (`## My Heading ~> id="my-heading"`).

Because you're writing HTML this doesn't happen. Therefore you need to manually add unique ID's to each of your headings. The following works for me:

```html
<table>
  <tr>
    <td>
      <h2 id="test">
        Test
      </h2>
    </td>
  </tr>
</table>
```

**Comment by tlindsay42** [comment]
Thanks much!
