### ISSUE TITLE
Adding/showing DISQUS comments

### ISSUE THREAD

**Issue by andresalerno** [mmistakes/minimal-mistakes#1669]
Hi!

I have some issues about adding DISQUS comments in the posts. Should I add the DISQUS' chunk code in the _layouts/archive.html. Below you can check my the code.

aspartners1.github.io/_layouts/archive.html

Tks,

**Comment by mmistakes** [comment]
You do not need to add the Disqus code snippet to layouts. Configure your site to use it in your _config.yml and enable on the posts you want with `comments: true`

Consult the documentation for more info.
https://mmistakes.github.io/minimal-mistakes/docs/configuration/#comments

**Comment by andresalerno** [comment]
Perfect! I have just done this and it worked! I can see the "Leave a message in the posts".

Now I have to discover how setting DISQUS up in the "development mode". If you have any hint (ex.: which folder), please let me know.

Tks for you help! As a newbie, your help save me a lot of time.

**Comment by mmistakes** [comment]
Not sure I follow what you mean by setting up Disqus in "development mode".
If you testing your site locally with `jekyll serve` they won't show unless you set `JEKYLL_ENV=production`.

This is covered in the documentation link I included above. You can also search throw the closed issues as I've answered similar questions before.
