### ISSUE TITLE
Changing font size

### ISSUE THREAD

**Issue by alkamid** [mmistakes/minimal-mistakes#167]
The default settings result in 80+ characters per line, which for me is a little too many. How to change the main text font? If I change `$doc-font-size` in `variables.scss`, it changes the relative sizes, e.g. changing it to 26 makes the headings very small. `1.2em` is more or less the size I'm looking for (the headings should stay the same).

**Comment by mmistakes** [comment]
Changing the `$doc-font-size` variable will likely screw with all of the typography as you've found. It's been awhile but I believe I didn't set a font size on paragraphs and instead let the browser use the default size (which is around 16px).

If you want to change paragraphs (or any other elements) you need to add some CSS to the `_page.scss` Sass partial. Something like this would increase the size of paragraphs... you'll likely need to bump up the line height too.

``` css
.article-wrap p {
  font-size: 16px; /* 16 is the default increase if you want it larger */
}

**Comment by alkamid** [comment]
Perfect! Thanks.

**Comment by lnalborczyk** [comment]
Hi, is there a simple way to reduce the overall font size, by keeping proportions all equals ?

**Comment by mmistakes** [comment]
@lnalborczyk Yes. See this issue's comment. https://github.com/mmistakes/minimal-mistakes/issues/1043#issuecomment-305472620
