### ISSUE TITLE
Recaptcha is not needed in staticman.yml?

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#1673]
## Description

https://github.com/mmistakes/minimal-mistakes/blob/master/staticman.yml#L97

Here you set reCaptcha but it seems it is not needed, and it is also on _config.yml? It should be removed from staticman.yml to avoid confusion.

## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- Operating system:
- GitHub Pages hosted (if yes provide URL to site):

---

**Comment by mmistakes** [comment]
It’s needed in both locations. Staticman needs it in [`staticman.yml`](https://staticman.net/docs/configuration) to configure it. And the theme needs it in`_config.yml` to [enable the recpatcha script in the front end](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments.html#L80-L92).
