### ISSUE TITLE
Problem setting up Google Analytics

### ISSUE THREAD

**Issue by Andy-ABTec** [mmistakes/minimal-mistakes#1674]
Hi, have recently launched a new release of our site using minimal-mistakes. All seems well, but I can't get Google Analytics working...

Site is: www.tvrename.com
GitHub repo is: https://github.com/TV-Rename/website

config.yml contains the following:

```
# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :UA-110543541-1
```

The tracking ID worked on a previous incarnation of the site (using the leap-day theme)

I can't for the life of me see what I've screwed up...

Any help much appreciated!

**Comment by mmistakes** [comment]
My guess is you haven't set [Jekyll's environment variable](http://jekyllrb.com/docs/configuration/#specifying-a-jekyll-environment-at-build-time) to production. By default it's set to development and the theme [only includes analytics tracking for production](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/analytics.html#L1)... much like comments.

You'll want to set it to `JEKYLL_ENV=production`

**Comment by Andy-ABTec** [comment]
Thanks for the quick reply...

As it happens, JEKYLL_ENV was already set to "production", I checked using {{ jekyll.environment }}  the issue was down to using "google-universal" rather than "google" viz:

```
# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-110543541-1
```

Thanks for your time anyway...

**Comment by pleonova** [comment]
@mmistakes  I tried the above fix and am unfortunately still not seeing any data in Google Analytics (GA). I am not sure if I need to edit any other files other than _config.  Any troubleshooting tips would be greatly appreciated.

What I have done so far:
I have entered my site: pleonova.github.io into the **Default Url** section in GA.  I then added the `tracking_id` into the _config file as well as changed the `provider` to "google-universal" from the default "false" and just tried "google", but unfortunately none have worked.

**Comment by mmistakes** [comment]
@pleonova Everything looks correctly configured and setup in the theme and with Jekyll. If you view any page's source on your site you'll see near the bottom the Google Analytics script is being injected.

```html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-124534051-1', 'auto');
  ga('set', 'anonymizeIp', false)
  ga('send', 'pageview');
</script>
```

Something must be mis-configured in Google Analytics. You'll have to dig into their support documentation as I'm not sure what could be the issue. It doesn't appear to be anything with the theme.

**Comment by pleonova** [comment]
@mmistakes thank you so much for taking a look, I really appreciate it! I'll dig more into GA to see if I can figure out if perhaps I mis-configured something there.

**Comment by HenryBernreuter** [comment]
Running into the same issue. Does anyone have a github repo that is using GA that  I could look at?

**Comment by mmistakes** [comment]
@HenryBernreuter have a look a theme’s doc site source. I’m using Google Analytics just fine there.

https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml#L99

**Comment by HenryBernreuter** [comment]
Thanks responding,
Its set exactly like yours. I am still not getting any hits.
Anything else I could look into?
best
Henry


[image: nohits.PNG]

**Comment by HenryBernreuter** [comment]
Here is the github link
https://github.com/HenryBernreuter/henrybernreuter.com

**Comment by mmistakes** [comment]
I don't think your problem is the theme. It's likely something in your Google Analytics account. Have you gone through all their steps to verify they can see the script and your `UA` id and all that?

**Comment by mmistakes** [comment]
Also I don't know how you're deploying your site, but you want to make sure you have Jekyll's production environment enabled, otherwise the Google Analytics tracking script won't be added to the HTML generated.

This is covered in the documentation for reference: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#analytics

> **Note:** Analytics are disabled by default in `development`. To enable when testing/building locally be sure to set `JEKYLL_ENV=production` to [force the environment](http://jekyllrb.com/docs/configuration/#specifying-a-jekyll-environment-at-build-time) to production.

**Comment by HenryBernreuter** [comment]
Thank you.

**Comment by gregoryalary** [comment]
A workaround might be to add the google analytics script into `_includes/head/custom.html`.

```html
<script async src="https://www.googletagmanager.com/gtag/js?id=XXX-YOURID-XXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'XXX-YOURID-XXX);
</script>
```

**Comment by HenryBernreuter** [comment]
I think I have it figured out, in what file do I add the google analytics
script so that it will post on every new page?

**Comment by sakshamg94** [comment]
@gregoryalary your solution worked wonders. @mmistakes  thanks for a great theme. Unfortunately, for me despite trying all solutions that are proposed here and on google searching, the analytics script (like here https://github.com/mmistakes/minimal-mistakes/issues/1674#issuecomment-415389656 )  would not show up in any of my source code.  I have no idea why!
