### ISSUE TITLE
Table of contents missing border between last parent header and all children

### ISSUE THREAD

**Issue by tlindsay42** [mmistakes/minimal-mistakes#1675]
## Description

The table of contents does not display the border between the last parent header (`<h2>`) cell and all subsequent children (`<h3>`).  This behavior occurs whether in standard or wide mode, for all skins tested, as well as for both pages & posts.

## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:

```powershell
Get-Content -Path .\Gemfile.lock | Select-String -Pattern '^\s{4}(?:jekyll(?:\s|-remote-theme)|minimal-mistakes-jekyll)'

    jekyll (3.7.3)
    jekyll-remote-theme (0.2.3)
    minimal-mistakes-jekyll (4.11.2)
```
- Git repository URL: https://github.com/troylindsay/troylindsay.github.io
- Operating system: Windows 10
- GitHub Pages hosted (if yes provide URL to site): https://www.troylindsay.io

---

## Expected behavior

The same border should be drawn between the last two cells as surrounds all of the other cells.

## Control 1

1. Create a page or post with a table of contents ([example](https://github.com/troylindsay/troylindsay.github.io/blob/master/_drafts/example-draft-post.md))
1. Enter a few test headers with the last header being a parent (`<h2>`)
1. Serve - the issue will not appear

![image](https://user-images.githubusercontent.com/11078689/40061870-890cdb5a-581f-11e8-9a2f-67cc3f8caa00.png)

## Control 2

1. Set `classes: 'wide'` in the front matter
1. The issue will not appear

![image](https://user-images.githubusercontent.com/11078689/40060709-dbd83fb2-581c-11e8-9819-9bb83f1a309b.png)

## Test 1

1. Change the last header to a child (`<h3>`)
1. The border will be missing between the last parent and its child header in the table of contents

![image](https://user-images.githubusercontent.com/11078689/40062158-30e6596e-5820-11e8-9fb5-d7c93fa5c0ac.png)

## Test 2

1. Comment out `classes: 'wide'` in the front matter

![image](https://user-images.githubusercontent.com/11078689/40062053-ea0870b8-581f-11e8-8600-3af4debf6d8b.png)

## Test 3

1. Add another child header (`<h3>`)

![image](https://user-images.githubusercontent.com/11078689/40062304-896cee04-5820-11e8-93b3-802b234c5851.png)

## Test 4

1. Re-enable `classes: 'wide'` in the front matter

![image](https://user-images.githubusercontent.com/11078689/40062682-64cd7cd4-5821-11e8-993b-e942aeeafe67.png)

**Comment by mmistakes** [comment]
Looks like [this CSS](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_navigation.scss#L531-L535) doesn't cover all possible combinations of nested list items.

I was using it to remove the last item's border so there wasn't a thicker one at the bottom, but I think it's safe to remove it all together. Then all list items correctly get a `border-bottom`.
