### ISSUE TITLE
Is MM compatible with gh-pages (github Projects)?

### ISSUE THREAD

**Issue by alkamid** [mmistakes/minimal-mistakes#168]
I am trying to set up a second blog on my [github.io page](https://github.com/alkamid/alkamid.github.io). I followed the instructions [here](http://jekyllrb.com/docs/github-pages/), i.e. I created a `gh-pages` branch and added `baseurl: /travel` to `_config.yml`. As far as I understand, this should result in my new blog being accessible at http://alkamid.com/travel, but it's not (I'm getting 404 — you can check it by opening the link). What might be the cause?

**Comment by mmistakes** [comment]
You'll need to modify some bits of the theme to use baseurl properly. Other than that the theme is GH pages compatible. I'm hosting the demo version of the theme there just fine.

**Comment by mmistakes** [comment]
Also your site is available just not in `/travel` as you expected. 

https://alkamid.github.io

**Comment by alkamid** [comment]
@mmistakes It's not available. You can tell by "Living in the Cambridge bubble" in the author box, instead of "Learning to undersdand" (see the [config file](https://github.com/alkamid/alkamid.github.io/blob/gh-pages/_config.yml) in gh-pages branch).

What bits would I have to modify to use baseurl? `permalinks` perhaps?

**Comment by mmistakes** [comment]
Not sure. Never used it with any projects. https://talk.jekyllrb.com/ is
the place for this sort of help. It might have to do with how your repo is
named. That plays a big part in how it's hosted. GH pages has different
ways of doing it and it's easy to screw up.

**Comment by mmistakes** [comment]
You might have to move the travel blog into its own repo. Might be getting confused with the master branch. For all my Jekyll themes they're hosted as projects in the gh-pages branch. Each in they're own repos v

**Comment by alkamid** [comment]
@mmistakes you're right, this setup was confusing Github indeed. I moved the travel blog into a new repo, added `baseurl` (but I'm only currently using it for language selector buttons because my blog is bilingual), deleted `CNAME`, and it seems to work.
For anyone who's asking in the future:
http://stackoverflow.com/questions/31906986/two-jekyll-blogs-on-the-same-github-page
http://stackoverflow.com/questions/31914048/how-to-set-up-two-jekyll-blogs-on-github-pages-with-the-same-domain-cname

**Comment by mmistakes** [comment]
Glad you got it sorted.
