### ISSUE TITLE
Replace Magnific Popup with Photoswipe (same author, better touch handling)

### ISSUE THREAD

**Issue by PeterDeKeer** [mmistakes/minimal-mistakes#1680]
I would be interested to work together on this issue, if you think it's a good way to go for this project.
It's also, not requiring jquery (FYI)

On the website of Maginific Popup the author claims:
> If you wish to add touch-swipe support, check my article on the Smashing Magazine, or new PhotoSwipe script.

**Comment by mmistakes** [comment]
Sure, if you want to submit a PR with PhotoSwipe as a drop-in replacement for Magnific Popup I'd be happy to look it over.

The version of MP the theme ships with is outdated too, so it would be nice to move to something lighter and with better touch support.
