### ISSUE TITLE
Add support for meta theme color

### ISSUE THREAD

**Issue by Pradhyo** [mmistakes/minimal-mistakes#1683]
## Description

Add support for [meta theme color](https://developers.google.com/web/fundamentals/design-and-ux/browser-customization/#meta_theme_color_for_chrome_and_opera)

I am able to achieve this using `_includes/head/custom.html` but just checking if it's a good idea to make this a part of the config since there are skins now. Happy to submit a PR.

**Comment by Pradhyo** [comment]
Should I add a variable in _config.yml and use it in _includes/head.html?

```yml
minimal_mistakes_skin    : "default"
minimal_mistakes_theme_color: "#252a34"
```

I wanted to set the color value below to the background-color value from the skin sass files but I am not sure how to do that if it's even possible.

```html
<meta name="theme-color" content="#252a34">
```

**Comment by mmistakes** [comment]
That's not possible. You can't pull out variables set in a Sass file into HTML.
