### ISSUE TITLE
About Contrast skin

### ISSUE THREAD

**Issue by cortix** [mmistakes/minimal-mistakes#1688]
Hi,

I want to adjust the contrast in different "skins". What should I do?
Thanks in advance.

Best Regards.

## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- Operating system:
- GitHub Pages hosted (if yes provide URL to site):

---

**Comment by mmistakes** [comment]
Consult the documentation on how to customize the stylesheet.

https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/

**Comment by cortix** [comment]
Thanks.

**Comment by WizKidd42** [comment]
Support
