### ISSUE TITLE
Is there a way to keep the author sidebar in the mobile version?

### ISSUE THREAD

**Issue by harshnisar** [mmistakes/minimal-mistakes#169]
I have modified a website in a hacky way such that there is another menubar in the author sidebar. 
But now it disappears in mobile.
Is there a way to just stack it on the top in the mobile view?

**Comment by mmistakes** [comment]
Anything is possible if you know enough CSS to pull it off.

**Comment by qgustavor** [comment]
If you want just to stack it on the top I think you can just remove the `display: none` from `.article-author-side` and fix the grid on it (use other elements as a example).
