### ISSUE TITLE
How to change lines for author bio 

### ISSUE THREAD

**Issue by rachel-sunrui** [mmistakes/minimal-mistakes#1695]
Hi, 

Thank you for this great theme! I am writing to ask how to change line in the author bio part. Instead of a sentence spanning the whole left side bar, I want to use a few words on different rows in the author bio part. I would appreciate your help.

Thank you.

**Comment by mmistakes** [comment]
The author bio simply spits out whatever string you give it inside of a paragraph tag `<p></p>`:

```html
{% if author.bio %}
  <p class="author__bio" itemprop="description">
    {{ author.bio }}
  </p>
{% endif %}
```

You could try adding line breaks to the your bio to achieve what you want. For example:

```yaml
author:
  bio: "I am an amazing person...<br>sometimes<br>.<br>.<br>or not?"
```

Would give you something like this:

![image](https://user-images.githubusercontent.com/1376749/40801795-cf75b70a-64e1-11e8-995c-838d1ddef71b.png)
