### ISSUE TITLE
TOC sticky not present

### ISSUE THREAD

**Issue by adibis** [mmistakes/minimal-mistakes#1703]
I see that the docs mention toc_sticky: true as a valid option but as per this file - I don't see that being picked up. Are the docs wrong or is it missing from the code?

https://github.com/mmistakes/minimal-mistakes/blob/9dd3a3a49ab9dbcc5f140b254dea82978c767864/_includes/toc#L1

**Comment by mmistakes** [comment]
Doesn't work for Kramdown generated toc. That's why you don't see the code in this include.

Sticky sidebars are only supported when using `toc: true` generated ones.

https://mmistakes.github.io/minimal-mistakes/docs/helpers/#table-of-contents

**Comment by adibis** [comment]
So, if I add to:true and toc_sticky: true, I still don't get a sticky toc.

**Comment by mmistakes** [comment]
Are you sure you're using the latest version of the theme on `master`? The demo site has a sample post with a sticky TOC and it is working as intended.

Ref: https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L38

- [Sample post](https://mmistakes.github.io/minimal-mistakes/layout-table-of-contents-sticky/)
- [Source](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_posts/2012-01-03-layout-table-of-contents-sticky.md)

**Comment by adibis** [comment]
Well - that is the issue. Seems like this is not part of the latest gem version (4.11.2). I will pull the master and use that. Thanks for looking into it.
