### ISSUE TITLE
Help: Ordering posts by some weight parameter

### ISSUE THREAD

**Issue by satwikkansal** [mmistakes/minimal-mistakes#1712]
Hi, first of all thank you so much for maintaining such a lovely template.

I wanted to to custom sort posts in my blog post,planning to add something like `weight` parameter to the meta:
```
date: 2018-06-22 12:51:36 +05:30
weight: 100
```

and then being able to sort all the displayed posts by `weight` instead of `date` (the default behavior). 

It'd be very kind of you, if you can help me by letting me know what changes would I have to make to achieve this. Thanks in advance!

**Comment by mmistakes** [comment]
The way you'll go about doing this depends on where you want to sort the posts.

There are several layouts that display posts (e.g. posts by tag, [posts by category](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/categories.html), [posts by year](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/posts.html), [recent posts](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/home.html) on homepage, etc.). You'd have to modify the one you want.

**Comment by hkalant** [comment]
When you set up a collection, say `_docs`, you can determine the order using numbers in the filename, eg `01-quick-start-guide.md`, like @mmistakes has done here:

https://github.com/mmistakes/minimal-mistakes/tree/master/docs/_docs

Wouldn't that work with `_posts` as well?

Of course if you follow that approach, you will have to define the permalink in the frontmatter, otherwise the number in the filename will be displayed in the URL for that post.

**Comment by mmistakes** [comment]
Also, you'll probably need to use the `sort` filter as suggested by this post on SO.

https://stackoverflow.com/a/30274671

**Comment by satwikkansal** [comment]
I'm using the [recent posts](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/home.html) layout.

I modified a couple of lines in the template to
```
{% assign posts = paginator.posts | sort:"weight" %}

{% for post in posts %}
  	{% include archive-single.html %}
{% endfor %}
```
It works, but the problem that I'm now facing it sorts the posts by `weight` just for that page. For example, if there's some other post on page 2 having the lowest `weight` of all, it'd be on the top of page 2 but not on page top of page 1.

Is there a way to fix this behavior? I tried looking for where `paginator` is populated in the code but couldn't find, I guess it's returned by some plugin...

**Comment by mmistakes** [comment]
Might be a limitation of Jekyll's pagination plugin that doesn't honor `sort`. You could submit and issue on their repo but not sure if that will get you anywhere as they deprecated the plugin a long time ago.

https://github.com/jekyll/jekyll-paginate

**Comment by satwikkansal** [comment]
Okay, I'll create an issue there. Thanks for the help :)
