### ISSUE TITLE
Use GitHub Issues for Blog Comments

### ISSUE THREAD

**Issue by toolowner** [mmistakes/minimal-mistakes#1719]
I want to use GitHub issues to store comments. I know it has some limitation, such as
- users must have a Github account to comment
- GitHub API rate limits
- manually linking blog posts to issues
- forcing users to leave the blog to post a comment

but I still prefer it over Disqus, Facebook, Google.

**Comment by mmistakes** [comment]
Not likely to add support for this for all of the reasons you've stated, but that shouldn't stop you from doing it in your repo.

The theme has support for "custom comments". You'd set the following in your _config.yml file:

```yaml
comments:
  provider: custom
```

And then you'd need to edit this [`_includes/comments.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments.html#L169) and [`_includes/comments-providers/custom.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments-providers/custom.html) to suit your needs.

**Comment by nadaa** [comment]
I tried to add "custom" and  "staticman_v2", but the boxes didn't appear!. What shall I do?

**Comment by mmistakes** [comment]
@nadaa Verify you're building Jekyll in `production` mode as described in the documentation.

> **Note:** Comments are disabled by default in `development`. To enable when testing/building locally be sure to set [`JEKYLL_ENV=production`](http://jekyllrb.com/docs/configuration/#specifying-a-jekyll-environment-at-build-time) to force the environment to production.

And that you have [`comments: true`](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#comments) added to the post's front matter along with all the required [Staticman configs](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#configure-staticman) in `_config.yml`. If you're missing something they won't show as a few variables are required.

**Comment by nadaa** [comment]
I tried what you suggested, but it is not working?

**Comment by mmistakes** [comment]
@nadaa Looks like you didn't add anything for `repository`... it's required for Staticman to work.

**Comment by nadaa** [comment]
@mmistakes, it works now, thank you :+1:  I got another issue when submitting the comment, where else I need to update?

**Comment by mmistakes** [comment]
@nadaa Please open another issue specific to your Staticman problem as it's off topic. This issue is about using GitHub issues as a way to add comments to a Jekyll site.

Thank you.
