### ISSUE TITLE
instead of time read, how can we show date on blog page

### ISSUE THREAD

**Issue by UsmanMaqbool** [mmistakes/minimal-mistakes#1730]
## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- Operating system:
- GitHub Pages hosted (if yes provide URL to site):

---

**Comment by mmistakes** [comment]
Date is already shown on the post's that use `layout: single` near the bottom of the page.

![screen shot 2018-07-05 at 4 14 10 pm](https://user-images.githubusercontent.com/1376749/42345790-806820aa-806e-11e8-8abe-5a2fe772e893.png)

If you want to add it in place of the read time you'll need to hack the theme files [around these lines](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L28-L33).

**Comment by natanrolnik** [comment]
I just did it myself, and here is what I changed in [line 31 here](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L31).

`<p class="page__meta"> {{ page.date | date: "%B %d, %Y" }} <i class="far fa-clock" aria-hidden="true"></i> {% include read-time.html %}</p>`

Also, if you want the date to be shown in the list of posts, you should change [this line here](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/archive-single.html#L34) to:

`<p class="page__meta">{{ post.date | date: "%B %d, %Y" }}<i class="far fa-clock" aria-hidden="true"></i> {% include read-time.html %}</p>`.

@mmistakes would you accept a PR enabling showing the published date in _config.yml?

**Comment by mmistakes** [comment]
@natanrolnik I think this is something that can be overrided as you have versus a config flag. I intentionally left the dates off of that view to avoid the extra clutter.

**Comment by UsmanMaqbool** [comment]
![image](https://user-images.githubusercontent.com/23024825/42822366-7614940a-8a0d-11e8-8948-940d91ec2d35.png)
Actually, I need published time in the main page under the title, instead of reading time. 
usmanmaqbool.github.io
