### ISSUE TITLE
Include "Back to top" Icon

### ISSUE THREAD

**Issue by lthurner** [mmistakes/minimal-mistakes#1731]
Hi,

first of all thanks for this great template, it is much appreciated! One feature I found missing when creating a homepage with minimal-mistakes was a back to the top icon that is always in the right lower corner and can be used to scroll back to the top at any time. I implemented this for my homepage by creating a simple new class in [_sidebar.scss](https://github.com/e2nIEE/e2niee.github.io/blob/0ba2066f3755cfa111afb3f2a45a7c6d0b41fefc/_sass/minimal-mistakes/_sidebar.scss#L66-L71) with fixed position:

```
.sidebar__top {
  position: fixed;
  bottom: 1.5em;
  right: 2em;
  z-index: 10;
}
```

And included it in [default.html](https://github.com/e2nIEE/e2niee.github.io/blob/0ba2066f3755cfa111afb3f2a45a7c6d0b41fefc/_layouts/default.html#L31-L33) with an awesome font icon and a link to #site-nav:

```
<aside class="sidebar__top">
<a href="#site-nav"> <i class="fas fa-angle-double-up fa-2x"></i></a>
</aside>
```

I linked to #site-nav so that clicking the icon scrolls all the way to the top of the page and not only to the first header. A working example can be seen here: www.pandapower.org

Is this something that would be interesting to include in the template as an option? I am fairly new to website design in general and the template specifically, so I don't know if and how this would possibly interfere with other features. But I would be willing to try to clean up the solution and put in a pull request if you think this would be a good idea to have in the template. 

Cheers
Leon

**Comment by mmistakes** [comment]
How you've customized the theme to add this feature looks fine to me.
Not sure if I'm interested in adding the feature though. I'll leave it marked as under consideration and see if there's any interest in it.

**Comment by theclue** [comment]
+1 to me :)

I've added this nice tweak to my installation as well :)

**Comment by lthurner** [comment]
One thing I am still struggling with: the back-to-the top icon in the current implementation disappears behind the footer:

![grafik](https://user-images.githubusercontent.com/23637821/44392546-bf3a0a80-a532-11e8-8abf-7df32b83f4e2.png)

Setting the z-index to a higher number does not seem to make a difference. @mmistakes: can you give me a hint how I could bring the icon above the footer?

**Comment by mmistakes** [comment]
@lthurner Change it's source order. Put it after `<div class="page__footer">` and it'll appear above it.

![image](https://user-images.githubusercontent.com/1376749/44400026-b5ef7480-a517-11e8-87e0-b22b326e9dbd.png)

![image](https://user-images.githubusercontent.com/1376749/44400043-c3a4fa00-a517-11e8-85b6-227f8c3ffc85.png)

**Comment by lthurner** [comment]
Thanks a lot, works like a charm! I have updated the description above accordingly.

**Comment by Kulbhushan-Chand** [comment]
+1 this will be a nice feature in the theme, and also required since lenghthy posts when viewed on mobile have toc on the top (toc are not sticky on mobile). Users have to scroll all the way to top to acess toc.

**Comment by bjwo** [comment]
Already stale? I like this feature and enhanced it in my implementaitons as well. :)

**Comment by stefanbschneider** [comment]
Nice feature! Does this also work when using the remote theme? So far, I couldn't get it to work.

I've added the [default.html](https://github.com/e2nIEE/pandapower-homepage/blob/0ba2066f3755cfa111afb3f2a45a7c6d0b41fefc/_layouts/default.html#L31-L33) under `_layouts` and added a `_sidebar.scss` under `_sass/minimal-mistakes`. In the `_sidebar.scss`, I only have the following code:

```
.sidebar__top {
  position: fixed;
  bottom: 1.5em;
  right: 2em;
  z-index: 10;
}
```

Any idea what the problem could be? Do I also need to copy and paste the remaining code in `_sidebar.scss`? Or do I need to copy and override any other files (eg, in `_sass`)? Not sure, how to debug this.

**Comment by stefanbschneider** [comment]
In fact, the "to top button" is there! But it's just at the very bottom of the website. So to go to the top, I'd have to scroll to the very bottom first? Not very convenient.

How could I adjust the button to float and stay at the top left corner while scrolling? So not at a fixed position on the website, but instead fixed at the top left corner of the screen?

**Comment by stefanbschneider** [comment]
@lthurner Did you have the same problem that the button was at the top left corner of the page (absolute) and not in the corner of the window the user sees? In your linked website, it looks good. Any ideas what the problem could be in my case with the remote theme?

**Comment by lthurner** [comment]
@stefanbschneider sorry just saw this now - I never had the problem that you describe. I can have a look at it, but I am in no means a CSS expert, so not sure if I can help. Can you link me to your code though? I wasn't able to find your github pages repo quickly

**Comment by stefanbschneider** [comment]
@lthurner Sorry, it's a private repo. But it uses the remote theme. I only added the `default.html` in a `_layouts` folder. It looks like this:

```html
<!DOCTYPE html>
<!--
  Minimal Mistakes Jekyll Theme 4.19.1 by Michael Rose
  Copyright 2013-2019 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE
-->
<html lang="{{ site.locale | slice: 0,2 | default: "en" }}" class="no-js">
  <head>
    {% include head.html %}
    {% include head/custom.html %}
  </head>

  <body class="layout--{{ page.layout | default: layout.layout }}{% if page.classes or layout.classes %}{{ page.classes | default: layout.classes | join: ' ' | prepend: ' ' }}{% endif %}">
    {% include_cached skip-links.html %}
    {% include_cached browser-upgrade.html %}
    {% include_cached masthead.html %}

    <div class="initial-content">
      {{ content }}
    </div>

    {% if site.search == true %}
      <div class="search-content">
        {% include_cached search/search_form.html %}
      </div>
    {% endif %}
    <aside class="sidebar__top">
        <a href="#site-nav"> <i class="fas fa-angle-double-up fa-2x"></i></a>
    </aside>

    <div id="footer" class="page__footer">
      <footer>
        {% include footer/custom.html %}
        {% include_cached footer.html %}
      </footer>
    </div>

    {% include scripts.html %}

  </body>
</html>
```

Does this help? What other info would you need? If necessary, I can try to reproduce the problem on a smaller example page.

Thanks for the help!

**Comment by lthurner** [comment]
Defining the position in cm might not be a good idea, have your tried em or px instead? Otherwise it looks correct to me. 

Have your checked if your _sass folder looks similar to mine: https://github.com/e2nIEE/pandapower-homepage/tree/master/_sass. I think it was necessary to include the minimal-mistakes.scss file as well, although I don't remember exactly why...

**Comment by stefanbschneider** [comment]
Thanks a lot! Adding the `minimal-mistakes.scss` file into my `_sass` folder solved the problem! cm worked fine, but I do prefer em now - thanks for the tip. :)

**Comment by quannetwork** [comment]
I've just found this well-maintained library, https://github.com/vfeskov/vanilla-back-to-top

You just need to include its script, don't have to include any CSS:

```
<script src="https://unpkg.com/vanilla-back-to-top@7.2.1/dist/vanilla-back-to-top.min.js"></script>
<script>addBackToTop({
  diameter: 56,
  backgroundColor: 'rgb(255, 82, 82)',
  textColor: '#fff'
})</script>
```
