### ISSUE TITLE
How to add a subtitle?

### ISSUE THREAD

**Issue by szgaljic** [mmistakes/minimal-mistakes#1733]
## Description
Is it possible to add a sub-title to my pages? I hacked this by adding a <small> block at the top of my markdown pages but there is still an odd looking gap between the title and the subtitle.

```
---
title:  "Very cool page"
permalink: /cool
---

<small>You're going to love this.</small>

## First Section
Text.

## Second Section
Text.
```

## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- Operating system:
- GitHub Pages hosted (if yes provide URL to site):

---

**Comment by mmistakes** [comment]
You'll probably need to hack the theme if you want to do this. You could add front matter to your posts like:

```yaml
---
title: "Very cool page"
subtitle: "You're going to love this."
permalink: /cool
---
```

And then add it to whatever layout you're using with:

```liquid
{% if page.subtitle %}{{ page.subtitle }}{% endif %}
```

A good place for that would be right after the [page's title](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L29) with whatever styling you'd need.

**Comment by szgaljic** [comment]
Okay thanks!

**Comment by amirkdv** [comment]
For anyone else ending up here: you don't need to hack the theme. You can just populate the `page__meta.html` template which is included by the  theme, see [code](https://github.com/mmistakes/minimal-mistakes/blob/9269842e9dceed85021d657bdc80fb0ddbb26b3c/_layouts/single.html#L32).

Example:

```jinja
<!-- _includes/page__meta.html -->

{% if page.subtitle %}
    <p id="page-subtitle" class="page__subtitle p-name" itemprop="headline">
    {{ page.subtitle }}
    </p>
{% endif %}

```
