### ISSUE TITLE
Changes required for new version of Susy

### ISSUE THREAD

**Issue by desilinguist** [mmistakes/minimal-mistakes#1734]
## Description
Understanding how to work with the new version of Susy

## Environment

- Minimal Mistakes version: 4.8.0
- Jekyll version: 3.7.0
- Git repository URL: https://github.com/emnlp2018/emnlp2018.github.io
- Operating system: macOS
- GitHub Pages hosted (if yes provide URL to site): http://emnlp2018.org

---

I had figured out how to use Susy for a custom layout -- thanks to your help -- with a previous version of the theme back in early 2017. However, it seems that Susy has changed significantly and my old CSS setup doesn't work. For example, I had the following in `_variables.scss` under the Grid section: 

```css
$susy: (
  columns: 20,
  gutters: 1/4,
  math: fluid,
  output: float,
  gutter-position: after,
  container: $large,
  global-box-sizing: border-box,
);
```

However,  if I change this to the new:

```css
$susy: (
  'columns': susy-repeat(20),
  'gutters': 0.25,
  'spread': 'narrow',
  'container-spread': 'narrow',
);
```

in the same location, I get the following error:

```
Error: [su-valid-span] [string] `susy-repeat(20)` is not a valid number, length, or column-list for $span. on line 43
```

This confuses me as this is the syntax that the Susy3 documentation recommends.

**Comment by mmistakes** [comment]
Not sure. Have you reached out to the Susy maintainers as they would know better than me.

I haven't worked with Susy much recently. The new version from what I remember is less about mixins and "magic" and more about math.

Looking at the error message it's pretty clear... it's expecting a `number` and you're giving it a `string`.

**Comment by desilinguist** [comment]
But the documentation clearly states that a plain number is not what’s
expected there.

I might just hardcode the measurements in the compiled CSS from the old
version of the code in this version, if I can’t figure it out.

**Comment by mmistakes** [comment]
Again, probably a better idea to file an issue on Susy's repo. The maintainers there would know more than me as they built it.

**Comment by desilinguist** [comment]
Will try that. Thanks!

**Comment by desilinguist** [comment]
I figured out that I can just use `percentage()` for my grid layout directly without needing to use Susy at all.
