### ISSUE TITLE
Is it possible to have separate categories/tags for each collection?

### ISSUE THREAD

**Issue by wAuner** [mmistakes/minimal-mistakes#1743]
## Description

I have a collection with projects and one with notes. I'd like use categories and tags which are separate from each other, meaning category x in projects leads to the category overview in projects and category x in notes to notes.
I tried to get it to work, but failed. Is that even possible? When I click on a category in notes section, it still links to the category overview of the project collection.

What I tried:
- add note_category_archive.html
- add note_category_list.html
- add note_archive (type liquid) in _config.yml
- add entry page_taxonomy.html
 Did I miss something?

Thanks!

**Comment by mmistakes** [comment]
Nope not possible. This is a Jekyll thing which the theme has no control over. tags and categories are part of the the entire `site` object.

**Comment by wAuner** [comment]
Thanks, that's good to know. Then I'll have to rethink my approach.
