### ISSUE TITLE
Configuration documentation missing Google Plus Comments details


### ISSUE THREAD

**Issue by ciferkey** [mmistakes/minimal-mistakes#1745]
The configuration documentation provides details about about setting up comment providers.

It starts with a list of comment providers and then has a section for each that details it's configuration information. 

Google Plus is listed as one of the providers but there is not details section for it.

**Comment by mmistakes** [comment]
That's because there is no configuration for Google Plus comments. You either enable it or not. Unlike the other options there are no configs needed.

`provider: google-plus`

**Comment by ciferkey** [comment]
Ok! Thank you for the clarification. Would you like me to close the issue?
