### ISSUE TITLE
Cannot use skins in gem version of minimal-mistakes

### ISSUE THREAD

**Issue by natanrolnik** [mmistakes/minimal-mistakes#1749]
## Description

When using minimal-mistakes via bundler (adding it to the Gemfile), changing the `minimal_mistakes_skin` variable in `_config.yml` makes no difference.
I also noticed that, in the gem folder downloaded by bundler, the `skins` directory is not available within `_sass`.

I tried copying the files, importing, and other hacky solutions, but the end result wasn't exactly like the images show in the docs.

## Environment

- Minimal Mistakes version: 4.12.0
- Ruby gem or remote theme version: Gem
- Jekyll version: 3.8.3
- Git repository URL: https://github.com/natanrolnik/blog
- Operating system: macOS 10.13.
- GitHub Pages hosted (if yes provide URL to site): no, but using netlify to deploy at blog.natanrolnik.me

## Expected behavior
Setting any skin changes the website look

## Steps to reproduce the behavior

* Clone the repo indicated, `cd` to the directory
* run `bundle install && bundle exec jekyll serve`
* open the website at localhost:4000
* see that changing skins won't affect the look of the website

**Comment by mmistakes** [comment]
I think you're using an older version of the theme. Looking at your [`Gemfile.lock` it says 4.2.1](https://github.com/natanrolnik/blog/blob/master/Gemfile.lock#L66) which is quite old.

That's likely the version Netlify is installing and since it's pre-skins that's why you don't see it.

You'll need to run `bundle update` locally to update, then commit the update `Gemfile.lock` and push that up.

**Comment by mmistakes** [comment]
Also looking at [blog.natanrolnik.me](https://blog.natanrolnik.me)'s source there is no theme version in there. Which tells me you're using a much older version.

`bundle update` will likely be all you need to do. Refer to the [upgrade docs](https://mmistakes.github.io/minimal-mistakes/docs/upgrading/) if you need more info.

**Comment by natanrolnik** [comment]
Oh 🤦‍♂️ 
I have no idea why I didn't specify the version in the Gemfile... 
@mmistakes thanks for looking into it, I really appreciate your time! And huge kudos for writing and mantaining such a good project!
