### ISSUE TITLE
"Article-author-side" does not span full page.

### ISSUE THREAD

**Issue by kjanjua26** [mmistakes/minimal-mistakes#1755]
Whenever I add a new page and add information to it which if exceeds a certain length, the Article-author-side class does not span full length and does not wrap the text, thus the added information goes below the Article-author-side class. I do not know how to resolve this issue.

Screenshot: 

<img width="1236" alt="screen shot 2018-07-22 at 3 23 15 am" src="https://user-images.githubusercontent.com/14023660/43041372-a4fe912c-8d5e-11e8-96d6-7fe6284caa98.png">

How do I resolve the list error??
The code is: https://gist.github.com/kjanjua26/8ff56d4eeebfee076eeb473b19ef85fa

Thanks.

**Comment by mmistakes** [comment]
Upgrade. 

The version of the theme you're using is a few years old. The latest version doesn't have this issue.

**Comment by kjanjua26** [comment]
Hey, 
It would be really hectic to change everything now. Do you think there is any workaround?

**Comment by kjanjua26** [comment]
This doesn't happen with the home or blog posts page, or even page similar to blog posts (the structure). It happens in other cases. Any workaround?

**Comment by mmistakes** [comment]
The workaround is to upgrade. Like I mentioned, I fixed these issues when I rebuilt the theme.

Only other option if you don't want to upgrade is sift through the CSS of they last version and see if you can backport anything.

**Comment by kjanjua26** [comment]
@mmistakes I found the solution. 
So apparently, you have to add this bit to your article-author-side's CSS or add this to your page head tag. 

```
  <link rel="stylesheet" type="text/css" href="mystyle.css">
  <style>
    .article-author-side{
          height: 100vh;
    }
  </style>
```

Thanks.
