### ISSUE TITLE
How to change the TOC case

### ISSUE THREAD

**Issue by copdips** [mmistakes/minimal-mistakes#1760]
Hello,

The default TOC sets all the characters to the uppercase.
Is it possible to change it to the origin case the same in the source code.
Thx.

**Comment by mmistakes** [comment]
https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_navigation.scss#L494

**Comment by copdips** [comment]
@mmistakes 

thx a lot, works like a charm. 

For those who face the same issue, hereunder the possible `text-transform` values:

- capitalize
- inherit
- initial
- lowercase
- none
- unset
- uppercase
