### ISSUE TITLE
Favicon in tab

### ISSUE THREAD

**Issue by Alwurts** [mmistakes/minimal-mistakes#1761]
Hi, im wondering if the theme supports adding a favicon to a tab so my website could have something like this where the GitHub logo is currently displayed.

![screen shot 2018-07-27 at 5 11 47 pm](https://user-images.githubusercontent.com/32560488/43312522-2cb01e82-91c0-11e8-9969-0fcfbc1c58f4.png)

Thank you in advance.

**Comment by mmistakes** [comment]
Duplicate of #949.
See that issue for a path forward.
