### ISSUE TITLE
Include ResearchGate and Medium on config.yml

### ISSUE THREAD

**Issue by vncoelho** [mmistakes/minimal-mistakes#1765]
## Description

Please include ResearchGate and Medium on config.yml

## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- Operating system:
- GitHub Pages hosted (if yes provide URL to site):

---

**Comment by mmistakes** [comment]
Closing as this is a duplicate of several other issues like #1676 

Additional sidebar links can be added using [`/includes/author-profile-custom-links.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/author-profile-custom-links.html) or creating your own layout overrides as [per the docs](https://jekyllrb.com/docs/themes/#overriding-theme-defaults).
