### ISSUE TITLE
Smooth scroll breaks back button

### ISSUE THREAD

**Issue by danieljl** [mmistakes/minimal-mistakes#1767]
### Current Behavior

Smooth scroll is triggered when a link to a different section on the same page is clicked, e.g. when clicking a table of contents. After clicking a section on a table of contents, users often want to go back to the table of contents. However, users cannot do that because the URL is not appended with the hash (section ID). This can be demonstrated at https://kswedberg.github.io/jquery-smooth-scroll/demo/.

### Proposed Solution:

1. Disable smooth scroll; or
2. Enable hashchange feature of jQuery smooth scroll. There are two ways to do that:
    a. Using native hashchange DOM event: [demo](https://kswedberg.github.io/jquery-smooth-scroll/demo/hashchange.html), [source code](https://github.com/kswedberg/jquery-smooth-scroll/blob/master/demo/hashchange.html).
    b. Not using native hashchange DOM event: [demo](https://kswedberg.github.io/jquery-smooth-scroll/demo/bbq.html), [source code](https://github.com/kswedberg/jquery-smooth-scroll/blob/master/demo/bbq.html).

**Comment by mmistakes** [comment]
2a looks fine to me if you want to go ahead and submit a pull request.
I tested it locally and all you'd need to do is:

1. Replace [this line](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/_main.js#L65) in `assets/js/_main.js` with:

```javascript
// Bind the hashchange event listener
  $(window).bind("hashchange", function(event) {
    $.smoothScroll({
      // Replace '#/' with '#' to go to the correct target
      scrollTarget: location.hash.replace(/^\#\/?/, "#"),
      offset: -20
    });
  });
  $('a[href*="#"]').bind("click", function(event) {
    // Remove '#' from the hash.
    var hash = this.hash.replace(/^#/, "");
    if (this.pathname === location.pathname && hash) {
      event.preventDefault();
      // Change '#' (removed above) to '#/' so it doesn't jump without the smooth scrolling
      location.hash = "#/" + hash;
    }
  });
  // Trigger hashchange event on page load if there is a hash in the URL.
  if (location.hash) {
    $(window).trigger("hashchange");
  }
```

2. Rebuild `assets/js/main.js` by running `npm run build:js` from root
3. Commit the changed `_main.js` and `main.js` files and push up.

**Comment by danieljl** [comment]
Hi @mmistakes, I just created a PR for this. I'm also thinking to create a feature knob for smooth scroll so it can be disabled. Could you guide me on how to do it? Thanks.

**Comment by mmistakes** [comment]
Don’t think that can be done easily without over complicating the theme.
Since the JS is precompiled in the theme there is no way to hook a `site` variable in there to do some sort of Liquid logic to not include the smooth scrolling stuff.

I guess it could be pulled out into its own script file and then conditionally loaded via some config flag, but that seems unnecessarily complicated.
