### ISSUE TITLE
This is not working on gitlab.

### ISSUE THREAD

**Issue by ritayadav** [mmistakes/minimal-mistakes#1768]
## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- Operating system:
- GitHub Pages hosted (if yes provide URL to site):

---

**Comment by ohadschn** [comment]
I haven't updated it in a long time, but my blog is on gitlab with this theme: https://gitlab.com/ohadschn/ohadschn.gitlab.io

**Comment by ritayadav** [comment]
I have tried to publish 4.6.0 on gitlab as gitlab pages but not publish, it's faild.

**Comment by ohadschn** [comment]
You should probably post your gitlab project URL and paste the exact error here to get further help...
