### ISSUE TITLE
Center author avatar?

### ISSUE THREAD

**Issue by davidlcassidy** [mmistakes/minimal-mistakes#1771]
## Description

What is the best way to center (horizontally) that author avatar within the sidebar? I've have tried several things, but non of them seem to work.

## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL: https://github.com/davidlcassidy/davidlcassidy.github.io
- Operating system:
- GitHub Pages hosted (if yes provide URL to site): https://davidlcassidy.github.io

## Expected behavior

Author avatar is centered within sidebar.

**Comment by mmistakes** [comment]
With CSS. You'll have to add something like `margin: auto` and `display: block` to `.author__avatar img` in [_sass/minimal-mistakes/_sidebar.scss](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_sidebar.scss#L125-L128).

```css
.author__avatar img {
    margin: auto;
    display: block;
}
```

**Comment by davidlcassidy** [comment]
Ah I had it outside img. That works. Thanks!
