### ISSUE TITLE
Links to menu items are written as absolute links

### ISSUE THREAD

**Issue by olbat** [mmistakes/minimal-mistakes#1783]
## Description
The #1588 PR was supposed to:
> Replace absolute_url filter with relative_url where it makes sense (asset/navigation related paths).

Is there any reasons to keep [links to menu items](https://github.com/mmistakes/minimal-mistakes/blob/c8226a32a675fc59e4e713bb3384a1e64fb698e9/_includes/masthead.html#L14) as absolute links ?

## Environment
- Minimal Mistakes version: 4.12.1

## Expected behavior
Links to menu items to be written as relative links as well ?
(works better with "reverse-proxified" websites)

**Comment by mmistakes** [comment]
It could absolutely be updated.

I use something like the following in my other theme's which cuts down on some of the Liquid spaghetti code currently in MM.

```liquid
{%- for link in site.data.navigation.main -%}
  {%- if link.url contains '://' -%}
    {%- assign url = link.url -%}
  {%- else -%}
    {%- assign url = link.url | relative_url -%}
  {%- endif -%}
  <li><!-- anchor stuff --></li>
{%- endfor -%}
```

Happy to look at a pull request if anyone wants to take a stab at cleaning up`_includes/masthead.html`.

**Comment by olbat** [comment]
Nice!

Thank you for your code snippet 👍 
I've opened a PR using it, please let me know if there is anything wrong ...

**Comment by ptsiampas** [comment]
I was a little more brutal than that by removing the {{domain}} from line 14, it was driving me mental for hours. :)
Glad you have fixed it with the snippet.
