### ISSUE TITLE
Could we replace  the left vertical scroll bar with just a vertical line？

### ISSUE THREAD

**Issue by jcyrss** [mmistakes/minimal-mistakes#1788]
Thanks for this greate template.

But some of the readers think the left vertical scroll bar looks a little ugly.

![image](https://user-images.githubusercontent.com/10496014/44094952-1f5518d4-a00a-11e8-9317-aeeaa841f024.png)

<br><br>
Could we replace that with just a vertical line, like the following 

<br><br>

![image](https://user-images.githubusercontent.com/10496014/44095729-1b4cdd10-a00c-11e8-8f2a-d8eabd5c34b6.png)

**Comment by mmistakes** [comment]
Every browser renders scrollbars differently, I'd prefer not to customize them.
In fact on touch devices you don't even see a scrollbar.
