### ISSUE TITLE
Remove p class from page_related 

### ISSUE THREAD

**Issue by Rafael-Guzman** [mmistakes/minimal-mistakes#1791]
Hello Michael 

how can I remove this p class from the page_related at the bottom of the page?, some of those pages contain code, they are HTML, if I could remove that or from all the posts from showing its content

<p class="archive__item-excerpt" itemprop="description">The GeoPackage Encoding Standard describes a set of conventions for storing the following within an SQLite database:

![capture](https://user-images.githubusercontent.com/37252212/44221226-06448c00-a13e-11e8-95f7-309cacb4e521.PNG)

Regards,

Rafael

**Comment by mmistakes** [comment]
It should use it. How are you using the theme? Ruby gem or remote theme?

**Comment by Rafael-Guzman** [comment]
I have a Gemfile that says 

source "https://rubygems.org"
#gem 'github-pages', '170', group: :jekyll_plugins
gem "github-pages", group: :jekyll_plugins
gem "minimal-mistakes-jekyll"

and in the _config.yml I have 

# theme                  : "minimal-mistakes-jekyll"
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

**Comment by mmistakes** [comment]
Is the repo public? 

Could be any number of things. Caching, using Ruby gem and remote theme at the same time, not pushing content to force a GH Pages rebuild, etc etc etc.

**Comment by Rafael-Guzman** [comment]
I'm serving it locally with bundle exec jekyll serve and then push it to github

**Comment by mmistakes** [comment]
If you're using GitHub Pages then you need to use it as a `remote_theme` as they don't support 3rd party gems. So you can remove the MM gem from `Gemfile` and the `theme:` line from _config.yml

When you say you "push it to github"? Are you pushing the source files (posts' Markdown, includes, etc) or are you pushing the contents of `_site` to GitHub?

Overriding `_includes` and `_layouts` does work, but sounds like to me you have things setup incorrectly. If you can link to a public repo I can let you know pretty quick what's the problem. Right now I'm just guessing.

**Comment by Rafael-Guzman** [comment]
this is my repo 

https://github.com/Rafael-Guzman/Rafael-Guzman.github.io

and I use netlify which builds the site

**Comment by mmistakes** [comment]
Here's your problem:

![image](https://user-images.githubusercontent.com/1376749/44226309-c392ac00-a15d-11e8-9465-e3dbdfd65dfa.png)

You need to commit and push `_includes/archive__single.html` up to GitHub. It doesn't exist in your repo therefore there's nothing to override the one bundled in the theme.

**Comment by Rafael-Guzman** [comment]
but how come it doesnt change locally having archive__single.html ?

**Comment by mmistakes** [comment]
No exactly sure since I can only test what I see in your actual repo on GH.

But seeing how you have all sorts of other layouts and includes that don't apply to the theme, or the fact that you have both the Ruby gem and remote theme versions installed at the same time... you aren't doing Jekyll any favors. Wires could be getting crossed somewhere.

**Comment by Rafael-Guzman** [comment]
I got it thanks a lot, yeah I have to check my environment
