### ISSUE TITLE
Add Twitter Feed

### ISSUE THREAD

**Issue by YNedderhoff** [mmistakes/minimal-mistakes#180]
Is there a way of adding a Embedded Twitter Timeline (https://dev.twitter.com/web/embedded-timelines/user) to the right side of the start page?

In my case, right next to the text: http://nedderhoff.xyz.

**Comment by mmistakes** [comment]
Edit the theme files and just place the embed where you'd like it to appear. Should be as simple as that.

**Comment by YNedderhoff** [comment]
Thanks.
