### ISSUE TITLE
site with main page and blog section

### ISSUE THREAD

**Issue by ghiboz** [mmistakes/minimal-mistakes#1802]
## Description
how can I configure the website with a mainpage (with an header image) and a 'blog' section to show the posts?

thanks and congrats for this fantastic template!

## Environment
github pages

**Comment by mmistakes** [comment]
Have a look through the demo site's source. There are examples of these and much more.

- [Demo](https://mmistakes.github.io/minimal-mistakes/)
- [Source for demos](https://github.com/mmistakes/minimal-mistakes/tree/master/docs)
