### ISSUE TITLE
draft post: better way

### ISSUE THREAD

**Issue by ghiboz** [mmistakes/minimal-mistakes#1805]
## Description

Hi!
I need the option to write a draft, and when is ok, publish as post...
at the moment the only way is to write a page and after convert into post, but is not a good way, 'cause the post has many feature like the page doesn't have..

what will be the better way to do this?

I need to write and see the result _(only me, so an hidden link should be good)_

thanks

**Comment by ghiboz** [comment]
thanks @flohw , I read it.. but is not possible to do this online in github pages

**Comment by flohw** [comment]
Yes, you have to install ruby/jekyll first. But this is a required for what you want to do.

**Comment by mmistakes** [comment]
Closing as this isn't related to the theme as @flohw noted above and is Jekyll core / plugin territory.
