### ISSUE TITLE
Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss': Invalid US-ASCII character

### ISSUE THREAD

**Issue by mediocregopher** [mmistakes/minimal-mistakes#1809]
## Description

My project has the following Gemfile:
```
  source "https://rubygems.org"
  gem "github-pages", group: :jekyll_plugins
```

and has the line `remote_theme: "mmistakes/minimal-mistakes"` in its `_config.yml`. I've run `bundle update` already. My project has no custom assets at all, just some posts under the `_posts` directory and some images which are used by those posts in an `img` directory.

On fresh install of my repo on another machine I get the following error when trying to serve the jekyll project locally:

```
> bundle exec jekyll serve
Configuration file: /home/mediocregopher/src/blog.mediocregopher.com/_config.yml
            Source: /home/mediocregopher/src/blog.mediocregopher.com
       Destination: /home/mediocregopher/src/blog.mediocregopher.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme mmistakes/minimal-mistakes
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    Invalid US-ASCII character "\xE2" on line 54
jekyll 3.7.3 | Error:  Invalid US-ASCII character "\xE2" on line 54
```

## Environment

- Ruby version: 2.5.1p57
- Bundler version: 1.16.4
- Ruby gem or remote theme version: 0.1.1
- Jekyll version: 3.7.3
- Git repository URL: https://github.com/mediocregopher/blog.mediocregopher.com
- Operating system: Archlinux x86_64
- GitHub Pages hosted (if yes provide URL to site): https://blog.mediocregopher.com

---

## Expected behavior

Site would build and be served locally, as it seems to do so on the hosted GitHub Pages.

## Steps to reproduce the behavior

This seems to happen even with a totally empty project.

```
mkdir /tmp/testing && cd testing
echo '
title: The Mediocre Blog
name: Brian
email: whatever@gmail.com
description: whatever
baseurl: "" # the subpath of your site, e.g. /blog
url: https://blog.mediocregopher.com
repository: mediocregopher/blog.mediocregopher.com

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"


title_separator: "-"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
' > _config.yml

echo '
source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
' > Gemfile

bundle update
bundle exec jekyll serve
```

**Comment by mmistakes** [comment]
Don't think it's the theme. this feels like something with your Ruby environment. I've seen it before but don't know the fix.

Have you tried searching the closed issues on [jekyll/jekyll](https://github.com/jekyll/jekyll/issues?utf8=%E2%9C%93&q=Invalid+US-ASCII+character)?

**Comment by Felix11H** [comment]
I saw this error as well when setting up a [Docker image](https://hub.docker.com/r/felix11h/docker-mmistakes) for the blog. I could solve the problem this by using `export LC_ALL="en_US.UTF-8"`.

**Comment by ssy341** [comment]
I got this error too, but I use Windows 10, How should I set `export LC_ALL="en_US.UTF-8"` env to my PC?
