### ISSUE TITLE
How to create 'All Posts Grouped by Tags'

### ISSUE THREAD

**Issue by copdips** [mmistakes/minimal-mistakes#1816]
## Description

I searched in the doc, but I didn't find a page describing how to use the `All Posts Grouped by Tags` or by Category.
I managed to create some posts with tags, I also managed to add the tags menu from the `navigation.yml` which is pointing to url: `/tags/`, but there's nothing inside.
I heard about the plugin `jekyll-archive`, but it seems that github pages doesn't support it.
I found the [PR-1209](https://github.com/mmistakes/minimal-mistakes/pull/1209/files), but it seems that it is only for doc.

For the moment, I found some tricks that works:
https://github.com/cagrimmett/jekyll-tools#posts-by-tag
http://dareneiri.github.io/Jekyll-Themes-and-Tags/

But what I really want is this style:
https://mmistakes.github.io/minimal-mistakes/tags/
https://mmistakes.github.io/minimal-mistakes/categories/

Is it possible to add a doc to let us know easily how to archive that ?
Thanks.

## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- Operating system:
- GitHub Pages hosted (if yes provide URL to site):

---

**Comment by mmistakes** [comment]
It’s [documented here](
https://mmistakes.github.io/minimal-mistakes/docs/layouts/#taxonomy-archives).

 You need to add a tag and category page using the specified layouts. There are links in the docs to copy the Markdown needed to make these pages.

Also the entire source for the MM demo site is in [`/docs` folder](
https://github.com/mmistakes/minimal-mistakes/tree/master/docs) if you need to see how I’m doing things.

**Comment by copdips** [comment]
@mmistakes,

Thx a lot for your rapid reponse.
I managed to make it working.

I suggest to replace following line in your [doc](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#taxonomy-archives) :

`"adding to your site"`
by
`"adding at the root of your site"`

I think it would be more clear by this way.

**Comment by mmistakes** [comment]
They don’t need to be in the root. Some people use a `_pages` folder with custom permalinks set. That’s why I left it intentionally vague as those pages can be setup in multiple ways depending on how you like to organize things.

**Comment by copdips** [comment]
thx for the confirmation
