### ISSUE TITLE
Shortcut to use font awesome icons in title and contents?

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/minimal-mistakes#1818]
I searched the documentation, but not able to figure out the **shortcut** to add font awesome icons to title and in the contents of posts.
**For example : -** Instead of using `<i class="fas fa-landmark"></i>` , is there any shortcut code like     `:fa-landmark` ?

**Comment by mmistakes** [comment]
The theme has no such shortcut.

You'll need to install a plugin similar to this <https://gist.github.com/23maverick23/8532525>

**Comment by Kulbhushan-Chand** [comment]
@mmistakes  Thanks for quick reply.

Plugin looks fine, however I rely on building website from GithubPages and they does not support external plugins. Looks like I have to use `<i class="fas fa-landmark"></i>`

**Comment by mmistakes** [comment]
Yeah I get that. Unfortunately that is out of control for the theme. This is more of an addon/plugin than anything the theme can be concerned with. It can probably be done with Jekyll includes which would be supported with GH Pages.

You could also look into [Netlify](https://www.netlify.com/). They will build your Jekyll site similar to GitHub Pages for free and they also support plugins.

**Comment by Kulbhushan-Chand** [comment]
@mmistakes Thanks for the tip about **Netlify**. 👍 

_**Thing is there is no all-in-one solution.**_ 

- Netlify has their own semantic in the website name and who knows in future if Netlify decide to change the pricing policy.
- GitHub has its own charm
  - Epic meaning of open source
  - Free developer account to students
  - and many more

I think (for me) its best to avoid [decision fatigue](https://en.wikipedia.org/wiki/Decision_fatigue). 🤔

**Comment by mmistakes** [comment]
Closing as this is something that can be added outside of the theme.

If someone builds an include to do this, it woudn't need to be merged in this project and could be its own thing.
