### ISSUE TITLE
Toggle Menu not showing up on small screens

### ISSUE THREAD

**Issue by Hannili** [mmistakes/minimal-mistakes#1819]
## Description

Collapse sidebar / Toggle menu not showing up on small screens.

## Environment

Cannot be seen anymore on the projects own website:
https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

---

## Expected behavior

A toggle menu button should appear on small screens (instead of showing the whole menu). It was introduced and discussed here: #607

I also have seen this feature on the projects documentation website a while ago.
Was it intendedly removed?

## Steps to reproduce the behavior

Use the mobile view of your browser on https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

**Comment by mmistakes** [comment]
Looks like Prettier mangled some of the Sass used to make the toggle work. I've corrected that and it should be fixed on `master`.
