### ISSUE TITLE
audio and video files

### ISSUE THREAD

**Issue by Rafael-Guzman** [mmistakes/minimal-mistakes#1827]
hello Michael, 

I'd like to submit posts that include a video or audio file, and the audio/video player too, files that could be hosted on another server or here in github, have you done something like this ?, I'm thinking what could be a good way to do this, I dont know if you have looked at octopod, a podcast project for jekyll, it grabs the audiofiles from the URL provided,

thanks

**Comment by mmistakes** [comment]
There's this old #101

Any modern browser can handle [`<audio>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) and [`<video>`](**url**) elements. At a basic level you can simply add them to your Markdown or HTML files and the browser will render them with player controls. There's nothing special the theme has to do.

```html
<audio controls>
  <source src="myAudio.mp3" type="audio/mp3">
</audio>

<video controls>
  <source src="myVideo.mp4" type="video/mp4">
</video>
```

I've heard of Octopod, but haven't used it or looked at its source. I don't podcast nor am I building a podcast theme so the need has never been there.

**Comment by lsolesen** [comment]
I've done this on http://github.com/vih/historie. It is by no means a perfect implementation, but it works allright.

https://github.com/vih/historie/blob/gh-pages/_includes/podcast-player.html
https://github.com/vih/historie/blob/gh-pages/_posts/2018-03-09-marie-lisby.md

If you come up with an even more clever implementation, I am all ears :)

**Comment by saguileran** [comment]
[lsolesen](https://github.com/lsolesen)
is it possible to use several audios on the same page and does it support wav files?
