### ISSUE TITLE
"Install Now" link error in home page

### ISSUE THREAD

**Issue by ykfq** [mmistakes/minimal-mistakes#1828]
When open the home page of minimal-mistakes, I found that the `Install Now` link is `404`, it jumps to **https://mmistakes.github.io/docs/quick-start-guide/** and it does not exist, the correct link is **https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/**, please update it.

**Comment by ykfq** [comment]
You fixed it so quickly！

**Comment by mmistakes** [comment]
There was a bug in the hero include that wasn't correctly applying the `relative_url` filter to the link. Should be fixed now.

https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/page__hero.html#L56-L64
