### ISSUE TITLE
Staticman comment issue when file name of post is changed

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/minimal-mistakes#1834]
The comments generated by staticman are saved in `/data/<subfolder>` folder. 

_If in future, we change the name of the markdown file in `_posts` the new comments will be saved in a new `<subfolder>`folder, and all the previous comments are not available._ 

 **My doubts -** 
- Is there any way to address the problem mentioned above?
- Is the new `<subfolder>` created by staticman tied to the post url, or permalink, or filename?

**Comment by mmistakes** [comment]
Check out my blog post to get an overview on how Staticman comments.
You can come up with whatever folder structure you want with regards to the comment data files. I decided on subfolders that match the post filename so they can be easily matched.

You can see [how that works here](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments.html#L35).

So yes. If you change the post name slug after having comments on that post, they won't show up unless you rename the `_data/subfolder` to match it. 

If all of your posts had some sort of unique identifier that never changed it wouldn't be as fragile, but currently Jekyll doesn't have that.

**Comment by Kulbhushan-Chand** [comment]
**Thanks for directions.**

I think the best option right now is - 
 **_If I ever change the filename in future , I should manually rename the `<folder>` corresponding to staticman comments in `/data/ ` folder immediately._**

**Comment by mmistakes** [comment]
That is correct.
