### ISSUE TITLE
Remove unneeded HandheldFriendly and MobileOptimized meta tags

### ISSUE THREAD

**Issue by coliff** [mmistakes/minimal-mistakes#1835]
```
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
```
I realise that these meta tags aren't doing any harm - but they are not needed at all and take up a few bytes of the page loading.

- The `HandheldFriendly` meta tag was used for a very old version of BlackBerry.
REF: https://developer.blackberry.com/playbook/html5/documentation/handheldfriendly.html

- The `MobileOptimized` meta tag was used for a very old version of Windows Mobile 5 / 6 (before even Windows Phone 7, 8 and Windows Mobile 10!).

I was thinking of making a PR to remove then, but wanted to check with you first.

**Comment by mmistakes** [comment]
Yes, please submit a PR to remove them. Thanks for bringing it up.

**Comment by junaga** [comment]
Hi @coliff, would you mind sharing the source explaining `<meta name="MobileOptimized">`. For `<meta name="HandheldFriendly">` I have this one https://getoutofmyhead.dev/handheld-friendly/.

**Comment by coliff** [comment]
> Hi @coliff, would you mind sharing the source explaining `<meta name="MobileOptimized">`. For `<meta name="HandheldFriendly">` I have this one [getoutofmyhead.dev/handheld-friendly](https://getoutofmyhead.dev/handheld-friendly/).

It was for old Internet Explorer for Windows Mobile... docs here:
https://learn.microsoft.com/en-us/previous-versions/bb431690(v=msdn.10)?redirectedfrom=MSDN

**Comment by junaga** [comment]
again, thank you very much. the reason I am asking, is because source citations are important. every developer is afraid of these tags, if we share and hardlink (in code/docs) how/why they are redundant, we remove the fear and everyone wins.

add me `@junaga` on https://discord.com/app
