### ISSUE TITLE
Issues with permalink and category-archive page

### ISSUE THREAD

**Issue by halfundecided** [mmistakes/minimal-mistakes#1857]
Hello!

First of all, 
[Link to blog](http://www.mijeong.me/dev-blog/)
[Link to repo](https://github.com/halfundecided/dev-blog)

I'm new to make a blog with Jekyll, I recently got an issue with my blog pages.
The problem is that I get 404 page when I click each posts from tag-archive page. It seems like it does not set the permalink properly. For example, the proper permalink for one of my posts(092818_TIL) should be http://www.mijeong.me/dev-blog/092818_TIL/. However, when I click this post from tag-archive page it goes to http://www.mijeong.me/092818_TIL/, which does not include my base url.

How can I fix this? 
Thank you.

**Comment by mmistakes** [comment]
Your custom layouts are the problem. You'll need to use Jekyll's `relative_url` filter on your `{{ post.url }}` statements. This will append your `baseurl` properly.

Take a look at the theme's `archive-single.html` include for an example of how to apply the filter.

**Comment by halfundecided** [comment]
That fixed the problem!

Thank you so much.
