### ISSUE TITLE
Cannot get installation working on remote laptop

### ISSUE THREAD

**Issue by ansiblejunky** [mmistakes/minimal-mistakes#1860]
I have tried your instructions but all I get when I run `bundle exec jekyll serve` is a blank page with VERY little content. I just want to do a `git clone` and test out your theme and throw some of my content into it before I decide to switch to your theme. I really like the theme but want to play around with it first. So far not able to get it working with any content at all. 
![image](https://user-images.githubusercontent.com/14311849/46305294-e5a58980-c565-11e8-9640-6c6b3bbe436f.png)

**Comment by mmistakes** [comment]
Add posts.

**Comment by ansiblejunky** [comment]
Yes, I just now figured that out and moved the content from `test` folder to the main site folder. Now it's looking better. Still however I do not get the image header that is shown on your demo site. I get the profile sidebar, and then a list of posts. How do I get a header image for my website? 

Also, is there an easy way to add thumbnail images to each post on the homepage? At the moment its just a text-based list of posts. Again, like your demo where you had 4 thumbnails listed. I like that style.

By the way, it's a really nice theme you created. Thank you!

When you have fixes/updates to your theme, what's the best way for me to update it in my github repo? 

One bit of feedback, when I try the gallery post where it shows multiple images and I select one and it opens up the lightbox... closing the lightbox with the `X` causes some red rectangle to show up very fast. This doesn't look good. Can you fix that?

**Comment by mmistakes** [comment]
The demo site's source is in [`/docs` folder](https://github.com/mmistakes/minimal-mistakes/tree/master/docs). You can find how I do everything there... hint the [home page](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_pages/home.md) is using `layout: splash`. You'll probably want to look over the the documentation completely as there's a lot in there that with examples.

If you want thumbnails in the post lists you'll need to use the grid layout or hack something else. Search through the closed issues, I've covered it a few times.

**Comment by Kulbhushan-Chand** [comment]
> One bit of feedback, when I try the gallery post where it shows multiple images and I select one and it opens up the lightbox... closing the lightbox with the X causes some red rectangle to show up very fast. This doesn't look good. Can you fix that?

Even I have that red rectangle problem, but choose to ignore that. May be there is a fix.

**Comment by mmistakes** [comment]
That's in there for accessibility reasons I believe, `:focus` on the close button. I didn't build that library so can't fully say, but that's my take on it.

**Comment by Kulbhushan-Chand** [comment]
Thanks, I have styled it away by including it it main.scss file
