### ISSUE TITLE
Error unzipping theme

### ISSUE THREAD

**Issue by blackat** [mmistakes/minimal-mistakes#1866]
Hello,
thanks a lot for the great theme, I am using it since 1 year.
Since a couple of days I get an issue runnig jeckyll.

OSX Mojave
Jekyll 3.7.4
ruby 2.5.0

When I run bundle exec jekyll serve I get this new error
```
Generating... 
      Remote Theme: Using theme mmistakes/minimal-mistakes
      Remote Theme: Downloading https://codeload.github.com/mmistakes/minimal-mistakes/zip/master to /var/folders/lt/4k9qvzbx7p5b0sv501s1s3_00000gn/T/jekyll-remote-theme-20181002-21853-1o3uh7j.zip
      Remote Theme: Unzipping /var/folders/lt/4k9qvzbx7p5b0sv501s1s3_00000gn/T/jekyll-remote-theme-20181002-21853-1o3uh7j.zip to /private/var/folders/lt/4k9qvzbx7p5b0sv501s1s3_00000gn/T/jekyll-remote-theme-20181002-21853-bb0yli
jekyll 3.7.4 | Error:  Zip end of central directory signature not found
```
any idea?

**Comment by mmistakes** [comment]
Not sure. You'll want to file an issue with [jekyll-remote-theme](https://github.com/benbalter/jekyll-remote-theme). They'll be of more help than me since it concerns their plugin.

**Comment by blackat** [comment]
I have restarted the process without the VPN activated and it seems working as before, I guess there is something strange going on with the VPN activated.

Thanks a lot I will follow your advice 👍
