### ISSUE TITLE
Make theme GDPR Compiliant

### ISSUE THREAD

**Issue by Scot3004** [mmistakes/minimal-mistakes#1867]
Theres #1662 in stale state

# How I think could be done
* Add to the theme a new hook for custom cookies scripts like [this](https://github.com/Scot3004/Scot3004.github.io/blob/master/_includes/cookies.html)
* Adding the modal included in theme and the respective tutorial to add term and conditions and other policies (legal things)

## Motivation

I think europeans could use this template or even people for other countries want to target this market.
My case is that I want to target european users but my current website is using google analytics (included in the theme) and other things that uses cookies

## Drawbacks

Implement this is a pain (Europeans and theirs laws)

A workaround is not using Google analytics at all, looks like a bad idea :sweat_smile:

**Comment by RichStone** [comment]
are there other current workarounds to have a compliant site with out the enhancements implemented yet?

**Comment by Scot3004** [comment]
If you don't use google analytics, you may be no need cookies

**Comment by antenore** [comment]
@maxime-michel the gdpr is backed up by laws, so if you infringe those laws, a tribunal may fines and/or shutdown your web site, depending on where is hosted, and which agreements there are between your country and Europe.
As soon as I'll have time, I'll investigate further on this as we're impacted as well with remmina.org

**Comment by maxime-michel** [comment]
Don't get me wrong, I'm happy to join the effort if there's a subtask that I could help with. But it's hard to make it a priority for me as well, when I still routinely see national-level companies that send email without any sort of opt-out.

**Comment by mmistakes** [comment]
> @mmistakes cannot know your specific use case and build a wonder machine that write and activates/deactivates things on your behalf miraculously understanding the context on which the theme has been used.

:+1: 

I believe the theme provides the mechanisms to make your site GDPR compliant. There are enough cookie consent generators out there that will guide you through the process and give you some JS/CSS you can embed to your page. I'm really not interested in taking a stab at my own as it will never meet the needs of everyone.

Best advice I can offer is:

1. Use something like [Cookie Consent](https://cookieconsent.insites.com/download/)
2. Configure your cookie consent
3. Copy/paste the code they provide into [`_includes/footer/custom.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/footer/custom.html) (create if you're using remote_theme or Ruby gem to override the default)
4. Create a Privacy Policy page and give it `layout: single`, here's a[ sample `.md` file](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_pages/terms.md) the demo site uses.
5. Add a [footer link](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-footer) to your privacy policy page.

**Comment by maxime-michel** [comment]
That's helpful, thanks. Another suggestion could be to use the `youtube-nocookie.com` domain as well as the `?dnt=true` flag for Vimeo embeds in the `video` include.

**Comment by mmistakes** [comment]
@maxime-michel I'd be on board if someone wanted to submit a PR to do both of these.

**Comment by maxime-michel** [comment]
I'll take care of it.

**Comment by fjp** [comment]
@mmistakes I think [this Jekyll script](https://raw.githubusercontent.com/jhvanderschee/jekyllcodex/gh-pages/_includes/cookie-consent.html) could be useful to implement a GDPR compliant solution. 
It's from [jekyllcodex.org](https://jekyllcodex.org/without-plugin/cookie-consent/).

> This script allows you to delay the loading of certain Javascript includes, until the user clicks on ‘Approve’ in a cookie banner.

The installation is as follows:

> Step 1. Download the file [cookie-consent.html](https://raw.githubusercontent.com/jhvanderschee/jekyllcodex/gh-pages/_includes/cookie-consent.html)
> Step 2. Save the file in the ‘_includes’ directory of your project
> Step 3. Make sure the bottom of your layout document looks like this:

```
{% include cookie-consent.html %}
</body>
</html>
```

The `_layouts/default.html` of the minimal mistakes theme looks like this:

```
...
    <div id="footer" class="page__footer">
      <footer>
        {% include footer/custom.html %}
        {% include_cached footer.html %}
      </footer>
    </div>

    {% include scripts.html %}

  </body>
</html>
```

Is it possible to move the `{% include scripts.html %}` inside the `<footer> </footer>`
and wrap the content with the provided `cookie-consent.html` script?

As far as I understand this script we just have to move 

```
{% include footer/custom.html %}
{% include_cached footer.html %}
{% include scripts.html %}
```

out of  `_layouts/default.html` and into the following section of the `cookie-consent.html`:

if(readCookie('cookie-notice-dismissed')=='true') {
        {% include ga.js %}
        {% include chatbutton.js %}
        {% include footer/custom.html %}
        {% include_cached footer.html %}
        {% include scripts.html %}
    } else {
        document.getElementById('cookie-notice').style.display = 'block';
    }
```

And then include the `cookie-consent.html` in the footer tag of `_layouts/default.html`:

```
...
    <div id="footer" class="page__footer">
      <footer>
        {% include cookie-consent.html %}
      </footer>
    </div>

  </body>
</html>
```

Am I missing something important? Or is there a reason why the `{% include scripts.html %}` has to be outside the footer tag?

**Comment by fjp** [comment]
> Am I missing something important?

Ok, I guess this won't work the way I wrote and hoped with `scripts.html` included in `cookie-consent.html` because `scripts.html` uses `<script> </script>` tags.
