### ISSUE TITLE
How to add a "raw" html+javascript page?

### ISSUE THREAD

**Issue by alkamid** [mmistakes/minimal-mistakes#187]
I'd like to add a page that would be purely in HTML + javascript that would come up on my domain (alkamid.com/mypage) but not in the post index. I tried simply creating another layout (`_layouts/raw-page.html`) with `{{ content }}` only, but javascript (d3.js) is not executing. Specifically, I'd like to add this gist as a separate page: https://gist.github.com/alkamid/29f86cfb22c8bdb080ab. How to do this properly?

**Comment by mmistakes** [comment]
You'll want to create a page outside of the `_posts` folder. Look at [`theme-setup`](https://github.com/mmistakes/minimal-mistakes/tree/master/theme-setup) as an example of how pages are setup. 

Basically you create a folder in the root of your Jekyll site and place an `index.md` file inside of that with Markdown or HTML. There's a million different ways to do this but one way off the top of my head:

1. Create a new layout `/_layouts/raw-page.html` and populate it with the contents from that gist.
2. Create `/mypage/index.md`. Add the appropriate YAML Front matter for title and set `layout: raw-page` and leave the content blank.

When you build your site you should get a page at `alkamid.com/mypage/` that looks like your gist.

If you want more info on how Pages work with Jekyll check out the [official documentation](http://jekyllrb.com/docs/pages/).

**Comment by mmistakes** [comment]
Also you should be able to just add a raw HTML file (or any file for that matter) in root. If you don't include any YAML Front Matter Jekyll should leave it alone. So instead of doing what I suggested above just created `/mypage/index.html` and place the contents of your gist in that file.
