### ISSUE TITLE
"YOU MAY ALSO ENJOY" section does not show related topics

### ISSUE THREAD

**Issue by ansiblejunky** [mmistakes/minimal-mistakes#1871]
I was expecting the `YOU MAY ALSO ENJOY` section to show related topics based on similar tags. This would make more sense. At the moment it only shows the most recent 4 articles. Can this be easily changed?

**Comment by mmistakes** [comment]
Yes and no. The theme uses Jekyll's `site.related_posts` array which under the right circumstances enables related posts.

> If the page being processed is a Post, this contains a list of up to ten related Posts. By default, these are the ten most recent posts. For high quality but slow to compute results, run the `jekyll` command with the `--lsi` (latent semantic indexing) option. Also note GitHub Pages does not support the `lsi` option when generating sites. 
> ref: [jekyll docs](https://jekyllrb.com/docs/variables/#site-variables)

I've also flirted with using Liquid to generate related posts based on their tags. This is 100% GitHub Pages compatible, but it negatively impacts build times considerably so I didn't merge it in. If you're curious what that change entails take a look at #978.

**Comment by aschrijver** [comment]
So the issue of related posts highlighted on [this page](https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-related-posts/) in comments, is still at play?

**Comment by mmistakes** [comment]
Yes. They were considerably longer, especially for large sites.

The fixes are:
1. don't host with GH and use a provider that allows you to enable `LSI`
2. Use my "related posts by tag" Liquid code in that unmerged pull request

**Comment by aschrijver** [comment]
Thank you @mmistakes ! I am on GH, so I'll go for 2.
