### ISSUE TITLE
Add types to links to css files and scripts

### ISSUE THREAD

**Issue by Solvegam** [mmistakes/minimal-mistakes#1878]
Hi there!)

First of all thank you for such an amazing theme!)

I am trying to host static website using gitlab pages. Everything looks working except downloading of style and js files:
`Refused to apply style from because its mime type ('text/html') is not a supported stylesheet mime`
<img width="1111" alt="screenshot 2018-10-06 at 14 26 30" src="https://user-images.githubusercontent.com/10787896/46571370-3527f300-c974-11e8-936a-f1e31e191c34.png">

Adding type properties to link tags of css and script can be a possible solution. If I understood everything right it should be done here:
/_includes/head.html
`line 15 <link rel="stylesheet" href="{{ '/assets/css/main.css' | relative_url }}" type="text/css">`
`line 39 <script src="{{ script_path }}" type="text/javascript"></script>`

**Comment by mmistakes** [comment]
I did a quick search and there are a lot of issues similar to this. Looks like GitLab doesn't set the correct mime types for whatever reason when it serves these files. Not sure what the fix is as I don't use GitLab.

**Comment by Solvegam** [comment]
Thank you for such a quick answer, added comments to relevant issue in [gitlab issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues/49310).

**Comment by Solvegam** [comment]
Checked locally my suggestion - it won't help.

**Comment by mmistakes** [comment]
Figured as much. This seems to be a server issue which I guess GitLab needs to address.

**Comment by Solvegam** [comment]
The reason is that gitlab uses repo name as a base path during deployment, it means that all you assets should have url like https://your_login.gitlab.io/**repo_name**/assets/css/main.css instead of just https://your_login.gitlab.io/assets/css/main.css
You may find other answer [here](https://gitlab.com/gitlab-com/support-forum/issues/2863)
