### ISSUE TITLE
Using FontAwesome within markdown in posts

### ISSUE THREAD

**Issue by ansiblejunky** [mmistakes/minimal-mistakes#1880]
I read through the following [issue](https://github.com/mmistakes/minimal-mistakes/issues/1818) regarding using FontAwesome, however it leads me to add the code `<i class="fas fa-info-circle"></i>` within my markdown text at every place I need it. I wanted to use the info circle whenever I do a `blockquote`.  So its not good coding to paste that text within my markdown at every location I do a blockquote. I would instead like to set it up by changing the css somehow.  So I looked into adding the following in the `main.scss` file:
```
blockquote::before {
  font-family: FontAwesome;
  content: '\f05a'; 
}
```
However, this results in the page showing a black square icon. Seems weird to me. The icon shows correctly when I use the `<i class="fas fa-info-circle"></i>` within the markdown text however. 

Any ideas?

**Comment by mmistakes** [comment]
I'd suggest StackOverflow or searching through FontAwesome's issues to see if others have been able to do this. Their older versions you could just as you have above, but maybe that's changed with the new JavaScript version.

**Comment by mmistakes** [comment]
Also the way FontAwesome works now isn't by using a webfont. It's inject the icons as inline SVGs via their JavaScript method.

Check their documentation, as it's possible but you need to do things slightly different from what you have above.

https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

**Comment by ansiblejunky** [comment]
Ok thanks. Where in your theme do you actually load/reference the Font Awesome font? I could not find that.

**Comment by ansiblejunky** [comment]
So you are using the Font Awesome Free? I have literally tried solving this problem but still getting that block square icon no matter what I try. Here is what I have written now in my `main.scss`.
```
@font-face {
    font-family: 'FontAwesome';
    src: url('../fonts/fa-solid-900.eot');
  }
blockquote::before {
    display: inline-block;
    font-style: normal;
    font-variant: normal;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    font-family: "FontAwesome";
    font-weight: 900; content: "\f007";
  }
```

And then I downloaded the files from `https://github.com/FortAwesome/Font-Awesome/tree/master/web-fonts-with-css/webfonts` and moved them to `assets/fonts/` folder.  However, this still produces the square icon. 
So at this point I am out of any other options. Anyone else can offer advice here it would be much appreciated.

**Comment by ansiblejunky** [comment]
Additionally, I tried the following in the `main.scss` but it didn't work.
```
@import url("https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/web-fonts-with-css/css/fontawesome-all.min.css"); /* FA CSS import */

/* ... */

blockquote:before {
    /* >> Symbol you want to use: */
    content: "\f16c";
    /* >> Name of the FA free font (mandatory)
               - 'Font Awesome 5 Free' for Regular and Solid symbols;
               - 'Font Awesome 5 Brand' for Brands symbols. */
    font-family: 'Font Awesome 5 Free';
    /* >> Weight of the font (mandatory)
               - 400 for Regular and Brands symbols;
               - 900 for Solid symbols. */
    font-weight: 900;

    /* >> Optional styling: */
    display: inline-block;
    /* ... */
}
```

**Comment by mmistakes** [comment]
You're in StatckOverflow territory now since this is general web dev stuff. I'd suggest expanding your search there.
