### ISSUE TITLE
Lunr Update to current release: 2.3.3

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#1882]
## Summary

I noticed that the version of LUNR on MM is 2.1.5, but the current version of [LUNR is 2.3.3](https://github.com/olivernn/lunr.js/tree/v2.3.3).  Wanted to see if there was any history or documentation that should be reviewed so I can submit a pull request.  Was 2.1.5 simply dropped in, or was there some additional "hacks" that were performed... so a simple copy/paste is not ideal?

## Motivation

In Safari, LUNR throws errors `undefined is not an object (evaluating 'y._index')` and does not return results as expected.

**Comment by mmistakes** [comment]
My memory is hazy on this. I think it was hacked up some and probably not a drop-in replacement when upgrading, but I could be wrong and the custom stuff is coming in the stemmers.

@nickgarlis did all of the work and is more qualified to answer this question than me.

**Comment by justinrummel** [comment]
Thanks, hopefully @nickgarlis can chime in, else I'll slap the update and test locally and see what happens. :)

**Comment by mmistakes** [comment]
Sounds good. For my other theme I used an off the shelf cut of [Lunr](https://github.com/mmistakes/jekyll-theme-basically-basic/tree/master/assets/javascripts/lunr) with these [language addons](https://github.com/MihaiValentin/lunr-languages). Could go that route if necessary.

I think all the custom stuff came in the [lunr-en.js](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/lunr/lunr-en.js) and [lunr-gr.js](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/lunr/lunr-gr.js). So unless there were some big API changes from 2.15 we should be safe just updating [lunr.js](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/lunr/lunr.js) and [lunr-min.js](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/lunr/lunr.min.js) to the latest version.

**Comment by justinrummel** [comment]
Doing quick update to lunr.jr and lunr.min.js with 2.3.3 looks good.  No Console errors and fast accurate results.  Submitting a PR.

**Comment by mmistakes** [comment]
Sounds good. Thanks!

**Comment by justinrummel** [comment]
PR submitted: https://github.com/mmistakes/minimal-mistakes/pull/1885

**Comment by nickgarlis** [comment]
@justinrummel There don't seem to be any major updates with the API so I don't think this update is going to cause any issues. As @mmistakes has already stated the only custom configuration was in [lurn-en.js](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/lunr/lunr-en.js) and [lurn-gr.js](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/lunr/lunr-gr.js).
