### ISSUE TITLE
How to generate numbered headings and TOC?

### ISSUE THREAD

**Issue by manid2** [mmistakes/minimal-mistakes#1890]
Hi, is it possible to generate the TOC and the headings with numbers without manually entering the section numbers, as shown below?

# 1. First

### 1.2.1 The thing

# 2 Second

### 1.2.1 The thing

From
```
# First

## One thing

## Another thing

### The thing

# Second

## One thing

## Another thing

### The thing
```

It will be useful and meaningful in blog posts of 2000 - 4000 words.

Thank you,
Mani

**Comment by mmistakes** [comment]
Not with the theme. You need some sort of Jekyll plugin or feature in Kramdown to do that.

Closing as this is something core Jekyll (or a plugin) would need to do.
