### ISSUE TITLE
how can I post a html file in posts folder?

### ISSUE THREAD

**Issue by InspiringPeople** [mmistakes/minimal-mistakes#1892]
I made HTML file by jupyter notebook using python code.
It doesn't allow to align contents and frame approximately if I use HTML file. (wrong.png)
But it makes sense with markdown file if I save jupyter notebook as markdown file. (right.png)
How can I post HTML file in posts folder?

(I set the markdown / HTML files in the same posts folder.)
Thanks in advance
![right](https://user-images.githubusercontent.com/34572963/46859409-a5d58080-ce48-11e8-9cbe-f6d97e90d0ab.png)
![wrong](https://user-images.githubusercontent.com/34572963/46859410-a5d58080-ce48-11e8-96ed-859f9e90744d.png)

**Comment by mmistakes** [comment]
Without seeing the HTML or Markdown you're trying to add to a post I can't really offer a suggestion.

Please add a link to a public GitHub repo that shows the issue, screenshots aren't enough.

**Comment by InspiringPeople** [comment]
sorry to bother you. but I'm a huge fan of minimal-mistakes :)
Here are my github link and github page.
- https://inspiringpeople.github.io/simple_test/
- https://github.com/InspiringPeople/InspiringPeople.github.io/blob/master/_posts/2018-01-15-simple_test.html
Thanks in advance.

**Comment by mmistakes** [comment]
I see the problem. You're trying to embed an entire `<html>` file inside of another one. This breaks the layout.

I don't think you're going to be able to drop in the HTML that is generated for you verbatium into a post. You'd need to strip out just the main content from that, but that could be difficult as it looks like it's applying Bootstrap CSS to entire thing... which the theme doesn't use.
