### ISSUE TITLE
Question about Facebook Feed

### ISSUE THREAD

**Issue by p16sako** [mmistakes/minimal-mistakes#1896]
Hello and thanks for your time in advance. How would it be possible for me to embed a facebook feed in my website? The website ofcourse is using a fork of minimal-mistakes. I tried using the facebook page plugin but so far i haven't been able to do it. If it's not too much trouble please direct me to the right source or give me some tips. Again thanks a lot for your time.

**Comment by RichStone** [comment]
Shouldn‘t there be some sort of HTML/JS embeddings?

It probably doesn’t have something to do with the theme, though..

**Comment by mmistakes** [comment]
@RichStone is correct. This isn't a theme issue. Facebook should give you an embed you can paste into a post, layout, or, include.

Basics knowledge of HTML is need and not something I can cover here. Stackoverflow or a related site is the appropriate place to ask for this sort of help.
