### ISSUE TITLE
Follow button doesn't open the social links overview

### ISSUE THREAD

**Issue by RichStone** [mmistakes/minimal-mistakes#1899]
## Expected behavior

When I click the follow button on my mobile phone I expect to see the buttons for the different social account opening up.

However nothing happens onclick.

## Environment

Tried on newest iOS - iPhone 8 Plus

Don't know if android has the same issue.

I tried it with three different minimalmistakes blogs, including [datagoodie.com](https://datagoodie.com)

<img width="409" alt="example" src="https://user-images.githubusercontent.com/15954169/47207567-c8592380-d38b-11e8-9626-07276c51a4d1.png">

**Comment by mmistakes** [comment]
You sure you don't have a content blocker installed?

That link above works fine for me on iOS. 

![9ce0a60f-eeca-4cbb-9eac-e3686c13e93c](https://user-images.githubusercontent.com/1376749/47217011-ebc4a400-d374-11e8-8494-7bb123b21ebb.png)

As does the themes demo site.
https://mmistakes.github.io/minimal-mistakes/year-archive/

![50a9c0de-9fb9-4458-a346-b1abe2f38b33](https://user-images.githubusercontent.com/1376749/47216942-b28c3400-d374-11e8-8e18-36f49c314f2f.png)

**Comment by RichStone** [comment]
You are totally right.

It is this option "Block Windows" option in the iPhone Safari settings that blocks the popup:

![Safari Settings -> General](https://user-images.githubusercontent.com/15954169/47229257-936ac200-d3c7-11e8-87d5-6d0bf1994c06.png)
