### ISSUE TITLE
remove orange box from active link

### ISSUE THREAD

**Issue by houtanb** [mmistakes/minimal-mistakes#1900]
Hi,

I really like your theme a lot. However, there's one thing I just can't figure out. I'd like to remove the orange box around an active link, the one you see in the screenshot below. It's activated when you right click on a link but, also, on certain OS/browser combos (Debian/Firefox) when someone hits the back button. I couldn't track down where this was in the CSS. Could you point me to the right location to remove the box?

![screen shot 2018-10-19 at 11 30 13](https://user-images.githubusercontent.com/584723/47210264-ce9ece00-d392-11e8-8538-26cea7e332a9.png)

**Comment by mmistakes** [comment]
This is a `: focus` state. It's good for accessibility.

https://css-tricks.com/focusing-on-focus-styles/

If you really want to remove it look here:
https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_base.scss#L130
