### ISSUE TITLE
`include_cached` preventing Disqus comments from displaying

### ISSUE THREAD

**Issue by paulfioravanti** [mmistakes/minimal-mistakes#1905]
## Environment

- Minimal Mistakes version: 4.13.0
- Ruby gem or remote theme version: remote theme version used
- Jekyll version: 3.7.4
- Git repository URL: https://github.com/paulfioravanti/paulfioravanti.github.io
- GitHub Pages hosted (if yes provide URL to site): https://paulfioravanti.com
- Operating system: Mac OS High Sierra 10.13.6 (17G65)

## Expected behavior

Disqus comments display underneath a post when `site.comments.provider` is `"disqus"`.

## Steps to reproduce the behavior

No specific steps to re-produce as the comments were working previously at some point in the past, and then one day I noticed they were not displaying anymore. However, I suspect that #1874 could be a potential cause (see further information below for reasoning).

The log of `bundle exec jekyll build --trace --verbose` was quite long, so I put it in [this gist](https://gist.github.com/paulfioravanti/054622dc34b8708716d9c35c1947ded3).

## Other

Here is a screenshot of running `JEKYLL_ENV=production bundle exec jekyll liveserve` on my local machine with the current version of Minimal Mistakes, where you can see that comments are not displaying:

<img width="934" alt="current_situation" src="https://user-images.githubusercontent.com/543366/47325859-9e686f80-d6b1-11e8-97f0-262ceacba14b.png">

Here is a screenshot of running `JEKYLL_ENV=production bundle exec jekyll liveserve` on my local machine after making the following changes:

1. Copying the content of [`_layouts/default.html`](https://github.com/mmistakes/minimal-mistakes/blob/c8f4820d31c6b4c605ec96f74213df007c74c7cd/_layouts/default.html) to a local `_layouts/default.html` file, and changing https://github.com/mmistakes/minimal-mistakes/blob/c8f4820d31c6b4c605ec96f74213df007c74c7cd/_layouts/default.html#L39
from `{% include_cached scripts.html %}` to `{% include scripts.html %}`
2. Copying the content of [`_includes/scripts.html`](https://github.com/mmistakes/minimal-mistakes/blob/c8f4820d31c6b4c605ec96f74213df007c74c7cd/_includes/scripts.html) to a local `_includes/scripts.html` file, and changing https://github.com/mmistakes/minimal-mistakes/blob/c8f4820d31c6b4c605ec96f74213df007c74c7cd/_includes/scripts.html#L28 from `{% include_cached /comments-providers/scripts.html %}` to `{% include /comments-providers/scripts.html %}`

<img width="946" alt="with-include-cached-removed" src="https://user-images.githubusercontent.com/543366/47326031-98bf5980-d6b2-11e8-8e85-017995a6d052.png">

Making these changes does output some Javascript errors in the console, unfortunately:

<img width="1278" alt="js-errors" src="https://user-images.githubusercontent.com/543366/47326119-feabe100-d6b2-11e8-9494-6216e57c9aa7.png">

However, since the comments are now displaying, I see the Javascript errors as the lesser of two issues. Hence, I have deployed out this change to [my site on Github Pages](https://paulfioravanti.com/), and can confirm that comments are displaying there as expected.

I haven't made a PR with the changes I've outlined since it brings up JS issues and I cannot confirm that the issue exists for other comment providers, but am happy to provide any further information I may have neglected to put in this issue.

**Comment by mmistakes** [comment]
It's definitely the cached include. The scripts and all comment provider includes should be reverted back to normal `{% include %}`

Some use `page` variables that I glossed over when don't the original enhancement, and those can't be cached to work properly.

**Comment by luispuerto** [comment]
Hey! 

I just notice this when you reverted it.... but I still have `{% include_cached scripts.html %}` in de default layout and `include_cached` in the `scripts.html` include my comments show perfectly 

e.g. https://luispuerto.net/blog/2018/07/23/new-web-in-jekyll/ 

Are you sure the culprit is `include_cached` and you don't have something in your side @paulfioravanti ? 

I'm asking because I also have a problem with the `include_cached` when I merged @mmistakes changes because I had this in my default layout. 

```html
{% include_cached scripts.html %}
{% include scripts.html %}
```

So de burger menu and the search icon stopped working till I removed `{% include scripts.html %}`.

**Comment by luispuerto** [comment]
Hey @paulfioravanti, 

You are right about questioning running the gem and then overriding it with my files. Anyhow... I've commented the gem and run it locally in production and I got the same result. 

I've done really few changes related to the comments, mainly CSS. So... I really don't know.
