### ISSUE TITLE
missing trailing slash in structured data

### ISSUE THREAD

**Issue by chatoo2412** [mmistakes/minimal-mistakes#1906]
## Environment

- Minimal Mistakes version: 4.13.0
- Ruby gem or remote theme version: remote
- Jekyll version: 3.7.4
- Git repository URL: https://github.com/chatoo2412/chatoo2412.github.io
- GitHub Pages hosted (if yes provide URL to site): https://chatoo2412.github.io/
- Operating system: -

## Expected behavior

Structured data don't contain trailing slashes, unlike canonical URL does.
Strictly speaking, paths with and without trailing slashes are different.
Please make it consistent.

## Steps to reproduce the behavior

https://github.com/mmistakes/minimal-mistakes/blob/c8f4820d31c6b4c605ec96f74213df007c74c7cd/_includes/seo.html#L126-L147

https://github.com/mmistakes/minimal-mistakes/blob/c8f4820d31c6b4c605ec96f74213df007c74c7cd/_includes/seo.html#L3

https://github.com/mmistakes/minimal-mistakes/blob/c8f4820d31c6b4c605ec96f74213df007c74c7cd/_includes/seo.html#L17

`seo_url` doesn't contain trailing slash but `canonical_url` does contain.

**Comment by mmistakes** [comment]
Not sure I follow where the issue is. Looking at the [output of the demo site](https://mmistakes.github.io/minimal-mistakes/) a trailing slash is on both the canonical URL and social sharing.

```
<meta property="og:url" content="https://mmistakes.github.io/minimal-mistakes/">
<meta name="twitter:url" content="https://mmistakes.github.io/minimal-mistakes/">
<link rel="canonical" href="https://mmistakes.github.io/minimal-mistakes/">
```

**Comment by chatoo2412** [comment]
Thanks for your reply.
What I'm talking about is this part:

```html
<script type="application/ld+json">
  {
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "https://chatoo2412.github.io",
  "logo": "https://chatoo2412.github.io/assets/images/cover.png"
  }
</script>

<script type="application/ld+json">
  {
  "@context": "http://schema.org",
  "@type": "Person",
  "name": "Wooram Jun",
  "url": "https://chatoo2412.github.io",
  "sameAs": ["https://github.com/chatoo2412","https://www.linkedin.com/in/chatoo2412/"]
  }
</script>
```

As you can see, `url` have no trailing slashes.

(Actually, `Organization` block is redundant if `site.social.type` is set to `Person`. I'll open it with another issue.)

**Comment by mmistakes** [comment]
Gotcha.
I've reopened an old issue to replace my hand-rolled SEO include with jekyll-seo-tag if you want to track it. 

I'm going to take another look at that as that plugin does more and has better support for for [JSON+LD meta output](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#customizing-json-ld-output). It's also better maintained than what I include in the theme.

cc/ #324
