### ISSUE TITLE
Missing subresource integrity checking for Font Awesome JS

### ISSUE THREAD

**Issue by Kristaba** [mmistakes/minimal-mistakes#1920]
It seems that the Font Awesome's javascript code is served by their CDN by default.
I am not too much used to web development, but I believe the [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) checking should be used in such case.

https://github.com/mmistakes/minimal-mistakes/blob/f4cfc87b0a4a4f3150ab47cd4491ac46834db6a1/_includes/scripts.html#L12

The hash of each version of Font Awesome files is available in  [their website](https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=svg-with-js).
So the current line should be replaced by something like:
```html
<script src="https://use.fontawesome.com/releases/v5.3.1/js/all.js" integrity="sha384-kW+oWsYx3YpxvjtZjFXqazFpA7UP/MbiY4jvs+RWZo2+N94PFZ36T6TFkc9O3qoB"></script>
```

**Comment by mmistakes** [comment]
Care to submit a pull request with the `integrity` value added?
