### ISSUE TITLE
using google-adsense 

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/minimal-mistakes#1923]
I have searches in all of the `_includes`, but was not able to find where in the theme you have used the google adsense script?

Since the theme website is monetized, do I need to remove your script to include my own? If yes, where is the location?

**Comment by mmistakes** [comment]
It's not part of the theme. I've manually added the AdSense `<script>` embed to the demo site by overriding [`_layouts/default.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_layouts/default.html#L24-L34).

**Comment by Kulbhushan-Chand** [comment]
Thanks

**Comment by I-Am-The-Great** [comment]
you can add that in `_includes/head/custom.html` too if you want it to be in the `head` section.
