### ISSUE TITLE
How to remove previous | next from pages?

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/minimal-mistakes#1927]
The previous | next link appears on posts as well as pages.
- Is there any way to make it appear on posts only?
- How can it be completely disabled?

**Repository -** https://github.com/Kulbhushan-Chand/Kulbhushan-Chand.github.io

**Following is the link, what I 'm talking about -**

![image](https://user-images.githubusercontent.com/17742733/47951913-918b2c00-df8d-11e8-8c47-bc55dadbf02b.png)

**pagination settings in _config.yml -**

![image](https://user-images.githubusercontent.com/17742733/47951941-0eb6a100-df8e-11e8-858c-ac451076a521.png)

**collections settings in _config.yml -**

![image](https://user-images.githubusercontent.com/17742733/47951953-2e4dc980-df8e-11e8-9fe6-dbcae8233953.png)

**folder structure -** 

![image](https://user-images.githubusercontent.com/17742733/47951968-6228ef00-df8e-11e8-86f4-b1be82c9d1f6.png)

**Comment by mmistakes** [comment]
It's [part of the `single` layout](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L63). There is no way to turn it off.

I'd suggest creating a variant of that layout or the [post_pagination.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/post_pagination.html) include if you want to omit those links.
