### ISSUE TITLE
Header Animation

### ISSUE THREAD

**Issue by dAmnation69** [mmistakes/minimal-mistakes#1935]
Hello Michael, 
wanted to know if it is possible to [animate ](https://codepen.io/thingir/pen/XgvQPK
)the header? if not can you guide me in the right direction.

[Reference](https://speckyboy.com/snippets-animated-headers-video-backgrounds/)

**Comment by mmistakes** [comment]
Anything is possible with a little CSS and JavaScript. If you're looking for an easy solution I don't have one.

Those reference links and similar tutorials are a good start.

**Comment by dAmnation69** [comment]
thanks for the motivation . I'll work something out

**Comment by dAmnation69** [comment]
Hello Michael, i got it to work [here](https://damnation69.github.io/), using particle.js to animate an overlay.

I have one question though. When i visit the site through a mobile device, the overlay on the hero banner seems a little off! Can you guide me on the issue?

Regards,
David

**Comment by mmistakes** [comment]
No idea, never used particle.js before.

**Comment by dAmnation69** [comment]
hi,
I worked it out. I would like to contribute to this repository. Surely would add some bling to the theme 😄
