### ISSUE TITLE
Is it possible to automatically link to pages?

### ISSUE THREAD

**Issue by antgel** [mmistakes/minimal-mistakes#1936]
Firstly, thanks for a wonderful theme. Secondly, is there a way to automatically show links to pages (as opposed to posts) in either the top or side navigation? It would be nice not to have to update the navigation whenever I add a new page.

(I have read the docs, but they are so long I might have missed this...)

**Comment by mmistakes** [comment]
There are, but the theme doesn't ship with them as they have a performance hit on build times.

I believe there are mentions of doing the same with the default theme Minima if you want to search through their issues for ideas on how to do it.

**Comment by antgel** [comment]
Thanks for the answer, indeed I was aware of it via Minima. I bit the bullet and coded the navigation manually, it's best to deliver something after all. :)
