### ISSUE TITLE
Broken link in layouts docs

### ISSUE THREAD

**Issue by cseas** [mmistakes/minimal-mistakes#1940]
The search page [example link](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_docs/10-layouts.md#search-page-layout) in the layouts docs is broken.

The file it points to doesn't exist.
There is no `search.md` in [_pages/](https://github.com/mmistakes/minimal-mistakes/tree/master/docs/_pages)

**Comment by mmistakes** [comment]
It was removed from the demo site because it uses Algolia search. The layout is still in the theme.

https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/search.html
