### ISSUE TITLE
Overlay header image in feed?

### ISSUE THREAD

**Issue by luispuerto** [mmistakes/minimal-mistakes#1942]
Hi! 

I'm wondering if it's possible to include the header image in the feed generation in anyway. 

The issue is, sometimes the only image you put to illustrate a post is the header image. However, for people that is subscribed to the page through the feed isn't getting those images because they aren't shown in the feed. I really don't know if it's possible to fix in anyway since the template is using [jekyll-feed](https://github.com/jekyll/jekyll-feed) plugin.

**Comment by mmistakes** [comment]
You might have to build your own custom feed template if **jekyll-feed** plugin doesn't do what you want. That's what I do with [my personal site](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/_layouts/atom_feed.html).

The jekyll-feed plugin does support adding images I believe. They need to be specified in your [front matter](https://github.com/jekyll/jekyll-feed#optional-front-matter) as:

```
image:
  path: path-to-your-image.jpg
```

Closing as this is a jekyll-feed question/issue.

**Comment by luispuerto** [comment]
Thanks!!! I just found out... sorry to bother 🙂
