### ISSUE TITLE
Tags and 404 page

### ISSUE THREAD

**Issue by ritayadav** [mmistakes/minimal-mistakes#1947]
If I click on Tags link or Categories link it goes to 404 page and 404 page is also not showing author details.  Please help me to solve this issues.

**Comment by mmistakes** [comment]
You need to create these pages using the appropriate layouts.

https://mmistakes.github.io/minimal-mistakes/docs/layouts/#taxonomy-archives

**Comment by ritayadav** [comment]
Thank you so much but only the 404 page is not working good with the custom domain as I think.
https://blog.maheshyadav.com.np/404

working fine if not custom domain
https://ritayadav.github.io/myOwnBlog/404

**Comment by mmistakes** [comment]
Not sure. This is a GitHub Pages concern, not the theme. Please investigate further on they end on how to setup a custom 404 page.

**Comment by ritayadav** [comment]
Ok thanks
