### ISSUE TITLE
Why links are included twice in author-profile.html?

### ISSUE THREAD

**Issue by kulbhushanchand** [mmistakes/minimal-mistakes#1948]
Hi @mmistakes 

- At this location all links have already been parsed.
https://github.com/mmistakes/minimal-mistakes/blob/7d257e4e8b05fb3cc522593fe110af6d1f841c05/_includes/author-profile.html#L51 

- But after this line onwards the links are again checked (however in another way using `author.`) https://github.com/mmistakes/minimal-mistakes/blob/7d257e4e8b05fb3cc522593fe110af6d1f841c05/_includes/author-profile.html#L59 

- Following is the `_config.yml` entry - https://github.com/mmistakes/minimal-mistakes/blob/7d257e4e8b05fb3cc522593fe110af6d1f841c05/_config.yml#L102

**Question -** 
**- Q 1. Why second time we are parsing again. This seems like redundant functionality.**
**- Q 2. Why  `rel attribute` is not included in the following line -**
 https://github.com/mmistakes/minimal-mistakes/blob/7d257e4e8b05fb3cc522593fe110af6d1f841c05/_includes/author-profile.html#L54

**Comment by mmistakes** [comment]
Backwards compatibility. `author.links` is the new and preferred way of assigning author sidebar links.

Everything that follows have been deprecated and will be removed eventually.

**Comment by mmistakes** [comment]
And missing `rel` attributes are just they... missing. The latest contributor PR looks to have missed adding it.

**Comment by Kulbhushan-Chand** [comment]
Adding `itemprop="sameAs" rel="nofollow noopener noreferrer"` to https://github.com/mmistakes/minimal-mistakes/blob/309b664cdbe08fbd5826ce4073378db9dbf1866d/_includes/author-profile.html#L54
would be fine, however doing this we are also assigning `itemprop="sameAs"` to `author.uri `and `author.email`, instead of `itemprop="url"` and `itemprop="email"` respectively.

What do you think about this?

**Comment by mmistakes** [comment]
@Kulbhushan-Chand That could be why it was left off. There's no magic bullet solution here I don't think. I would probably leave off `itemprop="sameAs"` and just add `rel="nofollow noopener noreferrer"`.

**Comment by Kulbhushan-Chand** [comment]
Would you like a PR for the same?

**Comment by mmistakes** [comment]
Sure.

**Comment by Kulbhushan-Chand** [comment]
PR created at  https://github.com/mmistakes/minimal-mistakes/pull/1959
