### ISSUE TITLE
Staticman now supports GitLab!

### ISSUE THREAD

**Issue by VincentTam** [mmistakes/minimal-mistakes#1949]
## Motivation

In `docs/_docs/05-configuration.md`, it's written that

> Note: Staticman is currently only compatible with GitHub based repositories. Support for GitLab Pages is planned but not available yet.

This is _outdated_.  https://github.com/eduardoboucas/staticman/pull/219#issuecomment-417052299 announced the launching of a public API instance https://dev.staticman.net two months ago.

Thanks to @ntsim's help, I've understood how to use his PR.  As a result, I've created my 2nd demo Staticman GitLab Pages at https://vincenttam.gitlab.io/bhdemo ([source](https://gitlab.com/vincenttam/bhdemo), served by @staticmanlab) yesterday (in order to demonstrate my recent PR to the Hugo theme halogenica/beautifulhugo#222).

![Staticman v3 on GitLab](https://user-images.githubusercontent.com/5748535/48619278-4533e900-e99c-11e8-9b43-c25f5939401b.png)

Coincidently, Staticman's main API is facing eduardoboucas/staticman#227.  This is also discussed in #1842.  The result of #1842 is to allow users to customize their own API instance.  In fact, on GitLab, such problem *doesn't* exist because the "accept invitation" mechanism *doesn't* exist---another user can immediately start contributing once invited.  Therefore, eduardoboucas/staticman#219 can, unexpectedly, solve #1842, apart from eduardoboucas/staticman#22.

From [my GitLab repo](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/1/) setup guide, one can setup Staticman to work with GitLab.

## Suggestion

Please update this notice to

> Note: Staticman is currently compatible with GitHub and GitLab based repositories. Support for GitLab Pages is already available.

**Comment by mmistakes** [comment]
Care to submit a PR changing the stuff text?
