### ISSUE TITLE
Facebook/Twitter/G+ Sharing broken

### ISSUE THREAD

**Issue by zoeycluff** [mmistakes/minimal-mistakes#195]
When you click on the share links, the links load as "https://plus.google.com/share?url=/play/" without the domain name. I have a URL in the _config.yml, and don't know what to do to make sharing work. any tips? thanks. 

# Site wide configuration

title:            Zoey's World
locale:           en_US
url:		      zoeyrae.com

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

# Site owner
owner:
  name: Zoey Cluff
  avatar: me.jpg
  bio: "Girl on a Mission."
  email:
  disqus-shortname:
  twitter: zoeycluff
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: 5549782/zoey-cluff   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: zoeycluff
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

**Comment by mmistakes** [comment]
`url` in your `_config.yml` is missing the `http://`. Should be

```
title: Zoey's World
locale: en_US
url: http://zoeyrae.com
```

**Comment by zoeycluff** [comment]
Same thing. even with the http. Also, I added my github username and it's not showing up. did a jekyll build, rebooted the PC and started/stopped the service I made. 

# Site wide configuration

title:            Zoey's World
locale:           en_US
url:		http://zoeyrae.com      


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6


# Site owner
owner:
  name: Zoey Cluff
  avatar: me.jpg
  bio: "Girl on a Mission."
  email: zoey.
  disqus-shortname:
  twitter: zoeycluff
  facebook: #username
  google:
    plus: #username
    analytics: UA-51898388-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: zoeycluff
  stackoverflow: 5549782/zoey-cluff   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: zoeycluff
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
