### ISSUE TITLE
Homepage not showing posts

### ISSUE THREAD

**Issue by claudiuconstantin** [mmistakes/minimal-mistakes#1950]
I am trying to create a new Jekyll (up to date version) site with Minimal Mistakes theme installed as a gem (latest version). I went through all the steps in the [Getting started](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/) guide ("Starting from jekyll new"), but the default Recent articles homepage doesn't seem to pick up the posts in the `_posts` folder. What can cause this issue, is there any additional configuration necessary?

I created a sample repo [here](https://github.com/claudiuconstantin/minimal-mistakes-test).

## Environment

- Minimal Mistakes version: 4.13.0
- Ruby gem or remote theme version: [4.13.0](https://rubygems.org/gems/minimal-mistakes-jekyll/versions/4.13.0)
- Jekyll version: 3.8.5
- Git repository URL: https://github.com/claudiuconstantin/minimal-mistakes-test
- GitHub Pages hosted (if yes provide URL to site): no, running locally
- Operating system: Windows 10

## Other

![image](https://user-images.githubusercontent.com/1537573/48669951-b64bdb80-eb17-11e8-83d1-bc2878d22779.png)

**Comment by ztou** [comment]
same issue here

**Comment by mmistakes** [comment]
Yes, more configuration is required. You need to configure Jekyll's pagination to have posts show. Please consult the documentation for the [home page layout](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#home-page-layout).

Closing as this has been addressed in duplicate issues: #1512, #1535,
