### ISSUE TITLE
How to create seperate posts for different pages?

### ISSUE THREAD

**Issue by lemikistu** [mmistakes/minimal-mistakes#1955]
Hi i already have Projects page where my .md files(posts) are shown by their tags.However i added Blog page as well and i like to put blog .md posts there.So i want to split blog and projects posts and don't want for instance project posts to be seen over blog page or vice versa.Right now i can seen the _posts folder .md content on both pages.I created additional blog.md under _pages  folder and i can see the blog tab and i made new _blog folder and put my blog post there but that last bit didn't work.How can i resolve this?My repo is here: https://github.com/lemikistu/lemikistu.github.io. Thanks.

**Comment by mmistakes** [comment]
Please ask Jekyll questions in their help forum. Your issue isn’t s theme one.

http://talk.jekyllrb.com/
