### ISSUE TITLE
Add a social network?

### ISSUE THREAD

**Issue by siadevelopment** [mmistakes/minimal-mistakes#196]
is it possible to add Beme to the list of social networks on the left. which file do I add it to?

Thanks

**Comment by mmistakes** [comment]
Yes it's possible to add any social network you want. Take a look at the [`_author-bio.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/_author-bio.html) include. You'll see all of the social networks the theme currently supports and how they're wrapped in Liquid if statements. You can simply add the link without that if you want.

For the icons I'm using [Font Awesome](http://fontawesome.io/) so you'll need to check if it has one for the social network you're hoping to add.
