### ISSUE TITLE
Add instructions for running in Docker

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#1968]
## Motivation

Other than https://github.com/mmistakes/minimal-mistakes/issues/1162, I didn't see anyone trying to host mmistakes on Docker. Speaking from experience, getting a local Jekyll environment can be pretty daunting, especially, if like me, web development isn't their strong suit.
I've a [fairly minimal site](https://github.com/asarkar/non-compos-mentis) hosted on Netlify (they are awesome BTW). I can stand up the site locally in seconds with a single Docker command and make changes dynamically.

## Suggestion

Having a section in the docs that describes how to get up and running in minutes could be very useful. I've no problem if you choose to link to my blog, but it's not a shameless plug, so if you don't, that's not a problem.

Thanks for maintaining mmistakes.

**Comment by mmistakes** [comment]
This sounds more appropriate for Jekyll/Ruby than with the theme.

**Comment by mmistakes** [comment]
Maybe the Jekyll docs would benefit from the addition.

https://jekyllrb.com/docs/continuous-integration/buddyworks/

**Comment by asarkar** [comment]
You're technically right, but running Jekyll is a bigger topic than running mmistakes, and there are many tutorials on running Jekyll. My thought behind creating this ticket was that someone would clone mmistakes, run a Docker command, and play around with difference configurations to help them understand how it works (to some extent). As far as I understand, that's currently not possible without first hosting the site someplace in the cloud, which is kind of a chicken and egg problem. If they don't have a site yet, they don't really need to find hosting, assuming running locally is difficult and not understood well.

**Comment by mmistakes** [comment]
The preferred method isn't cloning the theme repo. That introduces all kinds of maintenance and pulling for future theme update headaches... especially for those new to Jekyll, git, etc.

I still think this is better left as a Jekyll "how to" than something I directly want to mention in the theme. Especially since I will be the one supporting questions and concerns related to it. And I'd rather not endorse something I don't personally use our have experience with, that being Docker.

**Comment by asarkar** [comment]
Fair enough, I'm closing this ticket. On a separate note, what is the recommended way to create tags that are best represented by more than one words? `_`, `-`, or CamelCase? Or just stick to single-worded tags?
