### ISSUE TITLE
Just what is a gem file?

### ISSUE THREAD

**Issue by electronart** [mmistakes/minimal-mistakes#1970]
## Motivation

I just wanted to write up some API Documentation and make a presentable static page.

### Background

As a new user of Github Pages, naturally I wanted to give my page a better look than the default templates can provide.

Unfortunately a lot of assumptions about the knowledge of the user are made immediately within Github, casually bringing up the terminology 'Jekyll themes' - Something that a new user like myself is not familiar with (but is more than happy to familiarize themselves with, given the chance)

I wanted to configure my Github Page to use the minimal-mistakes theme. So I added `mmistakes/minimal-mistakes` to the `_config.yml` that appeared in my project after setting up Github Pages following the instructions posted [here](https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/)

The page rendered Okay but I couldn't get any menu items to appear, despite following your instructions to add a navigation menu  [here](https://mmistakes.github.io/minimal-mistakes/docs/navigation/)

So I began to think that perhaps there are additional installation steps. So I went to your installation page, and immediately there is a lot of mention of editing 'Your Gem File' .. Gem File? Where? And on another page there is a mention of `Replace gem "jekyll" with:...` - Again, nothing like this has appeared in [my repository](https://github.com/electronart/SearchCloudOne-API-Docs) after setting up Github Pages.

Unfortunately, googling for things such as 'What is a gem file' 'Where is my gem file' does not provide any real hints towards what a user should be doing. It is very difficult to find information on this matter.

## Suggestion

It would be great if there was some introduction to what these files are and where they are, before we are told to edit them, or at least some sort of pointer for newbies like myself.

**Comment by mmistakes** [comment]
Check Jekyll's documentation. The theme assumes you're familiar with its use and concepts.

They provide way more information on Ruby and such than I could ever with bulking up the theme docs.

https://jekyllrb.com/docs/ruby-101/
