### ISSUE TITLE
Security vulnerability due to a npm script ⚠️

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/minimal-mistakes#1977]
By the time this issue was filed, GitHub may have reporter you about the recent **security vulnerability** detected in a npm script - `event-stream` `flatmap-stream`. 

Here is the screenshot about my website using minimal-mistakes theme -

![image](https://user-images.githubusercontent.com/17742733/49058197-fbaf8d80-f228-11e8-9934-0596cb5b0fdb.png)

**To know in detail -** 
  - https://github.com/dominictarr/event-stream/issues/116
  - https://www.theregister.co.uk/AMP/2018/11/26/npm_repo_bitcoin_stealer/

**Possible solution -** We may need to revert back to previous version of script.

**Comment by mmistakes** [comment]
I don't think we have to do anything. Looks like NPM has removed the malicious version.

```terminal
\minimal-mistakes>npm ls event-stream flatmap-stream
minimal-mistakes@4.14.1 \minimal-mistakes
`-- npm-run-all@1.8.0
  `-- ps-tree@1.1.0
    `-- event-stream@3.3.4
```

**Comment by mmistakes** [comment]
Regardless I updated the NPM dependencies used as part of the `build:js` scripts when developing the theme. They were quite old.

Doing so, looks like `event-stream` is no longer used so we should be in the clear now.

```terminal
> npm ls event-stream flatmap-stream
minimal-mistakes@4.14.1 \minimal-mistakes
`-- (empty)
```
