### ISSUE TITLE
How to create links to the subsections of the same page?

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#1979]
I've some blogs [posts on algorithms](https://blog.asarkar.org/graphs-data-structures/2018-11-27-week-1-optional/) that cite references to other blogs/papers. In my blog, I'd like to link to references in the same page; how do I do that? I know how to create external hyperlinks, but not how to create links to the subsections of the same page.

**Comment by asarkar** [comment]
@Kulbhushan-Chand that link is useful, but not exactly. What I’m looking for is link to individual references, like so:
“This is a reference to an item in the References section [1]”
...
References:
[1] Some seminal work

In the above example, I’d like `[1]` to be a hyperlink.

**Comment by Kulbhushan-Chand** [comment]
You must be talking about footnotes. Try this - 

```
This is a reference to an item in the References section[^1]
this is some paragraph

References:
[^1]: Some seminal work
```
You can also use test instead of number 1 like this -

```
This is a reference to an item in the References section[^ref]
this is some paragraph

References:
[^ref]: Some seminal work
```

**Comment by mmistakes** [comment]
Closing as this is a Markdown concern and not theme related. Please use Stackoverflow or [Jekyll's help forum](http://talk.jekyllrb.com/) for these sorts of questions.
