### ISSUE TITLE
Button hyperlink in feature row

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/minimal-mistakes#1980]
Hi @mmistakes ,

_I asked here, because you have created the button class, and I think you may be of better help then stackoverflow_ 

On the homepage  of my [website](https://kulbhushan-chand.com/) I have used feature row.

The cursor changed to hand anywhere in the vicinity of the picture, but clicking only animates the button 
but doesn't goes to linked page. 

**My doubts -** 
-  How can I make the cursor change only on the button?
- The above effect was different from minimal mistakes, because I have added active class to button to animate the button. [Link to location](https://github.com/Kulbhushan-Chand/Kulbhushan-Chand.github.io/blob/651d5ea613fe460dbf6b10a1bd526c16809b1f24/_sass/minimal-mistakes/_buttons.scss#L37).
  - Removing this class reverts to default minimal-mistake behaviour, but still the cursor changes on the vicinity, but just on the button.  

  
  
![pic](https://user-images.githubusercontent.com/17742733/49158375-00b72e80-f348-11e8-847f-4e6bd088746c.jpg)

**Comment by mmistakes** [comment]
Through CSS. Look back through the commits, I adjusted things to [make the entire block a link](https://github.com/mmistakes/minimal-mistakes/pull/1864) (which makes it easier to click as users expect the image and headline to be clickable... not just the button).

There's a pseudo element on the button that is absolutely positioned and fills the parent's container to make this work. You'll likely need to add some additional `:hover` declarations to the sibling selectors if you want them styled differently.

**Comment by Kulbhushan-Chand** [comment]
Thanks for the help.
I'll make the required changes.

**Comment by Kulbhushan-Chand** [comment]
**Sorry for re-opening this issue,**

I tried but was not able to figure out that why adding `active `class to the [button ](https://github.com/Kulbhushan-Chand/Kulbhushan-Chand.github.io/blob/ce525849ce88a4d61326ceee9ec7b1f9f4868561/_sass/minimal-mistakes/_buttons.scss#L37)- 
```
  &:active {
    transform: scale(0.95);
  }
```
breaks the functionality.

The url opens only if I click on the button, in-other case the button just animates. 
Deleting the `active` restores the functionality, but I also want the transform effect to be there.

_Looking for your kind reply.._ 

**Following is screen recording of [homepage ](https://kulbhushan-chand.com/) -** 

![2018-11-30_11-28-26](https://user-images.githubusercontent.com/17742733/49271321-184efe00-f493-11e8-92b6-b9dc31dbb0d3.gif)

**Comment by mmistakes** [comment]
Please use a forum like [Stackoverflow](https://stackoverflow.com/questions/tagged/css) for these sorts of questions. This is 100% CSS related and not at all specific to the theme.

I can't possibly answer all general web development questions.

**Comment by Kulbhushan-Chand** [comment]
@mmistakes Sorry for my impatience. 
Heading to Stackoverflow
