### ISSUE TITLE
Toggle menu issue on minimal mistakes website

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/minimal-mistakes#1987]
## Environment

**On minimal mistakes website**

## Expected behavior

**The toggle menu should close**

## Steps to reproduce the behavior

Click few times on hamburger icon (_I managed to catch the bug **on fourth click**_),
I have checked on this particular page -
https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

![2018-12-05_13-24-20](https://user-images.githubusercontent.com/17742733/49498571-7c0d6880-f891-11e8-8b6f-0124dc8272d2.gif)

**Comment by mmistakes** [comment]
The menu doesn't currently close when clicking outside of the drop down nav. There was an old issue to build this feature in. I don't have a fix for it, but if someone wants to take it, have at it.

**Comment by mmistakes** [comment]
Also seems to only happen in Chrome.

**Comment by Kulbhushan-Chand** [comment]
Same thing with follow button, clicking outside does not closes the menu.
![image](https://user-images.githubusercontent.com/17742733/49562193-702caf80-f940-11e8-905a-ca3b95f499fa.png)
