### ISSUE TITLE
Breadcrumbs not working

### ISSUE THREAD

**Issue by Sashuu6** [mmistakes/minimal-mistakes#1990]
I enabled breadcrumbs and added jekyll archives for creating the pages. But, it won't work. I am getting a 404 error that page. Please help.

**Comment by mmistakes** [comment]
Please add a link to your repo as I can only guess what your issue is.
Most likely you need to create the pages it's trying to link to or you haven't properly setup the config to use JA pages instead of the Liquid `#refs`.

**Comment by Sashuu6** [comment]
Sorry, 
I think I didn't clearly convey the point. 
I am hosting my site via Github pages. First I used Jekyll-archives for creating categories. But, it didn't work. I went through the issues and found that you said Github has not made the gem whitelisted. So I moved to liquid instead. Then, I created a folder "categories" and created file index.html. After that, I added code present in "_layouts/categories.html". Then test run the site. I got the page, but it is broken. I think you recreate the bug by visiting the site and clicking on categories. By the way, Thank you for the theme and your immense support. 
Website: https://www.sashwat.in
Github Repository: github.com/sashuu6/Blog

**Comment by mmistakes** [comment]
Don't think you gave it enough time to build on GitHub Pages. Everything seems to be working for me.

To test I:

1. Went to this page: https://www.sashwat.in/linux/rhel/things-to-do-after-installing-rhel-7/
2. Click on the "Linux" breadcrumb, which goes to this working page https://www.sashwat.in/categories/#linux

Closing as it looks like you've fixed the issue.

![image](https://user-images.githubusercontent.com/1376749/49527258-8aeb1f80-f87f-11e8-9f06-194630b2142e.png)

**Comment by Sashuu6** [comment]
I have fixed it. Thank you for your support.
