### ISSUE TITLE
Show image header on homepage

### ISSUE THREAD

**Issue by Funeoz** [mmistakes/minimal-mistakes#1999]
Is it possible to show the header images on the homepage? Because It seems a bit "liveless"

**Comment by mmistakes** [comment]
Yes. Works like any other post or page. Add the appropriate YAML front matter.

**Comment by mmistakes** [comment]
https://mmistakes.github.io/minimal-mistakes/docs/layouts/#headers

**Comment by Funeoz** [comment]
Thank you !
