### ISSUE TITLE
 add: gem 'json' to Gemfile #8 

### ISSUE THREAD

**Issue by open-smc** [mmistakes/minimal-mistakes#200]
Otherwise jekyll errors out with:
/usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/filters.rb:2:in `require': cannot load such file -- json (LoadError)

I am running this on a CentOS 7 server

**Comment by mmistakes** [comment]
Are you running Jekyll with `bundle exec jekyll build` and `bundle exec jekyll serve`? And have you installed/updated all the gems?

**Comment by open-smc** [comment]
I forgot to mention the problem with:
gems: [jekyll-paginate]
I had to comment out the line:
#paginate: 4
Not a great fix but I am a linux sysadmin not a ruby programmer.

I commened out my two changes and there is the output:
bundle exec jekyll build
Configuration file: /home/www/opensmc.net/jekyll-experiment/_config.yml
       Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
            Source: .
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/filters.rb:2:in `require': cannot load such file -- json (LoadError)
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/filters.rb:2:in `<top (required)>'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/renderer.rb:48:in `run'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/excerpt.rb:76:in `output'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/excerpt.rb:60:in `to_s'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/document.rb:367:in `to_liquid'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/renderer.rb:37:in `run'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/site.rb:171:in `block (2 levels) in render'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/site.rb:169:in `each'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/site.rb:169:in `block in render'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/site.rb:168:in `each'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/site.rb:168:in `render'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/site.rb:59:in `process'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:60:in `build'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:35:in `process'
	from /usr/local/share/gems/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/local/share/gems/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/share/gems/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/share/gems/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/share/gems/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/share/gems/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/share/gems/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/share/gems/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

**Comment by mmistakes** [comment]
The theme doesn't use Jekyll's pagination. Have you made modifications to the theme to use that or are you using someone else's fork? In Jekyll 3.0 there's a deprecation warning for pagination because it is no longer included and you need to add `jekyll-paginate` to your `Gemfile`.

https://talk.jekyllrb.com/t/announcement-retiring-jekyll-paginate/1004/17
