### ISSUE TITLE
Disqus comments map back to the wrong blog post

### ISSUE THREAD

**Issue by MV10** [mmistakes/minimal-mistakes#2005]
I have a GitHub Pages blog and sometime during the past few months, Disqus comments posted to any article always wind up on the first, oldest article on the site. Comments used to work and I didn't change anything in the blog configuration or in my Disqus configuration, so I'm not really sure where to start looking. Comments posted prior to this problem still show up on the correct pages, and each page still shows a Disqus comment input box.

The configuration file is here -- you can see I include `comments: true` in the page defaults.

https://github.com/MV10/mv10.github.io/blob/master/_config.yml

The public version of the site is:

https://mcguirev10.com

**Comment by mmistakes** [comment]
Disqus maps comments to the URL of the post. If something changed there it could get confused.

Pretty sure this has zero to do with the theme. I haven't used Disqus in some time, but they used to have a way of seeing what comment threads went to which posts. That would help you identify why the mapping is off.
