### ISSUE TITLE
How to decrease the size of header video on a page?

### ISSUE THREAD

**Issue by I-Am-The-Great** [mmistakes/minimal-mistakes#2009]
Dear sir,

I do assure the following:
  - I have the latest versions of Jekyll and Minimal Mistakes 
    installed by running `bundle update`.
  - I thoroughly had read the theme's documentation at
    https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/
  - I searched all issues at https://github.com/mmistakes/minimal-mistakes/issues 
    for solutions and to avoid duplication.

I have started using your theme minimal-mistakes recently, I liked it very much thanks for providing such a good theme to use. I wanted to add custom header images and videos on different pages, I added an overlay header image, [at one page of my site](https://thegreat.ml/projects/1 ) [(file here)](https://github.com/I-Am-The-Great/I-Am-The-Great.github.io/blob/master/_projects/1.md ) but when I added a video header on these [1<sup>st</sup>](https://thegreat.ml/projects/2/ ) [(file here)](https://github.com/I-Am-The-Great/I-Am-The-Great.github.io/blob/master/_projects/2.md ) and [2<sup>nd</sup>](https://thegreat.ml/projects/3/ ) [(file here)](https://github.com/I-Am-The-Great/I-Am-The-Great.github.io/blob/master/_projects/3.md ) pages the video has too much height, is there a way to reduce the height of the video like to that the height of image at [here](https://thegreat.ml/projects/1 ), without or with changing the width?

And thanks again for the theme.

**Comment by I-Am-The-Great** [comment]
Is anyone here, from whom I may get the answer to my question?

**Comment by justinrummel** [comment]
If your question is asking the theme to modify the video files, I don’t believe that is possible. You would need to format the video to fit the proper dimensions. 

If you are looking to adjust the theme’s dimensions for the header, you can override the values by modifying the assets/css/main.scss

See https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/

**Comment by mmistakes** [comment]
@I-Am-The-Great there is no way to "configure" the size of a header video. They are designed to fill the full width of the screen (see examples below). The larger the screen, the taller the video is going to be (well depending on the source video's proportions).

Sounds like you'll want to move the video into the body of the content where it won't display as large.

**Desktop:**

![screen shot 2019-01-01 at 6 43 57 pm](https://user-images.githubusercontent.com/1376749/50577389-56727100-0df5-11e9-96bc-f9dae4b672c5.png)

**Tablet:**

![screen shot 2019-01-01 at 6 44 37 pm](https://user-images.githubusercontent.com/1376749/50577392-596d6180-0df5-11e9-9f57-be8fd97edec7.png)

**Mobile:**

![screen shot 2019-01-01 at 6 44 52 pm](https://user-images.githubusercontent.com/1376749/50577393-5d997f00-0df5-11e9-9a57-554eb898c31f.png)

**Comment by I-Am-The-Great** [comment]
Oh, so I will move the video to the contents section and put that in between text in adequate space, that may look better in a computer I think. And, thank you for your kind help; I like your theme 'minimal-mistakes' of Jekyll very much, thanks for the theme also. And sorry if this question was childish.

**Comment by I-Am-The-Great** [comment]
By the way please tell me how much would you rate my website between 1 to 10.
