### ISSUE TITLE
Custom Codeblock "linenos" start 

### ISSUE THREAD

**Issue by dAmnation69** [mmistakes/minimal-mistakes#2015]
Hi Sir,

`{% highlight python linenos %}` is the valid syntax and the numbering for each code block starts from `1`. Is there anyway I give a custom line number to start with ??

...... Thanks in advance.

**Comment by mmistakes** [comment]
@dAmnation69 Don't think so. This is a question is better for the Jekyll maintainers as the `{% highlight %}` tag is part of their project. I'd search around their issues or raise your own.
