### ISSUE TITLE
Turn off masthead

### ISSUE THREAD

**Issue by halperta** [mmistakes/minimal-mistakes#2017]
Is there any way to turn off the top menu for a single page in the site? I would like the homepage to be a splashpage, while all other pages follow the normal format. I'm not a web designer and don't have much experience with jekyll or css, so apologies if there is an obvious answer to this. 

Here are my links:

http://www.halperta.com/jicr-test/
https://github.com/halperta/jicr-test

I very cleverly tried adding "masthead: false" to the yaml but it did not work, unsurprisingly.

Thanks!

**Comment by mmistakes** [comment]
No sorry, it's part of theme and shows on all pages.

You could customize the [`default.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/default.html) layout to only show the masthead include by wrapping the masthead include like this:

```liquid
{% unless page.masthead == false %}
  {% include_cached masthead.html %}
{% endunless %}
```

Then adding `masthead: false` like you have will stop the masthead from being added to the page.

**Comment by halperta** [comment]
Amazing. That worked perfectly. Thank you so much!

**Comment by kflynn** [comment]
I know this is four years old, but it was still tremendously helpful. Any appetite for adding this patch for `masthead: false` to the core minimal-mistakes? 🙂
