### ISSUE TITLE
Is there a way we can include custom html under posts section ?

### ISSUE THREAD

**Issue by rajkstats** [mmistakes/minimal-mistakes#2018]
I tried doing that by putting it custom.html  under _include and in markdown under posts, tried to include it. It is not rendering properly. Is there a way we can do that?

**Comment by mmistakes** [comment]
Yes, depending on what [layout](https://github.com/mmistakes/minimal-mistakes/tree/master/_layouts) you're using to display posts you can just add whatever HTML you want.

**Comment by rajkstats** [comment]
Got it. Thanks @mmistakes
