### ISSUE TITLE
How to make your foo? Please help me.......

### ISSUE THREAD

**Issue by TOT0RoKR** [mmistakes/minimal-mistakes#2024]
![image](https://user-images.githubusercontent.com/24751868/50936175-f98c5000-14b1-11e9-99fb-8d9e59e01532.png)

I want this page :

![image](https://user-images.githubusercontent.com/24751868/50936367-c1394180-14b2-11e9-9416-cb3fca7451c2.png)

And I want disqus comments :

![image](https://user-images.githubusercontent.com/24751868/50936426-fe053880-14b2-11e9-9420-eb6e2f701f57.png)

![image](https://user-images.githubusercontent.com/24751868/50936453-11b09f00-14b3-11e9-8203-b93ac93e4880.png)

I try all week, but it does not work. Please help me. T.T

**Comment by TOT0RoKR** [comment]
![image](https://user-images.githubusercontent.com/24751868/50936561-8a176000-14b3-11e9-96cd-30981c87658b.png)

**Comment by mmistakes** [comment]
Copy this page for the posts by year layout.

https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_pages/year-archive.md

As far Disqus comments your either have your Disqus account misconfigured or you haven't enabled `production` environment when building your site. Check the documentation site, I explain how to enable this.

**Comment by TOT0RoKR** [comment]
Thank you for your comments.

But I already do it.
![image](https://user-images.githubusercontent.com/24751868/50964371-74855300-1512-11e9-952b-08b314ebce1a.png)

And It's working well.
![image](https://user-images.githubusercontent.com/24751868/50964425-97176c00-1512-11e9-99f0-706958b1a82e.png)

I want these(social share, prev or next page, category list, last update).
![image](https://user-images.githubusercontent.com/24751868/50936367-c1394180-14b2-11e9-9416-cb3fca7451c2.png)


Why my tail of posts different between then user posts. T.T

**Comment by mmistakes** [comment]
Share linkes, category list, and next previous only show on the actual posts. They're not part of the "posts" archive layout because that would make much sense.

**Comment by TOT0RoKR** [comment]
Oh! I explained to you that you misunderstood. Please see the end of this post: 

https://tot0rokr.github.io/kernel%20debugging/linux-arm64-build/

End of posts do not show this layout:

![image](https://user-images.githubusercontent.com/24751868/50936367-c1394180-14b2-11e9-9416-cb3fca7451c2.png)

**Comment by TOT0RoKR** [comment]
OMG!!!! I FIND IT NOW!!!!! THANK YOU!!
