### ISSUE TITLE
Invalid HTML tags in breadcrumb

### ISSUE THREAD

**Issue by chatoo2412** [mmistakes/minimal-mistakes#2025]
## Environment

- Minimal Mistakes version: 4.14.2

## Expected behavior

Valid HTML tags

## Steps to reproduce the behavior

https://github.com/mmistakes/minimal-mistakes/blob/a974e457127c42ef0c1f66e8bb036bf9a708f806/_includes/breadcrumbs.html#L16-L38

`<ol>` has `<span>` as its children which is invalid.

I tried to implement the seperator using CSS, but it uses a Jekyll variable `site.data.ui-text[site.locale].breadcrumb_separator`.
Inline style works, but ugly.

```html
<style>
.breadcrumbs ol > li:not(:first-child)::before {
  content: ' {{ site.data.ui-text[site.locale].breadcrumb_separator | default: "/" }} ';
  display: inline;
}
</style>

<nav class="breadcrumbs">
  <ol>
    <li>home</li>
    <li>cat1</li>
    <li>cat2</li>
    <li>post</li>
  </ol>
</nav>
```

What do you think?

**Comment by mmistakes** [comment]
That could work. In all honesty breadcrumbs are still in beta and are messy and are difficult to get working if you don't configure everything correct, add the category pages, etc.

I probably shouldn't have even added it to the theme and is something I've been thinking about removing.
