### ISSUE TITLE
Font Awesome Failed Checks

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#2030]
## Environment

- Minimal Mistakes version: 4.15
- Ruby gem or remote theme version: gem

It looks like the hash for Font Awesome has been changed, thus integrity checks are failing.
![n/a](https://d3vv6lp55qjaqc.cloudfront.net/items/310B3g282N3s172Y381f/Image%202019-01-17%20at%201.27.41%20PM.png?X-CloudApp-Visitor-Id=205743)

https://fontawesome.com/start has:
``` xml
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
```

vs. the hash at:
https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/scripts.html#L12

**Comment by mmistakes** [comment]
Hash in the theme looks correct to me....

![image](https://user-images.githubusercontent.com/1376749/51346658-30430700-1a6c-11e9-939b-9a2af21230c4.png)

FA 5.6.0 SVG 

```
<script defer src="https://use.fontawesome.com/releases/v5.6.0/js/all.js" integrity="sha384-z9ZOvGHHo21RqN5De4rfJMoAxYpaVoiYhuJXPyVmSs8yn20IE3PmBM534CffwSJI" crossorigin="anonymous"></script>
```

FA 5.6.0 SVG [used in the theme](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/scripts.html#L12)

```
<script defer src="https://use.fontawesome.com/releases/v5.6.0/js/all.js" integrity="sha384-z9ZOvGHHo21RqN5De4rfJMoAxYpaVoiYhuJXPyVmSs8yn20IE3PmBM534CffwSJI" crossorigin="anonymous"></script>
```

I think you're looking at the webfont version of the FA script and not the SVG.

**Comment by mmistakes** [comment]
MM demo site appears to be working fine with no failed integrity check warnings in the console.
