### ISSUE TITLE
Unable to display comment form with staticman v3

### ISSUE THREAD

**Issue by cloudwheels** [mmistakes/minimal-mistakes#2034]
I've read #2031 
I'm unable to get a static man comment form to show up.
My repo is here:
https://github.com/hortigraph/hortigraph.github.io/
I've authorised the v3 staticman app

In my _config.yml
I've enabled staticman_v2 as provider. 
comments: true is defaulf front matter for my collection "rhs"

1) I am unclear from the documentation about whether the endpoint property should be the full URL or the repo & branch are appended., ie should it be:
"https://dev.staticman.net/v3/entry/github/hortigraph/hortigraph.github.io/master/"

2) The documentation says:

> Bewteen v3 and /entry, one needs to input a Git service provider (either github or gitlab). 

The staticman site suggests otherwise, ie. the provider is AFTER v3/entry/ - I guess this is the correct version and docs need an update?

There's a few issues popping up by the minute on the staticman site about the new v3 app, so could just be dancing along the bleeding edge here and it may be a staticman issue, but it would be great to get some pointers on the correct set up for the theme.

**Comment by cloudwheels** [comment]
An empty comment section is being generated, but no input form: do I need to  add a form myself?

```html
<div class="page__comments"> 
   <section id="static-comments">
   </section>
</div>
```

**Comment by mmistakes** [comment]
As mentioned in the other issue, I haven’t used v3 nor did I work on the pull request to add it. I probably won’t be much help because of this.

The documention is lacking because of this. You’d be better off looking at the [source code](
https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments.html#L53) to see what it accepts. Checking there you’ll see `endpoint` is the full URL as you have above.

ccing @maxime-michel as he added the PR that added the Staticman endpoint config.

**Comment by cloudwheels** [comment]
@sseneca can I please ask whether you got staticman v3 running after #2031

**Comment by cloudwheels** [comment]
@mmistakes many thanks for the quick response and whilst I'm here ABSOLUTELY HUGE THANKS for all your amazing work with this repo - she's a beauty!
Will keep track & contrib if I can.

**Comment by maxime-michel** [comment]
I've never used v3 either, what does it bring to the table?

With v2 you'd want the `endpoint` property to look something like `https://your-private-staticman-deploy.heroku.com/v2/entry/`.

**Comment by sseneca** [comment]
> @sseneca can I please ask whether you got staticman v3 running after #2031

Yeah, I did. Extract of `_config.yml`:

```
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment by {fields.name}"
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "/_data/comments/{options.slug}" # (default)
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # (default) "timestamp-seconds", "timestamp-milliseconds"
  endpoint               : "https://dev.staticman.net/v3/entry/github/" # URL of your own deployment with trailing slash, will fallback to the public instance
```

Otherwise be sure to remove the old v2 `staticmanapp` as a contributor and install the v3 app to the correct repo. Then things should work fine.

**Comment by sseneca** [comment]
> I've never used v3 either, what does it bring to the table?

v2 was getting rate limited, see https://github.com/eduardoboucas/staticman/issues/243#issue-389697095. v3 fixes this because now it's an app rather than a GitHub user.

**Comment by cloudwheels** [comment]
LINE 30 of _includes/comments.html
`        {% if site.repository and site.staticman.branch %}`

need to be 
`        {% if site.repository and site.comments.staticman.branch %}`

**Comment by cloudwheels** [comment]
There's a bit of fiddling to do to get the form appearing and talking to the v3 staticman API / github app. Unfortunately I'm getting 500 errors back, which may be the config or may be the staticman api. 
There's seems to be a bit of confusion around how _config.yml and staticman.yml are used (by the theme to generate the POST request and by the staticman API itself), and I think there's a PR needed around the docs for this at least.
Not quite at the bottom of it yet but will do my best to feedback and put in a PR if I can.

**Comment by sseneca** [comment]
> @sseneca did you need to make this change, or should the site.staticman.branch key pickup from staticman.yml (I am a complete Jekyll noob)

I didn't touch anything else. All I did was add `staticman.yml` and make the changes I mentioned above in `_config.yml`.

**Comment by VincentTam** [comment]
@cloudwheels and all Sorry for introducing this error in #1956.  You're right about the v3 URL: it should be like

 
   https://endpoint/v3/entry/git{hub|lab}/user/repo/branch/property

**Comment by cloudwheels** [comment]
@VincentTam no probs: it made for a fun Saturday night and a few peoples' issues with the v3 api got fixed in the process :)
I will close this issue now as it's chatter and my problem is resolved, but have created #2036 to follow up.

**Comment by VincentTam** [comment]
Hi everyone,

I've just corrected the documentation about Staticman v3 URL scheme.  Sorry for the confusion over these few months.  In the updated documentation, I've added a sample config and a URL to the relevant Staticman PR for reference.

**Comment by slowbreathing** [comment]
Is there complete documentation for getting it to work with Jekyll based Github blog. I could never get it to work.

**Comment by VincentTam** [comment]
> Is there complete documentation for getting it to work with Jekyll based Github blog. I could never get it to work.

@slowbreathing Since everyone is using a different version, it's hard to have one.  For a self-contained starter, you may try https://github.com/daattali/beautiful-jekyll#staticman-comments.  An illustrated version of this would be the second section of https://github.com/einsteinpy/blog.einsteinpy.org/issues/12.

For a working example of MM + Staticman, you might see https://lstu.fr/mmsm19 ([source](https://lstu.fr/mmsm0)).

**Comment by slowbreathing** [comment]
i am using leonids theme. here is the error i get. :404},"errorCode":"GITHUB_WRITING_FILE"}

**Comment by slowbreathing** [comment]
staticman v3

**Comment by VincentTam** [comment]
@slowbreathing It would be better if you can give us a link to your repo: 
https://github.com/slowbreathing/slowbreathing.github.io, so that we can have a look.

Please take a look at [my article about Staticman errors](https://vincenttam.gitlab.io/post/2018-12-25-staticman-repo-setup-errors/).  It gives possible reasons for different types of errors.  You may also try the web developer tools in a modern web browser to see what's wrong with your requests.

**Comment by slowbreathing** [comment]
link to my repo is https://github.com/slowbreathing/slowbreathing.github.io

**Comment by audipen** [comment]
@cloudwheels , is this 'https://github.com/hortigraph/hortigraph.github.io/blob/master/_config.yml' the final working version of your config with v3 of the staticman API?
I have hosted staticman on heroku and I'm trying to get it working on a 'minimal mistakes' fork but can't get beyond [this ](https://github.com/mmistakes/minimal-mistakes/issues/2034#issuecomment-455795885 )stage. 

Can you post a working version of your config and detail any other steps that need to be taken ?

**Comment by cloudwheels** [comment]
Hi,
That site isn't really active in afraid but that was the last working
version. There's a fair chance something in Staticman has changed rather
than MM. Try posting a comment to see if it's still working? I can have a
better look later...
