### ISSUE TITLE
G+ integration

### ISSUE THREAD

**Issue by antenore** [mmistakes/minimal-mistakes#2038]
Hi all and than thanks your amazing job!
As G+ is going to be shutdown, are you planning anything to replace it?

Would it be feasible to integrate reddit, or friendica?

Thanks!

**Comment by mmistakes** [comment]
Not planning on replacing. Will just drop support.
I've taken the approach of supporting the majors, anything else like Reddit is up to you to add.

**Comment by antenore** [comment]
If I come up with something do you want I report it here for reference?
