### ISSUE TITLE
SASS end of life

### ISSUE THREAD

**Issue by antenore** [mmistakes/minimal-mistakes#2039]
When I test minimal mistakes locally, I receive a warning as sass will be deprecated soon this year, February if I remember correctly, I saw they advice to use a new api that is quite similar.
Are you working on it, may I help somehow?

**Comment by mmistakes** [comment]
I am not working on it. Jekyll has it on their roadmap I believe to swap out the Sass gem with their next major version.

The theme doesn't have to change anything. This will come from Jekyll core.

**Comment by mmistakes** [comment]
Also Sass isn't going anywhere. This is a deprecation of Ruby Sass which is transitioning to LibSass or Dart Sass.
