### ISSUE TITLE
site.logo does not have an alt attribute

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2041]
## Environment

- Minimal Mistakes version: 4.15.1
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL: https://github.com/vih/historie/tree/update-4-15-1
- GitHub Pages hosted (if yes provide URL to site): https://5c4817bc30159c0008f7a707--vih-historie.netlify.com/sange/
- Operating system:

## Expected behavior

The logo should have an alt-attribute for ordinary html-validation and inspection to pass.

## Steps to reproduce the behavior

See this Travis test - https://travis-ci.org/vih/historie/jobs/483271319

**Comment by mmistakes** [comment]
This will be fixed in #2035

**Comment by lsolesen** [comment]
When touching the code again the comment here might be worth considering? https://github.com/mmistakes/minimal-mistakes/pull/2026#issuecomment-455770730
