### ISSUE TITLE
How to pin a post at the top?

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#2045]
How do I pin one or more posts at the top regardless of the publication dates?

**Comment by mmistakes** [comment]
The theme doesn't support this natively. You'll need to use a plugin and adjust the theme solve to make it work.

https://github.com/ibrado/jekyll-stickyposts/

**Comment by asarkar** [comment]
Would you please elaborate on "adjust the theme"? Perhaps this should go in the user docs, since I assume it to be a fairly common ask.

**Comment by mmistakes** [comment]
@asarkar If you look at the link above and dig into their documentation they advise that you need to use a modified `for` loop to display posts correctly with those marked sticky at the top.

This modified `for` loop has to be changed in the theme files. Depending on if you're using pagination or not will determine how you modify the theme:

If you're using a paginated home page you'll need to modify [`_layouts/home.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/home.html#L9-L11) to something like:

```
{% assign sorted = paginator.posts | sort: "stickiness" %}
{% for post in sorted %}
...etc...
{% endfor %}
```

If you're not paginating you'll have to make modifications to [`_layout/posts.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/posts.html) to sort sticky posts correctly.

**Comment by mmistakes** [comment]
This is also the first time I've seen a request to "stick" posts. So not sure how common of a request it is. It's quite common with Wordpress since that's baked into that software. This is much harder to do with Jekyll since it requires a plugin (not GitHub Pages compatible) or a mess of Liquid spaghetti to pull it off.

**Comment by jhabdas** [comment]
Sticky posts has been the #1 request for the last two Jekyll sites I built for friends.

**Comment by asarkar** [comment]
> If you're using a paginated home page

@mmistakes Sorry for the dumb question, but how do I know if I'm using a paginated home page? If there're many posts then it may be apparent, but if I've a new blog with few posts, how can I tell?

**Comment by mmistakes** [comment]
@asarkar If you have `index.html` and it’s using [`layout: home`](
https://mmistakes.github.io/minimal-mistakes/docs/layouts/#home-page-layout), you’re pagination posts.

**Comment by asarkar** [comment]
Seems it can pin posts and collections, what about pages? I didn't find any mention in the docs.

**Comment by mmistakes** [comment]
@asarkar No idea, never used their plugin. Maybe inquire with the developer?

**Comment by lakshmanbasnet** [comment]
Not sure about the plugin, but I achieved pinning a post check it live[ here](https://blog.lakshmanbasnet.com/) just by adding a front matter sth like this in the post(s) you want to pin. 
```
---
pin: true
---
```

then picked up the post for listing whose pin value is true as:
```
{% for post in site.posts %}
  {% if post.pin == true %}
    <h2><a class="post-link" href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a></h2>
    <p style="font-size: 13px;">{{ post.description | strip_html | truncatewords: 30 }}</p> 
  {% endif %}
{% endfor %}
```

you can play around to best suit your need!

**Comment by asarkar** [comment]
@lakshmanbasnet Where did you put the script?

**Comment by psireal9** [comment]
> @asarkar If you look at the link above and dig into their documentation they advise that you need to use a modified `for` loop to display posts correctly with those marked sticky at the top.
> 
> This modified `for` loop has to be changed in the theme files. Depending on if you're using pagination or not will determine how you modify the theme:
> 
> If you're using a paginated home page you'll need to modify [`_layouts/home.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/home.html#L9-L11) to something like:
> 
> ```
> {% assign sorted = paginator.posts | sort: "stickiness" %}
> {% for post in sorted %}
> ...etc...
> {% endfor %}
> ```
> 
> If you're not paginating you'll have to make modifications to [`_layout/posts.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/posts.html) to sort sticky posts correctly.

what should i put in ...etc... ?
