### ISSUE TITLE
Exclude pages from search engines

### ISSUE THREAD

**Issue by stsrki** [mmistakes/minimal-mistakes#2048]
I'm trying to do SEO for my site I have some pages that I don't want to be viewed by the search engines. I know that I can use _robots.txt_, but I want to know is there an easier way to accomplish this.

So my question is, is there a keyword to write at the beginning of pages to let me do this (eg. `disallow: true`)? Or I can use some plugin for this?

tnx

**Comment by mmistakes** [comment]
The theme doesn't support anything like `disallow: true` in the YAML Front Matter. I don't think the **[jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag)** plugin does either.

Only other option you have is to customize the theme slightly. I provide a blank include for adding custom meta tags to your pages' `<head>`. This would be ideal for adding a `<meta name="robots" content="noindex, nofollow">` to instruct search bots not to index or follow any of the links on a given page.

If you want to use `disallow: true` as trigger you could add the following to [`_includes/head/custom.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/head/custom.html) and any page you add that to will get the `noindex, nofollow` meta tag added to it at build.

```liquid
{% if page.disallow %}
  <meta name="robots" content="noindex, nofollow">
{% endif %}
```

**Comment by stsrki** [comment]
Thank you, I have included your examples and it's working now.

I have also found a way to exclude pages from sitemap by adding a trigger `sitemap: false` and adding a robots.txt with the following content

```
User-agent: *
Disallow: /some-directory/*

Sitemap: https://example.com/siteindex.xml
```

**Comment by aschrijver** [comment]
Don't forget that `robots.txt` and `sitemap.xml` need to act in unison. From https://moz.com/blog/xml-sitemaps: 

> One of the most common mistakes I see clients make is to lack consistency in the messaging to Google about a given page. If you block a page in robots.txt and then include it in an XML sitemap, you’re being a tease. "Here, Google... a nice, juicy page you really ought to index," your sitemap says. But then your robots.txt takes it away. Same thing with meta robots: Don’t include a page in an XML sitemap and then set meta robots "noindex,follow."
