### ISSUE TITLE
Add link to RSS feed

### ISSUE THREAD

**Issue by ddd-workshop** [mmistakes/minimal-mistakes#205]
Right now you have to know it's under `feed.xml`

**Comment by mmistakes** [comment]
If you want to add a feed link to the author sidebar you can do so in the [_author-bio.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/_author-bio.html) include. There is [Font Awesome](https://fortawesome.github.io/Font-Awesome/) icon too if you want to include that before the link the social networking ones.
