### ISSUE TITLE
Posts, pages are visible locally, not in github pages

### ISSUE THREAD

**Issue by graviraja** [mmistakes/minimal-mistakes#2058]
Hi, I am new to github pages, jekyll. Excuse me, if this is a silly mistake.
I am using the minimal-mistakes for hosting my blog.
I have added a post. It is visible in my local machine. When i push the code, the page (or) changes are not reflecting in the github page. Please help me.

github page link : https://graviraja.github.io/
github code link : https://github.com/graviraja/graviraja.github.io

github page: 
![screen shot 2019-02-10 at 12 10 21 am](https://user-images.githubusercontent.com/7556119/52524662-6c613480-2cc5-11e9-95a7-73bc786c42d0.png)

local machine : 
![screen shot 2019-02-10 at 12 09 09 am](https://user-images.githubusercontent.com/7556119/52524645-45a2fe00-2cc5-11e9-9f33-d703d94db424.png)
![screen shot 2019-02-10 at 12 09 19 am](https://user-images.githubusercontent.com/7556119/52524647-49368500-2cc5-11e9-90d8-74ceffb43cef.png)

Thanks, in advance.

**Comment by mmistakes** [comment]
As far as I can tell you have things setup correctly. The fact that it works locally and not on GitHub Pages tells me there's something going on there and not theme related.

They might be caching the old version. I do notice you are commiting `_site`, `vendor/`, and a bunch of Jekyll cache files and folderd that you probably shouldn't. That might be confusing GH Pages when you push commits.

**Comment by graviraja** [comment]
Thank you for the quick reply. After removing the vendor, it worked.
