### ISSUE TITLE
Weird behaviour on link right-click (animation breaks) example using MM Official Site

### ISSUE THREAD

**Issue by hajdukd** [mmistakes/minimal-mistakes#2059]
Hi,

When trying to open MM Links in another tab for example, the link animation breaks the link background, making it look really bad.

[Example](https://i.imgur.com/nsCymOT.png)

I've tried to look for that animation, but i cannot find it anywhere.. Wanned to turn it off.
Normally the animation should change the colour of text / create and underscore under the link, but in this case it breaks it creating a really ugly frame.

Thx in advance.

**Comment by mmistakes** [comment]
It's not an animation, it's a `:focus` state. It's good for accessibility.
Ref: https://css-tricks.com/focusing-on-focus-style
