### ISSUE TITLE
multiple language in same code block is supported?

### ISSUE THREAD

**Issue by 1sonjm** [mmistakes/minimal-mistakes#2061]
When I write, is there a way to write multiple languages ​​separated by tabs in the code block at the same location as [this site](https://community.atlassian.com/t5/Confluence-questions/Is-there-a-code-box-with-tabs-for-multiple-programming-languages/qaq-p/759748)?

**Comment by mmistakes** [comment]
No not that I know of. This isn't a native feature of Jekyll. You'd need some sort of plugin to do this.

**Comment by 1sonjm** [comment]
Thanks for the advice.
