### ISSUE TITLE
Recent post not showing but can be searched

### ISSUE THREAD

**Issue by albilaga** [mmistakes/minimal-mistakes#2062]
How to showing my recent posts in homepage? When working in local if I enable pagination it will shown but when I publish it to my github pages it will not showing anything but the articles still can be accessed using search or permalink. If I disable pagination it will not showing in homepage (local and github pages) but still can be accessed using search or permalink. This is my github pages https://github.com/albilaga/albilaga.github.io
You can browse the blog in here https://albilaga.id and search using word "Tahun", and it will showing the article

**Comment by mmistakes** [comment]
1. You need to enable Jekyll's pagination in `_config.yml`.
  ```yaml
  paginate: 5
  paginate_path: /page:num/

  plugins:
    - jekyll-paginate
  ```
2. Remove [`index.md`](https://github.com/albilaga/albilaga.github.io/blob/master/index.md) from the root of your site. You already have `index.html` (which will be your paginated homepage). Having both is confusing Jekyll. Jekyll's pagination will not work with a `.md` home page, you need to have just the `.html` version.
