### ISSUE TITLE
Breadcrumbs. Title for parent crumbs instead of uri path

### ISSUE THREAD

**Issue by dmmax** [mmistakes/minimal-mistakes#2064]
Hi!
I have simple example with bread crumbs.

Repository: https://github.com/dmmax/dmmax.github.io
There is folder foo (with index.html) and subfolder bar (with index.html too).

In the current moment
Foo page has breadcrumbs:
![image](https://user-images.githubusercontent.com/6257813/53145164-bb666e00-35d1-11e9-9936-8fad045ff835.png)

Bar page has breadcrumbs:
![image](https://user-images.githubusercontent.com/6257813/53145180-c91bf380-35d1-11e9-8a7c-3dc9b1b36742.png)

But I want to show Foo title on Bar page.
e.g.: on Bar page breadcrumbs should such as: dmmax | The Foo qq | The Bar 1235 instead of dmmax | foo | The Bar 1235 

Could you help me with it?

**Comment by mmistakes** [comment]
Breadcrumb support is experimental. It hasn't been fleshed out to work like you want. The way it works now is it takes the URL and uses that as the crumb title, not the page title.

You'll likely need a Jekyll plugin to do what you want.
