### ISSUE TITLE
Widening content layout

### ISSUE THREAD

**Issue by Physium** [mmistakes/minimal-mistakes#2069]
Hello There,

Is it possible for me to widen the post content when author and toc are both set to falsed? Given that there are empty space space on botth ends, I'm trying to stretch the content block to fill up the screen more. I understand we can do things like ``classes:widen`` but this only expands towards the right when toc is not used. Can this also be done on when aurthor is not set?

Below is an image which kinda depicts what I am trying to achieve.

![screen shot 2019-02-25 at 9 50 46 pm](https://user-images.githubusercontent.com/7604837/53341968-dde8e600-3947-11e9-870d-ddeaf6afb4a6.jpg)

**Comment by mmistakes** [comment]
The theme was designed with a two column layout in mind, so you won't find a config to enable this.

To widen the main content container you'll need to adjust the theme's CSS. Take a look through these old issues as there are suggestions to get you started.

#1373, #1265, #623, #384, #74
