### ISSUE TITLE
add portfolio page?

### ISSUE THREAD

**Issue by ndimhypervol** [mmistakes/minimal-mistakes#207]
I really like your theme, but I'd like to add a portfolio page similar to [here](https://github.com/bogoli/-folio). As I'm not a web developer, I tried to integrate this for an hour and had to give up after getting nowhere. Is there a relatively straightforward way to do this, or have you come across someone who's implemented something like this before? Thanks.

**Comment by mmistakes** [comment]
You'll have to create a new `_layout` along with CSS to do something like this. Have you looked at my [Skinny Bones theme](https://github.com/mmistakes/skinny-bones-jekyll)? It has a mix of layouts to do portfolio type [gallery pages](https://mmistakes.github.io/skinny-bones-jekyll/media/) along with standard "[blog posts](https://mmistakes.github.io/skinny-bones-jekyll/articles/readability-post/)".

**Comment by ndimhypervol** [comment]
Skinny Bones is a really neat theme! Thanks for introducing me to it. Are there any implemented examples of it so I can see what the markdown files should look like? I'm having trouble configuring a media page. I want to make another page called "projects", so I made a "_projects" folder with the .md files for each project page, then a "projects" folder with the "index.md" file, but "site.projects" isn't picking them up like "site.posts" did for the posts page. Sorry for my ignorance.

**Comment by mmistakes** [comment]
The [demo site](https://mmistakes.github.io/skinny-bones-jekyll/) is here and all of the source files for it are in the [`gh-pages`](https://github.com/mmistakes/skinny-bones-jekyll/tree/gh-pages) branch. 

The `articles` and `media` pages that list posts are filtering by categories set in the YAML Front Matter. If you want to use collections instead you'll probably have to modify some of the variables used in the `_includes

**Comment by ndimhypervol** [comment]
Thanks for the help. Still having trouble setting up a separate `projects` archive page. My projects are in `_posts/projects/`, they all have `categories: projects` and `layout: article` in the YAML Front Matter, the `navigation.yml` has the page set to `/projects/`, and `projects/index.md` reads like this:

```html
<div class="tiles">
{% for post in site.categories.projects %}
	{% include post-grid.html %}
{% endfor %}
</div><!-- /.tiles -->
```
Yet the projects page is completely blank. Any idea what might be wrong here? I basically have tried to emulate your "media" post archive page except kept them as articles.

**Comment by mmistakes** [comment]
You have a public repo of this? Way easier to troubleshoot that way.

**Comment by ndimhypervol** [comment]
Yeah, just pushed it up. I appreciate the help!
http://ndimhypervol.github.io/

**Comment by mmistakes** [comment]
I see what the issue is. You need to rename the files in `_posts/projects/`. Since they are technically posts they need a date in the filename for Jekyll to process them. Renaming them to the following worked for me:

```
-- projects
   2016-01-04-1_project.md
   2016-01-04-2_project.md
   2016-01-04-3_project.md
   2016-01-04-4_project.md
```

![projects](https://cloud.githubusercontent.com/assets/1376749/12091663/5c280ab6-b2c6-11e5-827f-9b0b0cc85071.jpg)

**Comment by ndimhypervol** [comment]
Thanks a ton! And thanks for making this neat template.

On 4 January 2016 at 09:35, Michael Rose <notifications@github.com> wrote:

> I see what the issue is. You need to rename the files in _posts/projects/.
> Since they are technically posts they need a date in the filename for
> Jekyll to process them. Renaming them to the following worked for me:
>
> -- projects
>    2016-01-04-1_project.md
>    2016-01-04-2_project.md
>    2016-01-04-3_project.md
>    2016-01-04-4_project.md
>
> [image: projects]
> <https://cloud.githubusercontent.com/assets/1376749/12091663/5c280ab6-b2c6-11e5-827f-9b0b0cc85071.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mmistakes/minimal-mistakes/issues/207#issuecomment-168693067>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by fedebarabas** [comment]
Hi all!

I am trying to achieve the same thing ndimhypervol seemed to be doing here. 

However, my project gallery doesn't look at all like the one in https://mmistakes.github.io/skinny-bones-jekyll/articles/. In particular, I wanted a grid with two columns instead of 4, therefore I doubled the size of images. I got images way bigger than expected and only one per row.

This is my repo:
https://github.com/fedebarabas/fedebarabas.github.io/
This is my projects' page:
https://fedebarabas.github.io/projects/

Could you help me figure out what I'm doing wrong?

**Comment by mmistakes** [comment]
You'll need to modify the CSS as the current grid columns have widths of 25%, which gives you 4 across.

**Comment by fedebarabas** [comment]
Could you tell where that is?

**Comment by mmistakes** [comment]
https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_archive.scss

Under grid view. The widths are different depending on the screen size so you'll need to be comfortable with media queries. Small screens 1 column, medium 2 columns, large 4 columns.
