### ISSUE TITLE
Is there way to hide description of post?

### ISSUE THREAD

**Issue by HaeSeongPark** [mmistakes/minimal-mistakes#2070]
I read the quick guide. But I couldn't find information about that.
Is there way to hide description of post?

**Comment by mmistakes** [comment]
If your post has an `excerpt` in its YAML Front Matter it will be shown. You'll have to [remove this line](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/archive-single.html#L36) if you don't want them in the archive layouts.

**Comment by HaeSeongPark** [comment]
Ah~ It works like charm! Thanks a lot! Your theme is awesome!

**Comment by mendax1234** [comment]
@mmistakes Will deleting this line cause something wrong with SEO or decrease the SEO performance?
Thanks
