### ISSUE TITLE
Build warnings for layouts

### ISSUE THREAD

**Issue by echosa** [mmistakes/minimal-mistakes#2071]
I'll start by saying I'm very new to jekyll, bundle, and ruby gems in general. That said, I'm attempting to add this theme to my Github Pages blog as a `remote_theme` following the instructions at https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remote-theme-method

As a bit of backstory, I already had some trouble that I worked through. I made the changes that section of the quick start says to make, but bundle would error due to dependency issues. After some searching around, I ended up commenting out the `gem github-pages` line, commenting out everything relating to my current theme (the default `minima`), deleting `Gemfile.lock`, and then `bundle install` ran without issue.

Trying to `bundle exec jekyll serve` after that resulted in `Dependency Error: Yikes! It looks like you don't have jekyll-include-cache or one of its dependencies installed.` So, after a bit more poking around, I manually added that gem to Gemfile. I'm not sure why I needed to do that or if doing so was the right thing. Either way, after a `bundle update`, that error no longer happens. 

So now, we get to my current issue. When I `bundle exec jekyll serve`, it seems like none of the layouts are found. From what I can tell, the layouts should already exist (or, at least,`post` should) in the remote theme. Here's the output and an example of one of the posts. I have no idea what's wrong nor how to continue troubleshooting it. It's probably something stupidly simple that I just don't know or understand, but I can't find it or figure it out.

<details>
<summary>`bundle exec jekyll serve` output</summary>
<pre>
$ bundle exec jekyll serve
Configuration file: /Users/echosa/dev/echosa.github.io/_config.yml
            Source: /Users/echosa/dev/echosa.github.io
       Destination: /Users/echosa/dev/echosa.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
     Build Warning: Layout 'post' requested in _posts/2009-05-26-journey-begins-sort-of.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2009-05-26-some-improved-navigation.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2009-06-16-buffers-and-windows-and-frames-oh-my.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2009-06-25-jira-mode-pt-1.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2009-06-30-i-got-this-keyboard-on-lockdown.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2009-07-10-jira-mode-pt-2.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2009-08-04-q-to-dired-or-not-to-dired.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2009-08-18-lets-tag-and-load.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2009-09-25-oh-yeah-its-text-editor.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2009-10-12-jira-mode-033-available.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2009-11-27-version-control-conundrum.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2009-12-21-seek-and-hide.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2010-03-30-robust-startup.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2010-05-11-im-slowly-getting-organized.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2010-10-25-bring-out-your-dead.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2010-11-10-google-maps-in-emacs.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2011-02-10-proper-ansi-term-yankpaste.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2011-06-09-back-to-terminal.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2011-06-24-im-not-dead-i-feel-happy-especially-for.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2011-06-27-demo-video-of-zend-mode-now-available.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2011-07-17-regular-expressions-made-easy.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2011-11-01-weve-created-monster-and-its-call-zf.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2011-11-16-zf-mode-features-teaser-1.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-01-05-its-2012.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-01-10-search-your-open-buffers.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-02-20-it-kills-me-every-time.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-03-21-ctrl-less-emacs-or-at-least-less-ctrl.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-04-16-zf-mode-has-been-released.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-04-17-github-mania.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-05-07-packages-now-available-from-melpa.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-05-20-checkdoc-i-neednt-say-anything-more.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-05-25-zf-mode-is-no-more-viva-php.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-06-06-improving-ansi-term.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-06-26-re-builder-query-replace-this.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-07-03-confused-about-using-behat-with-acls.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-07-13-call-of-cli.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-07-13-changing-the-rest-of-my-life.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-07-13-ansi-term-vs-shell-mongodb.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-07-17-linum-mode-graphical-glitch.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-07-17-mac-os-x-screen-locking.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-07-26-listing-all-key-commands-for-given.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-07-27-major-emacs-setup-update.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-07-27-package-bundle-keep-track-of-your.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-07-31-showing-what-makes-line-too-long.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-08-07-emacs-haiku-on-twitter.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-08-10-design-patterns.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-08-17-so-im-learning-java.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-08-21-try-and-variable-initialization.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-08-22-xdebug-and-truncated-output.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-08-26-my-first-ios-app.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-08-30-press-q-to-quit-z-to-really-quit.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-08-30-keep-mini-buffer-from-growing.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-09-04-mountain-lion-safari-flash.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-09-09-triangle-game-update.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-09-27-php-and-chmod.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-09-27-vim-influences-prefixes-and-deleting-to.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-10-08-cli-emacs-and-multiple-frames.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-10-10-why-php-a-isnt-a-repl.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-10-16-kill-multiple-lines-with-kill-lines.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-10-16-combining-blogs.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-10-26-a-whole-new-world.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-12-04-os-x-text-substitution.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2012-12-05-file-temporary-backup-functions-bash.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2013-01-13-php-plus-mode-an-apology.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2013-02-01-emacs-with-tramp-causing-os-x-kernel-panic.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2013-04-12-node-dot-js-and-turntable-dot-fm.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2013-04-12-emacs-paredit-multiple-cursors.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2013-07-05-how-my-emacs-setup-changed-me-and-is-it-time-to-change-again.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2013-08-02-design-patterns-bridge-pattern.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2013-08-29-going-back-to-gopher.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-02-25-new-gopher-library-for-php.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-02-25-clojure-time.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-03-17-gopherpedia.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-03-17-solarized-dark-color-theme-for-eclipse.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-03-31-emacsagist.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-06-17-a-possible-paradigm-shift.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-06-18-lets-try-acme-ep-0-research.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-06-18-lets-try-acme-ep-1-hello.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-06-18-lets-try-acme-ep-2-wat.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-06-19-lets-try-acme-ep-3-problem-solving.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-06-26-lets-try-acme-ep-4-enough-messing-around.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-06-27-lets-try-acme-ep-5-well.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-07-07-lets-try-acme-episode-6-trouble-in-paradise.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-08-07-lets-try-acme-episode-7-equilibrium.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-08-26-lets-try-acme-episode-8-scrolling-and-plumbing.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-10-06-new-and-improved-emacs-config.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2014-10-06-lets-try-acme-episode-9-the-end.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-01-12-gopher-php-update.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-01-12-software-freedom.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-01-13-announcing-the-release-of-etchist.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-03-29-clojure-greed-update-static-typing.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-03-29-zork-fortress-update-0-dot-0-2.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2016-08-18-git-gpg-ide.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2019-02-21-blog-resurrection-and-revamp.markdown does not exist.
     Build Warning: Layout 'default' requested in 404.html does not exist.
     Build Warning: Layout 'page' requested in about.md does not exist.
     Build Warning: Layout 'home' requested in index.md does not exist.
                    done in 0.752 seconds.
 Auto-regeneration: enabled for '/Users/echosa/dev/echosa.github.io'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
</pre>
</details>

<details>
<summary>example post</summary>
<pre>
---
layout: post
title: "Blog Resurrection and Revamp!"
date: 2019-02-21 17:49:39 -0600
comments: true
---
It's been a long, long time since I did anything with this blog. I think it's time to bring it back!

First and foremost, you'll notice a new look. I've moved away from using [Octopress](http://octopress.org) and am now just using straight [Jekyll](https://jekyllrb.com). For now, I'm using the default theme, [Minima](https://github.com/jekyll/minima). I'll be keeping my eye out for a more full-featured theme in the future (specifically looking for one that handles tags). I'm open to suggestions!

Now, what about content? Well, for the most part, the content will be the same: programming, software, etc. I've got a couple of new ideas and series' in the works, though, so stay tuned!

I'm still getting used to the new site myself, so you might see it change in the near future as I poke, prod, and tweak it. Either way, it's good to be back, and I hope everyone enjoys the posts to come!
</pre>
</details>

**Comment by mmistakes** [comment]
The theme doesn't have a `post` layout, that's why you're getting an error.
You'll want to use the `layout: single`.

All of the layouts available to the theme are [documented here](https://mmistakes.github.io/minimal-mistakes/docs/layouts/).

**Comment by echosa** [comment]
@mmistakes Thanks. I just tried that, but `single` isn't found, either. Here's the new `serve` output, the updated post, and my `_config.yml` so you can see that I've added the recommended default front matter.

<details>
<summary>`bundle exec jekyll serve` output</summary>
<pre>
$ bundle exec jekyll serve
Configuration file: /Users/echosa/dev/echosa.github.io/_config.yml
            Source: /Users/echosa/dev/echosa.github.io
       Destination: /Users/echosa/dev/echosa.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
     Build Warning: Layout 'single' requested in _posts/2009-05-26-journey-begins-sort-of.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2009-05-26-some-improved-navigation.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2009-06-16-buffers-and-windows-and-frames-oh-my.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2009-06-25-jira-mode-pt-1.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2009-06-30-i-got-this-keyboard-on-lockdown.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2009-07-10-jira-mode-pt-2.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2009-08-04-q-to-dired-or-not-to-dired.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2009-08-18-lets-tag-and-load.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2009-09-25-oh-yeah-its-text-editor.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2009-10-12-jira-mode-033-available.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2009-11-27-version-control-conundrum.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2009-12-21-seek-and-hide.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2010-03-30-robust-startup.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2010-05-11-im-slowly-getting-organized.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2010-10-25-bring-out-your-dead.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2010-11-10-google-maps-in-emacs.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2011-02-10-proper-ansi-term-yankpaste.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2011-06-09-back-to-terminal.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2011-06-24-im-not-dead-i-feel-happy-especially-for.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2011-06-27-demo-video-of-zend-mode-now-available.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2011-07-17-regular-expressions-made-easy.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2011-11-01-weve-created-monster-and-its-call-zf.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2011-11-16-zf-mode-features-teaser-1.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-01-05-its-2012.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-01-10-search-your-open-buffers.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-02-20-it-kills-me-every-time.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-03-21-ctrl-less-emacs-or-at-least-less-ctrl.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-04-16-zf-mode-has-been-released.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-04-17-github-mania.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-05-07-packages-now-available-from-melpa.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-05-20-checkdoc-i-neednt-say-anything-more.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-05-25-zf-mode-is-no-more-viva-php.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-06-06-improving-ansi-term.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-06-26-re-builder-query-replace-this.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-07-03-confused-about-using-behat-with-acls.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-07-13-call-of-cli.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-07-13-changing-the-rest-of-my-life.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-07-13-ansi-term-vs-shell-mongodb.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-07-17-linum-mode-graphical-glitch.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-07-17-mac-os-x-screen-locking.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-07-26-listing-all-key-commands-for-given.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-07-27-major-emacs-setup-update.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-07-27-package-bundle-keep-track-of-your.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-07-31-showing-what-makes-line-too-long.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-08-07-emacs-haiku-on-twitter.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-08-10-design-patterns.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-08-17-so-im-learning-java.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-08-21-try-and-variable-initialization.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-08-22-xdebug-and-truncated-output.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-08-26-my-first-ios-app.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-08-30-press-q-to-quit-z-to-really-quit.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-08-30-keep-mini-buffer-from-growing.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-09-04-mountain-lion-safari-flash.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-09-09-triangle-game-update.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-09-27-php-and-chmod.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-09-27-vim-influences-prefixes-and-deleting-to.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-10-08-cli-emacs-and-multiple-frames.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-10-10-why-php-a-isnt-a-repl.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-10-16-kill-multiple-lines-with-kill-lines.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-10-16-combining-blogs.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-10-26-a-whole-new-world.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-12-04-os-x-text-substitution.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2012-12-05-file-temporary-backup-functions-bash.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2013-01-13-php-plus-mode-an-apology.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2013-02-01-emacs-with-tramp-causing-os-x-kernel-panic.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2013-04-12-node-dot-js-and-turntable-dot-fm.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2013-04-12-emacs-paredit-multiple-cursors.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2013-07-05-how-my-emacs-setup-changed-me-and-is-it-time-to-change-again.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2013-08-02-design-patterns-bridge-pattern.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2013-08-29-going-back-to-gopher.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-02-25-new-gopher-library-for-php.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-02-25-clojure-time.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-03-17-gopherpedia.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-03-17-solarized-dark-color-theme-for-eclipse.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-03-31-emacsagist.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-06-17-a-possible-paradigm-shift.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-06-18-lets-try-acme-ep-0-research.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-06-18-lets-try-acme-ep-1-hello.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-06-18-lets-try-acme-ep-2-wat.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-06-19-lets-try-acme-ep-3-problem-solving.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-06-26-lets-try-acme-ep-4-enough-messing-around.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-06-27-lets-try-acme-ep-5-well.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-07-07-lets-try-acme-episode-6-trouble-in-paradise.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-08-07-lets-try-acme-episode-7-equilibrium.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-08-26-lets-try-acme-episode-8-scrolling-and-plumbing.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-10-06-new-and-improved-emacs-config.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2014-10-06-lets-try-acme-episode-9-the-end.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2015-01-12-gopher-php-update.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2015-01-12-software-freedom.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2015-01-13-announcing-the-release-of-etchist.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2015-03-29-clojure-greed-update-static-typing.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2015-03-29-zork-fortress-update-0-dot-0-2.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2016-08-18-git-gpg-ide.markdown does not exist.
     Build Warning: Layout 'single' requested in _posts/2019-02-21-blog-resurrection-and-revamp.markdown does not exist.
     Build Warning: Layout 'default' requested in 404.html does not exist.
     Build Warning: Layout 'page' requested in about.md does not exist.
     Build Warning: Layout 'home' requested in index.md does not exist.
                    done in 0.697 seconds.
 Auto-regeneration: enabled for '/Users/echosa/dev/echosa.github.io'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
</pre>
</details>

<details>
<summary>post content</summary>
<pre>
---
layout: single
title: "Blog Resurrection and Revamp!"
date: 2019-02-21 17:49:39 -0600
comments: true
---
It's been a long, long time since I did anything with this blog. I think it's time to bring it back!

First and foremost, you'll notice a new look. I've moved away from using [Octopress](http://octopress.org) and am now just using straight [Jekyll](https://jekyllrb.com). For now, I'm using the default theme, [Minima](https://github.com/jekyll/minima). I'll be keeping my eye out for a more full-featured theme in the future (specifically looking for one that handles tags). I'm open to suggestions!

Now, what about content? Well, for the most part, the content will be the same: programming, software, etc. I've got a couple of new ideas and series' in the works, though, so stay tuned!

I'm still getting used to the new site myself, so you might see it change in the near future as I poke, prod, and tweak it. Either way, it's good to be back, and I hope everyone enjoys the posts to come!
</pre>
</details>

<details>
<summary>_config.yml</summary>
<pre>
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dev and Such
email:
description: >- # this means to ignore newlines until "baseurl:"
  A blog in which I discuss things related to programming,
  development, software, and tech in general.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://echosa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: echosa
github_username: echosa
repository: "echosa/echosa.github.io"

# Build settings
markdown: kramdown
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.15.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Custom settings
permalink: /blog/:year/:month/:day/:title/

disqus:
  shortname: devstuff-blog

#minima:
#  social_links:
#    rss: rss
#    twitter: echosa
#    github: echosa

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
</pre>
</details>

**Comment by mmistakes** [comment]
Looks like the remote theme isn't properly configured. And since that's not installed, the layouts are obviously missing.

You'll know that the remote theme installed because Jekyll will output when you run `build` or `serve`. Something like this:

```
bundle exec jekyll build
Configuration file: /docs/_config.yml
            Source: /docs
       Destination: /docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme mmistakes/minimal-mistakes
```

No idea if you're repo up on GH is current, but you need to remove `theme: minima` and add `remote_theme: "mmistakes/minimal-mistakes"`.

**Comment by echosa** [comment]
GitHub is not current. I'm working locally on a separate git branch specifically for testing and switching to this theme. Everything I'm doing right now is local. I added my config to my previous message. In it, you can see that I did comment out the minima theme and add the remote theme. Yet, it isn't working. Is there something else to check?

**Comment by mmistakes** [comment]
Try `bundle exec jekyll build --trace --verbose`

It'll give you more info. My guess is the remote theme plugin is failing for some reason and it's not downloading the theme files. I had this issue months ago on Windows. But they updated the plugin and those issues went away.

As far as I can tell your issue is your Ruby environment and possibly the remote theme plugin, not anything specific to the theme or a config.

**Comment by echosa** [comment]
Great, thanks! Seems like I needed to add `jekyll-remote-theme` to my `Gemfile`. After doing that, I no longer have the layout warnings. Should adding that gem to the `Gemfile` be added to your installation instructions?

**Comment by echosa** [comment]
Ah, the instructions say to replace your Gemfile with just the `source` call and the `github-pages` gem. Doing that automatically pulls in the remote theme pluging. However, I still think the instructions are missing something. Step 2 is to add `jekyll-include-cache` to the `plugins` in `_config.yml`. However, that's not enough. `gem "jekyll-include-cache"` also needs to be added to the Gemfile and `bundle update` run to get it. Unless `jekyll-include-cache` is also supposed to automatically be puled down by `github-pages`, in which case it isn't.

**Comment by mmistakes** [comment]
Both jekyll-remote-theme and jekyll-include-cache are installed by GitHub Pages. If you pushed the repo up to GH Pages now and didn't include them (or a `Gemfile`), your site would still build.

It's when you develop locally things can get iffy if you don't install all the gems. jekyll-include-cache is a weird one because it's not enabled by default, which is why you need to explicitly turn it on in both the `_config.yml` and your `Gemfile`.

The theme docs can over cover so much. 99% of the issues with Jekyll aren't even Jekyll related... they're Ruby and getting damn gems to install properly.

**Comment by echosa** [comment]
Ok, cool. That all makes sense, and I've learned a ton. Thank you!

**Comment by ErikPillon** [comment]
The following worked for me:

**Step 1**: You need to add/modify the following lines in your _config.yml file

```
plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/minimal-mistakes
```

**Step 2.** Add gem 'jekyll-remote-theme' to your Gemfile if building locally with the GitHub Pages gem.

**Step 3**: Run 
```
bundle update
```
