### ISSUE TITLE
"start" optional parameter for video embeds

### ISSUE THREAD

**Issue by maxime-michel** [mmistakes/minimal-mistakes#2073]
I'd like to be able to start a video at a certain timestamp through an optional parameter, named `start` for instance. Both Vimeo and YouTube embed options allow this by adding a parameter such as `t=1m2s`.

I can submit a PR but I'm not sure if this is a common need. Any thoughts?

**Comment by mmistakes** [comment]
To avoid further complicating things, not sure this is necessary. The time start is part of the video's URL. Couldn't you just append that to the video id and do something like this?

```
{% include video id="XsxDH4HcOWA?start=35" provider="youtube" %}
```

Perhaps just an update to the documentation to note that an `id` can contain the start time from a YouTube embed.

**Comment by maxime-michel** [comment]
Excellent idea, that works great, thanks a lot. I'll open a PR to have it mentioned it in the docs.
