### ISSUE TITLE
Adjusting navigation margin to the right.

### ISSUE THREAD

**Issue by albertyumol** [mmistakes/minimal-mistakes#2076]
First off, thank you so much for the amazing template! My questions is about adjusting the margins to the right of the navigation menus as shown (red arrow):

![question](https://user-images.githubusercontent.com/17405515/53704881-4c9fd500-3e5b-11e9-9b99-8878ff59bd65.png)

I have tried following 'Merge branch 'feature/greedy-nav-long-title-fix' into develop' but to no avail.

![question1](https://user-images.githubusercontent.com/17405515/53704893-5b868780-3e5b-11e9-8c4c-f637819ee0b0.png)

Thank you so much for helping out.

**Comment by mmistakes** [comment]
The masthead that the navigation links are placed inside, are wrapped with `<div class="masthead__inner-wrap"></div>`. This has a max-width of `1280px` set to constrain it with the main content width.

If you want to push the right links all the way to the right edge of the browser, you'll need to remove the max-width.

![screen shot 2019-03-03 at 7 59 00 pm](https://user-images.githubusercontent.com/1376749/53704945-f7c67500-3dee-11e9-8f64-430b8cbf99fd.png)

**Comment by albertyumol** [comment]
You are God sent! Thanks for the quick response. I will totally recommend minimalist mistakes!

![fixed](https://user-images.githubusercontent.com/17405515/53705460-98ed1400-3e5f-11e9-8747-66e863d4ae9f.png)
