### ISSUE TITLE
Staticman template requires email. Can it be optional instead?

### ISSUE THREAD

**Issue by echosa** [mmistakes/minimal-mistakes#2083]
## Summary
I just set up Staticman on my site that's using the minimal-mistakes theme. I noticed that the template for comments requires an email address be given. I'd like to be able to remove this requirement and, in fact, completely remove that field from the comment form.

## Motivation
Some people don't like having to give their email address, and putting in a fake one is should be unnecessary.

## Drawbacks
I can't think of any, since we would be able to choose whether or not email is required or even part of the comment form.

**Comment by mmistakes** [comment]
As far as Staticman is concerned it can be optional. It's up to you set configure Staticman as to which fields should be required. Simple remove `email` from `allowedFields` in your [staticman.yml](https://github.com/mmistakes/minimal-mistakes/blob/master/staticman.yml#L13) config file.

Removing the field isn't something I'd entertain as a customization to the theme. The HTML for that field can be found in [`_includes/comments.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments.html#L68-L71)` if you want to override the include or edit (if you've forked the theme).

**Comment by echosa** [comment]
> As far as Staticman is concerned it can be optional

Right. I've done this, but the field still exists on the page, of course.

> if you want to override the include

Is there a way to do this if I'm using the theme as a remote theme on GitHub pages? Maybe it's as simple as just copying the template HTML file into a local file with the same path and editing that local copy?

**Comment by mmistakes** [comment]
Yes, you can. Copy `_includes/comments.html` to the same location in the root of your repo and make your edits to it there.

All other layout files will come from the remote theme and the include you have locally will override the one in the theme.

**Comment by echosa** [comment]
Awesome! That’s perfect then. Thanks!
