### ISSUE TITLE
Easy way to configure padding around elements?

### ISSUE THREAD

**Issue by user501254** [mmistakes/minimal-mistakes#2085]
Hi,

Excellent theme!
However, I was wondering if there is an easy way (without editing scss files) to configure the padding around elements.

**Comment by mmistakes** [comment]
There is not. This is something purely done via CSS.

**Comment by user501254** [comment]
Okay, so there are no helper classes that can be used here. Does this seem like a good idea for a future release? In my opinion helper classes (like the existing `classes: wide`) can greatly simplify certain common customization like padding and font configuration without having the user to touch any CSS.
