### ISSUE TITLE
Gallery Image Loading Artifacts

### ISSUE THREAD

**Issue by sheldonhull** [mmistakes/minimal-mistakes#2087]
https://www.sheldonhull.com/blog/welcome-to-the-world-little-ella#

On my Android I've noticed the images load extremely slow, like dialup slow. Initially they show with gray, then greenish hue, and finally dull color. I'll see if I can reproduce and record my screen.

Primary question is if the dark theme applies JavaScript that might impact the processing of images. 

I've been wanting to create some galleries but this loading issue is a problem. All images have been optimized and are served by netlify cdn.

**Comment by mmistakes** [comment]
The theme does absolutely nothing in terms of image loading. The way your images are loading have to do with them being large and I believe progressively optimized.

Closing as this is a content issue.
