### ISSUE TITLE
Lightbox or expansion of blog post images

### ISSUE THREAD

**Issue by sheldonhull** [mmistakes/minimal-mistakes#2088]
This is a feature request, unless there is something I'm missing it already does this.

I occasionally share screenshots as part of technical documentation and blog posts.  Even with the wide layout these images can be a little bit difficult to see details. I'd like the option that a user could click on the image and it would expand it similar to how your gallery does it, but just be part of any image included in blog posts automatically. 

Is it possible to enable in the current website, or could this be a feature request to consider?

**Comment by mmistakes** [comment]
You can do this linking to a larger image.

```markdown
[![](small-img.jpg)](large-img.jpg)
```

**Comment by sheldonhull** [comment]
Thank you! So this would require me for a normal screenshot to link to itself to open up in expanded view? Ie
```
[![](img.jpg)](img.jpg)
```

This nested syntax is a little rough to use. Would you consider an option that clicking standard images would expand similar to gallery? If not I'll have to come up with this myself but thought I'd ask as seems valuable for those using images that contain detail difficult to see when not expanded. 

Thanks!

**Comment by mmistakes** [comment]
This is standard Markdown. To show a larger image you need to physically link to a larger asset.

The gallery does the same thing. Only instead writing it in Markdown using an include. Which if you ask me isn't as nice since if you ever decide to switch to another SSG your include won't work anymore.... the Markdown syntax would.

**Comment by mmistakes** [comment]
Also, the lightbox that shows the larger image is triggered on image links. So having standard images wouldn't work.

What you'll likely want is some sort of image "zooming" JavaScript plugin. I'm not interested in adding that to the theme, but you certainly could bolt it on yourself.

**Comment by JulianOestreich90** [comment]
> You can do this linking to a larger image.
> 
> ```gfm
> [![](small-img.jpg)](large-img.jpg)
> ```

How do i use this in galleries? I want a smaller cropped picture to be shown as a preview and the large scaled image after click.
