### ISSUE TITLE
Can't get home page to work after following instructions.

### ISSUE THREAD

**Issue by Rietty** [mmistakes/minimal-mistakes#2089]
So I decided to start a blog and wanted to use this theme. My issue being that the site doesn't update the home page at all, even after following all the configurations and trying to make sure everything is aligned.

So far I have this repository: https://github.com/rietty/rietty.github.io and I have two posts uploaded to the site which appear fine if I use perma-link.

![image](https://user-images.githubusercontent.com/35241556/54149553-d1b35d00-440c-11e9-96b1-e39c0038c107.png)

However when I go to home-page I have nothing show up in recent posts: 
![image](https://user-images.githubusercontent.com/35241556/54149593-e42d9680-440c-11e9-8e60-9f0253437c91.png)

Afaik the `index.html` and pagination should both be fine: 
![image](https://user-images.githubusercontent.com/35241556/54149656-02939200-440d-11e9-9293-e9b1e8046d43.png)

https://github.com/Rietty/rietty.github.io/blob/master/_config.yml

What is going wrong and how do I fix it?

**Comment by mmistakes** [comment]
You have your posts in the wrong folder. Jekyll will only paginate "posts".
Rename your [`_pages`](https://github.com/Rietty/rietty.github.io/tree/master/_pages) folder to `_posts` and it will work.

**Comment by Rietty** [comment]
Thank you! That worked, however I'm trying to get the sidebar to show up on my 404 page now, but putting `author: name` or `author_profile: true` doesn't seem to be working?

You have this: 
![image](https://user-images.githubusercontent.com/35241556/54152886-a9c7f780-4414-11e9-9e00-784d367cd799.png)

However when I try to accomplish the same thing I get: 

![image](https://user-images.githubusercontent.com/35241556/54152912-b8161380-4414-11e9-8e49-ece3ad2e7e0a.png)

What am I doing wrong now?

**Comment by mmistakes** [comment]
You don't have a `layout` assigned. Either add `layout: single` to its front matter, or use [front matter defaults](https://jekyllrb.com/docs/configuration/front-matter-defaults/) (hint... that's [what I'm doing with the demo site](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml#L226-L231)).

**Comment by Rietty** [comment]
Thank you once again!
