### ISSUE TITLE
add bio-photo.jpg

### ISSUE THREAD

**Issue by seblos101** [mmistakes/minimal-mistakes#209]
![bio-photo](https://cloud.githubusercontent.com/assets/16030460/12074340/58d82d6e-b145-11e5-85e0-9454319555b6.jpg)

**Comment by seblos101** [comment]
I want to add a picture to the .image DIRECTORY  (not into a blog post).
How do I upload the image from my PC-Desktop to the .Image directory pls ?

**Comment by mmistakes** [comment]
Not sure I understand the question. If you're wanting to push a file to your GitHub hosted page then add the file into the folder you want locally, commit the change with Git, the push it up to GitHub.
