### ISSUE TITLE
Remove underline from links

### ISSUE THREAD

**Issue by jonasstr** [mmistakes/minimal-mistakes#2091]
Hey, is there a way to remove the underline from all links? Which css file do I have to edit?
I only found a way to change the link color, not the other attributes.
Thanks in advance

**Comment by mmistakes** [comment]
Add `text-decoration: none;` [here](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_reset.scss#L77-L79).
