### ISSUE TITLE
Task lists rendering in GFM

### ISSUE THREAD

**Issue by user501254** [mmistakes/minimal-mistakes#2092]
[Task Lists](https://help.github.com/en/articles/about-task-lists#creating-task-lists) show up poorly.
Is this intentional?

![image](https://user-images.githubusercontent.com/6129517/54276241-d6197a80-45b2-11e9-834f-e75f757ee974.png)

**Comment by mmistakes** [comment]
Styling was not included for `.task-list`. Should be fixed now.
