### ISSUE TITLE
Hindi translation no more available

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/minimal-mistakes#2101]
The hindi translation added as per commit https://github.com/mmistakes/minimal-mistakes/pull/1888 , is no more visible in `_data/ui-text.yml`
I think it was mistakenly removed somewhere down the road.

**Comment by mmistakes** [comment]
Looks that way. Someone want to add it back?

**Comment by Kulbhushan-Chand** [comment]
**Sure,** 
I have created two pull requests for the same ( for master and docs folder).
https://github.com/mmistakes/minimal-mistakes/pull/2105
https://github.com/mmistakes/minimal-mistakes/pull/2106
Please review.
