### ISSUE TITLE
Hyperlink that creates a new window

### ISSUE THREAD

**Issue by NNTin** [mmistakes/minimal-mistakes#2103]
## Summary

An option that when you click on a link it will open a new page.

## Motivation

Similar to how you can add in the markdown file `{: .text-right}` the text will be displayed right it would be neat if you add something similarly all links within that paragraph will have a different behavior.  
For instance instead of it opening the link in the current window it will open the link in a new window.

## Drawbacks

There is no drawback when opening a link in a new window is a optional feature.

**Comment by mmistakes** [comment]
This is a browser feature that exists today. The user <kbd>CTRL</kbd>-clicks a link to open in a window or tab.

I'm not a fan of forcing this behavior on a user for all of the reasons [cited in this article](https://css-tricks.com/use-target_blank/).
