### ISSUE TITLE
Resizing image in index.html

### ISSUE THREAD

**Issue by mohameddhaoui** [mmistakes/minimal-mistakes#2107]
Hi , 
I'm just getting started with minimal-mistakes  :) 
I have an issue with an image that I put in my index.html file . The size is too big and I didn't find a way to resize it and fix the width and the height ...
Here is my index.html file :  

---
layout: home
author_profile: true
header: 
  image: "/images/back_2.gif"
---

Many thanks 
Regards

**Comment by mmistakes** [comment]
See this issue about video sizes in the header, it also applies to images.

https://github.com/mmistakes/minimal-mistakes/issues/2009#issuecomment-450766039

**Comment by mohameddhaoui** [comment]
Thanks for your quick answer . So there is no way to configure the size ... I don't understand why there are many websites using minimal mistakes theme and are able to fit the image size  ( for example https://thegreat.ml/ )  . Below how my home page looks ...... : 

![image](https://user-images.githubusercontent.com/49007999/55155491-c45dd880-5157-11e9-8dc2-9ef0c80932fa.png)

**Comment by mmistakes** [comment]
I think because you're only using a header image. That site you linked to above is using a header with text overlayed it. There's different settings for that.

https://mmistakes.github.io/minimal-mistakes/docs/layouts/#header-overlay
