### ISSUE TITLE
ERROR Deployer not found: github

### ISSUE THREAD

**Issue by Aierui** [mmistakes/minimal-mistakes#211]
ERROR Deployer not found: github

**Comment by mmistakes** [comment]
Please provide more context, a sample repo, etc. so I can troubleshoot the error. I'm unfamiliar with this error. Doesn't look like anything I've seen in Jekyll core before.

**Comment by mmistakes** [comment]
Closing because this appears to be related to Hexo and not Jekyll. Please file an issue with that project or whoever ported my Jekyll theme for use with Hexo.

**Comment by Aierui** [comment]
I press hexo d”，then prompt “ERROR Deployer not found: github” 
I want to upload my source code for subject to github，but failed

**Comment by mmistakes** [comment]
I've never used Hexo. My theme is for Jekyll. I'm guessing someone adapted it for Hexo so you'll have to get help from them.

**Comment by Aierui** [comment]
I'm trying
