### ISSUE TITLE
There isn’t anything to compare.

### ISSUE THREAD

**Issue by Aierui** [mmistakes/minimal-mistakes#212]
There isn’t anything to compare.

gh-pages and master are entirely different commit histories.
![02](https://cloud.githubusercontent.com/assets/16207137/12075772/c16e3266-b1c6-11e5-8e90-2160ed21a920.jpg)

**Comment by mmistakes** [comment]
I'd reach out to GitHub or Google around. This isn't an issue with the theme, it looks to me to be Git related.

https://pages.github.com/
