### ISSUE TITLE
.htaccess within include in _config.yml breaks generation of .md files in _pages directory

### ISSUE THREAD

**Issue by erikrtn** [mmistakes/minimal-mistakes#2125]
## Environment

- Minimal Mistakes version: 4.16.0
- Ruby gem or remote theme version: `mmistakes/minimal-mistakes@4.16.0`
- Jekyll version: 3.8.5
- Git repository URL: https://github.com/erikrtn/albert-anastasio.github.io
- GitHub Pages hosted (if yes provide URL to site): not live yet
- Operating system: macOS 10.14.4

## Expected behavior

I follow instructions at https://mmistakes.github.io/minimal-mistakes/docs/pages/.

All `.md` files in `_pages` directory (see screenshot) should appear after running `bundle exec jekyll serve`.

<img width="555" alt="Screen Shot 2019-04-12 at 10 41 49 AM" src="https://user-images.githubusercontent.com/1253422/56055908-9b207900-5d0f-11e9-9305-c08e4fb62e3e.png">

`index.html` is generated and can be viewed on localhost (`http://127.0.0.1:4000`), but none of the expected pages are generated from the markdown files within `_pages` directory, such as `about.md` (`http://127.0.0.1:4000/about/`):

<img width="588" alt="Screen Shot 2019-04-12 at 10 40 05 AM" src="https://user-images.githubusercontent.com/1253422/56055960-b8edde00-5d0f-11e9-9068-011023b88c9f.png">

I thought this could be due to a problem with my `_config.yml`, but it includes the appropriate array :

<img width="234" alt="Screen Shot 2019-04-12 at 10 55 20 AM" src="https://user-images.githubusercontent.com/1253422/56056618-9361d400-5d11-11e9-8300-bd700f31d073.png">

## Fix

If I remove the `- .htaccess` from my `include` statement, leaving only the `_pages` array, the markdown files in `_pages` are generated and the problem is solved:
<img width="248" alt="Screen Shot 2019-04-12 at 10 47 37 AM" src="https://user-images.githubusercontent.com/1253422/56056258-87c1dd80-5d10-11e9-8f4b-99f5bd11afff.png">

## Steps to reproduce the behavior
If I replace `- .htaccess` with `- anythingelse`, the same error occurs.

---

Seems like arrays do not play nicely in a list in `_config.yml`.

Any ideas why this is happening? How to fix? What if one wants to include several files, rather than a single array?

What does `.htaccess` do, and do I need to include it? That answer probably exists so I'll keep searching.

**Comment by mmistakes** [comment]
You have some bad YAML on your `include`. 

`include:
  - .htaccess
  - _pages
```

Is what you want. Indented hyphens are read by YAML as an array. 

Another way to write an array would be:

```
include: [".htaccess", "_pages"]
```

You can't mix the two as you have, which is why it stopped working.

**Comment by erikrtn** [comment]
Thanks for the super fast response and clarification. And thanks for the kickass theme.

I now understand how YAML reads hypens and how brackets are used. Makes sense.
