### ISSUE TITLE
Algorithm pseudocode in kramdown

### ISSUE THREAD

**Issue by fjp** [mmistakes/minimal-mistakes#2132]
Hi,
I am using kramdown and I am able to get latex formulas displayed correctly. Now I would like to add an algorithm using the latex package algorithm2e. [This answer](https://tex.stackexchange.com/a/452565/39188) on the tex.stackexchange shows that it works with markdown and pandoc. 

I added the package in [a post](https://fjp.at/posts/localization/mcl/#monte-carlo-localization-algorithm) in the preamble and copied the example from stackexchange but the algorithm does not get rendered as expected.

Here is the [link](https://github.com/fjp/fjp.github.io) to the repo of my github page.

How can I add extra latex packages using kramdown?

The [answer of an issue](https://github.com/gettalong/kramdown/issues/511#issuecomment-391333554) in kramdown states to use a custom latex template. However, I have no idea how to use a new template.

**Comment by mmistakes** [comment]
Looks like by template it's talking about an ERB one, which is done in Ruby land. Pretty sure the theme has no way of tying into this. It's something that needs to be done further up the chain with Jekyll likely.

I'd ask on their repo [jekyll/jekyll](https://github.com/jekyll/jekyll) if such functionality exists.
