### ISSUE TITLE
Hosting your page, after to fork and edit

### ISSUE THREAD

**Issue by rodolfolotte** [mmistakes/minimal-mistakes#2135]
Dear Michael, how are you!? First, you have made a great job on this new theme, well done! 

I've searched for this issue and found some people that are close related to this ([here](https://github.com/mmistakes/minimal-mistakes/issues/1244)), but, when I reproduced to my problem (inserting `gem "minimal-mistakes-jekyll", :github => "mmistakes/minimal-mistakes", :branch => 'color-skins'`), still did not get this done.

I've gotten the "fork" method, changed all the layout and pages to my custom-personal-page and have reached a good content to upload! So, after to try the procedures described [here](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/), in my main repository, the remain folders are:
```
├── assets
├── _config.yml
├── _data
├── _education
├── Gemfile
├── Gemfile.lock
├── _includes
├── _layouts
├── _pages
├── _portfolio
├── _posts
├── _publications
└── _site
```

My `_config.yml` file:  
```
theme                    : "minimal-mistakes-jekyll"  
minimal_mistakes_skin    : "dark"
```

My `main.scss` ending file:  
```...  
@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin  
@import "minimal-mistakes"; // main partials
```

my `Gemfile`:  
```
source "https://rubygems.org"  
  
gem "jekyll", "~> 3.5"  
gem 'minimal-mistakes-jekyll', :git => 'https://github.com/mmistakes/minimal-mistakes.git'
```

On localhost I see this:
[Page in localhost](https://cdn1.imggmi.com/uploads/2019/4/24/6cb7c3d36742c06f919960eb27180d91-full.png)

But when hosted:
[Page hosted at github](https://cdn1.imggmi.com/uploads/2019/4/24/5f6cce953ebf40e47e88cc01e4ebd254-full.png)

Then, i get this email from Github:

**The page build failed for the `master` branch with the following error:**

__Your SCSS file `assets/css/main.scss` has an error on line 513: File to import not found or unreadable: minimal-mistakes/skins/dark. For more information, see https://help.github.com/en/articles/page-build-failed-invalid-sass-or-scss._

Could you help me, to solve this issue?
Cheers!

**Comment by mmistakes** [comment]
It's not working because you are missing all of the Sass files. That's what the error message you are getting is all about. It's looking for Sass partials in `_sass/minimal-mistakes/` and they are missing. Make sure the complete [`_sass` folder](https://github.com/mmistakes/minimal-mistakes/tree/master/_sass) is in your repo and pushed up to GitHub.

I'd suggest not forking the theme. It's much easier to use it as a remote theme and override layouts or includes if you need to customize. Check the mm-github-pages-starter repo is [an example of how to setup using as a remote theme](https://github.com/mmistakes/mm-github-pages-starter). You get the benefit of easy upgrades without needing to manually pull in changes from the MM repo.

**Comment by rodolfolotte** [comment]
> It's not working because you are missing all of the Sass files. That's what the error message you are getting is all about. It's looking for Sass partials in `_sass/minimal-mistakes/` and they are missing. Make sure the complete [`_sass` folder](https://github.com/mmistakes/minimal-mistakes/tree/master/_sass) is in your repo and pushed up to GitHub.
> 
> I'd suggest not forking the theme. It's much easier to use it as a remote theme and override layouts or includes if you need to customize. Check the mm-github-pages-starter repo is [an example of how to setup using as a remote theme](https://github.com/mmistakes/mm-github-pages-starter). You get the benefit of easy upgrades without needing to manually pull in changes from the MM repo.

Thank you again, I will check the remote-theme method!
