### ISSUE TITLE
Javascript error - Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by deepfriedbrain** [mmistakes/minimal-mistakes#2137]
## Environment

- Minimal Mistakes version: 4.16.0
- Ruby gem or remote theme version: 2.5.1p57
- Jekyll version: 3.8.5
- Git repository URL:
- GitHub Pages hosted (if yes provide URL to site):
- Operating system: MacOS 10.14.1

## Expected behavior

I'm trying to upgrade from the theme version 4.6.0 and 4.16.0. I'm almost there but running into a javascript error when I scroll some pages all the way to the bottom. I have not seen anything broken due to this error, but it would be good to eliminate an errors on the site. I have not modified the main.min.js. It's coming straight from the theme repo.

```
Uncaught TypeError: Cannot read property 'content' of undefined
    at c (main.min.js:9)
    at f (main.min.js:9)
    at d.detect (main.min.js:9)
c @ main.min.js:9
f @ main.min.js:9
d.detect @ main.min.js:9
requestAnimationFrame (async)
h @ main.min.js:9
```

It's happening on some pages but not all. I tried a lot to troubleshoot but have not been able to figure out the root cause. 

Does it have something to do with one of the new scroll scripts?

Any help will be appreciated.

**Comment by mmistakes** [comment]
This should have been fixed in #2124. Updated to the latest version of the theme [4.16.1](https://github.com/mmistakes/minimal-mistakes/releases/tag/4.16.1)

**Comment by deepfriedbrain** [comment]
Thanks so much. That resolved the error. But I'm getting some warnings now which I didn't see with 4.16.0:

```
main.min.js:7 jQuery.Deferred exception: e is not a function TypeError: e is not a function
    at d (http://localhost:3000/assets/js/main.min.js:7:7511) undefined
```

**Comment by mmistakes** [comment]
Is this on a non-customized version of the theme? Or is it a fork with custom JavaScript?

**Comment by deepfriedbrain** [comment]
I'm pointing to your repo and not using a fork. 

I do have a few small Javascripts that are included separately but those are not bundled inside main.min.js.

**Comment by mmistakes** [comment]
Sounds like those are causing the problem. There are no script errors in the console for the unmodified version of the theme.

**Comment by mmistakes** [comment]
Nevermind, I see what you're saying. It's likely related to the jQuery update in #2129. I'll probably have to roll that back since I'm guessing there is an older plugin that doesn't work with the latest version.

**Comment by mmistakes** [comment]
Fixed in release 4.16.2

**Comment by deepfriedbrain** [comment]
Yes, it's resolved now. Thank you so much.

**Comment by coliff** [comment]
jQuery 3.4.1 has been released and fixes a few bugs: https://blog.jquery.com/2019/05/01/jquery-3-4-1-triggering-focus-events-in-ie-and-finding-root-elements-in-ios-10/

Can you retest Minimal Mistakes with that? It'd be good to upgrade from jQuery 3.3.1 as that version has a security vulnerability: https://snyk.io/vuln/npm:jquery

**Comment by mmistakes** [comment]
Looks like 3.4.1 fixed whatever bug was causing issues previously. I'm not seeing any console errors anymore.

Stay tuned for an update.
