### ISSUE TITLE
Javascript error when pages containing TOC are resized

### ISSUE THREAD

**Issue by deepfriedbrain** [mmistakes/minimal-mistakes#2140]
## Environment

- Minimal Mistakes version: 4.16.2
- Ruby gem or remote theme version: NA
- Jekyll version: 3.8.5
- Git repository URL: NA
- GitHub Pages hosted (if yes provide URL to site): NA
- Operating system: MacOS 10.14.1

## Expected behavior

If any page that contains a TOC is resized, the following Javascript error is thrown in the console:

```
main.min.js:9 Uncaught TypeError: Cannot read property 'sort' of undefined
    at i (main.min.js:9)
    at main.min.js:9
```
I'm using the default version of the theme (no fork), and have not modified main.min.js. I'm using Chrome 74.x (latest version).

**Comment by mmistakes** [comment]
Not seeing this on the demo site (for example [this page doesn't have a TOC](https://mmistakes.github.io/minimal-mistakes/markup-text-readability/) and I see no JavaScript errors in the console on resize). 

Do you have a reproducible test case repository?

**Comment by deepfriedbrain** [comment]
I think you misread my post. It appears on pages that have TOC. I can reproduce it on the demo site. 

Refer to this page: https://mmistakes.github.io/minimal-mistakes/layout-table-of-contents-post/

**Comment by mmistakes** [comment]
OK. I'm able to reproduce. When I rolled back jQuery the other day and uglified the scripts there were a few warnings related to the Gumshoe and scroll scripts. Perhaps something is getting mangled there when everything is concatenated.

Will have to play around.

**Comment by mmistakes** [comment]
It's Gumshoe related. When I use the unconcatenated versions of the scripts the error has more context.

```
TypeError: contents is undefined[Learn More] gumshoe.js:111:3
    sortContents http://127.0.0.1:4000/test/assets/js/plugins/gumshoe.js:111
    timeout http://127.0.0.1:4000/test/assets/js/plugins/gumshoe.js:412
```

**Comment by mmistakes** [comment]
Updating Gumshoe to v5.1.1 seems to have fixed it.

**Comment by deepfriedbrain** [comment]
Thank you. Was the jquery change from minified version to the full version intentional?

**Comment by mmistakes** [comment]
Yes. The uglify script I run minifies all the JavaScript when it concatenates. It does a better job of that if you run it on unminified code first.

**Comment by deepfriedbrain** [comment]
Yes, makes sense. I just wanted to confirm. The error has been resolved. Thanks!

BTW, I did notice that the jquery.min.js has been left in eventhough it's not used.
