### ISSUE TITLE
Question regarding deprecation of TOC include

### ISSUE THREAD

**Issue by deepfriedbrain** [mmistakes/minimal-mistakes#2141]
I was going through the latest documentation (v4.16.2) and noticed that the old construct of embedding TOC using include is deprecated. 

I had a concern regarding the new construct. It doesn't allow me to specify the location of the TOC in the body. On my site, I embed the TOC after the opening paragraph, which also includes an image usually. I have the image on the left and text on the right. That doesn't leave much space for the TOC.

Using the include toc construct, I can pretty much embed the TOC anywhere I want in the body of the post. But with the new construct, I would lose that control. 

So I just want to know if there's any way to control the position of the TOC using the new construct before the old construct gets deprecated.

Thanks.

**Comment by mmistakes** [comment]
The `{% include toc %}` isn't anything special really, it's essentially a shortcut for a feature available to Kramdown that is wrapped with some HTML for styling purposes.

If you add `{:toc }` anywhere in your Markdown file, [Kramdown will automatically convert](https://kramdown.gettalong.org/converter/html.html#toc) all of the headings into a table of contents. There is absolutely nothing stopping you from doing this, even after `{% include toc %}` is removed from the theme.

Even then you can copy [`_includes/toc`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/toc) and add to your repo and still use it as you always have. By me deprecating it I'm just warning that there may be styling issues in the future as it uses some hacky CSS to position it outside the content flow.

The new method builds it outside of the main content container... which isn't possible using Kramdown's method. It's unlikely this will break, I just didn't want to promise it will always work as there may be styling added to the new approved method which has side-effects to the old deprecated.
