### ISSUE TITLE
banner.js

### ISSUE THREAD

**Issue by inetbiz** [mmistakes/minimal-mistakes#2143]
Does banner.js serve a purpose in rendered site? I don't see it excluded. I don't see it included in the head.

**Comment by mmistakes** [comment]
It's strictly related to the development of the theme. It's used in the [`npm run build:js` script](https://github.com/mmistakes/minimal-mistakes/blob/master/package.json#L28-L33) that takes all of the unminified JavaScript, concatenates, and adds [banner text](https://github.com/mmistakes/minimal-mistakes/blob/master/banner.js#L10-L14) to the top of [`main.min.js`](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/main.min.js#L1-L5).

**Comment by inetbiz** [comment]
@mmistakes then should it be in the exclude on build?

**Comment by mmistakes** [comment]
It's not included in the build. If you're using the theme as intended (ruby gem or remote theme) `banner.js` will never appear in your site repo. For example the [`/test` folder](https://github.com/mmistakes/minimal-mistakes/tree/master/test) is what the structure of your site should be when using the theme. The bare minimum being:

```
\_posts
index.html
_config.yml
Gemfile
```

If you go against my advise and fork it, then yes you need to exclude it. Along with a bunch of other development related files... remove the `.gemspec`, correct the `Gemfile`, etc. etc. etc.
