### ISSUE TITLE
Possible to have tags and categories for collections

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2144]
In gh-1256 which is a couple of years old, I asked whether it is possible to use tags for collections and @wAuner raised the same question in gh-1743. Do you know whether that has been implemented, as I would like to use it with a new site based in your awesome theme - https://github.com/lsolesen/legestue-net-jekyll

**Comment by mmistakes** [comment]
To my knowledge it has not been added yet. Check out jekyll/jekyll's repo. I believe it was being discussed as a feature for 4.0 to harmonize how categories and tags work across collections... not just on posts.
