### ISSUE TITLE
Link post type does not work

### ISSUE THREAD

**Issue by diegoscl** [mmistakes/minimal-mistakes#2145]
Link entries do not work as expected. 

The expected behavior is that the title of the publication contains the link to the external site and then a marker icon is found. This can be seen in John Gruber's blog.

Example: https://mmistakes.github.io/minimal-mistakes/post%20formats/post-link/

**Comment by mmistakes** [comment]
Link posts work this way in archives.

**Comment by diegoscl** [comment]
Nop. In archives the title link goes to the single post page.

Thanks forma your help.

Regards.

**Comment by mmistakes** [comment]
That's strange. Which browser are you using? I've tested in Chrome, Safari, and IE and they all work as expected.

Clicking on the "Post: Link" title goes to an external site link, and clicking the chain link icon goes to actual single post page.

**Comment by diegoscl** [comment]
You're absolutely right. Apparently it is a problem with the browser because in the source code I see the correct tags.

Unfortunately I tried Firefox 66, Safari 12.1 and Chrome 74.

![Captura de Pantalla 2019-05-04 a la(s) 12 05 15](https://user-images.githubusercontent.com/1641555/57181732-5a76d400-6e65-11e9-846f-bae9a8508396.png)

Any ideas? 

Thanks for your help.

**Comment by diegoscl** [comment]
I made a new deployment with version 4.16.3 and now it's all OK!  😬  Maybe it was just a problem with the jquery version.

Thanks a lot!
