### ISSUE TITLE
Jekyll Conversion Error Building Locally

### ISSUE THREAD

**Issue by GBruening** [mmistakes/minimal-mistakes#2146]
I'm trying to run github pages locally for testing, I followed the steps [here](https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll). 

I'm working off of [academic pages](https://github.com/academicpages/academicpages.github.io).

My repo is [here](https://github.com/GBruening/GBruening.github.io).

### Environment
* __OS__:  windows 10
* __Ruby Version__:      ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]
* __Bundler Version__: Bundler version 2.0.1
* __Jekyll Version__:     jekyll 3.8.5

___

When I try to build the site using:
`bundle exec jekyll serve
`

I get the error:
```
Configuration file: E:/Google DRive/github/gbruening.github.io/_config.yml
            Source: E:/Google DRive/github/gbruening.github.io
       Destination: E:/Google DRive/github/gbruening.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: vendor/breakpoint/breakpoint. Load path: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-theme-primer-0.5.3/_sass on line 10
jekyll 3.8.5 | Error:  File to import not found or unreadable: vendor/breakpoint/breakpoint.
Load path: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-theme-primer-0.5.3/_sass on line 10

```

Not sure if I need to post this here, or at the academic pages, but any help would be greatly appreciated.

**Comment by mmistakes** [comment]
I would leave an issue on academic pages' repo. They're using an older fork of my theme which could be causing issues.

**Comment by GBruening** [comment]
Alright, i'll check there.
