### ISSUE TITLE
Blog post full page

### ISSUE THREAD

**Issue by blackat** [mmistakes/minimal-mistakes#2147]
## Summary
Introduce the possibility to have the blog article spanning over the all page, max-width:100.

## Motivation
Having both the author and TOC columns reduces quite a lot the readable space.
I have tried to set the variable max-width: 100% !important but it ends up with the same behaviour for the article page as well having worked on the #main tag.

**Comment by mmistakes** [comment]
If your want a wider main content area use

https://mmistakes.github.io/minimal-mistakes/docs/layouts/#wide-page

Or `layout: splash`

https://mmistakes.github.io/minimal-mistakes/docs/layouts/#splash-page-layout

**Comment by blackat** [comment]
I will try with the splash because 

>  If the page contains a table of contents, it will no longer appear to the right. Instead it will be forced into the main content container directly following the page’s title.

and I like the TOC on the right sticky specially with some long posts.
