### ISSUE TITLE
Gem theme splash page

### ISSUE THREAD

**Issue by inetbiz** [mmistakes/minimal-mistakes#2152]
looking at https://mmistakes.github.io/minimal-mistakes/ I would like to override layout to create this. Can the section dealing with gem theme install mention HOWTO make the index page just like yours and how to customize it?

**Comment by mmistakes** [comment]
All of the layouts are documented. You can also view the source of the documentation site to see exactly how everything is built.

- [`layout: splash`](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#splash-page-layout)
- [Demo site source](https://github.com/mmistakes/minimal-mistakes/tree/master/docs)
- [Demo site home page source](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_pages/home.md)

I've covered this before if you want to search through the closed issues for further context.
