### ISSUE TITLE
12 Column Full layout

### ISSUE THREAD

**Issue by inetbiz** [mmistakes/minimal-mistakes#2153]
How can I make https://jekyll.strikehawk.com/about/ a 12 column with padding? I've tried the ```classes: wide``` with the TOC but it renders bad.

**Comment by mmistakes** [comment]
The theme doesn't have a 12 column layout.

**Comment by inetbiz** [comment]
So nothing I can do except create my own foundations layout?

**Comment by mmistakes** [comment]
You'll probably want to use a theme that is built on Bootstrap or the like if that's your goal.

**Comment by mmistakes** [comment]
Or use [`layout: splash`](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#splash-page-layout) which doesn’t leave space for the left author sidebar.
