### ISSUE TITLE
Change the shape of avatar

### ISSUE THREAD

**Issue by tazzism** [mmistakes/minimal-mistakes#2154]
Is there a possibility to change the shape to the overlay over the author avatar? I'm specifically looking for a hexagonal overlay like here: [https://codepen.io/GeoffreyCrofte/pen/Hizkh](url)

**Comment by mmistakes** [comment]
Not something I'd consider supporting in the theme, but if you're adept at writing CSS you can remove `border-radius: 50%;` which currently makes a square image into a circle... and replace with whatever you need to change shape.

Here's the [relevant lines of CSS](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_sidebar.scss#L129-L137).
