### ISSUE TITLE
Pound symbol '#' not displayed properly in post tags and categories

### ISSUE THREAD

**Issue by deadlydog** [mmistakes/minimal-mistakes#2156]
## Environment

- Minimal Mistakes version: 4.16.3
- Ruby gem or remote theme version: 4.16.3
- Jekyll version: 3.8.5
- Git repository URL: https://github.com/deadlydog/deadlydog.github.io
- GitHub Pages hosted (if yes provide URL to site): https://deadlydog.github.io/
- Operating system: Windows 10 / GitHub

## Expected behavior

When creating a post and using a tag or category with a `#` in it, the tag/category does not get displayed properly on the post; instead just an empty box is displayed.

For an example, see the tags and categories [on this page](https://deadlydog.github.io/sweet-c-gems/), which uses `.Net` and `C#` as a tag and category. `.Net` shows up fine, but `C#` ends up just being an small empty box.

![image](https://user-images.githubusercontent.com/1187140/57979637-d2a0d600-79dd-11e9-9181-73e6b9c14e3b.png)

I believe the issue is caused by [the parsing of the tags/categories and splitting on the `#` sign](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/tag-list.html#L20).

The tag does show up properly in [the tags](https://deadlydog.github.io/tags/) and [categories](https://deadlydog.github.io/categories/) pages; just not on the posts themselves.

## Steps to reproduce the behavior

Simply include a `#` in your tag or category name on a post. I've tried escaping the `#` as well as wrapping it in quotes, but nothing seems to work.

e.g. [Here's a post](https://github.com/deadlydog/deadlydog.github.io/blob/master/_posts/2011-09-02-sweet-c-gems.md) with front matter that reproduces the issue.

```
title: 'Sweet C# Gems'
permalink: /sweet-c-gems/
categories:
  - .NET
  - C#
tags:
  - .NET
  - C#
```

Thank you for providing this outstanding theme!

**Comment by mmistakes** [comment]
Thanks for pointing out this bug. Should be fixed in https://github.com/mmistakes/minimal-mistakes/commit/26c1989bf65290761af2aad24c55a34311a26183

**Comment by deadlydog** [comment]
Works fantastically now. Thanks for the such quick turnaround time on this! 👍
