### ISSUE TITLE
Toc Levels

### ISSUE THREAD

**Issue by blackat** [mmistakes/minimal-mistakes#2158]
Hello,
I have seen that in kramdown it is possible to specify levels such as `toc_levels: 1..6` but as far as I got it is deprecated and `toc: true` should be used instead.
Is there a way to limit the to levels as in kramdown?

Thanks 🙏

**Comment by mmistakes** [comment]
Yes, you can customize/override the [table of content include](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/toc.html#L14-L22) to control min/max toc levels.

**Comment by blackat** [comment]
really cool, thanks man 👍
