### ISSUE TITLE
splash layout and right toc

### ISSUE THREAD

**Issue by blackat** [mmistakes/minimal-mistakes#2159]
Hello,
currently it seems not possible to have `layout: splash` and toc on the right of the page, is there a way to get it?

Thanks a lot for the attention 🙏

**Comment by mmistakes** [comment]
There is no way unless you hack the splash layout. It was purposely built to not support table of contents.

**Comment by vcidst** [comment]
For anyone who came here from search results. Alternative solution, add buttons on top of page that link to different sections of the page. For more resemblance to a TOC, you can add a markdown table in `excerpt` with links to particular sections of your page.

I was able to do this with my projects page that use the layout splash. [demo](https://shailendra.me/projects/) and [source](https://github.com/vcidst/vcidst.github.io/blob/master/_pages/projects-archive.md)
