### ISSUE TITLE
A way to download images ?

### ISSUE THREAD

**Issue by JulienParis** [mmistakes/minimal-mistakes#2163]
## Summary

Is there a to download an image frrom a link or an image ? I tried to include a link - in markdown and in html - but both ways are simply displaying the image fullscreen instead of opening a new page or downloading.

I tried those snippets in a post :  

```html
note : illustration in jpg 
<a 
  href="https://raw.githubusercontent.com/co-demos/apiviz-frontend/master/documentation/configurations/APIVIZ-CONFIGURATIONS-export-details-full.jpg" 
  target="_blank">
    download here
</a>
```

```md
**note** : illustration in jpg 
[here](https://raw.githubusercontent.com/co-demos/apiviz-frontend/master/documentation/configurations/DATA_WORKFLOW-details.jpg)
```

----------

so the text appears OK as follow...

![Capture d’écran 2019-05-23 à 15 06 15](https://user-images.githubusercontent.com/21986727/58255057-6cfd7280-7d6c-11e9-8e3f-aea1f60f4654.png)

... but both of the snippets are showing this after clicking on the link instead of the expected behaviour : 

![Capture d’écran 2019-05-23 à 15 00 10](https://user-images.githubusercontent.com/21986727/58254716-a4b7ea80-7d6b-11e9-9c12-8732a797a864.png)

Online behaviour [here](https://co-demos.github.io/apiviz-frontend/lexicon/data-flows/)

This code of the post is [here](https://github.com/co-demos/apiviz-frontend/blob/master/_posts/2019-05-07-data-flows.md)

## Motivation

It could be useful to be able to download documents / images with MMistakes... 

## Drawbacks

Perhaps I got it wrong ...

**Comment by mmistakes** [comment]
This will vary between browsers, but right clicking the image allows you to save/download the image.
Has nothing to do with the theme other than it's opening the image in a lightbox versus a blank window/tab.

![image](https://user-images.githubusercontent.com/1376749/58257008-0bbeaa80-7d3e-11e9-843e-4d66d0dd8605.png)
