### ISSUE TITLE
Odd frame around active link in Firefox

### ISSUE THREAD

**Issue by kamil4** [mmistakes/minimal-mistakes#2164]
## Environment

- Minimal Mistakes version: 4.16.3
- Ruby gem or remote theme version: 2.4.0
- Jekyll version: 3.8.5
- Git repository URL: N/A
- GitHub Pages hosted (if yes provide URL to site): no
- Operating system: Gentoo Linux

## Expected behavior

I'm seeing an odd behavior around links in Firefox 66.0.5 (Linux 64-bit version). I can't reproduce it with Chrome. Under certain circumstances, a thick frame is drawn around the last clicked on link or one being hovered on. It feels like a race condition of sorts.

While I noticed it with my own installation, it isn't my specific issue as I'm seeing the same even when browsing your https://mmistakes.github.io/minimal-mistakes/

Here's a screenshot:

![mmistakes](https://user-images.githubusercontent.com/16415200/58338583-9c17f080-7e0d-11e9-874a-eda72c2b848c.png)

## Steps to reproduce the behavior

With my regular Firefox profile, it's enough if I click on a link ("Quick-Start Guide" in the above screenshot), wait for the new page to load, and then press the browser's back button. The link is displayed underlined, and when I move the mouse around, it turns into the frame visible in the above screenshot. Clicking on any inactive area of the page clears it up.

With a fresh Firefox profile, it does not happen that way. I found that I need to enable in "Preferences", under "Privacy & Security", "Content Blocking" -- switch from "Standard" to "Custom" and "Trackers" to "In all windows". Then it starts behaving as described above. Even without changing any preferences, I can reproduce this effect by hovering over a link, pressing the right mouse button to bring up the context menu, and moving the mouse away -- the frame shows up.

**Comment by mmistakes** [comment]
This box is a `:focus` state. It is included for accessibility reasons to indicate what link (or button) you are currently focused on. It is useful for those users who tab through a page so they know what link they're currently on to interact with it.

If you remove that state it's impossible to tell. You can certainly [remove it by customizing the CSS](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_mixins.scss#L5-L11), but I wouldn't advise that if you care about making your site more accessible.
