### ISSUE TITLE
Custom category archive is not shown

### ISSUE THREAD

**Issue by slhck** [mmistakes/minimal-mistakes#2165]
## Environment

- GitHub pages
- Minimal Mistakes version: Git master
- Ruby gem or remote theme version: ^-- see above
- Jekyll version: 3.7.4
- Git repository URL:
    - https://github.com/vqeg/software-tools/ – the original
    - https://github.com/QUALINET/databases/ – the new site
- GitHub Pages hosted (if yes provide URL to site):
    - https://vqeg.github.io/software-tools/ – the original
    - https://qualinet.github.io/databases/ – the new site
- Operating system: macOS 10.14

## Expected behavior

I have an existing website at the first repository (https://github.com/vqeg/software-tools/) which uses the `/tools` link to show a simple overview of the categories, with a list of tools below that overview.

I achieved this by creating the page `tools.md` with a categories layout:

```
---
permalink: /tools/
layout: categories
header:
  overlay_image: /assets/images/computer-screen.jpg
  caption: "Photo credit: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Reflections_on_computer_screen.jpg)"
---

# Tools

Please use the below list to filter tools by category.
```

The category layout exists in `layouts/categories.html` and shows an overview of categories:

![image](https://user-images.githubusercontent.com/582444/58340225-9c36e100-7e4b-11e9-8b73-abdde2c3f3fc.png)

The `/tools` page can be reached via permalink.

I now want a copy of this website for a different purpose, where instead of `tool`, the collection is named `database`. Nothing else should change. I expect my `/databases` permalink to show to a similar category overview.

## Actual behavior

Instead of a list of categories at the URL `/databases`, I get only a list of "Recent databases", and it seems that the correct page isn't even loaded, as the header is missing:

![image](https://user-images.githubusercontent.com/582444/58340191-89bca780-7e4b-11e9-8bc0-210c090f46e7.png)

I don't know where this "Recent" list comes from. It seems that the behavior between the two repositories differs, although I cannot see any differences in code or build environment.

## Steps to reproduce the behavior

I copied the existing website, and renamed all occurrences of `tool` with `database`, deleting the existing posts and adding a dummy post.

## Further info

Complete build with trace:

<details>
<pre>
➜ bundle exec jekyll build --trace --verbose
  Logging at level: debug
Configuration file: /Users/werner/Documents/Projects/qualinet/databases/_config.yml
      GitHub Pages: github-pages v193
      GitHub Pages: jekyll v3.7.4
         Requiring: jekyll-github-metadata
Dotenv not found. Skipping
         Requiring: jekyll-seo-tag
         Requiring: jekyll-paginate
         Requiring: jekyll-sitemap
         Requiring: jekyll-gist
         Requiring: jekyll-feed
         Requiring: jemoji
         Requiring: jekyll-include-cache
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-github-metadata
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
         Requiring: jekyll-remote-theme
   GitHub Metadata: Initializing...
            Source: /Users/werner/Documents/Projects/qualinet/databases
       Destination: /Users/werner/Documents/Projects/qualinet/databases/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme mmistakes/minimal-mistakes
      Remote Theme: Downloading https://codeload.github.com/mmistakes/minimal-mistakes/zip/master to /var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1n1q021.zip
      Remote Theme: Unzipping /var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1n1q021.zip to /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs
       EntryFilter: excluded /README.md
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
           Reading: _posts/2019-05-24-test.md
             Theme: Ignoring assets/css/main.scss in theme due to existing file with that path in site.
        Generating: JekyllOptionalFrontMatter::Generator finished in 3.2e-05 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 6.0e-05 seconds.
       Jekyll Feed: Generating feed for posts
        Generating: JekyllFeed::Generator finished in 0.002851 seconds.
        Generating: JekyllRelativeLinks::Generator finished in 0.001537 seconds.
        Generating: JekyllDefaultLayout::Generator finished in 0.006359 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 0.000884 seconds.
        Generating: JekyllTitlesFromHeadings::Generator finished in 0.015767 seconds.
        Generating: Jekyll::JekyllSitemap finished in 0.000965 seconds.
         Rendering: _posts/2019-05-24-test.md
  Pre-Render Hooks: _posts/2019-05-24-test.md
  Rendering Liquid: _posts/2019-05-24-test.md
  Rendering Markup: _posts/2019-05-24-test.md
  Rendering Layout: _posts/2019-05-24-test.md
   GitHub Metadata: Generating for qualinet/databases
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: Calling @client.pages("qualinet/databases", {})
Include cache miss: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/browser-upgrade.html
Include cache miss: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/masthead.html
Include cache miss: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/search_form.html
Include cache miss: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/footer.html
Include cache miss: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/lunr-search-scripts.html
         Rendering: _pages/about.md
  Pre-Render Hooks: _pages/about.md
  Rendering Liquid: _pages/about.md
  Rendering Markup: _pages/about.md
  Rendering Layout: _pages/about.md
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/browser-upgrade.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/masthead.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/search_form.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/footer.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/lunr-search-scripts.html
         Rendering: _pages/contact.md
  Pre-Render Hooks: _pages/contact.md
  Rendering Liquid: _pages/contact.md
  Rendering Markup: _pages/contact.md
  Rendering Layout: _pages/contact.md
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/browser-upgrade.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/masthead.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/search_form.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/footer.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/lunr-search-scripts.html
         Rendering: _pages/databases.md
  Pre-Render Hooks: _pages/databases.md
  Rendering Liquid: _pages/databases.md
  Rendering Markup: _pages/databases.md
  Rendering Layout: _pages/databases.md
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/browser-upgrade.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/masthead.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/search_form.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/footer.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/lunr-search-scripts.html
         Rendering: databases/index.html
  Pre-Render Hooks: databases/index.html
  Rendering Liquid: databases/index.html
  Rendering Markup: databases/index.html
  Rendering Layout: databases/index.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/browser-upgrade.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/masthead.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/search_form.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/footer.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/lunr-search-scripts.html
         Rendering: index.md
  Pre-Render Hooks: index.md
  Rendering Liquid: index.md
  Rendering Markup: index.md
  Rendering Layout: index.md
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/browser-upgrade.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/masthead.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/search_form.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/footer.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/lunr-search-scripts.html
         Rendering: assets/css/main.scss
  Pre-Render Hooks: assets/css/main.scss
  Rendering Liquid: assets/css/main.scss
  Rendering Markup: assets/css/main.scss
         Rendering: _pages/tags.md
  Pre-Render Hooks: _pages/tags.md
  Rendering Liquid: _pages/tags.md
  Rendering Markup: _pages/tags.md
  Rendering Layout: _pages/tags.md
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/browser-upgrade.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/masthead.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/search_form.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/footer.html
 Include cache hit: /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlgs/_includes/search/lunr-search-scripts.html
         Rendering: assets/js/lunr/lunr-en.js
  Pre-Render Hooks: assets/js/lunr/lunr-en.js
  Rendering Liquid: assets/js/lunr/lunr-en.js
  Rendering Markup: assets/js/lunr/lunr-en.js
  Rendering Layout: assets/js/lunr/lunr-en.js
         Rendering: assets/js/lunr/lunr-gr.js
  Pre-Render Hooks: assets/js/lunr/lunr-gr.js
  Rendering Liquid: assets/js/lunr/lunr-gr.js
  Rendering Markup: assets/js/lunr/lunr-gr.js
  Rendering Layout: assets/js/lunr/lunr-gr.js
         Rendering: assets/js/lunr/lunr-store.js
  Pre-Render Hooks: assets/js/lunr/lunr-store.js
  Rendering Liquid: assets/js/lunr/lunr-store.js
  Rendering Markup: assets/js/lunr/lunr-store.js
  Rendering Layout: assets/js/lunr/lunr-store.js
         Rendering: feed.xml
  Pre-Render Hooks: feed.xml
  Rendering Liquid: feed.xml
  Rendering Markup: feed.xml
  Rendering Layout: feed.xml
         Rendering: sitemap.xml
  Pre-Render Hooks: sitemap.xml
  Rendering Liquid: sitemap.xml
  Rendering Markup: sitemap.xml
  Rendering Layout: sitemap.xml
         Rendering: robots.txt
  Pre-Render Hooks: robots.txt
  Rendering Liquid: robots.txt
  Rendering Markup: robots.txt
  Rendering Layout: robots.txt
                    done in 37.061 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
      Remote Theme: Cleaning up /private/var/folders/m6/mj4fjkpj2gj4s22zc3wfnchr0000gn/T/jekyll-remote-theme-20190524-87022-1wsrlg
</pre>
</details>

Some diffs:

```
➜ diff _pages/databases.md ../../vqeg/software-tools/_pages/tools.md
2c2
< permalink: /databases/
---
> permalink: /tools/
9c9
< # Databases
---
> # Tools
11c11
< Please use the below list to filter databases by category.
\ No newline at end of file
---
> Please use the below list to filter tools by category.
\ No newline at end of file
```

```
➜ diff _config.yml ../../vqeg/software-tools/_config.yml
19c19
< title                    : "QUALINET Databases"
---
> title                    : "VQEG Tools and Subjective Labs Setup"
22,25c22,25
< description              : "Subjective test databases"
< url                      : "https://qualinet.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
< baseurl                  : "/databases" # the subpath of your site, e.g. "/blog"
< repository               : "qualinet/databases" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
---
> description              : "Software tools and guidance for the research community."
> url                      : "https://vqeg.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
> baseurl                  : "/software-tools" # the subpath of your site, e.g. "/blog"
> repository               : "vqeg/software-tools" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
103c103
<   name             : "Qualinet"
---
>   name             : "VQEG"
200,201c200,201
< paginate: 20 # amount of posts to show
< paginate_path: /databases/page:num/
---
> paginate: 5 # amount of posts to show
> paginate_path: /tools/page:num/
235c235
<   path: /databases/
---
>   path: /tools/
267c267
<       layout: database
---
>       layout: tool
```

**Comment by slhck** [comment]
The only aspect that is different is that the first project is named `software-tools` and the categories page lives at `/tools`, whereas in the second project, the project is named `databases` and the categories page lives at `/databases`. Could that be an issue? Do the permalinks not resolve properly when they're using the same path as the project's name?

**Comment by mmistakes** [comment]
Your issue is content related. You have two pages that are both using the same permalink.

Your category page at `_pages/databases.md` which sets the permalink to `/databases/`. And then you have `/databases/index.html` which overwrites the category page with a "recent posts" page because it's using `layout: home`.

Delete the [`/databases/index.html`](https://github.com/QUALINET/databases/blob/master/databases/index.html) file and your problem will resolve.

**Comment by slhck** [comment]
Thank you for spotting that! I can confirm it's working now.
