### ISSUE TITLE
Portfolio index appears as a portfolio entry

### ISSUE THREAD

**Issue by gjbunyea** [mmistakes/minimal-mistakes#2168]
I need to include an `index.md` in `_portfolio/` to generate a portfolio page, but when I do this, the index gets cataloged as a portfolio entry. Removing the `index.md` results in no portfolio page, but I don't want it to appear as a link in the portfolio itself. 

I'm not sure if this is a configuration problem, as I've copied the portfolio configuration suggested in the documentation for collections. I also think it could be a bug, but given that you have examples without this problem, I lean toward config issue.

![image](https://user-images.githubusercontent.com/18299544/58385730-e5f60780-7fc2-11e9-9b2f-c3ced31e7095.png)

https://github.com/gjbunyea/www/tree/master/_portfolio - Site development working files
https://github.com/gjbunyea/gjbunyea.github.io/tree/master/portfolio - Site build output
https://gregbunyea.com/portfolio/ - Public site where you can see the issue in the screenshot above.

**Comment by mmistakes** [comment]
Instead of putting the index file in your portfolio collection I'd conert it to a static page instead.

Move `_portfoli/index.md` to `portfolio/index.md` to achieve this. Now it won't be considered a page in the portfolio collection.

**Comment by gjbunyea** [comment]
Perfect! Thank You!
