### ISSUE TITLE
How to stick the sidebar when scroll up and down?

### ISSUE THREAD

**Issue by GMHDBJD** [mmistakes/minimal-mistakes#2175]
Can I stick the sidebar when scroll up and down?

**Comment by mmistakes** [comment]
Which sidebar? Left or right?

Left sidebar sticks by default in modern browsers that support `position: sticky`. The [right side table of contents](https://mmistakes.github.io/minimal-mistakes/layout-table-of-contents-sticky/) can be stuck adding the following to the page's YAML front matter.

```
toc: true
toc_sticky: true
```

**Comment by GMHDBJD** [comment]
I mean the left sidebar.
When I scroll down, it seems that my author__avatar doesn't sticks.
![Screenshot from 2019-06-01 11-25-02](https://user-images.githubusercontent.com/35025882/58750419-2ee50a80-8460-11e9-9a98-3c139e821146.png)

**Comment by mmistakes** [comment]
Looks to me you need to update your browser or the theme to the latest versions. The author sidebar definitely sticks for me in latest Chrome, Safari, Firefox.

**Comment by mmistakes** [comment]
To verify if your browser is updated to the latest check [the demo site](https://mmistakes.github.io/minimal-mistakes/year-archive/) in your browser. It works there for sure in latest browser versions.

![Screen Shot 2019-06-01 at 11 43 43 AM](https://user-images.githubusercontent.com/1376749/58750606-900ddd80-8462-11e9-8173-ce721d47f67e.png)

I just looked at your repo and your sidebar sometimes sticks. As far as I can tell you've made some customizations that might be messing with it.

Stuck sidebar on scroll down

![Screen Shot 2019-06-01 at 11 42 08 AM](https://user-images.githubusercontent.com/1376749/58750588-50df8c80-8462-11e9-88a9-7abe8c89e3d0.png)

Scrolling back up it gets obscured by the sticky header you're adding.

![Screen Shot 2019-06-01 at 11 42 43 AM](https://user-images.githubusercontent.com/1376749/58750612-9ef49000-8462-11e9-829c-7f8125eb3b8d.png)

**Comment by GMHDBJD** [comment]
Oh!
I find that it's sticky until hit the footer.
Can I make it sticky all the time?

**Comment by mmistakes** [comment]
Maybe with JavaScript, I dunno.
I'm just using `position: sticky` property in CSS. I'm sure there is some logic to it, but not sure if you can override that.

Sounds like what you want is to use `position: fixed` with JavaScript that applies it when it needs it. This is how a lot of `sticky` polyfills work for browsers that don't support it.

**Comment by GMHDBJD** [comment]
thx. I'll try it.
