### ISSUE TITLE
Issue with image on top of sidebar when sidebar is collapsed

### ISSUE THREAD

**Issue by thomaspeyrin** [mmistakes/minimal-mistakes#2176]
Hi, 

I added a small image on top of my sidebar, as depicted here: https://mmistakes.github.io/minimal-mistakes/layout-sidebar-custom/

However, I remarked that when making the window smaller, at some point the image on top of the sidebar becomes huge (the sidebar is collapsed, but not the image on top of it). 

Is there a way to either:
- collapse the image together with the sidebar?
- reduce the image size when the sidebar is collapsed ?

Thanks for the help !

**Comment by mmistakes** [comment]
The navigation list in the sidebar is it's own thing, the image and content above it aren't part of the collapse.

If you know CSS it's possible to to hide the image or size it differently. You'll need to use media queries to target the screen size you want to make changes to the image. If you dig through some of the Sass partials used by the theme I'm using Breakpoint mixins to declare the media queries.

A very basic example you could do is, hide the sidebar image, then show on desktop and larger.

```sass
.sidebar {
  img {
    display: none;

    @include breakpoint($large) {
      display: block;
    }
}
```

**Comment by thomaspeyrin** [comment]
Added your code in /_sass/minimal-mistakes/_sidebar.scss , worked perfectly. Thanks !
