### ISSUE TITLE
Embedded local videos don't work with Chrome

### ISSUE THREAD

**Issue by PForet** [mmistakes/minimal-mistakes#2178]
Hi

I'm currently having some issues with embedded videos. When using the following code:
`![foo]({{ "/assets/videos/something.mp4" | absolute_url }})`
it works on Safari but not on Chrome. [A fix](https://stackoverflow.com/questions/48876911/embedded-local-mp4-not-playing-in-chrome-when-running-jekyll-serve-econnreset) seems to be to put the video on mute. Indeed, when embedding the video using html tags:

```
<video muted autoplay loop>
   <source src="/assets/videos/something.mp4" type="video/mp4" width="320" height="240">
</video>
```

then it works fine on both browsers. 
My issue with that fix is that we loose all the responsiveness of the markdown embedding (impossible to put the videos correctly in tables, rescaling, etc...). Is there a way to keep the behaviour of the markdown embedding while muting the video?

Thanks a lot

**Comment by mmistakes** [comment]
Closing as this isn't a theme issue. 

File an issue with Kramdown which is what Jekyll uses for converting Markdown.

The MD you're using above is for a link not to embed video using `<video>` element. I don't think such Markdown exists. Using HTML as you have is perfectly valid and likely the preferred method.

**Comment by mmistakes** [comment]
Also the theme includes a helper for video that wraps the container element to make it responsive.

https://mmistakes.github.io/minimal-mistakes/docs/helpers/#responsive-video-embed
