### ISSUE TITLE
404 error on Cyrillic links

### ISSUE THREAD

**Issue by simptomy-i-lechenie** [mmistakes/minimal-mistakes#2179]
Hello, Michael Rose, mmistakes.
Thanks for the great theme features and beautiful design.

I use the minimal-mistakes on localhost  and then upload it to the Gh-pages.
I am faced with the problem of Cyrillic links on all types of pages.
**For example:**
when i run `jekyll server`, it creates tags in `_site` folder. (e.g http://localhost:4000/ **категория**) but http://localhost:4000/ **category** works.

[screenshot if Cyrillic url](https://imgur.com/5TAk8Kq)
[screenshot if Latin url](https://imgur.com/GJj255y)

The folders **категория** and **categories**  are created in the _site folder.
inside there is an index.html file

but http://localhost:4000/категория - 404 error
http://localhost:4000/categories - it's ok...

[screenshot _site folder](https://imgur.com/v7lYxlP)

### Environment
minimal-mistakes-jekyll 4.16.4
jekyll 3.8.5
jekyll-include-cache 0.2.0
 jekyll-paginate 1.1.0
 jekyll-paginate-v2 2.0.0
 jekyll-seo-tag 2.6.1
 jekyll-sitemap 1.3.1
jemoji 0.11.0
jekyll-archives 2.2.1
jekyll-feed 0.12.1
concurrent-ruby 1.1.5
 i18n 0.9.5
 minitest 5.11.3
 thread_safe 0.3.6
 tzinfo 1.2.5
 activesupport 5.2.3
 public_suffix 3.1.0
 addressable 2.6.0
 bundler 2.0.1
 colorator 1.1.0
 eventmachine 1.2.7 (x64-mingw32)
 http_parser.rb 0.6.0
 em-websocket 0.5.1
 multipart-post 2.1.1
 faraday 0.15.4
 ffi 1.11.1 (x64-mingw32)
 forwardable-extended 2.6.0
 gemoji 3.0.1
 mini_portile2 2.4.0
 nokogiri 1.10.3 (x64-mingw32)
 html-pipeline 2.11.0
 rb-fsevent 0.10.3
 rb-inotify 0.10.0
 sass-listen 4.0.0
 sass 3.7.4
 jekyll-sass-converter 1.5.2
 ruby_dep 1.5.0
 listen 3.1.5
 jekyll-watch 2.2.1
 kramdown 1.17.0
 liquid 4.0.3
 mercenary 0.3.6
 pathutil 0.16.2
 rouge 3.3.0
 safe_yaml 1.0.5
jekyll-data 1.0.0
sawyer 0.8.2
 octokit 4.14.0
 jekyll-gist 1.5.0
minima 2.5.0
tzinfo-data 1.2019.1
 wdm 0.1.1

### system
Windows 10 LTSB
Ruby 2.5.5-1-x64 with MSYS2

I would really appreciate it if you'd help me :)

**Comment by mmistakes** [comment]
Seems like a GH Pages or Jekyll issue. Looking at your screenshot of `_site` it has a folder for `/категория`. I'm assuming there's an `index.html` inside of that.

Could be GitHub or the local Jekyll server has issues serving Cyrillic named folders. Not sure I can offer much other help as this doesn't appear to be a theme problem.
