### ISSUE TITLE
Upgrade to jekyll 3.0

### ISSUE THREAD

**Issue by gyandeeps** [mmistakes/minimal-mistakes#218]
Github supports it now: https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by mmistakes** [comment]
Check the [`jekyll-3` branch](https://github.com/mmistakes/minimal-mistakes/tree/jekyll3). The theme has been 3.0 compatible for some time. I've been waiting for GH to update before merging into master, which I can do now... when I get a free second :wink:
