### ISSUE TITLE
Poem Quote

### ISSUE THREAD

**Issue by vtrnnhlinh** [mmistakes/minimal-mistakes#2183]
## Environment

- Minimal Mistakes version: newest
- Ruby gem or remote theme version:
- Jekyll version: newest
- Git repository URL: https://github.com/vtrnnhlinh/vtrnnhlinh.github.io
- GitHub Pages hosted (if yes provide URL to site): vtrnnhlinh.github.io
- Operating system: Windows 10

## Expected behavior

I try to quote a poem with

```
>Roses are red\
Violets are purple
```
But it shows: Roses are red\ Violet are purple instead of:
>Roses are red\
Violets are purple

I tried

```
>Rose are red\
> Violets are purple,
```
it should show:
>Rose are red\
> Violets are purple

but it also didn't work

## Other

https://vtrnnhlinh.github.io/h%C3%A0nh%20tr%C3%ACnh%20-%20t%C3%A2m%20s%E1%BB%B1/thu-gui-toi-tri-ky/

**Comment by mmistakes** [comment]
The theme has no control over how Markdown is parsed, that is handled by [Kramdown](https://kramdown.gettalong.org/index.html) and Jekyll. Please file an issue with their projects.
