### ISSUE TITLE
Use Font Awesome Kits?

### ISSUE THREAD

**Issue by coliff** [mmistakes/minimal-mistakes#2184]
Font Awesome have changed the way they offer downloads and have a new implementation method which could be useful: https://blog.fontawesome.com/introducing-font-awesome-kits-7134d1d59959
By generating a custom link you can choose 'Latest' so you always get the latest version which has been released. (not sure what the cache life is like though).
Worth taking a look and deciding if it's something worth doing: https://fontawesome.com/

**Comment by mmistakes** [comment]
Nice. I went ahead and created a kit and as far as I can everything looks good. Going to push the change up to `master` and see how things go.

Should hopefully save you from having to PR the newest version of FA and keep it current. 🤣
