### ISSUE TITLE
Is there a way to make the logo bigger

### ISSUE THREAD

**Issue by mmorton234** [mmistakes/minimal-mistakes#2185]
Is there a way that I can edit the _includes or _layouts to make it so that I could change the base size that images and more specifically the logo at the top left of the masthead and where it is displayed. if so where would that be and how would I go about this. Thank you for your time

**Comment by mmistakes** [comment]
You'll have to do this through custom CSS.
I'd suggest inspecting the logo with your browser's web developer tools, which will give you the class (e.g. `site-logo`) names you'll need to adjust the width and height on.

**Comment by mmorton234** [comment]
I'm running into the problem of the masterhead having the size it works off of causing the width changes of the logo to go through but not the height changed

**Comment by mmorton234** [comment]
update I'm figured out how to change the size of the masthead but am still trying to figure out how I can change it so the logo can increase in height without changing the size of the masthead.

**Comment by mmorton234** [comment]
The problem has been solved by editing the /_sass/minimal-mistakes/_masthead.scss
I changed line 18 so the padding was 0 as I wanted the logo to take up the whole box
then I changed the logo size to 3 rem so that the masthead would stay the same size as it was

before this ticket gets closed is there as _sass that relates to feature_rows, thank you
