### ISSUE TITLE
Controllable image sizes for feature_row

### ISSUE THREAD

**Issue by mmorton234** [mmistakes/minimal-mistakes#2187]
## Summary
Ability to change the size of images inside of feature rows 

## Motivation
uses is for more customizability for the user 

## Drawbacks
none unless something else uses "archive__item-teaser" which on first glace I don't see

##
this change can be done by

step one 
in /_includes/feature_row
alt="{% if f.alt %}{{ f.alt }}{% endif %}" >
alt="{% if f.alt %}{{ f.alt }}{% endif %}" width={{f.image_size}} >

step two 
remove width from _archive.scss
add 
    display: block;
    margin-left: auto;
    margin-right: auto;
in its place

**Comment by VascoCorreia** [comment]
Works! Thank you!
