### ISSUE TITLE
Permalink breaking styles?

### ISSUE THREAD

**Issue by ikusalic** [mmistakes/minimal-mistakes#2188]
I'm struggling with initial settings of a new site and I'm wondering if you could help?

I've created a new site with jekyll and then switched to minimal-mistakes via gem option. I've copied _config.yml from master and used it as the basis for the configuration updates. I'm struggling with two issues that I don't know if they are related:

1) When the permalink option isn't commented out, it breaks 404 page
It seems it reverts to something more internal to jekyll. When the option is commented out, the 404 page is properly displayed (content and style)

2) Categories page doesn't have style
the page "/categories/" has the right content, but isn't styled.

Executing "bundle exec jekyll build" results in the following warnings:
>       Generating...
>         Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.
>        Jekyll Feed: Generating feed for posts
>      Build Warning: Layout 'post' requested in _posts/2019-06-10-welcome-to-jekyll.markdown does not exist.
>      Build Warning: Layout 'page' requested in about.md does not exist.

I'm using MacOS, ruby 2.6.3p62, jekyll 3.8.5, and minimal-mistakes-jekyll 4.16.4
My repo is: https://github.com/ikusalic/modelmosaic_com

Could you please help me understand what I'm doing wrong?

**Comment by mmistakes** [comment]
You're not setting the correct layout on your posts and pages.

Consult the documentation. The theme doesn't use `layout: post` or `layout: page`

You'll want to use `layout: single` or the carrots archive ones for your category pages.

https://mmistakes.github.io/minimal-mistakes/docs/layouts/

**Comment by ikusalic** [comment]
Ah, thank you, that fixed the warning with layouts.

The original 2 problems still persist in the same manner as before.

The category pages already use the layout suggested in the documentation:
> jekyll-archives:
>    enabled:
>      - categories
>      - tags
>    layouts:
>      category: archive-taxonomy
>      tag: archive-taxonomy

This should be correct, right?

**Comment by mmistakes** [comment]
I'm not following what the issue with 1 is. I see you have a 404.html page. Jekyll will take that and spit out 404.html with the default layout because that's what you're instructing it to do.

If you want styling applied use one of the theme's layouts. If you want a different permalink set that in it's YAML front matter.

Not sure how you're getting a /categories/ page. I see no such page in your repo nor does the Jekyll Archives plugin generate that. It builds the actual tag or category pages, not a page that lists all of your site's categories.

Seems to me there's a few Jekyll config and usage details you're getting tripped up with and not the theme itself. I'd widen your search to asking for Jekyll help on Stackoverflow or Jekyll's Talk forum.

**Comment by ikusalic** [comment]
The issue with permalink setting (the one from master of the theme) is that it adds or removes somehow the 404 page:

Missing page when permalink is commented out: "#permalink: /:categories/:title/"
<img width="909" alt="404 on permalink commented out" src="https://user-images.githubusercontent.com/1434229/59554266-c8540680-8fa0-11e9-9175-970d67c1831f.png">

Missing page when permalink config is left in: "permalink: /:categories/:title/"
<img width="693" alt="404 on permalink config present" src="https://user-images.githubusercontent.com/1434229/59554267-c8540680-8fa0-11e9-8204-55c8d736d885.png">

Hm, not sure where the categories come from then, I assumed the plugin must be generating them:
<img width="765" alt="categories" src="https://user-images.githubusercontent.com/1434229/59554265-c8540680-8fa0-11e9-9cd4-802b5e9c8404.png">

Thank you for looking into this and the support so far. And for pointing out the better resources. I'll continue from those if the questions are not relevant here.

**Comment by mmistakes** [comment]
Your webserver expects a custom 404 page in a specific location and filename.

So changing the permalink in the Jekyll config will alter were that page gets spit out by Jekyll.

You can override it by setting `permalink: /404/` (or whatever you want it named) in the 404.html source file's YAML frontmatter.

This is all basic Jekyll 101 stuff covered in their docs.

**Comment by mmistakes** [comment]
Also Jekylls local server doesn't necessarily work with custom 404 pages. You'll need to test this stuff on your actual webserver were the site will be hosted. You may need htaccess or nginx to get it working too.

Closing as these are not relevant to the theme.
