### ISSUE TITLE
Screenshots not matching the theme

### ISSUE THREAD

**Issue by cifkao** [mmistakes/minimal-mistakes#2189]
## Motivation

The theme looks quite different from the 3-years-old screenshots in the docs, at least in my browser:
![image](https://user-images.githubusercontent.com/8046580/59681775-f6219100-91d4-11e9-8e91-ba7c40edd561.png)

Note the alignment of the navigation (left-aligned in screenshots) and the post headings (underlined and different size and color than in screenshots).

## Suggestion

The screenshots should be updated. It would also be great to know how to obtain something closer to the old look (which is better in my opinion).

**Comment by mmistakes** [comment]
Feel free to submit pull requests with updated screenshots. The demo site's source files are all in [`/docs`](https://github.com/mmistakes/minimal-mistakes/tree/master/docs).

**Comment by danieltorrecillas** [comment]
@mmistakes, what's the quickest and/or best way to remove the horizontal line that appears under headings?

**Comment by mmistakes** [comment]
By editing/overriding the CSS.
