### ISSUE TITLE
Error: could not read file (/path/to/file): no implicit conversion of Fixnum into Array

### ISSUE THREAD

**Issue by ryan-p-randall** [mmistakes/minimal-mistakes#219]
Hi! I just updated after the bump to Jekyll 3. Now after running `bundle exec jekyll build` I'm getting the above error message for every single post. Jekyll also adds `Error: user lambdas.json doesn't exist`  

Do you know what would cause these errors or how to fix them? Thanks for any help.

**Comment by mmistakes** [comment]
Do you know what `lambdas.json` is? That's not part of the theme. Sounds like maybe a file specific to your setup that's causing problems.

**Comment by mmistakes** [comment]
Solution [could be here](https://github.com/jekyll/jekyll/issues/3796). Sounds like maybe some Node related files are being processed by Jekyll when they should be ignored. I took a look at your repo an didn't see anything out of the ordinary. You're excluding `node_modules` so not sure where this `lambdas.json` nonsense is coming from.

**Comment by mmistakes** [comment]
And one other idea, maybe it's related to your Jekyll plugins. I have zero experience with `jekyll-scholar`. Perhaps there's a bug there with Jekyll 3.

**Comment by ryan-p-randall** [comment]
Turns out that this was _two_ different issues. I'll explain them both if anyone else bumps into them.  

The first, which resulted in the error containing `no implicit conversion of Fixnum into Array`, was because I had `categories: 2014` in the posts' YAML. That should have been a singular `category:` or either a YAML list or an [category1, category2] comma-separated string. [See here.](http://jekyllrb.com/docs/frontmatter/#predefined-global-variables)  

The second, the `lamdas.json` business, was fixed when I added a directory that contains `Reveal.js` to the `exclude` section of `_config.yml`, so I assume that's the culprit. I saw it making that error in a different issue: https://github.com/dploeger/jekyll-revealjs/issues/2   

It's a short lived victory, though: now I'm getting a different error related to the SCSS conversion. I'll close this & start a different issue for that one.

**Comment by ryan-p-randall** [comment]
Just in case anyone else runs into this error—after updating the source for reveal.js, I'm now able to build those pages with Jekyll and put them up on Github Pages. 

So updating Reveal.js seems to be all that's needed to fix the `lambdas.json doesn't exist` error.
