### ISSUE TITLE
Not building because of typo in _includes/skip-links.html

### ISSUE THREAD

**Issue by redtux** [mmistakes/minimal-mistakes#2192]
- Minimal Mistakes version: 4.16.4

## Expected behavior

The site should build without problems. :smiley_cat: 

## Steps to reproduce the behavior

Try to build with Jekyll, and you will get the following error:

> Liquid Exception: Liquid syntax error (/home/redtux/tmp/mmistakes/_includes/skip-links.html line 4): Unexpected character { in "{{{ site.data.ui-text[site.locale].skip_primary_nav | default: 'Skip to primary navigation' }}" in /_layouts/default.html

## Fix

Delete the spare `{` on line 4.

**Comment by mmistakes** [comment]
Good catch, thanks @redtux

**Comment by redtux** [comment]
@mmistakes, thanks for fixing it so fast. Unfortunately, I still get an error (probably unrelated):
`Liquid Exception: Could not locate the included file 'skip-links.html'…`

Thank you for this great theme! :+1:

**Comment by mmistakes** [comment]
If you have a public repo share the link below and I can take a look. I haven't released a gem of the theme yet that has the skip links (it's on `master`).

So not sure how you're using the theme but that could be the problem. I'm not seeing any errors on my end or on GitHub Pages which seems to be building the demo site fine. They might have more lax Liquid error control as the `{{{` made it through fine before the fix.

**Comment by redtux** [comment]
Oh, my fault then! I had noticed the change in [`_layouts/default.html`](https://github.com/mmistakes/minimal-mistakes/blob/14366715006192e63636011649ee9d16befe0a55/_layouts/default.html) on commit 14adf5c – and thus included `{% include_cached skip-links.html %}` in my proper default.html (just testing locally atm) without having checked back if it was in the gem or not (as the file states `4.16.4` in the copyright notice). :smile_cat: Well, so I at least could discover the `{` typo… :smiley_cat:

**Comment by mmistakes** [comment]
Ah yeah, you need to add the new include file too. That's what the error Jekyll is shouting about... you're missing [`_includes/skip-links.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/skip-links.html) in your repo.
