### ISSUE TITLE
Forgotten console.log in lunr-en.js?

### ISSUE THREAD

**Issue by halirutan** [mmistakes/minimal-mistakes#2193]
I inspected my site and came across a mysterious print in the log console. Is this supposed to be there?

https://github.com/mmistakes/minimal-mistakes/blob/82e9aee6a8e5351f71ca4226bc6cb2085c9a8671/assets/js/lunr/lunr-en.js#L25

**Comment by mmistakes** [comment]
It's harmless. But if you want to submit a pull request with it's removal feel free to.

**Comment by halirutan** [comment]
Sorry, for not jumping on the PR. It's been crazy these days.
