### ISSUE TITLE
PWA support [enhancement]

### ISSUE THREAD

**Issue by Oxyenyos** [mmistakes/minimal-mistakes#2196]
## Summary

Make this theme PWA ready! I was thinking of adding PWA support to this theme. There would be two direct advantages, one the site can work offline due to available service worker and the site could be installed as app.

## Motivation

I've successfully implemented PWA on v4.15 installation, I was hoping to push the commits upstream.

**Comment by mmistakes** [comment]
@Oxyenyos Do you have an example of PWA implimentation with the theme you've done? In my experience setting up a PWA can be a little fiddly and knowing how customizable the theme is not sure how well it will play with that.

Last thing I want is to enable another optional thing that needs to be over configured by the user depending on what features they're using.

**Comment by Oxyenyos** [comment]
@mmistakes You can see the PWA implementation on [blog.alokprateek.in](https://blog.alokprateek.in) and the repo at `github.com/Oxyenyos/mmblog`.
The PWA I've implemented, I only needed to add a service worker file in root directory, and a registry function that goes in head partial. Apart from registering a service worker we also need a manifest, which is generated as part of https://realfavicongenerator.net/ icon package, otherwise we could supplement the head with a `manifest.json`, that pulls all values it needs from `_config.yml`. Infact `_config.yml` has all the essential values required for manifest to work, and PWA to be installable

**Comment by Oxyenyos** [comment]
Another thing we need to add 
```
---
layout: none
---

```
to the manifest.json, so it processes normally as JSON

**Comment by lsolesen** [comment]
So is this all that is really necessary to make a MM site PWA-ready? https://github.com/lsolesen/cykel-ruter-dk-jekyll/pull/1

**Comment by Oxyenyos** [comment]
Yep. I can't seem to push only those changes to to repo without messing up the commit tree. Will do commit squashing and deletion as I get free. Or commit using another account.

**Comment by lsolesen** [comment]
@Oxyenyos You could also consider not having your own website as a fork of MM, and then use the remote_theme feature. That really works very well for me. Then you can have a fork of MM, where you can suggest improvements. That is off course up to you.

**Comment by lsolesen** [comment]
@Oxyenyos I am not sure whether @mmistakes will accept a pull request with this, but it should probably be settings in the _config.yml, hvor you can enable PWA, as it requires you to manually enter e.g. the icons?

**Comment by Oxyenyos** [comment]
@lsolesen Everything that is in manifest can be mapped to config. Even the icons.

Also mapping the icons to config would reduce the effort to insert favicons and icons in custom head.
working on that too

**Comment by lsolesen** [comment]
@Oxyenyos Any progress on this issue?
