### ISSUE TITLE
Adding third column to one of the pages

### ISSUE THREAD

**Issue by pranav6670** [mmistakes/minimal-mistakes#2198]
I am working on a page where I want some contents in the right sidebar. How can I do that?

**Comment by mmistakes** [comment]
Adapt the `single` layout to place your contents inside of the [`<aside></aside>` element](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L38-L43).

**Comment by pranav6670** [comment]
So I will have to make changes in the `single.html` file? Sorry for these questions, I am new to this.

**Comment by mmistakes** [comment]
Yes. The theme only supports a table of contents in the right sidebar. Anything else you will need to customize the theme to do.

**Comment by pranav6670** [comment]
Customize in what sense? What files will I've to change?

**Comment by mmistakes** [comment]
See my comment above. I linked to lines in the layout file you’ll need to edit and build off of.

**Comment by pranav6670** [comment]
Thank you. Will try.
