### ISSUE TITLE
Conversion error: Jekyll::Converters::Scss encountered an error while converting '/assets/css/main.scss'

### ISSUE THREAD

**Issue by ryan-p-randall** [mmistakes/minimal-mistakes#220]
After the bump to Jekyll 3, I'm getting this build error: `Conversion error: Jekyll::Converters::Scss encountered an error while converting '/assets/css/main.scss': Invalid CSS after "...r : #3b5998": expected "{", was ";" on line 44`. 

That seems to be the `$facebook-color:` line imported from `variables.scss` but I have no idea what's tripping up the converter.

Any ideas? Again, thanks for the help!

**Comment by mmistakes** [comment]
Did you make any changes to the SCSS files? The un-altered ones work just fine with Jekyll 3 as I haven't received any errors and it make the trip fine through GitHub Pages where I host the demo.

My guess is you're missing a `;` or `{` after a declaration as the error suggests. It can be tricky finding which line that's on though since it's likely in a SCSS partial.

**Comment by mmistakes** [comment]
Looks like you're using Bigfoot.js. I'd start by disabling those `@import`s in `main.scss` and see if it builds. Probably something in there it doesn't like. If that doesn't work then disable each import and enable 1 by 1 to find the problem partial. Then check the lines for missing `;`, `{`, `}`, or duplicates.

**Comment by mmistakes** [comment]
Had a free second and looked at you `_sass` partials. Wonder if line 42 in `variables.scss` is your problem. `=======` underneath `// Links` is not valid and probably breaking the compiler. If this existed before updating to Jekyll 3 then perhaps you just got lucky that it didn't fail... or silently failed. When in doubt diff against the files in my repo to see where the errors might have creeped in.

![yaml](https://cloud.githubusercontent.com/assets/1376749/12797245/f8d9b97c-ca90-11e5-8dcb-77ae0503fe7f.jpg)

**Comment by ryan-p-randall** [comment]
That's exactly the culprit. I guess I wasn't careful enough comparing the HEAD and new versions when I pulled everything in from your update.  

Thanks so much!

**Comment by ryan-williams** [comment]
FWIW I think I saw this issue caused by two lines each containing `---` at the top of an `.scss` file; I don't remember why I'd added them (likely a hack to get something about Jekyll-plumbing/processing to work, maybe no longer necessary?), but removing them seemed to resolve this error.

**Comment by ssy341** [comment]
I got  this build error : ` Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    Invalid GBK character "\xE2" on line 54
`
here is main.scss file:
```scss
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@charset "utf-8";

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials
```
if I remove ‘---’ then build with no error ，but can't get main.css file

**Comment by rchatham** [comment]
@ssy341 

Any links to the place that told you to do that? 

I'm having the same issue where the new jekyll updates are not compiling the scss to a main.scss file.

**Comment by mmistakes** [comment]
@rchatham If you're on Windows try Jekyll's guide for installing. Encoding issues can be a common problem depending on how your Ruby environment is setup. It happens a lot with CI setups, Docker, and the like.

https://jekyllrb.com/docs/installation/windows/#encoding

**Comment by DOEHOONLEE** [comment]
Hi!
I got the same problem, but I can't seem to work it out.
```
 Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Internal Error: Invalid UTF-8
                    ------------------------------------------------
      Jekyll 4.0.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
```
I have been searching solution for this for like a week now. Could anybody please explain what's going on?

Thank you in advance!

**Comment by iBug** [comment]
@DOEHOONLEE Not until you provide more information, such as the content of your `assets/css/style.scss` as well as other relevant files.

**Comment by DOEHOONLEE** [comment]
@iBug  Thank you for the fast reply and I'm so sorry about not providing more information.

This is what I have on style.scss

```
---
---

@import "jekyll-theme-minimal";

#main-title {
    text-align: center;
    opacity: 0.9;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}
```

Is the "Please append '--trace' to the 'serve' command for any additional information or backtrace" part also an error? I only saw the style.scss error last week. I have no idea what is going on :(

**Comment by mmistakes** [comment]
@DOEHOONLEE What is jekyll-theme-minimal? That's not something coming from this theme.

**Comment by iBug** [comment]
@DOEHOONLEE Two things surfacing at first:

1. `jekyll-theme-minimal` doesn't appear to be related to this theme (Minimal Mistakes by Michael Rose), but rather [this one](https://github.com/pages-themes/minimal).
2. If you're building on Windows then there's (probably) a hidden [UTF-8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark) at the beginning of the file which you'll need to find a way to get rid of. This is a blind guess (you haven't yet provided the error trace) but my experiences point in this way.

**Comment by DOEHOONLEE** [comment]
I added
```
gemspec

gem "jekyll-theme-minimal"
```
to Gemfile and now I'm getting

![image](https://user-images.githubusercontent.com/20305442/81711971-1d4d1500-94af-11ea-8492-730f2bd6cdba.png)


Oh, I am sorry I got the wrong repository :O

**Comment by ninja-tech** [comment]
Hi 
I am getting below error 

`
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    No such file or directory @ dir_chdir - /github/workspace/docs
`

**Comment by UjjwalSaini07** [comment]
What Should i do i have **_same error_** 
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':

![issue2](https://user-images.githubusercontent.com/73696489/154911318-a259eb41-0251-4c36-afb3-fda40ff56f28.PNG)

**_Please help me in that....._**

**Comment by asolene** [comment]
> What Should i do i have **_same error_** Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
> 
> ![issue2](https://user-images.githubusercontent.com/73696489/154911318-a259eb41-0251-4c36-afb3-fda40ff56f28.PNG)
> 
> **_Please help me in that....._**

I have the same problem and i don't know what it means... it was all good before so i don't know what's wrong with my css...

**Comment by mmistakes** [comment]
If you look through the stacktrace above there's a conversion error with `assets/css/style.scss`. This theme doesn't use that file.

If you look a few lines above that it indicates `Theme: jekyll-theme-primer`... again not this theme.

**Comment by Angeldlc99** [comment]
> @asolene My **_Bugs Error Fixes_** and i know what should the mistake i do
> ![Capture](https://user-images.githubusercontent.com/73696489/156301203-d2480dee-00b0-419e-8941-7423ecb4b72b.PNG)
> .
> After so many errors in it but at last **_i deployed my Website Successfully._**

How did you solved it? I have the same error...

**Comment by mike-koala-bear** [comment]
I had an error Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    No such file or directory @ dir_chdir - /github/workspace/docs

**Comment by mike-koala-bear** [comment]
How did you solve it?

**Comment by Jarcovision** [comment]
I have the same error.

**Comment by espoirMur** [comment]
I think I am in the same basket.. some issue here.

**Comment by viniciusgribas** [comment]
> FWIW I think I saw this issue caused by two lines each containing `---` at the top of an `.scss` file; I don't remember why I'd added them (likely a hack to get something about Jekyll-plumbing/processing to work, maybe no longer necessary?), but removing them seemed to resolve this error.

I had the same problem, and solved it this way. Many thanks!

problem:
![image](https://user-images.githubusercontent.com/63691577/162009864-591f39a0-2a3a-4c52-9ad5-9e7a8983e537.png)

solved:
![image](https://user-images.githubusercontent.com/63691577/162009911-22b56cd7-ead1-4f3b-804e-ac8a3a8782ec.png)

**Comment by SebSwan** [comment]
Same problem here! It works locally but failed on github page deployment since i configured jekyll-seo-tag.
After removed the two lines containing `---` in front of main.scss, it works locally but not with the github page configuration, i get a 404 error when i try to reach `https://myrepo.github.io/website/css/main.css`

**Comment by joaovxsantos** [comment]
I managed to solve
One "." before the css file and images link is what was missing.

before:
![image](https://user-images.githubusercontent.com/97799540/175194753-ddb73164-200d-45ee-a8db-ac62de2f4c88.png)

after:
![image](https://user-images.githubusercontent.com/97799540/175194803-c83401fa-f6e0-4be6-ab7f-8bdfdddd2256.png)
