### ISSUE TITLE
Header text font, size and position and effects.

### ISSUE THREAD

**Issue by pranav6670** [mmistakes/minimal-mistakes#2201]
How can I change header text font, size or positioning? Also, how can I add the effect like [this](https://codepen.io/AlainBarrios/details/OEOKgm) to header text? Thank you

**Comment by mmistakes** [comment]
All of the header elements have class names that can be targeted and styled with CSS. If that's something you aren't comfortable with I'd suggest seeking out some CSS tutorials.
