### ISSUE TITLE
nokogiri-1.10.3

### ISSUE THREAD

**Issue by nesterenkoyana** [mmistakes/minimal-mistakes#2202]
Hi there, trying to use your theme and keep getting error "could not find nokogiri-1.10.3 in any of the servers". I've run "bundle install", "bundle update", and "gem install nokogiri -v 1.10.3". Error is still there. Please advise. Thank you!

**Comment by mmistakes** [comment]
See #328 for suggestions on fixes. 
Nokogiri isn't used by the theme, it's a GitHub Pages gem and/or it's dependencies.
