### ISSUE TITLE
change facebook comment font color

### ISSUE THREAD

**Issue by lpossamai** [mmistakes/minimal-mistakes#2204]
Hi.

How can I change the font color of a facebook comment to be white, please?

![Screenshot from 2019-07-03 22-29-54](https://user-images.githubusercontent.com/17607576/60584751-23c82600-9de2-11e9-9b74-fe037c7364a2.png)

**Comment by mmistakes** [comment]
Don't think Facebook lets you control the color that way. You can either use the [light or dark color scheme](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#facebook-comments) for all comments.

You'll have to dig through their API to see if it's possible.
