### ISSUE TITLE
New icon for ResearchGate not appearing

### ISSUE THREAD

**Issue by tomchor** [mmistakes/minimal-mistakes#2206]
I have been trying to include a custom icon for my ResearchGate profile and ORCID but nothing seems to work.

The closest I've been was to include the `_includes/author-profile-custom-links.html`, which has the following lines:

```
  <li>
    <a href="https://www.researchgate.net/profile/Tomas_Chor" itemprop="sameAs">
      <i class="ai ai-researchgate-square ai-fw"></i> ResearchGate
    </a>
  </li>

  <li>
    <a href="https://orcid.org/0000-0003-0854-3803" itemprop="sameAs">
      <i class="ai ai-orcid-square ai-fw"></i> ORCID
    </a>
  </li>
```

But as you can see from [my page](https://tomchor.github.io/), the links are there, but the icons are not. I copied this exactly from a person that had those icons working so I'm not sure what's happening.

**Comment by coliff** [comment]
The Minimal Mistakes theme includes [Font Awesome icons](https://fontawesome.com/) - so you can use any of those. ResearchGate is available: https://fontawesome.com/icons/researchgate?style=brands. To use: `<i class="fab fa-researchgate"></i>`

I don't think Orcid is available as part of Font Awesome though so maybe the person who had it working used their own icons. (Font Awesome icons class names always begin with `fa`)

**Comment by coliff** [comment]
You can vote (with a thumbs up) to request that icon to be included with Font Awesome here:
https://github.com/FortAwesome/Font-Awesome/issues/4401

**Comment by tomchor** [comment]
@coliff thanks for the reply. I'm new to mmistakes and jekyll so I'm still struggling to make sense of everything.

I applied your suggestion down but it didn't change anything. So maybe something else is happening?

Also, here's [the repo](https://github.com/jonbra/jonbra.github.io/blob/master/_includes/author-profile-custom-links.html) from which I copied this approach. As you can see from [his website](https://jonbra.github.io/) it seems to work for him. I've looked for those icons defined within his repo, but couldn't find anything.

**Comment by coliff** [comment]
Hi @tomchor  - that site used these icons: https://jpswalsh.github.io/academicons/

So if you add `<link rel="stylesheet" href="https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css">` to your `custom-head` then you'll be able to use the orcid and researchgate icons like that site did.

**Comment by tomchor** [comment]
@coliff Thanks a lot! That worked. So I'm guessing that's an alternative to Font Awesome?

**Comment by coliff** [comment]
it's like an unofficial Font Awesome 'add-on'.

I'd recommend copying that icon font and CSS to your local site in case that site goes offline.
Also that CDN link is from https://rawgit.com/ which is closing down in October.

**Comment by tomchor** [comment]
@coliff Yeah, probably copying it locally is a good idea. Do you have any material I can read on how to do so? I'm not sure exactly what to copy and how to reference it locally.

**Comment by coliff** [comment]
I think you can use this CDN instead which is unlikely to go offline:
`https://cdn.jsdelivr.net/gh/jpswalsh/academicons/css/academicons.min.css`
so use this instead:
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons/css/academicons.min.css">`

**Comment by tomchor** [comment]
@coliff Thanks!
