### ISSUE TITLE
Category specific header

### ISSUE THREAD

**Issue by claudiuconstantin** [mmistakes/minimal-mistakes#2207]
Is there any way to configure category-specific header for posts? Example: all posts in the "travel" category would all have something like this applied:
```
header:
  overlay_color: "#333"
  show_overlay_excerpt: false
```

**Comment by mmistakes** [comment]
You can add that YAML front matter to a specific category archive page if you're building those, but there is now way to apply that to a post that has a specific category assigned to it. You're treading into custom theme territory to do that.

**Comment by claudiuconstantin** [comment]
Got it, thanks a lot; congratulations for your awesome work!
