### ISSUE TITLE
menu button misbehaving

### ISSUE THREAD

**Issue by ryan-p-randall** [mmistakes/minimal-mistakes#221]
Do you know what would cause the folding menu button to always show and have reversed colors from what is expected? I've tried going through all the css, html, and javascript files for quite literally hours, but I can't catch what might be the cause of this.

![menu_large](https://cloud.githubusercontent.com/assets/850915/12839915/0b0e4bde-cb9b-11e5-95fc-799088573758.png)  

![menu_small](https://cloud.githubusercontent.com/assets/850915/12839917/119a1e38-cb9b-11e5-8036-c3f60e6c56ad.png)

I also tried running `grunt` but that didn't fix it, so I have no idea where I messed this up. If you have any ideas, I'd appreciate them!

**Comment by mmistakes** [comment]
If you use your browsers web dev tools to inspect the page it'll help troubleshoot what's going wrong. Your pages are throwing the following Javascript error which tells me something you might have changed or added there broke things.

```js
Uncaught TypeError: $(...).fitVids is not a function
```

My guess is it's Bigfoot.js or a typo when you added that. One `;` can really screw things up, so double check the commits when you made any script edits to see if you introduced a typo or other bug. That and diff against the scripts in my repo to maybe find out where you went wrong.

Fix the Javascript and the menu will correct itself. None of the scripts are working on your site which breaks the nav and the class names that get applied to it to correctly hide/style things.

**Comment by ryan-p-randall** [comment]
Thanks for the pointers and helping narrow down the cause!

**Comment by mmistakes** [comment]
No problem.
