### ISSUE TITLE
how to increase post line width?

### ISSUE THREAD

**Issue by khanhha** [mmistakes/minimal-mistakes#2214]
Hello, 
Thanks for making the awesome theme.

As you can see,  the lines on my post occupy just half of the page, which looks very narrow. 
Is there any setting to let the post make full use of the page width?

https://khanhha.github.io/posts/SMPL-model-introduction/
![img](https://i.ibb.co/qd6B1rp/Untitled.png)

I just came across [a similar issue](https://github.com/mmistakes/minimal-mistakes/issues/884), and tried to change post layout from single to archive, but it still looks the same. 

The answer to this issue suggest modifying *.ass file, but I am using the remote theme, which means that there's no _include in my repository. Is there any way to get around it? 

Thanks in advance, 
I look forward to hearing from you soon

**Comment by mmistakes** [comment]
Use the `wide` modifier. It's in [the documentation](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#wide-page) and also mentioned several times if you search through the closed issues.

```yaml
layout: single
classes: wide
```

**Comment by khanhha** [comment]
Thank you. 
I added class: wide below _posts in the_config.yml. 
It works now.

**Comment by DOEHOONLEE** [comment]
Does anybody know how to fix it back to default width? For some reason, mine does not show sidebar with author information and the widened width of post would not come back to normal even after removing "classes: wide"

**Comment by prichelle** [comment]
And id you would like to have the text spanning more place on the page + a sticky table of content ?
I wasn't able to have my table of content appearing close to the right side with my text taking more place.
The text in my post take always the same place and when the page is in full view mode, there are a lot of space on the right side (even with the table of content).

**Comment by benslack19** [comment]
> 

@prichelle were you able to figure this out? I'd like to keep the sticky table of contents as well and just widen the whole content.

**Comment by prichelle** [comment]
> > 
> 
> @prichelle were you able to figure this out? I'd like to keep the sticky table of contents as well and just widen the whole content.

Unfortunately not ! If you find any way to do it, please let me know.
Example:
https://prichelle.github.io/apic/APIC-certmanager/

**Comment by jlconlin** [comment]
This isn't working for me. I have the following in the header of my page

```
---
title: MyTitle
layout: single
classes: wide
---
```
and it doesn't look any different than if I don't have `classes: wide`.

I'm using the gem version 4.24.0.

Please advise.

**Comment by kbala97** [comment]
Does not work for me either. The "posts" page is not showing up "wide". Below is my config.yaml file

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: false
      comments: # true
      share: true
      related: true
      show_date: true

**Comment by dasiths** [comment]
You can use this.

```
max-width: calc(100vw - 200px);
```

![image](https://github.com/mmistakes/minimal-mistakes/assets/16128850/1f6667a4-23f0-4d65-bf66-a373ea5eb201)
