### ISSUE TITLE
Paginate Problem 

### ISSUE THREAD

**Issue by mmorton234** [mmistakes/minimal-mistakes#2223]
I have an 'index.html' file . in '/_pages' and when I surpass the pagination limit with posts (paginate: 5 and I have 6 posts) then I will get the error 
```
Error reading file /Path/To/minimal-mistakes/index.html: No such file or directory @ rb_sysopen - /Path/To/Downloads/minimal-mistakes/index.html
```
I also took a screenshot of the site overview and see there are two index.html in the site 
I think there is a problem in how it saves the index.html in the way I configure it or the default one

in '-/pages/index.html'
```
---
permalink: /index
layout: home
---

```
in '_config.yml'
```
paginate: 3 # amount of posts to show
paginate_path: /_pages/page:num/
```

![Screen Shot 2019-07-30 at 2 06 36 PM](https://user-images.githubusercontent.com/44326868/62154549-ee293680-b2d4-11e9-87b6-b2920373d5e9.png)

**Comment by mmistakes** [comment]
What you can try is moving the index.html out of _pages and into the root of your project.

Jekyll's pagination plugin is extremely picky and doesn't work when you deviate from its conventions.

Closing as this isn't a theme issue. Please file a bug report with Jekyll or ask for help on their talk forum.

**Comment by mmistakes** [comment]
Your `permalink` is likely the problem too. Try `permalink: /` instead.
