### ISSUE TITLE
Refactor implementation of tags and categories to make it easier to use in collections

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2224]
## Summary

It is a pain to implement categories and tags in collections. This approach will make it easier.

## Motivation

It should be easier to implement this even though Jekyll does fully support it. This approach will make it much easier without changing too much in the theme.

## Drawbacks

The liquid code is a bit convoluted and probably not as fast, at it could be. 

I have created a collection with tricks. In my collection I want to use tags and categories.

In my _config.yml I specify which archive_path I want to use: https://github.com/lsolesen/legestue-net-jekyll/blob/refactor-collection/_config.yml#L294

Then I create my tags archive page https://github.com/lsolesen/legestue-net-jekyll/blob/refactor-collection/_pages/tag-activity-archive.md and my category page https://github.com/lsolesen/legestue-net-jekyll/blob/refactor-collection/_pages/category-activity-archive.md for that specific collection.

Then I have the same functionality as tags and categories for _posts.

Only to add these two layouts:

https://github.com/lsolesen/legestue-net-jekyll/blob/refactor-collection/_layouts/collection-categories.html

https://github.com/lsolesen/legestue-net-jekyll/blob/refactor-collection/_layouts/collection-tags.html

If you like the approach I can make a proper pull request.

**Comment by lsolesen** [comment]
Forgot minor rewrites of https://github.com/lsolesen/legestue-net-jekyll/blob/9e77a048443a428ac2249977c3ef80624a239101/_includes/category-list.html and https://github.com/lsolesen/legestue-net-jekyll/blob/9e77a048443a428ac2249977c3ef80624a239101/_includes/tag-list.html

**Comment by mmistakes** [comment]
I’d prefer not to touch this until tags and categories are officially supported in collections.
Last thing I want to do is add more bloat and hacky approaches to something that may change anyways if/when Jekyll implements it.

**Comment by lsolesen** [comment]
I think that is a pity. It is basically not touching the existing code, and only adds two extra layouts. But it will solve the tags / categories pitfalls for collections in the theme until it is/if it is implemented in Jekyll (which seems to take a long, long time). But I know that you are the one who needs to look after the theme.

**Comment by gjbunyea** [comment]
@lsolesen Just want to 👍 this. This is exactly what I was looking for - Thanks!
