### ISSUE TITLE
Lunr search on development uses wrong url

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2225]
## Environment

- Minimal Mistakes version: 4.16.5
- Ruby gem or remote theme version: 
- Jekyll version:
- Git repository URL: http://github.com/motionsplan/motionsplan-dk-jekyll
- GitHub Pages hosted (if yes provide URL to site): yes
- Operating system:

## Expected behavior

That the correct link is used in search on development.

## Steps to reproduce the behavior

All links on the site works except for the prepended baseurl in Lunr search - there it sets `http://localhost:8080` when I am on my development environment AWS Cloud9. When the true baseurl is something like this: https://a-complicated-id.vfs.cloud9.eu-west-1.amazonaws.com/

**Comment by mmistakes** [comment]
Not sure I follow what the issue is. I don't see a `baseurl` defined in your [_config.yml](https://github.com/motionsplan/motionsplan-dk-jekyll/blob/gh-pages/_config.yml#L23).

**Comment by lsolesen** [comment]
But when I do not define a baseurl all other links works correctly which
makes it possible to have the same config for prod and dev. Only the Lunr
search does not work. :/

fre. 2. aug. 2019 18.17 skrev Michael Rose <notifications@github.com>:

**Comment by mmistakes** [comment]
I'm still not following what your issue is. What links don't have the correct `baseurl`?

**Comment by lsolesen** [comment]
The links that is displayed after searching in the search results.

fre. 2. aug. 2019 19.35 skrev Michael Rose <notifications@github.com>:

**Comment by mmistakes** [comment]
`baseurl` works as intended for me in the [`/test` site](https://github.com/mmistakes/minimal-mistakes/tree/master/test) when running locally.

What are you setting as your `baseurl` when testing? I see above you mentioned `https://a-complicated-id.vfs.cloud9.eu-west-1.amazonaws.com/`. If that's the case then that could be your problem as `baseurl` is meant to be used a subfolder and not the domain. `url` would be the correct usage. See this blog post from a Jekyll maintainer on its [correct usage](https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/).

There is a small caveat when setting `url` as well. Jekyll runs in `JEKYLL_ENV=development` by default and it overwrites whatever you set to the localhost server address. The only way to keep the `url` you've set is by running Jekyll in production mode with `JEKYLL_ENV=production`.

How to set environments are covered in [their documentation](https://jekyllrb.com/docs/step-by-step/10-deployment/#environments).

**Comment by iveney** [comment]
hmmm, I may be running into this after I upgraded to jekyll 4.2.0.

When using `bundle exec jekyll serve`, everything is resolved correctly to use `http://localhost:4000`, except the search result, which is the actual url of my site `http://www.ivansiu.com`. 

If I remove the `url: "https://www.ivansiu.com"` line in my `_config.yml` then it works.

Reproducible [here](https://github.com/iveney/ivansiu.com/tree/upgrade-jekyll)
