### ISSUE TITLE
GitHub unknown tag error

### ISSUE THREAD

**Issue by callywuthrich** [mmistakes/minimal-mistakes#2226]
Hi! Thanks for the awesome theme! 
I was hoping you could help me push my Jekyll site to Github pages. I was able to add all of my Jekyll files to a GitHub repo (https://github.com/callywuthrich/archesguides) but when I go to the repo web address, none of my files show up. 

Initially, GitHub gave me an error message because the _layouts file didn't get pushed to GitHub but after I fixed that I got this new error message: 
<img width="853" alt="Screen Shot 2019-08-06 at 2 36 31 PM" src="https://user-images.githubusercontent.com/53193540/62579093-b6cc0400-b857-11e9-83c5-7ff6817de9a7.png">

It directed me to an unrecognized Liquid tag in the `/_layouts/default.html`. Not sure how to fix this. 

I'm assuming that the error is because I installed the theme via a gem-based method, not as a remote theme, however, when I tried to switch to the remote theme method, it didn't work and gave me this message: 

<img width="656" alt="Screen Shot 2019-08-06 at 3 35 21 PM" src="https://user-images.githubusercontent.com/53193540/62582068-f991da00-b85f-11e9-9c17-0f2994a71015.png">

I would appreciate any suggestions people may have for solving this GitHub Pages issue! 

Thanks!

**Comment by mmistakes** [comment]
Install the theme as a remote theme and remove all of the theme files... you don't need them unless you are overriding things and customizing the theme.

I would suggest you fork or download the [Minimal Mistakes GitHub Pages starter](https://github.com/mmistakes/mm-github-pages-starter). Remove the sample `_posts` and pages included in that repo and replace with your own and everything should work.

I discourage forking this repo as it isn't configured for GH Pages directly and if you're new to Jekyll it's easy to screw up (i.e. have the wrong things in your `Gemfile`, misconfigured `_config.yml`, extra files not needed, etc.)

**Comment by callywuthrich** [comment]
Thanks for the quick response!

I did try adding it as a remote theme and removed all of the previous theme files. You can check out my [Gemfile](https://github.com/callywuthrich/archesguides/blob/gh-pages/Gemfile) here. 

This is the message I get after following all the instructions for remote theme installation. 
<img width="657" alt="Screen Shot 2019-08-06 at 4 57 50 PM" src="https://user-images.githubusercontent.com/53193540/62584921-6bbbec00-b86b-11e9-9c69-902135096afa.png">

I've already created the site so I'd rather not start over by forking the pages starter repo. All I want to do is push my local site (which was running perfectly before I tried to change MM to the remote theme) to GitHub Pages. 

Let me know your thoughts! Thanks again!

**Comment by mmistakes** [comment]
Don’t think the Gemfile is your problem. You still have the theme files in your repo. Remove _includes, _layouts, _sass, etc.  Reference the starter above. It has the correct file/folder structure, Gemfile, and _config.yml you need.

You likely have left over cruft from another theme that is causing the issue.

**Comment by callywuthrich** [comment]
Figured it out! Thanks!
