### ISSUE TITLE
markdown conversion: undefined method gsub

### ISSUE THREAD

**Issue by khziessow** [mmistakes/minimal-mistakes#223]
Generating a new version of minimalmistakes runs into an error:
 Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2011-03-10-sample-post.md':
                    undefined method `gsub' for nil:NilClass
Any suggestions?
Karl

**Comment by mmistakes** [comment]
Do you get this error without modifying the files after cloning? Or did you make any changes? This looks to me to be a gem conflict, probably from not prepending Jekyll commands with `bundle exec`.

Run `bundle install` from the root of your site then `bundle exec jekyll serve` and let me know if you still get the error.

Other thing to look at would be if you have the same Markdown parser settings in `_config.yml`. I'd compare against the theme's repo to see if something is missing there.

**Comment by khziessow** [comment]
The "bundle exec" did it, thank you!
But I still struggle with footnotes [^1] / [^1]: 

-- 
-- 
Dr. Karl-Heinz Ziessow · Bremer Str. 31 · D-27798 Hude
Tel. 04408/923353 · 01756813886 · ziessow@ballodora.de

**Comment by mmistakes** [comment]
Good. Don't know what to tell you about footnotes other than read up on the [Kramdown's syntax](http://kramdown.gettalong.org/syntax.html#footnotes) and reference it when you have issues.

**Comment by khziessow** [comment]
I tried the footnotes again, and now it worked fine. Thank you again.

-- 
-- 
Dr. Karl-Heinz Ziessow · Bremer Str. 31 · D-27798 Hude
Tel. 04408/923353 · 01756813886 · ziessow@ballodora.de
