### ISSUE TITLE
Adding subheadings to navigation bar

### ISSUE THREAD

**Issue by callywuthrich** [mmistakes/minimal-mistakes#2235]
Hi! I was wondering if it is possible to include subheadings in the navigation bar that could act as anchor links? Essentially eliminating the need for a the table of contents by embedding the page anchors on the same side as the navigation.

Here is what my navigation bar currently looks like. 
<img width="292" alt="Screen Shot 2019-08-19 at 2 36 38 PM" src="https://user-images.githubusercontent.com/53193540/63301194-cce1b780-c28e-11e9-8828-85add9062863.png">
When I created it I tried to create subheadings to include below many of my pages but that didn't work so I resorted to just adding a table of contents to the pages where I needed more navigation organization. However this has resulted in tocs like this one that are excessively long. 
<img width="298" alt="Screen Shot 2019-08-19 at 2 40 42 PM" src="https://user-images.githubusercontent.com/53193540/63301439-5ee9c000-c28f-11e9-941d-5a77038b1538.png">
Is there any way to get my navigation bar to look something more like this: 
<img width="278" alt="Screen Shot 2019-08-19 at 2 29 31 PM" src="https://user-images.githubusercontent.com/53193540/63301553-b556fe80-c28f-11e9-9ec1-9495f40d1d39.png">
I know this has to do with overriding the theme's css files but was wondering if you have any suggestions of where to start. Thanks so much!

**Comment by mmistakes** [comment]
The theme already supports subheadings that can be linked to other pages. Simply add a `url` property to the object if you want it linked somewhere.

Your YAML would look something like this:

main:
  - title: "Parent Link 1"
    url: /parent-1-page-url/
    children:
      - title: "Child Link 1"
        url: /child-1-page-url/
      - title: "Child Link 2"
        url: /child-2-page-url/
  - title: "Parent Link 2"
    url: /parent-2-page-url/
    children:
      - title: "Child Link 1"
        url: /child-1-page-url/
      - title: "Child Link 2"
        url: /child-2-page-url/
      - title: "Child Link 3"
        url: /child-3-page-url/
```

RE: customizing the table of contents... that's going to take more than just CSS. You'll need some JavaScript too to make the expand/collapse dropdowns work.

**Comment by fdq09eca** [comment]
how can I see the children nav..? I do not see a dropdown from the navbar. Sorry if it is a silly question.

**Comment by iBug** [comment]
@fdq09eca The `main` navigation bar (the top bar) currently does not support nested items. You'd have to write (quite some) code to implement that yourself.
