### ISSUE TITLE
Minify Fontawesome JS

### ISSUE THREAD

**Issue by jaranta** [mmistakes/minimal-mistakes#2236]
## Summary

When looking at why my site was loading slowly, I noticed that the Fontawesome javascript `all.js` is bigger than all the other assets loaded combined. It is an order of magnitude larger than the next biggest javascript file `main.min.js`.

Would it be possible to minify Fontawesome so that it would only provide the icons actually used by this theme?

## Motivation

Minimising this asset would mean quicker load times for all the websites using this theme.

## Drawbacks

This might mean not being able to easily use the default fontawesome js.

**Comment by mmistakes** [comment]
Are you sure you're using the latest version of the theme? It's not loading `all.js`, instead it's using this FontAwesome kit script... which is minified.

https://kit.fontawesome.com/4eee35f757.js

![image](https://user-images.githubusercontent.com/1376749/63355705-91012d80-c334-11e9-9e0f-8af94951c503.png)

Since I have no control over FA not sure if there's anything else I can do. You could look into subsetting the icons you need and override the theme to use that. I won't be doing that with the theme as there's an expectation by a lot of users that the **entire** FontAwesome library of icons are included in the theme.

**Comment by jaranta** [comment]
I'm using gem version of the theme. I just checked and when I reported this, I was using version 4.16.4. I've updated the version to 4.16.6. I ran into some problems: apparently there is a new dependency, and I needed to install jemoji? It was not installed as a dependency and I had to add it to my list of gems to get jekyll to build the site.

But you are correct: I updated the gem version and no longer see all.js loaded. Sorry for the mistaken bug report.

**Comment by jaranta** [comment]
Actually, I'm still not quite sure what is happening with Fontawesome. I'm on the latest version and in addition to the script in your screenshot, there is another Fontawesome JS file being loaded, which about the same size as the one I mentioned in the first message. 

<img width="1280" alt="Näyttökuva 2019-9-25 kello 22 53 57" src="https://user-images.githubusercontent.com/5079912/65639312-2785d600-dfe8-11e9-86c2-0606337148b5.png">

That script is larger than everything else needed to load a page on my site combined.

**Comment by mmistakes** [comment]
As mentioned above the theme has no control over that script. The theme is loading a single FA script from their CDN. I believe that then loads other files as needed.

The FontAwesome JS is not controlled by theme. You can override the theme to load a different version of FA if you like that is potentially more light weight.

Here’s the relevant line in the theme if you want to load a different FA script.

https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/scripts.html#L12

**Comment by jaranta** [comment]
Thanks for the clarification! I've been using the gem version of the theme, so I'll move to a personal fork.

Perhaps in the future there could be a more minimal version of the theme available where fontawesome is disabled (perhaps with some fallback)? It's pretty great for icons, but seems also a bit overkill for a small site to load a JS file bigger than all the other assets combined just for a few icons.

**Comment by mmistakes** [comment]
I don't think the theme needs any sort of config to do this. The theme already allows you to customize what scripts you want to use. This is 100% controlled via `_config.yml` which allows you to install the theme as a gem and then configure the scripts you want to load. If you [assign a `footer_scripts`](https://mmistakes.github.io/minimal-mistakes/docs/javascript/#customizing) array in your config you can define all of the scripts you want to load.

```yaml
footer_scripts:
  - /assets/js/main.min.js
  - /any-other-script-you-want.js
```

You can also copy `_includes/scripts.html` to your repo, and make the change you want there. That will [override only that file](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) in the bundle theme, giving you the customization you need, while reap all the benefits of using theme as a gem (easier upgrades, etc.).
