### ISSUE TITLE
Click on Headers for permalink

### ISSUE THREAD

**Issue by hasezoey** [mmistakes/minimal-mistakes#2246]
## Summary

Click on a Header to change URL to it & copy to clipboard
![permalink](https://user-images.githubusercontent.com/10911626/63998438-62880d00-cb01-11e9-9305-ffa9cf5e6c24.png) (image from https://jekyllrb.com/docs/)

## Motivation

It would make linking to it faster & more reliable (because of no typos)

## Drawbacks

none?

---

PS: does this feature exists already? because i cannot find it in this theme...

**Comment by iBug** [comment]
This shouldn't be hard to implement. I'll copy some code from another website I maintain and see if it works.

**Comment by iBug** [comment]
Great idea! I just implemented the same feature on my website [in this commit](https://github.com/iBug/iBug-source/commit/6d87a6d54588be5d125aa335f10bf801e71c9593), but I'm not sure how to integrate the commit into Minimal Mistakes. Maybe if someone could provide some guidance on where I should insert the code I'd be able to fire up a PR for this.

**Comment by luispuerto** [comment]
I use [AnchorJS](https://www.bryanbraun.com/anchorjs/) to create the feature. I don't know the advantages or drawbacks against the @iBug solution but seems that AnchorJS has more options and it's easier to customize.

**Comment by mmistakes** [comment]
Only drawback I could see is AnchorJS is way more JavaScript (~350 lines unminified) than @iBug's solution, which is about 10 lines unminified.

**Comment by marksbren** [comment]
How can I turn this off? I do not want these permalinks on my long-form blog.

**Comment by iBug** [comment]
> How can I turn this off? I do not want these permalinks on my long-form blog.

@marksbren You can copy the theme's default [`/assets/css/main.scss` file](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/css/main.scss) into your own website at the exact path, and append the following line to hide those permalink buttons. Note that permalinks will still work, just without the button introduced here.

```css
.header-link {
  display: none;
}
```
