### ISSUE TITLE
Search results to display the excerpt, when it exe

### ISSUE THREAD

**Issue by JoaoGFarias** [mmistakes/minimal-mistakes#2248]
#  Summary

Apparently the search results show the title and the **first few lines** of the content.
For some types of content, it is fairly acceptable, but when the content starts with Markdown, rather than pure text, the search results display the **raw Markdown**.

![image](https://user-images.githubusercontent.com/1585655/64076722-a11bf400-ccc8-11e9-835f-6211217aed3a.png)

If the problem is accepted as to be fixed, I believe a good first step is to default the search results to the post's excerpt, given this attribute is meant to be a summary of the post itself.

## Motivation

- Avoid, for most cases, the displaying of raw Markdown on search results;
- Display a text for more focused on summarizing the content.

## Drawbacks

- Previous search will have its _content_ part altered;
- Posts without an excerpt will continue to display raw Markdown.

**Comment by mmistakes** [comment]
Not sure why it's doing this for you but when I fork and build your site locally it's rendering Markdown fine in search results.

![Screen Shot 2019-09-01 at 2 42 58 PM](https://user-images.githubusercontent.com/1376749/64080869-d0316600-ccc6-11e9-90e1-141554ee744d.png)

It also appears to be fine on http://thatsabug.com/

**Comment by JoaoGFarias** [comment]
@mmistakes that's correct, it seems the markdown is rendered when in production.

But even considering we don't have an error per se, what do you think of displaying the excerpt rather than the first few lines? Is it possible currently by configuration?

**Comment by mmistakes** [comment]
The Lunr search file that s built uses a posts's content not it's excerpt to build a more relavant index.

This is then used and trimmed to populate the search results. The actual excerpt isn't part of the index.

https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/lunr/lunr-en.js#L66
