### ISSUE TITLE
Custom CSS and JavaScript

### ISSUE THREAD

**Issue by TheSarfaraz** [mmistakes/minimal-mistakes#2252]
Hello
I'm using Minimal Mistakes for GitHub Pages
Is there a way I can use a custom CSS and Javascript files for  a single page? I don't want to include it in the config or change default files because I want these css and script files to be used only on one page... 
Is there a way I can add custom css js in a markdown page?

**Comment by mmistakes** [comment]
Markdown allows you to add HTML, so you can add your own `<style></style>` and `<script></script>` tags to your files.

Closing as this is a Jekyll thing and not related to the theme specifically.
