### ISSUE TITLE
custom header or footer

### ISSUE THREAD

**Issue by salvob41** [mmistakes/minimal-mistakes#2256]
In the README you wisely say:

> Gem-based method
> With Gem-based themes, directories such as the assets, _layouts, _includes, and _sass are stored in the theme’s gem, hidden from your immediate view. Yet all of the necessary directories will be read and processed during Jekyll’s build process.

And that is extremely helpful. But what if I want to add my own custom header/footer? Should I just copy the `_include` folder in my home site?

**Comment by mmistakes** [comment]
Yes.

**Comment by mmistakes** [comment]
Jekyll's documentation covers this in greater detail.
https://jekyllrb.com/docs/themes/#understanding-gem-based-themes
