### ISSUE TITLE
Jekyll Algolia seems that isn't going to be compatible any more with Jekyll 4

### ISSUE THREAD

**Issue by luispuerto** [mmistakes/minimal-mistakes#2257]
Hey! 

Seems that jekyll-algolia isn't compatible with jekyll 4 there are no plans to make it compatible

https://discourse.algolia.com/t/jekyll-v4-compatibility/7834/4
https://github.com/algolia/jekyll-algolia/issues/136#issuecomment-514261700

Any idea of how to circumnavigate the issue and continue using algolia on jekyll 4?

**Comment by mmistakes** [comment]
> Plugins and themes authors must relax the jekyll dependency in their gemspec file to allow for Jekyll v4.0:
>
> `spec.add_runtime_dependency "jekyll", ">= 3.6", "< 5.0"`

Could be as simple as that. What you could do as a test is fork the repo and [change this line](https://github.com/algolia/jekyll-algolia/blob/develop/jekyll-algolia.gemspec#L26) to relax the version of Jekyll the jekyll-algolia depends on.

Then you can add that forked gem to your `Gemfile` and see if it builds. 

```ruby
gem 'jekyll-algolia', :git => 'https://github.com/yourUserName/jekyll-algolia.git'
```

Hopefully that's all that is needed an a simple PR and merge and jekyll-algolia is v4 supported.

If it's not, well then that's a bigger problem.

**Comment by luispuerto** [comment]
it's a bigger problem, but I don't know how much bigger. 
https://github.com/algolia/jekyll-algolia/issues/140#issuecomment-525041725

**Comment by mmistakes** [comment]
Closing as this is an upstream issue I have no control over.

**Comment by luispuerto** [comment]
@mmistakes Thanks a lot for take the time to look into the issue 🙂
