### ISSUE TITLE
Font size isn't displaying correctly. 

### ISSUE THREAD

**Issue by pricelessbrewing** [mmistakes/minimal-mistakes#226]
Forked your repo, updated my posts and configs etc to support jekyll 3.0 and removed all the no longer required files. 

Repo: https://github.com/pricelessbrewing/pricelessbrewing.github.io

Example page: http://pricelessbrewing.github.io/methods/Efficiency/

As you can see, all of the text is a good deal smaller than yours at http://mmistakes.github.io/minimal-mistakes/theme-setup/#site-wide-configuration

I tried changing the doc font size of variables in _sass but it didn't seem to be working on the regular text, only the highlighted sections, headers, and the index on the right. 

Also, how would I go about changing the background color for the index?

**Comment by mmistakes** [comment]
Strange, the font size on your site looks really big to me and not small.

![large-fonts](https://cloud.githubusercontent.com/assets/1376749/12977301/ede2b598-d097-11e5-8da3-42d910b540c9.jpg)

What I suggest:

1. Don't mess with the doc size in `variables.scss`, that sets the rhythm for a lot of the typography and as you'll notice it also increased the white space above and below headlines, paragraphs, etc.
2. I didn't set a size on the paragraph elements, they default to around 16px. If you want to change the size the best way is open the Developer Tools in your browser and inspect the element you want to change then mess with the CSS. When you get something you like add it to your stylesheet.

![inspector](https://cloud.githubusercontent.com/assets/1376749/12977367/4e6e72da-d098-11e5-883b-94cde5827cd5.jpg)

If you just want to make all the type larger globally then bump up the size on the `body`. It doesn't have a `font-size` currently and defaults to 16px so if you want to go bigger pick a value higher than that e.g.

```css
body {
  font-size: 18px;
}
```

Anything else is basic CSS. If you want to target specific elements to change colors, sizes, whatver, you may need to add some class names to the HTML. That's out of scope of what I can help with.

**Comment by pricelessbrewing** [comment]
Quite strange. I opened it in chrome and IE and it's working as intended. Don't know what the issue was with firefox last night, it's displaying properly now. 

I'll see if I can figure out the table of contents css part, thanks.

**Comment by mmistakes** [comment]
Probably a caching issue. I purposely disable it to make sure I'm always seeing the latest CSS and JS. You could try opening it in an incognito or private window and that usually forces it to not cache the page.

**Comment by pricelessbrewing** [comment]
Cool, good to know.
