### ISSUE TITLE
How to change views

### ISSUE THREAD

**Issue by TheSarfaraz** [mmistakes/minimal-mistakes#2260]
Hello
I have the default minimal mistakes setup.
I want my site to look like this one:
http://varianceexplained.org/theme-setup/
This one looks less zoomed, less padding on left and right, smaller font size
Also, the Toc is impressive, is it possible to have this toc movable ? which floats as the page is scrolled
Please guide. Thanks

**Comment by TheSarfaraz** [comment]
![](https://lh3.googleusercontent.com/00HtVbw5TxUXA3cICXyJpPfY5ZjgkTIvTISaITkSqXZFNcgsfY1TPTmbPSc78fpH_-qtw4EYir5nepIDmFfDCQ1ga3G3rNzg6iplXlF1GzejeUqtNib6pM41KREf-1zPRZQMvQvHusSJbqKaZbINJcBa4pFyUtnbTFSkl0IaMTwl1CsGo45N_bNpiy8Il-FayyP8LCk5ThPD0coJ0BpX2Y06o-GEfaZI3llY2wz3aS3a43gpBQcmn5TugBezGvN6D88788IujSXQr58g1RHGI4bQzr3wWvdGArcYOsUDxs80poHPCqAXxTK8iIlOB7G__XsYILmEEHS6RktuFheY2-QXswNInP7Dab6GJbF4WKyU89Mrs7QBIug24qzls8hcBj_TAbVCW3jnEluXFcywavv1dcmp9wGNaQKHmkfBbF1wdA0YC6YPnq6Jg24pvz7RiPxIWo9pyeePKltTRfmQ9L5pLIK5Uoyop7VuEiU0hzZkzNXVWBeiDlizec6HdMgUVuwCYvG3yMtmbBbvWlrnXFCxtZamkEL2jGLoK4PDUohV4G-V_B7z1HmDHiq2vzorYe39GJxoSJFD6fgk46GAc7aYD5bZrK-wY8-zCXbZjyyAJUHCnpKop4PllSoe8tsCiZ5bLdy9KQlKH_z2qz-p6J4M6rCtDhOt9eNXxKLI02X8K4-zmXdP-Nc=w1899-h976-no)

This is my website. I wish that the space on the left of Author Profile is minimized, the white space in the right side is minimized. Also I want the toc_sticky to be sticky on top of image just like overlay title and excerp  on the right side and then as we scroll down the toc moves along

Can someone guide me how to do this?

**Comment by mmistakes** [comment]
http://varianceexplained.org/theme-setup/ is using a version of MM from years ago ([version 2](https://github.com/mmistakes/minimal-mistakes/releases?after=3.0.2)). You can go back and fork that version but it predates being a theme gem/remote theme and is missing pretty much every feature the theme supports now.

**Comment by TheSarfaraz** [comment]
> http://varianceexplained.org/theme-setup/ is using a version of MM from years ago ([version 2](https://github.com/mmistakes/minimal-mistakes/releases?after=3.0.2)). You can go back and fork that version but it predates being a theme gem/remote theme and is missing pretty much every feature the theme supports now.

Ok I don't want previous theme but the new theme looks so much zoomed in, how do I change it? And how to move sticky toc to the top?

**Comment by mmistakes** [comment]
There is no quick and easy answer to either of these inquiries. It will require knowledge of HTML and CSS to customize the theme to do what you want.
