### ISSUE TITLE
Sticky TOC pushes feature_row down

### ISSUE THREAD

**Issue by iBug** [mmistakes/minimal-mistakes#2263]
## Environment

- Minimal Mistakes version: 4.16.6
- Ruby gem or remote theme version: Ruby gem
- Jekyll version: 3.8.6
- Git repository URL: Not required
- GitHub Pages hosted (if yes provide URL to site): Not required
- Operating system: Independent

## Wrong behavior

![image](https://user-images.githubusercontent.com/7273074/64869458-03370a80-d674-11e9-97da-ea8ee3baf685.png)

The sticky TOC pushes the first `feature_row` at an unexpected place. If the key `position: sticky;` was removed from the class `.sidebar__right.sticky`, then the `feature_row` locates at the correct place (i.e. no margin between it and the above heading 2 *Overview*).

I have since disabled `toc_sticky` for the article to give it a normal look.

## To reproduce

Create an article with a `feature_row` at top, as well as a few headings to give the TOC some height. Set `toc_sticky` on the page and check the result.

## Other

I'd like to know how to patch the CSS to fix this issue locally, but I'm not experienced in CSS and haven't yet figured out how. Yes, [I do patch the CSS](https://github.com/iBug/iBug-source/blob/master/assets/css/main.scss) to create my own desired layout.

**Comment by mmistakes** [comment]
I this page hosted somewhere so I can inspect the HTML/CSS in browser?
Looks like the feature blocks are in a different `<div>` that comes after the one that has the main content and TOC.

Which is why you're seeing the space.

**Comment by iBug** [comment]
@mmistakes [Here it is](https://ibugone.com/p/26-test).

**Comment by mmistakes** [comment]
I don't know if this will have unintended consequences somewhere else but if you add `float: left` to `.feature__wrapper` it properly clear the sidebar.

```css
.feature__wrapper {
  float: left;
}
```

![Screen Shot 2019-09-14 at 11 07 54 AM](https://user-images.githubusercontent.com/1376749/64909949-eb956b80-d6df-11e9-9956-f9efa38ecf56.png)

**Comment by iBug** [comment]
@mmistakes That's more a workaround than a solution to me. The feature block is now at a wrong position. The first block should be right under `<h2>Overview` without text between them but with `float: left;`, a few lines of text are moved up to fill in the gap.

What actually work for me was to add `.feature__wrapper { display: inline-block; }` and the order of content is well preserved. I don't know if there's any side effect either.

**Comment by mmistakes** [comment]
Not sure. Feature blocks weren't designed to be used as you have so that's likely why they misbehave for you.

They're more for splash pages, not posts with table of Contents.

Since you're doing images use the gallery helper instead. That's what it's designed for.

https://mmistakes.github.io/minimal-mistakes/docs/helpers/#gallery

**Comment by iBug** [comment]
Oh, much thanks for that. I should've read the docs thoroughly first!
