### ISSUE TITLE
¿Create links nofollow? 

### ISSUE THREAD

**Issue by rosepac** [mmistakes/minimal-mistakes#2266]
I can create nofollow links from github pages. Are there any options configured within the template for this?

I found this: https://github.com/d-ogarkov/jekyll-extlinks  but I don't know if there is something similar in the mmistakes template

...

## Others
I want to insert several things to the template and I have multiple doubts; but little by little.

I don't know if this is the best place to ask other questions, greetings; And thank you very much for everything. Or if there is a forum or something, where to ask.

**Comment by mmistakes** [comment]
For Jekyll questions ask in their forum. https://talk.jekyllrb.com/

I've never used that plugin, but that's likely the sort of solution you'll need. There is nothing in the template to alter links to add `rel="nofollow"`.

**Comment by mmistakes** [comment]
As it isn't a whitelisted plugin by GitHub Pages I'm not interested in adding it as a dependency of the theme as it would break compatibility. 

But there is nothing stopping you from installing it on your site. Looks fairly straight forward to do so.
