### ISSUE TITLE
Unable to use font awesome pdf icons in markdown text

### ISSUE THREAD

**Issue by schrilax** [mmistakes/minimal-mistakes#2267]
hello,
firstly i want to acknowledge that this is a really good theme for usage to create academic websites. i am pretty much done with my website design but i am unable to use font awesome pdf icons in my .md files. they do not render at all or render weirdly. can you please help me out ? perhaps it was something i did not understand in the documentation or something which i missed reading etc. so i wanted to get a clarification first rather than opening an issue. 

please do reply.
thanks.

schrilax

**Comment by mmistakes** [comment]
I would suggest posting this on the Jekyll help forum instead. It's not a a theme issue.

If/when you do post there, you'll get a better response if you include an example of what you've tried. Markdown supports HTML, so if you add Font Awesome icons using the Markup they provide on their site it should work fine.
