### ISSUE TITLE
Add the best-performing type of images: webp within the headings.

### ISSUE THREAD

**Issue by rosepac** [mmistakes/minimal-mistakes#2268]
## Summary
Add file format of modern images; to be supported in the headings.

## Motivation
Because it is a less heavy format that makes pages faster. In fact Currently. Google recommends it. Especially for mobile devices, and performance improvement

## Drawbacks
At first. None. The implementation could be fast. In the absence of testing if adding .webp generates problems within the template.

I have tried to generate a test environment and I have not succeeded.

Therefore, I would like it to be implemented; and if someone can try it quickly by adding: a[href$='.webp'] after the rest of image formats in:

main.js and main.min.js

And test if: .webp generates a problem due to the size of the images or some other possible configuration or not.

Sorry for my English. I hope my poor writing is understood. Regards and 🍻.

**Comment by erikw** [comment]
Reviving this

This theme could integrate with https://github.com/rbuchberger/jekyll_picture_tag. It works very nice! I've overridden the theme's `<img>` tags and it works great!
