### ISSUE TITLE
Noob unable to get custom javascript called in header for post

### ISSUE THREAD

**Issue by textplusdata** [mmistakes/minimal-mistakes#2269]
Hi,

I am trying to load some javascript files for a single post that is a data visualisation. It uses a bunch of javascript files (some cdn, some local) and I know it works because it works here when I set up in a separate folder outside of posts everything works.

http://textplusdata.se/legacy-dataviz/
https://github.com/textplusdata/textplusdata.github.io/blob/master/legacy-dataviz/index.html

What I want to do is get this visualisation into a markdown post, which means I need to call the javascript files into the head, but I only want to do this on specific posts, not all posts.

I have tried modifying the custom.html and now also directly the head includes file but nothing extra seems to show up in the head when I view source:
https://github.com/textplusdata/textplusdata.github.io/blob/master/_includes/head.html

```
<!-- couldn't get loading to work from the custom.html file in the head folder, so trying like this instead: -->
{% if post.dataviz %}
    <!-- possibly don't need jquery, as this is part of standard in this theme? Otherwise mix of cdn and local for no real good reason -->  
    <!-- <script src="http://code.jquery.com/jquery.js"></script> -->
  <script type="text/javascript" language="javascript" src="http://cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/jquery.dataTables.min.js"></script>
  <script type="text/javascript" language="javascript" src="dataviz-js/jquery-chosen/js/chosen.jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/d3/3.3.3/d3.min.js" charset="utf-8"></script>
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.1/crossfilter.min.js"></script>
  <script type="text/javascript" src="dataviz-js/dcjs/js/dc.min.js"></script> 
{% endif %}
```

My markdown post looks like this:
`---
title: "dataviz test"
dataviz: true
---`

I have read a couple of posts that seem to be related to this but I can't get my head round what I'm supposed to do.
I read this one: https://github.com/mmistakes/minimal-mistakes/issues/615

I also read this one, but that doesn't seem to allow for loading javascript conditionally based on the setting on the markdown:
https://mmistakes.github.io/minimal-mistakes/docs/javascript/ 

I am clearly missing something basic here but can't work out what I'm doing wrong. can anyone help?

**Comment by mmistakes** [comment]
Change [`{% if post.dataviz %}`](https://github.com/textplusdata/textplusdata.github.io/blob/master/_includes/head.html#L33) to `{% if page.dataviz %}`

It's a common mix up for Jekyll users. When you're trying to access YAML in a Markdown file it's always `page.foo`... with `foo` being whatever variable name you use in the front matter.

The `post` object is something you might use when looping over a collection. Like say `{% for post in site.post %}`.

I encourage you to read through [Jekyll's documentation](https://jekyllrb.com/docs/front-matter/#custom-variables) and other resources to get a better explanation of how this all works.
