### ISSUE TITLE
Changing font size within Nested Lists 

### ISSUE THREAD

**Issue by Anamika255** [mmistakes/minimal-mistakes#2270]
How can we decrease the font sizes for nested lists such that each lower level has a smaller font size? Also, is it possible to change the font size for some posts without modifying it for the whole website?

**Comment by mmistakes** [comment]
I would suggest searching around for CSS resources. You can use the cascade to style child elements however you want. Example:

```css
ul > ul,
ol > ol,
ul > ol,
ol > ul {
  font-size: 0.75em;
}
```

You'll need to [customize the theme's main stylesheet](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#customizing) to do this.

To do unique styles on specific posts/pages you'll need to add the inline styles directly to those pages in the body of the content.

```html
---
title: Your Special Page
layout: single
---

<style>
  /* your custom CSS here */
</style>

## A heading

Some content.
```
