### ISSUE TITLE
Not able to upgrade from 4.13.0 to 4.16.6

### ISSUE THREAD

**Issue by ansiblejunky** [mmistakes/minimal-mistakes#2271]
Was previously using remote theme, and decided to change this to use gem theme (to eliminate a remote dependency with internet, etc). I had made various changes to my theme/repo after my initial installation of jekyll + theme. Currently it seems I am using v4.13.0 (based on what is generated in the `_site/assets/css/main.css`. 

Running `bundle` shows I have jekyll 4.0.0 and theme v4.16.6.  However, what isn't my theme generated with the new version? How do I also ensure that I have the new enhancements/fixes from the latest version of the them applied to my local repo? 

```
$ bundle
Using public_suffix 4.0.1
Using addressable 2.7.0
Using bundler 2.0.2
Using colorator 1.1.0
Using concurrent-ruby 1.1.5
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using multipart-post 2.1.1
Using faraday 0.15.4
Using ffi 1.11.1
Using forwardable-extended 2.6.0
Using i18n 1.6.0
Using sassc 2.2.1
Using jekyll-sass-converter 2.0.0
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using ruby_dep 1.5.0
Using listen 3.1.5
Using jekyll-watch 2.2.1
Using kramdown 2.1.0
Using kramdown-parser-gfm 1.1.0
Using liquid 4.0.3
Using mercenary 0.3.6
Using pathutil 0.16.2
Using rouge 3.11.0
Using safe_yaml 1.0.5
Using unicode-display_width 1.6.0
Using terminal-table 1.8.0
Using jekyll 4.0.0
Using jekyll-feed 0.12.1
Using sawyer 0.8.2
Using octokit 4.14.0
Using jekyll-gist 1.5.0
Using jekyll-include-cache 0.2.0
Using jekyll-paginate 1.1.0
Using jekyll-sitemap 1.3.1
Using minimal-mistakes-jekyll 4.16.6
Bundle complete! 1 Gemfile dependency, 38 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Your help is appreciated.

**Comment by mmistakes** [comment]
If you’re not seeing the latest version in the generated site it’s because you:

1. Have local overrides for a layout or CSS with the older version number in it
2. Not running `bundle exec jekyll build` to force use the gem versions specified in you’re `Gemfile`... which is theme v4.16.6

**Comment by ansiblejunky** [comment]
When using gem theme, the files in my repo related to the theme should only exist if I am overriding the original file from the gem? Right? So the folders/files you specify in the upgrade steps should only contain stuff if I am attempting to override the original files from the gem, right? 

I tried running `bundle exec jekyll build` but that didn't fix the problem. I must have some overrides that exist.

**Comment by ansiblejunky** [comment]
Ok, it's generating the files now properly with the html header showing 4.16.6 version. This is what I did:
1. Cloned the theme's 4.13.0 tag and compared it to my repo
2. Cleanup my repo - removing any files that I am not overriding at all (basically those I never changed from the original 4.13.0)
3. Rebuild: `bundle exec jekyll build`
4. Serve: `bundle exec jekyll serve`
5. Test and make sure it's not broken
6. Push to github repo and validate published site

It seems the only way the repo will work in Github Pages is when I use a remote-theme. I cannot use gem-theme. Correct?  At least that's what I read on Github.

**Comment by mmistakes** [comment]
Yes, `remote_theme` will work with GitHub Pages... installing as a theme gem and installing as `theme` in _config.yml will not work.

With either method you should only have a _config.yml file and your `_posts` and/or pages/collections. If you have `_layouts`, `_includes`, or `_sass` files and they are named the same as the theme's, they will override them.

The whole point of installing the theme as a gem or `remote_theme` is so you don't need to have the layouts, includes, and sass files in your repo. Unless of course you are overriding a file or two.

**Comment by ansiblejunky** [comment]
Thanks for the support. It's looking good now.
