### ISSUE TITLE
Build fails as remote theme

### ISSUE THREAD

**Issue by thedukeoflemington** [mmistakes/minimal-mistakes#2272]
Hi, excellent theme that I've used successfully in the past (using local Gems build), but I'm trying to get it to work simply as a remote_theme. I have a repo with only a README and a _config.yml that fails to build.

## Environment
- remote theme version: remote_theme:  mmistakes/minimal-mistakes
- Git repository URL: https://github.com/thedukeoflemington/thedukeoflemington.github.io
- GitHub Pages hosted (if yes provide URL to site): https://thedukeoflemington.github.io

## Expected behavior
Builds without errors :)

## Steps to reproduce the behavior
I have a repo with only a README and a _config.yml that fails to build.

GitHub Pages failed to build your site.
The tag include_cached on line 15 in /_layouts/default.html is not a recognized Liquid tag.

**Comment by mmistakes** [comment]
See this note in the README and documentation:

> **Note:** The theme uses the [jekyll-include-cache](https://github.com/benbalter/jekyll-include-cache) plugin which will need to be installed in your `Gemfile` and added to the `plugins` array of `_config.yml`. Otherwise you'll throw `Unknown tag 'include_cached'` errors at build.
