### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by ekremkaraca** [mmistakes/minimal-mistakes#228]
Hi @mmistakes,

I'd like to translate theme into my language. I made some but I wonder whether they are reverted back while fetching updates from upstream. Can you tell me how I made this theme i18n'ed?

**Comment by mmistakes** [comment]
My other theme [Skinny Bones](https://github.com/mmistakes/skinny-bones-jekyll) supports being localized better as it makes use of some `_data` files. 

I have no plans to do the same with this theme. You'll just have to go through all the layouts and includes and localize any English text into the language you want.

**Comment by mmistakes** [comment]
Closing because theme text can now be [localized via a data file](https://mmistakes.github.io/minimal-mistakes/docs/ui-text/).
