### ISSUE TITLE
Footer breaks when using a browser toolbar

### ISSUE THREAD

**Issue by stanulilic** [mmistakes/minimal-mistakes#2281]
I use Chrome together with [ Mozbar](https://chrome.google.com/webstore/detail/mozbar/eakacpaijcpapndcfffdgphdiccmpknp?hl=en) Chrome extension from [Moz](https://moz.com/) to see the Domain Authority and Page Ranking score for every page I visit.

I noticed the theme footer breaks when I have enabled the toolbar as you can see in the screenshot below:

![Screenshot from 2019-10-13 21-05-55](https://user-images.githubusercontent.com/25522835/66720533-2a613300-edfe-11e9-8053-238ecdf7f465.png)

When I  disabled it, the footer looks fine:

![Screenshot from 2019-10-13 21-06-18](https://user-images.githubusercontent.com/25522835/66720548-64cad000-edfe-11e9-9460-a8a20d35245e.png)

I also tried this with a different toolbar [SEOQuake](https://chrome.google.com/webstore/detail/seoquake/akdgnmcogleenhbclghghlkkdndkjdjc?hl=en) from SEMrush.

![Screenshot from 2019-10-13 21-11-15](https://user-images.githubusercontent.com/25522835/66720574-c428e000-edfe-11e9-8d5b-46850c6f7b98.png)

As you can see the footer breaks again.

It happens on my blog and It also happens here: [https://mmistakes.github.io/minimal-mistakes/](https://mmistakes.github.io/minimal-mistakes/) as you can see from the screenshots. It is worse on my blog because it blocks the pagination. 

![Screenshot from 2019-10-13 21-30-21](https://user-images.githubusercontent.com/25522835/66720716-cbe98400-ee00-11e9-8e90-ca35fc4b7d95.png)

You can easily recreate this by trying the [ Mozbar](https://chrome.google.com/webstore/detail/mozbar/eakacpaijcpapndcfffdgphdiccmpknp?hl=en)  extension and then visit [https://mmistakes.github.io/minimal-mistakes/](https://mmistakes.github.io/minimal-mistakes/).

**Comment by mmistakes** [comment]
There's a bit of JavaScript that evaluates the height of the page to determine how much space it needs to stick to the bottom of the page.

My guess is the Moz and SEOrush toolsbars screw with that because they are adding their own sticky panels to the DOM. Not sure if there's anything I can do about how other scripts mess with the theme.

**Comment by mmistakes** [comment]
The Mozbar is injecting inline CSS to the `body` element to absolutely position it, which messes with the page layout. Don't think there's anything I can do about that.

```css
body.mozbar-margin-wGA7MhRhQ3WS {
    margin-top: 43px;
    position: absolute;
    width: 100%;
}
```

**Comment by stanulilic** [comment]
Okay. But I noticed on your website [https://mademistakes.com/articles/](https://mademistakes.com/articles/), the footer doesn't break when using a toolbar.  Perhaps, the solution could there?

**Comment by mmistakes** [comment]
mademistakes.com is my personal site, it's not using the Minimal Mistakes at all. It's a custom built Jekyll site that isn't using a theme.

**Comment by mmistakes** [comment]
The faux-sticky footer effect will need to be rethought to get around plugins that try to rewrite the height of the page.

Flexbox might be able to help here instead of absolutely positioning the footer and then using the JavaScript hack to clear it.

**Comment by stanulilic** [comment]
It would be awesome if it gets fixed. I was really worried that people who are using the toolbars wouldn't be able to access the pagination. They would simply assume that the site is broken.
