### ISSUE TITLE
How to make author + subpage in the title visible in google search?

### ISSUE THREAD

**Issue by peeter-t2** [mmistakes/minimal-mistakes#2282]
Hi, I'm very much enjoying the distribution, thanks a lot, it helped me make a nice personal website.

One thing, that I can't figure out how to find info for. When trying to make the page show up in google search results, some pages have as title the name of the whole website, some pages the name of the website and subpage, and some pages as the website+subpage+author.

I've tried making the pages equal, but I can't quite figure out what makes a difference. Author name has been attached to posts, post-collections and pages. Author name has been missing from other pages, but I can't find a difference between them. As google search engine does not update quickly, it is difficult to test too.

What should I do to make sure author name is shown with website+subpage in page title? Thanks a lot!

I add example screenshots from google below:
PS "About me" page is there twice, because it was a separate file that I copied later to index.html to act as frontpage. The other file is now removed, but for now still remains in google index.

![Screenshot from 2019-10-15 16-56-22](https://user-images.githubusercontent.com/4077432/66838089-c0b36700-ef6c-11e9-9956-ed4ea40c6c5b.png)
![Screenshot from 2019-10-15 16-53-13](https://user-images.githubusercontent.com/4077432/66838091-c0b36700-ef6c-11e9-9017-17b0ad79dac8.png)

**Comment by mmistakes** [comment]
For page `<title>`, the theme uses the page's title followed by a separator character, then the site's name.

If you're seeing author in the title's in Google search results pages like the screenshot above that appears to me that Google is rewriting the titles. It does this sometimes if it thinks it can provide a better title. You can verify what a page's title is by looking at the HTML source and searching for the `<title>` element.

![image](https://user-images.githubusercontent.com/1376749/66840733-829b5080-ef36-11e9-915e-ba447a83d3b3.png)

The theme does not add the author to page titles. So unless you specifically have it in a page's `title` front matter it's not going to be in the source HTML produced.

If you would like to have an author add to all page titles then you can modify these lines in `_includes/seo.html` 

```html
{%- if page.title -%}
  {%- assign seo_title = page.title | append: " " | append: title_separator | append: " " | append: site.title -%}
{%- endif -%}
```

To something like

```html
{%- if page.title -%}
  {%- assign seo_title = page.title | append: " " | append: title_separator | append: " " | append: site.title | append: " " | append: title_separator | append: " " | append: site.name -%}
{%- endif -%}
```

Which would give you a title like `Your Page Title - Site Name - Author Name`

**Comment by peeter-t2** [comment]
Thanks a lot for explaining and the fix! I will try it out in the near days. 

Interesting to know that google would change titles algorithmically, didn't even think of that.

**Comment by mmistakes** [comment]
I haven't seen it happen much, but Google does rewrite the titles if it feels like it. Seems like it uses what you publish in `<title>` as a suggestion in some cases, much like the meta description content.

Did your site use a different theme before? That could explain the titles being different. Depending on when Google has crawled your site and updated it's index you could see some differences there too.

Using their Google Search Console tool can often give you some extra insight on what it's indexed of your pages.

**Comment by peeter-t2** [comment]
Ok, tried it. Works perfectly.

I haven't changed the theme in some years, so not sure why this may have been. Thanks a lot though!
