### ISSUE TITLE
Nested task list displays as a flat list

### ISSUE THREAD

**Issue by bmaingret** [mmistakes/minimal-mistakes#2283]
## Environment
- Minimal Mistakes version: remote 4.17.0
- Jekyll version:  jekyll (= 3.8.5)
- Git repository URL: https://github.com/bmaingret/bmaingret.github.io
- GitHub Pages hosted (if yes provide URL to site): https://bmaingret.github.io
- Operating system: Windows

## Expected behavior
Nested task list should appear as nested.
Example: https://github.github.com/gfm/#example-280
Or as displayed : https://github.com/bmaingret/bmaingret.github.io/blob/master/_pages/now.md

## Steps to reproduce the behavior
Put a nested task list in a page or post and check rendering.

## Other
The following css is the reason as far as I can tell.

```{css}
.task-list {
   padding: 0;
}
```
I have added the following after the import in main.scss on my side.
```{css}
.task-list {
   padding-left: 1em;
}
```

Result: https://bmaingret.github.io/now/

**Comment by mmistakes** [comment]
If someone wants an easy Hacktoberfest PR all that's needed is something like 

```scss
.task-list .task-list {
  margin-left: 1em;
}
```
