### ISSUE TITLE
Site not indexed on google: What am I missing ? 

### ISSUE THREAD

**Issue by saraswatmks** [mmistakes/minimal-mistakes#2287]
Hello

Thanks a lot of creating this beautiful project. I can't imagine creating a website in few minutes.
Here's my site: https://github.com/saraswatmks/saraswatmks.github.com

I think I have followed all the steps and I don't see my blog when I search it on google. I have made sure to add `jekyll-sitemap` plugin in my config. I understand sometimes indexing takes time, but it's been three days since I published the blog. 

What am I missing ? 

Thanks in advance.
Manish

**Comment by mmistakes** [comment]
New sites can take a while for Google to index. I’d suggest reading up on SEO blogs and sites on how to get indexed.

You’ll also want to verify your site with [Google Search console](https://search.google.com/search-console/about) so you can add your sitemap.xml file.

You’ll be able to see any indexing issues and what pages Google has indexed.
