### ISSUE TITLE
Where can I change the font size of code and body?

### ISSUE THREAD

**Issue by JangHyeonJun** [mmistakes/minimal-mistakes#2290]
repository url : https://github.com/JangHyeonJun/janghyeonjun.github.io

Now, code and body text are too big so i want to reduce that font size.
I already know about 'type scale' but i don't know where can i set 'type' of code, body

![image](https://user-images.githubusercontent.com/18680116/67108635-e1e4b380-f209-11e9-9719-485b9d0947ed.png)
![image](https://user-images.githubusercontent.com/18680116/67108702-0476cc80-f20a-11e9-9c3c-a90745d938a9.png)

**Comment by mmistakes** [comment]
Search through the closed issues as I've answered this question numerous times before.

If you want to target specific text, then I suggest you use your browser's web developer tools to inspect and determine what class names you need to adjust `font-size` on.

![image](https://user-images.githubusercontent.com/1376749/67111114-42400a80-f1a2-11e9-9abb-0cec71612cc6.png)

**Comment by JangHyeonJun** [comment]
Thank you so much, I found it ! :) And I'm sorry for asking the same question 😢
