### ISSUE TITLE
permalinks and icons are breaking reader mode

### ISSUE THREAD

**Issue by Sayrus** [mmistakes/minimal-mistakes#2297]
## Environment

- Minimal Mistakes version: 4.17.2 (works on the demo)
- Ruby gem or remote theme version:
- Jekyll version: 3.7.4 (works on the demo)
- Git repository URL: ---
- GitHub Pages hosted (if yes provide URL to site): https://mmistakes.github.io/minimal-mistakes/layout-header-image-text-readability/
- Operating system: Arch Linux (5.3.7)

## Expected behavior

Permalinks (and sadly, icons too) disappear when using reader mode or stay but in a non-bothering format.

## Steps to reproduce the behavior

On Chromium (Experimental Reader Mode): everything works
On Firefox: Wait for permalinks and icons to load, activate reader mode.
![image](https://user-images.githubusercontent.com/22404472/67684867-da50a780-f98b-11e9-8ed1-a346b76f5813.png)
![image](https://user-images.githubusercontent.com/22404472/67684880-e2104c00-f98b-11e9-9abc-d9528135757a.png)

## Other

It would be interesting to allow one to disable permalinks totally as it:

- Adds Javascript
- Break layout if the permalink icon is placed on the next line (see screenshot, where the only reason there is a blank line is the hidden permalink icon)
![image](https://user-images.githubusercontent.com/22404472/67685564-3831bf00-f98d-11e9-88e1-f1c239a2cf9b.png)

Best regards,

**Comment by mmistakes** [comment]
Icons are added via Font Awesome's JavaScript and aren't really part of the page's "content"... which would explain why they're stripped from various browser reader modes.

The large sizing has to do with the icons coming in at 512x512 pixels and then resized via CSS with the theme... but the reader modes disregard the theme's CSS and use their own styling instead. If there's a way to size the icons smaller via Font Awesome without CSS then there's a chance to fix this.

I'll have to dig into the issue to see if there's anything I can do about it.

**Comment by Sayrus** [comment]
Having the icons disappearing is quite fair and is actually not that bad of a trade-off.
Using the font file instead of JS should ensure that the icon disappear, I don't know if there is any drawback to using the classic webfont version.

There is an open issue on FA:
https://github.com/FortAwesome/Font-Awesome/issues/14899
And they opened an issue on Mozilla Bugtracker:
https://bugzilla.mozilla.org/show_bug.cgi?id=1545453

**Comment by mmistakes** [comment]
The drawback is it's a pain to update when new fonts roll out. That's why the theme started using FA's JS.
That's not something I'm considering changing as the theme is easy enough to disable the JS and add FontAwesome's CSS/webfonts locally to load instead.

**Comment by Sayrus** [comment]
Makes sense. Let's wait for an answer on their issue, this should solve this one at the same time.

**Comment by mmistakes** [comment]
Both of those issues have been sitting around for 6 months... so don't expect a resolution anytime soon ;-)
