### ISSUE TITLE
How to change sidebar location?

### ISSUE THREAD

**Issue by WONILLISM** [mmistakes/minimal-mistakes#2303]
Thanks for your amazing theme!
I wonder that if I can chage sidebar location to left and hide sidebar with click.
Thank you!

**Comment by mmistakes** [comment]
There’s no configurable way to do this. You’ll need to be comfortable rewriting the theme’s CSS and JavaScript to move the sidebars and change their behavior.

**Comment by WONILLISM** [comment]
Oh... I have to study css, html... I don't know anything css, html.
Thank you for your reply!!
