### ISSUE TITLE
Linkedin Icon is missing

### ISSUE THREAD

**Issue by junyanyao** [mmistakes/minimal-mistakes#2305]
Under site author part. I found Linkedin icon is missing. I tried to make change, but it's not working.

`    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/" `

**Comment by mmistakes** [comment]
Have you read the documentation? You can add any icon and link you want.

https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-author

**Comment by reinhrst** [comment]
Doesn't seem that the linkedin icon is requested in the original request.. Anyways, I arrived at this same topic while googling. In case anyone else runs into this: Problem is that github/twitter etc icons use `fa-twitter-square`,  `fa-github-square`, etc. There is no `fa-linkedin-square` in Font Awesome, you have to use `fa-linkedin`.

**Comment by Qleoz12** [comment]
thanks @reinhrst , I dig a little and I find this scss handles the icons and also i can find more icons for example  icon: "fab fa-fw fa-youtube" for youtube, i would like to impreve the icons in the future with the recent version
 of FontAwesome.



![image](https://user-images.githubusercontent.com/15818177/164078174-9b941d8a-53e7-4b87-9463-343e4e69ee69.png)

**Comment by jiapei100** [comment]
Yeah, I would also recommend adding **linkedin** by default in this theme....

**Comment by am17torres** [comment]
> Doesn't seem that the linkedin icon is requested in the original request.. Anyways, I arrived at this same topic while googling. In case anyone else runs into this: Problem is that github/twitter etc icons use `fa-twitter-square`, `fa-github-square`, etc. There is no `fa-linkedin-square` in Font Awesome, you have to use `fa-linkedin`.

I tried this, not sure why it isn't working. Any ideas?

```yml
links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-linkedin"
      url: "https://www.linkedin.com/"
```
