### ISSUE TITLE
Footer is not static at the bottom of the page

### ISSUE THREAD

**Issue by hmz777** [mmistakes/minimal-mistakes#2309]
I just upgraded my GitHub page from 4.14.2 to the latest version of minimal mistakes which is 4.17.2 by replacing the necessary files from the latest repo and I noticed that the footer is not static at the bottom like it used to, it's floating in the middle of the page, so I compared the sass files in both versions and it turned out the class "page__footer" is missing a few attributes which are : 
```
  position: absolute;
  bottom: 0;
  height: auto;
```
[Github Page](http://www.hmz-software.me/)

adding them solved the issue.

**Comment by mmistakes** [comment]
Duplicate of #2301 and #2306
