### ISSUE TITLE
Make the right hand Markdown Table of Contents sticky

### ISSUE THREAD

**Issue by keohan** [mmistakes/minimal-mistakes#2312]
## Summary
Make the Right TOC menu for markdown documents sticky so that it is always shown when users scroll down large articles.

## Motivation
I feel that this feature is core to this project as it :

  * enhances consistency across the UI by making menus sticky across the board.
  * since the screen real estate is lost by it's allocation to the right side TOC, this feature would insure that this area of the screen is always populated/functional and not shown as white space.

## Drawbacks

  No drawbacks are perceived.

**Comment by mmistakes** [comment]
Closing as this is already a feature of the theme.
Please search/review the theme's documentation before requesting features.

https://mmistakes.github.io/minimal-mistakes/layout-table-of-contents-sticky/
