### ISSUE TITLE
Last_Modified_Date - can it be based on last git commit for that page?

### ISSUE THREAD

**Issue by vortexing** [mmistakes/minimal-mistakes#2313]
We are using your theme as a remote theme for a documentation site at a research institution (https://sciwiki.fredhutch.org/).  We have used the last modified date to show when a page was updated so readers know how current the info is.  BUT we'd much rather it be not manual but rather based on the date of the last git commit on that file.  

I can't quite figure out if there already is a variable/plugin to make this work along with your theme.  Are you aware of a way to do this? 

Thanks (for both any guidance and also for a great theme)!

**Comment by mmistakes** [comment]
Unfortunately the theme can't help with regards to this. You'll need some sort of tooling that automatically updates `last_modified_at` for you in your Markdown files.

There's a Jekyll plugin that may help you but it hasn't been updated in years and almost certainly doesn't work with GitHub Pages hosted sites.

https://github.com/gjtorikian/jekyll-last-modified-at

Closing as this isn't a theme concern. You may find some suggestions from other users on the [Jekyll Talk forum](https://talk.jekyllrb.com/) if you ask.

**Comment by vortexing** [comment]
Thanks.  I did look into that plugin but you're right, it doesn't work in the modern day. ;)  Worth a shot!

**Comment by segunak** [comment]
> Thanks. I did look into that plugin but you're right, it doesn't work in the modern day. ;) Worth a shot!

Have you seen this? 

https://mademistakes.com/notes/adding-last-modified-timestamps-with-git/
