### ISSUE TITLE
Google Analytics working for mobile access, but not for web access

### ISSUE THREAD

**Issue by deepns** [mmistakes/minimal-mistakes#2324]
Hi,

I forked my Github Pages site from [mmistakes-starter](https://github.com/mmistakes/mm-github-pages-starter) at deepns.github.io. I wanted to add Google Analytics for my pages, so followed the instructions from the [configuration guide ](https://mmistakes.github.io/minimal-mistakes/docs/configuration/). I updated the _config.yml with the GA tag, but didn't see any traffic reported in the GA console. I then added a custom.html in the _includes/head with the script tag given by GA. I'm now able to see the traffic updated when accessing the site from a mobile device, but not when accessing from a web browser. Any idea what I might be missing here? I thought mmistakes theme settings take care of inserting the GA script into the head of each page, but it seems to be missing here. Appreciate any help in resolving this issue. 

Thanks,
Deep

**Comment by mmistakes** [comment]
Which analytics provider did you try (`google`, `google-universal`)? There's a couple of different flavors of Google Analytics.

https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/analytics-providers/google.html

https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/analytics-providers/google-universal.html

**Comment by deepns** [comment]
Thank you for the response. I am using google-universal.. I think I used google as well, but didn't see any traffic. I then copied the script code from Google Analytics dashboard and pasted into _includes/head/custom.html. That code seems to be slightly different from the ones used in the files you referenced above. Is custom.html really needed here? I thought the theme files under analytics-providers/ provide the needed scripts.
________________________________

**Comment by mmistakes** [comment]
Custom is only needed if you need to drop in a different analytics script embed.
As far as I know the Google Analytics scripts the theme provides work. They're working for me.

Hard to tell if it's a configuration thing on your end or if the emded scripts used by the theme are older than what Google is using now. As far as I know they should be backwards compatible.

**Comment by mmistakes** [comment]
Looking at the source of your site I see this

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-151868570-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-151868570-1');
</script>
```

Which shows that you're using Google Tag Manager. If that's not what you're using on the backend, then that's why you're not getting any tracking data. Looks to me you have it misconfigured in `_config.yml` as the `provider` and `google` line needs to be indented properly.

Instead of this:

```yaml
analytics:
provider: "google-universal"
google:
  tracking_id: "UA-151868570-1"
  anonymize_ip: false # default
```

You want:

```yaml
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-151868570-1"
    anonymize_ip: false # default
```

**Comment by deepns** [comment]
Thank you. That solved the problem. My bad, I missed to notice the misconfiguration in _config.yml.
