### ISSUE TITLE
How to apply tags on collections.

### ISSUE THREAD

**Issue by coding-Alice** [mmistakes/minimal-mistakes#2325]
Hello, I am very very new to Jekyll and Ruby. I'm not a fluent English speaker/writer, sorry for bad English. 

I want to use tag function with collections. I have seen the previous issue, https://github.com/mmistakes/minimal-mistakes/issues/1256 that tags for collection is not working. 

Then I found a recent post on online where someone has somehow collected the tags from collections (he named it projects, but it seems like it's working like a collection). https://talk.jekyllrb.com/t/count-for-tagged-items-in-a-collection/291/4 

I looked into his code https://github.com/dieghernan/dieghernan.github.io/blob/master/blog/tags.html 

but I don't know how to apply it to the minimal mistakes theme. 

I tried replacing the code on /_layouts/tags.html but it didn't work, then I tried to change the code in tag-archive.md but it still didn't work. I think my approach is wrong. Can you please help?

Thank you.

**Comment by mmistakes** [comment]
Jekyll only supports tags and categories on `_posts`. Collections don't have that feature unless you want to do something custom like that Jekyll Talk post.

This theme doesn't support that method. There's no easy way to apply it unless you're comfortable editing the theme's core files to make it work.

**Comment by coding-Alice** [comment]
What I wanted was to organize my files into sub directories, and I just realized that it's possible to make sub directories under _post. 

Thank you for the reply!
