### ISSUE TITLE
Some possible features

### ISSUE THREAD

**Issue by aurelio-amerio** [mmistakes/minimal-mistakes#2330]
Hello, I really love this theme and I want to thank you for the awesome work you did!

I have introduced some elements in my website and I would like to make a pull request, if you find them interesting, as a way to contribute to the development of this wonderful theme:

- the possibility to enable **line numbers in code blocks**
- a **contact me page**, using slapform
- a page to **subscribe to the newsletter** (using tinyletter) and a small subscribe form in the footer
- the ability to enable the article image teaser while listing articles (for example in the home page)

If you like any of them I can work on a pull request

![techytok-contact-me](https://user-images.githubusercontent.com/43349899/69501355-71b20780-0f04-11ea-9f20-7e858f5773f7.png)
![techytok-newsletter](https://user-images.githubusercontent.com/43349899/69501356-71b20780-0f04-11ea-934f-358542b58ee0.png)
![techytok-newsletter-footer](https://user-images.githubusercontent.com/43349899/69501357-71b20780-0f04-11ea-92a7-72d97eefc839.png)
![tecjytok-recent-post-teaser](https://user-images.githubusercontent.com/43349899/69501358-724a9e00-0f04-11ea-8a03-d2a3b758a4a8.png)
![teckytok-code-block](https://user-images.githubusercontent.com/43349899/69501359-724a9e00-0f04-11ea-8c4e-3e6d1882bbe7.png)

**Comment by iBug** [comment]
Actually line numbers is already supported:

```liquid
{% highlight javascript linenos %}
var main = document.getElementById("main");
main.classList += "active";
{% endhighlight %}
```
