### ISSUE TITLE
Author Profiles in the Posts

### ISSUE THREAD

**Issue by mshlis** [mmistakes/minimal-mistakes#2333]
I do have updated versions but for some reason even with `author_profile : true` set as a both a default (through the config) and manually, it does not appear.

Im also using single layout for pages, but it appears there, just not for posts.

Any help would be greatly appreciated!

**Comment by mmistakes** [comment]
Link to your repo?

**Comment by mshlis** [comment]
https://github.com/mshlis/mshlis.github.io

**Comment by mmistakes** [comment]
Your issue is you have an `author` key in your _posts `.md` files. The theme expects there to be a corresponding author object in `_data/authors.yml` to map that info to... which you don’t have so it comes up blank on those pages.

Just remove `author: Michael Shliselberg` the front matter in those pages and it’ll work. Or you can add a `Michael Shliselberg` author object to a data file following the examples in the theme docs.

https://mmistakes.github.io/minimal-mistakes/docs/authors/

**Comment by iBug** [comment]
Making what @mmistakes said clearer: If there's an `author` key in the Front Matter of a page, then it's looked up in `_data/authors.yml`. If the `author` key is missing, then the sole author set in your site's `_config.yml` is used (think it as a default fallback that can't be specified explicitly).

**Comment by mshlis** [comment]
That fixed it, thank you so much!

**Comment by dadatuputi** [comment]
I suggest a blurb about this in the documentation - I'm coming from other jekyll sites where all my front matter has author specified. A simple blurb in the documentation about authors would be sufficient and would have saved me an hour or so.

**Comment by mmistakes** [comment]
Thought this was pretty clear in the author documentation: https://mmistakes.github.io/minimal-mistakes/docs/authors/

Happy to accept pull requests to improve if that’s not the case.

**Comment by dadatuputi** [comment]
I read that a few times, but I assumed that `_data/authors.yml` would just make more authors available, and that front matter `author: ` tag would default to `site.author`. All based on a bad assumption of course, but would 'falling back' to site.author if an author is specified and it's not in `authors.yml` hurt build time? In either case, I may do a PR. Thanks

**Comment by mmistakes** [comment]
It boils down to this which follows standard Jekyll conventions:

1. You set a `site.author` in `_config.yml`. This is used as the author for every post/page by default.
2. If you set an `author:` in a post or page this will override whatever you set in the `_config.yml` file
3. `_data/authors.yml` has almost nothing to do with assigning the author to a page. This is just a data file that is optionally looked up if you want to pull in author data (e.g. name, bio, links, etc.). You don't need this file, you could add this directly to a post/page's YAML front matter. It's just not DRY (don't repeat yourself).

Your assumption to fall back to `site.author` if an author is specified doesn't really follow convention. It's the other way around. If you specify one... it overrides the default in `site.author`.
