### ISSUE TITLE
how to strip /blog 

### ISSUE THREAD

**Issue by ysz** [mmistakes/minimal-mistakes#2336]
Thank you for great work!

I'm using mmistakes/mm-github-pages-starter. How to strip blog/ in posts (eg blog/post-notice/)? My GitHub project is already "blog"

**Comment by mmistakes** [comment]
`/blog` is part of the global permalink structure for Jekyll and not a theme thing.
Check Jekyll's docs and set the appropriate `permalink` in `_config.yml` you want to use.

https://jekyllrb.com/docs/permalinks/#global

The starter is using `permalink: /:categories/:title/` which adds the category defined in a post's front matter before it's title. If you just want `/post-notice/` change to `permalink: /:title/`

**Comment by iBug** [comment]
If you build your site under your [ysz/blog](https://github.com/ysz/blog) repository, then you can'y strip the `/blog/` part unless you connect a custom domain. It's a GitHub Pages restriction that Project Pages (as opposed to User Pages where the repository is named exactly *username*.github.io) are always placed in a subdirectory of the *username*.github.io domain.
