### ISSUE TITLE
Support copy to clipboard on code blocks

### ISSUE THREAD

**Issue by TannerYoung** [mmistakes/minimal-mistakes#2338]
I searched the issues but was surprised I didn't find one that matched this. Perhaps my search terms were wrong and if so I apologies. Thank you for the wonderful theme :)

## Summary

Support a copy-to-clipboard button on code blocks.

## Motivation

Improves user experience when interacting with documentation that has bash commands or code which is intended to be copied by the user.

## Drawbacks
Potential bloat, as it appears it will need a jquery style solution: 

https://stackoverflow.com/questions/48078199/jekyll-code-snippet-copy-to-clipboard-button

**Comment by dieghernan** [comment]
See https://github.com/mmistakes/minimal-mistakes/discussions/2795
