### ISSUE TITLE
image path variable for collections

### ISSUE THREAD

**Issue by fjp** [mmistakes/minimal-mistakes#2341]
When working with images, the paths can get quite long. In my case I work with a collections directory and put images corresponding to a collection in `/assets/collections/<name_of_collection>/...`. Is there a way to use variables to shorten the links to these images? I would like to avoid writing the first part of the image path (`/assets/collections/<name_of_collection/`) and instead use a variable. Something like `{{ page.collection }}`, `{{ page.url }}` or `{{ site.url }}` don't seem useful in this case. Is there a way to define (global) variables in Jekyll that could be used to set the corresponding image path for each collection?  

To display images I use the figure tag:

```
<figure>
    <a href="/assets/collections/a_collection/images/image-filename-1-large.jpg"><img src="/assets/collections/a_collection/images/image-filename-1-large.jpg"></a>
    <figcaption>Caption describing this image.</figcaption>
</figure>
```

**Comment by mmistakes** [comment]
I’m sure it can be done. Though what you are asking isn’t theme specific. I’d suggest widening your search and asking on the [Jekyll help forum](https://talk.jekyllrb.com/) and even Stackoverflow.

Off the top of my head you’ll probably want to abstract the logic out into an `_include` to test the current collection page’s path, then using `assign` and `capture` filters to create a new base URL variable you can prepend to your image paths.

I do something similar to test if an image is internally/externally hosted and generate the correct path in the theme’s various image helpers.

**Comment by fjp** [comment]
@mmistakes thanks for your help. I've now posted my question on the Jekyll help forum too.

Could you please elaborate a little bit more on how you would solve this? I am not sure how I can or should use the `_include` folder in combination with the `assign` and `capture` [liquid tags](https://shopify.github.io/liquid/tags/variable/) for this.

Do you mean that I could create a new file inside `_include` where I it is possible to define a new variable pointing to the image path of a collection? Something like the following:

```
{% capture img_path %}
{{ site.url }}/assets/collections/_{{ page.collection }}
{% endcapture %}
```

I am not sure about right syntax and how I should use this created file inside the pages of collections.

**Comment by mmistakes** [comment]
See what the forum has to say. But yes. Adding your own include with logic to generate the path would be one way.

**Comment by fjp** [comment]
Here is what someone posted on the forum:

> you can make your own variables in the config file and then reference them using {{site.myVariableName}} so you could add to your config file:
> 
> imgpath: /assets/collections/
> 
> and then your urls could be {{site.imgpath}}cats/fluffy.jpg
> 
> not sure that is much shorter though.
> 
> You can also make that whole figure thing an include, and pass in the filename and maybe collection name and have the include do the rest. Not sure that makes it any shorter either.

I just remembered that you have the `figure` include inside the `_includes` folder. Do you think adjusting this could help?

Instead of the default one:

```
<figure class="{{ include.class }}">
  <img src=
    {% if include.image_path contains "://" %}
      "{{ include.image_path }}"
    {% else %}
      "{{ include.image_path | relative_url }}"
    {% endif %}
    alt="{% if include.alt %}{{ include.alt }}{% endif %}">
  {% if include.caption %}
    <figcaption>
      {{ include.caption | markdownify | remove: "<p>" | remove: "</p>" }}
    </figcaption>{% endif %}</figure>
```

Something like this:

```
<figure>
  <a href=
    {% if include.image_path contains "://" %}
      "{{ include.image_path }}"
    {% else %}
      "/assets/collections/{{ page.collection }}/{{ include.image_path | relative_url }}"
    {% endif %}>
  <img src=
    {% if include.image_path contains "://" %}
      "{{ include.image_path }}"
    {% else %}
      "/assets/collections/{{ page.collection }}/{{ include.image_path | relative_url }}"
    {% endif %}
    alt="{% if include.alt %}{{ include.alt }}{% endif %}"></a>
  {% if include.caption %}
    <figcaption>
      {{ include.caption | markdownify | remove: "<p>" | remove: "</p>" }}
    </figcaption>{% endif %}</figure>
```
I am not sure if the `{{ page.collections }}` can be used this way.
Do you think this could work when I use it with something like the following inside a page:

```
{% include figure_collection image_path="images/image-filename-1-large.jpg" alt="this is a placeholder image" caption="This is a figure caption." %}
```

This would also avoid writing the file name twice (once for the link tag and for the image tag). However, the class feature is missing with this include. Maybe a for loop could help?

**Comment by mmistakes** [comment]
Think you’re just going to over complicate things. I wouldn’t advise a `for` as that will have performance implications and will slow your ire build as it grows in size.

The best you can hope for is assign the collection image path in the page’s front matter (you can do this globally with default YAML variables in _config.yml).

```
collection_baseurl: /assets/collections/foo
```

Then you can use it include or anywhere else with `{{ page.collection_baseurl }}/image.jpg`

But as the forum user mentioned, this isn’t really saving you any typing and if anything makes it harder to follow and complicated in your source.
