### ISSUE TITLE
Invalid theme folder: _sass & terminal hang

### ISSUE THREAD

**Issue by frhong** [mmistakes/minimal-mistakes#2347]
Hi Michael, first of all, thanks for the theme. My question is about "Invalid theme folder: _sass" and terminal hang when I ran this locally.  Here are the steps I took:

(1) Folked https://github.com/mmistakes/mm-github-pages-starter to my repo
(2) Git pull into a brand new folder locally. 
(3) Try BEJS (Bundle exec Jekyll serve) locally. 

Then...the message below:

```console
Richard:blog.richardhong rhmbp18$ bundle exec jekyll serve
NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
Faraday::Error::ClientError.inherited called from /Library/Ruby/Gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
Configuration file: /Users/rhmbp18/Documents/GitHub/blog.richardhong/_config.yml
            Source: /Users/rhmbp18/Documents/GitHub/blog.richardhong
       Destination: /Users/rhmbp18/Documents/GitHub/blog.richardhong/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Invalid theme folder: _sass
      Remote Theme: Using theme mmistakes/minimal-mistakes
[ ]
```
The terminal hung and the site was never served into the localhost. 

May I check what might have gone wrong? Thanks again.

**Comment by iBug** [comment]
I've reproduced the error line `Invalid theme folder: _sass`, but it appears irrelevant to me.

Please be aware that the `remote-theme` method fetches the theme from GitHub (default branch) every time you run jekyll. You most likely want to ensure that you can do a `git clone` on this repository before running `bundle exec jekyll whatever`. If network connectivity is an issue for you, consider switching to [Gem-based installation](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#gem-based-method) method.

**Comment by mmistakes** [comment]
I believe it’s a quirk with the remote theme gem plugin or Jekyll directly and not the theme. Sorry I don’t have much other insight on how to fix it.

https://github.com/jekyll/jekyll/issues/7630
