### ISSUE TITLE
Setting a _pages file as landing page

### ISSUE THREAD

**Issue by luca-martial** [mmistakes/minimal-mistakes#2349]
Hi, I'm trying to set my "About" page as my landing page. I do not want a landing page that shows the most recent posts. Just trying to keep the website as simple as possible.

I created an about.md file under _pages. I tried adding permalink: /about/ and layout: single to the header in index.html, however that seems to be the wrong move. 

Thanks!

**Comment by iBug** [comment]
Please delete your `index.html` or `index.md` and change to `permalink: /` in your `about.md`.

**Comment by luca-martial** [comment]
Works like a charm, thanks!
