### ISSUE TITLE
layout: single produces wide layout without classes: wide

### ISSUE THREAD

**Issue by Nhydrazine** [mmistakes/minimal-mistakes#2350]
All layout types give single column, wide page layout.  Author info and table of contents are vertically arranged instead of on the side in a separate column.

I have no global classes value set in _config.  I've tried classes: "" and classes: false and still nothing.  

Documentation suggests that layout: single should give the two-column layout with author info and table of contents on side.

Am I missing something?

Using minimal-mistakes 4.17.2 cloned from this repository.

**Comment by mmistakes** [comment]
What device are you viewing it on? The layouts are responsive and change depending on the width of the screen. 

Desktop has the author on the side. Anything smaller and it condenses to a single column with the author sidebar collapsed up top.

**Comment by Nhydrazine** [comment]
ahha!
Yes!  However, I do have to make the browser window take up almost my entire screen.  I'm on a 13" macbook pro, with the highest resolution setting.

Is there a way to allow the two-column display with smaller window sizes?

**Comment by mmistakes** [comment]
You could adjust the CSS. There are media queries in the various Sass style sheets that control when the layout switches from a single column to two. That happens at 1024 pixels width. 

Probably the easiest solution would be to override the [`$large` variable](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_variables.scss#L138) to something smaller to have it switch and narrower width.

Take a look at the [docs on how to override Sass variables](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#customizing) in the theme. If you add something like this to ` /assets/css/mains.scss`:

```sass
$large: 900px; 
```

That would override the large breakpoint.

**Comment by Nhydrazine** [comment]
Excellent!
Much appreciated!
This is a really fantastic theme, very thorough and customizable.
