### ISSUE TITLE
 How to change theme to suit right handed languages

### ISSUE THREAD

**Issue by MuhammadIbnAlAbbas** [mmistakes/minimal-mistakes#2353]
how to change theme to suit right handed languages so that it changes from being left aligned:

![Screenshot_2019-12-24 يل يبلاسب لايبل تيلاتن بل ا الحياة](https://user-images.githubusercontent.com/53350464/71384014-dda49000-25d6-11ea-834e-42358ec38889.png)

to become right aligned:
![Screenshot_2019-12-24 سر بسم الله الرحمن الرحيم - موضوع](https://user-images.githubusercontent.com/53350464/71384026-ea28e880-25d6-11ea-9178-c49b407bd9f7.png)

**Comment by mmistakes** [comment]
You’ll need to alter the themes CSS to do this.
