### ISSUE TITLE
Cannot enable comments ( Disqus )

### ISSUE THREAD

**Issue by navanchauhan** [mmistakes/minimal-mistakes#2357]
Website: navanchauhan.github.io
GH: github.com/navanchauhan/navanchauhan.github.io
Shortname: navan-chauhan

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mmistakes** [comment]
Have you set `comments: true` on the posts you want comments enabled on?
You can also enable it for all posts by using front matter defaults, which I see [you have commented out](https://github.com/navanchauhan/navanchauhan.github.io/blob/master/_config.yml#L307).

**Comment by navanchauhan** [comment]
Good lord, such a dumb mistake

Thank you

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
