### ISSUE TITLE
How to embed a pdf file inside my GitHub page with minimal-mistakes?

### ISSUE THREAD

**Issue by ToadHanks** [mmistakes/minimal-mistakes#2361]
I have made a pdf.html file inside the _layouts folder, code in it as follows:

    {% highlight html %}    
    {% raw %}       
       <!DOCTYPE html>       
           <html>       
            {% include head.html %}    
               <body>
                  {{ content }}   
               </body>     
            </html>   
     {% endraw %}    
     {% endhighlight %}    

Then a resume.md file with the following:

      ---
     title: "Résumé"
     layout: pdf
     permalink: /resume/
     ---

      <iframe src="https://drive.google.com/file/d/1gTkiMqqYOYQv8PmhzC559x51Pfc9cj36/preview" width="640" height="480"></iframe>

I then added an appropriate navigation in _data folder too. But I don't see any embedded pdf in my GitHub pages. I will appreciate if you help me out.

**Comment by ToadHanks** [comment]
I have also checked the "pdf rendering?" post, but couldn't see a possible solution in there.

**Comment by mmistakes** [comment]
You need to link to the PDF. I don’t see anywhere you’ve done that.

**Comment by mmistakes** [comment]
This doesn’t appear to be a theme issue either. You might want to dig into Jekyll/GitHub Pages support.

**Comment by ToadHanks** [comment]
hello, I have tried this prior:

    ---
    title: "Résumé"
    permalink: /resume/
    header:
    ---
    [See it here :)](http://ToadHanks.github.io/images/mihir_resume_2019v5.pdf)

Then I get a link that opens to new tab instead of a pdf embedded page. However, I have saved to pdf to image, and was able to display that  in the page.

**Comment by ToadHanks** [comment]
Update: Actually you're 100% correct, I should have sent the question to Jekyll. This problem is not related to the theme you made. Apologies sir.

**Comment by ashesh-0** [comment]
Just for completeness sake,  below is a pdf embedding example.
```
Code: https://raw.githubusercontent.com/belovanna/belovanna.github.io/b64e6c285e0e057f9bc9a1723a4eb767446a1947/_pages/curriculum.md
Effect: https://belovanna.github.io/Curriculum/
```
I felt using `classes: wide` makes it better.

**Comment by opendatasurgeon** [comment]
Thanks @ashesh-0 Appreciate the input.
