### ISSUE TITLE
Liquid Exception: uninitialized constant Faraday::Error::ConnectionFailed Did you mean? Faraday::ConnectionFailed in /_layouts/default.html

### ISSUE THREAD

**Issue by antonmarin** [mmistakes/minimal-mistakes#2362]
## Environment

- Minimal Mistakes version: 4.17.2
- Ruby gem or remote theme version: remote_theme
- Jekyll version: github-pages: 203
- Git repository URL: https://github.com/antonmarin/antonmarin.github.io
- GitHub Pages hosted (if yes provide URL to site): https://antonmarin.github.io/
- Operating system: macOS

## Expected behavior

build successfull (steps next)

## Steps to reproduce the behavior

- git clone ...
- docker run --rm -i -e JEKYLL_GITHUB_TOKEN -v ${PWD}:/app antonmarin/github-pages:203-alpine build --future

## Other

[https://stackoverflow.com/questions/59558141/jekyll-minimal-mistakes-theme-throwing-uninitialized-constant-faradayerrorc]() resolved issue

**Comment by mmistakes** [comment]
Closing as this isn’t a theme issue. It has to do with your Docker/Ruby environment.

**Comment by antonmarin** [comment]
Did i understand right, that theme don't require faraday?

**Comment by mmistakes** [comment]
That’s correct. You may need it for Jekyll/GitHub Pages gems buy my theme certainly doesn’t need it.

**Comment by antonmarin** [comment]
Thanks a lot 👍

**Comment by iBug** [comment]
It's an issue with Faraday v1.0. You may want to stick to 0.17 until it's fixed.

```ruby
# Gemfile
gem 'faraday', '~> 0.17'  # lock major version
```
