### ISSUE TITLE
High resolution screenshots?

### ISSUE THREAD

**Issue by rodrigograca31** [mmistakes/minimal-mistakes#2363]
## Suggestion
Hi.

I think you guys should use higher resolution images for the Skins (color variations)....
I understand they are there just to show the color difference but annoyed me to see crappy resolution when opening the images on a new tab....
[Example here](https://camo.githubusercontent.com/c2d782bc84adf107d7419f67552588fb0658f669/68747470733a2f2f6d6d697374616b65732e6769746875622e696f2f6d696e696d616c2d6d697374616b65732f6173736574732f696d616765732f73756e726973652d736b696e2d617263686976652e706e67)

If anyone can provide me with the sample posts used on the original images I will happily send a PR with high resolution screenshots for all the color variations.

**Comment by mmistakes** [comment]
The originals don't exist any more. But if you want to create some new ones at a higher resolution I'd be cool with that.

When I created the screenshots originally for all of the skins I followed this workflow:

1. Pull down `mmistakes/minimal-mistakes`
2. `cd test`
3. `bundle install`
4. `bundle exec jekyll serve`
5. Grab screenshot of the home page
6. Start Jekyll server.
7. Change `skin:` in `/test/_config.yml` file, restart Jekyll server, grab screenshot..
8. Rinse and repeat.

**Comment by rodrigograca31** [comment]
but that wouldnt have any content right?

is that ok?

**Comment by mmistakes** [comment]
It should have content if you follow the steps above. The [`/test` folder](https://github.com/mmistakes/minimal-mistakes/tree/master/test) is a complete Jekyll site I use for debugging and testing all of its features. 

If you `jekyll build` that you will get a full site with archives, home page, posts, collections, etc. Its the same content I used to grab the skin screenshots in the docs.

**Comment by rodrigograca31** [comment]
oh! didnt noticed the `test` folder :)

**Comment by rodrigograca31** [comment]
I have the images but couldn't find the the original folder where they are for example:
[https://mmistakes.github.io/minimal-mistakes/assets/images/air-skin-archive.png](https://mmistakes.github.io/minimal-mistakes/assets/images/air-skin-archive.png)

and I can't find the `assets/images` folder so I will leave the images here and hopefully you can update them?

![sunrise](https://user-images.githubusercontent.com/1134310/72024617-afc57980-326d-11ea-8057-a67523a7220a.png)
![plum](https://user-images.githubusercontent.com/1134310/72024619-afc57980-326d-11ea-983e-0b1e8b2cbfb8.png)
![mint](https://user-images.githubusercontent.com/1134310/72024620-afc57980-326d-11ea-8a91-10185e087f16.png)
![neon](https://user-images.githubusercontent.com/1134310/72024622-afc57980-326d-11ea-8b8b-710013c3d419.png)
![dirt](https://user-images.githubusercontent.com/1134310/72024623-afc57980-326d-11ea-8557-b61d31bc958f.png)
![dark](https://user-images.githubusercontent.com/1134310/72024625-b05e1000-326d-11ea-9769-171df0c33b65.png)
![contrast](https://user-images.githubusercontent.com/1134310/72024626-b05e1000-326d-11ea-8c69-31f57b14dbed.png)
![aqua](https://user-images.githubusercontent.com/1134310/72024627-b05e1000-326d-11ea-81f4-44122546480a.png)
![air](https://user-images.githubusercontent.com/1134310/72024628-b0f6a680-326d-11ea-95bb-632912a37b9f.png)

**Comment by mmistakes** [comment]
They go in [`/docs/assets/images/`](https://github.com/mmistakes/minimal-mistakes/tree/master/docs/assets/images)

And looking in that folder I have larger versions already. I believe I linked up the smaller versions in the README as it was wasteful to load the larger ones.

The better solution would be to show the small version, link to the large one. Something like this:

```markdown
[![air skin](https://mmistakes.github.io/minimal-mistakes/assets/images/air-skin-archive.png)](https://mmistakes.github.io/minimal-mistakes/assets/images/air-skin-archive-large.png)
```

Would yield this:

[![air skin](https://mmistakes.github.io/minimal-mistakes/assets/images/air-skin-archive.png)](https://mmistakes.github.io/minimal-mistakes/assets/images/air-skin-archive-large.png)

**Comment by rodrigograca31** [comment]
oh! the docs folder! I forgot!
I noticed it was a github page and I was looking for gh-pages branch but they had "versions" and I got confused .... :joy: 

Should we just update the links to the large version like you said or also update the images with my new ones? (I just noticed mine have the left bar "repeated" .... the extension sucsk.... :joy: )

**Comment by mmistakes** [comment]
Let update the links to the large versions and go from there. Wish I had remembered sooner that I had the 2x images in that folder. Would have saved you some time.
