### ISSUE TITLE
Error processing value 'repo_pages_info using this theme

### ISSUE THREAD

**Issue by biko-the-bird** [mmistakes/minimal-mistakes#2370]
I am using OSX. I have previously setup a github blog and it runs locally and on github.io with the default minima theme. When attempting to add your theme I encountered this error. I think I will just stick with the default but you may wish to know of this.
This is the complete output of the command ```jekyll serve```. 

```/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /Users/x/programs in PATH, mode 040777
Configuration file: /Users/x/Projects/my-github-site/_config.yml
            Source: /Users/x/Projects/my-github-site
       Destination: /Users/x/Projects/my-github-site/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
     Build Warning: Layout 'post' requested in _posts/2020-01-10-welcome-to-jekyll.markdown does not exist.
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: Error processing value 'repo_pages_info':
  Liquid Exception: uninitialized constant Faraday::Error::ConnectionFailed Did you mean? Faraday::ConnectionFailed in /_layouts/default.html
jekyll 3.8.5 | Error:  uninitialized constant Faraday::Error::ConnectionFailed
Did you mean?  Faraday::ConnectionFailed``

**Comment by mmistakes** [comment]
Your post is looking for a layout named `post` and that does not exist in my theme. You need to use a layout like `single` instead.

Consult the docs for more info. 

The `repo_pages_info` error has to do with some faraday gem.

https://talk.jekyllrb.com/t/error-repo-pages-info-and-connectionfailed-in-layouts-default-html/3793

**Comment by iBug** [comment]
The Faraday issue is the same as that in #2362.

**Comment by biko-the-bird** [comment]
thank you so much
