### ISSUE TITLE
Support anchor headings

### ISSUE THREAD

**Issue by tobiasvl** [mmistakes/minimal-mistakes#2372]
## Summary

Support for [allejo/jekyll-anchor-headings](https://github.com/allejo/jekyll-anchor-headings) as a helper would be nice, if possible.

## Motivation

Since [allejo/jekyll-toc](https://github.com/allejo/jekyll-toc) is supported already, it seems logical to also support this one.

Anchor headings have been suggested before, in #860, using AnchorJS. This is a simpler solution, IMO.

## Drawbacks

None that I can see

**Comment by mmistakes** [comment]
Am I missing something, the the already supports anchor headings and has for some time.

**Comment by tobiasvl** [comment]
Oh, my mistake, sorry. I can't see it listed under [Helpers](https://mmistakes.github.io/minimal-mistakes/docs/helpers/) or anywhere else in the docs (at least that I can find by searching), and it doesn't seem to be enabled by default, but it's probably I who am missing something!

**Comment by mmistakes** [comment]
The links are there. TOC points to header anchors and when you hover a
headliner (or click on mobile) a link icon appears to copy if needed for
sharing.

**Comment by tobiasvl** [comment]
Ah, right, I see. I thought you meant that allejo/jekyll-anchor-headings was supported, but it's actually a feature that comes with the TOC helper. So if I'm not mistaken, anchor link icons will not show up for headlines on pages that do not have a TOC. Not a biggie, I suppose. Thanks.

**Comment by mmistakes** [comment]
Anchor links show for all pages that have headers. You don’t need a TOC.

**Comment by ryan-p-randall** [comment]
I think this is related enough to not start a new issue; let me know if you'd rather it be a new one.  

I noticed that I **do** have a couple pages with headings that don't have the anchor links, although they are indeed there on most of my posts and pages. The anchors specifically are not present on [my home page](https://ryanpatrickrandall.com) and [another one](https://ryanpatrickrandall.com/about/). Both of those use an html include.  

Maybe I'm editing those two pages the wrong way?

**Comment by iBug** [comment]
@ryan-p-randall It seems like the anchor JS runs only on pages with `single` layout (or another layout with a `.page__content` wrapper), not with the `home` layout you're currently using.

The relevant code is [here](https://github.com/mmistakes/minimal-mistakes/pull/2251/files#diff-877e141496fb1421ed7b68b4c89d1a38R137).

**Comment by mmistakes** [comment]
I’d also add that headers that are part of the layout and not written in Markdown won’t get unique `id`s added as attributes. Which is needed to make all of this work.

**Comment by mmistakes** [comment]
Closing as this is already a feature of the theme.
