### ISSUE TITLE
Need to have tags in "the box" in Posts by tag page

### ISSUE THREAD

**Issue by ToadHanks** [mmistakes/minimal-mistakes#2375]
Hello,

Thanks a lot for everyone who have worked in this theme.

I have a quick question, is there a way to get the "Posts by Tag" page tags look similar to let's say one on the normal posts page?

For instance this guy needs to be changed from this:

![current_tag](https://user-images.githubusercontent.com/47681434/72749481-2a549a00-3b88-11ea-9e28-f94aba569ac3.png)

to tags in enclosed in independent boxes, similar to this):

![boxtestsLike](https://user-images.githubusercontent.com/47681434/72749511-422c1e00-3b88-11ea-8e01-ed4125140825.jpg)

or even this is ok:

![thisisok](https://user-images.githubusercontent.com/47681434/72749803-034a9800-3b89-11ea-86b1-4342ad6a229f.png)

I have added the `tag-archive.md` on my ` _pages` directory,
 ```
---
title: "Posts by Tag"
permalink: /tags/
layout: tags
author_profile: true
---
````
      
and the current situation is a result of that. Earlier I was getting 404s. Please help, or point me to right direction, I have searched the issues, but nothing similar to mine.

Link to my tag-list.html:
https://github.com/ToadHanks/ToadHanks.github.io/blob/master/_includes/tag-list.html

Link to my tags.html:
https://github.com/ToadHanks/ToadHanks.github.io/blob/master/_layouts/tags.html

~Mihir

**Comment by ToadHanks** [comment]
P.S. I have looked at the demos in _docs folder. Still have problem.

**Comment by mmistakes** [comment]
You're missing the CSS to style the list. If you inspect the tags you'll see it has a class of `.taxonomy__index`. Your repo doesn't have the CSS to go along with that which is why it doesn't look correct.

As far as I can tell you're using an outdated version of the theme (v4.9.0). The latest version is [4.17.2](https://github.com/mmistakes/minimal-mistakes/releases/tag/4.17.2)

Please update.

**Comment by ToadHanks** [comment]
Oh wow, didn't know. Thanks Mr. Rose.
