### ISSUE TITLE
Removing years from posts layout, and changing color i.e. from "Back to top"

### ISSUE THREAD

**Issue by ToadHanks** [mmistakes/minimal-mistakes#2376]
Sorry,

I left the last post open in case I would run into some issues or had questions. Sorry to bother, two quick questions.

Is there a way to remove (or hide) year and count from the pages with `posts' layout?
![date_areHere](https://user-images.githubusercontent.com/47681434/72760411-a8279e00-3ba6-11ea-9b13-2bb21f4d880a.png)

Second, which file contains the font colors for 'default' theme? Like I wanted to change Back to top $ Posts title labels color from blue to gray. 

![change_color](https://user-images.githubusercontent.com/47681434/72760489-e7ee8580-3ba6-11ea-8b0c-809c8a44430b.png)

I looked in directories after updating, but can't seem to find these. Also looked at past issues, and your docs page, no luck. I promise this time it is last question.

~Mihir

**Comment by mmistakes** [comment]
1. Edit this layout to remove the post count https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/posts.html#L12
2. Edit the CSS to change the link color here https://github.com/mmistakes/minimal-mistakes/blob/6d28d12d1dcf4883d41e168882c06f1d9948c040/_sass/minimal-mistakes/_page.scss#L392

**Comment by ToadHanks** [comment]
Nice, thank you very much dude. You rock!
