### ISSUE TITLE
author_profile changes doesn't show up on sidebar and footer

### ISSUE THREAD

**Issue by anhluong** [mmistakes/minimal-mistakes#2382]
anhnluong.com
https://github.com/anhluong/anhluong.github.io

Somehow, my author's profile sidebar and footer are lost in the upgrades process. There's no elements. And I can't figure out why. Please save my sanity and help. Otherwise, I think I will nuke the repo and start over. :D

**Comment by iBug** [comment]
I recommend starting again using either gem-based installation or the remote theme method. It's too easy to get things wrong if you fork the repository and edit.
