### ISSUE TITLE
staticmanapp no longer a user on github.com

### ISSUE THREAD

**Issue by improvethings** [mmistakes/minimal-mistakes#2383]
## Environment

- Minimal Mistakes version: minimal-mistakes-jekyll 4.18.1
- Ruby gem or remote theme version:
- Jekyll version: jekyll 3.8.6
- Git repository URL: private
- GitHub Pages hosted (if yes provide URL to site):
- Operating system:

## Expected behavior

I expected to find the user _staticmanapp_ on github to add as a repository collaborator. 

update: I think this is related to [bug 2170](https://github.com/mmistakes/minimal-mistakes/issues/2170) so it's likely just a matter of updating the config to reference what appears to the [new instructions to getting staticman v3 working on heroku](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/2/).

## Steps to reproduce the behavior

Following the steps on https://mmistakes.github.io/minimal-mistakes/docs/configuration/
under "Add Staticman as a collaborator" it says: 
_Allow Staticman push access to your GitHub repository by clicking on Settings, then the Collaborators tab and adding staticmanapp as a collaborator._
But there is no "staticmanapp" account when I try this.

**Comment by mmistakes** [comment]
You'll have to check Staticman's issues. I know there's been a lot of issues with the public instance and the GitHub bot. I don't really have control over either of those.

For my personal site I spun up my own instance of Staticman on Heroku. If you're serious about using Staticman that's the path I'd suggest as the public instance just isn't an option as it goes over the free tier limits all the time.

Closing as this is a Staticman issue.

**Comment by VincentTam** [comment]
Update: please stay away from any public API instance, as Staticman's maintainer recommends.
