### ISSUE TITLE
Staticman v2 provider configuration inconsistency

### ISSUE THREAD

**Issue by travisdowns** [mmistakes/minimal-mistakes#2386]
## Environment

- Minimal Mistakes version: 4.18.1
- Ruby gem or remote theme version: jekyll-remote-theme (0.4.1)
- Jekyll version: 3.8.5
- Git repository URL: http://github.com/travisdowns/mm-test
- Operating system: Linux

## Expected behavior

The staticman configuration implementation and doc seems a bit inconsistent. The [configuration doc](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#static-based-comments-via-staticman) shows that the `branch` key should be nested under `comments`, i.e., at `site.comments.staticman.branch`:

![image](https://user-images.githubusercontent.com/2403521/73384302-ffa9c600-4298-11ea-8b58-f3985cd1e2d7.png)

However, in the template [_config.yml](https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml#L32) in master, `staticman` is not nested under comments, but at the top level:

![image](https://user-images.githubusercontent.com/2403521/73384666-b017ca00-4299-11ea-8b10-13a1f1ea8cef.png)

I believe this is the way it was supposed to work for staticman _v1_, because the staticman API bridge lookins in _config.yml for it's _own_ configuration parameters.

However, for `v2`, this stuff goes in a separate `staticman.yml` file. So the actual bug I find is that in the [staticman_v2 provider](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments-providers/staticman_v2.html), it is checking the not-nested `site.staticman.branch`, rather than `site.comments.staticman.branch`:

![image](https://user-images.githubusercontent.com/2403521/73384820-084ecc00-429a-11ea-9b4e-3893b5ec9479.png)

This means if you configure staticman v2, it will be missing the javascript associated with form submission. As it turns out, comment submission will still go through, but you end up getting redirected to the JSON results page of the API bridge, because the default `action` is to do that, when the JS is missing, I guess.

**Suggested fix:**

1) Change `site.staticman.branch` to `site.comments.staticman.branch` in the v2 provider.
2) Clarify the documentation and default config.yml where to put the staticman stuff depending on the version. Include nested under `comments` the v2 configuration for staticman.

**Workaround:**

To get the comments working in the meantime, you can just include a redundant `staticman.branch` key at the top level so the check in the v2 provider passes, which is what I'm doing:

~~~yml
comments:
  provider: "staticman_v2"
  staticman:
    branch: "master"
    endpoint: https://staticman-travisdownsio.herokuapp.com/v2/entry/

# redundant, needed only as workaround for provider_v2.html bug
staticman:
  branch: "master"
~~~

**Comment by mmistakes** [comment]
I would follow what is in the docs. I don't think the `_config.yml` example was ever updated when this bug was report before.

Related: https://github.com/mmistakes/minimal-mistakes/pull/2351, https://github.com/mmistakes/minimal-mistakes/pull/2043

**Comment by mmistakes** [comment]
And yes you're right, doesn't look like this was ever fixed in the provider include for staticman_v2 https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/comments-providers/staticman.html#L1

And it should be:

```
{% if site.repository and site.comments.staticman.branch %}
```

**Comment by travisdowns** [comment]
@mmistakes - right, but it doesn't work if you follow the docs, although this clear only if you get half way though my bug report. Start from the text _So the actual bug_ to see the actual bug.

Essentially, it's the same fix as #2351 but in a different file.

**Comment by mmistakes** [comment]
The whole thing is a big ball of confusion anyways. v3 is really v2 with custom endpoints. In all honesty support for everything except the current custom endpoint method should be left. I don't think the public instance even works anyways and that would clear up all the issues related to that.

**Comment by travisdowns** [comment]
> The whole thing is a big ball of confusion anyways. v3 is really v2 with custom endpoints. In all honesty support for everything except the current custom endpoint method should be left. I don't think the public instance even works anyways and that would clear up all the issues related to that.

Correct, although v2 and v3 are pretty similar. I.e., you don't need a different provider for them (v2 will work fine), the only difference really is in the `endpoint` property. I think this is more or less orthgonal since it involves confusion between `v2/3` and `v1`. 

I didn't follow what you meant by "... should be left".

**Comment by mmistakes** [comment]
Should be left... keep support for it.
I deal with a lot of "my comments" don't work and they're almost always because the public Staticman endpoint is hammered and doesn't work.

Pointing people to that solution seems like a disservice since it almost never works anyways.

**Comment by travisdowns** [comment]
I agree, but I guess had troubling parsing this sentence:

> In all honesty support for everything except the current custom endpoint method should be left.

I parse it as "the current custom endpoint method should be removed, everything else should be left".

My "custom endpoint" I assume you mean using your own endpoint, and not the public instances, so I parsed this as the opposite of what you meant (sorry... don't you get to meet the most annoying pedants on github?).

**Comment by mmistakes** [comment]
Yup :smile:
