### ISSUE TITLE
What does '5 of 10' mean?

### ISSUE THREAD

**Issue by MinSeungHyun** [mmistakes/minimal-mistakes#2396]
https://github.com/mmistakes/minimal-mistakes/blob/b06b6477e95a96dc3a28cee0b316e3fc317fcdf2/_sass/minimal-mistakes/_archive.scss#L152-L227
I'm customizing this code. But I can't find the meaning of "of".
How should I search for this?

**Comment by iBug** [comment]
It's some Sass/Scss magic.

https://www.oddbird.net/susy/docs/api.html

**Comment by MinSeungHyun** [comment]
Wow thanks
