### ISSUE TITLE
Create an FAQ page?

### ISSUE THREAD

**Issue by iBug** [mmistakes/minimal-mistakes#2397]
I see a lot of people open issues for similar questions, so I feel that an FAQ page would be helpful to both sides:

- Users solve common questions more easily
- Maintainers spend less time digging through issues to find duplicate sources

The FAQ page would follow your changelog / history page, with each item linked to its original issue thread for faster lookup and navigation.

**Comment by mmistakes** [comment]
It's a good idea but not sure if it will be of much help. In my experience no one reads the documentation to begin with. A lot of the support issues are for things that are covered in detail in the docs already.

The other 3 questions I get over and over again are general Jekyll 101 things. Not sure how to handle those as I don't really want to be a "how to use Jekyll guide"...

**Comment by mmistakes** [comment]
@iBug Looks like **Discussions** are in beta on GitHub and I see this being a useful way of surfacing frequently asked (and answered) questions.

Having them under Issues has never been that great. Not sure when it will make it to all GitHub users but [next.js has it enabled now](https://github.com/zeit/next.js/discussions).

**Comment by iBug** [comment]
@mmistakes (OT) May I ask for "Triage" access to this repository so I can better help sort out new issues and PRs?

![image](https://user-images.githubusercontent.com/7273074/76843609-04d9c900-6877-11ea-924e-b80ddba305bd.png)

**Comment by mmistakes** [comment]
@iBug Doesn't look like there are roles on personal GitHub repos. If there are I couldn't find where you set that.

**Comment by iBug** [comment]
Oops, I might have forgot this. Seems like it's for organization repos only. Never mind.

**Comment by mmistakes** [comment]
I'm hoping the Discussions feature rolls out eventually. Most of these "issues" fit better in that area where they can treated more like a help forum. And then issues can go back to being a bug tracker instead of a repository of how to's.

**Comment by iBug** [comment]
Well then let's set this aside until Discussions becomes generally available.

**Comment by aschrijver** [comment]
> It's a good idea but not sure if it will be of much help. In my experience no one reads the documentation to begin with.

Well, don't underestimate the power of these docs. I for one really appreciate all the documentation you created, and I thank you a lot for creating it! I am not a Ruby / Jekyll developer myself, and many things are not directly obvious without this extra info. +1

**Comment by iBug** [comment]
Not stale.

**Comment by iBug** [comment]
Hey, I just came up with this. I still feel that extra permissions (managing issues and PRs) would be more productive. If you're not fine with granting me permission to push, "branch protection rules" come out helpful, as shown below.

![image](https://user-images.githubusercontent.com/7273074/82526142-cd80e480-9b65-11ea-8cef-0983360f7de6.png)

You can check the first one and uncheck the last one, so no one else except yourself can push directly to the master branch (or whichever you'd like to protect - an asterisk as a catch-all wildcard is also useful). Does this sound good?
