### ISSUE TITLE
Page-Link on home site will only show 404 page

### ISSUE THREAD

**Issue by maximusKarlson** [mmistakes/minimal-mistakes#2400]
Hey,

I was creating my website and everything works fine, except the specific page I created (**Machine Learning**) will not open when clicking on the button within the home page. I always get redirected to the 404-page. I created an **About** page which works totally fine.

Here is a link [to my page](https://maximuskarlson.github.io/machine-learning/)

The code I used for creating the machine-learning page is as follows:
```
---
layout: archive
title: "Machine Learning Posts by Tags"
permalink: /machine-learning/
header:
  image: "/images/ny.jpg"
----

Test
```

I inlcuded the `pages` within the default settings in the `_config.yaml`:

```
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
```

and the markdown-file for the machine-learning pages lives within the `_pages` folder.

Did somebody experience the same behavior or does know a solution to this?

Thanks in advance.

## Environment

- Minimal Mistakes version: 4.18.1
- Ruby gem or remote theme version:
- Jekyll version: 
- Git repository URL: https://github.com/maximusKarlson/maximuskarlson.github.io
- GitHub Pages hosted (if yes provide URL to site): https://maximuskarlson.github.io
- Operating system: Mac

**Comment by mmistakes** [comment]
Check your YAML front matter on that page, you have a typo... too many hyphens. Needs to start and end with `---`, you have 4 `----`

Try this instead:

```
---
layout: archive
title: "Machine Learning Posts by Tags"
permalink: /machine-learning/
header:
  image: "/images/ny.jpg"
---

Test
```

**Comment by maximusKarlson** [comment]
Wow... Sorry for asking this question. It was the fourth hyphens. Thank you very much!
