### ISSUE TITLE
Image needs specific directory to render on GitHub Pages?

### ISSUE THREAD

**Issue by methz** [mmistakes/minimal-mistakes#2403]
**This is a question about using the theme.**

Hello Michael. I'm Marcos and I need your help.

First of all, I would like to thank you for your production, it was exactly what I needed to create my website for scientific dissemination.

That said, let's go to the problem, which is simple and strange, but due to lack of experience and knowledge I have no idea how to fix it.

I'm having a problem with images. When I place a header image in any other directory than `/assets/images` it is not found on GitHub Pages. I created the `/assets/images/posts` directory, but it doesn't work. The other two directories I created (`authors and site`) apparently had no problem.

I can access the `/assets/images/posts` directory normally in the local environment **(using remote configuration)**, but when I upload it to GitHub Pages it doesn't work. And if I put the image in `/assets/images` it will work again, however, it does not load automatically, as if it were a remote link and was downloading. So the question is, why does it only work in the `/assets/images` directory?

And I inspected your site's HTML and it points most images to `../assets/images/..`, but in your repository that directory doesn't even exist. How is this possible?

I don't know if it's related, but I had the same problem when trying to add background images on the home page. It only worked with remote link, the directories were not recognized. But in this case, it didn't work even in a local environment.

I'm using [this post](https://github.com/methz/minimal/blob/master/_posts/2020-02-10-betinha-news-%232.md) as example. You can find all files in [this repository](https://github.com/methz/minimal). And you can see the site online through this [link](https://methz.github.io/minimal/).

Thanks in advance,
Marcos.

**Comment by mmistakes** [comment]
Not sure I follow what your issue is, when I look at your site all the images appear to be working for me.

But looking at that post you included as an example. Just looking at the YAML front matter I see some errors.

```yaml
header:
  image: "/assets/images/posts/betinha.jpg"
  teaser: /assets/images/posts/betinha.jpg/
```

For `teaser` your image path isn't accurate. It ends with a `/` which is likely a typo on your part.

If you're having issues with `/posts` folder in your image paths, then maybe that's Jekyll configuration thing. Could be ignoring that folder... I'm not sure. It's certainly not a theme issue. You'll probably want to reach out for Jekyll help in their various channels and support site.

**Comment by methz** [comment]
Michael, I have no idea what happened. I tested it for about 20 minutes and had this problem. But now it just worked. Maybe I need to give GitHub Pages more time to process everything (?). Anyway, thank you!

What about hiding directories, can you explain to me how it works? I tested some directories and saw that I don't need them on GitHub, like `_sass and _includes`, how does this work?

**Comment by mmistakes** [comment]
Have a look at Jekyll's documentation about themes. It'll explain what's going on with folders like `_layouts`, `_includes`, etc.

https://jekyllrb.com/docs/themes/#understanding-gem-based-themes

You don't need them if you've installed the theme as a Ruby gem or `remote_theme`. They are pulled in directly from the theme. The only reason you'd ever want those folders/files in your repo is if you're modifying them. Anything in your repo will override the ones bundled in the theme.
