### ISSUE TITLE
How to change the background color and text for a specific part of the home and post pages?

### ISSUE THREAD

**Issue by the-physicist** [mmistakes/minimal-mistakes#2405]
Hello Michael.

I am using the latest version of **dark theme**, but I would like to put the content section "Recent Publications" on the home page and the text of each post with a white (any clean) background.

I tried to create a `div` in `home.html` and make a new css estilization, but it didn't work. I also tried to use `$background-color: #fff;` in `main.scss`, but the background of all pages changes, I just want that part where the content appears.

Here is an example:

![example-white-page](https://user-images.githubusercontent.com/60639536/74978094-b584b200-540a-11ea-80fe-f40638115355.jpg)

I researched the issues and the documentation, but I didn't find it. I'm still learning how to use Jekyll, so forgive me if it's something very simple and obvious. Can you help me?

Thanks in advance,
Marcos.

**Comment by mmistakes** [comment]
This really isn't something that is Jekyll specific, it's just standard CSS. You'll want to research how to work with CSS to tackle this enhancement.

A pointer I can give you is made use of your browsers development tools. It will allow you to inspect any element on the page and see the current styles. It will also give you the selector names so you'll know what to target in your CSS file to modify the colors.

![image](https://user-images.githubusercontent.com/1376749/74979015-bfeb7f80-53fb-11ea-8a10-ba495f2d893e.png)

**Comment by the-physicist** [comment]
I already knew this information and I know the basics of CSS, I just thought that due to the structure of the theme and Jekyll it would be something more complicated. Maybe I don't really understand the fron-end basics...

I think I need to talk to more people, being locked up at home alone doing a website makes the person a little crazy. Thanks for the insight. And I'm sorry, again, to ask such an obvious question.

Anyway, I understood the structure and I can already make basic changes. It was more or less what I wanted, and now I got it (it's probably horrible, but with time I get better):

![image](https://user-images.githubusercontent.com/60639536/74986328-19fa3e00-5418-11ea-88bc-dcd4d57a1ee2.png)

![image](https://user-images.githubusercontent.com/60639536/74986976-ef5cb500-5418-11ea-8981-fdda234c909e.png)

I know you must be tired of reading this, but I really loved your theme, you did a great job! Congratulations.

Thank you very much for your attention.
