### ISSUE TITLE
I read most of issues topic about comment, but my comment still doesn't work

### ISSUE THREAD

**Issue by taojiangdt** [mmistakes/minimal-mistakes#2406]
https://github.com/taojiangdt/taojiangdt.github.io
Now my comment in production only show a title "Leave a comment", there is an empty area under "Leave a comment" can not input comments. Now, I would like to fix below problems:
1) how to make comments work in both of 'development',and 'production'?

2) There is no Netlify file in the mmistakes template, so how to and where is set JEKYLL_ENV=production?
https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L66

3) Which file to set up below code?
{% if jekyll.environment == "production" %}
   {% include disqus.html %}
{% endif %}

I read ticket #1562, and follow below posts:
https://mmistakes.github.io/minimal-mistakes/docs/configuration/#comments
https://jekyllrb.com/docs/configuration/environments/
https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L66
And I also know :
Therefore if you omit JEKYLL_ENV from the build arguments, the default value will be JEKYLL_ENV=development

Please help to work on it, thank you very much!

**Comment by mmistakes** [comment]
Netlify lets you set environmental fields. You can add `JEKYLL_ENV` and `production` values in either a Netlify config file or under your site dashboard:  **Settings > Build & deploy > Environment > Environment variables**

https://docs.netlify.com/configure-builds/environment-variables/#declare-variables

**Comment by taojiangdt** [comment]
Sorry, what is my site dashboard: Settings ? where do I can find my site dashboard?

**Comment by mmistakes** [comment]
Log into your Netlify account. There's all sorts of configurations there.

**Comment by taojiangdt** [comment]
Oh ,Thank you . I don't know should create connection between my site in github and Netlify.
There two questions:
1) Could you please teach me why do we need to create this connection between github and Netlify?
2) And I need to Create a new site in Netlify? because my site can't search in Netlify

Thank you

**Comment by mmistakes** [comment]
You don't have to create your site with Netlify. I assumed you were deploying that way since you mentioned Netlify above.

If you're using GitHub Pages to build and deploy your site you don't need to set a production environment variable as it does it for you.

I suggest you ask for help in Jekyll various forums. Your questions aren't theme specific and you'll have more success broadening your search.
