### ISSUE TITLE
`id` for Google Drive header video embed unclear

### ISSUE THREAD

**Issue by louquillio** [mmistakes/minimal-mistakes#2420]
## Motivation

I'd like to embed a Google Drive-hosted video header, but don't understand how to derive the `id`. The documentation seems to be a copy-paste of the method for YouTube. Here:

https://github.com/mmistakes/minimal-mistakes/blame/master/docs/_docs/14-helpers.md#L239

## Suggestion

Can you please clarify? Thanks.

**Comment by mmistakes** [comment]
I didn't add or use this feature... so I'm not going to be much help.
But here's the pull request. You can sift through the code and hopefully figure things out.

https://github.com/mmistakes/minimal-mistakes/pull/1967

Looks like `id` is coming from this sample `<iframe>` HTML that I assume Google Drive provides somewhere for embedding.

```html
<iframe src="https://drive.google.com/file/d/{{ video_id }}/preview" frameborder="0" allowfullscreen></iframe>
```

**Comment by louquillio** [comment]
Okay, thanks. You have to really dig for the `id`, but it exists.

https://support.google.com/blogger/thread/1950766
