### ISSUE TITLE
Is Comments working with the latest version?

### ISSUE THREAD

**Issue by audipen** [mmistakes/minimal-mistakes#2421]
## Environment

- Minimal Mistakes version: 4.18.1
- Ruby gem or remote theme version:4.18.1
- Jekyll version:
- Git repository URL: https://github.com/audipen/audipen.github.io
- GitHub Pages hosted (if yes provide URL to site): audipen.github.io
- Operating system:

## Expected behavior

I have a followed the steps to setup Staticman as the comments provider.  The staticman API is hosted on heroku. I have read numerous posts here and elsewhere on the issues with staticman.
I just can't get the comments to show up. Tried locally also with environment set to 'production'

## Steps to reproduce the behavior

Navigating to the hosted site 'audipen.github.io' and opening any post does not show the comments form.

**Comment by mmistakes** [comment]
Check the documentation for the correct YAML in your `_config.yml`.
You don't have `staticman` properties nested correctly under `comments`. Guessing you grabbed them from the `_config.yml` in the root of this project... which I think is wrong and was never updated when the other changes were made (accepting PRs if anyone wants to fix that :wink:)

https://mmistakes.github.io/minimal-mistakes/docs/configuration/#staticman-v3

```
# _config.yml
repository  : # Git username/repo-name e.g. "mmistakes/minimal-mistakes"
comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "master"
    endpoint  : https://{your Staticman v3 API}/v3/entry/github/
```

**Comment by audipen** [comment]
oh man!! Spent hours on this! Thanks for pointing it out.  Will open a PR for that small fix
