### ISSUE TITLE
Is it possible to group collections by tags ?  i.e. a tag-archive page for recipes ?

### ISSUE THREAD

**Issue by mcmasty** [mmistakes/minimal-mistakes#2426]
I would like to apply the tag-archive pattern to a specific collection, in addition to posts.

Using your demo site, imagine your recipes also had tags "Vegan", "Gluten Free", "Quick Meal", "High-Protein", etc. And then a page to browse recipes by tag.

In a nutshell, I'd like to have a "Recipes by tag" page that basically looks identical to "Posts by tag", except the list of pages is from the collection "_recipes" instead of posts.

I couldn't figure out from digging into the GH repo, where the directive is set, to instruct the summarization of posts, to hopefully mimic it for a tag-based summation of a designated collection (such as recipe).

[Here is the repo](https://github.com/mcmasty/mcmasty.github.io)   I am working with. It is still pretty vanilla, remote install of the theme, very few customizations.

Thanks in advance for any help.

Cheers,
Tyler

**Comment by mmistakes** [comment]
Don't think this is currently possible with Jekyll. `site.tags` are only accessible to the posts collection. Have a look through the closed issues, pretty sure I covered this a few times before and provided some likes back to core Jekyll issues where others have asked for the same.

For the theme to support it, it needs to be baked into core. For whatever reason collections don't have feature parity with posts even though they should.

**Comment by mcmasty** [comment]
@mmistakes   Thanks for the quick response.

I did search the repo, but only open issues 🤦‍♂   

Apologies for asking a redundant questions.
