### ISSUE TITLE
Instagram feed rolling on the splash page

### ISSUE THREAD

**Issue by anuraj-rp** [mmistakes/minimal-mistakes#2427]
Hi,

I have the theme setup with the splash page. https://anuraj-rp.github.io/

Now I was thinking on the splash page if I can have a feed roll of photos from my Instagram on one of the three links instead of a static image and link to a page.

Any direction would be nice to have.

**Comment by mmistakes** [comment]
https://jekyllcodex.org/blog/instafeed-js-alternative-for-instagram/
