### ISSUE TITLE
Broken vertical / horizontal header images with v4.18.1

### ISSUE THREAD

**Issue by ebolat** [mmistakes/minimal-mistakes#2429]
## Environment

- Minimal Mistakes version: **4.18.1**
- Jekyll version: **3.8.5**
- Git repository URL: [https://github.com/mmistakes/minimal-mistakes](https://github.com/mmistakes/minimal-mistakes)
- GitHub Pages hosted (if yes provide URL to site): [https://mmistakes.github.io/minimal-mistakes](https://mmistakes.github.io/minimal-mistakes)

## Expected behavior

To be able to display the vertical and horizontal header images as before.
After upgrading from **v4.16.0** to **v4.18.1** I also experienced the same problem with my blog.

## Steps to reproduce the behavior

Navigate to these pages to see the broken header images:
- [Link 1 - Vertical](https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-image-vertical/)
- [Link 2 - Horizontal](https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-image-horizontal/)
- [Link 3 - External Image](https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-image-external/)

## Other
![Broken Header Image - Vertical](https://user-images.githubusercontent.com/4147867/76217883-50abc300-6224-11ea-95bb-9635f886b3b8.png)

**Comment by mmistakes** [comment]
Pretty sure this is related to a typo in the `_includes/page__hero.html` that was fixed in #2428.
GitHub Pages hasn't rebuilt the demo MM site yet to include this change, that's why the images are still broken.

It will fix when I push a new release.
