### ISSUE TITLE
How to make tags visible

### ISSUE THREAD

**Issue by lhdatalab** [mmistakes/minimal-mistakes#243]
Hi Michael,
Love this theme. I have just setup my own github.io page and I was wondering how do I make tags visible, especially for posts.

Thanks.

**Comment by mmistakes** [comment]
Take a look at my other themes (So Simple and HPSTR) for ideas on how to add tags. You essentially loop over `post.tags` to display them on a page. If you want to build archive pages for each tag you have some more work to do or can use a plugin like [Jekyll Archives](https://github.com/jekyll/jekyll-archives).

**Comment by lhdatalab** [comment]
Thanks Michael

**Comment by mmistakes** [comment]
You're welcome. Here's a few [more examples](https://github.com/cagrimmett/jekyll-tools) if you're looking for other ideas on how to do tags with Jekyll.

**Comment by mmistakes** [comment]
Added support to tag lists for posts in commit 1ccd5f6bf08082b17ca51e63a70c4b01db831b6c

**Comment by darrenhaken** [comment]
Did this every get added?

**Comment by mmistakes** [comment]
@darrenhaken Yes it did. See the comment above with a link to the commit where it was added back in April of 2016.
