### ISSUE TITLE
How to change the font-type?

### ISSUE THREAD

**Issue by edualvarado** [mmistakes/minimal-mistakes#2435]
I just want to change the font of my whole GitHub page to "Roboto". I've seeing about changing it into the _variables.scss file. How can I do it? I could not find too much info about it.

Thanks!

**Comment by mmistakes** [comment]
It can be changed via CSS. You'll need to load the webfont into the `<head>` of your site as per the instruction of whatever font service you're using. For example if you're using Google Fonts you can add the following line to [`_includes/head/custom.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/head/custom.html)

```html
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet"> 
```

Then you can update the following Sass variable in [`_variables.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_variables.scss#L32)

```scss
$global-font-family: 'Roboto', sans-serif;
```
