### ISSUE TITLE
Question - Adding Get-Pocket Api Ruby Gem

### ISSUE THREAD

**Issue by JayPowerUser** [mmistakes/minimal-mistakes#244]
I wanted to add a Ruby Gem for the get-pocket api, would you happen to know how to incorporate this  ?
Here is a link for a reference. 

https://coderwall.com/p/uxgn6g/pocket-octopress-for-parsing-pocket-links-to-posts

Sorry I don't really understand Ruby. 

Thanks,

**Comment by mmistakes** [comment]
Don't think I'll be of much help since I'm not a Ruby guy. Maybe ask for help on the [Jekyll Talk forum](https://talk.jekyllrb.com/).
