### ISSUE TITLE
problem with No repo name found. using Gemfile installation

### ISSUE THREAD

**Issue by fdq09eca** [mmistakes/minimal-mistakes#2442]
Hi, I want to use the remoted theme method but i encounter the following error
**Error**
```
  Liquid Exception: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository. in /_layouts/default.html              ERROR: YOUR SITE COULD NOT BE BUILT:                     ------------------------------------                     No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.
```
the following is my `Gemfile` and `_config.yml` for installation
**Gemfile**
```ruby
source "https://rubygems.org"
gem "jekyll-include-cache"
gem "github-pages", group: :jekyll_plugins
```
**_config.yml**
```yml
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
plugins:
  - jekyll-include-cache
```
I understand that I should add the `repository` attribute in `_config.yml`, but it is a must for me to create a repo for running the site locally? Thanks.

**Comment by iBug** [comment]
It isn't a requirement by this theme, but rather `gem "github-pages"`. One of its bundled plugins, `jekyll-github-metadata`, requires a reference to a valid GitHub repository to operate. I'd recommend that you follow the error and let Jekyll know your repository.

**Comment by fdq09eca** [comment]
> It isn't a requirement by this theme, but rather `gem "github-pages"`. One of its bundled plugins, `jekyll-github-metadata`, requires a reference to a valid GitHub repository to operate. I'd recommend that you follow the error and let Jekyll know your repository.

ok, more of question.. what is the benefit for using `remote_theme` instead of local one?
coz i still can run the site locally without providing/uploading any repo if I included the following gems in my Gemfile:

```ruby
source "https://rubygems.org"
gem "jekyll-include-cache"
gem "minimal-mistakes-jekyll"
gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jemoji"
```

**Comment by iBug** [comment]
Using `remote_theme` makes your site directly build-able on GitHub Pages. Using Gem-based installation requires CI (Travis CI / CircleCI / GitHub Actions) to build your site and push to GitHub Pages.
