### ISSUE TITLE
Page build warning mail

### ISSUE THREAD

**Issue by davidlee1818** [mmistakes/minimal-mistakes#2443]
everytime github pages republish the blog, i just keep receiving the warning mail.
just like below:
"The page build completed successfully, but returned the following warning for the `master` branch:
You are attempting to use a Jekyll theme, "minimal-mistakes-jekyll", which is not supported by GitHub Pages"
is that a normal case? or i have made some config mistakes somewhere?
i'm confused,please help me .

**Comment by iBug** [comment]
See [Quick-Start Guide](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#page-title), the first paragraph (emphasis mine):

> Minimal Mistakes has been developed as a Gem-based theme for easier use, and 100% **compatible with GitHub Pages when used as a remote theme**.

If you want to use this on GH Pages, you should drop the `theme` key from your `_config.yml` and use `remote_theme: "mmistakes/minimal-mistakes@4.19.1"`.

**Comment by davidlee1818** [comment]
problem solved,thanks a lot!
兄弟谢了谢了
