### ISSUE TITLE
Wide layout using space to the left, replacing author info?

### ISSUE THREAD

**Issue by stefanbschneider** [mmistakes/minimal-mistakes#2453]
I use minimal mistakes for a [simple website about COVID-19](https://stefanbschneider.github.io/covid19/).
I don't need the author information that's usually on the left and have disabled it globally with `author_profile: false`. I do however use the space to the right with ToCs (`toc: true`).

Is there an existing layout or a simple way to create a layout that's a bit wider than the default "single" layout but extends to the left, not to the right, ie, covering the space that's usually occupied by the author info?

**Comment by mmistakes** [comment]
There is not. I’d suggest looking at one of my other themes. The design of this theme is to have an author sidebar on the left.

**Comment by stefanbschneider** [comment]
Any recommendation which one?

**Comment by mmistakes** [comment]
https://github.com/mmistakes/jekyll-theme-basically-basic
https://github.com/mmistakes/so-simple-theme
