### ISSUE TITLE
including folder that contain only images for a gallery in front matter

### ISSUE THREAD

**Issue by fdq09eca** [mmistakes/minimal-mistakes#2454]
[the current solution](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#gallery) for a gallery is manually typing the exact directory in the front matter. Is there any solution to include an entire file instead? such that `image_path: /assets/images/`?

**Comment by iBug** [comment]
Doesn't appear to be possible at the first glance. Jekyll doesn't provide a way to list directory contents, so this for sure needs a (custom) plugin.

**Comment by fdq09eca** [comment]
for anyone interested, I found this [solution](https://github.com/sillylogger/jekyll-directory).
