### ISSUE TITLE
liquid, markdown table problem

### ISSUE THREAD

**Issue by fdq09eca** [mmistakes/minimal-mistakes#2463]
I would like to have a table of authors that in the _data/authos
i tried the following 
```md
|Title  |Link  |
|---|---|
{% for people in site.data.authors -%}
{% for person in people -%}
|{{ person.name }}  |[Click Here]({{ person.links[1].url }})  |
{% endfor %}
{%- endfor -%}
```
it gives me this
![image](https://user-images.githubusercontent.com/51902242/77585689-dc5d6900-6f1f-11ea-8543-c26a5ffe52de.png)
Notably, whenever it render a person.name or person.url, it renden one extra **Click here** which is pointing to the current page.. it is confusing.

so I try another way
```markdown
| name | b |
| ---- | --- |{% for people in site.data.authors %}{% for person in people %}
| {{ person.name }} | {{ person.bio }} |{% endfor %}{% endfor %}
```

but it gives me this..
![image](https://user-images.githubusercontent.com/51902242/77586072-7f15e780-6f20-11ea-8e25-3312d9d0364a.png)
which has a lot of empty row..

so i tried another again:
```liquid
{% for people in site.data.authors -%}
  {% for person in people %}
    {{ person.name }}
  {% endfor %}
{% endfor %}
```
it give me this:
![image](https://user-images.githubusercontent.com/51902242/77594781-64e50500-6f32-11ea-9f56-a0de57aff906.png)
it is a code block and bunch of newlines that i never intended.

any idea? Thanks.

**Comment by mmistakes** [comment]
I’ve never tried Liquid in Markdown link this so. It sure. If I had to guess the spacing from the loops might be messing with how Markdown interprets things.

You’ll probably have better luck doing a standard HTML table. 
As this isn’t theme specific I’m going to close the issue. I’d suggest asking on the [Jekyll Talk](https://talk.jekyllrb.com/) forum instead, it’s good for these sorts of inquires.

**Comment by fdq09eca** [comment]
sorry for abusing the system.
i found the answer. My `authors.yml` takes the following format:
```
Alias:
  name: "name"
  bio: bio
  avatar: "url"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:email@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "www.website.com"
```
Thus, the 1st `forloop` return an array with 2 items. The 1st is the alias the 2nd is the json. The 1st one is the culprit for all these strange behaviours (e.g empty row). So the answer is the following:
```
title|title|title
:--:|:--:|:--:
{% for people in site.data.authors %}
{%- assign person = people[1] -%}
{{ person.name }}|{{ person.name }}|{{ person.name }}
{% endfor %}
```
Thanks.
