### ISSUE TITLE
Hyvor Talk Support

### ISSUE THREAD

**Issue by KiarashS** [mmistakes/minimal-mistakes#2468]
First thanks for `minimal-mistakes`.
Please add support for [Hyvor Talk Comment Platform](https://talk.hyvor.com/).

**Comment by KiarashS** [comment]
Best option is define `id` of custom comments container in `_config.yml`:

`<section id="custom-comments"></section>`

with `custom-comments` default value.

**Comment by bbatsov** [comment]
I came here just to mention that I'm another person who'd like to see built-in Hyvor Talk support.
