### ISSUE TITLE
Alignment of figure captions

### ISSUE THREAD

**Issue by SuryaDhee** [mmistakes/minimal-mistakes#2470]
I have tried to update the CSS in the file _base.scss by augmenting a text-align: center to the figcaptions but it doesn't seem to work for me. Am I missing something?

```
figcaption {
  margin-bottom: 0.5em;
  color: $muted-text-color;
  font-family: $caption-font-family;
  font-size: $type-size-6;
  text-align : center;
```

**Comment by mmistakes** [comment]
Do you have a link to an example on your site where this is not working? `text-align: center` is the correct CSS. Perhaps you haven't customized the theme's CSS files properly and it's not loading your changes. Without seeing an example I can't really see either way.

**Comment by SuryaDhee** [comment]
The second figure's caption in this page.
URL : suryadhee.github.io

**Comment by iBug** [comment]
The `<figcaption>` has `display: block` so what you'd want to apply is:

```css
margin-left: auto;
margin-right: auto;
```

**Comment by SuryaDhee** [comment]
Yepp that did it! Thank you.
