### ISSUE TITLE
Google Analytics is not working

### ISSUE THREAD

**Issue by rnagais2** [mmistakes/minimal-mistakes#2473]
Hallo I am using Google Universal Analytics, I followed all instructions here at https://mmistakes.github.io/minimal-mistakes/docs/configuration/#analytics. But Google Analytics working is still not working...

Site is: https://rnagais2.github.io/ 
GitHub repo is: https://github.com/rnagais2/rnagais2.github.io

config.yml contains the following:
```
# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-157507096-1"
    anonymize_ip         : false # true, false (default)
```

JEKYLL_ENV=production was set to force the environment to production and there was no problem.

I have been struggling with this issue for a long time. I would appreciate any advice!

**Comment by mmistakes** [comment]
Take a look at your site and open the browser's web developer tools. In the console you have some errors.

Looking in the source I see your Analytics code, so it's not a theme issue.

```
<script>
  window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
  ga('create','UA-157507096-1','auto');
  ga('set', 'anonymizeIp', false);
  ga('send','pageview')
</script>
<script src="https://www.google-analytics.com/analytics.js" async></script>
```

You also seem to have [Google Tag Manager code near the head](https://github.com/rnagais2/rnagais2.github.io/blob/master/_includes/head/custom.html) that is incomplete and appears to be the cause of the JavaScript error. Which could be breaking the GA Analytics script.

**Comment by rnagais2** [comment]
I have deleted the incomplete code and now it totally works. Many thanks!
