### ISSUE TITLE
How to change thumbnail images "You may also enjoy" section

### ISSUE THREAD

**Issue by Rainymood** [mmistakes/minimal-mistakes#2476]
First of all I want to apologise if this question is really simple but I honestly have spent so much hours trying to fix this and I'm at my wit's end. I honestly get stressed from not being able to figure this out. I just can *not* get this to work. 

I want to change the thumbnails in the "You may also enjoy" section

<img width="1280" alt="Screenshot 2020-04-01 at 14 34 19" src="https://user-images.githubusercontent.com/2186137/78138717-adfff200-7427-11ea-8c99-d40398f872c3.png">

I have added this to the YAML front matter of the post in question

```
image:
  thumb: 2020-04-01-leetcode-thumb
---
```

And have added the image in the `/images` folder, but it does not seem to work ...

https://github.com/Rainymood/rainymood.github.io/blob/master/_posts/2020-04-01-Leetcode-378.md

**Comment by iBug** [comment]
They use the same image as `teaser` if specified in the document, while falling back to `site.teaser` (as specified in `_config.yml`) if missing.

**Comment by Rainymood** [comment]
So how would I fix this? Can i do something like this?

```
image:
  teaser: 2020-04-01-leetcode-thumb
---
```

**Comment by mmistakes** [comment]
@Rainymood yup, you got it. This is documented here: https://mmistakes.github.io/minimal-mistakes/docs/layouts/#grid-view
