### ISSUE TITLE
Paragraphs indented with no blank line

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#248]
A blank line is not recognized as the start of a new paragraph, like what GFM does on GitHub.com.
Furthermore, there is an indent, which looks weird when there is no preceding blank line.
The example picture is from https://mmistakes.github.io/minimal-mistakes/theme-setup/

<img width="310" alt="screen shot 2016-03-20 at 7 54 05 pm" src="https://cloud.githubusercontent.com/assets/300046/13909292/b839b070-eed5-11e5-904f-0f79c9e4ec47.png">

I understand that coding can be different within this theme and GitHub.

To get an empty line to show, I use the workaround of  `&nbsp; `between two blank lines.

But how can I begin a new paragragh without indention within index.md and post files?

**Comment by mmistakes** [comment]
It's a fairly simple CSS declaration. Basically I'm using [`p + p`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/typography.scss#L137) to apply an indent to a paragraph that follows another paragraph. There's also some negative margin being applied.

If the spacing is giving you issues I'd suggest disabling the indent. It's really typographic preference that's not for everyone and looks best in certain circumstances. When you have short paragraphs or list elements it can look off sometimes.

**Comment by wilsonmar** [comment]
OK. That worked for me. But I would personally prefer to have the default $paragraph-indent: off since most of my paragraphs are short. Who writes long paragraphs anymore ;)
