### ISSUE TITLE
"A flexible two-column Jekyll theme. Perfect for building personal sites, blogs, and portfolios. Latest release v4.19.1" - these words appears in Sitemap.

### ISSUE THREAD

**Issue by bondbipu** [mmistakes/minimal-mistakes#2481]
## Environment

- Minimal Mistakes version: 4.19.1
- Ruby gem or remote theme version: 2.5.5p157
- Jekyll version: 4.0.0
- Git repository URL: 
- GitHub Pages hosted (if yes provide URL to site):
- Operating system: 

## Expected behavior
The [Site mape page ](https://mmistakes.github.io/minimal-mistakes/sitemap/), Page Archive page [https://mmistakes.github.io/minimal-mistakes/page-archive/](url) is supposed to have all the pages and posts and so on. But for some reason, the words "A flexible two-column Jekyll theme. Perfect for building personal sites, blogs, and portfolios. Latest release v4.19.1 " appears in the middle of these page with a link to the homepage.

I think this is a bug. I cannot locate the words in any page or post or anywhere. This is happening to my developing site also.

**Comment by iBug** [comment]
Most likely this would be considered `status-bydesign`, as `home.md` is one of [the pages under `_pages`](https://github.com/mmistakes/minimal-mistakes/tree/master/docs/_pages).

**Comment by bondbipu** [comment]
Thanks. The issue is now resolved.
