### ISSUE TITLE
Will you have this theme in gatsby or next as well? I wanted to use this in a netlify blog

### ISSUE THREAD

**Issue by simkimsia** [mmistakes/minimal-mistakes#2484]
Hi there, 

Apologies if this was already asked. I searched the archive for past issues, but no one seems to have asked this before.

I was wondering if this theme is available as a gatsby theme. I wanted to deploy a blog on netlify using this theme. 

Thanks

**Comment by iBug** [comment]
Porting a theme is a lot of work and is unlikely to happen *here*. You're free to create your own port, however, as there's already a Hugo port of this theme.

**Comment by simkimsia** [comment]
Got it yes I appreciate that it’s a lot of work I’m sure

Thanks for reply
