### ISSUE TITLE
Turn the starter repository into a template repository

### ISSUE THREAD

**Issue by tobiasvl** [mmistakes/minimal-mistakes#2485]
## Summary

The [Minimal Mistakes GitHub Pages starter repositoty](https://github.com/mmistakes/mm-github-pages-starter) repository should be turned into a [template repository](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository), so people can create websites using Minimal Mistakes without having to fork it in the usual way.

## Motivation

* This should be done simply because the starter repository _is_ in fact a template. Making it a template repo makes this explicit.
* Every other day, someone who has formed `mm-github-pages-starter` will open a pull request against it by mistake. Turning it into a template repo will make this less likely to happen.
* Everyone who uses Minimal Mistakes on GitHub Pages will have clean commit histories.

[More about template repositories and how to use them](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template)

## Drawbacks

If the starter repository changes, it's no longer simple for everyone using it to pull down the latest changes. However, the repository doesn't change often, and hopefully shouldn't need to (everything is done in _this_ repo), but it's something to consider.

**Comment by mmistakes** [comment]
Turned `mm-github-pages-starter` into a template repository.

![image](https://user-images.githubusercontent.com/1376749/80387879-2b782000-8877-11ea-94a7-3336db1049bd.png)
