### ISSUE TITLE
Get excerpt to show in post page

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#249]
The value to except: in yaml front matter appears in the All Posts list,
but does not appear in the post itself (under the page.title).
It's relevant to the post.

In my copy, I tried to add within _layouts/post.html this between div class="headline-wrap" and div class="article-wrap" this:

`<div class="post-excerpt">
{% if page.excerpt %}{{ page.excerpt }}{% endif %}
</div`

It's still not showing now.
I'm a newbie with Jekyll, so I thought I'd check before adding to page.css.
Is that the appropriate name for the class?

**Comment by mmistakes** [comment]
Yes `{{ page.excerpt }}` is what you want. If you add `excerpt: "Whatever you want the excerpt to be."` to a post or page's YAML Front Matter it should show up that page. If it's not showing then there's something likely wrong with your YAML or you've added `page.excerpt` to the wrong layout/include.

If you want to include excerpts inside of a `{% for post in site.posts %}` or equivalent loop you'd use `{{ post.excerpt }}` instead.

As far as a class name, that has nothing to do with Jekyll. It's HTML/CSS and depending on where and how you want it styled that will likely change.

Jekyll's docs may offer some more help on [how to use excerpts](https://jekyllrb.com/docs/posts/#post-excerpts).
