### ISSUE TITLE
How can I change the colour of the header text?

### ISSUE THREAD

**Issue by thephet** [mmistakes/minimal-mistakes#2495]
I am using an image as header which has some overlay text.

I am following this:

https://mmistakes.github.io/minimal-mistakes/docs/layouts/#header-overlay

And my problem is that the colour of the text is white, while I think that Black would work better for me.

**Comment by mmistakes** [comment]
If you know how to write CSS you can change it to whatever you want. There’s nothing directly in Jekyll or the theme to facilitate this, you’ll need to customize.

https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/

**Comment by thephet** [comment]
my knowledge of css is a bit basic. what file should I modify? I tried to search around for "header" but I couldnt find it. I could modify masthead, but that's something different.

thanks for our help
