### ISSUE TITLE
Mailchimp pop-up does not appear

### ISSUE THREAD

**Issue by ekofi** [mmistakes/minimal-mistakes#2503]
Hello, there is a site code provided by mailchimp in my custom/head.html. Normally when I publish pop-ups via mailchimp, it should appear automatically because this code is on the site.
However, no pop-ups appear in any way. What could be the reason for this? Thanks.

My repo: https://github.com/ekofi/ekofimakale.github.io

**Comment by iBug** [comment]
It's showing up for me. Perhaps you should disable your ad blocker or whatever similar before trying again?

**Comment by mmistakes** [comment]
Same for me. Popup shows.
Closing as this isn't a theme issue.

![image](https://user-images.githubusercontent.com/1376749/80124382-31f85600-855e-11ea-8fd0-5e387bc9a393.png)
