### ISSUE TITLE
Custom collection pages not generating gallery

### ISSUE THREAD

**Issue by shenchingtou** [mmistakes/minimal-mistakes#2506]
## Environment

<!--
Theme version: 
Public git repository: 
Tested on MacOS 

- Minimal Mistakes version: Remote theme mmistakes/minimal-mistakes
- Ruby gem or remote theme version: latest
- Jekyll version: 
- Git repository URL: https://github.com/shenchingtou/shenchingtou.github.io
- GitHub Pages hosted (if yes provide URL to site): https://shenchingtou.github.io
- Operating system: MacOS

## Expected behavior
1. Custom gallery "recipes" should look like the "Portfolio" gallery https://shenchingtou.github.io/portfolio/ that includes a sidebar navigation. 
-- Missing sidebar 

2. Custom gallery "writing" should look like the "Portfolio" gallery https://shenchingtou.github.io/portfolio/ that includes a sidebar navigation. 
-- Missing gallery preview & sidebar 

## Steps to reproduce the behavior
*Note - the portfolio.md works.

1. Copied https://github.com/mmistakes/minimal-mistakes/edit/master/docs/_pages/recipes-archive.md

2. Created recipes.md  and writing.md
https://github.com/shenchingtou/shenchingtou.github.io/blob/master/_pages/recipes.md
https://github.com/shenchingtou/shenchingtou.github.io/blob/master/_pages/writing.md

3. Added _config.yml
` recipes:
     output: true
     permalink: /:collection/:path/`

` writing:
     output: true
     permalink: /:collection/:path/`
4. Created _recipes folder and _writing folder

5. Bundled

6. Jekyll serve locally

Thanks!

**Comment by shenchingtou** [comment]
## Environment

Theme version: 
Public git repository: 
Tested on MacOS 


- Minimal Mistakes version: Remote theme mmistakes/minimal-mistakes
- Ruby gem or remote theme version: latest
- Jekyll version: 
- Git repository URL: https://github.com/shenchingtou/shenchingtou.github.io
- GitHub Pages hosted (if yes provide URL to site): https://shenchingtou.github.io
- Operating system: MacOS

## Expected behavior
1. Custom gallery "recipes" should look like the "Portfolio" gallery https://shenchingtou.github.io/portfolio/ that includes a sidebar navigation. 
-- Missing sidebar 

2. Custom gallery "writing" should look like the "Portfolio" gallery https://shenchingtou.github.io/portfolio/ that includes a sidebar navigation. 
-- Missing gallery preview & sidebar 

## Steps to reproduce the behavior
*Note - the portfolio.md works.

1. Copied https://github.com/mmistakes/minimal-mistakes/edit/master/docs/_pages/recipes-archive.md

2. Created recipes.md  and writing.md
https://github.com/shenchingtou/shenchingtou.github.io/blob/master/_pages/recipes.md
https://github.com/shenchingtou/shenchingtou.github.io/blob/master/_pages/writing.md

3. Added _config.yml
` recipes:
     output: true
     permalink: /:collection/:path/`

` writing:
     output: true
     permalink: /:collection/:path/`
4. Created _recipes folder and _writing folder

5. Bundled

6. Jekyll serve locally

Thanks!

**Comment by Gioele-Bencivenga** [comment]
I'm trying to use this theme without having installed Ruby or Jekyll and I'm running into a similar issue with my portfolio not displaying correctly.
Did you ever figure out what the problem was?
