### ISSUE TITLE
Add a Copy-to-Clipboard button and support bilibili video

### ISSUE THREAD

**Issue by sunete** [mmistakes/minimal-mistakes#2508]
## Summary
1. add a Copy-to-Clipboard button to the code block.

2. Make the theme support to instert [bilibili](https://www.bilibili.com/) video.

### add button
I think  Copy-to-Clipboard button is necessary for this theme. A lot of posts contain code blocks. Now, this theme doesn't have a clip-to-clipboard button. When someone needs to copy the code,  they need to select all the code and ctrl+C to copy to clipboard. It is a waste of time and inconvenience. Besides,  some characters will be left. But if you add a button to the code block, it will be convenient.

I have searched for some articles to add a button by myself. I haven't learned programming before, so I can't finish it.

### support post bilibili video
Can you make this theme supports insert [bilibili](https://www.bilibili.com/) video which is a very popular video website in China? When I instert a bilibili video in the post, it couldn't adapt to the width. **This problem may not be what most people need.** So I  tried to solve this problem by myself. Finally I made it. 
This is the code in [_includes/video ](https://github.com/sunete/sunete.github.io/blob/9c5a5d5d740886b3f646f6cd14b3e7ca5762434f/_includes/video#L12)
```js
<div class="responsive-video-container">
  <iframe src="//player.bilibili.com/player.html?bvid={{ video_id }}&page=1&as_wide=1&high_quality=1&danmaku=0" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>
</div>
```

**Comment by iBug** [comment]
Hi, thanks for the suggestion. It seems like you've already figured out about the Bilibili video suggestion, so it'd be great if you could wrap it up and submit a pull request. We'd love to see your contribution! You can check out [the documentation on contributing](https://mmistakes.github.io/minimal-mistakes/docs/contributing/) if you're looking for a how-to.

**Comment by sunete** [comment]
OK，I will creat a pull request later. How about the copy-to-clipboard button? Is it possible to add the button in the next version?

**Comment by mmistakes** [comment]
Depends on the solution for doing a copy and paste button for code blocks. The ones I've seen are clunky and don't let you use standard Markdown `(```)` fenced code blocks, which is a deal breaker for me. Also not exactly sold on adding extra JavaScript to the theme for this.

- https://aleksandrhovhannisyan.github.io/blog/dev/how-to-add-a-copy-to-clipboard-button-to-your-jekyll-blog/

**Comment by mmistakes** [comment]
Added bilibili support in #2512

**Comment by dieghernan** [comment]
See https://github.com/mmistakes/minimal-mistakes/discussions/2795
