### ISSUE TITLE
Document inline images markdown URL syntax

### ISSUE THREAD

**Issue by aschrijver** [mmistakes/minimal-mistakes#2510]
## Motivation

I have a site where the staging location has a `site.baseurl` and the live version has not. While working with inline images I found - by looking at the mmistakes codebase, could not discover instruction in the docs - that instead of this:

```markdown
![my image](/assets/images/my-image.png)
```

I have to write the markdown like this in order to work when a baseUrl is set:

```markdown
![my image]({{ "/assets/images/my-image.png" | relative_url }})
```

## Suggestion

This should be added to the documentation somewhere. I tried to find it, but could not. Sorry if I overlooked it somehow.

**Comment by iBug** [comment]
This is surely a good idea, but it's not specific to this theme. I suppose such points would fit better on Jekyll's docs (or just rely on individual's Jekyll experiences).

**Comment by aschrijver** [comment]
Yes, you are right, but.. The beauty of the documentation that comes with this theme is that one doesn't have to know much about Jekyll to get started right away and only type away in markdown. And the documentation gives some explainers about e.g. adding css classes to that, so it might fit there.

**Comment by iBug** [comment]
That's a brilliant answer. But then where should this be put? There isn't a page for "miscellaneous stuff" yet :)

**Comment by aschrijver** [comment]
That is a good question :) Maybe in the Sample Posts section there can be a page 'Markup: Inline images with baseUrl set' or something similar.

But it can also be in 'Utility Classes' as there is already a sort of presentation of the styleguide of the template. The examples of [Image Alignment](https://mmistakes.github.io/minimal-mistakes/docs/utility-classes/#image-alignment) there have the same issue, if a 'baseUrl' is set. A good place for a notice block or separate paragraph, maybe.

**Comment by aschrijver** [comment]
not stale
