### ISSUE TITLE
Weird "jittery" scrolling behaviour on MacOS Firefox

### ISSUE THREAD

**Issue by limjh16** [mmistakes/minimal-mistakes#2519]
## Environment
- Minimal Mistakes version: 4.19.2
- Ruby gem or remote theme version: gem version 3.0.3
- Jekyll version: 4
- Git repository URL: https://github.com/mmistakes/minimal-mistakes/tree/master/docs
- GitHub Pages hosted (if yes provide URL to site): https://mmistakes.github.io/minimal-mistakes/
- Operating system: MacOS
## Expected behavior
Expected the scroll to be smooth or at least not weird
## Steps to reproduce the behavior
This only happens on Firefox, it doesn't seem to be an issue on Chrome. This happens throughout the website except for the [homepage](https://mmistakes.github.io/minimal-mistakes/). This also only happens when I use the mouse wheel, it doesn't appear with a trackpad. In the screen capture below, you can see what I mean when compared to another website (I scrolled using the mouse wheel for both sites)

![screen](https://user-images.githubusercontent.com/15180396/81286439-a5888000-9093-11ea-8e34-db29db9b935a.gif)
## Other
I was going to link my own website together with jekyll trace logs, but seems like the jekyll logs gives nothing and this happens on the official website as well so I just linked that instead.

**Comment by mmistakes** [comment]
Hmmm, not sure. Whatever the issue is it's not Jekyll related. It's 100% either JavaScript or CSS.
Something tells me this could be hard to diagnose...

**Comment by mmistakes** [comment]
If I had to guess it's due to the sticky sidebars. The home page doesn't have them and maybe there are performance implications related to it... or some sort of Firefox bug when dealing with them.

**Comment by limjh16** [comment]
I don't think its performance related though, it's completely smooth with my trackpad and the performance inspector in Firefox doesn't show any frame drops
Any way which I can help you debug this? I'm not sure where to start...

**Comment by mmistakes** [comment]
The fact that it only does it with FF for you tells me it's something with that browser. I just tested on my fairly old iMac (late 2013), with latest FF and it scrolls perfectly fine with me using my magic mouse.

Smells like something to do with your mouse device and its scroll wheel and or some sort of FF quirk related to that combo.

Sorry I have no other insight here as I can't reproduce it.

**Comment by limjh16** [comment]
<img width="221" alt="Screenshot 2020-05-10 at 1 56 22 PM" src="https://user-images.githubusercontent.com/15180396/81491928-08f9f400-92c6-11ea-95ee-9c023e4e8db5.png">

Apparently I had smooth scrolling enabled, and that caused the issue. When I disabled it scrolling on the webpage went back to normal.. woops!
