### ISSUE TITLE
Use of Modernizr for browser feature detection

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#252]
Just for fun, I used Microsoft's new tool at:
https://dev.windows.com/en-us/microsoft-edge/tools/staticscan/?url=http%3A%2F%2Fmmistakes.github.io%2Fminimal-mistakes%2F

In the Browser Detection section, it says 
"We've found that this webpage may be using browser detection techniques to determine how the webpage should render across many different versions of browsers."
and recommends using http://modernizr.com/
for feature-based detection (instead of version-based like "IE8").

**Comment by mmistakes** [comment]
I've found Modernizr is overkill for what I'm doing with the theme. In the upcoming release I've dropped it to shrink the JavaScript footprint. I was only really using it for CSS fallbacks which really isn't a progressive way of handling things.

I'm also cleaning up the theme's JavaScript overall so it's still accessible when disabled.

Doing more with less is really what I'm trying to achieve with the theme. I want to avoid jamming in everything or over developing the theme in the hopes of making it more approachable and easy to extend into whatever you want.
