### ISSUE TITLE
The og_image URL does not include the base URL

### ISSUE THREAD

**Issue by aschrijver** [mmistakes/minimal-mistakes#2523]
## Environment

- Minimal Mistakes version: v4.13.0
- Ruby gem or remote theme version:
- Jekyll version: v4.0.0
- Git repository URL: (not yet public)
- GitHub Pages hosted (if yes provide URL to site): no (codeberg.org)
- Operating system: Ubuntu 18.04

## Expected behavior

The `og_image` should take `site.baseurl` into account.

## Steps to reproduce the behavior

In my page (splash layout) frontmatter I set an `og_image` like so:

```markdown
header:
  overlay_image: /assets/images/my-landingpage-hero.png
  og_image: /assets/images/my-page-ogimage.png
```
 In `_config.yml` the site has a `site.baseurl` of _"mybaseurl"_:

```markdown
baseurl                  : "/mybaseurl" # the subpath of your site, e.g. "/blog"
```

The hero image URL is constructed correctly in `page__hero.html` include, but the opengraph image is not. It is set to an absolute url in `seo.html` include which does not take the base URL into account.

**Comment by iBug** [comment]
Couldn't reproduce locally on Minimal Mistakes 4.13.0 using the docs site. Would you mind providing a demo where this can be reliably reproduced?

**Comment by iBug** [comment]
The code doesn't look erroneous, either:

<https://github.com/mmistakes/minimal-mistakes/blob/4.13.0/_includes/seo.html#L31-L47>
<https://github.com/mmistakes/minimal-mistakes/blob/4.19.2/_includes/seo.html#L35-L42>

**Comment by aschrijver** [comment]
Ah, I see that the problem is on a different level. First of all the Link preview generator of Discourse forum, where I pasted the site link, probably uses a cache and used an earlier URL that had no baseurl prefix.

The generated HTML in `_site` is indeed correctly including `site.baseurl`. However because I until now didn't have the `url` set in config (because I still manually copy/paste `_site` contents to multiple locations) the absolute URL started with `https://localhost:4000/`.

Sorry to have bothered you with this @iBug but thanks a lot for your responses!
