### ISSUE TITLE
Hide titles from Table of Contents?

### ISSUE THREAD

**Issue by frroool** [mmistakes/minimal-mistakes#2528]
Hi!
Big thanks for your work with this theme!

I have created a webpage that is hosted at Github Pages and today I added staticman via this guide: https://travisdowns.github.io/blog/2020/02/05/now-with-comments.html

I use (and will use) `toc: true` a lot for auto generated Table of Contents since it is a really nice feature but since I added comments the auto generated ToC finds a title in the comment section which makes it look kind of weird :) 

![image](https://user-images.githubusercontent.com/64637165/81501721-1a4cfb80-92da-11ea-9998-c7440f513f6e.png)

I think that the title it finds is the `<h2>` in the file `comment_form.html`:

```
...
<fieldset>
  <div class="textfield">
    <label for="comment-form-message"><h2>Add Comment<small><a rel="nofollow" id="cancel-comment-reply-link" href="{{ page.url | absolute_url }}#respond" style="display:none;">(cancel reply)</a></small></h2>
      <textarea class="textfield__input" name="fields[message]" type="text" id="comment-form-message"></textarea>
    </label>
  </div>
  </fieldset>
...
```
Also the "Comments" title in the ToC only leads to "#top" of page. And I think that it is the `<h2>` in the file comments.html that it finds.

```
...
  <div class="comments__existing">
    <h2>Comments</h2>
...
```
Any ideas how to correct this? Or hide these two titles from the ToC?

Feel free to check out my [repo](https://github.com/frroool/frroool.github.io) where everything is hosted.

**Comment by mmistakes** [comment]
Try adding the class `no_toc` to your headings in the comment/comments includes. jekyll-toc should exclude them then.

Ref: https://github.com/allejo/jekyll-toc/issues/32#issuecomment-601972551
