### ISSUE TITLE
Flip ahead browsing via rel="next" and rel="prev"

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#253]
How do I add Next/Previous functionality to this theme?

Microsoft's new tool at:
https://dev.windows.com/en-us/microsoft-edge/tools/staticscan/?url=http%3A%2F%2Fmmistakes.github.io%2Fminimal-mistakes%2F

Also, in the Windows Features > Flip Ahead Browsing section, it says 
To enable pagination and Flip Ahead browsing, add the following to your page's element

```html
<link rel="next" href="/next"/>
<link rel="prev" href="/prev"/>
```

**Comment by mmistakes** [comment]
You can add it using Jekyll's `page.next` and `page.previous` variables. https://jekyllrb.com/docs/variables/

It only really works for posts. If you're trying to paginate Collections you'll have to roll your own custom Liquid to do it.
