### ISSUE TITLE
`google-universal` vs `google-gtag`: which on is the real setting for Google Universal?

### ISSUE THREAD

**Issue by esciara** [mmistakes/minimal-mistakes#2531]
## Summary

The Google doc page "[See if you use Universal Analytics](https://support.google.com/analytics/answer/4457764?hl=en&ref_topic=6010376)" suggests that the code needed to use Google Universal is actually the [code used with the `google-gtag` option](https://github.com/mmistakes/minimal-mistakes/blob/4.19.2/_includes/analytics-providers/google-gtag.html) and not the [code used with the `google-universal ` option](https://github.com/mmistakes/minimal-mistakes/blob/4.19.2/_includes/analytics-providers/google-universal.html). 

Could this be clarified?

## Motivation

Clarify 😁 .

## Drawbacks

Might need to handle backward compatibility if code options are changed.

**Comment by mmistakes** [comment]
The real setting is the one that matches whatever embed code Google gives you after setting up analytics. I haven't done this to any of my sites in years so not sure what the "default" is.

But if one has `googletagmanager.com` in the code use `google-gtag`. If it doesn't then you're probably using `google-universal`.
