### ISSUE TITLE
reduce the space under the menu

### ISSUE THREAD

**Issue by eborbath** [mmistakes/minimal-mistakes#254]
How do I reduce the space under the main menu, if I don't use any header image? I essentially would like to push up the left wrapper where the author bio is and the right one, where the content is.
Thanks for the template, it's a really nice design!

**Comment by mmistakes** [comment]
Remove the `2em` of top margin applied to `#main` and it'll move up closer to the main menu. It's in [`_sass/page.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/page.scss#L225)

![main-margin](https://cloud.githubusercontent.com/assets/1376749/14258700/9767f95e-fa71-11e5-8065-e0e2cdf9f5d3.jpg)

**Comment by eborbath** [comment]
Thanks a lot!
