### ISSUE TITLE
Always adds whitespace to seo_description

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2541]
## Environment

- Minimal Mistakes version: 4.19.2
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL: https://github.com/motionsplan/motionsplan-dk-jekyll
- GitHub Pages hosted (if yes provide URL to site): https://www.motionsplan.dk
- Operating system:

## Expected behavior

SEO description should not have an ending whitespace

## Steps to reproduce the behavior

seo_description consistently have a trailing whitespace.

**Comment by iBug** [comment]
@mmistakes This one might be better categorized as a bug report.
