### ISSUE TITLE
Incorrect posts representation

### ISSUE THREAD

**Issue by doncem** [mmistakes/minimal-mistakes#2543]
- Minimal Mistakes version: using remote flag `remote_theme: "mmistakes/minimal-mistakes"`
- Ruby gem or remote theme version: freshly install ruby v2.7
- Jekyll version: 3.8.5
- Git repository URL: not published. testing locally. target url i want to publish is github.com/donalora/donalora.github.io
- GitHub Pages hosted (if yes provide URL to site): www.donalora.com
- Operating system: linux, fedora 32

## Expected behavior

each post represents its' contents + sorts out in "list of posts" correctly

## Steps to reproduce the behavior

assume you have

```
2020-03-03-some-name.md
2020-04-04-some-name.md
```

notice name is same but date is different.

expected behaviour is each post link should open to `/2020/03/03/some-name` and `/2020/04/04/some-name` respectively (don't mind he prefixes). also general posts should be sorted by date not by title (i hacked by providing `permalink`).

## Other

![image](https://user-images.githubusercontent.com/1420191/82731114-81b47380-9cfc-11ea-81a5-eea75c838d5d.png)

sample ^. new e-shop is created mid March, updated photos is created just now - mid May. and both point to the earliest (which is March) post

**Comment by iBug** [comment]
What's your global `permalink` setting? (The one in `_config.yml`)

If you set it to just `/:title/`, Jekyll may be confused by that. I don't think it's this theme's fault.

**Comment by doncem** [comment]
i have this:

```
collections:
  posts:
    output: true
    permalink: /post/:year/:month/:day/:slug
```

**Comment by doncem** [comment]
oh no. sorry, got very premature here. i still had permalinks in my markdown. so after removing them it doesn't work with just `:title`. it's the same one (and earliest). no matter what title i would expect to be sorted by date and title if not possible by time within the post.

each post should make sure it opens what it represents. after the change you suggested it just got worse results: same url (without date) for both posts. previously at least i had diferent url (date part: 2020/04/04 and 2020/03/03)

**Comment by doncem** [comment]
As usual - classic mistake of copy/paste. Apologies for the alert.

Let me explain myself:

- I copied existing post and only replaced title and contents
- went to bed as it was pretty late
- forgot about all this and after a week attempted to come back to this

lesson to myself - attention to detail
