### ISSUE TITLE
Creating code tabs

### ISSUE THREAD

**Issue by tranlyvu** [mmistakes/minimal-mistakes#2547]
Hi, how do I create code tab like this in minimal

<img width="993" alt="Screenshot 2020-05-29 at 11 55 17 PM" src="https://user-images.githubusercontent.com/12371875/83279667-07a65200-a208-11ea-92e8-62e1632f6d14.png">

**Comment by iBug** [comment]
There's no built-in way. You'll have to add your own HTML template and relevant JS / CSS around.

**Comment by tranlyvu** [comment]
> There's no built-in way. You'll have to add your own HTML template and relevant JS / CSS around.

Do you know any example, I'm not very proficient with frontend and static generator

**Comment by iBug** [comment]
Then learn the skills required for your needs and DIY.

The repository is a Python project, designed to be a plugin for [Python Markdown][3]. It's unlikely to be able to be integrated into Jekyll, which itself is a Ruby program.

Just FYI, [Material for MkDocs][1] supports this feature [out of the box][2].

  [1]: https://squidfunk.github.io/mkdocs-material/
  [2]: https://facelessuser.github.io/pymdown-extensions/
  [3]: https://python-markdown.github.io/

**Comment by tranlyvu** [comment]
Found solution, closing!

**Comment by iBug** [comment]
Would you mind sharing your solution? That'd help others with the same issue.

**Comment by tranlyvu** [comment]
> Would you mind sharing your solution? That'd help others with the same issue.

I simply added css/js into assets
