### ISSUE TITLE
Enlarge overlay_image in splash page

### ISSUE THREAD

**Issue by tranlyvu** [mmistakes/minimal-mistakes#2548]
Hi,

My overlay_image is cut off on the top, how do we enlarge the overlay_image such that my uploaded image can be seen fully? thanks

https://distributedsystemsblog.com

<img width="868" alt="Screenshot 2020-05-30 at 1 15 16 PM" src="https://user-images.githubusercontent.com/12371875/83320268-65728280-a278-11ea-919e-63718db77362.png">

**Comment by mmistakes** [comment]
See #542
Closing as this is a duplicate issue.
