### ISSUE TITLE
Using existing .html page as .md page

### ISSUE THREAD

**Issue by Jimbo994** [mmistakes/minimal-mistakes#2554]
Hi Community,

After searching the internet a lot, I can't seem to find an answer to my question, so I decided to post it here.

I have an old website that I want to update and make easier to maintain by switching to a Jekyll based website. However, some of my pages are actually fine and I just want to copy them on my Jekyll website.

How do I do this? I have added my layout.html file to my _layouts directory. I then have made a markdown file in _pages in which I set layout: layout.

However, I keep on getting a 404 error. Any pointers on how to do this?

Many thanks in advance!

**Comment by mmistakes** [comment]
If you add front matter to a file Jekyll will process and copy it.
General Jekyll questions are better for the Jekyll Talk forum. Closing as this isn't theme specific.

```
---
---
```

**Comment by Jimbo994** [comment]
Thanks for the quick reply! I will look into the Jekkyl Talk forum.
