### ISSUE TITLE
If page has two galleries all images are included in popup

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2560]
## Environment

- Minimal Mistakes version: 4.19.3
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL: https://github.com/motionsplan/motionsplan-dk-jekyll
- GitHub Pages hosted (if yes provide URL to site): https://www.motionsplan.dk/
- Operating system:

## Steps to reproduce the behavior

I have added two galleries to this page: https://www.motionsplan.dk/test-muskelfibertyper/ which is here: https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/_posts/2020-06-09-test-muskelfibertyper.md

However, when I click on a picture in the second gallery, then it says 3/12 pictures. However in the second gallery there is only 10 pictures.

![Screenshot (30)](https://user-images.githubusercontent.com/148026/84245095-d6c9f500-ab04-11ea-8327-d700df6e965f.png)

**Comment by iBug** [comment]
This might actually be the intended behavior. I'm uncertain so have to let @mmistakes explain.

**Comment by mmistakes** [comment]
Unless you can init the [MFP script ](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/_main.js#L89-L122)for each specific gallery with some sort of unique identifier it's grouping in all images on the page.

Ref: https://dimsemenov.com/plugins/magnific-popup/

**Comment by timothymcmackin** [comment]
I'm seeing this, too. Any workarounds?

**Comment by timothymcmackin** [comment]
I've tried it like this, per instructions in https://dimsemenov.com/plugins/magnific-popup/documentation.html#multiple-galleries :

```
<!-- Magnific Popup core CSS file -->
<link rel="stylesheet" href="assets/css/magnific-popup.css">

<!-- jQuery 1.7.2+ or Zepto.js 1.0+ -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<!-- Magnific Popup core JS file -->
<script src="assets/js/jquery.magnific-popup.js"></script>

<script>
$('.gallery').each(function() { // the containers for all your galleries
    $(this).magnificPopup({
        delegate: 'a', // the selector for gallery item
        type: 'image',
        gallery: {
          enabled:true
        }
    });
});
</script>

<div class="gallery" id="gal1">
    <a href="assets/images/image.jpg"><img src="assets/images/image_th.jpg"></a>
    <a href="assets/images/image.jpg"><img src="assets/images/image_th.jpg"></a>
</div>
<hr/>
<div class="gallery" id="gal2">
    <a href="assets/images/image.jpg"><img src="assets/images/image_th.jpg"></a>
    <a href="assets/images/image.jpg"><img src="assets/images/image_th.jpg"></a>
</div>
```
