### ISSUE TITLE
How to display categories and tags in the sidebar ?

### ISSUE THREAD

**Issue by phicarre** [mmistakes/minimal-mistakes#2561]
The question is in the title.
- display categories and number, click to display all posts of the category
- display tags and number, click to display all posts with this tag

**Comment by mmistakes** [comment]
Not supported by theme. You’ll need to customize layouts to do this.

**Comment by phicarre** [comment]
The _includes/sidebar.html  layout ?
Do you have references to help me ?

rgds,

**Comment by mmistakes** [comment]
https://superdevresources.com/tag-cloud-jekyll/

**Comment by phicarre** [comment]
Thank you so much !
Excellent theme I discovered day after day.
