### ISSUE TITLE
<pre> formatted as normal code

### ISSUE THREAD

**Issue by josecastillolema** [mmistakes/minimal-mistakes#2565]
## Summary

Hi @all, I realized, as per https://mmistakes.github.io/minimal-mistakes/markup/markup-html-tags-and-formatting/#preformatted-tag, that preformatted tag code (pre) is displayed in a different way than normal ``` block codes.
Would it not be better to display it as standard block codes?

## Motivation

Github markdown displays code with the preformatted-tag as normal code blocks. An example:
<pre>
<b>$ cd /kubernetes
$ pwd</b>
/home/ubuntu/fiap/aso/kubernetes
<b>$ ls</b>
api-deployment.yaml  api-service.yaml  mysql-deployment.yaml  mysql-pv.yaml  mysql-service.yaml
</pre>
 I believe that it would be better to mimic github markdown behaviour as much at possible.

## Drawbacks

If the present output accomplished by the preformatted tag is desired, it would need another tag to implement it.

**Comment by mmistakes** [comment]
There are some challenges there. In that post it's using the `<pre>` element.
Syntax highlighted code from triple backticks or Jekyll's `{% highlight %}` tag use additional markup which allows for the enhanced styling... it's not just a single `<pre>` element... it's nested with several classes to magic the magic work.

![Screen Shot 2020-06-14 at 1 40 16 PM](https://user-images.githubusercontent.com/1376749/84600056-a48dff80-ae44-11ea-9498-04ba007c2bbc.png)
