### ISSUE TITLE
plugin not accepted on github

### ISSUE THREAD

**Issue by jphconstantin** [mmistakes/minimal-mistakes#2588]
Hello,
I added a plugin (which run correctly locally with minimal-mistakes) and github seems to not accept it. The author confirmed it. The plugin is jekyll-exif-data.
Does exist a work around ?

**Comment by iBug** [comment]
<https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins>

If you want to use unsupported plugins, you can instead build your site with a CI service like Travis CI. I have written an article years back which you can refer to.

<https://ibug.io/p/4>

**Comment by jphconstantin** [comment]
Don't close the subject: I must digest your article ...

**Comment by mmistakes** [comment]
Closing as this isn't a theme issue.

**Comment by jphconstantin** [comment]
But I would like to talk with iBug !

**Comment by iBug** [comment]
No need to talk to me. There are [plenty of resources](https://www.google.com/search?q=GitHub+Pages+Travis+CI) on the internet. Try a few guides and you'll work your way out of it.

**Comment by mmistakes** [comment]
This is what the [Jekyll Talk Forum](https://talk.jekyllrb.com/) is for. The MM issues are for bug reports related to this theme, not general "how to use Jekyll" requests.
