### ISSUE TITLE
Error while trying to build and serve Ramme locally

### ISSUE THREAD

**Issue by justinshaffner** [mmistakes/minimal-mistakes#259]
Any ideas? Many thanks in advance!

```
$ jekyll build
Configuration file: /Ramme-gh-pages/_config.yml
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- jekyll-mentions (LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/jekyll/plugin_manager.rb:28:in `block in require_gems'
	from /usr/lib/ruby/vendor_ruby/jekyll/plugin_manager.rb:26:in `each'
	from /usr/lib/ruby/vendor_ruby/jekyll/plugin_manager.rb:26:in `require_gems'
	from /usr/lib/ruby/vendor_ruby/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:71:in `setup'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:33:in `initialize'
	from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:28:in `new'
	from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:28:in `process'
	from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:17:in `block (2 levels) in init_with_program'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `call'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `block in execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `each'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/program.rb:42:in `go'
	from /usr/lib/ruby/vendor_ruby/mercenary.rb:19:in `program'
	from /usr/bin/jekyll:18:in `<main>'
```

```
$ jekyll serve
Configuration file: /Ramme-gh-pages/_config.yml
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- jekyll-mentions (LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/jekyll/plugin_manager.rb:28:in `block in require_gems'
	from /usr/lib/ruby/vendor_ruby/jekyll/plugin_manager.rb:26:in `each'
	from /usr/lib/ruby/vendor_ruby/jekyll/plugin_manager.rb:26:in `require_gems'
	from /usr/lib/ruby/vendor_ruby/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:71:in `setup'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:33:in `initialize'
	from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:28:in `new'
	from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:28:in `process'
	from /usr/lib/ruby/vendor_ruby/jekyll/commands/serve.rb:24:in `block (2 levels) in init_with_program'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `call'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `block in execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `each'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/program.rb:42:in `go'
	from /usr/lib/ruby/vendor_ruby/mercenary.rb:19:in `program'
	from /usr/bin/jekyll:18:in `<main>'

```

**Comment by mmistakes** [comment]
Use Bundler, it should solve the dependency issues you're having by incompatible gems versions loading.

1. Make sure you have the correct gems installed. Run `bundle install`... may have to do `bundle update` if prompted.
2. Run Jekyll, but with `bundle exec jekyll serve` and `bundle exec jekyll build`. Doing this will load the approved gem versions in `Gemfile.lock` and should fix your problems.

**Comment by justinshaffner** [comment]
Thank you. I've Run `bundle install` and `bundle update`. When I run `bundle exec jekyll serve` and `bundle exec jekyll build` I get a new error:

/var/lib/gems/2.1.0/gems/jekyll-3.0.3/bin/jekyll:13:in `<top (required)>': undefined method `require_from_bundler' for Jekyll::PluginManager:Class (NoMethodError)
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

Thanks again!

**Comment by mmistakes** [comment]
Have you made any updates to the theme? Installed plugins? Other gems to `Gemfile`? What happens if you remove `Gemfile` and `Gemfile.lock` and then run `jekyll serve`?

You definitely have some gem issues, which I don't think have anything to do with the theme.

**Comment by mmistakes** [comment]
What's under `gems:` in your `_config.yml`? I'm guessing `jekyll-mentions` perhaps since it's up above in one of the errors?

You'll most likely need to include those gems in the `Gemfile` so they're installed and called in with Bundler. Most, if not all Jekyll official plugins have instructions to add them to the `Gemfile` when installing.

**Comment by justinshaffner** [comment]
It seems that I  havd installed jekyll via packagemanager and also via gem. I uninstalled the packagemanager version with

`sudo apt-get remove --purge jekyll
`
and installed the gem again:

`sudo gem install jekyll jekyll-watch
`
And it works! Thank you!

**Comment by justinshaffner** [comment]
Well, almost. Here's the latest:

```
$ bundle exec jekyll serve
Configuration file: /home/justin/Documents/Ramme-gh-pages/_config.yml
            Source: /home/justin/Documents/Ramme-gh-pages
       Destination: /home/justin/Documents/Ramme-gh-pages/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 3.116 seconds.
jekyll 3.0.3 | Error:  uninitialized constant Jekyll::Watcher
```
Thanks again!

**Comment by mmistakes** [comment]
Only other thing I can think of is to replace `gem "jekyll"` with `gem "github-pages"` in `Gemfile`, then do `bundle install`, `bundle exec jekyll serve`.

The `github-pages` gem ships with a bunch of other dependencies that vanilla Jekyll doesn't include. (eg. Jekyll plugins like mentions, sitemap, jemoji, etc).

**Comment by justinshaffner** [comment]
Fixed. Thanks again for your help!
