### ISSUE TITLE
Math markdown doesn't render on the final post.

### ISSUE THREAD

**Issue by MAVERICK6912** [mmistakes/minimal-mistakes#2605]
Hi guys,

I wrote a sample post to test formatting of math equations in the markdown, but sadly the math markdown doesn't get rendered.
Here's my .md [file](https://github.com/MAVERICK6912/maverick6912.github.io/blob/master/_posts/2020-07-13-test_post.md)

Is there anything that I'm missing that is required for rendering math markdown?

Thanks.

**Comment by iBug** [comment]
Math is in no way "supported by default". You need to add the relevant math library (MathJax or KaTeX) somewhere, for example:

<https://github.com/iBug/iBug-source/blob/bcdbfadb2fb5adf05baf6e3fc10f62264f8ac55b/_includes/head/custom.html#L13-L24>

**Comment by mmistakes** [comment]
See https://github.com/mmistakes/minimal-mistakes/issues/735
