### ISSUE TITLE
`jekyll-data` missing since 4.16.6?

### ISSUE THREAD

**Issue by iBug** [mmistakes/minimal-mistakes#2621]
I was trying to create a localized website with this theme when I suddenly discovered that l10n was not working at all unless I include `ui-text.yml` in my repository. This was not what I expected as I've always had the impression that data files bundled in this theme are automatically loaded unless overridden.

It's also what the current documentation says:

> ### [Quick-Start Guide > Migrating to Gem Version](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#migrating-to-gem-version)
>
> From `v4.5.0` onwards, you don't have to maintain a copy of the default data files viz. `_data/ui-text.yml` and `_data/navigation.yml` either.

Tracing through Git history shows removal of `jekyll-data` along with `jemoji` in 2388cbe020e7edab658730f998be11e04af711d3. I can confirm that adding `jekyll-data` into plugins list restores the functionality.

Looking at `jekyll-data` itself, ashmaroli/jekyll-data#33 might be a reason for the removal as a dependency at the time. The plugin isn't included in stock GitHub Pages, either (see [GitHub Pages dependency versions](https://pages.github.com/versions/)). Generating a `Gemfile.lock` with Bundler from theme version 4.19.3 plus latest `github-pages` (206 ATM) shows no trace of `jekyll-data`.

I wonder what we should do next - add it back or update the documentation to reflect <s>recent</s> changes? (not quite recent at all...)

**Comment by mmistakes** [comment]
You’re correct that’s why I removed it as a dependency. My thinking is if you need the functionality it provides you can just install yourself.

Documentation probably should be updated to reflect that it was removed...

**Comment by iBug** [comment]
I can take this task of updating the documentation tomorrow in a new PR. Let me confirm a few points quickly:

1. Users building their websites on vanilla GitHub Pages have to include `ui-text.yml` in their repositories.

   In other words, the `jekyll-data` plugin approach now requires building locally or with a CI service.

2. Users can opt-in to include either `ui-text.yml` file or `jekyll-data` plugin if they want the l10n feature.

Am I missing anything?

**Comment by mmistakes** [comment]
1. Correct
2. By default users get English strings. If they want to utilize any of the language strings in the data file they need to copy it into their data folder (if using GH pages) or install the jekyll-data plugin to have it use the bundled data file.

User also needs to set the appropriate locale. I believe that’s mentioned in the docs already, but it’s a common omission I see being made enough that it might make sense to reference it again.
