### ISSUE TITLE
Quickstart docs reference Continuous Integration services, dead link

### ISSUE THREAD

**Issue by jasonhemann** [mmistakes/minimal-mistakes#2635]
This is simply a URL change or documentation fix:

Continuous Integration (CI) services links to `https://jekyllrb.com/docs/continuous-integration/` which looks like it 404's.

**Comment by iBug** [comment]
You can create a PR for this fix by yourself. Just change the link in [`docs/_docs/0101-quick-start-guide.md`](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_docs/01-quick-start-guide.md) to the one you find appropriate.

**Comment by jasonhemann** [comment]
Thank you. If I knew where it was supposed to point, I would have done so. Instead, I merely note the issue.

**Comment by mmistakes** [comment]
I would just remove the dead link then. Not sure what it should be pointed to either.

**Comment by iBug** [comment]
Probably should be redirected here: <https://jekyllrb.com/docs/deployment/automated/#continuous-integration-service>
