### ISSUE TITLE
Table formatting 

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#266]
Sorry this is a more generic issue that just this theme.
But I've seen tables look better with other themes.

Tables right now are being displayed without dividers and text is vertically aligned.
Background colors are not alternated every row, as in:
https://guides.github.com/features/mastering-markdown/

How can I get dividers, text each row aligned to top of row, etc.?

**Comment by mmistakes** [comment]
You can do all of that by changing the CSS.

**Comment by wilsonmar** [comment]
What I'm writing about here is that I copied the markdown for the table from
minimal-mistakes/blob/gh-pages/_posts/2011-03-10-sample-post.md
and it doesn't display the same way as the demo site.
I shouldn't need to change the CSS to get the same result, right?

**Comment by mmistakes** [comment]
Depends. If your on and older version of theme then CSS is different. I
just released a complete rebuild of the entire theme the other day.
