### ISSUE TITLE
Missing word or link in documentation. Perhaps documentation generation bug.

### ISSUE THREAD

**Issue by jasonhemann** [mmistakes/minimal-mistakes#2678]
> To start, add a new key to _data/navigation.yml. This will be referenced later in via YAML Front Matter so keep it short and memorable.

I can't parse this as written. It looks like there was supposed to be a hyperlink or page name between `in` and `via`.

I would expect either add a link or page name. If that's not the correct way to fix this, then some other larger rewording or textual refactoring.

**Comment by mmistakes** [comment]
I believe `in` is a typo. Should just read "This will be referenced later via YAML Front Matter so keep it short and memorable."
