### ISSUE TITLE
Skype call link among author-bio links

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#268]
Skype is quite popular.
For many years a web page can access Skype installed on the machine by using the skype protocol much like http. I used it by adding this code to my _includes/_author-bio.html:

`  {% if author.skype %}<a href="skype:{{ author.skype " }}?call" }}" class="author-social" target="_blank"><i class="fa fa-fw fa-skype"></i> Skype call</a>{% endif %}
`

The code references a new line in the _config.yml I added, such as:

`  skype: wilsonmar4
`

Let me know if you want me to send up a pull request.

**Comment by mmistakes** [comment]
Sure feel free to submit a PR. One thing I would add would be a string for "Skype call" in `_data/ui-text.yml` so English isn't hard coded and can be localized in the author profile from a data file. See what I did with `website_label` as an example: https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/author-profile.html#L29

**Comment by mmistakes** [comment]
Closing to keep the theme lean and avoid configuration bloat. The defaults cover the most popular networks, anything else I envisioned being customized by the user.
