### ISSUE TITLE
Feature rows disappears after updating from 4.19.3 og 4.20.1

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2685]
## Environment

- Minimal Mistakes version: 4.20.1
- Ruby gem or remote theme version:
- Jekyll version: jekyll 4.0.0
- Git repository URL: https://github.com/motionsplan/motionsplan-dk-jekyll/tree/mm4201
- GitHub Pages hosted (if yes provide URL to site): https://www.motionsplan.dk
- Operating system:

## Steps to reproduce the behavior

Doing this update: https://github.com/motionsplan/motionsplan-dk-jekyll/commit/0dd44b94514d41e9ec6bb029f62c2dc74476917f

On this branch https://github.com/motionsplan/motionsplan-dk-jekyll/tree/mm4201 the feature rows from the front page (and probably other places) disappears:

![Screenshot (35)](https://user-images.githubusercontent.com/148026/92391651-5a53ac00-f11d-11ea-8d54-c98d41738e08.png)

On 4.19.3 it looks like this:

![Screenshot (36)](https://user-images.githubusercontent.com/148026/92391837-9edf4780-f11d-11ea-8922-6e88c706b8cb.png)

**Comment by iBug** [comment]
Feature rows aren't touched between 4.19.3 and 4.20.1, so I'm not immediately sure what's gone wrong.

Besides, it'd be helpful if you could create a "Minimal, Complete, Verifiable example". Your 2 GB repository is burdening to clone...

**Comment by mmistakes** [comment]
There were some bad `assign` tags in a pull request that messed up the `page` variables. I fixed it in https://github.com/mmistakes/minimal-mistakes/pull/2641

Update to the latest commit on `master`.

```
remote_theme: "mmistakes/minimal-mistakes@8bec01b76dbb94d54ffd36fbb01841892ce37190"
```
