### ISSUE TITLE
Search Pages Lunr

### ISSUE THREAD

**Issue by ceesuade** [mmistakes/minimal-mistakes#2707]
Is there something special that needs to be done to include pages in search results using Lunr ?  Currently when searching it is only pulling back posts but nothing in the _pages directory.  Have the need for search to include both posts and pages.  Have looked into algolia and google but would like to stick with lunr as it fits needs just doesn't return pages which .

Doesn't appears the pages are getting index.  Looking here https://jekyllcodex.org/without-plugin/search-lunr/ it appears possible just wondering if I am over looking something hoping this theme is excluding pages and if that is the case maybe point me in the right direction to make this work :) 

GREAT THEME and great work you have put into this really is nice and easy to understand!

**Comment by mmistakes** [comment]
https://github.com/mmistakes/minimal-mistakes/issues/1663#issuecomment-387790192

**Comment by ceesuade** [comment]
Thanks @mmistakes I did see this before posing the questions but this commit https://github.com/mmistakes/minimal-mistakes/issues/1663#issuecomment-458716716 had me wondering if not a available how was this done 🤔 Looked at the .js file he mentioned and see it in the repo but not sure how to adjust to index pages as well this was two years ago thought something might have changed ... maybe :) GREAT work again sir
