### ISSUE TITLE
When a post has an empty table of content, it shows Uncaught TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by quanengineering** [mmistakes/minimal-mistakes#2717]
## Environment

- Minimal Mistakes version: 4.20.2 (latest)
- Ruby gem version: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c)
- Jekyll version: 4.1.1
- Operating system: Ubuntu 20.04

## Expected behavior

The console window of Chrome browser will show this message:

```
Uncaught TypeError: Cannot read property 'content' of undefined
    at c (main.min.js:9)
    at f (main.min.js:9)
    at d.detect (main.min.js:9)
```
![image](https://user-images.githubusercontent.com/8580008/97412504-3b5ee280-1934-11eb-95c0-5aa2b4675fd2.png)
 
## Steps to reproduce the behavior
- Delete all headings of a post, so that the post will have an empty table of content.
 - Enable the sticky table of content of that post, by using these options:
```
      toc: true
      toc_sticky: true
```

**Comment by iBug** [comment]
Doesn't seem to be harmful. Probably coming from [`gumshoe.js`](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/plugins/gumshoe.js) which we can safely ignore for now.

**Comment by iBug** [comment]
Can this still be reproduced with the latest version (4.22)?

**Comment by quanengineering** [comment]
I've just checked again. This error disappear with the latest version (4.22). So it's time to close this issue.
