### ISSUE TITLE
Opt-in to Hacktoberfest for this repo?

### ISSUE THREAD

**Issue by iBug** [mmistakes/minimal-mistakes#2719]
I only saw [this](https://hacktoberfest.digitalocean.com/hacktoberfest-update) just now (emphasis mine):

> We’re making Hacktoberfest **opt-in only for projects** – which maintainers can do simply by adding the `hacktoberfest` topic to a repository.

Can you add the topic to this repository so whoever contributed in October gets a chance for a successful participation in this year's Hacktoberfest?

**Comment by mmistakes** [comment]
Sure no problem.

**Comment by mmistakes** [comment]
I added the `hacktoberfest-accepted` label. Didn't do the global label as I had to limit contributions at the start of the month as I was getting garbage PRs just to cash in on the free tshirt.
