### ISSUE TITLE
Table of contents (TOC) not generating anchor hyperlinks for <h2> tags, only ##-style headings

### ISSUE THREAD

**Issue by abevoelker** [mmistakes/minimal-mistakes#2751]
## Environment

- Minimal Mistakes version: 4.21.0
- Ruby gem or remote theme version: Ruby gem minimal-mistakes-jekyll version 4.21.0
- Jekyll version: 3.8.7
- Git repository URL: https://github.com/mmistakes/minimal-mistakes
- GitHub Pages hosted (if yes provide URL to site): https://mmistakes.github.io/minimal-mistakes/docs/helpers
- Operating system: Ubuntu 18.04

## Expected behavior

I expect setting `toc: true` in the page front matter and then including HTML header markup in my .md files like

```markdown
<h2>Foo</h2>
```

to generate working anchor tags in the table of content (toc) sidebar, the same way it works for using markdown shorthand like

```markdown
## Foo
```

## Steps to reproduce the behavior

If you visit https://mmistakes.github.io/minimal-mistakes/docs/helpers/ right now you can see this happening in the toc there; the Placeholder 1,  Placeholder 2, Placeholder 3 text in the toc are not hyperlinks but just plain text. Here is a screenshot:

![Screenshot from 2020-12-09 23-27-36](https://user-images.githubusercontent.com/153459/101726052-67af6800-3a77-11eb-9b06-03f80e858a11.png)

I can reproduce the behavior on my own Jekyll site by writing headers like `<h2>Placeholder 1</h2>`. Writing `## Placeholder 1` instead generates the anchor link successfully.

## Other

N/A

**Comment by iBug** [comment]
I would rather say this is the correct behavior. The ToC template expects headings to have an HTML `id` attribute, which Jekyll's default Markdown renderer, Kramdown, will automatically generate [with `auto_ids` enabled][1].

If you want manually-written HTML headings to have ToC entries, create your `id` as well:

```html
<h2 id="placeholder-1">Placeholder 1</h2>
```

  [1]: https://github.com/mmistakes/minimal-mistakes/blob/e61476d0a9a004a0b7f2a7722481fa5589be9044/_config.yml#L194
