### ISSUE TITLE
ToC broken when using jekyll-commonmark-ghpages

### ISSUE THREAD

**Issue by wdhongtw** [mmistakes/minimal-mistakes#2763]
## Environment

- Minimal Mistakes version: 4.21.0
- Ruby gem or remote theme version: 3.1.2
- Jekyll version: 4.2.0
- Git repository URL: https://github.com/wdhongtw/sample-site
- GitHub Pages hosted (if yes provide URL to site):
- Operating system: Ubuntu server 20.04

## Expected behavior

The ToC should be rendered like

![image](https://user-images.githubusercontent.com/16065489/103116356-2e930c80-46a1-11eb-9332-71a1a8c8e2ed.png)

But when using `jekyll-commonmark-ghpages`, the ToC is rendered like

![image](https://user-images.githubusercontent.com/16065489/103116404-5d10e780-46a1-11eb-9959-11d122ca59ae.png)

## Steps to reproduce the behavior

- Clone the sample jekyll site from the given URL
- In the project folder
  - `bundle install`
  - `bundle exec jekyll server`

**Comment by iBug** [comment]
`jekyll-toc` bundled in the current version of the theme relies on Kramdown (Jekyll's default MD renderer). This will be fixed in the next release (#2752).
