### ISSUE TITLE
How to redirect a page using GH pages?

### ISSUE THREAD

**Issue by blogi-kriptovalyut** [mmistakes/minimal-mistakes#2777]
Hello,
How to redirect a category and page using GH pages?

If I just replace url in jekyll, then it changes, but there will be no redirect from the old page. Is it possible to redirect using  GH pages?
Examle: https://blogi-kriptovalyut.github.io/exchanges/okex/ -->> 301 redirect https://blogi-kriptovalyut.github.io//markets/okex/

**Comment by iBug** [comment]
Check out [jekyll-redirect-from][1] which is bundled with GH Pages.

Next time we'll appreciate it if you ask general Jekyll support questions on [Jekyll Talk](https://talk.jekyllrb.com/). Issues are for bug tracking only.

  [1]: https://github.com/jekyll/jekyll-redirect-from

**Comment by blogi-kriptovalyut** [comment]
Thanks
