### ISSUE TITLE
author_profile not working in posts

### ISSUE THREAD

**Issue by Flodu31** [mmistakes/minimal-mistakes#2779]
## Environment

- Minimal Mistakes version: last
- Ruby gem or remote theme version: mmistakes/minimal-mistakes
- Jekyll version: N/A
- Git repository URL: https://github.com/Flodu31/Flodu31.github.io
- GitHub Pages hosted (if yes provide URL to site): https://cloudyjourney.fr/
- Operating system: N/A

## Expected behavior

In my blog, I can't see the profile on the left, for posts.

## Steps to reproduce the behavior

Here is an exemple: https://cloudyjourney.fr/2021/01/07/migration-blog-github-pages/

## Other

It works for pages, in my index, but not for posts

Thanks for your help.
Florent

**Comment by ElectricRCAircraftGuy** [comment]
@Flodu31 , why did you close this? What was the end result or solution? Please always post what you did to fix something if you got something to work. It may help others later on.

**Comment by Flodu31** [comment]
Hi,
I added an author.yml file with details, in the _data folder.
