### ISSUE TITLE
Year Archive Layout

### ISSUE THREAD

**Issue by thewismit** [mmistakes/minimal-mistakes#278]
Hi Michael,

I apologize in advance if this is the wrong place to ask you a question.  This may not even be an issue with your code. I'm very new so please excuse me.

I've forked your theme and am trying to configure an archive page based on your year-archive.html code. However, the year shows up as

<h2 id="2016" class="archive__subtitle">2016</h2>
(when previewing this, it shows up properly. I'm guessing I'm missing an include?

The page I'm working on is listed [here](https://github.com/wismit/wismit.github.io/blob/master/_pages/all-the-things.md) 

Any help would be appreciated. Thank you!

**Comment by mmistakes** [comment]
What's going on is Markdown is parsing the indents in the code and turning them into code blocks. You have two ways of getting around this.

**1.** If you want to stick with a `.md` file then remove the indents so you have something like this following. It's not as easy to read but it gets the job done.

```html
<!-- all-the-things.md -->
There's a [hot debate as to whether to use the word "Archive" or "Archives"](https://www.robincamille.com/2011-09-09-archive-vs-archives-internet-vs-internet/) - yeah, I'm not touching that! So instead, here we have all the things!

{% include base_path %}
{% capture written_year %}'None'{% endcapture %}
{% for post in site.posts %}
{% capture year %}{{ post.date | date: '%Y' }}{% endcapture %}
{% if year != written_year %}
<h2 id="{{ year | slugify }}" class="archive__subtitle">{{ year }}</h2>
{% capture written_year %}{{ year }}{% endcapture %}
{% endif %}
{% include archive-single.html %}
{% endfor %}
```

**2.** Rename your file to `.html`. If you have any Markdown you want to convert either rewrite it in HTML or use some Liquid capture tags to get the string, the spit it back out with the `markdownify` filter.

```html
<!-- all-the-things.html -->
{% capture text-string-1 %}There's a [hot debate as to whether to use the word "Archive" or "Archives"](https://www.robincamille.com/2011-09-09-archive-vs-archives-internet-vs-internet/) - yeah, I'm not touching that! So instead, here we have all the things!{% endcapture %}

{{ text-string-1 | markdownify }}

{% include base_path %}
{% capture written_year %}'None'{% endcapture %}
{% for post in site.posts %}
  {% capture year %}{{ post.date | date: '%Y' }}{% endcapture %}
  {% if year != written_year %}
    <h2 id="{{ year | slugify }}" class="archive__subtitle">{{ year }}</h2>
    {% capture written_year %}{{ year }}{% endcapture %}
  {% endif %}
  {% include archive-single.html %}
{% endfor %}
```

**Comment by wismit** [comment]
That makes sense now that you reminded me about the indents. I should've 
figured that out! Thanks much for the help.

Michael Rose wrote:
> What's going on is Markdown is parsing the indents in the code and
> turning them into code blocks. You have two ways of getting around this.
>
> *1.* If you want to stick with a |.md| file then remove the indents so
> you have something like this following. It's not as easy to read but it
> gets the job done.
>
> 
> There's a [hot debate as to whether to use the word "Archive" or "Archives"](https://www.robincamille.com/2011-09-09-archive-vs-archives-internet-vs-internet/) - yeah, I'm not touching that! So instead, here we have all the things!
>
> {% include base_path %}
> {% capture written_year %}'None'{% endcapture %}
> {% for post in site.posts %}
> {% capture year %}{{ post.date | date: '%Y' }}{% endcapture %}
> {% if year != written_year %}
> <h2  id="{{ year | slugify }}"  class="archive__subtitle">{{ year }}</h2>
> {% capture written_year %}{{ year }}{% endcapture %}
> {% endif %}
> {% include archive-single.html %}
> {% endfor %}
>
> *2.* Rename your file to |.html|. If you have any Markdown you want to
> convert either rewrite it in HTML or use some Liquid capture tags to get
> the string, the spit it back out with the |markdownify| filter.
>
> 
> {% capture text-string-1 %}There's a [hot debate as to whether to use the word "Archive" or "Archives"](https://www.robincamille.com/2011-09-09-archive-vs-archives-internet-vs-internet/) - yeah, I'm not touching that! So instead, here we have all the things!{% endcapture %}
>
> {{ text-string-1 | markdownify }}
>
> {% include base_path %}
> {% capture written_year %}'None'{% endcapture %}
> {% for post in site.posts %}
>    {% capture year %}{{ post.date | date: '%Y' }}{% endcapture %}
>    {% if year != written_year %}
>      <h2  id="{{ year | slugify }}"  class="archive__subtitle">{{ year }}</h2>
>      {% capture written_year %}{{ year }}{% endcapture %}
>    {% endif %}
>    {% include archive-single.html %}
> {% endfor %}
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mmistakes/minimal-mistakes/issues/278#issuecomment-212054346>
>



--
Will Smith
will@wismit.com | wismit.com
