### ISSUE TITLE
TOC is not properly indented

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2793]
## Environment

- Minimal Mistakes version: 4.21.0
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL: 
- GitHub Pages hosted (if yes provide URL to site): https://mmistakes.github.io/minimal-mistakes/docs/helpers/
- Operating system:

## Expected behavior

TOC should be properly indented. It happened in one of the last couple of updates.

## Steps to reproduce the behavior

Just see the TOC in the docs - https://mmistakes.github.io/minimal-mistakes/docs/helpers/

**Comment by iBug** [comment]
This has already been fixed in #2752. The demo site isn't updated yet.
