### ISSUE TITLE
Make the docs site always build with the latest (master) version of theme?

### ISSUE THREAD

**Issue by iBug** [mmistakes/minimal-mistakes#2794]
If we build the docs site (`docs/`) with the latest version of the theme, i.e.:

```yaml
remote_theme: 'mmistakes/minimal-mistakes@master'
```

we can always preview the latest features that will be shipped in the next release version. This will also help eliminate some confusion like that in #2793, where the reported issue is already fixed but not showcased.

I'm not aware of your reason for sticking the theme version in the docs site to the latest release instead of the `master` version.

**Comment by mmistakes** [comment]
I've pinned it to eliminate confusion. The docs suggest pinning it and there often issues raised because the demo site had features the latest release didn't.

It also reflects the latest theme gem too. I'd rather it reflect the latest release instead of something unreleased if that makes sense.
