### ISSUE TITLE
jekyll 4.2.0 stopped overriding site.url, breaks lunr search result

### ISSUE THREAD

**Issue by iveney** [mmistakes/minimal-mistakes#2801]
Originally posted [here](https://github.com/mmistakes/minimal-mistakes/issues/2225#issuecomment-769642777). After a bit of search, I think this is probably because Jekyll [*stopped overriding site.url*](https://jekyllrb.com/news/#3-siteurl-is-set-by-the-development-server)

> Additionally, we have stopped overriding the site.url to http://localhost:4000 in absolute URLs while developing via jekyll serve.

## Environment

- Minimal Mistakes version: 4.21.0
- Ruby gem or remote theme version: 
- Jekyll version: 4.2.0
- Git repository URL: https://github.com/iveney/ivansiu.com/tree/upgrade-jekyll
- GitHub Pages hosted (if yes provide URL to site): www.ivanxiao.com
- Operating system: Mac OS Catalina

## Expected behavior

In local deve (jekyll serve), clicking the search icon and type something, returned result should have proper URL as "http://localhost:4000/path". But now it is using site.url.

## Steps to reproduce the behavior

- Clone my gh page repo  [here](https://github.com/iveney/ivansiu.com/tree/upgrade-jekyll)
- run `bundle exec jekyll serve`, open localhost:4000, click search and type something. Observe link is incorrect:

![Ivan_Xiao](https://user-images.githubusercontent.com/51033/106247679-b8645700-61c4-11eb-9621-ea2ca929854e.jpg)

**Comment by mmistakes** [comment]
Closing as this isn't a theme issue, Jekyll 4.2.0 changed the behavior of when it overrides `site.url`.

https://jekyllrb.com/news/2020/12/14/jekyll-4-2-0-released/

**Comment by iveney** [comment]
@mmistakes What's the reason to use `absolute_url` instead of `relative_url` in [lunr-store.js](https://github.com/mmistakes/minimal-mistakes/blob/faf86f59e9f897c5ed8928b6cf01ba0028402458/assets/js/lunr/lunr-store.js#L45-L46) though?

As in other places such as `archive-single.html` I am seeing the`<a/>` is [being added with](https://github.com/mmistakes/minimal-mistakes/blob/faf86f59e9f897c5ed8928b6cf01ba0028402458/_includes/archive-single.html#L22) `{{ post.url | relative_url }}` instead of `absolute_url`.
