### ISSUE TITLE
InstantSearch.js slows down the site

### ISSUE THREAD

**Issue by blogi-kriptovalyut** [mmistakes/minimal-mistakes#2802]
Hello.

InstantSearch.js loads 20 (!) images for quick search. But it slows down lighthouse and google core web vitals.
Can this feature be removed or configured so that images are requested only at the moment of clicking on the search?

Or maybe there is an opportunity to tell him to load not 20, but 5 images?

source: https://github.com/mmistakes/minimal-mistakes/blob/d6444412c63aea5e47241ef536509fb1bfef4830/_includes/search/algolia-search-scripts.html

my blog page: [https://bitkoinblog.ru/novye-kriptovalyuty/dogecoin/](https://bitkoinblog.ru/novye-kriptovalyuty/dogecoin/)

<a href="https://ibb.co/r5q3Lcg"><img src="https://i.ibb.co/TPJ1nbZ/img-2021-01-29-19-50-37.png" alt="img-2021-01-29-19-50-37" border="0"></a>

**Comment by mmistakes** [comment]
Probably a better question for Algolia. Instantsearch is their library and is needed to make search work.

https://www.algolia.com/products/instantsearch/

**Comment by blogi-kriptovalyut** [comment]
I think Algolia adapts to jekyll settings and the number of posts per page. Because I have just 20 posts on the front page and Algolia is loading 20 images from the last 20 posts ...

**Comment by Ethermine-pool** [comment]
yes, it would make sense to revise the search logic so as not to slow down the site.
I found a parameter in algolia -
it's called `hitsPerPage: 20`
It looks like by default it loads the last 20 posts (and images, respectively).
You need to find where to write it in the JS code.
Google gave the following example:
```var search = instantsearch ({
     appId: 'my-app-id',
     apiKey: 'my-search-only-api-key',
     indexName: 'my-indices',
     urlSync: false,
     searchParameters: {
         hitsPerPage: 10
     }
});
```

**Comment by blogi-kriptovalyut** [comment]
I am new to js, it would be cool if I could configure this in _config.yml
```
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : algolia # lunr (default), algolia
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    :  # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : true # true (default), false
  files_to_exclude:
    - _posts/news/2019/*.md
    - _posts/news/korona/*.md
    - _posts/news/krizis/*.md
    - _posts/news/2020q1/*.md
    - _posts/news/2020q1/*.md
    - _posts/news/2020q2/*.md
    - _posts/news/2020q3/*.md
hitsPerPage             : 5 # number of search results
```

**Comment by Ethermine-pool** [comment]
It would help, but not much.
The ideal solution would be to defer the load of `InstantSearch` until the moment the user clicks on the search.
Or postpone rendering of images until the `window.onload` event is fully fired.
It might be possible to do just [loading-lazy](https://github.com/gildesmarais/jekyll-loading-lazy), but this plugin does not take images from `InstantSearch`, so they are loaded on the main thread anyway. 

However, 90% of users will never click on search. So yes, I think we need to think of something.

**Comment by blogi-kriptovalyut** [comment]
I also opened a discussion here: [https://github.com/algolia/instantsearch.js/issues/4641](https://github.com/algolia/instantsearch.js/issues/4641)
