### ISSUE TITLE
Add alt tag to Site Logo

### ISSUE THREAD

**Issue by wildone** [mmistakes/minimal-mistakes#2823]
For latest version can you please update site-logo image in masthead.html to have alt text, `site.title` is a good title for that logo.

`masthead.html:8`:

`<a class="site-logo" href="{{ '/' | relative_url }}"><img src="{{ logo_path | relative_url }}" alt="{{ site.title }}"></a>`

This just failes htmlproofer and its not supper accessible either.

**Comment by mmistakes** [comment]
Duplicat eof #2529
