### ISSUE TITLE
Can't open website when in 4G mode

### ISSUE THREAD

**Issue by fayeah** [mmistakes/minimal-mistakes#2827]
## Environment

- Minimal Mistakes version: **4.22.0**
- Ruby gem or remote theme version: 
- Jekyll version:**4.2.0**
- Git repository URL:**https://github.com/fayeah/fayeah.github.io**
- GitHub Pages hosted (if yes provide URL to site): **https://fayeah.github.io/**
- Operating system: **macOS**

## Expected behavior

Can open git page (website) as normal under 4G/data, but it fails to load the page without loading on  mobile (iPhone).

## Steps to reproduce the behavior

open page on Safari browser

**Comment by iBug** [comment]
Whoa... things are getting stranger and stranger.

It's definitely not this theme's fault that the page doesn't load on your mobile cellular data. Check your internet connection.

BTW, China Mobile is notorious for its terrible global internet access. For example, [this V2EX thread](https://v2ex.com/t/651518) and [this Emacs China thread](https://emacs-china.org/t/github-pages/14316) both blames China Mobile for GitHub Pages accessibility issues.

Checkout [my article](https://ibug.io/p/28) on accelerating GH Pages with Cloudflare (custom domain needed).

（要爱国上网就别用移动网，或者买个[好点的梯子](https://go.ibugone.com/get-ss)）

**Comment by fayeah** [comment]
> Whoa... things are getting stranger and stranger.
> 
> It's definitely not this theme's fault that the page doesn't load on your mobile cellular data. Check your internet connection.
> 
> BTW, China Mobile is notorious for its terrible global internet access. For example, [this V2EX thread](https://v2ex.com/t/651518) and [this Emacs China thread](https://emacs-china.org/t/github-pages/14316) both blames China Mobile for GitHub Pages accessibility issues.
> 
> Checkout [my article](https://ibug.io/p/28) on accelerating GH Pages with Cloudflare (custom domain needed).
> 
> （要爱国上网就别用移动网，或者买个[好点的梯子](https://go.ibugone.com/get-ss)）

好嘛，谢啦～
