### ISSUE TITLE
Use of Sass @extend causing unexpected selector specificity when customizing CSS

### ISSUE THREAD

**Issue by iBug** [mmistakes/minimal-mistakes#2852]
This is the offending code I've tracked down:

<https://github.com/mmistakes/minimal-mistakes/blob/c501842db8765d9538fc787219ca4437a6570beb/_sass/minimal-mistakes/_forms.scss#L391-L393>

I tried to override non-button `<a>` element styles like this:

```scss
.page__content a:not(.btn) {}
```

However, the use of [Sass `@extend`][1] in the theme code causes Sass to generate the following CSS:

```css
.page__content a:not(.btn):not(#goog-wm-sb) {}
/* Oh yeah... */
```

The problem here is, the generated `:not(#goog-wm-sb)` makes the [specificity][2] of the selector higher than expected, as it has one ID selector. This makes overriding any styles difficult [without `!important`][3] because a "superceding" selector also needs an ID selector now.

Can we somehow rearrange this rule so it doesn't use `.btn` as aggressively? Using [`%btn`][4] is one (good) way I can think of, as we don't have too many bare `.btn`s to deal with.

  [1]: https://sass-lang.com/documentation/at-rules/extend
  [2]: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#selector_types
  [3]: https://uxengineer.com/css-specificity-avoid-important-css/
  [4]: https://sass-lang.com/documentation/at-rules/extend#placeholder-selectors

**Comment by mmistakes** [comment]
`#goog-wm-sb` styles should be removed. As they were part of Google's search field that was used on the 404 sample page... which was deprecated.

**Comment by mmistakes** [comment]
In fact all of these styles can probably go as G killed off the feature. No sense in shipping unused CSS.

https://github.com/mmistakes/minimal-mistakes/blob/c501842db8765d9538fc787219ca4437a6570beb/_sass/minimal-mistakes/_forms.scss#L361-L393

**Comment by iBug** [comment]
@mmistakes Mind adding me as a collaborator so I can help sort out issues and PRs? I check GitHub multiple times every day and can respond quickly.
