### ISSUE TITLE
node-sass No input file was found.

### ISSUE THREAD

**Issue by spa46** [mmistakes/minimal-mistakes#286]
Does anyone have a touble using **node-sass** that is given in package.json?

I am new to nodejs and followed various guidelines but now stuck in building css from _scss. 
When I ran one of the script that is in package.json in window command prompt,    

    node-sass --output-style compressed -o assets/css assets/_scss
     
it gives a following error.

    No input file was found.

Could you please tell me anyone had the problem and made it work?

These are what I tried:

- Installed different nodejs versions (i.e. v4.4.3 and v0.12.13) multiple times with different packages.
- checked package dependancy that is written in package.json (from master branch)
- tried with different [node-sass](https://github.com/sass/node-sass#command-line-interface) syntax

**Comment by mmistakes** [comment]
What if you change line 32 in `package.json` to this?

```js
"scss": "node-sass assets/_scss --output-style compressed -o assets/css",
```

I think I may have had the input and outputs reversed. It seems to work both ways for me on OS X and Windows.

**Comment by spa46** [comment]
C:\USERNAME.github.io>**node-sass assets/_scss --output-style compressed -o assets/css**
**No input file was found.**

C:\USERNAME.github.io>node -v
v0.12.13

C:\USERNAME.github.io>npm -v
2.15.0

C:\USERNAME.github.io>node-sass -v
node-sass       3.6.0   (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]

what version do you use?

**Comment by mmistakes** [comment]
Here's the versions on my Windows 7 machine. For Mac OSX they're about the same `node v4.x` and `npm v2.x`.

```bash
C:\Users\Michael\Documents\minimal-mistakes> node -v
v4.3.2

C:\Users\Michael\Documents\minimal-mistakes> npm -v
2.14.12

C:\Users\Michael\Documents\minimal-mistakes> node-sass -v
The term 'node-sass' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the s
pelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:10
+ node-sass <<<<  -v
    + CategoryInfo          : ObjectNotFound: (node-sass:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


C:\Users\Michael\Documents\minimal-mistakes> npm run build:css

> minimal-mistakes@2.1.0 build:css C:\Users\Michael\Documents\minimal-mistakes
> npm run scss && npm run autoprefixer


> minimal-mistakes@2.1.0 scss C:\Users\Michael\Documents\minimal-mistakes
> node-sass assets/_scss --output-style compressed -o assets/css

Rendering Complete, saving .css file...
Wrote CSS to C:\Users\Michael\Documents\minimal-mistakes\assets\css\main.css
Wrote 1 CSS files to C:\Users\Michael\Documents\minimal-mistakes\assets\css

> minimal-mistakes@2.1.0 autoprefixer C:\Users\Michael\Documents\minimal-mistakes\minimal-mistakes
> postcss -u autoprefixer -b ">, 5%, ie 9" -r assets/css/*
```

**Comment by spa46** [comment]
I synchronized those versions to yours but still did not work so that 
I reported it to node-sass as well.

https://github.com/sass/node-sass/issues/1505

Wait and see their feedback.

**Comment by mmistakes** [comment]
Closing as this appears to be a `node-sass` issue. Please reopen if that's not the case.
