### ISSUE TITLE
Incorrect link to setup an upstream remote

### ISSUE THREAD

**Issue by findjigar** [mmistakes/minimal-mistakes#287]
[Here on this page](https://mmistakes.github.io/minimal-mistakes/docs/upgrading/), it suggests utilizing git to fetch new updates from this repo's master branch, and provides a ready-to-use command as well but looks like it's correct.

It should be,
```git remote add upstream https://github.com/mmistakes/minimal-mistakes.git```

instead of,
```git remote add upstream https://github.com/mmistakes/minimal-mistakes/blob/minimal-mistakes.git```

**Comment by mmistakes** [comment]
Good catch. Thanks.
