### ISSUE TITLE
Author object tags showing at top of page

### ISSUE THREAD

**Issue by padraic7a** [mmistakes/minimal-mistakes#289]
I know this must mean I've done something silly but I can't see what it is.

When I build the site it displays as follows: 
![selection_004](https://cloud.githubusercontent.com/assets/3010391/14850963/764067a6-0c74-11e6-9311-6d36c06212ef.png)

Any hints as to what I've done?

**Comment by mmistakes** [comment]
Not exactly sure but all those variables are `author` ones in `_config.yml`. Maybe you have some improperly formatted YAML there.

**Comment by padraic7a** [comment]
That must be it. Thanks for your time and the theme.

**Comment by mmistakes** [comment]
I think you found a bug. In `_config.yml`. Quick fix is to add a Twitter account under `author`

```yaml
author:
  twitter: "padraicst"
```

There's a conditional in the `<head>` that I need to improve. It's getting confused by the fact that you set site `twitter.username` but not `author.twitter` as well.

**Comment by mmistakes** [comment]
Bug fix, change [*`_includes/seo.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/seo.html#L28) line 28

```liquid
{% assign seo_author = page.author | default: page.author[0] | default: site.author[0] %}
```

**Comment by padraic7a** [comment]
Ah, I was just drafting a response saying that it only triggers with a twitter username. I thought it might be because I put some extra gems in the gemfile.

Thanks again for your help!

**Comment by viktorsmari** [comment]
I have a related bug. I was using the Jekyll Wordpress importer tool and it creates the front matter yaml:

```
author:
  display_name: Someone
  login: someone
  email: someone@gmail.com
  url: ''
```

As a result I get this:

![a](https://user-images.githubusercontent.com/1689020/34663725-738cf362-f458-11e7-813b-2213bbba6639.png)


I traced the error to this line:
https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/seo.html#L42

Any ideas?

**Comment by mmistakes** [comment]
@viktorsmari The theme expects `author` to be a string not an array, that's why it's outputted that garbage at the top of your posts.

This is the way the [theme expects post author's to be specified](https://mmistakes.github.io/minimal-mistakes/docs/authors/).

**Comment by viktorsmari** [comment]
Thank you.

Because I was migrating a Wordpress site with hundreds of posts with the same front matter format, where the author is an array. Do I need to change each post or is there a simpler way? 
I am trying not to mess with the theme defaults.

**Comment by mmistakes** [comment]
@viktorsmari I don't think there is an easy way forward. I'll take a look at the templates and see if there is something I can adjust. `jekyll/feed` and `jekyll/jekyll-seo-tag` both use `author` in a similar way as this theme. I'll take a look and see what their solution is to accept `author` as a string or object.

**Comment by mmistakes** [comment]
@viktorsmari I pushed some updates. Try changing `remote_theme` to the fix branch and see if that takes care of the issue.

`remote_theme: "mmistakes/minimal-mistakes@seo-fixes"

**Comment by viktorsmari** [comment]
Hmm does not seem to work, if you want to try it yourself it is an open source project:

https://github.com/piratar/piratar-jekyll

Remember to remove the _includes/seo.html, or uncomment line ~42 back.

I start the project with the `./server.sh`

**Comment by mmistakes** [comment]
@viktorsmari Quick look you didn't update `remote_theme` in your _config.yml. You need to use the line above so it pulls from the git branch with the fix. Otherwise it'll continue to use the current version on `master`.

remote_theme: "mmistakes/minimal-mistakes@seo-fixes"

**Comment by viktorsmari** [comment]
I tried that locally, which did not work. I just did not push this change to Github.

**Comment by mmistakes** [comment]
@viktorsmari Hmmm. Define not working. I'm not seeing the `author` object array text on any of your pages.

![image](https://user-images.githubusercontent.com/1376749/34681611-6bb90600-f46a-11e7-8d01-cfbfc2fa7dda.png)

**Comment by viktorsmari** [comment]
If you scroll at the bottom of the frontpage, there are many pages you can try. 

Like the last one "Styrkja Pirata", does that one work?

Did you also undo/uncomment the SEO I wrote above?

**Comment by mmistakes** [comment]
@viktorsmari Yup. I removed your local version of `_includes/seo.html` so it doesn't override the fixed one in the theme.

All the pages, including that last one work as expected. No erroneous text printing on the pages from `author`.

![image](https://user-images.githubusercontent.com/1376749/34681832-0de88112-f46b-11e7-80b3-746e5613b398.png)

**Comment by viktorsmari** [comment]
Weird, this is my setup:
![2018-01-08_441x93](https://user-images.githubusercontent.com/1689020/34681836-5a1fa72c-f49d-11e7-949e-bc35ff81e341.png)
![2018-01-08_677x98](https://user-images.githubusercontent.com/1689020/34681837-5a433048-f49d-11e7-8827-0218035e10c2.png)

**Comment by mmistakes** [comment]
@padraic7a And you deleted your copy of `_includes/seo.html`?

**Comment by viktorsmari** [comment]
Haha, that was it! 

Thank you for your patience!

**Comment by mmistakes** [comment]
@viktorsmari OK good. 

FYI - When I merge in this change you'll want to remove `@seo-fixes` from the remote theme line. It can pull from master at that point since that SEO branch will eventually be deleted.

**Comment by padraic7a** [comment]
Hi @mmistakes , I haven't updated or even looked at the site since April 2016. I'll check this thread out when I get to update again.
 
Do you need me to close this issue?

**Comment by mmistakes** [comment]
Nah don't worry about it @padraic7a, I reopened it today to deal with a sort of related issue.

It'll close automatically when I merge in the fix https://github.com/mmistakes/minimal-mistakes/commit/176261c88e7afc9594e8efcdf2f453f34741966c

A lot has changed with the theme since then, if/when you get around to updating [give the docs a look](https://mmistakes.github.io/minimal-mistakes/docs/upgrading/). It's much easier to install/upgrade the theme once you migrate.

**Comment by padraic7a** [comment]
Great, will do. Thanks!
