### ISSUE TITLE
inline code extending content 

### ISSUE THREAD

**Issue by Bilenki** [mmistakes/minimal-mistakes#2905]
## Environment

- im working in github enterprise (GHE)
- using jekyll 4.1.1
- build your whole github page on my own

## Expected behavior

- i added some code snippets as inline code
- the page should automatically do a line break, but doesn't
-  if i add the command as one word it also doesn't break the line
## Steps to reproduce the behavior

- simply add `kubectl get cronjobs -A -o='custom-columns=KIND:.kind,NAME:.metadata.name,FS_GROUP:.spec.jobTemplate.spec.template.spec.securityContext.fsGroup'` to any post
- my github page doesn't break the line in the end of `page__content`
- sorry that i cannot offer you more information, the worst way for me would be to create the whole new page in the normal github...
- thanks in advance

**Comment by mmistakes** [comment]
Add `word-wrap: break-word;` to this line should fix it.
https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_base.scss#L173

**Comment by Bilenki** [comment]
thank you very much!
it worked!!!

you are a genius and also thank you for the awesome theme

**Comment by Bilenki** [comment]
Maybe one more question
I didn't get the point why do i need to paste {{ site.url }}{{ site.baseurl }} when i want to add images to my files.
Could you explain it to me? I'm very new to the topic
