### ISSUE TITLE
No "www" in links to social media causes redirects

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#292]
Please add to links generated from entries in _config.yml to include "www".
This would make it a little faster for users by avoiding a redirect.

![screen shot 2016-04-28 at 8 55 24 am](https://cloud.githubusercontent.com/assets/300046/14890346/76f1e070-0d1f-11e6-8f55-110791602cde.png)
This is from the report by the W3 validator at:
https://validator.w3.org/checklink?uri=http%3A%2F%2Fwilsonmar.github.io%2F&summary=on&hide_type=all&recursive=on&depth=1&check=Check

I'll create a PR on file **author_profile.html** (previously _author_bio.html) in the _includes folder within the develop branch.

**Comment by mmistakes** [comment]
A PR to `develop` should be good.

**Comment by wilsonmar** [comment]
PR #293 filed.

**Comment by mmistakes** [comment]
Merged in PR #293
