### ISSUE TITLE
Is there an easy way to size fix "x" amount of gallery images per row?

### ISSUE THREAD

**Issue by dkromp** [mmistakes/minimal-mistakes#294]
I see class="full"... is there an easy way to size, say 4 images per row in a gallery?

**Comment by mmistakes** [comment]
The [`gallery` include](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/gallery) has some logic built in that determines what CSS class to apply to the wrapper, which in turn determines if it should be 2 or 3 columns of images.

```liquid
{% if gallery_size == '2' %}
  {% assign gallery_layout = 'half' %}
{% elsif gallery_size >= '3' %}
  {% assign gallery_layout = 'third' %}
{% else %}
  {% assign gallery_layout = '' %}
{% endif %}
```

To do this with the least amount of work on your part you'd need to add a new class to style the images into 4 columns. I'd start with adding something like `.fourth` to [`_base.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/_scss/_base.scss#L198):

```scss
figure {

  &.fourth{
    > a,
    > img {
      @include breakpoint($small) {
        width: calc(25% - 0.5em);
      }
    }
...
}
```

Then you can use the gallery include with the `class` parameter like so:

```html
{% include gallery class="fourth" %}
```

And you should get something like this:

![gallery-4](https://cloud.githubusercontent.com/assets/1376749/14926104/82ce37d2-0e18-11e6-8233-473da4f9e6a2.jpg)

**Comment by dkromp** [comment]
I updated the _base.scss as you suggested and changed the gallery include to the following... 

`{% if gallery_size == '2' %}
  {% assign gallery_layout = 'half' %}
{% elsif gallery_size == '3' %}
  {% assign gallery_layout = 'third' %}
{% elsif gallery_size >= '4' %}
  {% assign gallery_layout = 'fourth' %}
{% else %}
  {% assign gallery_layout = '' %}
{% endif %}`

Instead of displaying the images as desired (in your example), I get each image being 100% width even though class="fourth" is displayed in the resulting figure tag.

Any ideas?

**Comment by mmistakes** [comment]
You probably need to [build the CSS](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/) as it's not automatic. You'll need to preprocess it using the included `npm run build:css` task. You made the change to the SCSS but it doesn't exist in the compiled CSS the site uses.

**Comment by dkromp** [comment]
That did it!!!
Thanks :+1:

**Comment by mmistakes** [comment]
:smile:

**Comment by Sciss** [comment]
It would probably be good to include this patch, I had done a similar thing a while back and suspect more people have to edit those files. Would be better to stay in sync with upstream.

**Comment by mmistakes** [comment]
@Sciss Visually four columns is pushing it for me as the images start to get small. I have a feeling this one is a matter of taste and no matter what solution I bake into the theme someone is going to want something else :wink:

For now I think I'm going to leave it as is and err on the side of being conservative with 3 columns as the max.

**Comment by healiseu** [comment]
I think there should be a more generic approach to the problem of **Responsive Grid Layout**. You may find relevant the discussion and solution we had on [this issue](https://github.com/mmistakes/minimal-mistakes/issues/383)
