### ISSUE TITLE
Need of a small tutorial on how to write a consistent and basic article website

### ISSUE THREAD

**Issue by ysig** [mmistakes/minimal-mistakes#2948]
Hi, 
thanks a lot for this awesome repo and this really motivating community work.

## Motivation

I have recently started creating my website on https://ysig.github.io/ and in https://github.com/ysig/ysig.github.io

I have the following problem:

I have created subfolders in order to put markdown files in order to post articles (as in [_data/navigation.yml](https://github.com/ysig/ysig.github.io/blob/master/_data/navigation.yml)).

My problems are the following and were not resolved from the [quick start guide](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/):

- How can the recent posts be automatically or manually updated with recent updates on those directories?
Right now my recent posts column looks like this:
![image](https://user-images.githubusercontent.com/28439529/117566909-0214e580-b0c2-11eb-97d6-98ef28cdf5dc.png)

- Moreover I observe a lack of spacing and centering in the subfolders I have.
So for a example the main page is well spaced:
![image](https://user-images.githubusercontent.com/28439529/117566740-29b77e00-b0c1-11eb-9f73-648c97cd6c79.png)
whereas when I click one of the tabs:
![image](https://user-images.githubusercontent.com/28439529/117566758-3e941180-b0c1-11eb-8d94-e32169af7ab2.png)
I see this:
![image](https://user-images.githubusercontent.com/28439529/117566771-4f448780-b0c1-11eb-8083-67ae1ba8f87f.png)
i.e. there is no spacing or centering.
Why is this happening? Should I add a command on the begging of my markdown file?

## Suggestion

I have not found any tutorial that can help me resolve this issue and thus I share it here, so that you maybe can add relevant information to your docs.
I would like to note, that although I am developer, I know nothing more than the absolute basics of web development.

I remain at your disposal for further questions.
Thanks a lot!!!

**Comment by iBug** [comment]
Looks like you're using the `default` layout when you're supposed to use [`single`](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#single-layout) instead.
