### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by glamvian** [mmistakes/minimal-mistakes#296]
can't full view code inside markup syntax highligh when acces in mobile phone

**Comment by mmistakes** [comment]
Not sure I follow what you're asking.

Code blocks have `overflow-x: auto` set in the CSS to properly contain lines that may be too wide to fit inside of the viewport. If they are wider a scrollbar appears to view the entire text (on mobile the scrollbars are generally hidden).

![mm-syntax-highlight-overflow-scroll](https://cloud.githubusercontent.com/assets/1376749/14943156/c8983f28-0f9f-11e6-82bb-a81bfb465798.gif)

If what you're asking is how to change it so none of the code is `hidden`, then you'll need to modify the CSS. If you remove the overflow the text will spill out and look like this.

![screen shot 2016-05-01 at 1 20 58 pm](https://cloud.githubusercontent.com/assets/1376749/14943162/e63d8a74-0f9f-11e6-89ca-5dd43ae2db35.png)

So you'll likely have to mess with `white-space: pre` to force line breaks with something like `white-space: normal`, which doesn't exactly look all that great either.

![screen shot 2016-05-01 at 1 24 50 pm](https://cloud.githubusercontent.com/assets/1376749/14943176/2cf9090c-0fa0-11e6-9d4a-ae2c4986bd54.png)

**Comment by glamvian** [comment]
sorry about my bad english , I think  google chrome in my mobile phone scollbars is not worked
when I try in tablet phone with different browser everything about syntax highlighting is perfect..
thankyou very much michael for your answer
