### ISSUE TITLE
Add Speaker Deck link to author profile

### ISSUE THREAD

**Issue by glennsarti** [mmistakes/minimal-mistakes#300]
Speaker Deck is a popular sharing site for presentations etc.  It would be nice to link/show-off your Speaker Deck presentations via the author profile.

I have raised https://github.com/mmistakes/minimal-mistakes/pull/299 with the code I used to add it to my blog site.

**Comment by mmistakes** [comment]
Closing to keep the theme lean and avoid configuration bloat.
