### ISSUE TITLE
ㅌㄹㅇㄹㅇㄴㅁㄹㅇ

### ISSUE THREAD

**Issue by co1dtype** [mmistakes/minimal-mistakes#3037]
## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- GitHub Pages hosted (if yes provide URL to site):
- Operating system:

## Other

![코드업_1478](https://user-images.githubusercontent.com/76248669/123981882-9124e680-d9fd-11eb-918c-0d32d86f5ab9.png)

**Comment by mmistakes** [comment]
???
