### ISSUE TITLE
Ability to move main navigation to bottom of the page

### ISSUE THREAD

**Issue by tobie** [mmistakes/minimal-mistakes#304]
I'm experimenting with so called [upside-down home pages](https://blog.leadpages.net/guest-post-home-page-design-bryan-harris-videofruit/) for my consulting website.

The main idea is to move the navigation at the bottom of the page to really put the content first.

Would you be interested to enable something like this?

This could be done either by adding a `hide_masthead` page variable (with the ability to create the navigation from scratch in the footer directory) or through a `navigation_position: top|bottom|none|both` variable with a predefined bottom nav design.

If you think the use case is too fringe the first solution (`hide_masthead` variable) has a minimal footprint and would still allow a lot more experimenting without touching the templates.

**Comment by mmistakes** [comment]
I think this is something best left out of the theme for now. Ideally I'd use [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) to lay out elements which makes it painfully easy to change their appearance order.

Taking the current markup of the page:

```html
<html>
  <body>
    <div class="masthead">...</div>
    <div id="main">...</div>
    <div class="page__footer">...</div>
  </body>
</html>
```

We could use `order` as part of flexbox in the CSS:

```css
.masthead { order: 3; }
#main { order: 1; }
.page__footer { order: 2; }
```

To move the masthead to the bottom of the page... or do whatever else you want.

```
[ #main ]
[ .page__footer ]
[ .masthead ]
```

Support for Internet Explorer [isn't quite there yet with flexbox](http://caniuse.com/#feat=flexbox) so I opt'd not to use it. On my personal site I do and have found it a joy to work with. It's very powerful and has the benefit of not having to mess with the actual page markup if you want to rearrange content.

**Comment by tobie** [comment]
Sounds good. Thanks for considering it and for the quick reply.
