### ISSUE TITLE
bundle exec jekyll serve throws error for dependencies

### ISSUE THREAD

**Issue by zachcowell** [mmistakes/minimal-mistakes#305]
I am attempting to run through the install steps locally (non-GH pages install). The instructions state: 

> If you’re not planning on hosting with GitHub Pages and want to leverage features found in the latest version of Jekyll, replace `gem "github-pages"` with `gem "jekyll"` in your `Gemfile`

However, after doing so, I do a `bundle install` followed by `bundle exec jekyll serve` I get the following:

```
[min-twitch] > bundle exec jekyll serve
Configuration file: /Users/zachcowell/Playground/blogs/min-twitch/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-sitemap or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-sitemap' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
```

I resolved all this by changing my Gemfile to the following and everything seems to work now:

```
source "https://rubygems.org"

gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jemoji"
# gem "jekyll-archives"
gem "wdm", "~> 0.1.0" if Gem.win_platform?
```

**Comment by mmistakes** [comment]
All true. The `github-pages` gems includes all of those gems by default (`jekyll-sitemap`, `jekyll-gist`, `jemoji`, etc. So removing it throws the error unless you specifically add in all of those. They're the same gems listed under `gems` in `_config.yml`.

**Comment by zeebluejay** [comment]
I came across this issue today and had to manually add those gems to make it work. I suggest before you consider this issue closed, please update your instructions to make it clear that all other gems should be added in the Gemfile. It would save people a lot of time in the future.

Looking forward to use this theme and great work!
Thanks for making it available.
