### ISSUE TITLE
Adjust colour for border-left when using {: .notice } classes in blockquotes

### ISSUE THREAD

**Issue by Andre601** [mmistakes/minimal-mistakes#3068]
## Environment

- Minimal Mistakes version: 2.24.0
- Ruby gem or remote theme version: 0.4.3 (Jekyll-remote-theme)*
- Jekyll version: 3.9.0
- Git repository URL: https://github.com/5zig-reborn/5zig-reborn.github.io
- GitHub Pages hosted (if yes provide URL to site): https://5zigreborn.eu/ (Page that uses the blockquote: https://5zigreborn.eu/downloads)
- Operating system: Windows 10

*Please note that I don't use ruby nor jekyll locally and that everything is done through GitHub pages. The version listed here is from the [Dependency versions page](https://pages.github.com/versions/) for GitHub Pages.

## Expected behavior
When using the `{: .notice }` option together with a blockquote (See reproduction steps) should the line used on the left side mimic the color used for the notice-type applied.

## Steps to reproduce the behavior
Write a blockquote with a notice similar to this setup:

```markdown
> This is a quote block.
> It is used to wrap multiple lines, including blank ones, into a `<p>` or something similar to then apply the `{: .notice--warning }` class.
>
> I use this since it's a bit easier than using a `<div>` solution.
{: .notice--warning }
```
Once rendered, you will notice that the blockquote will have a bright blue line on the left, while the body is an orange from the `notice--warning` class.

This feels out of place, but makes sense since the notice classes don't seem to override the border when they are used in combination with a blockquote, which is possible.

## Other
It's a minor visual issue, so I understand if changing this wouldn't take priority at all or doesn't even get worked on at all, but considering that using a block quote for larger areas together with the notice classes allows more simple formatting than using div classes (That either requires usage of HTML OR the `{% capture %}` option) would it be a shame if this wouldn't be corrected.

**Comment by iBug** [comment]
@mmistakes Got time to take a look at this one and the PR? Should be easy and harmless.
