### ISSUE TITLE
Should this API Key / Secret be here?

### ISSUE THREAD

**Issue by chris-bishop** [mmistakes/minimal-mistakes#3075]
First, let me say thank you for this wonderful theme you have graciously put so much of your time and effort in to - saving untold amounts of same for we cloners! Much appreciated!

As a matter of due diligence, I am just calling attention to the reCaptcha (site):API Key and secret hardcoded in the following file on L101 and 104 respectively:

https://github.com/mmistakes/minimal-mistakes/blob/89de4d46db3b7abf08748eeb41e24c34c935f4bf/staticman.yml#L99-L104

Please forgive me for the "blinding flash of the obvious" - but if these are legitimate auth creds for any existing site, they should be removed.

Please disregard if these are just "dummy" values meant as an example.

Cheers,

[@chris-bishop](https://github.com/chris-bishop)

**Comment by mmistakes** [comment]
One value is public and the `secret` value has been encrypted. Both are API keys that can be exposed.

**Comment by mmistakes** [comment]
Note the URL above the values. Has more context about encrypting these values before adding to any publicly accessible config files.

ref: https://staticman.net/docs/encryption

**Comment by chris-bishop** [comment]
@mmistakes 

Great! Thank you for the clarification! Much appreciated!
