### ISSUE TITLE
Bug: Here will use '///' as the home path

### ISSUE THREAD

**Issue by FavorMylikes** [mmistakes/minimal-mistakes#3093]
https://github.com/mmistakes/minimal-mistakes/blob/9269842e9dceed85021d657bdc80fb0ddbb26b3c/_includes/breadcrumbs.html#L22

![1627757614(1)](https://user-images.githubusercontent.com/16064851/127749819-b860fd23-cc7b-466c-ba90-b6c456b9aa82.jpg)

BTW

Current path is like `https://host/cate_1/cate_2/cate_3/`

**Comment by iBug** [comment]
Seems more like misconfiguration than theme fault. Could you share your repository where this can be reproduced?

**Comment by FavorMylikes** [comment]
Repo: [FavorMylikes/hackmd-note](https://github.com/FavorMylikes/hackmd-note)

You can access my blog at [ucas.io](https://ucas.io/3d/Initial-3D-builder-environment/)

The home still '///'

**Comment by iBug** [comment]
Neither `url` nor `baseurl` should end with a slash. [Jekyll just joins everything provided][1] to form a "complete URL".

Recommend closing this issue as it's not this theme's fault.

  [1]: https://github.com/jekyll/jekyll/blob/627e3bbe53db16d292d15e3d594d429673813fc1/lib/jekyll/filters/url_filters.rb#L79

**Comment by FavorMylikes** [comment]
Thanks! Cool!
