### ISSUE TITLE
Title should not be markdownified

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#3094]
## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- GitHub Pages hosted (if yes provide URL to site):
- Operating system:

I cannot use a pipe | in the title, as it will be changed by the markdownify. It seems unneccesary to markdownify the title, but there is probably some reason for this?

```
{%- if seo_title -%}
  {%- assign seo_title = seo_title | markdownify | strip_html | strip_newlines | escape_once -%}
{%- endif -%}
```

## Expected behavior

I think it should be pssible to use a pipe in the title.

## Steps to reproduce the behavior

Just try to add a pipe to the title.

**Comment by iBug** [comment]
I second that. If you submit a PR to change this I'll be in favor.
