### ISSUE TITLE
css missing while serving via https in custom domain

### ISSUE THREAD

**Issue by poudelprakash** [mmistakes/minimal-mistakes#310]
I have used this theme in my blog <http://www.poudelprakash.com/>, it works fine while on http but when i switch to https(<https://www.poudelprakash.com/>) css goes missing.
Is there some settings I can make to force this theme to fetch assets from https url instead of http while on https url?

**Comment by mmistakes** [comment]
You need to properly set `url: ` in your `_config.yml` to the domain you want to use. So use:

```yaml
url: https://www.poudelprakash.com
```

And your assets and links should be `https://` then. I looked at your source and everything is `http://` which is why your CSS isn't loading due to insecure mixed content.

**Comment by poudelprakash** [comment]
Thanks! it works :+1:

**Comment by mmistakes** [comment]
Did you set `
