### ISSUE TITLE
Reading time function couldn't count number of words correctly

### ISSUE THREAD

**Issue by xfl03** [mmistakes/minimal-mistakes#3235]
### What happened?

- Minimal Mistakes version: 4.24.0
- Ruby gem or remote theme version: 3.2.22
- Jekyll version: 3.9.0
- Git repository URL: None
- Hosted on GitHub Pages (if yes provide URL to site): None
- Operating system: Windows

If the post is written in a language which doesn't need to use space between words, the number of words couldn't be count correctly. 
To display the number of words, I modified `_include/page__meta.html`. The only thing I do with this file is show `{{ words }}` in html.

![image](https://user-images.githubusercontent.com/3205159/141672651-b9ac963d-ae82-44a3-85c5-fc7929006e2c.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/3205159/141672618-fed31570-6e7c-447b-9496-e9ff4146269e.png)

### Steps to reproduce the behavior

Write a post in Chinese. 
```
比如说我写了这么一段话，他认为我只有1个字。再加一句话也是如此。
```

**Comment by iBug** [comment]
This is not a fault of the theme. It's how [Jekyll's `number_of_words`](https://github.com/jekyll/jekyll/blob/v3.9.0/lib/jekyll/filters.rb#L125) filter is implemented. If you need better results for CJK you may check out [my plugin](https://github.com/iBug/iBug-source/blob/master/_plugins/number_of_words.rb).

**Comment by xfl03** [comment]
> This is not a fault of the theme. It's how [Jekyll's `number_of_words`](https://github.com/jekyll/jekyll/blob/v3.9.0/lib/jekyll/filters.rb#L125) filter is implemented. If you need better results for CJK you may check out [my plugin](https://github.com/iBug/iBug-source/blob/master/_plugins/number_of_words.rb).

Thanks, but I think Jekyll should fix this.

**Comment by xfl03** [comment]
@iBug 
Unfortunately, GitHub Pages didn't support new version of Jekyll. And the `_plugins/number_of_words.rb` did not work too.
So I make a workaround for it, which only uses Liquid syntax: https://github.com/xfl03/xfl03.github.io/blob/1abc2de22e46f07dbb91ad2ca8c5ef2980280323/_includes/page__meta.html#L17-L42

**Comment by iBug** [comment]
Glad to know you came up with your own solution. Just to note that [custom plugins are not supported with GitHub Pages](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins), so if you want the `_plugins/*.rb` files to work, you have to build your site locally or use some CI to automatically build & push. I [had an article](https://ibug.io/p/38) about using GitHub Actions a year ago.
