### ISSUE TITLE
Provide a place to add custom CSS

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#327]
Since this template uses SASS, one cannot simply paste CSS for additional fields, such as a search form. So how about creating a blank **custom.css** file so users of this site can simply paste their custom CSS there. What I am asking is to pre-implement work-arounds such as 
https://github.com/chriseppstein/sass-css-importer.

BTW, I describe this in my notes at http://wilsonmar.github.io/jekyll-search-field.md

**Comment by mmistakes** [comment]
Why not just [use Sass](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/) and bake it into that as another partial that is `@import`ed into [main.scss](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/_scss/main.scss). It keeps all the CSS in one file then eliminating the extra HTTP request which is good for performance.
