### ISSUE TITLE
Improve masthead, hero overlay, and footer text alignment

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/minimal-mistakes#342]
To avoid awkward placement of masthead, overlay text, and footer links, left align all to line up nicely.

![mm-left-align](https://cloud.githubusercontent.com/assets/1376749/15834880/89badec8-2bfb-11e6-960c-d2b5b9aa7513.jpg)

**Comment by mmistakes** [comment]
ebccf636383d82b8f6b903887a61ca33a28fa49a

**Comment by casa-albore** [comment]
Much appreciate all this work - but is this change configurable? It completely changes the look of my site (which doesn't use the left-hand side-bar), spoiling it (IMHO). I love the theme though.

**Comment by mmistakes** [comment]
@casa-albore You don't have to update if the change doesn't fit with your site. It's only cosmetic changes in the theme's CSS. You can easily revert the changes back if you've already merged it in by looking at the commit and adding back the centering.

Changes: https://github.com/mmistakes/minimal-mistakes/commit/ebccf636383d82b8f6b903887a61ca33a28fa49a
