### ISSUE TITLE
Yandex and Alexa verifications require missing configuration flags

### ISSUE THREAD

**Issue by jhabdas** [mmistakes/minimal-mistakes#347]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.2.1
- **`github-pages` or `jekyll` gem version:** 3.1.6
- **Operating system:** OS X 10.11.5

---

## Expected behavior

Adding a value to `site.alexa_site_verification` or `site.yandex_site_verification` front matter does not output the expected `meta` tags given `seo.html` has liquid conditions requiring a flag under `site.owner.[service].verify` to be truthy in order to output the tag.

## Steps to reproduce the behavior

1. Add a verification codes for Alexa or Yandex to `_config.yml`.
1. Observe no new `meta` tags output in the generated document `head`.

Here's the webmaster verification related code in `seo.html` as of this version:

``` liquid
{% if site.google_site_verification %}
  <meta name="google-site-verification" content="{{ site.google_site_verification }}" />
{% endif %}
{% if site.bing_site_verification %}
  <meta name="msvalidate.01" content="{{ site.bing_site_verification }}">
{% endif %}
{% if site.owner.alexa.verify %}
  <meta name="alexaVerifyID" content="{{ site.alexa_site_verification }}">
{% endif %}
{% if site.owner.yandex.verify %}
  <meta name="yandex-verification" content="{{ site.yandex_site_verification }}">
{% endif %}
```

Is there a specific reason Yandex and Alexa don't follow the same branch logic pattern used for Google or Bing?

**Comment by mmistakes** [comment]
@jhabdas Looks like you found some typos. Both Alexa and Yandex should follow the same logic as the others. `owner` shouldn't be in the variable names.

Happy to merge in a pull request if you want to take a stab at fixing it. It's a super easy change.
