### ISSUE TITLE
Can't add Font Awesome icon

### ISSUE THREAD

**Issue by Reevid** [mmistakes/minimal-mistakes#3576]
### What happened?

Hosted by github page
Use latest version

I add Font Awesome Icon to my page as below
https://github.com/Reevid/Reevid.github.io/commit/77ef05fab8e1485f5e90f9583032d9fb1b0f3864

But it shows wrong image
![image](https://user-images.githubusercontent.com/4592433/163318806-0b8f7598-1ded-4cff-8a44-a4855a996054.png)

https://reevid.github.io

### Expected behavior

I want use all free font awesome icons

### Steps to reproduce the behavior

See this page https://reevid.github.io

**Comment by juweins** [comment]
Hey! I just came across a related (basic) issue. Can you tell me how you managed to change the font? So far I tried everything I know.

I recently started with jekyll and the discussion forum seems to be dead. Consider my repo is a "fresh" clone of BB...
