### ISSUE TITLE
Use jekyll-archives to show all posts (sorted by date)

### ISSUE THREAD

**Issue by synedra** [mmistakes/minimal-mistakes#363]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 3.2.6** 
- **`github-pages` or `jekyll` gem version: 3.1.6** 
- **Operating system: ubuntu** 

---

## Expected behavior

/archive should show a list of posts regardless of category, sorted by date (but not limited by year).  At the least I need to know how to create a master page that links to each of the category/date pages.  My layout-fu is very weak.
## Steps to reproduce the behavior
1) Include jekyll-archives
2) Activate it in _config.yml
3) Serve the existing pages

https://github.com/synedra/minimal-mistakes

**Comment by mmistakes** [comment]
Just a FYI. You don't need Jekyll archives to show all posts. That gem is used to generate individual archive pages for each category or tag. It has nothing to do with building a page that lists all categories or tags.

If you just want a page that lists every post in reverse chron remove `archive.html` in the root, rename `_pages/archive.md` to `_pages/archive.html` and replace the content with this.

```html
---
layout: archive
permalink: /archive/
author_profile: true
---

{% include base_path %}

{% for post in site.posts %}
  {% include archive-single.html %}
{% endfor %}
```

Which will give you a page at `/archive/` that lists every one of your posts.

![archive](https://cloud.githubusercontent.com/assets/1376749/16094114/a5dc97e6-330c-11e6-962e-4f6bb8071858.jpg)

I noticed quite a few duplicate pages floating around that might cause you trouble down the road. If you have pages in `_pages` don't place ones with the same name/permalink in the root. They go in one or the other or else they will just overwrite each other.

Also if you hope to use Jekyll Archives you were missing a few configurations. The gem needs to be added to `Gemfile` with `gem "jekyll-archives"` and then `bundle install`. As well as adding it under `gems` in your `_config.yml` along with uncommenting the Jekyll Archives settings and replacing `liquid` with `jekyll-archives`.

Refer to the [docs](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#taxonomy-archive) for the full set of instructions.

For help with installing [Jekyll Archives](https://github.com/jekyll/jekyll-archives) check their docs.

**Comment by mmistakes** [comment]
I'm going to assume you got this working. If that's not the case feel free to re-open the issue.
