### ISSUE TITLE
Custom portfolio page

### ISSUE THREAD

**Issue by nicolaspettican** [mmistakes/minimal-mistakes#364]
In order to view the pages and posts inside of the _portfolio directory in the portfolio archive html page you would use a liquid tag such as:
  {% for post in site.portfolio %}
    {% include archive-single.html type="grid" %}
  {% endfor %}
However, I was wondering if there would be a way to use this liquid tag to view posts and pages from a custom directory such as "_illustrations" in the root directory. Using something like {% for post in **site.illustrations** %} does not work. Any ideas?

**Comment by mmistakes** [comment]
How have you setup your `illustrations` collection in `_config.yml`? Does it have it's output set to `true`? The for loop used for `site.portfolio` collection should work the same way for any other collection as long as it's properly setup and has content.

**Comment by pettiblog** [comment]
Hi Michael, thanks for getting back to me! I think I managed to sort it out. I had set up the new collection in **_config.yml** with its own permalink as */:portfolio/:illustrations/* to try and make it as a subsection of the portfolio only to run into errors, so I removed it and it works fine now (should I have done that?). I also forgot to include the defaults for **illustrations**, thanks for the [link](https://jekyllrb.com/docs/collections/)!

**Comment by nicolaspettican** [comment]
Hi Michael, thanks for getting back to me! I think I managed to sort it out. I had set up the new collection in **_config.yml** with its own permalink as */:portfolio/:illustrations/* to try and make it as a subsection of the portfolio only to run into errors, so I removed it and it works fine now (should I have done that?). I also forgot to include the defaults for **illustrations**, thanks for the [link](https://jekyllrb.com/docs/collections/)!

**Comment by mmistakes** [comment]
That could have been the problem, not sure. I've never tried to make a child collection before. 

If you run into any other Collection related issues, might be worth your time asking for help on https://talk.jekyllrb.com/ since it's more of a "using Jekyll" question than something directly tied to my theme.

Closing because it seems you've sorting it out.

**Comment by nicolaspettican** [comment]
Thanks :smile: will do!
