### ISSUE TITLE
The YouTube video on the "Layout: Header Video" page is private

### ISSUE THREAD

**Issue by bewuethr** [mmistakes/minimal-mistakes#3649]
### Motivation

The [example post with a header video](https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-video/) ([source](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_posts/2010-06-02-post-video-youtube.md)) looks like this:

![image](https://user-images.githubusercontent.com/8521043/168209010-20b7e834-05db-4cab-893b-9515e4559203.png)

i.e., doesn't demonstrate what a header video would look like.

### Suggestion

Use a non-private video 🙂

**Comment by bewuethr** [comment]
Interestingly, when I visit the link from the source directly, I can access the video 🤔

**Comment by mmistakes** [comment]
Not a theme issue... I'm guessing the video owner has turned off embedding/sharing and that's why it doesn't show up anymore.

Switching the embeds to public videos...
