### ISSUE TITLE
Wide figures overflow content area (minor)

### ISSUE THREAD

**Issue by mje-nz** [mmistakes/minimal-mistakes#369]
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** commit f7ebec9 (3.2.9)

---

## Expected behavior
Wide figures should be limited to the width of the main column, like wide images are.

## Steps to reproduce the behavior

Look at [the image alignment demo page](https://mmistakes.github.io/minimal-mistakes/markup/markup-image-alignment/) -- the 1200px figure overflows the content area.

**Comment by mmistakes** [comment]
That's for bringing this up. It's not technically a bug but intentional. I applied some CSS to that figure element `style="width: 1200px"` to force it to break the layout as a check. In practice no one would do this.
