### ISSUE TITLE
Sidebar image size

### ISSUE THREAD

**Issue by paulvickers** [mmistakes/minimal-mistakes#371]
Is it possible to alter the size of an image included in the sidebar? The sidebar css class forces image width of 100% but I have a logo I'd like to include that is smaller than that. I've put the following into sidebar.html:

`  <a href="http://www.icad.org"><img border="0" alt="ICAD" src="images/ICAD.png" width="90"></a>`

**Comment by mmistakes** [comment]
Have you tried adding inline CSS to the `img` element to set the width and heights you want. That should override any of the sidebar CSS.

```html
<a href="http://www.icad.org">
  <img border="0" alt="ICAD" src="images/ICAD.png" width="90" style="width: 90px; height: 90x;">
</a>
```

**Comment by paulvickers** [comment]
Perfect, thanks. :-)
