### ISSUE TITLE
config.yml has `future: false` yet in Collection grid future posts are visible, when clicked page not found (want future posts in grid/collection OFF)

### ISSUE THREAD

**Issue by gChingon** [mmistakes/minimal-mistakes#3817]
### What happened?

- Minimal Mistakes version: 4.24.0
- Ruby gem or remote theme version: 2.6.0
- Jekyll version: unknown (M1 Mac Mini doesn't play nice with ruby/bundle/gem)
- Git repository URL: CochinoChingon/sucias.git
- Hosted on GitHub Pages (if yes provide URL to site): sucias.xyz/blog
- Operating system: Mac OS 12.3.1

### Expected behavior

on my website sucias.xyz/blog I expect future blog posts to not show up in the grid. however, the excerpt, teaser and link are visible. when clicked I get a 404 error page. So technically the page isn't displaying (as expected) however, I don't think the link/teaser/excerpt should be visible in the collection/grid/layout (sucias.xyz/blog) page. 

also TOC isn't working in collection posts

### Steps to reproduce the behavior

generated/forked minimal-mistakes theme from starter. have edited/used the theme for over a year, recently decided to post future blog posts with a youtube embed, because I can get the link when it's scheduled in the future. Vs having to wait for spotify to post podcast episode, remember to create a post and rush once episode is live. 

So I hadn't used future posts before and noticed this quirk now that I have to future posts pending. 

### Other

here is the current [config](https://github.com/CochinoChingon/sucias/blob/master/_config.yml) where `future: false` on line 32. 

today's date is 29 JUL 2022, two blog posts are dated 2022-08-02 and 2022-08-09, titles, teaser img and excerpt are visible on https://sucias.xyz/blog. (reverse order) so the top two posts (at the time of this issue) shouldn't be visible. [_pages/blog.md](https://github.com/CochinoChingon/sucias/blob/master/_pages/blog.md) also has `future: false` set in front matter and have tried/tested on desktop and mobile with and without `future: false` set in front matter, and with/out in `_config.yml` in all cases (allowing 5 mins between each page refresh) future posts are visible in url/blog

**Comment by iBug** [comment]
By default `future` only applies to the built-in `_posts` collection. Since you've created your own `_blog` collection, it's no longer governed by that setting.

If you want to go any more into this question, it's about Jekyll and not this theme.
