### ISSUE TITLE
Embedding youtube videos or other content with a responsive grid layout : Is that possible ?

### ISSUE THREAD

**Issue by healiseu** [mmistakes/minimal-mistakes#383]
Hi Michael,

is there a quick way to embed two, three or more youtube videos in a row, i.e. next to each other. I noticed that you have built something similar for the figures with the `<figure class="third">.....</figure>`. I have also tried to use `<div class="grid__wrapper">` without any luck. There is also a `group-by-array ` include file that **allows an object to be grouped by an array**. It has been used in categories and tags archive lists but I don't know if  and how it is possible to make it work with youtube embedded videos.

Could you please help with this feature ?

Thank you

**Comment by mmistakes** [comment]
Not really. You'll need to add some custom CSS to do this. The group by array include has nothing to do with this... it's purely styling.

YouTube video embeds use the `<iframe>` element. So you'd need to style them similar to how I've styled `<img>` inside of a [`<figure>` element](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/_scss/_base.scss#L173).. giving them a width, floating to the left, etc. so they align next to each other and fit inside of their parent container.

You could try adding `iframe` to `.half` and `.third` and [rebuild the theme's stylesheet](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/) and see if that works. Might need some further styling to fine tune things.

```scss
  &.half {
    > a,
    > img,
    > iframe {
...
}

  &.third {
    > a,
    > img,
    > iframe {
...
}
```

**Comment by healiseu** [comment]
Generally speaking I am in a process of porting my site from the [Phlow feeling-responsive theme](http://phlow.github.io/feeling-responsive/). In my opinion your theme is far more suitable and compatible to store on github and the overal style and appearence is better too. 

Nevertheless, one of the things I am greatly missing is the easy of use and the power of a grid system that is based on Zurb Foundation Grid component. It is super easy to [construct a grid layout](https://phlow.github.io/feeling-responsive/design/grid/) and fill it with any type of content you like. I recommend you adopt a similar solution for your theme. 

Anyway that is just a suggestion for further enhancements. There are other nice features I am missing from feeling-responsive. I will try to see how I can replace them with features of your theme.

Thank you again for your prompt support and quick reply.

**Comment by mmistakes** [comment]
Minimal Mistakes uses [Susy](http://susy.oddbird.net/) to build any sort of grid system you want. It's way more powerful and bespoke than an off the shelf an opinionated framework like Bootstrap or Foundation. My intention wasn't to make yet another Jekyll theme that uses those frameworks.

You're right it doesn't come with predefined classes to set column widths. I prefer semantic grids that don't liter up your HTML markup with things like `class="col-4-sm`". With a little work you can do something similar with Susy and building out the stylesheet to suit your own needs.

**Comment by healiseu** [comment]
Susy, tastes great, this is good to know ;-) I cannot consider myself an experienced web developer, neither I have time to dig deep enough. I have already spent a week to absorb the details of your theme. I do not regret this, I just hope I will be rewarded with a beautiful result and full control of my web site at the end. 

As a user of your theme I would expect a demo on constructing a grid like the one I referenced in my previous comment. But for now, I have followed your advice. I managed to update first my npm, node, not an easy task, then I rebuilt the theme's style-sheet successfully. I have committed the changes and you can view my [updated version of _base.scss](https://github.com/healiseu/healiseu.github.io/blob/master/assets/_scss/_base.scss#L173). I tried to [test it with this post](http://healis.eu/medilig/neurohealis-pilot-study/) but although it does something, videos are not aligned in a row.

Any ideas how I can fix this, since I reached that far ?
Thank you

**Comment by mmistakes** [comment]
Probably out of the scope of what I can help with. You're venturing into the fun and exciting world of web development and questions of that nature are best ask on sites like Stackoverflow.

To get you started it's has something to do with the [FitVid.js](http://fitvidsjs.com/) script the theme uses to make videos responsive. If you inspect the elements with your browser's web developer tools you'll see it's wrapping the `<iframe>`s so it can apply some styling. That's making them have a width of `100%` which is obviously not what you're trying to achieve.

You could disable the script and see if that works for you. That would require doing a similar thing with `npm` and pulling it out FitVid specific stuff.

A low-tech solution would be to place the videos in a `<table>` with however many columns you want and set the widths on the `td`. Problem with this approach is it's not responsive so it'll likely look awful on small screens when it tries to squish 3 videos together in a row.

**Comment by healiseu** [comment]
OK thank you, I am stopping here. I will post a screen capture of how this looked like previously on a 3rows x 2columns grid and with a window of 730pixels wide. I have put also the code in case you or someone else might decide to enhance your theme in the near future.

![3x2-youtube-videos](https://cloud.githubusercontent.com/assets/14239698/16460872/4245127c-3e32-11e6-9664-5192b75377d8.jpg)

``` html
<!-- Set a 3rows x 2columns Grid, i.e. 2columns x 6width = 12  -->
<div class="row t60">
  <!-- First Row -->
    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe
        src="http://www.youtube.com/embed/dhAQB44QQZg"
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>

    <!-- Leave this cell empty -->
    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe        
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>
  <!-- End of First Row -->

  <!--Second Row -->
    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe
        src="http://www.youtube.com/embed/0zqYT7C7OXI"
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>

    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe
        src="http://www.youtube.com/embed/kewwVdJpzSY"
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>
  <!-- End of Second Row -->

  <!-- Third Row -->
    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe
        src="https://www.youtube.com/embed/LbAwuEZNNms"
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>

    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe
        src="https://www.youtube.com/embed/7qWokWCfqdo"
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>
  <!-- End of Third Row -->
</div> <!-- End of Grid -->
```

**Comment by healiseu** [comment]
OK thank you, I am stopping here. I am posting a screen capture of how this looked like on the [Phlow feeling-responsive theme](http://phlow.github.io/feeling-responsive/). The captured image displays a 3rows x 2columns grid taken from a window 730pixels wide. I have put also the code in case you or someone else might decide to enhance your theme with a similar functionality in the near future. That will be great ;-)

![3x2-youtube-videos](https://cloud.githubusercontent.com/assets/14239698/16460872/4245127c-3e32-11e6-9664-5192b75377d8.jpg)

``` html
<!-- Set a 3rows x 2columns Grid, i.e. 2columns x 6width = 12  -->
<div class="row t60">
  <!-- First Row -->
    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe
        src="http://www.youtube.com/embed/dhAQB44QQZg"
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>

    <!-- Leave this cell empty -->
    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe        
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>
  <!-- End of First Row -->

  <!--Second Row -->
    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe
        src="http://www.youtube.com/embed/0zqYT7C7OXI"
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>

    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe
        src="http://www.youtube.com/embed/kewwVdJpzSY"
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>
  <!-- End of Second Row -->

  <!-- Third Row -->
    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe
        src="https://www.youtube.com/embed/LbAwuEZNNms"
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>

    <div class="medium-6 columns b30"><div class="flex-video widescreen vimeo">
      <iframe
        src="https://www.youtube.com/embed/7qWokWCfqdo"
        frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
      </iframe>
    </div></div>
  <!-- End of Third Row -->
</div> <!-- End of Grid -->
```
