### ISSUE TITLE
List Posts by Category and/or Tag 

### ISSUE THREAD

**Issue by healiseu** [mmistakes/minimal-mistakes#387]
- [x] This is a feature request.

## Filter the list of your posts by using specified criteria

The following code is an include command, e.g. list-posts that can be used in posts, pages and even sidebar to retrieve a list of items that satisfy several criteria: number of entries, offset, category and tag. You may see an example of use **`{% include list-posts category='MEDILIG' %}`** [here](http://healis.eu/medilig/#medilig-posts).

``` ruby

{% comment %}
list-posts depends on {% include archive-single.html %} and
is used in sidebar, posts or pages to list posts under the following criteria

*
*   Possible parameter for this loop:
*
*    › entries
*    › offset
*    › category only
*    › tag only
*    › category AND tag
*
*   Example for Category: {% include list-posts entries='3' offset='1' category='design' %}
*   Example for Tag: {% include list-posts entries='5' tag='terminal' %}

*   Example for Category and Tag: {% include list-posts category='en' tag='speech' %}
*   Output all speeches in English
*
*   This loop works like this:
*
*   1. First we check if there was given a category for filtering › if include.categories == NULL
*   2. If no category is given for filtering do a general loop.
*   3. If a category/tag was given, assign secat/seltg to the variable category/tag
*
{% endcomment %}


{% assign selcat = include.category %}
{% assign seltg = include.tag %}


{% if selcat == NULL and seltg == NULL %}
  {% for post in site.posts limit:include.entries offset:include.offset %}
    {% include archive-single.html %}
  {% endfor %}


{% elsif selcat!="" and seltg!="" %}
  {% for post in site.categories.[selcat] %}
    {% if post.tags contains seltg %}
      {% include archive-single.html %}
    {% endif %}
  {% endfor %}


{% elsif selcat %}
  {% for post in site.categories.[selcat] limit:include.entries offset:include.offset %}
    {% include archive-single.html %}
  {% endfor %}


{% elsif seltg %}
  {% for post in site.tags.[seltg] limit:include.entries %}
    {% include archive-single.html %}
  {% endfor %}

{% endif %}

```

**Comment by mmistakes** [comment]
How is this any better than using the [group by array](https://github.com/mushishi78/jekyll-group-by-array) already included with the theme?

I prefer simpler solutions when possible and keeping things more "vanilla" make's it easier to find help instead of digging through layers of abstraction. This sort of logic is more of an add-on than a "bundle it in by default" sort of thing I think.

**Comment by healiseu** [comment]
Documentation on [group by array](https://github.com/mushishi78/jekyll-group-by-array) liquid include command says:

> Include the file in your template, passing in a collection and a field variable

A **post category** is not a collection, you can do
`{% include group-by-array.html collection=site.posts field='categories' %}`

But **list-posts** can do a filtering on the posts (collection) based on a **specific category** and a **specific tag**. 

This is very useful as in **you often want to present your user only a subset of posts that satisfy certain criteria**, i.e. specific category and tags. With a database as a back-end that would be trivial but without a database you have to resort to such liquid include solutions.

**Comment by mmistakes** [comment]
Gotcha. Get how it would be useful in some cases, but still not convinced it needs to be in the theme.
