### ISSUE TITLE
Disqus comment box not showing when using posts layout

### ISSUE THREAD

**Issue by mmolinac** [mmistakes/minimal-mistakes#3873]
### What happened?

I can see Disqus comments in posts with `layout: single` but not in posts with `layout: posts`.
However, if I check the source code of the page in both cases, the JS code for the box is there.

- Minimal Mistakes version: latest
- Ruby gem or remote theme version: jekyll-remote-theme (= 0.4.3)
- Jekyll version: 3.9.2
- Git repository URL: https://github.com/pocosmhz/pocosmhz.github.io
- Hosted on GitHub Pages (if yes provide URL to site): Yes. https://blog.pocosmhz.org which points to https://pocosmhz.github.io
- Operating system: Both Debian Linux and MacOS Big Sur.

### Expected behavior

I hoped to see the comment box in posts with `layout: posts` as well.

### Steps to reproduce the behavior

I supply the same post with different date and layout field. The rest of the post is the same:

- Post with `layout: single`, where the comment box appears: https://blog.pocosmhz.org/2021/02/07/secret-world.html
- Post with `layout: posts`, where the comment box does not appear: https://blog.pocosmhz.org/2021/02/08/secret-world.html

### Other

Again, and just in case, the blog repository is public and can be downloaded from https://github.com/pocosmhz/pocosmhz.github.io .

**Comment by iBug** [comment]
I'd say it's pretty much intended. The `posts` layout is for listing recent posts and not for content pages, so there's no `<section id="disqus_thread">` for the Disqus script to insert the comment area.

**Comment by mmolinac** [comment]
@iBug oh, I see.
I thought the "default" layout was `posts`. I'll use `single` for my posts as it looks it's the best for that.
Thanks!
