### ISSUE TITLE
ordering of custom sidebar and author profile

### ISSUE THREAD

**Issue by allender** [mmistakes/minimal-mistakes#388]
- [ ] This is a question about using the theme.
- [X] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.2.13
- **`github-pages` or `jekyll` gem version:**  github-pages 86
- **Operating system:** Windows 10 

---

## Expected behavior

  Per the docs on layouts:

**ProTip:** Custom sidebar content added to a post or page's YAML Front Matter will appear above the author profile if enabled with `author_profile: true`.

But the author profile currently shows above the custom sidebar

## Steps to reproduce the behavior

Visit:  https://allender.github.io/apple2emu/intro/. 

You'll notice that the author information appears above the custom sidebar, contradicting the information in the docs for the theme.  The fix is easy and I can submit a PR if that would be helpful

**Comment by mmistakes** [comment]
It's a typo. Should say that it appears "below" the author profile. It's working as intended.

**Comment by allender** [comment]
Sounds good.  Thanks.

**Comment by mmistakes** [comment]
Thanks for catching it. I'll fix the docs.
