### ISSUE TITLE
ERROR `/favicon.ico' not found

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#389]
- [X] This is a question about using the theme.
- [X] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** OSX El Capitan
---

## Steps to reproduce the behavior

0. git clone
0. bundle
0. bundle exec jekyll serve --port 4001
   The response:

```
Configuration file: /Users/mac/gits/jekyll/minimal-mistakes/_config.yml
            Source: /Users/mac/gits/jekyll/minimal-mistakes
       Destination: /Users/mac/gits/jekyll/minimal-mistakes/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.122 seconds.
 Auto-regeneration: enabled for '/Users/mac/gits/jekyll/minimal-mistakes'
Configuration file: /Users/mac/gits/jekyll/minimal-mistakes/_config.yml
    Server address: http://127.0.0.1:4001/
  Server running... press ctrl-c to stop.
[2016-07-08 11:32:01] ERROR `/favicon.ico' not found.
[2016-07-08 11:32:01] ERROR `/favicon.ico' not found.
```

Suggestion: Add a favicon.ico file to the root folder fixes this.
I'm preparing a PR now.

**Comment by mmistakes** [comment]
I purposely left out the `favicon.ico` to avoid the propagation of one designed for the theme. I've included it in the past and no one (well mostly no one) ever bothers to change it.

Someone who knows what a favicon is will be the same person who will add one in. I don't think it's a big issue that the WEBrick server bundled with Jekyll is shouting that there is one missing. The default [`jekyll new` site theme](https://github.com/jekyll/jekyll/tree/master/lib/site_template) doesn't include a favicon either, so I think there's some precedence here to eliminate the fluff and provide sensible defaults when necessary.

**Comment by wilsonmar** [comment]
OK. Is there a way to suppress the error message.

**Comment by mmistakes** [comment]
I'm not familiar with the intricacies of WEBrick to know if there's a way to suppress those errors. It's not really an error with Jekyll, WEBrick, or the theme.

Depending on your browser some automatically make HTTP request for `favicon.ico` and since it doesn't exist WEBrick is showing that message. Those requests will also appear in your server logs.

Best way around it is as you noted above, drop a `favicon.ico` file in the root of your site. As this is more of a web dev thing than a responsibility of the theme I don't feel it's necessary to include. It's not going to break anything if you leave it out.

**Comment by The-K-Man** [comment]
nice

**Comment by Venkat-Rajgopal** [comment]
Thank you for the explanation.

**Comment by dkambam** [comment]
Looks like WEBrick is replaced by 'Thin' 
https://stackoverflow.com/questions/3802913/error-errnoeconnreset-connection-reset-by-peer
