### ISSUE TITLE
RTL layout for fa-IR and ar-AR localisations

### ISSUE THREAD

**Issue by srezasm** [mmistakes/minimal-mistakes#3903]
### What happened?

- Minimal Mistakes version: 4.24.0
- Ruby gem or remote theme version: Any
- Jekyll version: 3.9
- Git repository URL: https://github.com/srezasm/blog
- Hosted on GitHub Pages (if yes provide URL to site): https://srezasm.github.io/blog/
- Operating system: Linux

### Expected behavior

The theme must adjust to the RTL layout by choosing a right-to-left language localization like fa-IR and ar-AR

### Steps to reproduce the behavior

1. Cloned the main repo
2. Configured the GitHub pages settings

**Comment by srezasm** [comment]
Here you can see a RTL post example: https://srezasm.github.io/blog/rtl/rtl-post

I changed every "right" with "left" and vice versa in the inspector > sources > main.css and added `direction: rtl` to the body element and here is the result:
![screencapture-srezasm-github-io-blog-rtl-rtl-post-2022-09-10-18_38_39](https://user-images.githubusercontent.com/45644975/189487131-740e4ac9-67a2-4d67-9662-37ec876abe6e.png)

**Comment by N013M** [comment]
can you tell me how did you do it?

**Comment by srezasm** [comment]
> can you tell me how did you do it?

Here is the link to my RTL fork:
https://github.com/srezasm/minimal-mistakes-rtl

**Comment by iBug** [comment]
Implemented in #4886.
