### ISSUE TITLE
How to create multiple authors? 

### ISSUE THREAD

**Issue by xinghengwang** [mmistakes/minimal-mistakes#392]
There would be several people contributing to this blog. 
I love the author section. but I don't know if there is a way to support multiple authors? 

Thanks

- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** 

---

**Comment by mmistakes** [comment]
Have you looked over the thrme's documentation?

https://mmistakes.github.io/minimal-mistakes/docs/authors/

There's an example post to showing how to assign an alternate author. 

https://mmistakes.github.io/minimal-mistakes/layout-author-override/

**Comment by xinghengwang** [comment]
sorry, missed that part. Thanks.
