### ISSUE TITLE
Images not showing on single layout

### ISSUE THREAD

**Issue by bmenicucci** [mmistakes/minimal-mistakes#393]
Hello Michael,
I've found your theme very nice and "minimal", so I decided to use it and customize it to my needs to move from wordpress to a new jekyll website; you can see the draft heading to https://bmenicucci.github.io

However, I'd like to ask you the following:
1. It seems I'm unable to have images showing on a page with "single" layout. If I change the layout to "splash" it works 
2. I decided to start with a splash index.md instead of a list of posts; that's fine, as you can see, but I haven 't been able to change the page title that I would change to one of my choice 

Am I missi gli something?
Thanks a lot in advance and keep up this very good work!
Brunello

- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** 

---

**Comment by mmistakes** [comment]
For the missing images on a single page do you have an example of one not working? What sort of images? The hero image? Markdown images in the body? If you inspect the elements what are the file paths? My guess is that's wrong or you need to prepend them with `{{ site.url }}` so they correctly resolve. But without seeing an example it's hard for me to speculate.

Here's a few image examples (using `layout: single`) if you want to see how I'm doing things to compare against.

| Demo page | Source |
| ---------------  | ---------------------- |
| [Header Image Overlay](https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-overlay-image/) | [Markdown](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_posts/2012-03-15-layout-header-overlay-image.md) |
| [Header Image Horizontal](https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-image-horizontal/) | [Markdown](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_posts/2012-03-15-layout-header-image-horizontal.md) |
| [Post Image (Standard)](https://mmistakes.github.io/minimal-mistakes/post%20formats/post-image-standard/) | [Markdown](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_posts/2010-08-05-post-image-standard.md) |
| [Another Post with Images](https://mmistakes.github.io/minimal-mistakes/markup-more-images/) | [Markdown](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_posts/2013-05-22-markup-more-images.md) |

As far as the page title. Those work slightly different for the "home" page. There's some logic in there for SEO purposes and tries to do some smart things. You can modify that if you need to, it's all in [`_includes/seo.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/seo.html).

**Comment by bmenicucci** [comment]
Hello,
first of all, thank for your prompt reply!
The page "visione-sistemica.md" is just an example: I set it up as follows:

---
layout: single
title: La Visione Sistemica
permalink: /visione-sistemica/
header:
  overlay_color: "#000"
  overlay_filter: "0.3"
  overlay_image: yin-yang.jpg
sidebar: 
  nav: moreontls
category: Theory Of Constraints
tag: management
---

and, putting in 

{% if page.header %} "True!" {{ page.header.overlay_image }} {% endif %}

I get "True!" and "yin-yang.jpg" but using the Chrome "inspect" tool I don't see any reference to the image!

about.md is another example: hereafter the YAML section, where I tried to address the image prepending the name with /images/:
---
layout: single
title: About Us
permalink: /about/
header:
  image: /images/about-us.jpg
sidebar: 
  nav: chisiamo
vimeoid: 136204836
category: About us
tag: M&A
---

**Comment by mmistakes** [comment]
Looking really quick it looks like you've modified `single.html` layout. It's completely missing this:

```
{% if (page.header.overlay_color or page.header.overlay_image) or page.header.image %}
  {% include page__hero.html %}
{% endif %}
```

Which is the part of the code that brings in the hero images. It's in `splash.html` but looks like you removed it from single. There could potentially be other changes you've made that broke something. I'd suggest comparing your modified `_layouts` against the default ones and see where things went wrong.

**Comment by bmenicucci** [comment]
Ooops! Don't know why but... you're absolutely right! Now it works like a charm ;)
Again, thanks a lot for your support and for sharing your beautiful themes

**Comment by mmistakes** [comment]
Glad that solved it.
