### ISSUE TITLE
navigation links sidebar overlays main body text on small screens

### ISSUE THREAD

**Issue by casa-albore** [mmistakes/minimal-mistakes#396]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Expected behavior

navigation sidebar either disappears when screen too narrow or scrolls away as the page is scrolled, does not overlay text from main page

## Steps to reproduce the behavior

Visit the below page on a smaller width screen and scroll down a little:

   https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

The navigation sidebar text overlays the main text.

I'd personally prefer the navigation text to be hidden when the screen is too narrow (navigation is possible from elsewhere anyway)...

**Comment by mmistakes** [comment]
Can you attach a screenshot of the overlap? I'm not seeing it.

**Comment by casa-albore** [comment]
here's a screenshot with chrome/mac:

<img width="936" alt="screen shot 2016-07-14 at 08 00 03" src="https://cloud.githubusercontent.com/assets/19647567/16829559/64ca0d30-4999-11e6-8c5f-a0858d06a923.png">

The same issue occurs on my android phone. It doesn't reproduce on firefox/mac or safari/mac

**Comment by mmistakes** [comment]
Ah yeah I see it. It's related to a pull request @ZenHarbinger submitted to cleanup the sidebar https://github.com/mmistakes/minimal-mistakes/commit/c3e2272a6f6a611c6cf684f1dbfa2ee95c7b387c

There's a [bit of JavaScript](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/_main.js#L14) in there that's probably not triggering properly on the custom sidebar shown in the Documentation section of the site.

Definitely a bug.

**Comment by ZenHarbinger** [comment]
My bad, I guess there isn't always an author's button and it needs a hard width value.  I can see if a better condition can be found.

At least I'm assuming that this situation doesn't have the author button.

I'll look at it when I get a chance.

**Comment by mmistakes** [comment]
Sounds good. Thanks @ZenHarbinger

**Comment by ZenHarbinger** [comment]
How do you generate your minimized javascript?

**Comment by mmistakes** [comment]
@ZenHarbinger Through a [`npm` script](https://github.com/mmistakes/minimal-mistakes/blob/master/package.json#L34) that pipes it through UglifyJS.

Docs: https://mmistakes.github.io/minimal-mistakes/docs/javascript/

**Comment by ZenHarbinger** [comment]
Awesome, one thing, can you update the page; I instead of
```sh
npm build:js
```
it's
```sh
npm run build:js
```

at least it is for node 6.3, if it's still that for 4.x, nevermind.
That is all, I'm working on this as we speak.

**Comment by mmistakes** [comment]
Good catch. It's a typo I missed.
