### ISSUE TITLE
Layout broken on Chrome

### ISSUE THREAD

**Issue by MeoBeoI** [mmistakes/minimal-mistakes#397]
- [x ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

![Imgur](http://i.imgur.com/Ngt1Qbc.png)

## Environment informations
- OSX 10.11.5
- Chrome Version 51.0.2704.106 (64-bit)

## Expected behavior
- Not broken 😅

## Steps to reproduce the behavior

- Access : [https://mmistakes.github.io/minimal-mistakes/docs/layouts/](https://mmistakes.github.io/minimal-mistakes/docs/layouts/) on Chrome
- Resize window

**Comment by mmistakes** [comment]
Closing. Duplicated of #396
