### ISSUE TITLE
Trying to change layout

### ISSUE THREAD

**Issue by jimtryon** [mmistakes/minimal-mistakes#399]
- [X] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

  Please include theme version, `github-pages --version`, and the operating system you are on or tested with.

Mac OS X 10.11
Atom 1.9
github-pages 87

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** 

---

## Expected behavior

  Describe the intended output or what you expected to see.

## Steps to reproduce the behavior

  Include a link to a public repository or ZIP file so that they can more easily be reproduced. Being able to see your actual files helps troubleshooting as most issues stem from missing YAML Front Matter, a mis-configured `_config.sys` file, or `_posts` content. 

  Describe the steps you took for this problem to exist. Such as you cloned the theme, customized `_config.yml`, added your own posts, and started up a Jekyll server locally.

  If an error occurred on GitHub Pages when pushing, please build locally and provide a complete log by running `bundle exec jekyll --trace --verbose` and including this output in the filed issue.

  Screenshots can also be included if they help illustrate a behavior.

I've added the following lines to my _config.yml to change the layout from default to single using a Front Matter defaults.

```
defaults:
  -
    scope:
      path: "" # an empty string means all files in the project
    values:
      layout: single   
```
  I then stop any server that is running and issue the commands:
 **bundle exec jekyll build && bundle exec jekyll serve**  and when I check localhost, nothing is updated.  I also changed single to "single" in case it is a quoted string and .

**Comment by mmistakes** [comment]
If you have a layout set in your posts/pages YAML it will override whatever is set as a default in `_config.yml`. 

Can you confirm if that is the case? If so either change every occurrence to `layout: single` or remove them so the defaults can take precedence.

**Comment by jimtryon** [comment]
There was a layout set in some of the posts/pages.  I changed every occurrence to layout: single and could not get the default to take precedence.  I've started with a new site.

**Comment by mmistakes** [comment]
Front matter defaults will never take precedence if there are values in the actual post/page's YAML Front Matter. Take a look at Jekyll's docs, it explains how it's suppose to work and what overrides what.

https://jekyllrb.com/docs/configuration/#front-matter-defaults
