### ISSUE TITLE
Limitation in the no of images in gallery 

### ISSUE THREAD

**Issue by adrianbradu** [mmistakes/minimal-mistakes#402]
I like the gallery helper; However it looks like it is properly working with a maximum 9 of images in the gallery. So far the solution for this is to greate gallery1 and gallery2 in the YAML Front Matter then: 
```
{%include gallery id="gallery1"%}
{%include gallery id="gallery2"%}
```
Is there any way to sort out this?
Thanks a lot

**Comment by mmistakes** [comment]
Do you have an example of a gallery > 9 images that isn't working? To my knowledge there's nothing in the `gallery` include's Liquid that is enforcing any sort of maximum amount of images.

**Comment by mmistakes** [comment]
Looking at this closer appears there's a bug with some of my Liquid. Stay tuned for a fix...
