### ISSUE TITLE
Google AdSense support

### ISSUE THREAD

**Issue by gyandeeps** [mmistakes/minimal-mistakes#404]
First, Thanks for the great web template. :+1: 

Based on the `3.3.3` release, I have been using this template on my website [here](http://gyandeeps.com/)
I can see the `_config.yml` file has a spot for google ad id information [here](https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml#L59-L61) but its not getting used any where.

Am i missing something here or is this functionality not available?

**Comment by mmistakes** [comment]
Nope you're not missing anything. Those were just placeholders that I didn't end up using and forgot to remove. Adsense works just fine without it. Simply copy/paste the script code Google gives you into a `layout` or `include` where you want it to appear.

For the theme's demo site I dropped it in right [above the footer](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_layouts/default.html#L21) if you want to see a live example.

**Comment by gyandeeps** [comment]
In the previous version, it used to put the ads for you. Do you think its should do it now also?

**Comment by mmistakes** [comment]
With this newer version there are custom `head` and `footer` includes so you can copy/paste in AdSense scripts (and other things).

- [`_includes/footer/custom.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/footer/custom.html)

I found that's more flexible. Simply take the script Google gives you after setting up your ad unit and paste it into `footer/custom.html`, in `default.html` layout (as I've done with the demo site), or anywhere else you'd prefer ads to appear.

If you check out the demo site (`gh-pages` branch) you can see how I handled it, using the responsive ad unit. These tend to work better with the theme since they adapt to various screen sizes (mobile, tablet, etc.) without overflowing the parent container.

```html
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <div align="center" style="margin: 1em 0;">
    <ins class="adsbygoogle"
         style="display:block; border-bottom: initial;"
         data-ad-client="ca-pub-7328585512091257"
         data-ad-slot="3049671934"
         data-ad-format="auto"></ins>
    </div>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
```

**Comment by DeveloperPaul123** [comment]
@mmistakes Is [this](https://github.com/mmistakes/minimal-mistakes/issues/404#issuecomment-235431889) still the way to do it if you're using minimal mistakes as a remote theme?

**Comment by mmistakes** [comment]
@DeveloperPaul123 Yes.

**Comment by fredrikj31** [comment]
@mmistakes If I use the remote theme, how do I add content to the custom header file, when I have no access to the _layout folder when using the remote theme? Is there something I have missed?

**Comment by mmistakes** [comment]
@fredrikj31 https://jekyllrb.com/docs/themes/#overriding-theme-defaults

**Comment by fredrikj31** [comment]
> @fredrikj31 https://jekyllrb.com/docs/themes/#overriding-theme-defaults

Ohhh thanks. I think I had overseen that on the docs. Thanks a lot

**Comment by cortix** [comment]
> With this newer version there are custom `head` and `footer` includes so you can copy/paste in AdSense scripts (and other things).
> 
> * [`_includes/footer/custom.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/footer/custom.html)
> 
> I found that's more flexible. Simply take the script Google gives you after setting up your ad unit and paste it into `footer/custom.html`, in `default.html` layout (as I've done with the demo site), or anywhere else you'd prefer ads to appear.
> 
> If you check out the demo site (`gh-pages` branch) you can see how I handled it, using the responsive ad unit. These tend to work better with the theme since they adapt to various screen sizes (mobile, tablet, etc.) without overflowing the parent container.
> 
> ```
>     <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
>     <div align="center" style="margin: 1em 0;">
>     <ins class="adsbygoogle"
>          style="display:block; border-bottom: initial;"
>          data-ad-client="ca-pub-7328585512091257"
>          data-ad-slot="3049671934"
>          data-ad-format="auto"></ins>
>     </div>
>     <script>
>     (adsbygoogle = window.adsbygoogle || []).push({});
>     </script>
> ```


When I tested my website on my old laptop(15.6 inc), I noticed that the design of the sidebar with the google ad was slightly distorted. When I remove the google ad from the sidebar, the problem goes away. I did what you said but the problem still persists. You can see the screenshots below.

I tested my website on google, safari and opera;

chrome : 108.0.5359.125 (64 bit)
firefox : 108.0.1 (64 bit)
opera:  version 94.0.4606.38

![hasancelik org-1](https://user-images.githubusercontent.com/6178404/208682226-4b8da48b-8ff1-499c-a3c0-aced3183ad20.png)
![hasancelik org-2](https://user-images.githubusercontent.com/6178404/208682230-bdb37e18-2a53-4972-81de-63f3c701caad.png)
