### ISSUE TITLE
Highlight color for TOC in the dark skin 

### ISSUE THREAD

**Issue by vogella** [mmistakes/minimal-mistakes#4100]
### What happened?

- Minimal Mistakes version: latest

If I enable a toc in the `minimal_mistakes_skin: "dark"` it is not readable.

Screenshot:

![Screenshot from 2023-01-15 21-28-45](https://user-images.githubusercontent.com/139910/212565536-cae0b27e-c39f-4db8-a6b8-f3746f9498bf.png)

Example Font matter:

```
---
layout: single
title: Gruppen im Larp
permalink: /gruppen/
toc: true
toc_label: Übersicht
toc_sticky: true
---
```

This is more a FYI, it is not a super bad rendering issue but I really like your theme and as an OS person myself (https://projects.eclipse.org/user/1168), I consider bug reports as a sign of respect.

Feel free to close in you don't think this is worth an action on your side.

### Expected behavior

The highlighted text should still be readable.

### Steps to reproduce the behavior

Use 

```
---
layout: single
title: Gruppen im Larp
permalink: /gruppen/
toc: true
toc_label: Übersicht
toc_sticky: true
---
```

And configure

```
minimal_mistakes_skin: "dark"
```

**Comment by vishalsingh2972** [comment]
@vogella can you assign this to me if this issue is still open?
