### ISSUE TITLE
other content styling in the archive layout

### ISSUE THREAD

**Issue by rubinovk** [mmistakes/minimal-mistakes#414]
- [X] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [X] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: v.3.3.6** 
- **`github-pages` or `jekyll` gem version: 89** 
- **Operating system: OSX** 

---

Currently `archive` layout seems to be capable to display only list/grid views of posts. Although it is said that `archive` is essentially the same as `single` layout, there is no coherent styling when adding *other* content to the `archive` layout. 

For instance, if adding to the archive page a paragraph of text with links, the links won't be rendered in color as in the `single` layout.

Is this a limitation of the `archive` layout? Can it be overcome with css or other changes?

Thank you!

**Comment by mmistakes** [comment]
Not exactly sure I follow what you're asking.

If you set a page with the archive layout using `layout: archive` and add content to that like you would in any other post or page, it should similar styling as the `single` layout. All of the CSS styles for main content apply across the layouts.

For example this test page [`_pages/archive-layout-with-content.md`](https://raw.githubusercontent.com/mmistakes/minimal-mistakes/gh-pages/_pages/archive-layout-with-content.md) has a bunch of sample Markdown content in the body and then following it is Liquid loop to show an index of all pages.

As you can see all the styling is exactly the same as `single`
https://mmistakes.github.io/minimal-mistakes/archive-layout-with-content/, with the exception of metadata, next/previous links, and a few other things that aren't part of the archive layout.

Do you have an example of the page you're trying to build that is using `archive` and giving you problems? Perhaps you have it saved as a `.html` file. If that's the case and you didn't write your content in HTML then that could be why all the styling looks off. 

To parse the content as Markdown the file needs to be `.md` or `.markdown`, which will output the correct HTML.

**Comment by rubinovk** [comment]
Great clarification. In my case I have `.md` file, so it's not the reason.

Perhaps I was too fast to conclude that `archive` layouts are limited after observing non-colored hyperlink. However, these two screenshots can highlight the difference in the formatting between a normal `single` post https://mmistakes.github.io/minimal-mistakes/markup/markup-html-tags-and-formatting/ :

![screen shot 2016-08-04 at 10 33 56](https://cloud.githubusercontent.com/assets/2063487/17395604/a10267b0-5a2f-11e6-943b-ff26fd0a09e9.png)
(Notice smaller font in this list and a colored hyperlink)

and the `archive` example you have generated https://mmistakes.github.io/minimal-mistakes/archive-layout-with-content/ :

![screen shot 2016-08-04 at 10 30 28](https://cloud.githubusercontent.com/assets/2063487/17395619/bd5892ae-5a2f-11e6-90b4-98f6079f2c0e.png)
(Notice bigger font and a non-colored hyperlink)

There are few more differences, e.g. no horizontal line after `## Header two` headers, different left alignment at `Steve Jobs ... `. 

Other than that--indeed--all other elements show up correctly.

**Comment by mmistakes** [comment]
I see what you're saying now.

A few of these are because `single` has the content wrapped in `section.page__content` which applies a few other styles that aren't present in `archive`.

The unstyled links on the other hand are due to the color and underline being removed specifically for an archive list. You could remove that in the CSS if you want to keep the same styling.

```css
.archive a {
    color: inherit;
    text-decoration: none;
}
```

The `archive` layout was designed more for indexes and listing of posts/pages/collections with some really light intro content. Removing overrides in the CSS on links and adding the content wrappers from `single` into `archive` would help you harmonize the too if that's what you're trying to achieve.

**Comment by rubinovk** [comment]
The distinction is quite clear now. Somehow I expected the same exact behavior for the content part and a specific `archive` styling for the included archive items.
Thanks!

**Comment by mmistakes** [comment]
To expand further there's nothing stopping from you from using a hybrid approach.

If you want to use `archive` layout and have the main content styling (with the exception of the link color since that's overridden by `.archive`) you could wrap the content like so.

```liquid
---
layout: archive
---

<!-- wrap your post content and include markdown="1" so Kramdown process the MD inside -->
<section class="page__content" itemprop="text" markdown="1">
  ... your markdown here
</section>

<!-- your archive loop -->
{% include base_path %}
{% for post in site.pages %}
{% include archive-single.html %}
{% endfor %}

<!-- another block of content if you want -->
<section class="page__content" itemprop="text" markdown="1">
  ... your markdown here
</section>
```

There's also nothing stopping from you using the `single` layout and including an archive listing. The links will be colored and the spacing is off because of how the `.page_content` styles cscade down. But they could be overridden if with custom CSS depending on what you're looking for.

```liquid
---
layout: single
---

Your markdown content here.

{% include base_path %}
{% for post in site.pages %}
{% include archive-single.html %}
{% endfor %}
```

![single-archive](https://cloud.githubusercontent.com/assets/1376749/17401864/0b90433e-5a1e-11e6-8bd3-96af60cdbfd3.jpg)

I'm not sure if this covers exactly what you're wanting since you didn't share an example. The styles are going to be off here and there just because of how the cascade works. The archive modules aren't completely modular and will inherit styling depending on where they are placed.

**Comment by rubinovk** [comment]
Sorry I don't have examples to share because I am still organizing the content. I think you have understood my intention quite well in your example. To put it simply, I want to have an `archive` page that first introduces a couple of other pages of my site on a given topic, and then lists posts from a given category. 
However, as you pointed out, in the first solution the links are sort-of invisible without coloring, while in the second (`single` with an archive) IMHO the look is not as perfect as in the original `archive` style. For now I'll try to restructure the content and will be looking for a 3rd solution in the meantime.
Thanks for your time

**Comment by rubinovk** [comment]
Hi Michael, so I worked on the solution and stepped on what looks like a bug:

As you suggested in [your comment](https://github.com/mmistakes/minimal-mistakes/issues/414#issuecomment-237539217) one should be able to add content before and __after__ the archive loop. 

The __after__ one does not work for me when using `grid_wrapper`, the content under overlaps the grid (see screenshot attached). The normal non-`grid_wrapper` case works.

![screen shot 2016-08-05 at 14 56 31](https://cloud.githubusercontent.com/assets/2063487/17437467/2b6adcfe-5b1e-11e6-9edc-e93d19b15a7f.png)

Another issue I noticed only now, is that the width of the content in `archive` layout is bigger than that of single layout (and it does not react to adding `<section class="page__content" ... ` wrapper nor `<div class="page__inner-wrap">` around `page__content`).

What would be your ideas?

**Comment by mmistakes** [comment]
Can you create a sample repo on GitHub so I can reproduce the issue and debug.

I'm pretty sure it's a CSS `float` issue and the content needs to be cleared so the overlap doesn't happen. But it's hard to troubleshoot from a screenshot alone.

The theme includes a clearfix class `.cf` that you can try wrapping the archive listing with and possibly the content that displays after it. But I think if you clear the listing that should be enough.

Something like:

```html
Content before

<div class="cf">
... archive listing ...
</div>

Content after
```

**Comment by rubinovk** [comment]
Unfortunately `.cf` doesn't work.

Have a look, here's the visual: https://rubinovk.github.io/mmistakes/research/
and here's the code: https://raw.githubusercontent.com/rubinovk/mmistakes/gh-pages/_pages/research.md

**Comment by mmistakes** [comment]
Works for me putting the clearfix on `<section class="page__content cf">` that appears after the listing instead.

![cf](https://cloud.githubusercontent.com/assets/1376749/17438371/7cdbd8f0-5af0-11e6-8370-72c7b0d9a529.jpg)

**Comment by rubinovk** [comment]
It does, thanks! 

The more we are in this issue, the more tweaks are being applied. If I'm the only one to enrich `archive` layout with additional content, then it's OK. However, if more people are to use it, then I believe this layout should be more "other-content"-friendly, just as your other theme features are clean and straightforward.
