### ISSUE TITLE
Archive page subtitles be surrounded by <code> mistakenly

### ISSUE THREAD

**Issue by hijiangtao** [mmistakes/minimal-mistakes#415]
I used the latest release version to generate my blog, and use [year-archive.html](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_pages/year-archive.html) in your repo's gh-pages branch to generate my /archive page.
It is supposed that the subtitle of year, such as **2016** should be like the appearance in your website [archive by year](https://mmistakes.github.io/minimal-mistakes/year-archive/), but when I `jekyll s` it locally, it is surrounded by `<code>` tag mistakenly. And the only thing I did is rename the year-archive.html to year-archive.md, I am wondering if there is some modifications in the latest release version that influence the generation of this page. I also tried tag-archive.html and category-archive.html in _pages folder, but it runs normally without the `<code>` tag surrounded.
Picture shows below.

![image](https://cloud.githubusercontent.com/assets/4990015/17409182/a92c88f0-5aa0-11e6-9511-1d6805aab78d.png)

Best.

**Comment by mmistakes** [comment]
What's going on is when you changed the page from `.html` to`.md` it's telling Jekyll to process the page as Markdown.

Since there is an indent in the code around the subtitle it's being converted into a `<code>` block. If you remove the indents it should process correctly.

```liquid
{% include base_path %}
{% capture written_year %}'None'{% endcapture %}
{% for post in site.posts %}
{% capture year %}{{ post.date | date: '%Y' }}{% endcapture %}
{% if year != written_year %}
<h2 id="{{ year | slugify }}" class="archive__subtitle">{{ year }}</h2>
{% capture written_year %}{{ year }}{% endcapture %}
{% endif %}
{% include archive-single.html %}
{% endfor %}
```
