### ISSUE TITLE
RSS feed no longer generated

### ISSUE THREAD

**Issue by Vel0x** [mmistakes/minimal-mistakes#417]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.3.6
- **`github-pages` or `jekyll` gem version:** 89 (github-pages)
- **Operating system:** Ubuntu 14.04

---

## Expected behavior

Feed.xml (or whatever is in `atom_feed.path`) is generated automatically like it used to be. 

## Steps to reproduce the behavior

Simply build as normal.

**Comment by mmistakes** [comment]
feed.xml is generated with the [Jekyll Feed plugin](https://github.com/jekyll/jekyll-feed) so make sure that's properly working and installed. The bit in `_config.yml` is only there to set the feed path that appears in [`<head>`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/head.html#L7) and has nothing to do with generating the actual feed.

If you have a public repo I can give you a better idea of what could be setup wrong.

**Comment by mmistakes** [comment]
Uncommented the `gems` lines in `_config.yml` and the feed should generate again. Gems added to the Jekyll plugin group in a `Gemfile` are suppose to be autoloaded so you don't need to specify them under `gems:` in the config. But looks like that's not working with the feed plugin.

```yaml
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
```

**Comment by Sciss** [comment]
I'm having this problem, I don't know what's going on. I checked `bundle install` and it lists

    Using jekyll-feed 0.9.2

And in `_config.yml` I do have the defaults:

    plugins:
      - jekyll-feed
      ...

But there is no `feed.xml` generated in `_site`. Any ideas?

**Comment by Sciss** [comment]
So I browsed a bit, saw [this](https://github.com/jekyll/jekyll-feed/issues/183) and got the idea that I should use `gem` instead of `plugins`. So I added

    gems:
      - jekyll-feed

Now it works. What is the difference between `plugins` and `gems`?

**Comment by mmistakes** [comment]
Both should work. There was an update to Jekyll a few releases (I forget which version) ago that changed `gems` to the more semantic `plugins`. 

`plugins` is suppose to be backwards compatible but maybe you're using an older version of Jekyll?

**Comment by mmistakes** [comment]
As per their docs

> ⚠️ If you are using Jekyll < 3.5.0 use the `gems` key instead of `plugins`.

Smells like your on an older version of Jekyll.

**Comment by Sciss** [comment]
Hmmm. No it's Jekyll 3.7.0. Strangely it outputs this warning when serving:

> Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.

Nevertheless, if I use plugins and no gems, the feed.xml disappears. Perhaps it's a bug in the plugin.

**Comment by mmistakes** [comment]
You're using Bundler correct (eg. `bundle exec jekyll serve`)? What versions of Jekyll and jekyll-feed are in your `Gemfile.lock`

That'll tell you really quick what versions of the gems you're using and verify you're on the latest.

**Comment by Sciss** [comment]
Yes, `bundle exec jekyll server`. Here is the contents of `Gemfile.lock`: https://gist.github.com/Sciss/672703625f3067741c4d3ee9ac4feca4

Looks all normal to me? Although I don't understand yet, why the gems have to be specified twice, once in `minimal-mistakes-jekyll.gemspec` and the second time in `_config.yml`.

**Comment by mmistakes** [comment]
Yeah looks fine to me.

In my experience plugins are inconsistent with theme gems. I have no idea if it's gotten better with later releases or if it's up to the plugin to autoload. I err on the side of caution and just add them all to the `plugins` in _config.yml
