### ISSUE TITLE
site.github  certificate verify failed.

### ISSUE THREAD

**Issue by BruceZhaoR** [mmistakes/minimal-mistakes#418]
- [x] This is a question about using the theme.
- [ ] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:3.3.6** 
- **`github-pages` : 84** 
- **Operating system:Win 10** 

```bash
$ JEKYLL_GITHUB_TOKEN=7d733604e9899a94a36b7d96676b40f936c1c7b0 bundle exec jekyll serve
Configuration file: C:/Users/Bruce/Documents/Github/blog/_config.yml
            Source: C:/Users/Bruce/Documents/Github/blog
       Destination: C:/Users/Bruce/Documents/Github/blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed in _includes/head.html, included in _layouts/default.html
jekyll 3.1.6 | Error:  SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

**Sorry bothering you, I am a noob in ruby or jekyll.** I want to use the latest version ,but I encountered the new problem. I've tried the ways I known and even searched the stackoverflow. I appreciate it if you can give me some instructions. Thanks in advance!

**Comment by mmistakes** [comment]
Perhaps this thread will be helpful. I don't think the error is theme related.

https://github.com/jekyll/jekyll/issues/3985

**Comment by BruceZhaoR** [comment]
Thanks a lot! :blush:

**Comment by ceefour** [comment]
Also got this too on Windows 10. The other thread doesn't help.

**Comment by mmistakes** [comment]
@ceefour Looks to be related to the jekyll-gist gem. Please file an issue upstream as I don't control that gem.

- https://github.com/jekyll/jekyll-gist/issues/30

**Comment by ceefour** [comment]
@mmistakes as I mentioned before Tried commenting jekyll-gist in _config.yml but didn't work.

So it's probably a similar root cause , that still happens without jekyll-gist.

**Comment by mmistakes** [comment]
@ceefour That said the issue isn't theme related. It's something with either your Ruby environment, the Jekyll gem, one of its dependencies, or a combination of these. You'll have to look for help there.

Only other thing I can think of is you're using `github-pages` gem in `Gemfile`, which autoloads the Jekyll Gist gem regardless if you comment it out or not. Try replacing with `gem "Jekyll"`, then `bundle update`, then `bundle exec jekyll serve`.

Other than that I can't really offer any other advice or help. You're better off hoping someone from the core Jekyll team or one of its plugin maintainers comes up with a fix. Windows and Jekyll are known to have issues. Well rather Ruby and Windows,

**Comment by BruceZhaoR** [comment]
@ceefour  Maybe you can try delete the https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/seo.html#L7 .  It worked fine on my site https://github.com/BZRLC/bzrlc.github.io/blob/master/_includes/seo.html#L7 . Just a advice, don't know if it work on your site.

**Comment by ceefour** [comment]
@BruceZhaoR You're a genius! That line is the culprit:

```
{% assign seo_url = seo_url | default: site.github.url %}
```

Curiously, I don't see **any** mention of `github.url` in `_config.yml`. Probably a bug?

**Comment by mmistakes** [comment]
Not a bug @ceefour, that's related to the [`github-metadata`](https://github.com/jekyll/github-metadata) plugin. I was going to suggest it but seemed more tied to `jekyll-gist` so I didn't. When you push your site to GitHub it uses that plugin to automatically set `site.github.url` for you.

You'll get all kinds of other Liquid errors if you don't [properly configure it](https://github.com/jekyll/github-metadata#authentication) to. That's why I suggested you switch from using the GitHub Pages gem to vanilla `gem "jekyll"` in the `Gemfile` as it won't use the GitHub Metadata plugin.

Usually all you need to do is add `repository: username/repo-name` to your **_config.yml** and the error will go away.

Give that plugin docs a read over. It tells you how to set things up so it properly authenticates. If that doesn't work you might have encountered a bug and if so file an issue with them.

**Comment by ceefour** [comment]
Wait, so the best practice is to use `gem "jekyll"` instead of `github-pages` gem ? This seems contradictive with the minimal-mistakes defaults _and_ what GitHub itself suggests.

BTW I did have `repository: username/repo-name` in my `_config.yml` from the start.

**Comment by ceefour** [comment]
Commenting github-pages gem and using just jekyll gave me:

```
C:\Users\ceefour\git\matagaruda.github.io>bundle exec jekyll serve
Configuration file: C:/Users/ceefour/git/matagaruda.github.io/_config.yml
Configuration file: C:/Users/ceefour/git/matagaruda.github.io/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.3.0 | Error:  jekyll-paginate
```

**Comment by mmistakes** [comment]
It depends on where you're hosting. If you hosting with GitHub Pages then you'll want to use `gem "github-pages"` as it uses versions of Jekyll and its dependencies that mirror how GH Pages..

If you're self hosting then use `gem "jekyll"` as it gives you the more recent version.

I don't know all the intricacies of how `github-metadata` works, but I know i've come across all kinds of similar authentication errors if things are configured correctly on Windows. Like I said usually setting `repository` is enough, but there are some other options you may need to do.

Reach out to the maintainers of that repo for further help. Entirely possible you hit a legit bug. I can't say either way as I have no involvement with that gem/plugin.

**Comment by mmistakes** [comment]
@ceefour If you switch to `gem "jekyll"` you'll need to add all the gems/plugins to your `Gemfile`. `github-pages` has `jekyll-paginate`, `jekyll-sitemap`, `jemoji`, etc. as dependencies so they come along for the ride. Otherwise you'll get those error (which tells you exactly how to solve the problem).

This is all documented.

> The [GitHub Pages](https://github.com/github/pages-gem) gem installs additional dependencies that may need to be added to your Gemfile if you decide to remove the gem "github-pages".

Your `Gemfile` should look like this when using vanilla Jekyll:

```ruby
source "https://rubygems.org"

gem "jekyll"
gem "wdm", "~> 0.1.0" if Gem.win_platform?

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem " jemoji"
end
```

**Comment by ceefour** [comment]
Thanks @mmistakes , that works. And I see no more SSL errors even with the original `seo.html` .....
