### ISSUE TITLE
there is a error that can't fix "An error occurred while installing json (1.8.3)"

### ISSUE THREAD

**Issue by Ufinhub** [mmistakes/minimal-mistakes#4184]
### What happened?

- Minimal Mistakes version: 0.8.1
- Ruby gem or remote theme version: 3.0.2
- Jekyll version: 4.3.2
- Git repository URL:
- Hosted on GitHub Pages (if yes provide URL to site):
- Operating system:
- bundle exec jekyll build
- 

### Expected behavior

i just tried a lot of way it's just always stop on can't install json
no ideal why

### Steps to reproduce the behavior

Could not find json-1.8.3 in any of the sources
Run `bundle install` to install missing gems.
➜  myblog bundle install
Fetching gem metadata from https://rubygems.org/.Retrying dependency api due to error (2/4): Bundler::HTTPError Network error while fetching https://index.rubygems.org/api/v1/dependencies?gems=i18n%2Cjson%2Cminitest%2Cthread_safe%2Ctzinfo%2Cactivesupport%2Caddressable%2Ccoffee-script-source%2Cexecjs%2Ccoffee-script%2Ccolorator%2Cffi%2Cethon%2Cmultipart-post%2Cfaraday%2Cgemoji%2Cnet-dns%2Csawyer%2Coctokit%2Cpublic_suffix%2Ctyphoeus%2Cgithub-pages-health-check%2Csass%2Cjekyll-sass-converter%2Crb-fsevent%2Crb-inotify%2Clisten%2Cjekyll-watch%2Ckramdown%2Cliquid%2Cmercenary%2Crouge%2Csafe_yaml%2Cjekyll%2Cjekyll-coffeescript%2Cjekyll-feed%2Cjekyll-gist%2Cjekyll-github-metadata%2Cmini_portile2%2Cpkg-config%2Cnokogiri%2Chtml-pipeline%2Cjekyll-mentions%2Cjekyll-paginate%2Cjekyll-redirect-from%2Cjekyll-seo-tag%2Cjekyll-sitemap%2Cjemoji%2Cterminal-table%2Cgithub-pages
.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using i18n 0.7.0
Installing json 1.8.3 with native extensions

NoMethodError: undefined method `dir_mode=' for "/Users/evanhill/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/cache/json-1.8.3.gem":String
Using minitest 5.9.0
Using thread_safe 0.3.5
Using addressable 2.4.0
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using colorator 0.1
Installing ffi 1.9.14 with native extensions

NoMethodError: undefined method `dir_mode=' for "/Users/evanhill/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/cache/ffi-1.9.14.gem":String
Using multipart-post 2.0.0
Using gemoji 2.1.0
Using net-dns 0.8.0
Using public_suffix 1.5.3
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.11.1
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using jekyll-feed 0.5.1
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using jekyll-paginate 1.1.0
Using jekyll-sitemap 0.10.0
Using terminal-table 1.6.0
Using bundler 1.12.5
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

**Comment by iBug** [comment]
Likely your Ruby and Bundler version combination is too weird. <https://stackoverflow.com/q/66110828/5958455>
