### ISSUE TITLE
Social buttons to share post do not show up

### ISSUE THREAD

**Issue by StephenCavender** [mmistakes/minimal-mistakes#422]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.3.6
- **`github-pages` or `jekyll` gem version:** 3.1.6
- **Operating system:** Windows 10

---

## Expected behavior

Social buttons show up under 'Share On' text at the bottom of each post.

## Steps to reproduce the behavior

https://github.com/StephenCavender/stephencavender.github.io
1. Forked theme
2. Customized and created posts
3. Updated to 3.3.6

**Comment by mmistakes** [comment]
Same issue as #422, related to an ad blocker removing Font Awesome icons... which are used in the sidebar, footer, and social sharing buttons.

**Comment by StephenCavender** [comment]
Argh! Just installed ADP on Edge... Forgot I had it and it's not obvious on the UI... Sorry for the three extra false issues, but thx for the quick response time!

**Comment by mmistakes** [comment]
No problem. I've gotten this issue enough times now I know exactly what the problem is when it comes up. :smile:
