### ISSUE TITLE
A problem occured when github action was running

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [mmistakes/minimal-mistakes#4221]
### What happened?

- Minimal Mistakes version: 4.24.0
- Ruby gem or remote theme version: 3.3.7
- Jekyll version: 4.3.1
- Git repository URL: https://github.com/S-N-O-R-L-A-X/S-N-O-R-L-A-X.github.io
- Hosted on GitHub Pages (if yes provide URL to site): https://s-n-o-r-l-a-x.github.io/
- Operating system:

### Expected behavior

The deployment job shoud run well. But now it ran well in local but raised an error when github action was running, which said "Warning:  github-pages can't satisfy your Gemfile's dependencies.
/usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:84:in `rescue in gemspec': The minimal-mistakes-jekyll theme could not be found. (Jekyll::Errors::MissingDependencyException)"

### Steps to reproduce the behavior

1. Run `jekyll new ` to create a blog.
2. Use git remote to relate github and blog.
3. Install theme using Gem-based method.
4. Push the code to remote.

**Comment by clintjk** [comment]
I found that adding the faraday-retry gem to the gemfile fixed this issue:
```
gem 'faraday-retry', '~> 2.2'
```

**Comment by jupier** [comment]
I've been able to fix the similar issue with this documentation https://github.com/mmistakes/minimal-mistakes#remote-theme-method 😉
