### ISSUE TITLE
Include a way to download demo posts

### ISSUE THREAD

**Issue by stephenkoo** [mmistakes/minimal-mistakes#427]
- [x] This is a feature request.

Would love an option to download sample posts markdown displayed in the demo so I could quickly replicate functionality, especially for first-time Jekyll users.

Is there any way I can get them?

Thanks for the amazing theme Michael.

**Comment by mmistakes** [comment]
They're all in the [`gh-pages` branch](https://github.com/mmistakes/minimal-mistakes/tree/gh-pages). You can [download](https://github.com/mmistakes/minimal-mistakes/archive/gh-pages.zip) from there and then integrate the `_posts`, `_pages`, and `collections`. Just be sure to properly configure all the settings and front matter defaults in `_config.yml`.

Quickest way to get up and running would be to download the `gh-pages` branch and change titles, `url`, `repository` and a few other thinks specific to the demo site.

I've also broken the sample posts out into a different repo to be used in other themes for testing purposes.
https://github.com/mmistakes/jekyll-theme-unit-test

**Comment by stephenkoo** [comment]
Ah, I forgot I could check gh-pages. Silly me.

Thanks Michael!
