### ISSUE TITLE
Change width of feature_rows

### ISSUE THREAD

**Issue by jonbra** [mmistakes/minimal-mistakes#433]
- [X] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 3.3.7** 
- **`github-pages` version: 89 (haven't build locally yet)**
 
---

## Expected behavior
First of all let me thank you for this awesome template and great guide. I am playing around with customising the landing page, and I am trying to use your `index.md` file from `gh-pages`. I want to have two columns of text and I have used `feature_row:` for this, but I can't change the widths of these. The two columns are named **Research** and **Recent posts** on [https://jonbra.github.io/](https://jonbra.github.io/)

## Steps to reproduce the behavior

https://github.com/jonbra/jonbra.github.io
https://jonbra.github.io/

**Comment by mmistakes** [comment]
To do this you'll need to modify the stylesheet slightly. Currently `.feature__item`'s are laid out in 3 columns. If you change [this line](https://github.com/jonbra/jonbra.github.io/blob/master/assets/_scss/_archive.scss#L164)

```scss
@include gallery(4 of 12)
```

to `@include gallery(6 of 12)` they'll fill 50% of the parent container and appear as 2 columns.

It looks like you're on a slightly older version of the theme so it might be more work for you to update the stylesheet. You'll need to edit the `_scss` partial and then rebuild `main.css` using `npm run build:css`. [Archived instructions here](https://github.com/mmistakes/minimal-mistakes/blob/890a5e3eb2bf6716a217bcbebbb68a7b6c616e95/_docs/15-stylesheets.md#build-process).

The current version of the theme using native Sass/SCSS preprocessing so you just have to edit the file and Jekyll/GitHub Pages takes care of the rest.

**Comment by jonbra** [comment]
Thanks for the prompt reply!
Sorry if this is a very basic question, but is it possible to upgrade to the latest version of the theme using GitHub? I currently don't have the right access to run `bundle install` etc. on my computer so I can't install the theme locally.  I only have Git installed.

**Comment by mmistakes** [comment]
Not easily. Other than going through the [most recent commits](https://github.com/mmistakes/minimal-mistakes/commits/master) to the theme and editing your repo to match, it could be pretty painful.

Even if you can do things locally it's not the easiest thing as you'll have to pull down the theme's repo and manage some merge conflicts.

Jekyll just rolled out support for [`gem` themes](https://jekyllrb.com/docs/themes/) which will make all of this infinitely easier. You'll just add `theme: theme-name` in your Jekyll config and won't have to worry about managing outdated layouts, stylesheets, includes, etc.

I'll eventually be rebuilding the theme to support this, but [waiting on a few things](https://github.com/mmistakes/minimal-mistakes/issues/419) first:

- [GitHub Pages to support Jekyll `3.2`](https://github.com/blog/2220-github-pages-to-upgrade-to-jekyll-3-2)... coming August 23rd
- Jekyll themes to be updated to support bundling Javascript and other assets

**Comment by jonbra** [comment]
I see. Thanks for giving such detailed answers.
