### ISSUE TITLE
Search includes asset files

### ISSUE THREAD

**Issue by kslcsdalsadg** [mmistakes/minimal-mistakes#4418]
### What happened?

- Minimal Mistakes version: 4.2.4
- Ruby gem or remote theme version: 0.4.3
- Jekyll version: 3.9.3
- Git repository URL: robertoprubio.github.io
- Hosted on GitHub Pages (if yes provide URL to site): robertoprubio.github.io
- Operating system: ubuntu server 22.04-LTS

I have activated search at _config.yml:

[code]
search                   : true # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
lunr:
  search_within_pages    : true # true, false (default)
[/code]

a search button appeared at the top right but when I click then introduce a text, it search at posts and also at assets files.

### Expected behavior

Search only at posts

### Steps to reproduce the behavior

At robertoprubio.github.io click at the search icon at top right, then search for "v" (without quotion marks). A lot of "null" references appears, that refers to asset files.

![Screenshot](https://github.com/mmistakes/minimal-mistakes/assets/31618496/cb0640af-6771-4c54-81a4-42af910331b1)

**Comment by iBug** [comment]
I think this is fixed in #4000.
