### ISSUE TITLE
Not able to show posts

### ISSUE THREAD

**Issue by jonbra** [mmistakes/minimal-mistakes#456]
- [X] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 3.4** 
- **`github-pages` or `jekyll` gem version: 89** 
- **Operating system: OS X** 

---

## Expected behavior

Sorry for this silly question, but I am really puzzled here. I have three folders where I keep blog posts, talks and publications: `_posts`, `_talks` and `_publications`, and under `_pages` I keep different `archive.html` files for displaying these posts by date. I am linking to these posts using the `navigation.yml` and blogs and talks are displaying just fine, but publications I simply cannot show. If I change `{% for post in site.publications %}` in `publication-archive.html` to `{% for post in site.talks %}` the talks are displayed where I wanted to have publications, so the archive-file seem alright. 

## Steps to reproduce the behavior
https://github.com/jonbra/jonbra.github.io

**Comment by mmistakes** [comment]
Doesn't look like a theme issue.

`_talks` and `_publications` are collections. Looking at your `_config.yml` I only see that you setup [**talks**](https://github.com/jonbra/jonbra.github.io/blob/master/_config.yml#L164). You need to do the same for **publications** so Jekyll knows to build them.

Consult the [Jekyll collection docs](https://jekyllrb.com/docs/collections/) if you need more info.

**Comment by jonbra** [comment]
Yeah sorry, just found out I missed that in my config file.... Thanks for your time anyway
