### ISSUE TITLE
Staticman comments offset in 2.2.1

### ISSUE THREAD

**Issue by ryan-p-randall** [mmistakes/minimal-mistakes#457]
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 2.2.1

---

## Expected behavior

I expected the comment and comment form to each take up the entire width of the comments container. Instead, the comment and the new comment form currently each take up half the width of the comments container. I've tried mucking around with the scss myself, but I clearly don't understand the grid system well enough.  

It's _totally_ fair to respond with "I don't support 2.2.1 anymore—upgrading will fix this!" I'm just hoping that you might know a few lines that will fix this columns issue until I have time to update my whole site.  

In any case, thanks for adding Staticman! It's a great enhancement to the theme.    

## Example  

![comments](https://cloud.githubusercontent.com/assets/850915/17646149/7eb8ba18-617a-11e6-919e-06d3c9f9b4fa.png)  

Here's a [link to that post](http://ryanpatrickrandall.com/2016/wa-2016-week-31/), if that's somehow helpful.

**Comment by mmistakes** [comment]
Yeah think you're out of luck with this one :wink:. Looks like it's missing all of the form styling. When I added it to current version of MM I didn't touch the grid. 

It's likely inheriting styling in the old version that's messing with these layout. Or cancelling some styling out. Maybe try to debug the CSS with dev tools and compare against the latest MM. 

Might be something simple like change class named to avoid clashes.

**Comment by ryan-p-randall** [comment]
Okay, cool. Thanks for giving it a glance!

**Comment by mmistakes** [comment]
One quick fix you could do is change `<article>` in `_includes/comment.html` to `<div>`. It's inheriting some width styling from `#main article` used for the main content column.

That and if you pull in the SCSS I used in the current version to style things like `.comment__avatar-wrapper` and the form you should be in business.

**Comment by ryan-p-randall** [comment]
Thanks! I switched to `<div>` and added some of those style declarations to the 2.2.1 `page.scss`, and comments look great now.   

Much appreciated!!!
