### ISSUE TITLE
Interactive fig (svg/canvas) support?

### ISSUE THREAD

**Issue by zahachtah** [mmistakes/minimal-mistakes#460]
Hi, and thanks for this wonderful piece of code. I was wondering if there is a preferred way of displaying interactive javascript figures in MM & Jekyll. Typically one would have a div with some id and a javascript to make the figure. But is there a way to have this as an alternative to using a figure like image: fig.jpg and still be able to have these pretty layout options like feature rows etc?

Also, what is the best way to have page/post specific javascript code?

I am mostly thinking about [d3](https://d3js.org) or [jsxgraph](http://jsxgraph.uni-bayreuth.de/wp/index.html)

Any hints much appreciated!

Jon

**Comment by mmistakes** [comment]
Not sure on the preferred way to display them. You'll probably have to test adding them to the page and see how they look. I would think you'll need to make some CSS adjustments in the case they break the layout at all.

As far as adding page/post specific JavaScript, I can think of a few ways.
For anything that is common among the pages you could add something like to a layout:

```
{% if page.script %}
  <script src="the_script_path.js"></script>
{% endif %}
```

And then in each post/page you want that script to load add `script: true` to its YAML Front Matter. You could obviously name the `script` variable anything you want to carry more meaning.

And if you need to add something unique to each page you could just put that in the body of the post/page as an inline script:

```
<script>
 your script here
</script>
```

You could try and put the script in the YAML Front Matter if you wanted to keep it out of the main content, but I think that would be tricky as you'll have to deal with escaping quotes and apostrophes to properly capture it as a string.

Have you searched around <https://talk.jekyllrb.com/> or Stackoverflow at all? This seems like the sort of thing many people have done so you might be able to gleam some best practices there.

**Comment by zahachtah** [comment]
Ok, thanks for the input. I'll use the javascript in yaml approach. 

I'll try to figure out how to have a <div> replace the image in the feature rows and galleries and such. 

Thanks again
