### ISSUE TITLE
3.3.7+ broken local hosting

### ISSUE THREAD

**Issue by amweiss** [mmistakes/minimal-mistakes#461]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 3.3.7+** 
- **`github-pages` or `jekyll` gem version: github-pages 98** 
- **Operating system: OSX** 

---

## Expected behavior

When making `site.url` empty, the links should be relative to `localhost:4000`.

## Steps to reproduce the behavior

It looks like ca9ff32 changed this functionality, and perhaps I'm just missing something, but when running `bundle install` and then `bundle exec jekyll serve` it now makes all the links be relative to the github repo rather than `localhost`. How can I get back to running off localhost?

**Comment by mmistakes** [comment]
Easy solution is don't leave it blank and use `url: "http://localhost"` when testing locally. The better solution is to create a dev config, something like `_config.dev.yml` and add any dev environment overrides. In this case you would just need a single line:

```
url: "http://localhost:4000"
```

Then when you run jekyll locally you do:

```
bundle exec jekyll serve --config _config,yml,_confg.dev.yml
```

And all will be well with the world.
