### ISSUE TITLE
jekyll-archives not works

### ISSUE THREAD

**Issue by ZhiZe-ZG** [mmistakes/minimal-mistakes#4758]
### What happened?

- Minimal Mistakes version: (used as remote_theme)
- Ruby gem or remote theme version: gem 3.5.7
- Jekyll version: 3.9.5
- Git repository URL: https://github.com/ZhiZe-ZG/zhize-zg.github.io
- Hosted on GitHub Pages (if yes provide URL to site): https://www.zhize.xyz/
- Operating system: Windows 11

Discrete taxonomy pages were not generated as described in <https://mmistakes.github.io/minimal-mistakes/docs/configuration/> even at local host.

I make sure I have run the `bundle install` command after change the Gemfile.

### Expected behavior

Generate discrete taxonomy pages as described in <https://mmistakes.github.io/minimal-mistakes/docs/configuration/> .

### Steps to reproduce the behavior

```
bundle exec jekyll serve
```

**Comment by iBug** [comment]
Seems like you didn't set the taxonomy pages to be generated by jekyll-archives:

<https://github.com/ZhiZe-ZG/zhize-zg.github.io/blob/4e78acf23a890447fd27c700a649f7f5c0604fde/docs/_config.yml#L251>
<https://github.com/ZhiZe-ZG/zhize-zg.github.io/blob/4e78acf23a890447fd27c700a649f7f5c0604fde/docs/_config.yml#L254>

**Comment by ZhiZe-ZG** [comment]
@iBug It was open at the time of my question. Because I gave up using this plugin now, I switched to Liquid.
