### ISSUE TITLE
Liquid syntax error / warning: Expected dotdot but found id in ...

### ISSUE THREAD

**Issue by vwchu** [mmistakes/minimal-mistakes#479]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.4.3
- **`github-pages` or `jekyll` gem version:** Github-pages 93 and Jekyll 3.2.1 and Liquid 3.0.6
- **Operating system:** Ubuntu 14.04 LTS (Vagrant ubuntu/trusty64)

---

## Expected behavior

I updated the theme to 3.4.3 and ran `bundle install`. After upgrading while trying to generate the site with `bundle exec jekyll build`, I encountered the following warning / error for Liquid:

```
Liquid Warning: Liquid syntax error (line 3): Expected dotdot but found id in "(page.header.overlay_color or page.header.overlay_image) or page.header.image" in /_layouts/single.html
Liquid Warning: Liquid syntax error (line 1): Expected dotdot but found id in "(page.header.overlay_color or page.header.overlay_image) or page.header.image" in /_layouts/archive.html
Liquid Warning: Liquid syntax error (line 3): Expected dotdot but found id in "(page.header.overlay_color or page.header.overlay_image) or page.header.image" in /_layouts/splash.html
```

Appears to be the same error as https://github.com/mmistakes/so-simple-theme/issues/141, where parentheses are not permitted by Liquid. So to fix this issue we should just remove the offending parentheses as specified by the error message.

**Comment by mmistakes** [comment]
Curious do the page header images or overlays still render properly in the `_site` files? What are the contents of your `Gemfile.lock`.

I haven't been able to reproduce the error on Mac OS X or Windows, so curious if it's an older gem or just an environment thing.

I'll have to do some testing with your pull request since it fundamentally changes the conditional and it might miss some edge cases doing "x `or` y `or` z" instead of "(x `or` y) `or` z"

**Comment by mmistakes** [comment]
So I just did `bundle update` and it bumped Jekyll to 3.2.1 and now I'm seeing the warning. Looks to be just a warning and the HTML generates fine.

I'll test out your PR and get back to you to verify nothing breaks.

**Comment by yanlee26** [comment]
Waiting for the bug's fix ASAP...

**Comment by MoralCode** [comment]
I was able to fix this error by removing the parenthesis. in your case where doing so would fundamentally affect the conditional, maybe you could use jekyll to `assign` a variable with just the part of the conditional in parenthesis to force it to evaluate first, and then use that in place of the parenthesis in the original location of your conditional.

Considering I don't even use this theme, i suspect this may be a jekyll issue
