### ISSUE TITLE
Quick start guide still points to v4.24.0

### ISSUE THREAD

**Issue by brackendawson** [mmistakes/minimal-mistakes#4809]
### Motivation

On step 4 of the [Remote Theme Method](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remote-theme-method) in the Quick Start Gide it has you pin version 4.24.0.

### Suggestion

Either use v4.25.0 or don't pin the version.

**Comment by iBug** [comment]
Thanks for reporting. This is a leftover habit from Michael and I have no idea why it went this way initially. I've updated the docs to point to 4.25.0 for now.
