### ISSUE TITLE
404 for link to minimal mistakes

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#4840]
### What happened?

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- Hosted on GitHub Pages (if yes provide URL to site):
- Operating system:

### Expected behavior

No 404

### Steps to reproduce the behavior

This is the file - https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/footer.html

### Other

The link goes to a 404 on mademistakes site.

**Comment by iBug** [comment]
I'm not seeing anything wrong. The link <https://mademistakes.com/work/jekyll-themes/minimal-mistakes/> goes normally.

**Comment by lsolesen** [comment]
![image](https://github.com/mmistakes/minimal-mistakes/assets/148026/3c1d32a5-dc1f-4c2b-95a7-52d8487a6b3d)

I think it is a missing slash.

When I go to https://mademistakes.com/work/minimal-mistakes-jekyll-theme it is a 404. When going to https://mademistakes.com/work/minimal-mistakes-jekyll-theme/ it works

**Comment by lsolesen** [comment]
@iBug ^^

**Comment by iBug** [comment]
The code doesn't seem to miss anything:

```html
<a href="https://mademistakes.com/work/minimal-mistakes-jekyll-theme/" rel="nofollow">Minimal Mistakes</a>
```
