### ISSUE TITLE
Figure helper breaks when using code font in caption

### ISSUE THREAD

**Issue by ShaneKosieradzki** [mmistakes/minimal-mistakes#4841]
### What happened?

- Minimal Mistakes version: 4.26.0
- Ruby gem or remote theme version: remote theme
- Jekyll version: 3.9.5
- Git repository URL: https://github.com/ShaneKosieradzki/ShaneKosieradzki.github.io
- Hosted on GitHub Pages (if yes provide URL to site): https://shanekosieradzki.github.io/projects/fpga-keygen/
- Operating system: Windows 11

### Expected behavior

When using the [figure helper](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#figure) template, the `caption` attribute is sensitive to use of [code text](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). 

What i mean is if you wrap a word in the caption in backticks, than the whole template breaks. This does not seem to happen with other markdown syntax such as italics.

It still displays the figure and caption when you have the code text but it also shows some raw html in the final output website

### Steps to reproduce the behavior

To reproduce this error in a markdown file use the [figure template](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#figure) and set a caption that has some word wrapped in backticks.

### Other

Use this snippet to recreate the error
```raw
{% include figure popup=true image_path="/path/to/figure.png" caption="This caption has `code text` which will cause the template to break" %}
```

**Comment by iBug** [comment]
Try the latest patch with `remote_theme: "mmistakes/minimal-mistakes"` (i.e. drop the version number) and see if it's resolved.

**Comment by ShaneKosieradzki** [comment]
This resolved the issue thanks!
