### ISSUE TITLE
Need Algolia API key to update search index

### ISSUE THREAD

**Issue by iBug** [mmistakes/minimal-mistakes#4893]
The theme's search feature is still returning stale results from 2022. I believe this is due to a lack of update of Algolia's index.

If you can add an Actions secret named `ALGOLIA_API_KEY`, I can copy the Actions [workflow from my own repo](https://github.com/iBug/iBug-source/blob/3c594e246d5a0ac053fcf350f12a9a4d2a3d587c/.github/workflows/build.yml#L67-L71) to get this fixed and kept updated automatically.

I also plan to automate more tasks like [populating the per-page `last_updated_at` from Git history](https://github.com/iBug/iBug-source/blob/3c594e246d5a0ac053fcf350f12a9a4d2a3d587c/Gemfile#L47) with Actions. CI is the best way to keep these things tidy and in order.

**Comment by mmistakes** [comment]
@iBug Doesn't look like there's an Algolia index anymore for the MM site. I seem to remember I was using Travis CI to run the Algolia index build with it (this was way before GitHub added Actions).

Looks like that was purged, which caused Algolia to dump my account due to inactivity years ago.

Can you create a new instance or do you need me to set something up?

**Comment by iBug** [comment]
> Doesn't look like there's an Algolia index anymore

I strongly doubt that, as otherwise the current site search wouldn't produce any result. Could you try digging for that account and index?

If I have to set up a new Algolia account, I have no confidence that the [current free tier](https://www.algolia.com/pricing/) would suffice. Note that a decade ago Algolia used to offer unlimited search queries for free which is no longer the case.

**Comment by mmistakes** [comment]
Found it. Which type of secret do you need it added as? Environment or Repository?

<img width="794" alt="Screenshot 2024-06-26 at 5 34 00 PM" src="https://github.com/mmistakes/minimal-mistakes/assets/1376749/e8ecd2e8-932d-4a5c-b00a-9bdc96d7660b">

Also, might be worth switching to [Pagefind](https://pagefind.app). I've been meaning to use it on my personal site, but haven't gotten around to it yet. Seems performant and there wouldn't be a worry of hitting limits with Algol.

**Comment by iBug** [comment]
Repository secret is the way to go, just make sure you name it `ALGOLIA_API_KEY`.

BTW, I have two sites running on Algolia's legacy unlimited free plan and have yet to run into any issue (besides network ones). But their traffic, even summed up, are nowhere near that of this site.

Re: Pagefind: Maybe one day someone finds it useful and decides to contribute with their implementation. For documentation sites I've been using [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/). It uses Lunr and runs like butter, so personally I have little interest in searching for an alternative.

**Comment by mmistakes** [comment]
@iBug Should be all set. I've added the `ALGOLIA_API_KEY` as a repository secret.
