### ISSUE TITLE
How would you make a page which showed all the authors in _data/authors.yml?

### ISSUE THREAD

**Issue by zfrenchee** [mmistakes/minimal-mistakes#494]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

Could you do this using the collection logic? If so, how would you point it at authors.yml?

Thanks!

**Comment by mmistakes** [comment]
You can loop over the data in any file found in `_data`. [Check the docs] or inquire on the forum for more help. In fact the official docs includes an example for pretty much exactly what you want.

These sorts of questions are best for [talk.jekyllrb.com] or [Stackoverflow](http://stackoverflow.com/questions/tagged/jekyll) as they're not really theme related. It's standard Jekyll faire.

**Comment by zfrenchee** [comment]
Sorry!
