### ISSUE TITLE
The page is different from locally to github

### ISSUE THREAD

**Issue by GnCavalry** [mmistakes/minimal-mistakes#500]
- [ ] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x ] I have updated all gems with `bundle update`.
- [x ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** 

---

## Steps to reproduce the behavior

Here is my 2016-09-01-test.md in _posts

```
---
layout: single
title: This is a Test Article
comments: true
---

这是一个测试文章

MMMMMMMMMM

......测试

{% highlight ruby linenos %}
def show
  @widget = Widget(params[:id])
  respond_to do |format|
    format.html # show.html.erb
    format.json { render json: @widget }
  end
end
{% endhighlight %}

Write a test split words.

{% highlight java linenos %}

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button btnStartAnotherApp = (Button) findViewById(R.id.btn_start_other_app);
        btnStartAnotherApp.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = getPackageManager().getLaunchIntentForPackage("com.sinohealth.erm");
                intent.addCategory(Intent.CATEGORY_LAUNCHER);
                startActivity(intent);
            }
        });
}

{% endhighlight %}


```

It's ok when I run it locally:

![image](https://cloud.githubusercontent.com/assets/11587781/18197279/e33b0faa-7128-11e6-9cb5-c54ad7efd03a.png)

But when I push it to github, It looks like this:

![image](https://cloud.githubusercontent.com/assets/11587781/18197349/26a4038c-7129-11e6-9478-9c76ac25ed0f.png)

How can I fix it ?

**Comment by mmistakes** [comment]
Not sure what's going on. Looks like its parsing the Markdown wrong as there appears to be a `>` before the code blocks that I'm not seeing in your first example.

I don't control that part of Jekyll and Kramdown so I can't really comment on the problem. Are you using the `github-pages` gem locally to run Jekyll so its mirroring the environment on GitHub Pages. Could be you're running a different version of Jekyll locally than what GitHub uses and that's why you don't see the problem.

GitHub Pages' version of Jekyll is different and it likely doesn't have all the updated gems that might have fixed this issue. You'll need to file a bug on that repo if that's the case since this is an upstream issue and not the theme.

**Comment by mmistakes** [comment]
Found the issue. It's the [Compress HTML](http://jch.penibelst.de/) layout I'm using. When you run locally you're most likely using Jekyll in dev mode (which disables HTML compression). On GitHub Pages it sets `JEKYLL_ENV` to `production`.

The HTML compress layout apparently has issues with certain characters. Someone recently submitted a related issue where Chinese characters (#484) were causing problems and would break the layout. That's what's happening here.

There may be settings you can adjust to stop that, so check its [documentation](http://jch.penibelst.de/) first. Or you could just disable it all together by removing `layout: compress` from **_layouts/default.html**

**Comment by GnCavalry** [comment]
Thank you very much , It's works !

By the way , JEKYLL_ENV=production can't verify this issue on my machine...

**Comment by mmistakes** [comment]
What's your operating system? That matters how you set the `JEKYLL_ENV` variable.
For example with Windows you need to do `set JEKYLL_ENV=production` followed by `bundle exec jekyll serve`.

**Comment by GnCavalry** [comment]
Oh , My mistake .
I put <code>JEKYLL_ENV=production</code> in the end of the command line.
It should be written in the first.
Thanks !!!
