### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by RinatMambetov** [mmistakes/minimal-mistakes#5000]
### Theme version and system environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- URL to the page with the problem:
- Operating system:
- Browser version:

### What happened?

Despite the fact that you're on your website at https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/, you still have no favicon.

### Expected behavior

Despite the fact that you're on your website at https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/, you still have no favicon.

### Steps to reproduce the behavior

Despite the fact that you're on your website at https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/, you still have no favicon.

**Comment by iBug** [comment]
A favicon is not included in the documentation site, and Michael probably didn't bother having one.

**Comment by iBug** [comment]
The theme provides [`_includes/head/custom.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/head/custom.html) for you to override with custom HTML. This is where you can drop a `<link>` to your favicon like [I do](https://github.com/iBug/iBug-source/blob/ab4f32938b6cd1cb642be0871cc761a6490b54f0/_includes/head/custom.html#L1).
