### ISSUE TITLE
Panels overlap main content when window is 800 pixels wide

### ISSUE THREAD

**Issue by djpeterhenry** [mmistakes/minimal-mistakes#5015]
### Theme version and system environment

- Minimal Mistakes version: 4.26.2 (Or whatever's used by github right now)
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- URL to the page with the problem:
- Operating system:
- Browser version:

### What happened?

Main window content is left aligned and underneath author info when browser window is 800 pixels wide.

### Expected behavior

Main window content should be to the right of the "Author" information as opposed to under it.

### Steps to reproduce the behavior

I can demonstrate the issue on the sample page https://mmistakes.github.io/minimal-mistakes/year-archive/

Scroll down when the window is 800 pixels wide and it looks something like this:
![Screen Shot 2024-10-26 at 5 30 00 PM](https://github.com/user-attachments/assets/3d89d3b2-c191-4081-be2d-7ef45e46caaa)

**Comment by iBug** [comment]
No reproduction.

![image](https://github.com/user-attachments/assets/1243253b-0197-49a1-b8a4-8349ecc7d2f6)
