### ISSUE TITLE
Tabulate CSV Data

### ISSUE THREAD

**Issue by diegobiavati** [mmistakes/minimal-mistakes#5027]
### Theme version and system environment

- Minimal Mistakes version: 4.26.2
- Ruby gem or remote theme version: 3.4.0
- Jekyll version: 4.3.4
- Git repository URL: https://gitlab.com/diegobiavati/blog
- URL to the page with the problem: https://diego.biavati.nom.br/ex%C3%A9rcito/recodom/c%C3%B3digos/recodom/
- Operating system: Linux (Debian) 12
- Browser version: Firefox 128 - ESR

### What happened?

I'm trying to generate an article based on a CVS file, following this tutorial https://jekyllrb.com/tutorials/csv-to-table/, when I have a table in markdown and then load the script, the error doesn't happen, but the information is doubled.

When I leave the script just to generate the spreadsheet, I receive the following error:

```Liquid Exception: Liquid syntax error (line 9): 'for' tag was never closed in /builds/diegobiavati/blog/_posts/2024-10-18-recodom.md/#excerpt
  Liquid Exception: Liquid syntax error (/builds/diegobiavati/blog/.gem/ruby/3.3.0/gems/minimal-mistakes-jekyll-4.26.2/_includes/page__related.html line 9): 'for' tag was never closed included in /builds/diegobiavati/blog/.gem/ruby/3.3.0/gems/minimal-mistakes-jekyll-4.26.2/_layouts/single.html
                    ------------------------------------------------
      Jekyll 4.3.4   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
```

<https://gitlab.com/diegobiavati/blog/-/jobs/8296173763>

### Expected behavior

I would like to generate a spreadsheet dynamically whenever I load the CVS file with the updates.

### Steps to reproduce the behavior

Not

**Comment by iBug** [comment]
Problem's with your own code:

<https://gitlab.com/diegobiavati/blog/-/blob/702d6d2785532e43d917aa059d0011bb1a1e8b0f/_posts/2024-10-18-recodom.md?plain=1#L28>

**Comment by iBug** [comment]
You did not fix anything. The superfluous `{% endfor %}` is still there. Get rid of it and you should be fine.
