### ISSUE TITLE
Unknown tag 'include_cached' in /_layouts/default.html

### ISSUE THREAD

**Issue by al-martyn1** [mmistakes/minimal-mistakes#5051]
### Theme version and system environment

- Minimal Mistakes version: 4.26.2

### What happened?

I've got a message in actions build log

> Liquid Exception: Liquid syntax error (line 10): Unknown tag 'include_cached' in /_layouts/default.html

### Expected behavior

I expected it works

### Steps to reproduce the behavior

Try to use theme with empty pages repo

**Comment by iBug** [comment]
Please read the README carefully.
