### ISSUE TITLE
There is some conflicts using {% hightlight %} with minimal

### ISSUE THREAD

**Issue by geekbanana** [mmistakes/minimal-mistakes#512]
- [ ] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:**  3.4.4
- **`github-pages` or `jekyll` gem version:** github-pages
- **Operating system:** ubuntu 16.04

---

## Expected behavior

Expected code in <code>{% highlight %}</code> aligns left but aligns right .

## Steps to reproduce the behavior
1. I have deleted <code>layout: compress</code> in my <code>_layout/defaults.html</code>
2. use <code>```</code> for code block is normal
3. use <code>{% highlight %}</code>  for code block will make the code align right.

Here is the result page:
https://geekbanana.github.io/android/handler/creating-teminal/

Here is the code: 

https://github.com/geekbanana/geekbanana.github.io/blob/master/_posts/android/handler/2016-09-09-creating-teminal.md

**Comment by mmistakes** [comment]
Strange, I'm not seeing any right alignment to the code blocks. They're all left aligned.

![screen shot 2016-09-08 at 9 28 22 pm](https://cloud.githubusercontent.com/assets/1376749/18372517/4977ed4c-760b-11e6-9a35-68c5207baca8.png)

**Comment by geekbanana** [comment]
It's weird .   
I just downloaded a new project of minimal-mastakes .

1. change <code>_config.yml/url</code> to <code>http://localhost:4000</code>

2. write a post <code>_posts/2016-09-09-just-code.md</code>
```
---
title: just-code
---

{% highlight java %}

public static Boolean valueOf(boolean b) {
    return b ? Boolean.TRUE : Boolean.FALSE;
}

{% endhighlight %}
```
3.copy <code>defaults</code> from your gh-pages
4.<code>bundle install</code>
5.<code>bundle exec jekyll build</code> , then the console report an error :  

Liquid Exception: Liquid syntax error (line 1): 'highlight' tag was never closed in /home/new-github-blog/_posts/2016-09-09-just-code.md/#excerpt
  Liquid Exception: Liquid syntax error (line 1): 'highlight' tag was never closed in index.html
jekyll 3.2.1 | Error:  Liquid syntax error (line 1): 'highlight' tag was never closed

**Comment by mmistakes** [comment]
Could be due to the spaces. 

```
{% highlight java %}
public static Boolean valueOf(boolean b) {
    return b ? Boolean.TRUE : Boolean.FALSE;
}
{% endhighlight %}
```

I stopped using Jekyll's `{% highlight %}` tag awhile ago once [GFM](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) backticks started working reliably with Kramdown and Jekyll.

**Comment by mmistakes** [comment]
If removing the spaces doesn't work it could also be due to how Jekyll deals with excerpts. If you don't define `excerpt: ` in the YAML Front Matter then the theme falls back to Jekyll which autogenerates it from the first paragraph of content.

Entirely possible it has issues processing the `{% highlight %}` tag.

> Since v1.0.0, Jekyll has had automatically-generated post excerpts. Since v1.1.0, Jekyll also passes these excerpts through Liquid, which can cause strange errors where references don’t exist or a tag hasn’t been closed. If you run into these errors, try setting excerpt_separator: "" in your _config.yml, or set it to some nonsense string.

- https://jekyllrb.com/docs/posts/#post-excerpts
- https://jekyllrb.com/docs/troubleshooting/#excerpts

**Comment by geekbanana** [comment]
It works for me to remove the spaces. 

But the code block still align right. . .

**Comment by mmistakes** [comment]
Can you provide a screenshot? I've tested in a few browsers and I'm not seeing anything aligned to the right.

**Comment by geekbanana** [comment]
Oh, yeah , It is related to the browser. 
I changed to Chromium , Then the code block works well.
But in Firfox , the code block will align right. 
I'll privode the scrennshot and browser environment later.

**Comment by geekbanana** [comment]
Here is the FireFox screenshot:
https://goo.gl/photos/NhnJBwvr3DkaqpvUA

Here is the chromium screenshot:
https://goo.gl/photos/n3nFjPg4WXUQnK2C6

FireFox 48.0
Chromium Version 52.0.2743.116 Built on Ubuntu
OS: ubuntu 16.04

**Comment by mmistakes** [comment]
Fixed. You can reference this commit https://github.com/mmistakes/minimal-mistakes/commit/3c034e59f4fe61e1c93521b0fbedaca29b197977 with the necessary SCSS to cleanup the alignment and make line number look better.

Example:

![highlight-code](https://cloud.githubusercontent.com/assets/1376749/18390386/0013bf60-7678-11e6-9db1-99e4886158fa.jpg)
