### ISSUE TITLE
backgroud color of sidebar is different from _pages to _posts

### ISSUE THREAD

**Issue by geekbanana** [mmistakes/minimal-mistakes#515]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.4.6
- **`github-pages` or `jekyll` gem version:**  jekyll 3.x
- **Operating system:** ubuntu 16.04
- **browser:** firefox 48.0 && chromium 52.0.2743.116 Built on Ubuntu

---

The sidebar's background color is different from _pages to _posts.  
Here is the screenshot of [_pages/java.html](https://github.com/geekbanana/geekbanana.github.io/blob/master/_pages/java.html):

![9](https://cloud.githubusercontent.com/assets/11587781/18415149/eca27978-7819-11e6-850a-0bf7bd0abada.png)

Here is the screenshot of [_posts/java/effective-java/2016-09-11-cado-static-factory-methods.md](https://github.com/geekbanana/geekbanana.github.io/blob/master/_posts/java/effective-java/2016-09-11-cado-static-factory-methods.md)
![10](https://cloud.githubusercontent.com/assets/11587781/18415163/30aa251c-781a-11e6-9852-46b17503ebed.png)
)

By the way , the text size of sidebar and code block is too small for me , Where can I change them?

**Comment by mmistakes** [comment]
Sidebar nav hasn't been styled to work with `archive` layout that's why it looks different. It was built for `layout: single`.

CSS for the sidebar and code blocks are in these SCSS partials.

- https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_sidebar.scss
- https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_syntax.scss

**Comment by geekbanana** [comment]
But there is no thing deferent after I changed to `layout: single`

**Comment by mmistakes** [comment]
I just looked at your site. The sidebar is working as intended. When you're on the a page that is in the nav an `active` class it added to indicate that fact.

**Comment by geekbanana** [comment]
Oh, I'm so stupid.  Thank your very much .
