### ISSUE TITLE
Revisit responsive typography

### ISSUE THREAD

**Issue by jhabdas** [mmistakes/minimal-mistakes#533]
This theme does a great job at managing responsive font sizes. But I noticed there's a need for another breakpoint for larger viewports. To get a feel for what I mean on OS X open System Preferences and access Displays, and scale for _More Space_ as shown here:

<img width="780" alt="screen shot 2016-09-16 at 11 01 35 am" src="https://cloud.githubusercontent.com/assets/440298/18592531/0130568a-7bfd-11e6-94eb-90eec19ab5b8.png">

Here's an example of what the theme looks like with the _More Space_ setting on a Retina display with a full-screen browser window:

![screen shot 2016-09-16 at 11 04 14 am](https://cloud.githubusercontent.com/assets/440298/18592622/6e6050b6-7bfd-11e6-8325-495ff3933969.png)

As you can see things are a bit eye-straining. As a result, next time responsive typography is revisited please consider adjusting based on the guidance here:

https://ia.net/know-how/responsive-typography-the-basics
https://ia.net/know-how/100e2r

And take a peek at how iA looks at the _More Space_ setting:

![screen shot 2016-09-16 at 11 07 41 am](https://cloud.githubusercontent.com/assets/440298/18592713/cfdf6af2-7bfd-11e6-9257-83c28987f4b7.png)

Cheers!

**Comment by mmistakes** [comment]
This one is actually pretty easy to fix. I purposely set type in relative units like `ems` and `rems` to globally scale font-sizes and white space up/down.

Inside of [`_reset.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_reset.scss#L13-L15) there's this line that bumps up the base font size from the default of `16px` to `18px. Could easily add another breakpoint to go to `20px` for larger screens.

I'm not at my iMac currently, but if you wanted to test this minor change and see if it improves things that would be cool.

```diff

html {
  /* apply a natural box layout model to all elements */
  box-sizing: border-box;
  background-color: $background-color;
  font-size: 16px;

  @include breakpoint($medium) {
    font-size: 18px;
  }

+  @include breakpoint($large) {
+    font-size: 20px;
+  }

  -webkit-text-size-adjust: 100%;
  -ms-text-size-adjust: 100%;
}
```

If type goes to large too quick might work better on `$x-large` instead.
