### ISSUE TITLE
Links from local test site link to production site

### ISSUE THREAD

**Issue by zfrenchee** [mmistakes/minimal-mistakes#535]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Expected behavior

If you try to test a site locally, using `bundle exec jekyll serve` then each of the links in the navigation redirect to the live site, instead of localhost:4000/whatever you get yourproj.github.io/whatever. More importantly, if you update styles locally they don't show up at localhost:4000 because your local site will have

```
<link rel="stylesheet" href="http://yourproj.github.io/assets/css/main.css">
```

in its header instead of localhost:4000/assets/css/main.css

Is this intentional?

**Comment by mmistakes** [comment]
If you take a look at the theme files you'll see that all of the nav links and asset paths are prepended with `site.url` + `site.baseurl`. If you don't change `url` in your _config.yml when testing locally it will use the production domain you set. This is noted in the docs.

When working locally change it to `url: http://localhost:4000` and all will be well.
