### ISSUE TITLE
Showing the posts dates on the home page

### ISSUE THREAD

**Issue by vladsandulescu** [mmistakes/minimal-mistakes#550]
Hi, 

First of all, thanks for a great template! Is there a way to show the posts dates in the Recent Dates page (basically the home page)?

Thanks,
Vlad

**Comment by mmistakes** [comment]
Not through any settings no. But if you're up for hacking the theme a little you can easily add post dates to archive listings. 

Take a look at [archive-single.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/archive-single.html)

You essentially need to add `{{ page.date }}` to that _include where you want the date. On the same line as the read time would be my suggestion.

**Comment by vladsandulescu** [comment]
Thanks for the suggestion.
I added {{ post.date | date: "%B %d, %Y" }} to the archive-single page and
it looks great.

/Vlad

**Comment by ykfq** [comment]
I'm able to avhive this by fllow his blog

> https://github.com/dvhart/dvhart.github.io/blob/master/_includes/archive-single.html

Just remove line 33-35 and add these code under line 32:
```html
    <p class="page__meta">
      {% if post.last_modified_at %}
        <i class="fa fa-fw fa-calendar" aria-hidden="true"></i> <time datetime="{{ post.last_modified_at | date: "%Y-%m-%d" }}">{{ post.last_modified_at | date: "%B %d, %Y" }}</time>&emsp;
      {% elsif post.date %}
        <i class="fa fa-fw fa-calendar" aria-hidden="true"></i> <time datetime="{{ post.date | date_to_xmlschema }}">{{ post.date | date: "%B %d, %Y " }}</time>&emsp;
      {% endif %}
      {% if post.read_time %}<i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;{% include read-time.html %}{% endif %}
    </p>
```
