### ISSUE TITLE
Related posts not shown

### ISSUE THREAD

**Issue by fa-ribeiro** [mmistakes/minimal-mistakes#554]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---
## Environment informations
- **Minimal Mistakes version: 4.0.1 (feature/theme-gem branch)** 
- **`jekyll` gem version: 3.2.1 (master branch)** 
- **Operating system: Mac OSX 10.11.6** 

---
## Expected behavior

Related post should appear on every post as they are enabled by default in my `_config.yml`:

```
# Defaults
defaults:
  # _posts
  * scope:
      path: ""
      type: posts
    values:
      related: true
```
## Steps to reproduce the behavior
1. create a couple of posts
2. enable related posts on `_config.yml`
## Additional information

If I insert the following code block (extracted from `_layouts/single.html`) in a post, the related posts are shown as expected:

```
{% if page.id and page.related and site.related_posts.size > 0 %}
  <div class="page___related">
    {% if site.data.ui-text[site.locale].related_label %}
      <h4 class="page__related-title">{{ site.data.ui-text[site.locale].related_label | default: "You May Also Enjoy" }}</h4>
    {% endif %}
    <div class="grid__wrapper">
      {% for post in site.related_posts limit:3 %}
        {% include archive-single.html type="grid" %}
      {% endfor %}
    </div>
  </div>
{% endif %}
```

Any ideas?
Thanks in advance for any help!

**Comment by mmistakes** [comment]
Link to a repo so I can troubleshoot? Most likely it's a content or config problem on your end.

**Comment by fa-ribeiro** [comment]
it's a private repo, but here it is the `_config.yml`:

# Welcome to Jekyll!
    #
    # This config file is meant for settings that affect your entire site, values
    # which you are expected to set up once and rarely need to edit after that.
    # For technical reasons, this file is *NOT* reloaded automatically when you use
    # `jekyll serve`. If you change this file, please restart the server process.

    theme                    : "minimal-mistakes-jekyll"

    # Site Settings
    locale                   : "pt-PT"
    title                    : "FRibeiro.org"
    title_separator          : "-"
    name                     : "Fernando Ribeiro"
    description              : "Random thoughts, quick notes, some stories and a few ideas."
    url                      : "https://fribeiro.org" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
    baseurl                  : # the subpath of your site, e.g. "/blog"
    repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
    teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
    # breadcrumbs            : false # true, false (default)
    words_per_minute         : 200
    comments:
      provider               : disqus # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
      disqus:
        shortname            : fribeiro # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
      discourse:
        server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
      facebook:
        # https://developers.facebook.com/docs/plugins/comments
        appid                :
        num_posts            : # 5 (default)
        colorscheme          : # "light" (default), "dark"
    staticman:
      allowedFields          : ['name', 'email', 'url', 'message']
      branch                 : # "master", "gh-pages"
      commitMessage          : "New comment."
      filename               : comment-{@timestamp}
      format                 : "yml"
      moderation             : true
      path                   : "_data/comments/{options.slug}"
      requiredFields         : ['name', 'email', 'message']
      transforms:
        email                : "md5"
      generatedFields:
        date:
          type               : "date"
          options:
            format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
    atom_feed:
      path                   : # blank (default) uses feed.xml

    # SEO Related
    google_site_verification :
    bing_site_verification   :
    alexa_site_verification  :
    yandex_site_verification :

    # Social Sharing
    twitter:
      username               : Pinguim_Ribeiro
    facebook:
      username               : pinguim.ribeiro
      app_id                 :
      publisher              :
    og_image                 : "assets/images/authors/fribeiro.png" # Open Graph/Twitter default site image
    # For specifying social profiles
    # - https://developers.google.com/structured-data/customize/social-profiles
    social:
      type                   : # Person or Organization (defaults to Person)
      name                   : # If the user or organization name differs from the site's name
      links: # An array of links to social media profiles

    # Analytics
    analytics:
      provider               : google # false (default), "google", "google-universal", "custom"
      google:
        tracking_id          : UA-73135626-1


    # Site Author
    author:
      name             : "Fernando Ribeiro"
      avatar           : "assets/images/authors/fribeiro.png"
      bio              : ""
      location         : "Porto, Portugal"
      email            :
      uri              :
      bitbucket        :
      codepen          :
      dribbble         :
      flickr           :
      facebook         : pinguim.ribeiro
      foursquare       :
      github           : fa-ribeiro
      google_plus      : 106547917473163896243
      keybase          :
      instagram        :
      lastfm           :
      linkedin         : ribeirofernando
      pinterest        :
      soundcloud       :
      stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
      steam            :
      tumblr           :
      twitter          : Pinguim_Ribeiro
      vine             :
      weibo            :
      xing             :
      youtube          :


    # Reading Files
    include:
      - .htaccess
      - _pages
    exclude:
      - "*.sublime-project"
      - "*.sublime-workspace"
      - vendor
      - .asset-cache
      - .bundle
      - .jekyll-assets-cache
      - .sass-cache
      - assets/js/plugins
      - assets/js/_main.js
      - assets/js/vendor
      - Capfile
      - CHANGELOG
      - config
      - Gemfile
      - Gruntfile.js
      - gulpfile.js
      - LICENSE
      - log
      - node_modules
      - package.json
      - Rakefile
      - README
      - tmp
    keep_files:
      - .git
      - .svn
    encoding: "utf-8"
    markdown_ext: "markdown,mkdown,mkdn,mkd,md"


    # Conversion
    markdown: kramdown
    highlighter: rouge
    lsi: false
    excerpt_separator: ""
    incremental: false


    # Markdown Processing
    kramdown:
      input: GFM
      hard_wrap: false
      auto_ids: true
      footnote_nr: 1
      entity_output: as_char
      toc_levels: 1..6
      smart_quotes: lsquo,rsquo,ldquo,rdquo
      enable_coderay: false


    # Sass/SCSS
    sass:
      sass_dir: _sass
      style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


    # Outputting
    permalink: /:categories/:title/
    paginate: 5 # amount of posts to show
    paginate_path: /page:num/
    timezone: Europe/Lisbon # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


    # Plugins
    gems:
    #  - jekyll-archives
      - jekyll-paginate
      - jekyll-sitemap
      - jekyll-gist
      - jekyll-feed
      - jemoji

      - jekyll-youtube

      - jekyll/tagging
      - jekyll-tagging-related_posts

    # mimic GitHub Pages with --safe
    whitelist:
      - jekyll-archives
      - jekyll-paginate
      - jekyll-sitemap
      - jekyll-gist
      - jekyll-feed
      - jemoji

      - jekyll-youtube

      - jekyll/tagging
      - jekyll-tagging-related_posts


    # Archives
    #  Type
    #  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
    #  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
    #  Path (examples)
    #  - Archive page should exist at path when using Liquid method or you can
    #    expect broken links (especially with breadcrumbs enabled)
    #  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
    #  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
    #  - <base_path/my-awesome-category/index.html ~> path: /
    category_archive:
    #  type: jekyll-archives
      path: /categories/
    tag_archive:
      type: jekyll-archives
      path: /tags/
    # https://github.com/jekyll/jekyll-archives
    jekyll-archives:
      enabled:
        - categories
        - tags
      layouts:
        category: archive-taxonomy
        tag: archive-taxonomy
      permalinks:
        category: /categories/:name/
        tag: /tags/:name/


    # HTML Compression
    # - http://jch.penibelst.de/
    compress_html:
      clippings: all
      ignore:
        envs: development


    # Collections
    # collections:
    #   recipes:
    #     output: true
    #     permalink: /:collection/:path/
    #   pets:
    #     output: true
    #     permalink: /:collection/:path/
    #   portfolio:
    #     output: true
    #     permalink: /:collection/:path/


    # Defaults
    defaults:
      # _posts
      - scope:
          path: ""
          type: posts
        values:
          layout: single
          author_profile: true
          read_time: true
          share: true
          related: true
          comments: true
      # _pages
      - scope:
          path: ""
          type: pages
        values:
          layout: single
          author_profile: true
          read_time: true
          share: true

**Comment by mmistakes** [comment]
Config looks fine. Could be content or something else but since I can't see that to test hard to say.

**Comment by fa-ribeiro** [comment]
ok, possibly it's something wrong somewhere...  I'll review everything again.
Can you please close this issue?
Many thanks for you help.

**Comment by mmistakes** [comment]
Also just noticed you're using the gen version of the theme. Since it's not officially released it's possible there's a bug in there, but I'd be surprised if that was the case.

What happens if you pull down the [latest stable release](https://github.com/mmistakes/minimal-mistakes/releases/tag/3.4.8) and drop in the contents of your `_posts` folder?

Since it's working fine on the demo site I have a suspicion there's something going on with the theme in `gem` form.

**Comment by fa-ribeiro** [comment]
Yes, I'm testing the `feature/theme-gem` branch.
My `Gemfile`has:

    gem "jekyll", :git => "https://github.com/jekyll/jekyll.git"
    gem "minimal-mistakes-jekyll", :git => "https://github.com/mmistakes/minimal-mistakes.git", :branch => "feature/theme-gem"

I copied the posts from the [minimal-mistakes/example/_posts/](https://github.com/mmistakes/minimal-mistakes/tree/feature/theme-gem/example/_posts) (again the `feature/theme-gem` branch) into my _posts. As result, the latest 4 posts have related posts, but not the others; as soon as I remove the added posts, no more related posts are shown.

**Comment by mmistakes** [comment]
Did some testing of my own and there are some posts in the demo site that don't show related posts even though they should. Adding `{{ site.related_posts | inspect }}` to _layouts/single.html shows outputs:

this for a post with related

```
[#<Jekyll::Document _posts/2016-02-24-welcome-to-jekyll.md collection=posts>, #<Jekyll::Document _posts/2013-08-16-markup-syntax-highlighting.md collection=posts>, #<Jekyll::Document _posts/2013-05-22-markup-more-images.md collection=posts>, #<Jekyll::Document _posts/2013-01-11-markup-html-tags-and-formatting.md collection=posts>, #<Jekyll::Document _posts/2013-01-10-markup-image-alignment.md collection=posts>, #<Jekyll::Document _posts/2013-01-09-markup-text-alignment.md collection=posts>, #<Jekyll::Document _posts/2013-01-05-markup-title-with-special-characters.md collection=posts>, #<Jekyll::Document _posts/2013-01-05-markup-title-with-markup.md collection=posts>, #<Jekyll::Document _posts/2012-05-22-markup-text-readability.md collection=posts>, #<Jekyll::Document _posts/2012-03-15-layout-sidebar-custom.md collection=posts>]
```

and this for ones without

```
nil
```

I don't really know how Jekyll determines what is related and what isn't but for that appears to be where the bug or problem is. I suspect it's content related but not sure why that would matter. Sites like @jhabdas's [appears to work](https://habd.as/) just fine so it doesn't appear to be the theme's fault.

Where it gets even stranger is only the most 4 recent posts on the demo site show related posts. I took the most recent post  (which is showing related posts), changed the date so it became the last post in the list, and the related posts disappeared.

Thought maybe `limit: 4` has something to do with it in this line `{% for post in site.related_posts limit:4 %}` so I took that out too, and it made no difference.

I'm really stumped here. Only thing I can think of would be to not use `site.related_posts` and instead use `site.posts` and filter on tags/categories instead to fake "related posts".

**Comment by jhabdas** [comment]
Scroll down on any post on https://habd.as to see the related posts feature and feel free to inspect my blog source code: https://github.com/jhabdas/habd.as. Good luck!

**Comment by mmistakes** [comment]
@jhabdas I'm stumped why it's working fine for you but not the MM's demo site. I wrote the damn thing and I can't figure out what's going wrong :sweat_smile: 

It's really strange. After the 4th most recent post they stop showing. I thought maybe it was working for you because you're using a newer Jekyll gem, but looks like it's the older GitHub Pages one.

And in @fa-ribeiro's case their using the latest Jekyll off of `master`.

So strange!

**Comment by jhabdas** [comment]
> I wrote the damn thing and I can't figure out what's going wrong

ROFL

Might be worth leaving this open and see if anyone else is having issues besides @fa-ribeiro. Also, @mmistakes when you're ready to come to the dark side I'd love to work together to port this theme to Hugo.

**Comment by mmistakes** [comment]
@jhabdas That's what I was thinking. If it's a widespread issue and not something to do with a weird content edge-case I'm surprised I hadn't heard about yet.

RE: Hugo. I've looked at it and considered switching my personal site over just because it takes so long to build. Everyone always says it builds faster than Jekyll when you have a lot of posts but it would be a crap ton of work for me to rebuild just to test that. So I haven't. PR's like this give me faith Jekyll's build speed will improve.

I've made a lot of [improvements](https://github.com/mmistakes/made-mistakes-jekyll/issues/49) pulling out anything that isn't strictly for converting `.md` files into `.html` files, and that helped a lot.

Not to mention I didn't really care for the template syntax. It's close enough to Liquid sure, but it just looks ugly to me.

**Comment by jhabdas** [comment]
@mmistakes going to delete this message as it's off-topic, but check this out: https://habd.as/choose-hugo-over-jekyll/

**Comment by jhabdas** [comment]
<img width="762" alt="deploy-hackcabin" src="https://cloud.githubusercontent.com/assets/440298/18847851/5b5147b8-83f1-11e6-9136-186e5d01d5fd.png">

Hugo builds and deploys with `s3_website` to cloudfront in under 10 seconds

**Comment by icicimov** [comment]
Hi guys,

Maybe unrelated but I have the same issue in my gh-pages branch I forked from the master about 5-6 days ago. I have the following in my `_config.yml` file:

```
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      author_profile: true
```

but related posts is not showing on any of my posts, see https://icicimov.github.io/blog/

I was under impression this should be working by default but maybe I'm missing something. I'm not sure how the plugin/feature works ie is it parsing the posts body to find a match based on some words or is just picking up 4 random posts etc. Probably I'm just missing something, some non-minimal mistake :-( 

Thanks, 
Igor

**Comment by mmistakes** [comment]
I believe there may be a bug in Jekyll core and how it handles related posts.

The theme is using this to output 4 related posts, which is wrap in a conditional that only shows the module when there are related posts and the feature is enabled.

```
{% for post in site.related_posts limit:4 %}
  {% include archive-single.html type="grid" %}
{% endfor %}
```

When I remove `limit:4` from the for loop related posts works again, but it shows 10 related posts (which is the default behavior). For whatever reason the limit is limiting it to the first 4 posts of the site, instead of limiting it to showing 4 related posts on a given post... if that makes sense.

For example the 4 most recent posts show related posts fine, but when you hit say the 5th post there are no related posts shown. The `limit:4` is affecting that when it really shouldn't.

There's probably another way to limit the amount of related posts shown that I'll investigate to get around the issue.

---

As far as what `related_posts` uses to parse, I'm not entirely sure. Because GitHub Pages disables `LSI` I'm pretty sure it outputs an array of the 10 most recent posts, which makes the whole thing pointless. On my personal site I use a plugin that provides better matches for this reason.

**Comment by mmistakes** [comment]
I came up with a way of showing "related posts" by like `post.tags` instead of using the built in `site.related_posts` array.

The advantage here is you actually get a different set of related posts on each post instead of just the "most recent" posts that currently happens due to `LSI` being disabled on GitHub Pages.

Using this spaghetti code of Liquid in [`_layouts/single.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L63-L75) will display related posts that share the same tags as the current post. It will show 1-4 posts depending on how many matches it finds.

```html
 {% comment %}<!-- show posts by related tags when `related: true` -->{% endcomment %}
  {% if page.related %}
    {% assign n_posts = 0 %}
    {% for post in site.posts %}
      {% if post.id == page.id %}{% continue %}{% endif %}
      {% for this_tag in page.tags %}
          {% if post.tags contains this_tag %}
            {% if n_posts == 0 %}
              <div class="page__related">
                {% if site.data.ui-text[site.locale].related_label %}
                  <h4 class="page__related-title">{{ site.data.ui-text[site.locale].related_label | default: "You May Also Enjoy" }}</h4>
                {% endif %}
                <div class="grid__wrapper">
            {% endif %}
            {% include archive-single.html type="grid" %}
            {% assign n_posts = n_posts | plus: 1 %}
            {% break %}
          {% endif %}
      {% endfor %}
      {% if n_posts > 3 %}{% break %}{% endif %}
    {% endfor %}
    {% if n_posts > 0 %}
        </div>
      </div>
    {% endif %}
  {% endif %}
```
Thoughts?

**Comment by icicimov** [comment]
@mmistakes , thanks for the code it works for me, tried and applied to my site. Matching by tags looks like right direction to go in terms of logic about finding related posts if you ask me.

At the end, just wanted to say thanks for this awesome theme!

**Comment by mmistakes** [comment]
@icicimov Great! Yeah I think related posts by tags does a better job of conveying "related posts" than whatever basic method the default uses.

**Comment by justinrummel** [comment]
Trying to convert my site to the Gem version of MM.  Was this ever added to the Gem version or should I copy my old single.html to the _layouts/ folder?

**Comment by jhabdas** [comment]
@justinrummel would love to hear more about your experience once you make the leap!

**Comment by mmistakes** [comment]
@justinrummel No. This is still open as I haven't found a fix. 

If you're using the gem version remove all local  _layouts, _includes, and _sass folders and files. Unless of course you want them to override the ones bundled in the gem.

**Comment by justinrummel** [comment]
@mmistakes and @jhabdas the migration is complete. Wasn't as bad as I thought except for all the images moving from /images/ to /asset/images/.  Took me a while to figure out what was doing what (inserting the default vs. my .md files forcing a path).  Thank goodness for ```find``` and ```perl``` commands.

``` bash
~/mm-gem-repo/> perl -p -i -e 's/(^    image: )/    image: \/assets\/images\//g' _posts/*
~/mm-gem-repo/> perl -p -i -e 's/(^    overlay_image: )/    overlay_image: \/assets\/images\//g' _posts/*
~/mm-gem-repo/> perl -p -i -e 's/(^    teaser: )/    teaser: \/assets\/images\//g' _posts/*
```

If there was something still wrong, I would search the origin HTML to see if I could find something unique and then search the repo for that value:

``` bash
~/mm-gem-repo/> find . -type f -exec grep -e 'mySearchItem' \{\} \; -print
```

From there I had to find what didn't function or look right.  I inserted Instagram images on the main page, added .css for "fifth" and "sixth" for large amount of photosets pointing to flickr, added Lunr search functionality, and finally this section for related items.  I prefer the searching on tags vs. what is default right now.  I guess I'll leave the single.html until something permanent takes it place.

My slimmed down repo is:

[_includes](https://github.com/justinrummel/jr.com-mm/tree/jr-branch/_includes)
[_layouts](https://github.com/justinrummel/jr.com-mm/tree/jr-branch/_layouts)
[_sass](https://github.com/justinrummel/jr.com-mm/tree/jr-branch/_sass)

**Comment by justinrummel** [comment]
While researching HTTPS testing via ```jekyll serve```, I noticed there is a --lsi flag.  From Jekyll's documentation:

> If the page being processed is a Post, this contains a list of up to ten related Posts. By default, these are the ten most recent posts. For high quality but slow to compute results, run the  jekyll command with the --lsi (latent semantic indexing) option. Also note GitHub Pages does not support the lsi option when generating sites.
source: https://jekyllrb.com/docs/variables/

I can confirm it gives me different results than a list of 10 most recent posts, but still don't think it is perfect.  If you try the --lsi option, be sure to install ```gsl``` as mention on http://footle.org/2014/11/06/speeding-up-jekylls-lsi/ or else you will be sitting for hours without any progress.

**Comment by mmistakes** [comment]
I've always used LSI but pretty sure it's disabled on sites hosted with GitHub Pages. The best solution ice found is using a related post plugin that improves on the one built into Jekyll. But that's sadly not an option for the vast amount of people hosting the theme on GH.

**Comment by mmistakes** [comment]
I came up with a different solution that uses a post tags to compare against and show related posts that way. It can be tested from PR #978 or by copying these two files to your `_layouts` and `_includes` folder.

- [`_layouts/single.html`](https://github.com/mmistakes/minimal-mistakes/blob/934b052ebad61f742e43b417675bf596c38b25ce/_layouts/single.html)
- [`_includes/page_related.html`](https://github.com/mmistakes/minimal-mistakes/blob/934b052ebad61f742e43b417675bf596c38b25ce/_includes/page__related.html)

**Comment by dadatuputi** [comment]
It looks like this was closed without ever implementing tag-based related posts - was that intentional? I'm dealing with this now, and it seems that it would be pretty trivial to do, but I'm not sure why you didn't. If this is something that can be rolled into the gem, then I won't bother now, otherwise I'll override it.

**Comment by mmistakes** [comment]
My pull request made build times worse. That is why it wasn’t merged. I wasn’t comfortable degrading build times for users... especially those with a lot of posts.

**Comment by dadatuputi** [comment]
Would putting it as a configurable option, for example, `related_posts_tag`, eliminate that penalty?

**Comment by mmistakes** [comment]
I've been against adding more configuration flags as they have many costs. In this case I don't think it's warranted as you can override the two files above as I have in the PR if you're OK with slower builds.
