### ISSUE TITLE
SEO information not displayed

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#556]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: current master as of 2016-09-27** 
- **`github-pages` or `jekyll` gem version: jekyll (3.2.1)** 
- **Operating system: Mac OS** 

---

## Expected behavior

Display SEO information as implied by the _includes/seo.html in the HTML source

## Steps to reproduce the behavior

If you view the HTML source for https://mmistakes.github.io/minimal-mistakes/docs/configuration/ you can see there is a large amount of empty space between the SEO comment and the _title_.  Something is wrong with the logic in the /_includes/seo.html file so this information is not being populated.

see screenshot: http://cl.rummel.co/0R3c1J1l0o1H 

![HTML source](https://d3vv6lp55qjaqc.cloudfront.net/items/3a1j1G0S001h022H3o3c/Image%202016-09-27%20at%208.33.19%20AM.png?X-CloudApp-Visitor-Id=205743)

**Comment by mmistakes** [comment]
@justinrummel doesn't look like anything is missing to me. All of the relevant open-graph meta, Twitter cards data, etc. are there.

I get why you'd think something is missing from all of the white-space, but that is due to Liquid. For example that chunk of white-space before the `<title>` tag are all Liquid `assign` tags that don't actually output anything, but when read by Jekyll output as blank lines.

```
{% if site.url %}
  {% assign seo_url = site.url | append: site.baseurl %}
{% endif %}
{% assign seo_url = seo_url | default: site.github.url %}

{% if page.title %}
  {% assign seo_title = page.title | append: " " | append: site.title_separator | append: " " | append: site.title %}
{% endif %}

{% if seo_title %}
  {% assign seo_title = seo_title | markdownify | strip_html | strip_newlines | escape_once %}
{% endif %}

{% if site.url %}
  {% assign canonical_url = page.url | replace: "index.html", "" | prepend: site.url %}
{% endif %}
```

That's the case for a lot of the white-space and is completely normal... messy sure... but that's a Liquid issue and not the theme. HTML minification cleans that right up if you enable it.

**Comment by justinrummel** [comment]
OK, but I would have still expected a generic meta items be displayed somewhere in the head

``` html
<meta name="description" content="{{ seo_description }}">
<meta name="keywords" content="{{ post.tags}}">
<meta name="author" content="{{ site.name }}">
```

**Comment by justinrummel** [comment]
Oh, and thanks for the note about the _layouts/compress.html!  The documentation at http://jch.penibelst.de is perfect.

**Comment by mmistakes** [comment]
@justinrummel  `<meta name="description" content="{{ seo_description }}">` is an omission and should be there. Happy to look at a PR to add it in.

`keywords` is useless and potentially harmful as it's been [abused in the past](https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html) by spammers. It's a general best practice not to use it.

What is the value of adding `meta name="author"`? I haven't seen it used in many places. Most of the SEO include is lifted from the [Jekyll SEO plugin](https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html) which doesn't use it either.

**Comment by mmistakes** [comment]
@justinrummel I originally had `compress` enabled with the theme but it caused several issues so I turned it off. In most causes it should work fine.

**Comment by justinrummel** [comment]
@mmistakes the suggestion for keywords and author are not requirements.  Just was trying to expand beyond the one item description to see if there were other default meta tags that may be missing based on http://smo.knowem.com 

I'll work on a PR for the description tag.
