### ISSUE TITLE
compress options do not seem to work

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#559]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: current master** 
- **`github-pages` or `jekyll` gem version: 3.2.1** 
- **Operating system: Mac OS** 

---

## Expected behavior

Looking at HTML source blank lines should be removed

## Steps to reproduce the behavior

Updated _config to use: 

``` apache
compress_html:
  clippings: all
  blanklines: true
  ignore:
    envs: development
```

Updated _layouts/default.html with 

``` raw
---
layout: compress
---
```

However page source blank lines are not removed.

Site: https://www.justinrummel.com/
repo: https://github.com/justinrummel/jr.com-mm 

![](https://d3vv6lp55qjaqc.cloudfront.net/items/2D2q293C2Y1c1F3X2a0l/Image%202016-09-27%20at%207.58.32%20PM.png?X-CloudApp-Visitor-Id=205743)

thanks!

**Comment by mmistakes** [comment]
It's working as intended, although when you run Jekyll locally it defaults to the development environment, which disables `compress`.

If you want to see how your pages will minify you need to run Jekyll in `production`.

```
bundle exec JEKYLL_ENV=production serve
```

Or if you're on Windows

```
set JEKYLL_ENV=production
bundle exec jekyll serve
```

When deploying to GitHub Pages you don't have to worry about setting the `JEKYLL_ENV` variable to `production` as it does it for you.

The `compress` [documentation](http://jch.penibelst.de/) doesn't really mention all this well, so it's easy to miss if you're unfamiliar with how Jekyll runs.

**Comment by justinrummel** [comment]
Thanks @mmistakes !!!
