### ISSUE TITLE
toc as sidebar in portfolio

### ISSUE THREAD

**Issue by gpldecha** [mmistakes/minimal-mistakes#562]
Hi, I am new to jekyll and have been using your theme for a week now and I have been finding it very useful. 

Q: I was wondering if it is possible to have a table of content (toc) as a side bar in a portfolio. I have not found native support for this yet. Or I might just be mistaken.

any help would be greatly appreciated.

**Comment by mmistakes** [comment]
Links in the [left sidebar](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-navigation-menu) have to be manually created.

![mm-custom-sidebar-nav](https://cloud.githubusercontent.com/assets/1376749/18914138/d3017a4e-8559-11e6-9b8d-43af93d3f2e2.jpg)

The theme uses Kramdown's [automatic table of contents feature](http://kramdown.rubyforge.org/converter/html.html#toc) which builds an un-ordered list out of headings used in your Markdown file. When using the [`{% include toc %}` helper](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#table-of-contents), a table contents is created and floats to the right of your main content.

![mm-toc-helper-example](https://cloud.githubusercontent.com/assets/1376749/18914143/d6594190-8559-11e6-967c-94cedf3da0c9.jpg)
