### ISSUE TITLE
archive-single is not limiting to 160 characters

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#566]
- [ ] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: current Master** 
- **`github-pages` or `jekyll` gem version: 3.2.1** 
- **Operating system: MacOS** 

---

## Expected behavior

Items in /page#/ would limit the character count to 160 as defined in _includes/archive-single.html

## Steps to reproduce the behavior

I'm not confident this is a mm issue.  On only ONE of my archive /page#/ listings does the excerpt generate something greater that 160 characters, and I'm not sure why.  From the HTML source it seems like it's hitting the correct section of _includes/archive-single.html, but something in the .MD source is corrupting the limitation.

- Public page: https://www.justinrummel.com/page15/
- .md file: https://raw.githubusercontent.com/justinrummel/jr.com-mm/jr-branch/_posts/2011-06-29-smime-email-certificates-in-depth.md 
- archive-single.html: https://raw.githubusercontent.com/justinrummel/jr.com-mm/jr-branch/_includes/archive-single.html

**Comment by mmistakes** [comment]
Maybe there's something with your Markdown that Jekyll's post excerpt function doesn't like. It's parsing the entire post as a single object instead of grabbing just the first paragraph and then truncating that.

https://jekyllrb.com/docs/posts/#post-excerpts

I typically do headings like this

```md
## My Heading
```

versus

```
My heading
---
```

So could be something there as I see this note in Kramdown's docs.

> An edge case worth mentioning is the following:
>
> `header`
> `---`
> `para`
>
> One might ask if this represents two paragraphs separated by a horizontal rule or a second level header and a paragraph. As suggested by the wording in the example, the latter is the case. The general rule is that Setext headers are processed before horizontal rules.
>
> http://kramdown.gettalong.org/syntax.html#headers

Have you tried manually adding a post separator after the first paragraph? You can also define the post's excerpt in its YAML Front Matter which will override Jekyll's automatically generated excerpt.

```yaml
excerpt: "You post excerpt goes here that will override the one generated by Jekyll off of the first paragraph of content."
```

**Comment by justinrummel** [comment]
@mmistakes Thanks for the suggestion.  I first tried to ensure that a line break was after the '---', but that did not solve the issue.  Inserting an ``` excerpt: ``` in the YAML header did resolve.  

Thanks again!

**Comment by mmistakes** [comment]
Unlikely this was causing the issue, but found something you might want to fix with your code block Markdown in that post.

1. Think `HTTP` should be lowercase, according to what [languages Rouge supports](https://github.com/jneen/rouge/wiki/List-of-supported-languages-and-lexers) for applying syntax highlighting.

It's showing on the page without syntax highlighting.

![screen shot 2016-10-02 at 9 01 50 pm](https://cloud.githubusercontent.com/assets/1376749/19025223/9d8f5204-88e3-11e6-9384-7c7036b2b602.png)

Changing to this:

```
``` http
---BEGIN CERTIFICATE---
MIIFJjCCBA6gAwIBAgIRAPQyFuvXTYP/N2gOhG540kUwDQYJKoZIhvcNAQEFBQAw
...
```

![screen shot 2016-10-02 at 9 02 22 pm](https://cloud.githubusercontent.com/assets/1376749/19025226/aa766606-88e3-11e6-9d49-3f2f6eb82cb6.png)

**Comment by justinrummel** [comment]
thanks!  I'll try that out.
