### ISSUE TITLE
masthead color.

### ISSUE THREAD

**Issue by QuantLab** [mmistakes/minimal-mistakes#573]
Hey Michael!

I'm wondering how to change a color of masthead? I add background color to masthead.scss, but unfortunately still have little white block after animated menu. Can you point out how to resolve it?

**Comment by mmistakes** [comment]
What exact CSS changes did you make so I can get a feel for what you tried.

Also a screenshot of what it looked like would be helpful.

**Comment by QuantLab** [comment]
here is screenshot of white block:

![mh](https://cloud.githubusercontent.com/assets/7352747/19207822/00f4dbd2-8d05-11e6-9c51-fa5495b3a930.png)
this is a code (I only added 3 `background` variables to 3 masthead elements + changed position to `fixed` for sticky header)

```
/* ==========================================================================
   MASTHEAD
   ========================================================================== */

.masthead {
  position: fixed;
  top: 0;
  border-bottom: 0px solid $border-color;
  -webkit-animation: intro 0.3s both;
          animation: intro 0.3s both;
  -webkit-animation-delay: 0.15s;
          animation-delay: 0.15s;
  z-index: 20;
  width: 100%;
  background: $lighter-gray; 
  height: 55px;

  &__inner-wrap {
    @include container;
    @include clearfix;
    padding: 0 1em 0;
    font-family: $serif;
    font-size: $type-size-5;

    @include breakpoint($x-large) {
      max-width: $x-large;
    }

    nav {
      z-index: 10;
    }

    a {
      text-decoration: none;
    }
  }
}

.masthead__menu {
  background: $lighter-gray;
  @include breakpoint($large) {
    @include prefix(2.5 of 12);
  }

  ul {
    margin: 0;
    padding: 0;
    clear: both;
    list-style-type: none;
  }
}

.masthead__menu-item {
  background: $lighter-gray;
  display: block;
  list-style-type: none;
  white-space: nowrap;

  &--lg {
    padding-right: 0;
    font-weight: 700;
  }
}
```

**Comment by mmistakes** [comment]
I'm not at my computer to fully dig into the code but I'd suggest right clicking the white box and hit "inspect" to fire up your browser's web dev tools. It'll tell you exactly what the element or class is so you can search for it in the Sass partials to edit. That's my go to method for debugging CSS.

I suspect it's this line in `_sass/_navigations.scss` related to the "greedy nav" used in the masthead.

https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_navigation.scss#L178

**Comment by QuantLab** [comment]
> I suspect it's this line in _sass/_navigations.scss related to the "greedy nav" used in the masthead.

bingo! thanks a lot @mmistakes
