### ISSUE TITLE
Loading unsafe script? 

### ISSUE THREAD

**Issue by Celyagd** [mmistakes/minimal-mistakes#574]
The newest version of Chrome is particularly aggressive about script loading, and refuses to load some of the scripts associated with MinimalMistake.

Here's an example website made with MM:

https://celyagd.github.io/research/

Chrome tags many of the scripts on this page as 'unsafe' and refuses to load them, causing the CSS and other things to break (screenshot attached).

In the processed HTML code of the page, I see stuff like this:

```
<link href='//fonts.googleapis.com/css?family=...
<script src="//ajax.googleapis.com/ajax/...
```

As well as this:

```
<script>window.jQuery || document.write('<script src="http://celyagd.github.io/assets/js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
```

My suspicion is that Chrome is not loading any of these scripts, out of security concerns.

What part of MM should I edit to get valid, secure (i.e. starting with `https://`), absolute (i.e. not `document.write`) URLs for all of these scripts?

![celyagd-minimal-mistakes](https://cloud.githubusercontent.com/assets/8224204/19211898/afbb0adc-8d47-11e6-906d-912e66851b01.jpg)

**Comment by justinrummel** [comment]
Update your url in [_config.yml](https://github.com/Celyagd/celyagd.github.io/blob/master/_config.yml) to be HTTPS

**Comment by mmistakes** [comment]
Exactly what @justinrummel said. GitHub enabled https awhile back and if you don't use that in `url` assets will be served insecurely throwing those mixed content warnings in Chrome and other browsers.

**Comment by Celyagd** [comment]
Thanks, modification done !
