### ISSUE TITLE
Duplicated author name when no avatar is defined in _data/authors.yml

### ISSUE THREAD

**Issue by angolini** [mmistakes/minimal-mistakes#575]
- [ ] This is a question about using the theme.
- [ x ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ x ] This is a feature request.
- [ x ] I have updated all gems with `bundle update`.
- [ x ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** master
- **`github-pages` or `jekyll` gem version:** jekyll
- **Operating system:** Ubuntu 16.04

---

## Expected behavior

I have a *site* avatar configured in `_config.yml`, and I have no *author* avatar defined in `_data/authors.yml`.

I expect to have the site avatar displayed at home screen, and when I click on a post by that author, I have no avatar, only the Author name, bio, links, etc.

However what I see is a duplication of author's name just like in the picture:
![author-name-duplicated](https://cloud.githubusercontent.com/assets/1568936/19215470/82f0acea-8d75-11e6-8fbc-ed807a568063.png)

In the `_data/authors.yml` I have tried to use `avatar: ""` and not add any `avatar` at all, the same result.

So I thought it was a mistake in the `_includes/author-profile.html` and tried to debug it. I tried, for example:

` <div itemscope itemtype="http://schema.org/Person">
 
+{% if author.avatar %}
   <div class="author__avatar">
     {% if author.avatar contains "://" %}
        <img src="{{ author.avatar }}" alt="{{ author.name }}">
@@ -13,6 +14,7 @@
        <img src="{{ author.avatar | prepend: "/images/" | prepend: base_path }}" class="author__avatar" alt="{{ author.name }}">
     {% endif %}
   </div>
+{% endif %}
`
But, it looks like, because I have `site.author.avatar` on the `author.avatar` does exist, but is kind of empty somehow.

I solved this locally by using `avatar: 'none'` in `_data/authors.yml` and changing  `_includes/author-profile.html` by:

` <div itemscope itemtype="http://schema.org/Person">
 
+{% unless author.avatar == 'none' %}
   <div class="author__avatar">
     {% if author.avatar contains "://" %}
        <img src="{{ author.avatar }}" alt="{{ author.name }}">
@@ -13,6 +14,7 @@
        <img src="{{ author.avatar | prepend: "/images/" | prepend: base_path }}" class="author__avatar" alt="{{ author.name }}">
     {% endif %}
   </div>
+{% endunless %}
`

but I think it's far from a good solution. Anyway, I would not know which would be a good solution for the theme as maybe the default behavior would be use the site.author.avatar instead of displaying nothing like I'm doing now.

## Steps to reproduce the behavior

- assign a site avatar in the author from `_config.yml`
- create `_data/authors.yml` with one author **without** avatar
- assign a post to the author from `_data/authors.yml`.
- display the post

Please, let me know if you can reproduce the issue of if there is anything else I can provide. If you have an idea on how to better solve this I can prepare the patch if you want.

**Comment by mmistakes** [comment]
Yes this is definitely a bug. I recently fixed it in an unreleased version of the theme https://github.com/mmistakes/minimal-mistakes/commit/50d4b1b9a8eb4922aa6e8498b5b8f2c9ca52eae5. The fix is actually quite simple.

What you want to do is wrap the `author.avatar` bit in _includes/author-profile.html with a Liquid conditional that checks if there is an avatar image.

Wrap `<div class="author__avatar"></div>` like so and you should be all set.

```html
  {% if author.avatar %}
  <div class="author__avatar">
    {% if author.avatar contains "://" %}
    	<img src="{{ author.avatar }}" alt="{{ author.name }}">
    {% else %}
    	<img src="{{ author.avatar | prepend: "/images/" | prepend: base_path }}" class="author__avatar" alt="{{ author.name }}">
    {% endif %}
  </div>
  {% endif %}
```

Now when `avatar` is blank you won't get the empty `<img>` element on the page with `alt` showing the author name... making it look like it's duplicated.

**Comment by angolini** [comment]
Thanks for your help on this. I have tried it yesterday locally but maybe the browser cache confused me.

It worked in the server. There is a draft here https://imxdev.gitlab.io/tutorial/Install_SDL_devel/

And, let me take this opportunity to ask: Do you want the upstream of this patch:
https://gitlab.com/imxdev/imxdev.gitlab.io/commit/c51a3e312ff4ee33bde48d05a8bfabe47e0a9d9e

Thanks a lot for your time <3
