### ISSUE TITLE
Adding internal links into posts to other posts

### ISSUE THREAD

**Issue by icicimov** [mmistakes/minimal-mistakes#581]
- [x ] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.4.8
- **`github-pages` or `jekyll` gem version:** github-pages 96, jekyll 3.3.0
- **Operating system:** Linux

---

## Expected behavior

Adding internal links into posts does not work for me. For example when I include a link to some post like this:

```
Please see [GlusterFS internals]({% post_url 2015-11-13-GlusterFS-internals %}) for more details on GLusterFS extended attributes.
```

the URL rendered reads https://icicimov.github.io/high-availability/GlusterFS-internals/ instead of https://icicimov.github.io/blog/high-availability/GlusterFS-internals/ which is correct one.

## Steps to reproduce the behavior

Go to https://icicimov.github.io/blog/high-availability/GlusterFS-metadata-split-brain-recovery/ and click on the "GlusterFS internals" link about half way down the page.

**Comment by mmistakes** [comment]
Looks like you're using `baseurl: /blog` is this correct? If so I don't think Jekyll includes that property into `post_url`. Try prepending it.

```
{% post_url 2015-11-13-GlusterFS-internals | prepend: site.baseurl %}
```

Or you could do:

```
{{ site.baseurl }}{% post_url 2015-11-13-GlusterFS-internals %}
```

As this isn't a theme issue and is a general "how to use Jekyll" question I'm going to close it. If you need further help with `post_url` I'd suggest filing an issue on the [`jekyll/jekyll`](https://github.com/jekyll/jekyll) repo or ask for help on [talk.jekyllrb.com](https://talk.jekyllrb.com/)
