### ISSUE TITLE
ID of staticman comments section not sufficiently unique

### ISSUE THREAD

**Issue by lunaryorn** [mmistakes/minimal-mistakes#582]
The staticman comments section has the ID `#comments` which isn't really unique, given that kramdown automatically generates IDs from headlines.  Specifically, any "Comments" headline would also generate the ID `#comments`.  

I hit this when I added staticman to my blog which has an article about syntax highlighting which talks about source code comments in a section named, well, "Comments".

I solved the issue for my blog by prefixing the IDs generated by Kramdown, but I think the ID of the comments should be more unique nonetheless, e.g. `minimal-mistakes-staticman-comments` or so… just something that's less likely to conflict with a header ID.

**Comment by mmistakes** [comment]
Good catch. I'll have to double check by pretty sure I'm not using `#comments` anywhere so it could easily be removed from the `<section>` element.

**Comment by mmistakes** [comment]
Fixed in https://github.com/anbuchelva/anbuchelva.github.io/commit/1f7bd64c1389e86817de0cd6dbcf778fd8c9bc27 and will be in the next release of MM
