### ISSUE TITLE
How do we change the favicon in the title bar?

### ISSUE THREAD

**Issue by jocelyn-ong** [mmistakes/minimal-mistakes#585]
- [x] This is a question about using the theme.

---

## Environment informations

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** OS X El Capitan

**Comment by mmistakes** [comment]
There's no Jekyll magic here, favicons are loaded like you would for any other site (e.g. placing `favicon.ico` in your site's root). 

On the theme demo site I used http://realfavicongenerator.net/ to generate all of the sized icons from a single file, placed them in `assets/images` and then added the html it spit out to the [`_includes/head/custom.html`](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_includes/head/custom.html)

There's a bunch of ways to approach it, which you can search around for if the favicon generator I linked to above doesn't meet your needs.

**Comment by jocelyn-ong** [comment]
Thank you! If I don't want a favicon can I change the P to another letter? or is the P a default favicon?

**Comment by mmistakes** [comment]
Not sure what the P is you're referring to. The theme doesn't ship with a
default favicon so if you're seeing one it's from your web host being
defined at the server level... Not the theme.

**Comment by jocelyn-ong** [comment]
I got it to work! Thanks so much! Lovely theme by the way!

**Comment by lamastex** [comment]
Thanks! This was great explanation!
