### ISSUE TITLE
Cant seem to compile any saas

### ISSUE THREAD

**Issue by chrisvidal** [mmistakes/minimal-mistakes#594]
- [ x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x ] I have updated all gems with `bundle update`.
- [x ] I have tested locally with `bundle exec jekyll build`.

- **Minimal Mistakes version:** 
3.4.8
latest, just downloaded the master.zip

---

## Expected behavior

Hi

using the command

````cmd
bundle exec jekyll serve````

and if i change the bgcolor css in the body for example, nothing happen, no compilation and no new stylesheet generated.

Any idea what i am missing here please ?

## Steps to reproduce the behavior
my repo https://github.com/chrisvidal/death-notes/

**Comment by mmistakes** [comment]
When running Jekyll locally you need to change `url: http://localhost:4000` in _config.yml otherwise it'll use your domain instead and load the CSS there. That's why you're not seeing your changes.

**Comment by chrisvidal** [comment]
OK @mmistakes thank you.
so im using this command line now and it is working fine
````cmd
bundle exec jekyll serve --config _config.yml,_config.dev.yml
````

however, it is normal that the regeneration time is flirting with 20s ?

**Comment by mmistakes** [comment]
Yes that's normal. The more posts the longer the generation time. My personal site takes minutes to build so count yourself lucky yours is in there seconds.

**Comment by chrisvidal** [comment]
i have one post for now :)
ok good to know, not really a problem when you are writing post actually.
thanks
