### ISSUE TITLE
What is the best way to add javascript libraries?

### ISSUE THREAD

**Issue by zfrenchee** [mmistakes/minimal-mistakes#605]
- [x] This is a question about using the theme.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

I'd like to add a javascript library, e.g. underscore.js, to my site.

My intuition was that just placing the file in `assets/js/` would cause it to show up in the scripts. That didn't work. Neither did putting it in the `vendor` or `plugin` subfolders. Neither did putting it in those folder and manually adding it to the list of files in the grunt task, which was surprising. 

The way I managed to work around this was to add a line to `includes/script.html` but that means my library isn't being minified with the rest of the stuff in `main.min.js` which I would have liked. Is there some proper way to get my library into `main.min.js` ?

**Comment by mmistakes** [comment]
See the docs. Having it concatenated and minified into `main.min.js` requires a build step.

https://mmistakes.github.io/minimal-mistakes/docs/javascript/

**Comment by zfrenchee** [comment]
Thanks!
