### ISSUE TITLE
collapse sidebar to hamburger

### ISSUE THREAD

**Issue by seiyria** [mmistakes/minimal-mistakes#607]
- [x] This is a feature request.

---

Is it possible to collapse the sidebar into a hamburger menu? I know it works for a really large top menu, but I have a large side menu and I'm looking for ways to improve the mobile experience. You can [see my site here](http://seiyria.com/drakkar/scenarios/sdc/lairs).

Unfortunately most users of my site get breakpointed for mobile on their laptops (1366x768 res) which makes it tough to do anything meaningful and still make it so they have a decent view of data.

**Comment by mmistakes** [comment]
Will have to think about it. My intention for the sidebars weren't as full blown navigation components... but I get the appeal of using them that way. Kind of set myself up for it when I built it specifically for the theme docs.

Perhaps could do something similar to what I've done on [my personal site](https://mademistakes.com/articles/using-jekyll-2016/). When the screen size collapses down the nav list turns into a toggle.

![toc-reveal](https://cloud.githubusercontent.com/assets/1376749/20399153/f37e3c22-acbd-11e6-914a-50c146117b57.gif)

**Comment by seiyria** [comment]
I definitely agree with you, but in my case that's how I ended up having to use them. Having everything along the top would have been suicide in a different way. What you have there looks nice, by the way, I think that's a reasonable solution.

**Comment by mmistakes** [comment]
Merged in https://github.com/mmistakes/minimal-mistakes/commit/cdf5877acc9a54760768f594cda2d540b2d17886

Will show up in the next release of MM.

![sidebar-nav-list-toggle](https://cloud.githubusercontent.com/assets/1376749/20406851/f439acf4-acdc-11e6-9ad6-25d943fdaa38.gif)
