### ISSUE TITLE
GitHub Metadata Warnings/Errors

### ISSUE THREAD

**Issue by mones-cse** [mmistakes/minimal-mistakes#608]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
---
## Environment informations

- **Minimal Mistakes version: current master** 
- **`github-pages` or `jekyll` gem version:3.3.0** 
- **ubuntu 16.04 LTS** 
---
## Steps to reproduce the behavior

when i do `bundle exec jekyll server` it work just fine but if i change any post during the server is running i got an error 
`
Server running... press ctrl-c to stop.
`
`
      Regenerating: 1 file(s) changed at 2016-10-23 14:30:10    GitHub Metadata: GET https://api.github.com/orgs/mones-cse: 404 - Not Found // See: https://developer.github.com/v3`
here is my [_config.yml](https://github.com/mones-cse/mones-blog/blob/gh-pages/_config.yml) file.
at this point i am confiused where is the problem :(

**Comment by mones-cse** [comment]
i tried `bundle exec jekyll server --verbose`
output is 
`
 GitHub Metadata: Initializing...
   GitHub Metadata: Calling @client.contributors("mones-cse/mones-blog")
   GitHub Metadata: Calling @client.repository("mones-cse/mones-blog")
   GitHub Metadata: Calling @client.organization("mones-cse")
   GitHub Metadata: GET https://api.github.com/orgs/mones-cse: 404 - Not Found // See: https://developer.github.com/v3
   GitHub Metadata: Calling @client.list_repos("mones-cse", {"type"=>"public"})
   GitHub Metadata: Calling @client.releases("mones-cse/mones-blog")
`

**Comment by mmistakes** [comment]
I don't know what the issue is but those errors suggest it has to do with [`github-metadata`](https://github.com/jekyll/github-metadata) and not the theme. 

I'd file an issue there and see if they can help.
