### ISSUE TITLE
Don't work tags & categoties

### ISSUE THREAD

**Issue by npofopr** [mmistakes/minimal-mistakes#620]
[ ] This is a question about using the theme.
[ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
[ ] This is a feature request.
[x] I have updated all gems with `bundle update`.
[x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** v.3.4.8
- **`github-pages` or `jekyll` gem version:** github-pages 100
- **Operating system:** Windows 10 build 1607

---

## Expected behavior

Don't work, don't generated tags and categories. 
http://altyncev.ru/blog/task_complite/
Repository: https://github.com/npofopr/_altyncev/
Locally don't work too.

> ERROR `/tags/' not found.

## Steps to reproduce the behavior

I'm installed clean mmistakes
https://npofopr.github.io/mmistakes_test/blog/task_complite/
repository https://github.com/npofopr/mmistakes_test

But problem still exists.

**Comment by mmistakes** [comment]
You're missing the [`tags.md`](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_pages/tag-archive.html) page. Create that and tag links will work.

Consult the archive settings portion of the docs for more info. https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings

**Comment by npofopr** [comment]
How easy. Thank you!
