### ISSUE TITLE
Blog post don't appear in pages

### ISSUE THREAD

**Issue by saguiitay** [mmistakes/minimal-mistakes#627]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.4.8
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** Working directly in GitHub

---

## Expected behavior

Blog posts should be fully supported on a page

## Steps to reproduce the behavior

I created a page: https://github.com/saguiitay/saguiitay.github.io/blob/master/_pages/blog/index.html

I've also configured `_config.yml' (https://github.com/saguiitay/saguiitay.github.io/blob/master/_config.yml) as follow:

  - url                      : http://www.saguiitay.com
  - baseurl                  : 
  - permalink: /:year/:month/:day/:title/
  - paginate: 5 # amount of posts to show
  - paginate_path: /blog/page:num/

However, the create page doesn't include any posts: http://www.saguiitay.com/blog/

**Comment by mmistakes** [comment]
Not a bug, it's related to how you have Jekyll setup. You're using `site.paginator` twice and [Jekyll Paginate](https://jekyllrb.com/docs/pagination/) only allows one instance of it.

You're using it on your home page at `<site root>/index.html` and also in `_pages/blog/index.html`. I'd suggest changing your home page to:

```html
{% for post in site.posts limit:3 %}
  {% include archive-single.html %}
{% endfor %}
```

which will show the 3 most recent posts (which you're essentially doing now), and then on your blog page all of the posts will show with pagination.

And then move `_pages/blog/index.html` to `<site root>/blog/index.html`. For whatever reason those need to be in the root and not stuffed into a `_pages` folder.

After that your blog page should appear as you want.

![blog-page](https://cloud.githubusercontent.com/assets/1376749/19933281/342d3678-a0e9-11e6-87ab-9f11ff679129.jpg)

You also have some layout issues with pages in your root folder `posts.html` and `tags.html`. They're calling for `layout: post-index` which doesn't exist. Check the errors Jekyll produces on `bundle exec jekyll build` for more info.

**Comment by saguiitay** [comment]
I've fixed the pagination in the homepage, and moved the blog/index.html page as explained. This indeed results in the posts appearing in the blog page.

However, the posts are always displaying the last page:
![capture](https://cloud.githubusercontent.com/assets/1009589/19935341/66556e84-a122-11e6-8e4c-778f524f0125.PNG)

Also, the links in the paginator are incorrect - they point to (for example) http://www.saguiitay.com/page22/ instead of http://www.saguiitay.com/blog/page22/ even though I've configured `paginate_path` to `/blog/page:num/`

**Comment by mmistakes** [comment]
I'd file an issue on [`jekyll-paginate`](https://github.com/jekyll/jekyll-paginate) as it's related to that plugin and not the theme. It has been deprecated though. My understanding is it has some problems.

I've never tried to paginate a non-homepage before so that could explain the strange behavior.

**Comment by sdruskat** [comment]
FWIW, I've just tried to achieve something similar, i.e., a site using a splash page at `/`, and the paginated archive at `/blog/`, and it works with the following slightly weird setup.

- `<site-root>/index.html` as per default, but added `permalink: /blog/` in YAML metadata
- `_layouts/home.html` as per default
- `_pages/home.md` with `layout: splash` and `permalink: /`

Works like a spell, so either this is just a less semantic way of achieving this, or the paginate plugin has been fixed.
