### ISSUE TITLE
Cannot run jekyll serve

### ISSUE THREAD

**Issue by pizzapgh** [mmistakes/minimal-mistakes#640]
I followed the quick start directions:

Quick Start

Add this line to your Jekyll site's Gemfile:

gem "minimal-mistakes-jekyll"
Add this line to your Jekyll site's _config.yml file:

theme: minimal-mistakes-jekyll
Then run Bundler to install the theme gem and dependencies:

bundle install
To update the theme run bundle update.

Then I run jekyll serve and I get this error down below. 

C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:40:in `block in setup': You have already
activated addressable 2.5.0, but your Gemfile requires addressable 2.4.0. Prepending `bundle exec` to your command may s
olve this. (Gem::LoadError)

**Comment by flohw** [comment]
You have to run `bundle exec jekyll serve` in order to make it works.
It's like you have installed all the gems locally in your working directory instead of installing them globally on the system. So jekyll (wich is global) doesn't know the gems you've installed locally.

**Comment by pizzapgh** [comment]
Man, you right!!!! *jumping up and down* 
Thanks flohw. You made my night.
