### ISSUE TITLE
Liquid Exception: undefined method `gsub' for nil:NilClass in _includes/head.html, included in _layouts/default.html

### ISSUE THREAD

**Issue by icicimov** [mmistakes/minimal-mistakes#646]
- [x] This is a question about using the theme.

---

## Environment informations

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** 
$ bundle show github-pages
/var/lib/gems/2.3.0/gems/github-pages-28
$ bundle show jekyll
/var/lib/gems/2.3.0/gems/jekyll-2.4.0
- **Operating system:** 
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

---
Hi all,

I realise this is not related to the theme but just wonder if anyone else had to deal with this kind of issue. It sudden;y happened after system and kernel update.

$ bundle exec jekyll serve --port 4445 --config _config.yml,_config.dev.yml --watch --detach --trace &
[1] 25262
$ /var/lib/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: key "index0" is duplicated and overwritten on line 46
Configuration file: _config.yml
Configuration file: _config.dev.yml
            Source: /home/igorc/blog
       Destination: /home/igorc/blog/_site
      Generating... 
              Lunr: Creating search index...
              Lunr: Index ready (lunr.js v0.4.5)
  Liquid Exception: undefined method `gsub' for nil:NilClass in _includes/head.html, included in _layouts/default.html
/var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/tags/include.rb:121:in `rescue in render': undefined method `gsub' for nil:NilClass (Jekyll::Tags::IncludeTagError)
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/tags/include.rb:113:in `render'
	from /var/lib/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/block.rb:109:in `block in render_all'
	from /var/lib/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `each'
	from /var/lib/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `render_all'
	from /var/lib/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/block.rb:82:in `render'
	from /var/lib/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/template.rb:128:in `render'
	from /var/lib/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/template.rb:138:in `render!'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:106:in `render_liquid'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:205:in `render_all_layouts'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:239:in `do_layout'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/page.rb:122:in `render'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:269:in `block in render'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `each'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `render'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:46:in `process'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/command.rb:28:in `process_site'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:55:in `build'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:33:in `process'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.3.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

Any help appreciated.
Thanks,
Igor

**Comment by icicimov** [comment]
Bundler and liquid versions in case anyone knows about any related bugs:

$ bundle show bundle
/var/lib/gems/2.3.0/gems/bundler-1.13.6
$ bundle show liquid
/var/lib/gems/2.3.0/gems/liquid-2.6.1

**Comment by mmistakes** [comment]
Looks like a plugin issue to me. Are you using a Jekyll search plugin? I see some errors related to Lunr which I believe does search.

**Comment by mmistakes** [comment]
Also check your _config.yml. The error report you pasted above says there's a problem on line 46.

**Comment by mmistakes** [comment]
One other thing. You're using really old versions of Jekyll. Looks like version 2.4 to me and there theme required 3.0 or newer.

Try running `bundle update` or `bundle update jekyll` to upgrade to the latest versions. That should help with the Liquid errors.

**Comment by icicimov** [comment]
Hi Michael,

Thanks for your swift reply. First this is what I have in line 46 in my _config.yml

     42   generatedFields:
     43     date:
     44       type               : "date"
     45       options:
     46         format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
     47 atom_feed:
     48   path                   : # blank (default) uses feed.xml

This is the result of updating jekyll:

$ bundle update jekyll
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using RedCloth 4.2.9
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.1
Using thread_safe 0.3.5

Your user account isn't allowed to install to the system Rubygems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to Rubygems using sudo.

  Password: 
Installing public_suffix 2.0.4
Using blankslate 2.1.2.4
Using fast-stemmer 1.0.2
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using colorator 0.1
Using multipart-post 2.0.0
Using ffi 1.9.14
Using gemoji 2.1.0
Using jekyll-paginate 1.1.0
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using kramdown 1.3.1
Using liquid 2.6.1
Using mercenary 0.3.6
Using posix-spawn 0.3.12
Using yajl-ruby 1.1.0
Using redcarpet 3.1.2
Using safe_yaml 1.0.4
Using mini_portile2 2.1.0
Using jekyll-sitemap 0.6.0
Using maruku 0.7.0
Using rdiscount 2.1.7
Using jekyll-feed 0.7.2
Using libv8 3.16.14.15
Using ref 2.0.0
Using bundler 1.13.6
Using tzinfo 1.2.2
Installing addressable 2.5.0 (was 2.4.0)
Using parslet 1.5.0
Using classifier-reborn 2.0.4
Using coffee-script 2.4.1
Using faraday 0.9.2
Using rb-inotify 0.9.7
Using jekyll-sass-converter 1.2.0
Using pygments.rb 0.6.0
Using nokogiri 1.6.8.1
Using therubyracer 0.12.2
Using activesupport 4.2.7.1
Using toml 0.1.2
Using jekyll-coffeescript 1.0.0
Using sawyer 0.8.0
Using listen 3.0.8
Using jekyll-lunr-js-search 3.2.0
Using html-pipeline 1.9.0
Using octokit 4.6.0
Using jekyll-watch 1.5.0
Using jekyll-gist 1.4.0
Using jekyll 2.4.0
Using jekyll-mentions 0.1.3
Using jekyll-redirect-from 0.6.2
Using jemoji 0.3.0
Using github-pages 28
Bundle updated!

$ bundle show jekyll
/var/lib/gems/2.3.0/gems/jekyll-2.4.0

Loks to me something is preventing the update to jekyll 3.0. Now the thing is I'm very much sure I had jekyll 3.0 running but seems like it got downgraded at some point due to some dependencies.

Thanks,
Igor

**Comment by icicimov** [comment]
The content of my Gemfile.lock file:

$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    RedCloth (4.2.9)
    activesupport (4.2.7.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.5.0)
      public_suffix (~> 2.0, >= 2.0.2)
    blankslate (2.1.2.4)
    classifier-reborn (2.0.4)
      fast-stemmer (~> 1.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    colorator (0.1)
    execjs (2.7.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    fast-stemmer (1.0.2)
    ffi (1.9.14)
    ffi (1.9.14-x64-mingw32)
    gemoji (2.1.0)
    github-pages (28)
      RedCloth (= 4.2.9)
      jekyll (= 2.4.0)
      jekyll-coffeescript (= 1.0.0)
      jekyll-mentions (= 0.1.3)
      jekyll-redirect-from (= 0.6.2)
      jekyll-sass-converter (= 1.2.0)
      jekyll-sitemap (= 0.6.0)
      jemoji (= 0.3.0)
      kramdown (= 1.3.1)
      liquid (= 2.6.1)
      maruku (= 0.7.0)
      pygments.rb (= 0.6.0)
      rdiscount (= 2.1.7)
      redcarpet (= 3.1.2)
    html-pipeline (1.9.0)
      activesupport (>= 2)
      nokogiri (~> 1.4)
    i18n (0.7.0)
    jekyll (2.4.0)
      classifier-reborn (~> 2.0)
      colorator (~> 0.1)
      jekyll-coffeescript (~> 1.0)
      jekyll-gist (~> 1.0)
      jekyll-paginate (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 2.6.1)
      mercenary (~> 0.3.3)
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      safe_yaml (~> 1.0)
      toml (~> 0.1.0)
    jekyll-coffeescript (1.0.0)
      coffee-script (~> 2.2)
    jekyll-feed (0.7.2)
    jekyll-gist (1.4.0)
      octokit (~> 4.2)
    jekyll-lunr-js-search (3.2.0)
      json (~> 1.8)
      nokogiri (~> 1.6)
      therubyracer (~> 0.12)
    jekyll-mentions (0.1.3)
      html-pipeline (~> 1.9.0)
      jekyll (~> 2.0)
    jekyll-paginate (1.1.0)
    jekyll-redirect-from (0.6.2)
      jekyll (~> 2.0)
    jekyll-sass-converter (1.2.0)
      sass (~> 3.2)
    jekyll-sitemap (0.6.0)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    jemoji (0.3.0)
      gemoji (~> 2.0)
      html-pipeline (~> 1.9)
      jekyll (~> 2.0)
    json (1.8.3)
    kramdown (1.3.1)
    libv8 (3.16.14.15)
    liquid (2.6.1)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    maruku (0.7.0)
    mercenary (0.3.6)
    mini_portile2 (2.1.0)
    minitest (5.9.1)
    multipart-post (2.0.0)
    nokogiri (1.6.8.1)
      mini_portile2 (~> 2.1.0)
    nokogiri (1.6.8.1-x64-mingw32)
      mini_portile2 (~> 2.1.0)
    octokit (4.6.0)
      sawyer (~> 0.8.0, >= 0.5.3)
    parslet (1.5.0)
      blankslate (~> 2.0)
    posix-spawn (0.3.12)
    public_suffix (2.0.4)
    pygments.rb (0.6.0)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.1.0)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    rdiscount (2.1.7)
    redcarpet (3.1.2)
    ref (2.0.0)
    safe_yaml (1.0.4)
    sass (3.4.22)
    sawyer (0.8.0)
      addressable (>= 2.3.5, < 2.6)
      faraday (~> 0.8, < 0.10)
    therubyracer (0.12.2)
      libv8 (~> 3.16.14.0)
      ref
    thread_safe (0.3.5)
    toml (0.1.2)
      parslet (~> 1.5.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    yajl-ruby (1.1.0)

PLATFORMS
  ruby
  x64-mingw32

DEPENDENCIES
  github-pages
  jekyll-feed
  jekyll-gist
  jekyll-lunr-js-search
  jekyll-paginate
  jekyll-sitemap
  jemoji

BUNDLED WITH
   1.13.6

**Comment by mmistakes** [comment]
It's related to your Ruby environment. Google will probably turn up more help for you.

You can run Bundler with `sudo` and that will prompt you for your password which should let you update the gems as the error message above suggests.

```
sudo bundle update
```

The error you pasted above also suggests running `bundle install --path vendor/bundle` if you don't want to go the `sudo` route. Just follow the error message suggestions, they're usually pretty good at pointing you in the right direction.

And if that fails try a site like Stackoverflow Jekyll Talk forums are another good place to turn if Googling the specific error msg doesn't turn up something.

**Comment by icicimov** [comment]
Thanks Michael I'll do so.

**Comment by icicimov** [comment]
Just an update, I think the problem is with the RedCloth extension in ruby:

Your bundle is locked to RedCloth (4.2.9), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of RedCloth (4.2.9) has removed it. You'll need to update your bundle to a different version of RedCloth (4.2.9) that hasn't been removed in order to install.

**Comment by mmistakes** [comment]
Redcloth isnt a dependrncy currently used. Best I remember it was with Jekyll many versions ago. I'd ditch your Gemfile.lock and start fresh leaving just `Gemfile` and then run `bundle install`.

Or use the new theme gem if you're not hosting with GitHub. 

https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

**Comment by icicimov** [comment]
Michael, removing the lock file did the trick! I thought the same and was just going to replace the `Gemfile.lock` with the one from the github pages when I saw your last comment.

Thanks a lot for your help.

Cheers,
Igor
