### ISSUE TITLE
coderay not working on github page

### ISSUE THREAD

**Issue by vikas5914** [mmistakes/minimal-mistakes#65]
Hey . coderay is not working on github page . 

http://mmistakes.github.io/minimal-mistakes/code-highlighting-post/

also if you use category function  like this "category: tutorials" instead of "category: [tutorials] ". its work perfect

**Comment by rahul-rkt** [comment]
Github pages runs on a minimal configuration. The details of installed dependencies and versions are listed [here](https://pages.github.com/versions/).

As CodeRay is not installed, if you try to build directly from Github, it is not going to tokenize your code blocks. There is an easy workaround for this, just build your site locally where it will generate the proper tokens and maintain the actual build on your username.github.io repository.
