### ISSUE TITLE
Read time no displayed for posts

### ISSUE THREAD

**Issue by ashleyconnor** [mmistakes/minimal-mistakes#657]
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** minimal-mistakes-jekyll (4.0.7)
- **`github-pages` or `jekyll` gem version:**  jekyll 3.3.1
- **Operating system:**  OSX/S3
---

## Expected behavior

Read time to be displayed for each blog post

## Steps to reproduce the behavior

[https://github.com/ashleyconnor/blog](https://github.com/ashleyconnor/blog)
[ashleyconnor.co.uk](http://ashleyconnor.co.uk)

Below you can see the `fa-clock` but no time.

![https://www.dropbox.com/s/5sj1q3cb2vyee7g/Screenshot%202016-11-18%2008.30.32.png?dl=1](https://www.dropbox.com/s/5sj1q3cb2vyee7g/Screenshot%202016-11-18%2008.30.32.png?dl=1)

**Comment by mmistakes** [comment]
You're missing one small config line. Add `words_per_minute: 200` to your **_config.yml** and it should work.

**Comment by ashleyconnor** [comment]
I'll try that tonight. The docs make it sound like there's a default of 200 already and I only need to add the config entry to override that value.

>Reading Time

>Enable estimated reading time snippets with read_time: true in YAML Front Matter. 200 has been set as the default words per minute value — which can be changed by adjusting words_per_minutes: in _config.yml.

**Comment by mmistakes** [comment]
Going to make a fix to _includes/read-time.html that properly sets `words_per_minute` if it's omitted from the config file.

The new theme gem way of installing doesn't include it. So the fix for now is adding to your config. That and you'll probably want to add `locale: en` as well since I noticed that missing.

**Comment by mmistakes** [comment]
Fixed in https://github.com/mmistakes/minimal-mistakes/commit/f9e36767c2a5a3449b4c4e1c64e7fa8fd5040821
