### ISSUE TITLE
Long sidebar overlaps with post content when unfolded

### ISSUE THREAD

**Issue by carlesfernandez** [mmistakes/minimal-mistakes#668]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.0.8
- **`github-pages` version:** 104
- **Operating system:** macOS Sierra

---

## Expected behavior

A long sidebar overlaps with post content when the menu is unfolded, when using Chrome for Android. It looks good (i.e., the menu folds and unfolds correctly) in Chrome for desktop/laptops.

 
## Steps to reproduce the behavior

Example: 
  Web: http://gnss-sdr.org/news/ 
  Repo: https://github.com/gnss-sdr/geniuss-place
  Using GitHub Pages

How it is rendered by Chrome for Android when menu is unfolded:

[![Screenshot from a Nexus 5](https://s17.postimg.org/wjtu83ie7/Screenshot_20161121_191643.png)](https://postimg.org/image/cp7slz36j/)

**Comment by mmistakes** [comment]
Will have to see if I can reproduce it. Sure looks like this issue from before related to the "sticky" sidebar.

https://github.com/mmistakes/minimal-mistakes/issues/396

**Comment by carlesfernandez** [comment]
I've done some theme customization, so maybe I've messed up things at some point. Thanks for looking it up, and of course also for this awesome theme!

**Comment by mmistakes** [comment]
I think I know what the issue is. On screen sizes `1024` and up, `position: sticky` is being applied to the sidebar. I have the sidebar nav list showing up at `1023` so it's having the sticky position applied. Which is screwing up the layout.

Shouldn't take much CSS to fix it.

**Comment by mmistakes** [comment]
@carlesfernandez Just to be sure it's not due to a customization you did (I don't think it is :smile:) can you verify if this page looks messed up too in Chrome for Android?

https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

**Comment by carlesfernandez** [comment]
Yes, this page suffers from the same problem:

[![Screenshot_20161121-212543.png](https://s14.postimg.org/ndo0a0a69/Screenshot_20161121_212543.png)](https://postimg.org/image/am9u3i0e5/)

**Comment by mmistakes** [comment]
OK. Thanks for checking. It's definitely not the `sticky` class. Looks like only part of the sidebar overlaps. Think it might have something to do with how Chrome on Android handles viewport units.

Might need to change `100vh` to `100%` in [_navigation.scss](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_navigation.scss#L449)

```diff
.nav__list input:checked ~ .nav__items {
    -webkit-transition: 0.5s ease-in-out;
    transition: 0.5s ease-in-out;
-   max-height: 100vh;
+   max-height: 100%;
    overflow: visible;
    opacity: 1;
    margin-top: 1em;
    -webkit-transform: translate(0, 0);
    -ms-transform: translate(0, 0);
    transform: translate(0, 0);
}
```

**Comment by mmistakes** [comment]
Seeing it in Firefox's responsive web tester. Changing `max-height: 100vh` to `max-height: 100%` appears to fix it. Can you confirm if it fixes it for Chrome for Android since I have no way of testing that?

![firefox](https://cloud.githubusercontent.com/assets/1376749/20499749/d732e9f0-b000-11e6-9837-51e928bfc0b6.jpg)

**Comment by carlesfernandez** [comment]
You nailed it!

I confirm this change solves the issue in Chrome for Android. Thank you!

**Comment by mmistakes** [comment]
Fantastic. Thanks for identifying and testing the bug.
