### ISSUE TITLE
Favicon icon and gallery question

### ISSUE THREAD

**Issue by icicimov** [mmistakes/minimal-mistakes#672]
- [ x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** github-pages-102, jekyll-3.3.0
- **Operating system:** 

Hi,

I have couple of issues that can't figure out solution for.

1. I dropped favicon.ico file in the root of my repository but still seeing: ERROR `/favicon.ico' not found
2. Created a gallery on one of the posts, see https://icicimov.github.io/blog/high-availability/Tomcat7-clustering-and-session-replication/, but when clicking on the images they open in the current window instead in gallery overlay. I folowed the instruction on the helpers page https://mmistakes.github.io/minimal-mistakes/docs/helpers/. What am I doing wrong? Anything else needed for this feature to start working?

Thanks as always.
Igor

**Comment by mmistakes** [comment]
1. I think with GitHub Pages hosted sites you also have to set the favicon path using `<link>`, dropping `favicon.ico` in the root isn't enough. http://stackoverflow.com/questions/30551501/unable-to-set-favicon-using-jekyll-and-github-pages
2. Something is wrong with your JavaScript which is causing the overlay script to not fire. When I open up the web inspector console I see the following errors.

```javascript
Uncaught SyntaxError: Unexpected identifier                                     (index):811
Uncaught TypeError: $(...).fitVids is not a function(…)                         main.min.js:5
```

My guess is you've added some JS to the theme's default and that's causing a conflict. Clear up the errors and the lightbox overlay should work.

**Comment by icicimov** [comment]
Thanks Michael, fixed and all working now as expected.

Cheers,
Igor
