### ISSUE TITLE
Why doesn't my page titles display properly on Google Plus?

### ISSUE THREAD

**Issue by bpshbp** [mmistakes/minimal-mistakes#686]
Why doesn't my page titles display properly on Google Plus?

Example:

http://share-ask.com/ideal-bedroom-partner/
Any ideas?

- [ ] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** 

---

**Comment by mmistakes** [comment]
From the looks of that link it's not a Minimal Mistakes theme site so I can't help you. Feel free to share a live example that's using MM so I can investigate.

**Comment by bpshbp** [comment]
No i dont use Minimal Mistakes theme ,stilll can you help me

**Comment by mmistakes** [comment]
Try https://talk.jekyllrb.com/

**Comment by bpshbp** [comment]
i tried almost every where bt its not helpg
