### ISSUE TITLE
Undefined method 'include?' when running bundler exec jekyll serve

### ISSUE THREAD

**Issue by absolutejam** [mmistakes/minimal-mistakes#692]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** Latest (Cloned from repo yesterday)
- **`github-pages` gem version:** 39
- **`jekyll` gem version:** 2.4.0
- **Operating system:** Ubuntu Mate 16.04 (Running in docker container)
- **ruby version:** ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
---

## Expected behavior

Site should be generated! :(

## Steps to reproduce the behavior

Clone https://github.com/absolutejam/jekyll-minmistakes-issue and `docker up` to build the image and run as I would.

The error I'm getting is:
```
jekyll_1  | Configuration file: /jekyll-data/_config.yml
jekyll_1  |             Source: /jekyll-data
jekyll_1  |        Destination: /jekyll-data/_site
jekyll_1  |       Generating... 
jekyll_1  |   Liquid Exception: undefined method `include?' for 0.5:Float in _includes/page__hero.html, included in _layouts/single.html
jekyll_1  | jekyll 2.4.0 | Error:  undefined method `include?' for 0.5:Float
jekyll_jekyll_1 exited with code 1
```

**Comment by mmistakes** [comment]
You're using very old versions of both Jekyll and the `github-pages` gem. This theme requires Jekyll 3+. Please update and report back if the error still exists.

For reference:

| Gem | Your Version | Latest Version |
| --- | -------------- | --------------- |
| [Jekyll](https://rubygems.org/gems/jekyll) | 2.4.0 | 3.3.1 |
| [Github Pages](https://github.com/github/pages-gem) | 39 | 105 |

**Comment by absolutejam** [comment]
Well this is embarrassing, haha. I just grabbed the Gemfile from the github pages site like I had done in the past (I'm coming back to using Jekyll with your amazing <3 theme again after a hiatus). I'll have to figure out the best way of grabbing the latest versions! Duh!

Thanks for your help, your contributions and patience! Have a great weekend.

**Comment by mmistakes** [comment]
Provided you have `gem 'github-pages'` in your `Gemfile` then running `bundle update` should do the trick.

There's a bug with updating I've seen mention of so you might need to swap that line with this instead to force the update:

```
gem 'github-pages', '104', group: :jekyll_plugins
```

**Comment by absolutejam** [comment]
That's exactly what I needed! Brilliant, thanks :+1:
