### ISSUE TITLE
Dynamic `words_per_minute` "less than" and "minute read" values

### ISSUE THREAD

**Issue by iamsk** [mmistakes/minimal-mistakes#703]
branch: master

It's better make 180 and 360 related to words_per_minute setting.
Different type of article have different reading speed as your design.

Thanks for your creating this amazing theme.

**Comment by mmistakes** [comment]
`word_per_minute` is [configurable](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#reading-time). 

Feel free to change it to a different value in your **_config.yml** if the `200` default doesn't work for you.

**Comment by iamsk** [comment]
What I mean is this part ```{% if words < 180 %}
  {{ site.data.ui-text[site.locale].less_than | default: "less than" }} 1 {{ site.data.ui-text[site.locale].minute_read | default: "minute read" }}
{% elsif words < 360 %}
  1 {{ site.data.ui-text[site.locale].minute_read | default: "minute read" }}```
