### ISSUE TITLE
Sidebar: Not able to see overflow content in sidebar until scroll down till the end of the page.

### ISSUE THREAD

**Issue by vanlong441** [mmistakes/minimal-mistakes#706]
http://i.imgur.com/RUfHq1w.png --> Scroll down to half a page
http://i.imgur.com/u270pcc.png --> Scroll down to the bottom of the page

**Comment by mmistakes** [comment]
Unfortunately there is no way around this without introducing a scrollbar or something similar on the sidebar.

Your only option is to disable the "sticky" sidebar and then it will scroll with the rest of the page content. If you want to go with that solution [remove the `sticky` class](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/sidebar.html#L2) from the sidebar.

**Comment by vanlong441** [comment]
@mmistakes I suggest that the y-scrollbar become visible when mouseover with x-scrollbar always hidden...

**Comment by mmistakes** [comment]
Happy to look at a pull request if you want to submit a fix.

**Comment by mmistakes** [comment]
Added support for sidebar scrollbars when needed in https://github.com/mmistakes/minimal-mistakes/commit/3e347970c7c632658976f1debcc622eb8ed88a90

**Comment by rashevskyv** [comment]
With sticky class on in mobile view content moves under the screen

http://prntscr.com/fzak4u - w\o sticky
http://prntscr.com/fzakyz - w sticky

**Comment by mmistakes** [comment]
@rashevskyv The theme purposely [doesn't apply `position: sticky`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_utilities.scss#L356-L367) to those elements on < `1024` pixel wide screens for this very reason. 

Are you using a modified version of the theme? You'll probably need some JavaScript to make it work.

**Comment by rashevskyv** [comment]
Yes, it is modified, but only in some variables. On clean mm it works fine? 
btw, page has alot of menu - 
![image](https://user-images.githubusercontent.com/18294541/28509381-9abc5a96-704a-11e7-8c92-af4c1c08d14b.png)
