### ISSUE TITLE
Youtube social links use legacy URL format

### ISSUE THREAD

**Issue by denkyuu** [mmistakes/minimal-mistakes#716]
- [x] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [x] This is a feature request. (kinda)
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.1.0  
- **`github-pages` or `jekyll` gem version:** Jekyll gem version
- **Operating system:** Windows 10 WSL (Ubuntu)

---

## Expected behavior

Youtube social links (in sidebar and about) should be able to link to current url structure for channels:

http://www.youtube.com/channel/<CHANNEL_ID>
http://www.youtube.com/c/<CUSTOM_URL>

Currently, the author.youtube variable is being injected into the legacy format:

http://www.youtube.com/user/<USERNAME>

This only works with older channels created before the structure changed.

## Steps to reproduce the behavior

Add a channel ID or custom url to _config.yml. 

After searching the repo, I found a couple of spots where the url is built from author.youtube, but I think that code is bundled in the gem, so I don't know how to edit it.

**Comment by mmistakes** [comment]
If you add the entire URL to your YouTube channel (eg. `youtube: https://youtube.com/c/customURL`) in _config.yml you should be all set.

Adding a username still works like it used. There's a check for `://` now to determine which format to use.

**Comment by scienceopen** [comment]
Thank you! I had manually edited the code to do this; I really appreciate allowing the whole URL as a trigger for custom behavior!
