### ISSUE TITLE
In _data/ui-text.yml ,invalid leading UTF-8 octet at line 1 column 1

### ISSUE THREAD

**Issue by TU-RUI** [mmistakes/minimal-mistakes#724]
when i run  "bundle exec jekyll serve",i got `jekyll 3.3.1 | Error:  (/home/turui/Downloads/blog/_data/ui-text.yml): invalid leading UTF-8 octet at line 1 column 1
` why

**Comment by mmistakes** [comment]
I believe it's an encoding issue not related to the theme. I'd Google around for some solutions as it has to do with your environment.

https://www.google.com/search?q=invalid+leading+UTF-8+octet&ie=UTF-8&oe=UTF-8

**Comment by mmistakes** [comment]
Closing this issue as it appears to be addressed. If not feel free to re-open with additional information to help debug the issue.
