### ISSUE TITLE
Option for cdn for static assets

### ISSUE THREAD

**Issue by weikinhuang** [mmistakes/minimal-mistakes#726]
Please include an option to use a cdn for jquery and font awesome to save on bandwidth costs when using a self hosted option.

- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [x] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

**Comment by mmistakes** [comment]
Building an option to use a CDN version of jQuery would introduce several complexities to the theme I'm not comfortable adding.

As far as using a CDN version of Font Awesome, that's fairly easy to do. You have two options depending on how you installed the theme:

## Installed as a theme gem

1. In the root of your site folder add [`_sass/vendor/font-awesome/_variables.scss`](https://github.com/mmistakes/minimal-mistakes/blob/f4df3d459b41ebba3c6b90454ea826e6f2ecda45/_sass/vendor/font-awesome/_variables.scss)
2. Uncomment [line 7](https://github.com/mmistakes/minimal-mistakes/blob/f4df3d459b41ebba3c6b90454ea826e6f2ecda45/_sass/vendor/font-awesome/_variables.scss#L7) to replace the local font path with the CDN version. `$fa-font-path:        "//netdna.bootstrapcdn.com/font-awesome/4.6.3/fonts" !default;`

## Installed by forking the MM repo

1. Uncomment [line 7](https://github.com/mmistakes/minimal-mistakes/blob/f4df3d459b41ebba3c6b90454ea826e6f2ecda45/_sass/vendor/font-awesome/_variables.scss#L7) `_sass/vendor/font-awesome/_variables.scss`

**Comment by weikinhuang** [comment]
Alright thanks!

**Comment by weikinhuang** [comment]
Actually I just tried it, and it doesn't seem to be picking up the local `_sass/vendor/font-awesome/_variables.scss` file. I'm using the gem version of the theme. I've tried overriding other files too in the sass folder and it also doesn't seem to be picking up those changes either.

**Comment by mmistakes** [comment]
I'll have to test and see if I can reproduce. 

There's a related issue open for local files in `assets` not overriding the gem ones #722. If that's the case here then there might be a regression bug with Jekyll that will need to be filled upstream.

**Comment by mmistakes** [comment]
I got it to work by copying the entire `_sass/vendor/font-awesome/` folder to my local repo, then commenting `// $fa-font-path:        "../fonts" !default;` and uncommenting `$fa-font-path:        "//netdna.bootstrapcdn.com/font-awesome/4.6.3/fonts" !default;`

Seems like the way Jekyll reads in local files to override the theme gem's versions gets confused when you start `@import`ing levels deeper.

**Comment by weikinhuang** [comment]
That works, but still sucks to have to copy the entire directory into an otherwise empty repo. Thanks!

**Comment by mmistakes** [comment]
Agreed. Theme gems are still in their infancy so there are still some kinks to be worked out in Jekyll-land.

**Comment by weikinhuang** [comment]
👍
