### ISSUE TITLE
Embed gitter via custom comments?

### ISSUE THREAD

**Issue by zahachtah** [mmistakes/minimal-mistakes#728]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [x] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: just forked today** 
- **`github-pages` ** 
- **Operating system: github** 

---

## Expected behavior

Hi, 

I tried to add gitter as custom comments (chatt really but works for me). the process is explained here: https://sidecar.gitter.im

First I got an error using the default js distribution from sidecar.gitter.im. changing this to the one used below got rid of that error but it won't show the chatt in the .custom-comments div (tried .page__comments with and without the dot too....)

I added the following into the custom.html:

```html
<script>
  ((window.gitter = {}).chat = {}).options = {
    room: 'https://gitter.im/Introduction-to-Sustainability-Science/Lobby',
    targetElement: '.custom-comments'
  };
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gitter-sidecar/1.2.4/sidecar-module.js" async defer></script>
```

So I have two questions:

1) do you have any ideas why its not showing up?
2) maybe add as one new option for comments?

I so love this theme and would like to thank you very much for sharing it.

**Comment by mmistakes** [comment]
Can you verify that you set the following in _config.yml

```yaml
comments:
  provider: "custom"
```

and in each post or page's YAML Front Matter you want to embed the gitter chat you have `comments: true`

Do you happen to have a public repo that I could look at to help troubleshoot?

**Comment by mmistakes** [comment]
Looking over your script above you're targeting the wrong element selector (class instead of id).

Instead of `targetElement: '.custom-comments'` try `targetElement: '#custom-comments'`

**Comment by zahachtah** [comment]
ah, that simple :-(

sorry for the trouble! and thanks again!
