### ISSUE TITLE
Broken link in footer

### ISSUE THREAD

**Issue by BenjaminJurke** [mmistakes/minimal-mistakes#739]
- [ ] This is a question about using the theme.
- [X] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [X] This is a feature request.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.1.1
- **`github-pages` or `jekyll` gem version:** 3.1.1
- **Operating system:** Ubuntu 16.10 x64

---

## Expected behavior

I noticed that the back link in the footer to the Minimal Mistakes theme is broken. The file relevant here is `_includes/footer.html`. Here we find in the last line

`<a href="https://mademistakes.com/work/minimal-mistakes-jekyll-theme/" rel="nofollow">Minimal Mistakes</a>.` 

which most likely should be

`<a href="https://mmistakes.github.io/minimal-mistakes/" rel="nofollow">Minimal Mistakes</a>.`

## Steps to reproduce the behavior

Click on the current link and witness the 404. :)

## Wish list

Since you will already be touching `_includes/footer.html`, I would suggest to add the following to the list of "social links" in the footer:

```
    {% if site.author.email %}
      <li><a href="mailto:{{ site.author.email }}"><i class="fa fa-fw fa-envelope-square" aria-hidden="true">&nbsp;</i>{{ site.data.ui-text[site.locale].email_label | default: "Email" }}</a></li>
    {% endif %}
    {% if site.author.linkedin %}
      <li><a href="https://www.linkedin.com/in/{{ site.author.linkedin }}"><i class="fa fa-fw fa-linkedin-square" aria-hidden="true">&nbsp;</i>LinkedIn</a></li>
    {% endif %}
    {% if site.author.xing %}
      <li><a href="https://www.xing.com/profile/{{ site.author.xing }}"><i class="fa fa-fw fa-xing-square" aria-hidden="true">&nbsp;</i>XING</a></li>
    {% endif %}
    {% if site.author.skype %}
      <li><a href ="skype:{{ site.author.skype }}?call"><i class="fa fa-skype" aria-hidden="true">&nbsp;</i>Skype</a></li>
    {% endif %}
```

The somewhat ugly `&nbsp;` hack makes the spacing between the FontAwesome logo and the actual link look nicer, especially the underscore when hovering. But there is probably a better way to do this.

**Comment by mmistakes** [comment]
Thanks for pointing this out. It's not technically broken link. My site mademistakes.com was having some issues, which is why the link breaks. It's back up and working now though.

_includes/footer.html is purposely left sparse of social links. It's small enough that you can customize it to fit your needs. Ideally you'd use the gemified version of the theme (if you're not on GH Pages) and [override it](https://mmistakes.github.io/minimal-mistakes/docs/overriding-theme-defaults/) as you see fit.

**Comment by mmistakes** [comment]
RE: the non-breaking spaces (`&nbsp;`) between icon and text. That's in there to make sure the icon is always attached to the text. Without it the text could potentially break to the next line depending on the browser's screen size.

Sure it may be ugly, but it's completely valid and being used semantically, nothing hacky about it. One could argue all of that Liquid/HTML garbley gook above is ugly :wink:
