### ISSUE TITLE
set 'target' attribute for outgoing (http://...) to  'target="_blank"' 

### ISSUE THREAD

**Issue by gernotstarke** [mmistakes/minimal-mistakes#753]
- [x] This is a question about using the theme.
- [?] This is a feature request.
- [x ] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Expected behavior

It would be nice if outgoing (external) links would always be amended
to open in new tab/window by setting 'target="_blank"'

**Comment by gernotstarke** [comment]
will create a PR for this (small js that mods all outgoing links)

**Comment by mmistakes** [comment]
In my opinion setting `target="_blank"` is a web anti-pattern and is mostly abused as a matter of preference. Some context here. https://css-tricks.com/use-target_blank/

It also has [security implications](https://mathiasbynens.github.io/rel-noopener/) if you don't add `rel="noopener"` to links that target a `_blank` window.

I don't think it's the theme's place to dictate the usage of `target="_blank"` and would rather leave it out and up to the user to decide if they want to add it or not.

That's for opening the issue and the PR.

**Comment by gernotstarke** [comment]
that are great arguments - thanx!

best regards from Cologne,
Gernot

PS: THANX for your awesome theme - which makes Jeykll fun again!

**Comment by ohadschn** [comment]
@mmistakes how would you recommend adding `target="_blank"` if I were so inclined? The scripts in the attached commit seems a bit hacky, plus I'd rather not override things in `assets` and `_includes` if I can (for a better upgrade experience).

**Comment by mmistakes** [comment]
@ohadschn I think overriding is your only course of action. Anytime you deviate and customize you'll have to be weary of changes in the core and keep on top of them.

**Comment by ohadschn** [comment]
@mmistakes would you consider adding some optional flag to say `_config.yml_ to enable `target="_blank"` out of the box?

**Comment by mmistakes** [comment]
No not at this time... for all of the reasons I cited above about it being a perceived anti-pattern.

**Comment by ohadschn** [comment]
Fair enough, but after all this is a _personal_ blog theme, and personally some of us like external links opening in new tabs :) 

(with the proper `noopener`/`noreferrer` security measures in place of course)

**Comment by mmistakes** [comment]
Nothing stopping you from dropping in the script from https://github.com/gernotstarke/minimal-mistakes/commit/9ba387bbe3160e83f54c7f63f303254155f9fab5 into `_includes/footer/custom.html`. That's the whole point of that file.

**Comment by ohadschn** [comment]
Looks like the UX community agrees with @mmistakes: https://ux.stackexchange.com/questions/5397/whats-your-take-on-target-blank/5399.
