### ISSUE TITLE
Using title_separator: "|", page title doesn't display correctly

### ISSUE THREAD

**Issue by billgarrison** [mmistakes/minimal-mistakes#760]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:**  4.1.1
- **`github-pages` or `jekyll` gem version:** Jekyll gem 3.3.1, Ruby 2.4
- **Operating system:** Mac OS 10.11.6

---

## Expected behavior

Expected to see the "|" character display as a separator in the page breadcrumb path when bookmarking in my browser. What appears instead is a blank space.

## Steps to reproduce the behavior

1. In `_config.yml`, add this line:
`title_separator: "|"`
2. run `bundle exec jekyll serve` and open browser to `localhost:4000`
3. Attempt to bookmark a page in the browser.
4. Observe that the proposed bookmark title is missing the title separator character of "|". 

Interestingly, if I pick a character other than `"|"` as the title separator, the feature works as expected. E.g.

`title_separator: "•"` works
`title_separator: "&&"` works
`title_separator: "|"` :-(

**Comment by mmistakes** [comment]
I haven't tested this yet, but this could be related to [YAML](http://www.yaml.org/spec/1.2/spec.html). I know you can use `|` to have it preserve newlines if you do something like:

```yaml
stats: |
  65 Home Runs
  0.278 Batting Average
```

Perhaps it's ignoring `|` when parsing the YAML, which could explain why it's blank. Perhaps there is a way to escape that character so it shows up. I'd suggest digging into the YAML spec as this appears to be an issue there and not with the theme.

**Comment by mmistakes** [comment]
Did some testing and it does seem like YAML or Liquid or Jekyll is removing the vertical pipe `|`. What you can do instead is declare it as a HTML entity and then it'll work.

```yaml
title_separator: "&#124;"
```

Will give you something like:

```html
<title>Welcome to Jekyll | Minimal Mistakes</title>
```

**Comment by billgarrison** [comment]
+1. Thanks! I was going to try an HTML entity next. Thanks for checking this out so quickly.
