### ISSUE TITLE
Break blog title over two lines?

### ISSUE THREAD

**Issue by pjpaulpj** [mmistakes/minimal-mistakes#765]
How can I display the tile of my blog split across two lines?  My current blog is hosted at https://pjpaulpj.github.io/. It's titled 
> Notes on Economics, Development and Literature

in a single line, as you can see.

 I'd like the title to instead appear in the following format: 

> Notes on Economics
> Development and Literature

I'm using Minimal Mistakes via GIthub pages, I have not hosted the Jekyll site locally.

**Comment by mmistakes** [comment]
That can be tricky. You'll need to customize the [masthead include](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/masthead.html#L7) to accommodate a sub-title or tagline. And will likely need to make some CSS changes to get things looking good.

The theme was designed for a title without a tagline. There was a previous issue filed by someone who had a really long site title and I gave suggestions on how to break it into multiple lines, but I can't seem to find it. It was probably buried in unrelated issue making it hard to find.

But maybe peruse the closed issues to see if you can dig it up.
