### ISSUE TITLE
Latex does not render

### ISSUE THREAD

**Issue by pjpaulpj** [mmistakes/minimal-mistakes#769]
Hi,

Github does not render my latex test. [This](https://github.com/pjpaulpj/pjpaulpj.github.io/blob/master/_posts/2017-1-13-test-post.md) is the source file and [this](https://pjpaulpj.github.io/test-post/) is the rendered version.

I've tried three different Latex formattings- nothing works.

**Comment by mmistakes** [comment]
That's because you need to add the [MathJax](https://www.mathjax.org/) library to render them. If you dig into Kramdown's documentation it notes this. See [this issue](https://github.com/mmistakes/minimal-mistakes/issues/735) for more assistance.
