### ISSUE TITLE
Liquid Exception: exit in _layouts/post.html

### ISSUE THREAD

**Issue by fliiiix** [mmistakes/minimal-mistakes#77]
I get a error with your theme: (oh btw. thank you for your awesome work :heart:  )

```
Invalid Date: '' is not a valid datetime.
Liquid Exception: exit in _layouts/post.html
```

I guess the error is this [part](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/post.html#L50): (I have no Idea how you can call in ruby a method with a pipe but probably it's possible)

```
<time datetime="{{ page.date | date_to_xmlschema }}">
```

Because this work fine for me:

```
<time datetime="{{ date_to_xmlschema(page.date) }}">
```

```
$ jekyll --version
jekyll 2.1.1
```

**Comment by nibra** [comment]
You can move the posts to an "example" directory without problems. You just have to add "example" to the exclude list in _config.yml.

**Comment by jianjinucdavis** [comment]
Thanks everyone! I finally caught the one left .md file which caused the problem!
