### ISSUE TITLE
Jekyll warnings on build

### ISSUE THREAD

**Issue by iandstanley** [mmistakes/minimal-mistakes#770]
- [X] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment information
- Using minimal-mistakes-jekyll 4.1.1 from source at `.`
- jekyll 3.3.1
- Not using github pages
- Running on Ubuntu virtual server on Cloud9 (c9.io)

---

## Expected behavior
Build without deprecation notices

Doesn't appear to break jekyll build though as a _site is produced

## Steps to reproduce the behavior

download zip and extract 
cd directory
bundle install
bundle exec jekyll b 

> iandstanley:~/workspace (master) $ bundle exec jekyll b
> Configuration file: /home/ubuntu/workspace/_config.yml
>             Source: /home/ubuntu/workspace
>        Destination: /home/ubuntu/workspace/_site
>  Incremental build: disabled. Enable with --incremental
>       Generating... 
>        Deprecation: A call to '{{ post_url 2012-03-15-layout-header-image-text-readability }}' did not match a post using the new matching method of checking name (path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.
>        Deprecation: A call to '{{ post_url 2010-09-09-post-gallery }}' did not match a post using the new matching method of checking name (path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.
>        Deprecation: A call to '{{ post_url 2013-01-11-markup-html-tags-and-formatting }}' did not match a post using the new matching method of checking name (path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.
>        Deprecation: A call to '{{ post_url 2013-08-16-markup-syntax-highlighting }}' did not match a post using the new matching method of checking name (path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.
>                     done in 37.55 seconds.
>  Auto-regeneration: disabled. Use --watch to enable.

**Comment by mmistakes** [comment]
This is a Jekyll related error and not theme related. That said I believe what is going on here is you're using `post_url` incorrect. If you have a link to a public repo I can confirm that...

Instead of `{{ post_url }}` you want `{% post_url %}` with percent signs.

To link to `<site root>/_posts/2012-03-15-layout-header-image-text-readability.md` you'd use:

```
{% post_url 2012-03-15-layout-header-image-text-readability %}
```

To read up more on how to use the `post_url` tag or new `link` tag check the official Jekyll docs. https://jekyllrb.com/docs/templates/#post-url
