### ISSUE TITLE
Create another page with pagination enabled

### ISSUE THREAD

**Issue by jongmin92** [mmistakes/minimal-mistakes#778]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- Using minimal-mistakes-jekyll 4.1.1 from source at .
- jekyll 3.3.1
- Using github pages

---

## Expected behavior

 One more page that can be paginated like posts.

## Steps to reproduce the behavior

 Hello. First of all, thank you for allowing me to use the amazing Jekyll theme.
When I first applied the minimal-mistakes theme, I would like to create another page that can be paginated like posts. For example, I wonder if two pages 'blog' and 'til' can paginate different posts.

**Comment by mmistakes** [comment]
Not entirely sure what the question is, but going to assume you want to paginate multiple pages.

With the [official Jekyll pagination plugin](http://jekyllrb.com/docs/pagination/) it only allows you to paginate a single page (usually the home page). If you want to do more you need to use another plugin. I suggest [jekyll-paginate-v2](https://github.com/sverrirs/jekyll-paginate-v2).

**Comment by jongmin92** [comment]
I am sorry that my English is poor. I have solved what I tried to solve by referring to the **"pagination plugin"** you mentioned! Thank you very much!
