### ISSUE TITLE
Sidebar disappears on last document for a collection

### ISSUE THREAD

**Issue by ImAlexisSaez** [mmistakes/minimal-mistakes#780]
- [ ] This is a question about using the theme.
- [X] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.1.1
- **`github-pages` or `jekyll` gem version:** 114
- **Operating system:** Windows

---

## Expected behavior

I'm using a custom sidebar navigation menu to display a collection. When I click on the last item of the menu, the menu disappears and the page shows the information of the author instead.

## Steps to reproduce the behavior

Check https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/ and click on the last item in the sidebar menu: "Terms & Privacy Policy" ([link](https://mmistakes.github.io/minimal-mistakes/terms/)). That page shows the information about the author, instead of the sidebar menu for the collection. Is it an intended behaviour?

**Comment by mmistakes** [comment]
Not a bug. It's linked to the "Terms" page which isn't part of that collection... it's just a single page.
