### ISSUE TITLE
Question: How to implement parallax with minimal-mistakes

### ISSUE THREAD

**Issue by Shellcat-Zero** [mmistakes/minimal-mistakes#789]
- [x] This is a question about using the theme.

---
I was wondering if it's fairly simple to do this, it looks like you're using the parallax scroll effect with Skinny Bones (https://mmistakes.github.io/skinny-bones-jekyll/) so I was hoping I could do it with this theme.  

If it's not implemented, it looks like it can be done in pure css (http://keithclark.co.uk/articles/pure-css-parallax-websites/).  Disclaimer: I'm pretty new to web design and css myself.

**Comment by mmistakes** [comment]
You could try adding `background-attachment: fixed` but it will likely have unintended side-effects. That's how I did it with Skinny Bones.

**Comment by Shellcat-Zero** [comment]
Thanks!  I'm going to see about implementing and integrating my own parallax layout with minimal-mistakes.  Keith Clark (the link in my 1st post) suggests that the pure css implementation is superior to a javascript implementation, I would be curious to get more input on the pros and cons of this.

**Comment by mmistakes** [comment]
I think it depends on the complexity of the parallax effect you want to achieve. There are some that react to mouse position which wouldn't be possible without JavaScript.

Personally I prefer CSS-only solutions for everything just for simplicity's sake. For more feedback on the matter I'd seek out blogs/forums/sites dedicated to web development. You'll find more valuable information there.

**Comment by mmistakes** [comment]
Closing this issue as it appears to be addressed. If not feel free to re-open.

**Comment by AkashCherukuri** [comment]
Hey, I was able to use Rellax to achieve this. [Here's](akashcherukuri.github.io) the link of my page as a demo. It doesn't work on Mozilla, but you can just check the browser and change the style to be fixed then.

I changed `page__hero.html` as [follows](https://github.com/AkashCherukuri/AkashCherukuri.github.io/commit/bad969c119965eb80c1f797d25a729a1e829d87a#diff-568c7dd2026523567ea2553c252eac6585e647126ccdee95ef90ca099654df2a).

Posting here for you to verify; and for it to help anyone else that stumbles upon the question.
