### ISSUE TITLE
Gallery with iPhone picture frame

### ISSUE THREAD

**Issue by scinfu** [mmistakes/minimal-mistakes#791]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [x] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

There is a  template gallery to make an auto scroll and add an iPhone picture frame ?

Thank you

**Comment by mmistakes** [comment]
There is not.

**Comment by scinfu** [comment]
And only slider images ?

**Comment by mmistakes** [comment]
No slider images either. The theme supports:

- [large hero images](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#headers) at the top of any page
- post images with caption (see [`figure` helper](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#figure))
- multiple post images grouped together as a "gallery" ( see [`gallery` helper](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#gallery))

**Comment by mmistakes** [comment]
Closing this issue as it appears to be addressed. If not feel free to re-open.
