### ISSUE TITLE
Last version that works with Ruby 2.1.5

### ISSUE THREAD

**Issue by Sciss** [mmistakes/minimal-mistakes#806]
On Debian stable (Jessie) the latest Ruby version is 2.1.5. I'm trying to upgrade to the latest version of MM, cloning the repository. After changing the contents of `Gemfile` to:

```
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
end
```

The `bundle update` call doesn't work, because it requires Ruby 2.2.2:

```
Installing RedCloth 4.2.9
Installing concurrent-ruby 1.0.4
Installing i18n 0.7.0
Installing minitest 5.10.1
Installing thread_safe 0.3.5
Installing tzinfo 1.2.2

Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
An error occurred while installing activesupport (5.0.1), and Bundler cannot continue.
Make sure that `gem install activesupport -v '5.0.1'` succeeds before bundling.
```

Can you tell me which is the last version of MM that works with Ruby 2.1.5; and if possible, also the last version that has the nice fonts (current theme seems to have dropped fonts). Thanks!

**Comment by mmistakes** [comment]
Don't think it's MM that's the issue here, but the various Jekyll gems it depends on. The theme could care less what version of Ruby you have installed.

**Comment by Sciss** [comment]
So I see that the 3.x versions still build, but that the old layout with nice font etc. stopped at 2.2.1.

Is there any severe problem with 2.2.1 that should keep me from using that version? (Like incompatibility with mobile devices, security issues, ...)?

**Comment by mmistakes** [comment]
Not really. The old `v2` version should work, but it is missing a lot of the new stuff I've added since.

If you want the fonts back from `v2` it's easy enough to add. I provide instructions in the theme docs.

https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#typography-from-older-versions

**Comment by Sciss** [comment]
Thanks!
