### ISSUE TITLE
Posts not shown

### ISSUE THREAD

**Issue by duttashi** [mmistakes/minimal-mistakes#808]
Hello,

I'm setting up my personal website using this excellent theme. However, the posts are not visible. I'm on a Windows 7 environment. I have checked the config.yml and have followed the suggestions you have given on a similar question [here](https://github.com/mmistakes/minimal-mistakes/issues/401) I am trying to solve this problem for 3 days now and am on my wits end. Please, suggest what has gone wrong here.
 
[Link to website](https://duttashi.github.io/)
[Link to github repo](https://github.com/duttashi/duttashi.github.io)
[Link to the post on github repo](https://github.com/duttashi/duttashi.github.io/tree/master/_posts)

I created a new repo. Instead of forking your repo, I copied the contents of your repo and followed the [instructions](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/)

Please help or advice.

Thank you

**Comment by mmistakes** [comment]
1. You are using the wrong layout on your [homepage](https://github.com/duttashi/duttashi.github.io/blob/master/index.html#L2). Change `layout: default` to `layout: home`.
2. You have a ton of YAML errors in your posts. I would suggest [building locally](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) so you can see all of the errors and correct them as pushing to GitHub won't give you as much detail as to what is wrong.

```
Generating...
  Error: could not read file /duttashi.g
ithub.io/_posts/2013-12-10-writing-for-scientific-publication-3-common-mistakes.
md: (<unknown>): mapping values are not allowed in this context at line 3 column
 42

  Error: could not read file /duttashi.g
ithub.io/_posts/2014-08-23-fix-arff-file-not-recognised-or-unable-to-load-data-i
n-weka.md: (<unknown>): mapping values are not allowed in this context at line 3
 column 11

  Error: could not read file /duttashi.g
ithub.io/_posts/2014-10-02-error-python-version-2-7-required-which-was-not-found
-in-the-registry-solved.md: (<unknown>): mapping values are not allowed in this
context at line 3 column 13

  Error: could not read file /duttashi.g
ithub.io/_posts/2014-11-17-conquering-errors-in-t-sql-and-ssis-act-1-scene-1.md:
 (<unknown>): mapping values are not allowed in this context at line 3 column 43

  Error: could not read file /duttashi.g
ithub.io/_posts/2014-11-24-working-with-weka-data-preprocessing-error-array-inde
x-out-of-bounds-exception.md: (<unknown>): mapping values are not allowed in thi
s context at line 3 column 52

  Error: could not read file /duttashi.g
ithub.io/_posts/2015-05-05-hierarchical-clustering-methods-implementation-in-r-a
-case-study.md: (<unknown>): mapping values are not allowed in this context at l
ine 3 column 59

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-01-09-big-or-small-lets-save-them-all-exploratory-data-anal
ysis.md: (<unknown>): mapping values are not allowed in this context at line 3 c
olumn 40

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-01-15-big-or-small-lets-save-them-all-making-data-managemen
t-decisions.md: (<unknown>): mapping values are not allowed in this context at l
ine 3 column 40

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-01-23-big-or-small-lets-save-them-all-visualizing-data.md:
(<unknown>): mapping values are not allowed in this context at line 3 column 40

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-02-10-big-or-small-lets-save-them-all-anova-tukeys-hsd-post
-hoc-comparison-test.md: (<unknown>): mapping values are not allowed in this con
text at line 3 column 40

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-02-21-big-or-small-lets-save-them-all-chisquare-test-of-ind
ependence.md: (<unknown>): mapping values are not allowed in this context at lin
e 3 column 40

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-02-21-big-or-small-lets-save-them-all-pearsons-correlation-
coeffecient.md: (<unknown>): mapping values are not allowed in this context at l
ine 3 column 20

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-02-24-big-or-small-lets-save-them-all-exploring-statistical
-interactions.md: (<unknown>): mapping values are not allowed in this context at
 line 3 column 20

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-03-15-big-or-small-lets-save-them-all-how-the-data-was-coll
ected.md: (<unknown>): mapping values are not allowed in this context at line 3
column 40

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-03-25-big-or-small-lets-save-them-all-uncovering-the-factor
s-responsible-multiple-regression-analysis-2.md: (<unknown>): mapping values are
 not allowed in this context at line 3 column 40

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-03-29-big-or-small-lets-save-them-all-logistic-regression-a
nalysis.md: (<unknown>): mapping values are not allowed in this context at line
3 column 40

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-04-20-to-penalise-or-not-to-penalise-the-curious-case-of-au
tomatic-feature-selection.md: (<unknown>): mapping values are not allowed in thi
s context at line 3 column 38

  Error: could not read file /duttashi.g
ithub.io/_posts/2016-04-26-give-me-data-and-i-shall-give-you-clusters-the-case-o
f-k-means-algorithm.md: (<unknown>): mapping values are not allowed in this cont
ext at line 3 column 50

  Build Warning: Layout 'page' requested in _posts/2013-07-28-about.md does n
ot exist.

  Liquid Exception: undefined method `gsub' for nil:NilClass in _includes/archiv
e-single.html, included in _layouts/single.html
jekyll 3.1.6 | Error:  undefined method `gsub' for nil:NilClass
```

For example in [`_posts/2016-04-26-give-me-data-and-i-shall-give-you-clusters-the-case-of-k-means-algorithm`](https://github.com/duttashi/duttashi.github.io/blob/master/_posts/2016-04-26-give-me-data-and-i-shall-give-you-clusters-the-case-of-k-means-algorithm.md) on line 2 in the title you have a colon that isn't inside of the quotes. This is throwing a YAML error. You have to be really careful with single quotes, double quotes, and : colons.

It also appears Jekyll is having problems with some of your dates that you've set in the post's YAML. Probably the format is off. Instead of something like `2013-12-10 17:50` it needs to be in ISO format `2013-12-10T17:50`.

And finally you're using the wrong layout in `_posts/2013-07-28-about.md`. Should be `layout: post` not `layout: page`.

Fix these things and your home page will build properly.

**Comment by duttashi** [comment]
Thanks very much for your detailed response. I'm at a learning stage setting up a blog on github so do not understand much of YAML etc. Unlike, your excellent theme, your excellent response have helped much too. While, waiting for your response, I accidentally stumbled on another [repo](https://academicpages.github.io/) which is derived from your excellent theme. The layout and structure of this theme matches my requirements as I'm from the academics domain. I hope you do not mind and continue to offer me your excellent advice. 
Thank you for your time.
