### ISSUE TITLE
Different forms of website in browsers

### ISSUE THREAD

**Issue by RAlexeev** [mmistakes/minimal-mistakes#816]
Unfortunately, I'm not a web programmer, but still would like to ask about different forms of website in Mozilla Firefox and Google Chrome. See screenshots below.

This form has your web site `https://mmistakes.github.io/minimal-mistakes/year-archive/` in Mozilla Firefox:

![firefox](https://cloud.githubusercontent.com/assets/17528007/22623880/0d0c6bea-eb7b-11e6-8e41-d69184152759.PNG)

This form has your web site `https://mmistakes.github.io/minimal-mistakes/year-archive/` in Google Chrome:

![chrome](https://cloud.githubusercontent.com/assets/17528007/22623879/0d07e520-eb7b-11e6-8375-b5ad4301a07a.PNG)

As you can see, there aren't icons "Follow: Twitter Facebook GitHub Feed" in case of Google Chrome. But in mobile Google Chrome it looks good with social icons.

If inspect footer element in browser, then this element has height 0 in Google Chrome:

```html
<div class="page__footer-follow">
  <ul class="social-icons">
    ...
</div>
```

And also left part of page with author info slides only in Mozilla Firefox while scrolling down, but not in Google Chrome. In case of Google Chrome it's static in the above of page.

```html
<div class="sidebar sticky">
  <div itemscope="" itemtype="http://schema.org/Person">
    ...
  </div>
</div>
```

**Comment by mmistakes** [comment]
I believe you need to update Chrome. Recently they added support for `position: sticky`. You likely have an older version which doesn't have this feature and the sidebar won't "stick" on scroll. 

Also do you have any adblockers installed? They're known to be aggressive and remove content they think are "social" related. The sidebar and footer look fine for me in Chrome with no extensions enabled on macOS and Windows which is why I ask.

**Comment by RAlexeev** [comment]
I'm so sorry to have bothered you. I totally forgot about ad blockers in browsers. The problem with social links was solved by disabling ad blockers. And you were totally right about old version my Google Chrome. After updating browser `position: sticky` started working properly! Thank you very much for the help!

**Comment by rriemann** [comment]
Thank you!

Ok, I close this as a duplicate.

**Comment by mmistakes** [comment]
If you want `position: sticky` to work with older browsers you can add back a polyfill I was previously using. As it's purely presentational and most modern browsers support it now I removed it to lighten the JavaScript included with the theme.

Here's the commit you can revert if you want it back https://github.com/mmistakes/minimal-mistakes/commit/55843c5dca8fcf5ff83e48ace202fc529d58ae14
