### ISSUE TITLE
sticky left sidebar broken in Chromium (like Chrome)

### ISSUE THREAD

**Issue by rriemann** [mmistakes/minimal-mistakes#818]
I just went with Chromium 51.0.2704.103 (linux/opensuse 64bit) to the web page
https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

When I scroll down, the left nav bar is not sticky as it is the case with Firefox. The same for the author information.

I could reproduce the problem locally with my own site based on the latest fork.

**Comment by RAlexeev** [comment]
Hello!

I asked this question too just today: https://github.com/mmistakes/minimal-mistakes/issues/816. I think updating your browser will help you too.

**Comment by rriemann** [comment]
Thank you!

Ok, I close this as a duplicate.
