### ISSUE TITLE
Bug with embedding discourse

### ISSUE THREAD

**Issue by ghutchis** [mmistakes/minimal-mistakes#823]
- [X] This is a question about using the theme.
- [X] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.
---

## Environment informations

- **Minimal Mistakes version:** 4.2.1
- **`github-pages` or `jekyll` gem version:** 3.4.0
- **Operating system:** MacOS 10.12

---

## Expected behavior

Based on the docs, I expect to embed Discourse comments from my server.

## Steps to reproduce the behavior

See source of http://avogadro.org/news/avogadro-1-90-released/

I believe that _includes/comments.html needs a `when` case for "discourse"
```
{% when "discourse" %}
    <h4 class="page__comments-title">{{ comments_label }}</h4>
    <section id="discourse-comments"></section>
```

The resulting site has the embedded Discourse forum.

**Comment by mmistakes** [comment]
@ghutchis Care to submit a pull request to the `develop` branch with the fix?
