### ISSUE TITLE
github-pages minimal-mistakes-jekyll jekyll-sitemap version conflict

### ISSUE THREAD

**Issue by kvz** [mmistakes/minimal-mistakes#842]
When installing the latest `4.2.1`, `bundler` throws:

```
   Bundler could not find compatible versions for gem "jekyll-sitemap":
     In snapshot (Gemfile.lock):
       jekyll-sitemap (= 0.12.0)

     In Gemfile:
       github-pages (= 112) was resolved to 112, which depends on
         jekyll-sitemap (= 0.12.0)

       minimal-mistakes-jekyll (= 4.2.1) was resolved to 4.2.1, which depends on
         jekyll-sitemap (~> 1.0)
```

It appears the github-pages gem that I use for bootstrapping jekyll (but is also used for any github page), wants `jekyll-sitemap (= 0.12.0)` but minimal-mistakes-jekyll wants `jekyll-sitemap (~> 1.0)`.

The latest version of github-pages (120) still requires the old jekyll-sitemap version: https://rubygems.org/gems/github-pages/versions/120.

Any chance to losen the dependency on jekyll-sitemap, or should I rather file a bug report with GitHub instead?

Thanks for minimal mistakes - I love it

**Comment by kvz** [comment]
It seems like this problem will go away with https://github.com/github/pages-gem/pull/409

Sorry for the noise!

**Comment by mmistakes** [comment]
The other option is to use the Jekyll gem in your `Gemfile` instead of `github-pages`. Minimal Mistakes doesn't work on GitHub Pages as a theme gem anyways since there are only a few themes whitelisted currently (all GH owned owns).
