### ISSUE TITLE
Theme's default locale value, "en", makes Facebook displeased

### ISSUE THREAD

**Issue by billgarrison** [mmistakes/minimal-mistakes#843]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:*4.2.1* 
- **`github-pages` or `jekyll` gem version:*3.4.0* 
- **Operating system:*Mac OS X 10.11.6* 

---

## Expected behavior

Expected Facebook Object Debugger to approve of my site, but it came back complaining that the `og:locale` value of `en` was not valid.  "en" is theme's default value when no `locale` value is set in the config file.

## Steps to reproduce the behavior

1. Install a new theme instance at web-accessible location.
1. Ensure that no `locale` settings is specified in `_config.yml` so that the theme's default value is used.
1. Fire up the [Facebook Object Debugger](https://developers.facebook.com/tools/debug/og/object/) and let it scan your new site instance.

The report should come back highlighting an error with the `og:locale` value. 

<img width="1041" alt="screen shot 2017-02-14 at 8 51 57 pm" src="https://cloud.githubusercontent.com/assets/63499/22993909/c44317ea-f392-11e6-8697-e6491ac17eb4.png">

Setting the locale value in `_config.yml` to `en_US` fixed it for me.  `en_US` should probably be the new default value in the theme.

**Comment by mmistakes** [comment]
As you noted it's fairly trivial to change to something more specific to appease the OpenGraph debugger.

I'd rather keep it generic at `en` and not force a United States locale on everyone.

Anyone who cares about this sort of thing would likely consult the docs when setting this up where it explains the various options. I'd be open to beefing up the documentation around it. Perhaps a note that if you leave it at the default value of `en` you'll piss off OG and you really should set it to a more specific locale like `en-US`, `en-GB`, etc.

https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-locale

**Comment by jhabdas** [comment]
Should be resolved when https://github.com/mmistakes/minimal-mistakes/issues/324 is fixed.

**Comment by jhabdas** [comment]
Sounds like a bug in OG :)~

**Comment by mmistakes** [comment]
@jhabdas They probably view it as a "feature" hah.
