### ISSUE TITLE
Sidebar appears then disappears in Chrome

### ISSUE THREAD

**Issue by weiyangtham** [mmistakes/minimal-mistakes#853]
- [x] This is a question about using the theme.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

This seems to be a Chrome problem specifically. For some blog posts, the sidebar appears for a split second but then disappears, but it works perfectly fine for others. 

Unfortunately I can't show the sidebar disappearing but this is [an example after it disappears](https://weiyangtham.github.io/revisiting_event_study/) with screenshot below:

![screen shot 2017-02-18 at 11 15 47 pm](https://cloud.githubusercontent.com/assets/15363607/23099247/42965298-f630-11e6-963c-303fe43e2c5c.png)

[Another post with the same problem](https://weiyangtham.github.io/nih_booms_busts/).

Example of [a post where the sidebar works](https://weiyangtham.github.io/extract_nci_pdf/) with screenshot below: 

![screen shot 2017-02-18 at 11 18 06 pm](https://cloud.githubusercontent.com/assets/15363607/23099262/8fc1b97c-f630-11e6-8b25-82a62d88e12f.png)

I'm using the latest version of Chrome (Version 56.0.2924.87) and I've tried turning off all extensions, including adblockers, as suggested in issue #816. The problem exists when I build locally.

**Comment by mmistakes** [comment]
Maybe it's a bug with an older version of Chrome. I'm on `Version 57.0.2987.54 beta (64-bit)` and the sidebar on all of those links works just fine for me.

**Comment by mmistakes** [comment]
The posts where it disappears for you... are they ones with the MathJax script? Entirely possible that's causing some sort of delay or conflict with the script that initializes the sticky sidebar.

I'd suggest updating the theme (current version is 4.2.1) because [I removed that](https://github.com/mmistakes/minimal-mistakes/issues/752) a few versions ago and seems like you're using an older version (modified 4.0.10?) that doesn't have a lot of these fixes.

**Comment by weiyangtham** [comment]
Yes they are the ones with MathJax; I hadn't noticed that at first. 

I tried updating the theme without updating Chrome and that didn't help. After that I updated Chrome and that worked. So I guess it was some interaction of MathJax and a Chrome bug that was causing the problem. 

Many many thanks for the prompt help!
