### ISSUE TITLE
align top navbar to the right

### ISSUE THREAD

**Issue by lingxz** [mmistakes/minimal-mistakes#859]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

How do I adjust the css of the top navbar so that they are aligned to the right without breaking greedy nav? I have tried adding pull-right to the site-nav class, but the greedy nav dropdown menu will overlap with the last link.

**Comment by mmistakes** [comment]
Have a look at this [set of commits on the `develop` branch](https://github.com/mmistakes/minimal-mistakes/commit/a3ccadc8e389a652331c75daf7d77567c4d8c375). I've reworked the greedy nav to work better with long site titles and the nav links now float to the right. 

It'll be released in the next version of the theme.

**Comment by lingxz** [comment]
great, thanks!

**Comment by mmistakes** [comment]
Added with latest release https://github.com/mmistakes/minimal-mistakes/releases/tag/4.2.2
