### ISSUE TITLE
4.2.2 hamberger nav display issue

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/minimal-mistakes#865]
- [ x ] This is a question about using the theme.
- [ x ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ x ] This is a feature request.
- [ x ] I have updated all gems with `bundle update`.
- [ x ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** minimal-mistakes-jekyll (4.2.2)
- **`github-pages` or `jekyll` gem version:** GEM
- **Operating system:** macOS 10.12.3

---

## Expected behavior

After the 4.2.2 gem update, it appears the hamberger menu is not displaying correctly on mobile devices.  here is a screenshot w/ Chrome and iPhone 6 settings.  this is the same way it appears on my physical phone using mobile Safari.

![mm](http://cl.rummel.co/0k010i3R1P23/Image%202017-02-22%20at%208.32.42%20PM.png)

**Comment by mmistakes** [comment]
Looks ok to me on an actual device. I know you have a modified version, sure you have the latest JS and CSS? How does the demo site look to you?

![img_8281](https://cloud.githubusercontent.com/assets/1376749/23241849/b889f642-f943-11e6-87dc-2b56171931bf.PNG)

**Comment by justinrummel** [comment]
Demo site looks fine. Let me check the commit and see if I'm overwriting any of the files, thus missing info.

**Comment by mmistakes** [comment]
Not sure if it's related but on Chrome they're were security warnings that blocked me from even loading your site. Guessing something with your SSL certificate is up.

**Comment by justinrummel** [comment]
I remember you stating that before. Are you in a work environment with an appliance that decrypts TLS for logging?  I enable HPKP so if you are not using "my" cert, it will throw an error that there is a man-in-the-middle.

**Comment by mmistakes** [comment]
Nope not in a work environment this time.

**Comment by justinrummel** [comment]
My issue may be from Cloudflare cache.  I Checked this morning and everything is fine on my iPhone.

For the cert warning, I want to double check as I have moved my site a couple of times so I may not have HPKP correct.  I think you are using Chrome dev, correct?  I may have too many pinned certs.

**Comment by mmistakes** [comment]
Using Chrome 56 (stable non-beta) at home and work in incognito mode to rule out any sort of extension issues. The security warning above shows for both in Windows and macOS on different IPs, so it's not DNS related or some sort of Firewall.

I ran your site through some SSL checkers and everything seemed fine, so not sure what Chrome's issue is.

**Comment by justinrummel** [comment]
Found the solution for Chrome.  B/c I've moved hosting companies and SSL certs... things are "complicated" (moved from Site5 w/ StartSSL => frantech w/ Let's Encrypte => frantech VPS w/ Cloudflare Cert).

solution is to visit: chrome://net-internals/#hsts and in the bottom "Query domain" enter ```www.justinrummel.com```.  You can delete Chrome's cache of the site and then it will work fine.

**Comment by mmistakes** [comment]
Everything related to SSL is complicated and a pain :wink:

Removing your domain cache worked. Sure hope you don't have a lot of Chrome users who cached the old cert... what a pain.
