### ISSUE TITLE
No CSS rendered locally for static sites

### ISSUE THREAD

**Issue by felixhaass** [mmistakes/minimal-mistakes#873]
- [x] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

First off, thanks for the great theme and all the work you've put into this. It is really amazing. Much appreciated.

Here's my issue:

## Environment informations

- **Minimal Mistakes version:** 2.5.2
- **`jekyll` gem version:** 3.4.0
- **Operating system:** Windows 10

---

## Expected behavior

I have this weird problem, where no CSS is rendered for any static pages. Blog posts work fine. 

The issue is similar to issue #637 but I did in fact change the `url:` entry to `url: http://localhost:4000`. The problem occurs both if I use `_pages` plus fixed permalinks (as described [here](https://mmistakes.github.io/minimal-mistakes/docs/pages/) and `/about/index.md/`-style static pages. 

## Steps to reproduce the behavior

I'm only working locally on this and did not push this to GitHub yet, so it's a purely local problem. I've uploaded [a zipped copy of the basic website folder](https://github.com/mmistakes/minimal-mistakes/files/801567/minimal-mistakes-master.zip) with only one post but several non-functioning sites. 

Please let me know if you require more information / files to replicate the issue; any help would be greatly appreciated.

**Comment by mmistakes** [comment]
This is an easy one. For the pages not showing any CSS it's because you're missing the `layout` from their YAML Front Matter. Set that and it'll work. Guessing you'll want to use `layout: single` for the pages, and if they're an archive of documents use `layout: archive`.

**Comment by felixhaass** [comment]
That solved it. I thought the `layout: single` in the `defaults:` was sufficient. Guess I was wrong. Thanks for the quick help!

**Comment by mmistakes** [comment]
You only had the defaults set for posts. You'd have to set them for the pages path (e.g. `_pages`) too and then they should work.
