### ISSUE TITLE
Gallery with varying widths

### ISSUE THREAD

**Issue by annawees** [mmistakes/minimal-mistakes#875]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
---
- **Minimal Mistakes version:**  4.0.10
---
Hey y'all,

I'm trying to get my gallery on my site (annawees.github.io) to vary between a double column width and single column width, similar to the layout used by Refinery 29 (www.refinery29.com). I've edited the archive.scss to the following:

```
 /*
    Grid view================================================= */
 
 .grid__item {
   margin-bottom: 2em;
   .archive__item-title {
     margin-top: 0.5em;
     font-size: $type-size-5; letter-spacing: 2 px;
   }
 
   .archive__item-excerpt {
     display: none;
   }
 
   @include breakpoint ($small) {
        @include span(12 of 12 split);
        .archive__item-teaser {
            max-height: 200px;
       }
   }
 
   @include breakpoint ($medium) {
        @include span(6 of 12 split);
        &:nth-child(3), 
             {width: (12 of 12 split);}    
   }
     
   .page__meta {
     margin: 0 0 4px;
   }

}
```

This worked on sassmeister, but I was not able to reproduce the results on GitHub. Any hints as to what might be the fix?

**Comment by mmistakes** [comment]
Looks to me the CSS you wrote is doing what instructed to do.

Single column (12 of 12) @ `$small` 

![screen shot 2017-02-26 at 8 31 47 pm](https://cloud.githubusercontent.com/assets/1376749/23345881/ac77e400-fc62-11e6-8515-68ea56fb7ed1.png)

and two column (6 of 12) @ `medium` and up.

![screen shot 2017-02-26 at 8 31 55 pm](https://cloud.githubusercontent.com/assets/1376749/23345876/a8a332a8-fc62-11e6-818c-585278b25f3b.png)

Refinery29 looks to me to be using a 4 column layout. If you want to match that then you'd want `span(3 of 12)`.

**Comment by annawees** [comment]
What I was talking about was the intermittent posts that span two columns.

<img width="646" alt="screen shot 2017-02-26 at 8 06 28 pm" src="https://cloud.githubusercontent.com/assets/24393972/23346380/55b6303e-fc5f-11e6-878b-a104a27c0c98.png">

I added the  `&:nth-child(3), {width: (12 of 12 split);}  `but was not able to produce the desired result.

**Comment by mmistakes** [comment]
That'll be really tricky due to the breakpoints. If you look at the compiled CSS it throws in float clears using various `nth-child` declarations which you have to override or else the layout will break. 

You're probably better off looking at flexbox than using Susy's float based grids. But that doesn't have as well off browser support.

**Comment by mmistakes** [comment]
This might give you some ideas https://zellwk.com/blog/susy-gallery-problems/

**Comment by annawees** [comment]
Thanks! I think I'll try to see if I can build with JS.

**Comment by mmistakes** [comment]
Closing. Feel free to re-open with updates or more information if you managed to get this working.
