### ISSUE TITLE
How to set the width of the recent posts to be the full width of the page?

### ISSUE THREAD

**Issue by juliohm** [mmistakes/minimal-mistakes#884]
As you can see on this example, the posts occupy half of the page:

https://juliohm.github.io/blog/

Where could I set this property to make full use of the page width?

**Comment by mmistakes** [comment]
There isn't a single setting for this. You'll have to make some edits the theme's CSS. Depending on your comfort level with that it could really easy or a pain.

The archive styles are in this partial. There are styling declarations for list (think that's what you're using) and grid view.

https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_archive.scss

I'd verify you're using `layout: archive` on your home and blog pages and not `single`. The widths look narrow to me compared to what I have on the demo site.

**Comment by juliohm** [comment]
Thank you @mmistakes I was using `layout: single` instead of `layout: archive in that page. It is looking much better now.

**Comment by DOEHOONLEE** [comment]
Does anybody know how to fix it back to default width? For some reason, mine does not show sidebar with author information and the widened width of post would not come back to normal even after removing "classes: wide"
