### ISSUE TITLE
Warning after renaming index.html to index.md

### ISSUE THREAD

**Issue by juliohm** [mmistakes/minimal-mistakes#885]
Everything is working perfectly except that I get a few warnings when I build the site locally in my laptop:

>Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.
>   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.

I would like to understand what they mean and what should I do to fix them. For instance, some of the icons are not shown locally when I build, I think it may be related?

**Comment by mmistakes** [comment]
I'd suggest giving the Jekyll docs a good looking over and read up on [how pagination works](http://jekyllrb.com/docs/pagination/). The error message pretty much tells you what's going on. 

Jekyll pagination is looking for an `index.html` file in the root of your site. That's likely harmless if you don't care about paginating your home page. My guess you have the pagination settings in your `_config.yml` file which is telling Jekyll to look for `site.paginator` in an `index.html` file that may or may not exist.

Either of those conditions will throw that error.

If you're still having problems then check out the [Jekyll forum](https://talk.jekyllrb.com/). This sort of thing is a general "I have a question about X" with Jekyll and not really specific to the theme. Chances are your question has been asked a few times before and you can find the answer there.

The [issues on the Jekyll repo](https://github.com/jekyll/jekyll/issues) is a good place to search too through closed/open tickets.

**Comment by mmistakes** [comment]
Also just saw the title of this issue. The renaming is the issue. Jekyll's paginator only works with `.html` files as per the docs.

> **Pagination only works within HTML files**
> Pagination does not work from within Markdown or Textile files from your Jekyll site. Pagination works when called from within the HTML file, named index.html, which optionally may reside in and produce pagination from within a subdirectory, via the paginate_path configuration value.

**Comment by juliohm** [comment]
Thank you @mmistakes , totally agree with all the points you raised. Thank you for pointing me to the right places.
