### ISSUE TITLE
Titles of posts which start with a numbering are not rendered properly

### ISSUE THREAD

**Issue by simdevmon** [mmistakes/minimal-mistakes#893]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.3.0
- **`github-pages` or `jekyll` gem version:** 2.5.2
- **Operating system:** Windows 10 Pro

---

## Expected behavior

If I have a posts with a title like this `title: "42. Layout: Header Video"` I would expect to have exactly this title displayed on the post list and on the post itself.

Instead only 1. is displayed 

![2017-03-07_23h40_58](https://cloud.githubusercontent.com/assets/16277781/23681545/a4bdecd0-038f-11e7-8f44-a385af96a337.png)

Which is rendered in a additional `<ol>` tag 
![2017-03-07_23h43_17](https://cloud.githubusercontent.com/assets/16277781/23681614/f6990cf6-038f-11e7-9f22-086f0ceffb72.png)

I could fix this for the post like in `archive-single.html` by replacing `{ title }` with `{{ post.title | escape }}`.

## Steps to reproduce the behavior

Change any post title to start with a numbering like "15. XYZ".

**Comment by mmistakes** [comment]
This is due to Markdown. The theme allows Markdown in titles via the `markdownify` filter Which is converting `n.`  into an ordered list item. Will have to investigate possible solutions. Thinking there's a way to escape those characters so Kramdown doesn't process them.

If not I'll have to add some sort of config to enable/disable Markdown titles which I'd rather not do.

**Comment by mmistakes** [comment]
As suspected there is a way to tell Kramdown to [ignore something](https://kramdown.gettalong.org/syntax.html#extensions).

```yaml
title: "{::nomarkdown}42.{:/} Layout: Header Video"
```

Will give you the output you want.

**Comment by simdevmon** [comment]
Thank you for the quick response. The solution with `{::nomarkdown}...{:/}` worked for me.

**Comment by mmistakes** [comment]
Closing as this appears to be solved.

**Comment by micfan** [comment]
Hi, is there a section to configure this behavior in `_config.yml`

**Comment by mmistakes** [comment]
@micfan Don't think so. This is a question for [Jekyll core](https://github.com/jekyll/jekyll).

**Comment by micfan** [comment]
ok, thanks
