### ISSUE TITLE
Links with _blank attribute in navigation.yml

### ISSUE THREAD

**Issue by marathon67** [mmistakes/minimal-mistakes#896]
- [ x] This is a question about using the theme.

---
Hello
Is it a way to set a "_blank" attribute to the links in navigation.yml ?
And thanks a lot for that splendid theme.

**Comment by mmistakes** [comment]
Not without you modifying the theme directly. You could [add it to this line](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/masthead.html#L13).

**Comment by marathon67** [comment]
Hello Michael


Thanks for that astounding fast answer. I will try to add a  - target: attribute to navigate.yml and modify my own version of the theme.


Bien cordialement.

[http://formation.crdp-strasbourg.fr/webdoc/photos_atelier/logo_mail.jpg]

Pierre Kessler
Directeur Projets Numériques
Direction territoriale Grand Est
Académies de Nancy-Metz, Reims et Strasbourg
---
pierre.kessler@reseau-canope.fr
23 rue du Maréchal Juin
T. 03 88 45 50 42 ou 06 07 34 87 17
CS 20279 67007 Strasbourg Cedex
FRANCE

________________________________
De : Michael Rose <notifications@github.com>
Envoyé : vendredi 10 mars 2017 15:21
À : mmistakes/minimal-mistakes
Cc : KESSLER Pierre; Author
Objet : Re: [mmistakes/minimal-mistakes] Links with _blank attribute in navigation.yml (#896)


Not without you modifying the theme directly. You could add it to this line<https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/masthead.html#L13>.

-

**Comment by abuyukcakir** [comment]
> Not without you modifying the theme directly. You could [add it to this line](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/masthead.html#L13).

For those who are wondering how to do this, the way I did was as follows:

Find the line in that masthead.html that creates the link, which is something like:

`<li class="masthead__menu-item"><a href="{{ domain }}{{ link.url }}">{{ link.title }}</a></li>`

Let's say you had **title** and **url** fields for your navigation entries previously, and want to add **target** field now. To this line (which creates your anchor element), you add your new attribute that you will fill in navigation.yml.

`<li class="masthead__menu-item"><a href="{{ domain }}{{ link.url }}" target="{{ link.target }}">{{ link.title }}</a></li>`

Of course, after this, whichever entry you want to have it opened in new tab, you add the following line to that entry that has "_blank" as its field. For instance:

```
  - title: "CV"
    url: /files/personal/cv.pdf
    target: "_blank"
```
