### ISSUE TITLE
Odd condition on "You May Also Enjoy" translated string displaying

### ISSUE THREAD

**Issue by Bounga** [mmistakes/minimal-mistakes#900]
- [ ] This is a question about using the theme.
- [X] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.3.0
- **`github-pages` or `jekyll` gem version:** 3.4.2
- **Operating system:** OS X 10.11.6

---

## Expected behavior

The string "You May Also Enjoy" string or it's translation should always be displayed before related posts section. It should be displayed whether you have a translation file available or not and even if you have a translation file without the matching key (`related_label`).

As of today, if you don't have a translation file (that's how I understood that the translations wasn't bundled with the gem) this string won't display so it will leave the "related posts" section without any description what could be confusing for the reader.

It's because of the conditional available here: https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L66

I think that we don't want this test at all since the line in the condition has a default value.
 
## Steps to reproduce the behavior

Pretty simple:

- create a new Jekyll site
- add the minimal-mistakes gem
- enable related posts
- add multiple posts
- run `jekyll s`
- go to the latest  post
- check "related posts" section

The related label will be missing.

![capture d ecran 2017-03-15 a 10 51 55](https://cloud.githubusercontent.com/assets/25862/23942696/6e379510-096d-11e7-8942-913bb3295cd6.png)

Add the translation file with the key and then it displays as intended:

![capture d ecran 2017-03-15 a 10 53 36](https://cloud.githubusercontent.com/assets/25862/23942787/b19b28da-096d-11e7-86db-5a94e753635c.png)

If it helps I can PR a patch. Oh and BTW you theme is *really awesome*

**Comment by mmistakes** [comment]
Looks like a legit bug to me. If you want to submit a PR against the `develop` branch that removes the `{% if site.data.ui-text[site.locale].related_label %}` around that heading I'll get it merged in.

**Comment by Bounga** [comment]
Here it is https://github.com/mmistakes/minimal-mistakes/pull/901
