### ISSUE TITLE
Embedding videos

### ISSUE THREAD

**Issue by rvalenzuelar** [mmistakes/minimal-mistakes#91]
I haven't been able to insert a video so far. I'm using:

<pre><code>
&lt;iframe src="https://www.youtube.com/watch?v=MU9sobaVx6I" width="560" height="315" frameborder="0"&gt; &lt;/iframe&gt;
</code></pre>

I've tried with and without whitespace between the tags. I also added the fitVids script as indicated in their website, but still the video doesn't render.

**Comment by sanderrzkelly** [comment]
There’s another way to adjust the size of embedded Youtube videos on you posts. You can use a plugin called YT Portrait Video Embed. This plugin is totally free & easily available on wordpress. With the help of this, you can easily embedded a video to your posts. 

https://wordpress.org/plugins/yt-portrait-video-embed/
