### ISSUE TITLE
Multiple languages support

### ISSUE THREAD

**Issue by bastoGrande** [mmistakes/minimal-mistakes#917]
- [x] This is a feature request.
---
Based on [this](https://www.sylvaindurand.org/making-jekyll-multilingual/) beautiful post (especially the "**Flexibility**" point and the **language selector** are important to me) I was dreaming about using your great theme with at least two languages. 

I recon I could implement my own solution, but thought that you (@mmistakes) or others could implement it much cleaner as I ever could implement it (and keep it up to date from time to time). I'm a backend dev, never had a passion for the frontend, just want to use it. 😉 

I'm of course willing to tip, because I know how much time can get wasted with this kind of task.

If this a double, I'm sorry, caues I didn't found a similar issue.
-bg

**Comment by bastoGrande** [comment]
Ah forgot to write, that I'm totally not aware how this could behave with comments or permalinks or sitemaps or feeds or tags or ...

**Comment by mmistakes** [comment]
Supporting multi-language content is out of the scope of what I'm doing with the theme. There's really no standardization on how best to do it. 

It's even harder to bake it all into the theme without over complicating things for the average user... someone who is only ever going to write content in a single language.

There's several plugins out there that propose to do this. Along with even more blog posts on the method's people are using. Until Jekyll bakes in support for this natively I don't I want to touch it. A biggie would be for them to support localizing dates without needing to resort to a bunch of [messy Liquid code](https://www.sylvaindurand.org/making-jekyll-multilingual/#translation-of-dates).

For more context here's some older issues asking for the same thing #612 and #50.

**Comment by bastoGrande** [comment]
thanks for the quick reply! ok.. so I'll do it my own.. 😕

**Comment by eric-lee-ltk** [comment]
@bastoGrande Did you finally make it out? If you did, can you share how to do it? Thanks.
