### ISSUE TITLE
Open Graph doesn't fetch the property

### ISSUE THREAD

**Issue by milkyklim** [mmistakes/minimal-mistakes#925]
When I am trying to share the [page](http://milkyklim.com/12-things-to-do-in-aachen/) on facebook the Open Graph throws an [error](https://developers.facebook.com/tools/debug/og/object/?q=http%3A%2F%2Fmilkyklim.com%2F12-things-to-do-in-aachen%2F). 

> The 'og:type' property is required, but not present.

I checked the page and `og:type` is definitely there.

My best guess is that the problem arises due to the "https://" redirect. Any way to fix this problem? 

As a side note, Twitter Cards look fine.

**Comment by mmistakes** [comment]
I'm not seeing any errors in the open graph debugger. There are some warnings, but those shouldn't affect sharing.

https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fmilkyklim.com%2F12-things-to-do-in-aachen%2F

![screen shot 2017-03-28 at 6 55 02 am](https://cloud.githubusercontent.com/assets/1376749/24401742/97eb2776-1383-11e7-9727-16e085353370.png)

**Comment by milkyklim** [comment]
The canonical link in open graph was wrong due to the redirect -- had **https** instead of http. But now everything looks fine. 

Thanks for looking into this!
