### ISSUE TITLE
Use last_modified_at instead of or in addition to modified?

### ISSUE THREAD

**Issue by lunaryorn** [mmistakes/minimal-mistakes#929]
- [x] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

Minimal Mistakes uses the `modified` property of a page for the ["Updated:" footer in single layout](https://github.com/mmistakes/minimal-mistakes/blob/805dad00775ad5e36b1e8b7ac8d8570242d72ef4/_layouts/single.html#L46).  However, jekyll-feed uses [last_modified_at](https://github.com/jekyll/jekyll-feed/blob/c048229b94c803b1b5d1f5597e2a1820a23977a9/lib/jekyll-feed/feed.xml#L40) which can be set automatically by a [Jekyll plugin](https://github.com/gjtorikian/jekyll-last-modified-at).

So, currently I have to set both "modified" and "last_updated_at" if I'd like to have correct dates on the page as well as in the atom feed.  

Would it be possible for Minimal Mistakes to use "last_updated_at" instead of or in addition to "modified"?

**Comment by mmistakes** [comment]
Good suggestion. I made the switch to `last_modified_at` recently on my personal site for this exact reason. Total meant to update MM to user it to. Thanks for the reminder!

**Comment by lunaryorn** [comment]
@mmistakes Thanks.  I made #930 to replace `modified` with `last_modified_at` :)
