### ISSUE TITLE
Greedy nav not working in Chrome for Mac or iOS.

### ISSUE THREAD

**Issue by twhite96** [mmistakes/minimal-mistakes#932]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 
4.3.1
- **`github-pages` or `jekyll` gem version:** 
`jekyll -v 3.4.3`
- **Operating system:** 
macOS 10.12.4
---

## Expected behavior

Greedy nav appears then disappears, Chrome 57, desktop and on iOS 10.3
## Steps to reproduce the behavior

Repo: https://github.com/twhite96/twhite96.github.io

  Describe the steps you took for this problem to exist. Such as you cloned the theme, customized `_config.yml`, added your own posts, and started up a Jekyll server locally.
I've added some custom js with Bigfoot which doesn't seem to be the issue, I don't think. It worked when I first added it.

  If an error occurred on GitHub Pages when pushing, please build locally and provide a complete log by running `bundle exec jekyll --trace --verbose` and including this output in the filed issue.

  Screenshots can also be included if they help illustrate a behavior.

Dev Tools: 

![screenshot2017-04-04_01-28-50_am](https://cloud.githubusercontent.com/assets/7698292/24682340/202f04fc-1967-11e7-868f-633b0807bfb9.jpg)

If you notice it has hidden button count as "0". Not sure why.

iPhone Nav:

![file apr 04 1 29 17 am](https://cloud.githubusercontent.com/assets/7698292/24682348/34d7aa26-1967-11e7-9ed2-4327cb72e98d.png)

**Comment by mmistakes** [comment]
Try updating the theme to the latest. According to the source you're on a much older version. 

For example in your HTML source I see this which tells me parts of your site are using outdated files:

```html
<!doctype html>
<!--
  Minimal Mistakes Jekyll Theme 4.2.2 by Michael Rose
  Copyright 2017 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE.txt
-->
```

CSS and JS are that way too. Probably something is out of sync when you customized the scripts and stylesheets to add Lunr search and BigFoot.

If you look at the demo site you'll see how the source and various assets have the version number printed at the top.

HTML source:

```html
<!--
  Minimal Mistakes Jekyll Theme 4.3.1 by Michael Rose
  Copyright 2017 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE.txt
-->
```

[Main CSS source](https://mmistakes.github.io/minimal-mistakes/assets/css/main.css):

```css
/*!
 * Minimal Mistakes Jekyll Theme 4.3.1 by Michael Rose
 * Copyright 2017 Michael Rose - mademistakes.com | @mmistakes
 * Licensed under MIT (https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE.txt)
*/
```

[Main JavaScript source](https://mmistakes.github.io/minimal-mistakes/assets/js/main.min.js):

```js
/*!
 * Minimal Mistakes Jekyll Theme 4.3.1 by Michael Rose
 * Copyright 2017 Michael Rose - mademistakes.com | @mmistakes
 * Licensed under MIT
 */
```

I'd suggest either backtracking what changes you made and comparing against the MM repo. I recently rebuilt the greedy nav so [these commits](https://github.com/mmistakes/minimal-mistakes/issues/836) are a good place for you start comparing against.

**Comment by twhite96** [comment]
My problem is that I used the gem on GitHub pages. I didn't know you couldn't do that so every time I update the site on another server, it *still* has the GitHub Pages version I used. Anyway to fix this without blowing up my site?

**Comment by mmistakes** [comment]
The Ruby gem bundles in `_layouts`, `_includes`, `_sass`, `assets/css/main.scss`, and `assets/js`. If you're using the theme as a gem then you have no need for those files and they can be removed. 

If you keep them they will override the ones bundled in the gem which is probably why things aren't working. Just keep the files you specifically customized, but make sure they have any upstream updates as well. 

Other than that I don't really have any other advice.

**Comment by twhite96** [comment]
Fixed. Thanks for your help.
