### ISSUE TITLE
Sidebar reformatting and disqus comments not working

### ISSUE THREAD

**Issue by emma-ladouceur** [mmistakes/minimal-mistakes#938]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:* Not sure how to get this information... sorry* 
- **`github-pages` or `jekyll` gem version:* 4.3.1....? also not sure- gems are up to date though* 
- **Operating system:* OSX 10.12.3*
- **Google Chrome:* Version 57.0.2987.133 (64-bit)*

---

## Expected behavior

 -  Main Issue: Sidebar When view the page in Firefox i see what i intend to see, which is my sidebar correctly formatted and what i used to see in google chrome;
<img width="1280" alt="screen shot 2017-04-06 at 3 38 16 pm" src="https://cloud.githubusercontent.com/assets/13708013/24758348/6a27b9c4-1ae2-11e7-8a05-cad5ec91539f.png">

When I view my page in chrome now i see this, with the sidebar changed to a compressed title bar:
<img width="1280" alt="screen shot 2017-04-06 at 3 38 00 pm" src="https://cloud.githubusercontent.com/assets/13708013/24758378/7d9a0c28-1ae2-11e7-8734-54fec30ea4c3.png">

But when i view your about page with  a sidebar i see what i expect;
<img width="1280" alt="screen shot 2017-04-06 at 3 37 55 pm" src="https://cloud.githubusercontent.com/assets/13708013/24758256/1d37ceba-1ae2-11e7-9200-6417a82fed61.png">

- Second issue: Disqus comments: I expect to see the disqus comments display at the bottom of this post.
<img width="1280" alt="screen shot 2017-04-06 at 4 06 39 pm" src="https://cloud.githubusercontent.com/assets/13708013/24758564/0de8e52e-1ae3-11e7-97b6-205e39202dc6.png">

## Steps to reproduce the behavior
Last time i worked on the site, i was not having these issues, which was maybe 1.5-2 months ago. I have not made any changes myself since then, so i think its maybe to do with an update, but im not quite sure i understand the steps for updating when I have customised  a few things.

The Disqus comments worked before, but they were having some trouble loading last time i worked on it, sometimes coming up with an error to say try again later.

Heres the repository with current changes:
https://github.com/emma-ladouceur/conservation

*Please note its still in draft form with all your sample posts in it.

Thanks!

**Comment by mmistakes** [comment]
Since the sidebar on the demo site is working as expected, I suspect something broke with your fork. Did you make any changes to the layouts or includes? That would be my guess.

Quick way to check your version is to view source. I think you have an older version of the theme because you don't even have a version number. If you look at the demo site you'll see this (which is the latest version)

```html
<!--
  Minimal Mistakes Jekyll Theme 4.3.1 by Michael Rose
  Copyright 2017 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE.txt
-->
```

And since you're hosting with GitHub there's really no easy way to update other than copying all of the files from the MM repo to yours. Which can get tricky if you made any changes. Here's my suggestions on how to [handle updates](https://mmistakes.github.io/minimal-mistakes/docs/upgrading/). Things are much easier if you didn't modify any of the core theme files.

**Comment by mmistakes** [comment]
RE: Disqus not working. You don't have a valid shortname in `_config.yml`. Consult the [configuration docs](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#disqus) which has a link to an article on Disqus' site for figuring out your shortname.

**Comment by emma-ladouceur** [comment]
Thanks for this, I've resolved everything.
