### ISSUE TITLE
Adding support for W3C web annotations via txtpen

### ISSUE THREAD

**Issue by kevchn** [mmistakes/minimal-mistakes#947]
- [ ] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

**Comment by mmistakes** [comment]
Can you give some more detail? I'm not exactly sure what you're looking for here.

**Comment by kevchn** [comment]
Making it easier to integrate web annotations found here: https://jekyllrb.com/docs/extras/

**Comment by mmistakes** [comment]
You can do this quite easily by just adding the script embed here [`_includes/scripts.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/scripts.html)

Or to one of the the custom head/footer includes created exactly for the purpose of adding 3rd party scripts and assets. 

- [_includes/head/custom.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/head/custom.html)
- [_includes/footer/custom.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/footer/custom.html)
