### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by emma-ladouceur** [mmistakes/minimal-mistakes#949]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** 

---

## Steps to reproduce the behavior
Just wondering if you have any advice on getting a favicon.ico to appear. Ive tried just putting it in the main directory,  and it shows up on my localhost, but not when published.

Ive tried other peoples advice  of putting  a " < link rel="shortcut icon" href="/assets/images/favicon.ico"  / > "on a page, but dont think that works either

Thank you!!

**Comment by mmistakes** [comment]
I suggest using something like the [Favicon Generator](http://realfavicongenerator.net/). It will create several favicons with instructions on how to load them. Essentially you drop all the icons into your site and then paste in some HTML in the `<head>`.

The theme has a file just for doing this which you can add here: [`/_includes/head/custom.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/head/custom.html)

This question has been asked a few times before so if you need more guidance give [these issues](https://github.com/mmistakes/minimal-mistakes/issues?q=favicon+is%3Aclosed) a look. You can also Google around as this is a common web development need and isn't specific to this theme or Jekyll.

**Comment by emma-ladouceur** [comment]
Ok great advice. Sorry i tried searching earlier but didn't realize i had limited to my search to issues that were still open so didn't see these.

Ive used the favicon generator now and tried to follow your advice and the other posts as best i could but still think ive gone wrong somewhere.

Ive put the files in the root directory, but in some posts you also said assets/images so i placed them there too. Not sure which is correct.

I pasted the code the generator spit out into /head/custom.html but think it must not be correct. The icon shows up in my localhost:4000 but not on the published version. Heres how my custom.html looks;





<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">



Thank you!!

**Comment by mmistakes** [comment]
If you fire up your browser's web dev tools it'll show you if there are any bad paths. You can place the favicons wherever you want, you'll just need to update the `href` path in those `link` elements to match. If you put them in `/assets/images` then you'll want paths something like: `href="/assets/images/apple-touch-icon.png"` or `href="{{ apple-touch-icon.png | prepend: '/assets/images' | absolute_url }}"`.

Also browsers tend to cache favicons so they don't always update right away. The [Real Favicon site](http://realfavicongenerator.net/) has a tool to verify on their homepage to check if you've loaded favicons correctly.

Closing as this isn't a theme issue. If you're still having troubles I'd suggest poking around [Stackoverflow ](https://stackoverflow.com/search?q=favicon)or similar web dev forums for help.
