### ISSUE TITLE
github pages site does not format but local does

### ISSUE THREAD

**Issue by aguang** [mmistakes/minimal-mistakes#951]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 4.3.1
- **`github-pages` or `jekyll` gem version:** 134, 3.3.1 (but I have activated 3.4.3)
- **Operating system:** Mac OSX

---

## Expected behavior

I expected to see my github pages site (`aguang.github.io`) to look the same as on my local host. When I run bundle exec jekyll serve, my page at localhost:4000 looks fine and like the minimal mistakes theme. However when I push my changes to aguang.github.io, the page layout looks broken; all my links and text are there but there is no formatting.

## Steps to reproduce the behavior

Link to public repository: `https://github.com/aguang/aguang.github.io`

I cloned the theme, customized _config.yml, added two pages (About, and Research), and was able to run bundle exec jekyll serve after installing and updating all the gems.

My commit history will look strange because I spent a lot of time trying to figure this out myself - I tried manually copying over the _site pages, I tried making a Rakefile and using travis-CI, none of it seemed to work. I can't figure out why my page will load fine locally but not on GitHub Pages.

I don't think this is relevant but in addition to this issue I have been receiving Warning messages about my build:

> The page build completed successfully, but returned the following warning:
> 
> You are attempting to use a Jekyll theme, "minimal-mistakes-jekyll", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

**Comment by mmistakes** [comment]
3rd party themes installed as a Ruby gem aren't currently supported when you host with GitHub Pages.

You either have to fork the theme and use it that way, build it locally and push up just the contents of your `_site` folder, or use a CI service to deploy it for you to GH.

https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#github-pages-compatible-method
