### ISSUE TITLE
grid view from custom sidebar navigation menu

### ISSUE THREAD

**Issue by MaCXyLo** [mmistakes/minimal-mistakes#953]
Hi,
i want to create a grid view from the links of a custom sidebar navigation menu.
the links at the custom sidebar navigation menu have overlay_images.
Found this piece of code.

```
<div class="grid__wrapper">
  {% for post in pages.category.product %}
    {% include archive-single.html type="grid" %}
  {% endfor %}
</div>
```
I created a products folder in the _pages folder and created several markdown files.
have not the right idea at the moment to do that.
Can anybody help? 

Kind Regards,

**Comment by mmistakes** [comment]
The archive single include has a `type` flag on it. If you call it with `{% include archive-single.html type="grid" %}` it'll output the HTML needed for a grid element.

You'll also need to wrap it with a `for` loop that has a `post` object... similar to the example above. If you look at the [`_includes/archive-single.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/archive-single.html) you'll get a better idea of what actual YAML variables it uses. 

The grid images are assigned with `header.teaser` and not the overlay images. You can see an [example here](https://raw.githubusercontent.com/mmistakes/minimal-mistakes/master/docs/_posts/2016-02-24-welcome-to-jekyll.md) which is used to build the "related posts" module at the bottom of a post.

![screen shot 2017-04-16 at 9 26 05 pm](https://cloud.githubusercontent.com/assets/1376749/25076025/5277fbc0-22eb-11e7-83ea-ec58dc4b7ebb.png)

**Comment by mmistakes** [comment]
Feel free to reopen if you're still having trouble and can provide additional info or a link to a public repo to better assist.
