### ISSUE TITLE
Masthead navicon shows inverted behavior

### ISSUE THREAD

**Issue by satwikkansal** [mmistakes/minimal-mistakes#975]
The dropdown list of the navicon disappears when we click elsewhere on the screen, but the navicon (which looks like "X" after clicking) remains "X" resulting in inverted behavior.

![image](https://cloud.githubusercontent.com/assets/10217535/25456941/fde17e20-2ac3-11e7-80e5-73252731e4dc.png)

![image](https://cloud.githubusercontent.com/assets/10217535/25456951/08fe74ca-2ac4-11e7-9c3e-22d0e9075cc1.png)

**Comment by mmistakes** [comment]
Good catch @satwikkansal
