### ISSUE TITLE
cannot load such file -- mercenary/program (LoadError)

### ISSUE THREAD

**Issue by vishnu667** [mmistakes/minimal-mistakes#98]
Is there a Fix for this issue works fine on gitHub but am unable to run the same locally 

WARN: Unresolved specs during Gem::Specification.reset:
      redcarpet (~> 3.1)
      jekyll-watch (~> 1.1)
      classifier-reborn (~> 2.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.4/lib/mercenary.rb:20:in `program': cannot load such file -- mercenary/program (LoadError)
    from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.0/bin/jekyll:20:in`<top (required)>'
    from /usr/local/bin/jekyll:23:in `load'
    from /usr/local/bin/jekyll:23:in`<main>'

**Comment by icaroabreu** [comment]
But for me it didn't help at all. Same error.

**Comment by mmistakes** [comment]
@icaroabreu https://github.com/jekyll/jekyll/issues/3084

**Comment by OOTS** [comment]
Have you installed the mercenary package of ruby? For me `sudo apt-get install ruby-mercenary` fixed the problem. (Using Ubuntu 14.10.)
