### ISSUE TITLE
Sidenotes

### ISSUE THREAD

**Issue by bastoGrande** [mmistakes/minimal-mistakes#986]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Question
I thinkt this is a easy and quick question. Is there already a way to use sidenotes as you have them on your [private page](http://mademistakes.com/)? When I tried the notation from your page, it just 

`**some text**[^WWW]` 
`[^WWW]`

resulted as a footnote. So I thought something is implemented, but I couldn't find the footnotes either in the documentation. So it might be a relict or the documentation is missing something?

Here the sidenote I'm talking about: 
![sidenote](https://cloud.githubusercontent.com/assets/15093263/25644575/a91c2bce-2f7d-11e7-8fff-1ffbddc77f64.PNG)

**Comment by mmistakes** [comment]
This theme doesn't support footnotes like I have them on my personal site.

I'm using a JavaScript plugin called [Bigfoot.js](http://bigfootjs.com/) to do them so they pop-up. You'd have to customize the Minimal Mistakes theme a little to do it.

**Comment by bastoGrande** [comment]
Thanks!

Alright, so I'm going to implement on my own.. :)
Or do you plan to integrate them into the theme in the future as well?

**Comment by mmistakes** [comment]
No plans right now. Trying to keep it to the minimum.

**Comment by bastoGrande** [comment]
Ok, thanks. 
Good luck! 😉
