### ISSUE TITLE
comment does not show in pages

### ISSUE THREAD

**Issue by banpie** [mmistakes/minimal-mistakes#995]
## Environment informations

- **Minimal Mistakes version:** 4.4.1
- **`github-pages` or `jekyll` gem version:** 3.6 
- **Operating system:**  mac 

---

## Expected behavior

show comment on pages

## Steps to reproduce the behavior

The disqus comment works fine in post, but does not show in pages.

btw, I have add the `comments= true` in YAML in `pages/about.md`.

Here is the [About Page](banpie.github.io/about/)

Here is my [Jekyll Repo](https://github.com/banpie/banpie.github.io)

Thanks!

**Comment by mmistakes** [comment]
Looking at your repo you don't have `pages: true` in it's YAML Front Matter. That's why comments are not displaying.

This is what you have.

```yaml
---
title: 关于
permalink: /about/
date: 2015-07-23
---
```

**Comment by banpie** [comment]
Thanks, my bad... forget to push local repo to live repo.

Get fixed!
